### ISSUE TITLE
Admin should be able to upload/ replace images(Is this still relevant)

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#1]
If a user reports a problem with an image, the admin should be able to go to the image file screen and upload a new replacement image.

**Comment by edickens** [comment]
Yes.  Part of the image server maintenance.  At present I have to upload all images (have done a few thousand these last couple of weeks).  We will need full maintenance of the set of images.

**Comment by edickens** [comment]
Does this need to be approved and included as a function in V1.5?

**Comment by richpomfret** [comment]
Later (down the road still).

**Comment by edickens** [comment]
Or does thi need to come first?
I am uploading new images now and they will need IGs and must match the County/Place/Church and a Register Type and a Source need to be created if necessary.
At present Bev has created Register Types if they is not one to match, and this will need to continue if we are to avoid having images with no links to the database.
So do we need the image upload Action now which will ensure that the images are properly linked and indexed?  I don't think it is a lot of work as Bev has done the basic work.
I can continue to use BitKinex to upload images, but cannot guarantee that they match and how will the indexes be created?
The Image Upload Action needs to be Management only for now, but should included the need to create Register Type, Source and IG entries.

**Comment by Captainkirkdawson** [comment]
This has been incorporated in the current version of the image server software
