### ISSUE TITLE
The ISP iinet.net.au does not seem to like us

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1001]

**Comment by edickens** [comment]
Bouncing emails are starting to come to me and I've had a few from yesterday's message.  But many are for this ISP.
I have checked one and messages from the SC get to this correct address.
But I have not had any bounced emails from file uploads, and some of these which bounced are transcribing.  Those who have not uploaded recently I am making Inactive.

**Comment by Captainkirkdawson** [comment]
See 978.
As part of that process we now send bounced messages back to the sender. Previously they were ignored. So it is now up to the sender to take what ever action is appropriate including setting the flag for invalid email

**Comment by edickens** [comment]
Yes.  I am taking the necessary action.  But emails from the SC get 
through but not from the server.  There is an ISP blocking problem. 
Blueyonder and now telkomsa.net in South Africa seem to be blocking us.  E

**Comment by Captainkirkdawson** [comment]
Be careful of your statement "blocking us"

The updated message send enables you to send messages either from your address or the default freereg-contacts@freereg.org.uk address. If you are getting bounces back in your email address then it is you who is being blocked

**Comment by PatReynolds** [comment]
Lemon may be able to help with resolving this issue.

**Comment by edickens** [comment]
They were sent from the default and returned to
    freereg.edickens+REG@gmail.com
    
    On 30/10/2016 16:44, Kirk Dawson wrote:
    
      Be careful of your statement "blocking us"
      The updated message send enables you to send messages either
        from your address or the default freereg-contacts@freereg.org.uk
        address. If you are getting bounces back in your email address
        then it is you who is being blocked
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #1001: Be careful of your statement \"blocking us\"\r\n\r\nThe updated message send enables you to send messages either from your address or the default freereg-contacts@freereg.org.uk address. If you are getting bounces back in your email address then it is you who is being blocked"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/1001#issuecomment-257162245"}}

**Comment by edickens** [comment]
Many more have come in and these are from people who uploaded recently, 
so they would have got the uploaded confirmation emails. I'm not doing 
any more until the problem is identified.  E
