### ISSUE TITLE
ASAPs running at the same time can interfer with each other

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1007]
Something is not as anticipated with the performance current database. 
For most of the time weare seeing an overall reduction in search_query create from about 3.5 ms to 2.9ms but we are seeing the occasional massive spike that lasts for 10 minutes where it looks like the database is not responding. on the slaves eg 14;40 GMT on 10 Nov. Colobus was fine but ALL 4 slaves were essentially unresponsive.
What was colobus sending to the slaves that seemed to lock the database

**Comment by Captainkirkdawson** [comment]
All servers including colobus show a 30 minute write period tarting at 14:40.

**Comment by Captainkirkdawson** [comment]
Think I see a possible hint of a clue. There were 5 ASAPs submitted over a very short period starting at 14:18,, 3 from one user jmh. All 3 were for ESS, Great Easton, St John and St Giles, Parish Register The first created a new batch of

**Comment by richpomfret** [comment]
In terms of analysing the issue here, is this something Lemon can assist with?

**Comment by Captainkirkdawson** [comment]
perhaps from an overall systems perspective but not from an internal REG or Mongodb one but any observations are good

**Comment by Captainkirkdawson** [comment]
Similar spike when a new batch was created at the same time that another batch but differenent place was being updated

**Comment by edickens** [comment]
Do you have any record by record delay on ASAP as you have (had)
    overnight?  I think this would be acceptable.  They will get the
    email when it is done.  E
    
      On 11/11/2016 23:09, Kirk Dawson wrote:
    
    
      Similar spike when a new batch was created at the same time
        that another batch but differenent place was being updated
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #1007: Similar spike when a new batch was created at the same time that another batch but differenent place was being updated"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/1007#issuecomment-260076764"}}}

**Comment by Captainkirkdawson** [comment]
Confirmed that we need to investigate why replication has difficulty on batch creation

**Comment by Captainkirkdawson** [comment]
2 ASAPs running at the same time on test3 caused a system crash over both tring to update the plae+cache at the same time

**Comment by Captainkirkdawson** [comment]
Replaced by 1053
