### ISSUE TITLE
New field for Register Type (post #809)

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1009]

**Comment by edickens** [comment]
The Register Type needs to be a new field when uploading a file.  It should be in the header.  At present it is added to each Church name, but we should get away from this.  It has its own field on the server, but we cannot upload to it.  E

**Comment by Sherlock21** [comment]
I support this. Especially if it comes complete with a once-off update of all the existing files and the Way CC's can change a Register type without going round the houses of the present Relocate Everything.

**Comment by Captainkirkdawson** [comment]
Location information does NOT come from the header. Location information is in the record. So the Register Type would have to be in the record too. Implementation is dependant on 809 the flexible CSV format and on a WinFreeREG modification

**Comment by Sherlock21** [comment]
For me, I don't mind where it goes, so long as we get to the position of a single field for each unrelated element. - Grouping with the church name was only a temporary expedient in F1, in the first place.

**Comment by Captainkirkdawson** [comment]
Implemented as part of Flex CSV
