### ISSUE TITLE
Invalid token on setting password - new volunteer

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1012]

**Comment by edickens** [comment]
We have had a new volunteer who has had problems registering as he gets "Reset password token is invalid".   See comment 57381777 of 27 October.
But we think this was while maintenance was taking place.  So the point I'm making is that when shutting down for maintenance we also need to shut the "Volunteer" button or/and give a useful reply.

**Comment by Captainkirkdawson** [comment]
Could the story be amended to reflect that situation. Your analysis is likely correct as the volunteer would never have got far enough

**Comment by edickens** [comment]
Sending a password reset email has solved the problem.   So it is the report saying "invalid token" which is confusing.  The reason is most likely that it was out of time.  So a message to that effect would avoid the confusion.  TY  E

**Comment by PatReynolds** [comment]
See also #1021

**Comment by PatReynolds** [comment]
See #864 for the latest on this issue
