### ISSUE TITLE
Provide time of uploading as part of the overnight processing report?

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1015]

**Comment by edickens** [comment]
Can the time of uploading be added to the information as part of the overnight processing report?  At present it is just the time of processing.  I ask because I am helping someone find a problem with a file, but it still has problems and I can't easily see if it was uploaded before or after I advised the correction to be made.  The file was completely rejected so I don't think I can find this information even if I go into the website.  TY  E

**Comment by Captainkirkdawson** [comment]
Why not look in the attic for the userid. 
The time that the previous version was put into the attic is the time of the  replace

**Comment by edickens** [comment]
Yes, I know that I could find the time, but it is more convenient if it 
is with the upload information.  Not really important, just useful.  E

**Comment by edickens** [comment]
Will this be needed if Kirk's queuing system is introduced?

**Comment by Captainkirkdawson** [comment]
New processing process in use

**Comment by edickens** [comment]
Is that why I am getting daytime FreeREG Update Processing Reports with 
no entries?

Eric J Dickens

**Comment by Captainkirkdawson** [comment]
No idea

**Comment by Captainkirkdawson** [comment]
There is no overnight processing or report
