### ISSUE TITLE
The Tool to Change Place Name  does NOT ripple through to the files

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1017]

**Comment by Sherlock21** [comment]
I re name the Place of SOM / Downton (Shepton Mallet) yesterday ( 19 Nov 2016) do become Downton (Chilcompton) using the tool : change Place Name. there was a church and  batches attached.
The place name changed and the system message said to the effect that: changed OK. but looking at the files attached, these still showed the Old place name.
I suspected that this key be one of those tasks that fought up overnight. so checked again this morning and the record files are still showing Downton (Shepton Mallet)

**Comment by CommsCoord** [comment]
I am not sure if the same applies but when we create a new church (say
because the name of the original was misspelled) we then have to move the
files over one by one using the relocate tool. Would that not have been the
same principle here?​

_________________________________________________________________________________

Sandra Adams-West
*FreeREG Communications Coordinator*
*__________________________________________________________________________________*

**Comment by Sherlock21** [comment]
Thanks for that comment, Sandra. But this was an all embracing tool for me, where all the churches and their files all changed in the one (massive) move - for use a t quiet times because if the impact.. It did once work. I have also discovered there is a strand effect of Search results too ( see next item)

**Comment by Captainkirkdawson** [comment]
Eric. Can you please check the mod made to test3
Sandra you can use the relocate tool to relocate incorrectly named churches to the correctly named church and it will move all files at once

**Comment by CommsCoord** [comment]
Great! Did not know that.​

_________________________________________________________________________________

Sandra Adams-West
*FreeREG Communications Coordinator*
*__________________________________________________________________________________*

**Comment by Sherlock21** [comment]
Testing WRY / Bardsey / All Hallows church/ PR [ it has 1 small file.
The Place name changes correctly in the Active Places list - to BardseyTwo.
and when viewing the file details, it  has changed there.

but viewing on the church file name for the list of Registers it DOES NOT change ( screen copy attached)
![bardseytwo_church](https://cloud.githubusercontent.com/assets/9368704/20477003/9c42d9a2-afcb-11e6-9e55-ad15bbb47e1b.jpg)

**Comment by Captainkirkdawson** [comment]
That is because the church location field is NOT the place and never was . The church location field is an independent field to state the location of the church should the coordinator choose to so do. It is like the church website, notes and denomination fields.You can see that the church is in the place name of BardsleyTwo from the heading.

**Comment by Sherlock21** [comment]
But it gets populated automatically, whether you want it or not, when one creates a new church.

SO if its not actually linked thereafter to the Place, can you stop creating this Churches' Place Name in the first place please?

It only becomes an issue, when the Place name is changed i agree. - but as there are more places "renamed", its confusing.

**Comment by Sherlock21** [comment]
I tried editing the now-wrong place name in the church details and Edit Headers does not do it.

so I tried Relocate this Batch,  as its the only other tool I have to correct this Church location.
This crashed when i had set all the new names, and hit: GO. the system msg was Sorry something seems to have gone wrong.

**Comment by Captainkirkdawson** [comment]
Saw the crash;  nothing related to this issue
The church location issue is separate and distinct. Needs a new story.
I believe the relocation propagation is fixed

**Comment by Captainkirkdawson** [comment]
In my tests the creation of a church does not fill the location field from the place, It is an input field

**Comment by Captainkirkdawson** [comment]
I had no difficulty editing the church fields

**Comment by Captainkirkdawson** [comment]
Complete as far as I am concerned

**Comment by Sherlock21** [comment]
Agreed. This was my mis-understanding of church information, that others had completed.

can be cancelled
