### ISSUE TITLE
The public search tool produces wrong Place / Church / Register name

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1018]

**Comment by Sherlock21** [comment]
This may just be a consequence of 1017, or it may be general.

But a search of one of the people from the Re named place in 1017 -  
SOM / Downside (Chilcompton) / Christ Church / PR .
for Mary Goold baptised 12 May 1839 
returns the wrong data on the Search Result listing.
See example.

Place is shown as Downside.
Church as Chilcompton
Reg type as Parish Register - this element is correct.
But the first 2 elements are wrong.

**Comment by Sherlock21** [comment]
![placechange-search](https://cloud.githubusercontent.com/assets/9368704/20462058/6c7f8e6c-af09-11e6-80ef-9a46743c2a46.jpg)

**Comment by Captainkirkdawson** [comment]
Please review on test3. I believe it to be a ramification of 1007

**Comment by Sherlock21** [comment]
Your suspicion was correct .

my testing of 1017 gave a search result that now has the correct strings of Place/ chu
![bardsettwo_search_res](https://cloud.githubusercontent.com/assets/9368704/20477218/85540396-afcc-11e6-9397-c146b86df5a4.jpg)
rch name / Reg type - see attached.

**Comment by Captainkirkdawson** [comment]
Completed
