### ISSUE TITLE
Missing fields in UseridDetail

### ISSUE THREAD

**Issue by AlexAvlonitis** [FreeUKGen/MyopicVicar#1020]
When i run:
bundle exec rake foo:create_userid_docs[add,userid,/.uDetails]
to change permission roles

It invokes the create_userid_docs.rb 
which at some point it requests the syndicate_name and disabled fields from the UseridDetail model.
And they don't exist.

To work on my machine i added those fields in UseridDetail, i was wondering if you would like me to push those changes or you want those fields not to be in UseridDetail and instead delete any reference of them from create_userid_docs.rb.

**Comment by Captainkirkdawson** [comment]
I am sorry I do not understand why you are trying to run that rake task unless it is to set up your own development machine, It is an initial setup creation task used when starting FR for the first time. It was designed for rails 2 and had not been updated for rails 4. Those specific fields are not used or required im userid details. The disabled field is actually the active field in FR and the syndicate_name is actually the syndicate field in the userid_details collection of FR. Those "original" fields are the fields that come in from the FR1 user .udetails file which is read by the rake task to create the initial userid_details collection.
They should not be added to the userid_details collection as this will cause confusion. But deletion of any reference to them from the rake code would mean that we would not populate the syndicate and active fields. Any code changes should be to not try to create those fields in the userid_details collection.

**Comment by AlexAvlonitis** [comment]
Thank you @Captainkirkdawson , sorry i forgot to mention i was following the instructions to build my dev environment. It's clear now thanks

**Comment by Captainkirkdawson** [comment]
I wrote those 2 years ago and never looked at them after moving to rails 4.
I expect that itds the normal issue of providing undefined fields in a
collection which used to be OK and is now a no no

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1
