### ISSUE TITLE
Invalid token on resetting password

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1021]

**Comment by edickens** [comment]
This is not the first time we have had this problem.  This time it is UserID Alvertonian - Brian Allison.  We have tried everything including my sending him a password reset email and he has replied immediately but still gets invalid token.

This is the message:-
 On Friday, 25 November 2016, 11:44, "reg-web@freereg.org.uk" <reg-web@freereg.org.uk> wrote:


Hello Alvertonian!
You have either just registered and need to set your own password or just need to change your existing password. You can do this by clicking on the link below.
Change my password
Your password won't change until you follow the link above and create a new one.
We hope you will enjoy or already are enjoying working with FreeREG. It is only through your work that researchers can find their ancestors on FreeREG.
The FreeREG Team.

But we have had some new volunteers register successfully.  So is the problem to do with him being someone who is coming back again?  He had been Active = No for a while but I have changed that back to Active = Yes.

Odd?  E

**Comment by PatReynolds** [comment]
See #864 for the latest on this issue, also #1012

**Comment by Captainkirkdawson** [comment]
All commentary on this issue is now being tacked in #864
