### ISSUE TITLE
Concern that cookies have let in Spam

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1022]

**Comment by edickens** [comment]
This from a transcriber:-

Yesterday I made a little use of the Freereg website which makes mention of cookies and that they may pass details of your contact to interested parties . Assuming that Freereg followed a reasonable code of conduct I agreed to their cookies . However , this morning on checking my mail I find I have received 68 potentially dodgy emails overnight and I can only think for the moment that these are in someway connected to Freereg .
I would be pleased to hear from any Group member that has experienced a similar issue . Also whether it is just pure coincidence that these emails arrived after accessing Freereg .
Kind regards
Roger Cox 

Perhaps this should be linked to the https story?

Do you want an example of a Spam email?

E

**Comment by PatReynolds** [comment]
Need to change text to reflect reality: we don't share our users' email addresses.

**Comment by PatReynolds** [comment]
Privacy policy fine: "We will not share or sell your personal data to a third party organisation for marketing or fundraising purposes without your consent."
Cookie policy on FreeREG: links to cookie policy on freeukgen (no mention of sharing, as we don't run Adsense there), and should go to the FreeREG cookie policy (which should mention sharing with advertisers - new story).   
I don't see where he saw that FreeREG may pass on cookie information to interested parties.

**Comment by dougkdev** [comment]
Since #855 has been created by Pat, can we let the user know that his increase in spam had nothing to do with our cookies and close this story?

**Comment by Captainkirkdawson** [comment]
Please let person know we do not share email addresses and then close
