### ISSUE TITLE
add "All Counties" option to search page

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/MyopicVicar#1024]
This performs the same as leaving the county blank (the default), just gives an explicit selection option for those who are confused and think they must select a county or who can't figure out how to unselect once they have already selected a county. Already added to FreeCen code by @AlexAvlonitis, @edickens suggested also adding to FreeReg.

**Comment by Sherlock21** [comment]
But did we not get a shredding from the Shaw Trust review for not doing the same thing consistently throughout the application? So whilst it would work easily either way,  it would not conform. And we have spent many man-hours going back over to satisfy that report have we not.?

MORE to the point though, if the search of Parish Register records is allowed to be All Counties, then wight he 250 record restriction, you will not get far ingot he potential Country wide selection anyway! And there is no way of knowing what's in the Excluded part of what the search returns, is there. So Researches will be worse off in my view.
They might take the online help advice of restricting the date span, but that will not  be effective here.

Don't offer Country wide search in FR is my view. - either by the default of blank, or by adding the All Counties name.

**Comment by dougkdev** [comment]
No one will be worse off. This is how it already works. This just makes it
less confusing to people.

**Comment by PatReynolds** [comment]
We need consistency across all fields, and all sites.  Stating 'All counties' (or 'All whatever' at the top seems like beset practice.

**Comment by Captainkirkdawson** [comment]
Have added an All option
It is required to clear the county selected on a revise if the user wants to deselect all  counties
