### ISSUE TITLE
SCs uploading files into Inactive UserIDs

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1027]

**Comment by edickens** [comment]
This is perhaps a question and the answer may need to go into SCs Help pages.

An SC can upload a file directly into transcriber's UserID.  But if the transcriber is no longer Active then the should not receive the confirmation email.  Some SCs have therefore changed the email address in the UserID to avoid this, but a much better system would be to just not send out the email to the Inactive UserID but only send the copy to the SC.

This many be happening, but I have just had an email from a transcriber who is no longer transcribing and they have received an email.  E

**Comment by PatReynolds** [comment]
Presumably the email is not the transcriber ID?  Or is it?  If it is, then it needs to remain.
Assuming that we continue to know who the transcriber was, then changing the email isn't an issue.  It will only happen (again I presume) in a few weeks after the transcriber has stepped down, as the SC will be uploading the file as soon as possible afterwards.

**Comment by Captainkirkdawson** [comment]
emails about processed files for an inactive user are NOT sent to an inactive user just to the coordinator

**Comment by Captainkirkdawson** [comment]
@edickens what is needed please

**Comment by edickens** [comment]
I think that the server is working correctly now and server generated emails do not go to inactive transcribers.
What is needed now is for the Help pages to give advice to SCs when they make someone Inactive, so that they know the process and the significance of their action.
Taking up Pat's comment, I think changing the email is an issue because we then lose any record of how to contact an inactive transcriber.  Some become inactive for short periods, so want to return, and sometimes we need to contact them about their transcription, so do need to keep their email address.  Their address is in the batch header, but this is not necessarily their latest email address.  The main thing is that we do not want any automated or general messages to go to them.   E

**Comment by AlOneill** [comment]
Currently, the advice to Coords reads:

"**Please note that**: If you Upload or Replace a file for one of your Transcribers, then both yourself and the Transcriber will get an email reporting the success or failure of the processing. In addition, the other relevant SC or CC will get a copy of the email (unless they have been sent one anyway). The only exception is that Inactive Transcribers will not be sent an email."

What specifically needs to be added/amended?

**Comment by edickens** [comment]
That looks fine.  Let's see if anyone does not understand.  We need
    to make sure that CC and SC use the help.
    
    This story can be closed now.
    
    Thanks
    
    Eric
    
      On 02/01/2017 15:43, AlOneill wrote:
    
    
      Currently, the advice to Coords reads:
      "Please note that: If you Upload or Replace a
        file for one of your Transcribers, then both yourself and the
        Transcriber will get an email reporting the success or failure
        of the processing. In addition, the other relevant SC or CC will
        get a copy of the email (unless they have been sent one anyway).
        The only exception is that Inactive Transcribers will not be
        sent an email."
      What specifically needs to be added/amended?

**Comment by Captainkirkdawson** [comment]
Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1
