### ISSUE TITLE
Files uploaded as OT are being downloaded as TR

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1028]

**Comment by edickens** [comment]
The correct Register Type for a transcription is OT (Other  Transcription) and the server accepts this.  But if the file is then downloaded it converts this to the old standards of TR.
I thought there was a question about TR being converted to OT, but it now seems that perhaps this should have been the other way round.  This is from the List Batches screen.
Problem reported by Michael, STS Coordinator.

**Comment by Captainkirkdawson** [comment]
This is identical to 845 which was closed 2 weeks ago.
The Internal representation of OT is TR they are one and the same as far as the system is concerned.
This is because we did not want to go back and convert all TR batches to OT batches since they are exactly the same definition.
Personally speaking I saw no reason to introduce the OT as it had the same definition as TR
Why is this being started again?

**Comment by PatReynolds** [comment]
I think because the 845 was TR is converted to OT, but this is OT is converted to TR.

**Comment by Captainkirkdawson** [comment]
No they are both OT becoming TR. There is only one internal and that is TR

**Comment by edickens** [comment]
But that is changing the new coding back to the old.  See
http://www.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers#regCodes
    
    If the server is changing codes back to the old, then why do we tell
    transcribers to use the new codes?  What is used internally by the
    server doesn't really matter.
    
    E
    
      On 12/12/2016 20:49, Kirk Dawson wrote:
    
    
      No they are both OT becoming TR. There is only one internal and
        that is TR
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #1028: No they are both OT becoming TR. There is only one internal and that is TR"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/1028#issuecomment-266548430"}}}

**Comment by Captainkirkdawson** [comment]
I agree entirely there was no substantive reason for the change from TR to
OT

We can display OT as easily as TR in the download of the church name. But
given all of the other changes on our plates how important is it. I would
far rather have put effort into other stories such as the flexible csv code
for example where we could have register type as a field of its own

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Not important.  Either TR or OT are accepted, which is all that matters.

There was a good reason for these changes in that all Transcriptions end 
in T, such as PT, DT and then OT.  Just as all registers end in R.

E

**Comment by richpomfret** [comment]
Kirk to change the text for the user.
