### ISSUE TITLE
Update update_freereg2 script

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1033]
The current update-freereg2 script does a chown apache:apache at start and then a chown back to webserv:webserv. This means file uploads and log writes fail if they occur while the script is running.
If the update_freereg2 script fails or is aborted then writing to tmp or log is not permitted. Need to recover

**Comment by Captainkirkdawson** [comment]
Currently testing revised version on vervet

**Comment by Captainkirkdawson** [comment]
After testing will request Lemon to add to puppet

**Comment by Captainkirkdawson** [comment]
Request has been made to @lemon-ukgen to  include in puppet.

**Comment by lemon-ukgen** [comment]
On 9/2/17 07:36 AEDT Kirk Dawson wrote:
> Request has been made to @lemon-ukgen to  include in puppet.
>

Where is the tweaked script to add to Puppet?

**Comment by Captainkirkdawson** [comment]
@lemon-ukgen       its with that name (update-freereg2) on [kirkdawson@vervet ~]$

**Comment by lemon-ukgen** [comment]
On 9/2/17 09:08 AEDT Kirk Dawson wrote:
> @lemon-ukgen       its with that name (update-freereg2) on [kirkdawson@vervet ~]$

Thanks. Committed, pushed out.

**Comment by Captainkirkdawson** [comment]
TY

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by lemon-ukgen** [comment]
All done, AFAIK.
