### ISSUE TITLE
Update System Documentation

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1034]
The system documentation is seriously out of date. It does not reflect the current state of implementation

**Comment by richpomfret** [comment]
Additionally, a separate conversation is needed on how we might be able to export/ dynamically update an external copy of this documentation.

**Comment by Captainkirkdawson** [comment]
Updated onto gsuite drive. Created system documentation folder and within that a FreeREG folder.
