### ISSUE TITLE
Add monitoring information to system documentation

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1035]
The tools used to monitor REG preformance need to be documented

**Comment by Captainkirkdawson** [comment]
Added section to system documentation on gsuites drive

**Comment by edickens** [comment]
At yesterday's Scrum I was asked to check this out.  I can find it OK, but is it still a Test environment?  It says:-

Background.

You are working in a test environment. Nothing you do is kept after the next rebuild of the test server nor will it impact your files on F1. So feel free to try EVERYTHING; even discarding information; you will likely learn something by doing so, if the system crashes (unlikely but if it does we need to know before advancing; one of the reasons for testing). Remember you are encouraged to try anything and everything; no one will object! If it barfs or does not do what you think it should we need to know.

**Comment by edickens** [comment]
Should this now be referred to in the Coordinators Help pages rather than System Documentation?  E

**Comment by Captainkirkdawson** [comment]
Eric

I am unsure what you looked at and where

**Comment by edickens** [comment]
I used this action...

![capture](https://cloud.githubusercontent.com/assets/8876165/21688063/5ecfb1ba-d363-11e6-9b23-ab6d49bf9eb7.JPG)

after which I go to gsuite.

But I am saying that gsuite should be accessed via a link from the Help pages not this Action button, which will not be available for everyone.

**Comment by Captainkirkdawson** [comment]
I disagree with putting a link in the Help. Those pages are for developers and system people . (Except the Roadmap which is public)

The document you refer to is not anything to do with monitoring. It is the original document I wrote 18 months ago. Useful for developers though

**Comment by edickens** [comment]
If for developers only, then definitely not in the Help.  I did not
    know that.  TY  E
    
      On 05/01/2017 16:55, Kirk Dawson wrote:
    
    
      I disagree with putting a link in the Help. Those pages are for
        developers and system people . (Except the Roadmap which is
        public)
      The document you refer to is not anything to do with
        monitoring. It is the original document I wrote 18 months ago.
        Useful for developers though
      
      
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #1035: I disagree with putting a link in the Help. Those pages are for developers and system people . (Except the Roadmap which is public)\r\n\r\nThe document you refer to is not anything to do with monitoring. It is the original document I wrote 18 months ago. Useful for developers though"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/1035#issuecomment-270695638"}}}
