### ISSUE TITLE
Reduce number of email addresses?

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1037]
Currently FR uses a number of different email addresses to distribute mail to our members.
 "freereg-contacts@freereg.org.uk" default
"freereg-processing@freereg.org.uk"
"freereg-feedback@freereg.org.uk"
"freereg-registration@freereg.org.uk"

**Comment by Captainkirkdawson** [comment]
Given the need to encourage members to whitelist our email addresses should we reduce their number?
At the same time should we move to the use of freereg@freeukgenealogy.org.uk

**Comment by richpomfret** [comment]
Agreed to go with one single email address (for sendgrid).

**Comment by Captainkirkdawson** [comment]
@AlexAvlonitis if we change sendgrid to use whitelabelling domains for our emails does this eliminate or change what we need to do with the sender email addresses used by our user mailer?

**Comment by Captainkirkdawson** [comment]
On hold pending  experience with 870

**Comment by Captainkirkdawson** [comment]
No longer see this as a requirement
