### ISSUE TITLE
"Transcriptons" misunderstanding by a researcher

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1039]

**Comment by edickens** [comment]
I've had a comment by a researcher who said that after looking at LAN, Flixton and choosing "Select one option", they said that they just get returned to the same screen.
I can see the problem because the wording on the results screen is the same as the select screen and the change is off the bottom of the screen, so it looks identical.  I don't think that the coordinators name and county records count are needed again on this page so that the results will become visible.  E

**Comment by Captainkirkdawson** [comment]
Please clarify action that is required
If this is to meet misunderstanding by 1 of 1000s of researchers why is it important to address
In meantime assigned future release

**Comment by edickens** [comment]
Version 2.  More about planning screen layouts to cater for people
    who cannot find their way around our screens when the results are
    off the bottom.  E
    
      On 13/12/2016 16:44, Kirk Dawson wrote:
    
    
      Please clarify action that is required
        If this is to meet misunderstanding by 1 of 1000s of researchers
        why is it important to address
        In meantime assigned future release
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #1039: Please clarify action that is required\nIf this is to meet misunderstanding by 1 of 1000s of researchers why is it important to address\nIn meantime assigned future release"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/1039#issuecomment-266791418"}}}

**Comment by edickens** [comment]
Version 2.  More about planning screen layouts to cater for people
    who cannot find their way around our screens when the results are
    off the bottom.  E
    
      On 13/12/2016 16:44, Kirk Dawson wrote:
    
    
      Please clarify action that is required
        If this is to meet misunderstanding by 1 of 1000s of researchers
        why is it important to address
        In meantime assigned future release
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #1039: Please clarify action that is required\nIf this is to meet misunderstanding by 1 of 1000s of researchers why is it important to address\nIn meantime assigned future release"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/1039#issuecomment-266791

**Comment by edickens** [comment]
This is so old, close it.  E
