### ISSUE TITLE
Message to be sent when a Profile is edited

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1045]

**Comment by edickens** [comment]
I edited my profile to change the Telephone Number field and got:-


Dear Eric;

Eric Dickens at freereg.edickens+som@gmail.com and userid edickens has been re-assigned to your syndicate.

Please make them welcome

The FreeREG Team

I know that this is a one fits all message, but before the system can be improved perhaps just say that the Profile has been edited.
I'm thinking about how we can use the Profile to know if someone is going to be out of contact for a while.  So if they are going to enter this information, this confirmation message to the SC will need to be more general.
  E

**Comment by Captainkirkdawson** [comment]
Message now only goes to SC if a syndicate changes on the edit. Will no longer happen on a straight edit
