### ISSUE TITLE
MOTDs for Everyone and just for Adminstrators

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#105]

**Comment by Captainkirkdawson** [comment]
MOTD is there for Members do we need for Researchers?

**Comment by edickens** [comment]
Yes.  Notices such as "Server
      maintenance" or "New facilities added".  But will be used a lot
      less than Members.  If no message, then nothing shows, as in FR1. 
      Where will it be now that the homepage is full with the search?
      EricD
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 02/01/2015 04:24, Kirk Dawson wrote:
    
    
      MOTD is there for Members do we need for Researchers?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by edickens** [comment]
I see that this has been done for the homepage and I have had a message which says that I can operate this by amending "Message" in Refinery.  No problem here.  But how do I remove the message when it is not needed without deleting it from Refinery so that it is there for future use?  If I just delete the text will this leave a blank line in the homepage and so move the search box even further off the screen?  How long should I leave a message, such as the present apology, on the homepage?  (I would suggest no more than a day after the event.)
E

**Comment by Captainkirkdawson** [comment]
Just remove all the text. You can leave the Message page in Refinery

How long is up to you

This one has been there long enough

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Done.
    E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 01/06/2015 14:49, Kirk Dawson wrote:
    
    Just remove all the text. You can leave the Message
      page in Refinery
      
      How long is up to you
      
      This one has been there long enough
      
      Kirk Dawson
      Fairmont Hot Springs, B.C.
      V0B 1L1
      
      On Mon, Jun 1, 2015 at 12:36 AM, Eric Dickens
      <notifications@github.com>
      wrote:
      
      > I see that this has been done for the homepage and I have had
      a message
      > which says that I can operate this by amending "Message" in
      Refinery. No
      > problem here. But how do I remove the message when it is not
      needed without
      > deleting it from Refinery so that it is there for future use?
      If I just
      > delete the text will this leave a blank line in the homepage
      and so move
      > the search box even further off the screen? How long should I
      leave a
      > message, such as the present apology, on the homepage? (I
      would suggest no
      > more than a day after the event.)
      > E
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
<https://github.com/FreeUKGen/MyopicVicar/issues/105#issuecomment-107322411>
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.
