### ISSUE TITLE
Manage Processes for Comments and Feedback

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1050]
See email by Eric D 3/1/2017

**Comment by Captainkirkdawson** [comment]
What email?

**Comment by edickens** [comment]
Sent to project team entitled Processing of Comments and Feedback at
    15:50GMT.
    
    E
    
      On 03/01/2017 18:51, Kirk Dawson wrote:
    
    
      What email?
      
      
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #1050: What email?"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/1050#issuecomment-270191678"}}}

**Comment by Captainkirkdawson** [comment]
Data problems are now sent directly to Com Coordinator and not to County Coordinator.
Data Problem Report page has been updated for accessibility. on test3

**Comment by CommsCoord** [comment]
Just tested from CMN, the email is still going to COunty Coordinator for
Data problem. Or have I junped the gun and this has not been actioned?

_________________________________________________________________________________

Sandra Adams-West
*FreeREG Communications Coordinator*
*__________________________________________________________________________________*

**Comment by Captainkirkdawson** [comment]
Message was not totally clear. These changes have only got as far as test3. They are there for people like you and erid to test and make sure I did not foul things up too bady

**Comment by edickens** [comment]
I have used the "Report a transcription error" from the Details screen of Search results in Test3 and this has generated this message.

![capture](https://cloud.githubusercontent.com/assets/8876165/21713921/4e928ed0-d3f4-11e6-94c4-d3f5d9e11bc4.JPG)

Where you will see that a copy has gone to freereg@bricknell.org.uk who is a transcriber in Anna's NTH Syndicate.  Why?  Ilona Bricknell has nothing to do with this transcription.

The search was Dickens, 1835 to 1855 MA SOM.  1 result.

E

**Comment by edickens** [comment]
I see now that freereg@bricknell.org has the role of Contacts Coordinator.  So this would now seem to be working correctly and messages do not go to the CC.  E

**Comment by CommsCoord** [comment]
A contact, 63614610​, has come through to new Comms email addressed only to
the originator, Comms and the Comms deputy's (Ilush) email. It is a data
problem for SOM, and SOM CC has been bypassed.

_________________________________________________________________________________

Sandra Adams-West
*FreeREG Communications Coordinator*
*__________________________________________________________________________________*
