### ISSUE TITLE
Change Comscoord address

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1052]
Coms coords now set up on gsuite.  Please change address to comscoord.freereg@freeukgenealogy.org.uk

**Comment by edickens** [comment]
I have changed the email address in the CommsCoord UserID.  It
    should change now for any new messages.  E
    
      On 05/01/2017 11:27, PatReynolds wrote:
    
    
      Coms coords now set up on gsuite. Please change address to comscoord.freereg@freeukgenealogy.org.uk

**Comment by edickens** [comment]
Done and messages are coming through already.   Just the copy to CCs to be taken off Comments and Feedback leaving just CommsCoord to get them.  E
