### ISSUE TITLE
Revise file processing process

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1053]
We currently run ASAP rake tasks for small files and hold large ones to the night.
There are issues caused by multiple ASAPs running at the same time for the same location but different record types. This causes update contention on the index files.
It bunches many files together for processing at one time. Lastly we have enormous files of 50,000 records that cause massive headaches for the servers.
It is proposed that 1) all files are placed into the waiting state. 2) That there be a cron task run hourly to process all waiting files except those that are beyond processing limits. This will require an interlock system so that only one task runs at a time 3) A list of unprocessed files be provided to the data manager who will work with the transcriber/coordinator to resolve the processing indigestion 4) that the data manager has access to a special processor that processes unlimited size files when that is deemed necessary.
This replaces 1007

**Comment by Captainkirkdawson** [comment]
It will have the benefit of spreading out the processing load and while slowing some processing will result in overall faster processing

**Comment by edickens** [comment]
Good idea.  E

**Comment by Sherlock21** [comment]
At the moment I dont have a better idea for you,Kirk.

but based on the response I got from some CC’s whilst trying to get Cc’s to address the existing 39 unprocessed files, this one will go nowhere when I invole those CCs.

and anyway: if the backlog is a bunch of jobs from many people say done over the weekend, and all put in on the Sunday evening, the processing will have worked though normally in oyur new system, by Monday evening or Tuesday morning be the time I get to email the CC concerned.

I can see it being a bit of a waste of my day. 
BUT I can see here migh be a better solution if we know some more parameters:

Like how many files would you accept as the limit for this new cron task?
is it number of files, or records per file that’s the problem.

and how well you get upnrocessed files, if they are drip fed in this controlled manner please?

And yes I dont mind taking advantage of your point 4) on quiet occasions if that’s the way to clear up a backlog for example if that’s what you had in mind?

EB

**Comment by edickens** [comment]
I don't think we should over react as the overnight processing has been 
working well for some time now.  It is just Yvonne that has clogged the 
system.  People are trying to stick to the smaller limit which is why on 
some nights there just a handful of flies. WinFreeREG does throw up a 
warning when 2,000 is hit.  E

**Comment by Captainkirkdawson** [comment]
You might have a different view if you were *1 of the 50* researchers today
who had their searches needlessly time out because of the issue and who
decided to stop using such an unresponsive site as a result


Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
@Sherlock21  I made a mistake in the use of the terminology "A list of unprocessed files" given the difficulties you had with the clearing of that backlog.
What I had in mind was that when the process runs it will give you a list of any files that were not processed in that run as they exceeded the limits that we establish.  So it refers to those files that have been submitted for processing in the past 24 hrs that have a size problem and asking you to work with the userid to seek a solution but providing you with the ability to have that file processed if you were of the opinion that there was no better solution

**Comment by Sherlock21** [comment]
Ah....
Thats a different matter. I can handle it when expressed in those terms.

My first though is: if it has to be processed as one big file, then run it in a quiet time. BUT how do I know when a quiet time is? I can't see the processor's 'workload' so i would just do early mornings say up to 09:00 GMT if that would do? else tell me how to guess please.

ON the same topic: if I say: divide the new file up into 3000 record individual records, say, and load each as a new.
THEN DELETE the original big file, won't that deletion process cause as much load anyway, as that which we are trying to prevent?

**Comment by Captainkirkdawson** [comment]
I would not touch a large file unless there is something wrong with it. If its a few records I would do an on-line edit of each of them. If its additions I would put in a new file. Key is what are they trying to do with an old file.

**Comment by Captainkirkdawson** [comment]
There is a further way of doing this. When we have a file get loaded we look to see if the processor is running. If not we initiate the processor. If the processor is running we set the waiting flag on the new file. When the processor finishes it checks to see if anything is waiting.  If so it processes what is waiting. If nothing is waiting then it shuts down. 
wrt "large files" we hold them, we notify data manager. We then give data manager a version of the processor that processes large files but only runs at a predefined quiet time. He initiates this when he is convinced its processing is truly required.

**Comment by Sherlock21** [comment]
I agree with your strategy, Kirk.
So let's set that up then please. I will have go and see how we go on.

But I would appreciate it i you would tell me the numbers you are proposing for:-
 Normal preferred file size limit for New files
Limit for a Reload so it will not likely get held up
"Large files" to hold them and refer to me

And I would need the FR Manager to tell all CC's of these limits please.

**Comment by edickens** [comment]
If it was me, I would want to amend the version of my work on my
    computer.  This could be done just as easily by doing it online,
    when validation is done immediately, then downloading the file to
    replace the one on my computer, BUT the sequence could have
    changed and not match the source images, which is why I would not
    want to do online edit and download.  E
    
    On 07/01/2017 23:05, Kirk Dawson wrote:
    
    
      I would not touch a large file unless there is something wrong
        with it. If its a few records I would do an on-line edit of each
        of them. If its additions I would put in a new file. Key is what
        are they trying to do with an old file.

**Comment by edickens** [comment]
I agree that this is probably the only solution, but in principle I like 
to avoid manual intervention as we need a system that will last for the 
next 100 years,  E

**Comment by Sherlock21** [comment]
Yes, it is a bit of a problem trying to match a downloaded file back to the version on ones PC as you say.
But if not too many corrections have been done online, (as opposed to adding a lot more records to the end of an existing file) the person doing them is working from a list, and so should then be able to apply those same corrections to their file. Admittedly their file will not be in the same order as the one online, but it never was going to be. 
So what?

And in the future online transcribing method will that not be the same out of steepness that we have now? or will there be some methodology they keeps then in step?

It also begs the question: why can't a Transcriber's file have its own Row/sequence number column, which get uploaded as part of the record. and then one can reorder any downloaded file back into the order the Transcriber has it?

**Comment by Sherlock21** [comment]
I:F we don't permit any more extra large files, then there will be no growing problem handling them
and these that are online at present, should need very little correcting. So i see this as a temp job, rather than a Career for Life for the DM.

The Key lies in establishing that future files may not be bigger than xxxx rows So don't keep adding more to the end of a file and Reloading it.
I have looked at all my own files, and I don't think I have any greater than 10,000 rows -  
The downside of many small 2000 row files is the number of these files that would get created for a large church, with a lot of records so that 48000 record files would become 5 files at 10000 rows, AND WITH 2000 ROW LIMIT will make 24 files so think of the mass of file refs in the Whats Available header list.

**Comment by edickens** [comment]
Would a "File Row/sequence number" also help with the overnight 
processing?  If this number matches one already on the server and there 
is no change to the entry, then it does not need to be processed.  
Insertions would trigger a lot of updating from that point on, but 
insertions are rare.  Most changes are amendments. Insertions should be 
additions on the end.  But I think Kirk's processing works this way now, 
because he did a lot of work to avoid reprocessing entries that do not 
change.  E

**Comment by edickens** [comment]
And we have Manchester's public cemetery with 1M entries.  E
    
      On 08/01/2017 10:31, Sherlock21 wrote:
    
    
      I:F we don't permit any more extra large files, then there will
        be no growing problem handling them
        and these that are online at present, should need very little
        correcting. So i see this as a temp job, rather than a Career
        for Life for the DM.
      The Key lies in establishing that future files may not be
        bigger than xxxx rows So don't keep adding more to the end of a
        file and Reloading it.
        I have looked at all my own files, and I don't think I have any
        greater than 10,000 rows -
        The downside of many small 2000 row files is the number of these
        files that would get created for a large church, with a lot of
        records so that 48000 record files would become 5 files at 10000
        rows, AND WITH 2000 ROW LIMIT will make 24 files so think of the
        mass of file refs in the Whats Available header list.
      
      
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Sherlock21 in #1053: I:F we don't permit any more extra large files, then there will be no growing problem handling them\r\nand these that are online at present, should need very little correcting. So i see this as a temp job, rather than a Career for Life for the DM.\r\n\r\nThe Key lies in establishing that future files may not be bigger than xxxx rows So don't keep adding more to the end of a file and Reloading it.\r\nI have looked at all my own files, and I don't think I have any greater than 10,000 rows -  \r\nThe downside of many small 2000 row files is the number of these files that would get created for a large church, with a lot of records so that 48000 record files would become 5 files at 10000 rows, AND WITH 2000 ROW LIMIT will make 24 files so think of the mass of file refs in the Whats Available header list."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/1053#issuecomment-271142641"}}}

**Comment by Captainkirkdawson** [comment]
Needs a scrum review before implementation

**Comment by Captainkirkdawson** [comment]
Today we had an interesting example of a single transcriber uploading 7 files within 3 minutes. This meant we had 7 rake tasks performing updates on the database simultaneously and yes it did have a negative impact on performance..

**Comment by Captainkirkdawson** [comment]
See impact chart

![impact](https://cloud.githubusercontent.com/assets/2874694/21919437/af8a1370-d917-11e6-812c-dac297df0054.JPG)

**Comment by edickens** [comment]
I can understand why this happens.  The older registers are often a 
mixture of BA, MA and BU, so create three files.  And if you are making 
corrections as a batch, you can end up with a number of files ready to 
go and then you log in and find the Replace for them.  E

Eric J Dickens

**Comment by Captainkirkdawson** [comment]
Yes  their activity is quite understandable and is something the sever needs to be able to deal with.

**Comment by edickens** [comment]
I liked your one at a time idea that you put forward a few days ago.  If 
someone tries to process they just need a message to say "The server is 
already updating the indexes from another upload, so your work has been 
put in a queue."  Or something like that.  In this way you might be able 
to do away with the overnight processing queue.  If the server is only 
processing one upload at a time, and you have still included the slight 
delay between records, then there should not be too much degradation of 
service.

Would this mean that you put everything in the queue, and always put out 
that message, unless the queue is empty?

Interesting that last night's update only took 13 minutes but there were 
only 5 files.

E

Eric J Dickens

**Comment by Captainkirkdawson** [comment]
Wrote new process whereby one rake task only runs. It clears the waiting queue. A rake starts runs as soon as it is required. Large files of more than about 6000 records are held for review by Data Manager. 
Data Manager may initiate if he feels it is required. In Physical Files he sets file to processing.
