### ISSUE TITLE
Mongo security issue.

### ISSUE THREAD

**Issue by israelriibeiro** [FreeUKGen/MyopicVicar#1059]
Hi, guys.

I saw an article about how mongodb is vunerable to attacks. The cracker invades the server in order to steal the data and he asks for money in exchange for data.
    
- Enable authentication that provides you 'Defense in depth' if your network is compromised. Edit your MongoDB configuration file — auth = true.
- Use firewalls — Disable remote access to the MongoDB, if possible. Admins are advised to use firewalls to protect the MongoDB installations by blocking access to port no. 27017.
- Configure Bind_ip — Limit access to the server by binding local IP addresses.
- Upgrade -- Administrators are strongly recommended to upgrade their software to the latest release.

We must pay attention to this: [Hacker news](http://thehackernews.com/2017/01/secure-mongodb-database.html)

@Captainkirkdawson @benwbrum @richpomfret

**Comment by PatReynolds** [comment]
Thank you, Israel.  I'm taking this off-discussion to email.

**Comment by israelriibeiro** [comment]
As Lemon said, he checked this, so i'm gonna close this issue.
