### ISSUE TITLE
Investigate impact of a church relocation

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1064]
We had a church relocation with 700 records that had a significant impact on performance.
Was it simply index rebuild or something else.

**Comment by Captainkirkdawson** [comment]
![impact](https://cloud.githubusercontent.com/assets/2874694/21964398/5ebbef34-db08-11e6-8028-87ceafb4b9e4.JPG)

**Comment by Captainkirkdawson** [comment]
![impact](https://cloud.githubusercontent.com/assets/2874694/21964406/8331805e-db08-11e6-91a3-7574edcebe50.JPG)

**Comment by Captainkirkdawson** [comment]
relocating a church from one place to another

specifically  the church was in  SOM/ Bath / and the church had the church name Twerton - St Peter
file name drh123.SOMTWPBA.csv number of records 2400.

and relocated it to the place name SOM/ Twerton.
with the church name just St Peter.

It did take ages, and then  browser timed out but  the Active places list, it had arrived OK.

Then after a few minutes gap - about 16:45 isn, moved the Marriages file from the same (wrong) place & church to the right Twerton / St Peter. this file had about 750 records.

**Comment by Captainkirkdawson** [comment]
Question is this because of the change in storage engine. The MMAPV1 storage engine was able to an insert in place in the database. Does the Wired Tifger do a move???

**Comment by Captainkirkdawson** [comment]
No it does not it writes a new record for every update and cleans up in background.

**Comment by Captainkirkdawson** [comment]
Lets look at update_all

**Comment by Captainkirkdawson** [comment]
Timing tests have shown 99.5% of time goes to promulgation of changes

**Comment by richpomfret** [comment]
Eric B to test.

**Comment by Sherlock21** [comment]
Testing is in hand with my results going straight to Kirk - via emails.
EB
