### ISSUE TITLE
Problem when replacing a file

### ISSUE THREAD

**Issue by CommsCoord** [FreeUKGen/MyopicVicar#1065]

**Comment by CommsCoord** [comment]
A transcriber is getting this message when trying to replace a file, which they have not seen before
![freereg](https://cloud.githubusercontent.com/assets/20557838/21965103/8fcb1c10-db50-11e6-87e4-0afe2875d2ac.PNG)

**Comment by Captainkirkdawson** [comment]
Identical to 899 which is awaiting deployment of fix

**Comment by CommsCoord** [comment]
Apologies. Will close this one.
