### ISSUE TITLE
File error for place name not used

### ISSUE THREAD

**Issue by CommsCoord** [FreeUKGen/MyopicVicar#1068]

**Comment by CommsCoord** [comment]
UserID Jeff46 has received an error message regarding the church name not being in the database for the place name. The problem is that the place name contained in the file is correct, however when uploaded the system tried to send it to a similar place name which was not in use. There already was a file in the correct place and church name but for some reason this file has is not following.
![jeff error](https://cloud.githubusercontent.com/assets/20557838/22038658/fd9fffea-dcf3-11e6-8d5a-ef397e02e56b.png)

**Comment by CommsCoord** [comment]
This is a copy of the first dataline from the file:
RAD,Llanfihangel Helygen,St Michael PR,,03 Sep 1841,Anne,,,,,HAMER,84,,

Llanfihangel Helygen,St Michael is correct. For some reason the system wants to send it to the place name with a hyphen and lowercase h.

**Comment by Captainkirkdawson** [comment]
That place name exists
![place](https://cloud.githubusercontent.com/assets/2874694/22040189/437f68f0-dcbf-11e6-9e65-c48b34ebe202.JPG)

**Comment by CommsCoord** [comment]
True, but the data line clearly shows the placename matches the one 4 lines
up from the one you highlighted, with the church name in place. The system
was trying to direct it somewhere that it should not have.

Kind regards
The Communications Team

**Comment by CommsCoord** [comment]
This scenario has again been repeated, this time with Llanfihangel Nant Melan  in RAD. in both cases (including Llanfihangel Helygen) the transcriber has entered the correct place name and church, but the system is trying to direct the file to a place name not in use,.. System is trying to send the files to a place name with the same spelling, but one with lover case letter at the start of the second name, and also with dash i.e Llanfihangel-helygen. This is not a transcriber error, it is a system error at some level

**Comment by Captainkirkdawson** [comment]
Do you intend to have both places as valid places?

 If not then please delete the unwanted ones and the issue will go away

**Comment by CommsCoord** [comment]
Thought that might be the case but was unsure. Thank you​

**Comment by Captainkirkdawson** [comment]
@CommsCoord  have you resolved this and can it be closed?

**Comment by CommsCoord** [comment]
Have asked for the place names to be deleted, and will now close this story
