### ISSUE TITLE
Delete older files

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1074]
We need to delete log files older than 50 days as part of the nightly cleanup to avoid unnecessary disc space wastaheiles

**Comment by Captainkirkdawson** [comment]
Need @lemon-ukgen  to provide task with permission

**Comment by lemon-ukgen** [comment]
`sudo` change done

```
$ ROOT=/home/apache/hosts/freereg2/production
$ sudo -u webserv find ${ROOT}/log
1161290     1363 drwxrwsr-x    2 webserv                          webserv                              2784 Feb  8 07:13 /home/apache/hosts/freereg2/production/log
...
```

The grant is

```
/usr/bin/find /home/apache/hosts/freereg2/production/log *
```

so you can do anything after the `${ROOT}/log` parameter, like `-ls` for testing.

**Comment by Captainkirkdawson** [comment]
Sorry @lemon-ukgen  but last night was still
[update-freereg2_production_database] 2017-02-09 02:42:44 delete log files more than +30 days old
Sorry, user freereg2 is not allowed to execute '/usr/bin/find log -mtime +30 -delete' as webserv on colobus.freebmd.org.uk.

**Comment by lemon-ukgen** [comment]
On 09/02/2017 16:16 AEDT Kirk Dawson wrote:
> Sorry @lemon-ukgen  but last night was still
> [update-freereg2_production_database] 2017-02-09 02:42:44 delete log files more than +30 days old
> Sorry, user freereg2 is not allowed to execute '/usr/bin/find log -mtime +30 -delete' as webserv on colobus.freebmd.org.uk.
> 

You need to fully qualify the path like in my example. See my previous
comment for the sudo grant - your invocation must match it up to the '*'

**Comment by Captainkirkdawson** [comment]
OK I was under the clearly false understanding that since the command was being executed from within the folder $(ROOT) then log was already relative to that.

**Comment by lemon-ukgen** [comment]
On 10/02/2017 02:48 AEDT Kirk Dawson wrote:
> OK I was under the clearly false understanding that since the command was being executed from within the folder $(ROOT) then log was already relative to that.

`sudo` works by comparing the command it's being asked to run with a
list of patterns. It doesn't know how a particular command, `find`, will
interpret a particular argument, `log` (ie: relative to the working
directory) at all. They're just strings to match.

The grant is explicit so that it's only that one log directory,
`${ROOT}/log` that can be operated on this way.

Otherwise `cd /var; find log ...` would work too!

**Comment by Captainkirkdawson** [comment]
Thanks for the explanation. The older one gets the more one learns
unfortunately it is also the more one forgets. Hopefully the latter does
not outweigh the former.

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Working

**Comment by lemon-ukgen** [comment]
All done, AFAIK.
