### ISSUE TITLE
Issues when creating certain new Place Names

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1075]
There is already a Place Name NBL / Newbiggin-by-the-Sea.
I need also to create a Place name NBL / Newbiggin Hall at grid ref NZ203680 ( this is different to the existing Place)
BUT I am stopped creating my new Placename  by an Error Msg: the place already exists. This is not true. Only the first word of the new Place name is the same as the first word of the existing one.

**Comment by Sherlock21** [comment]
Interestingly, we have an existing place called NBL / Gosforth.

And I have just managed to successfully create NBL /North Gosforth with no problem, as the common bit does not start both names.

**Comment by Sherlock21** [comment]
More interesting info: an hour after the original attempt to create this Placename, I happened to be looking in  FR production NBL/ at the same page as Newbiggin is on. AND Lo: the name that I and been trying to create, but got told it had failed, is in fact there now.

this reminds me one before, I was trying to recreate a single word Place Name that had been previously disabled, and got the same system error message. But on looking back at the Names index, it had in fact been reactivated despite my being told I could not have  it!
Might this be another example of Newbiggin Hall was actually Deactivated before I tried today to create it?

**Comment by Captainkirkdawson** [comment]
Likely this is a result of a poor message on reactivating a disabled place

**Comment by Sherlock21** [comment]
I think I agree with  Kirk's comment, as the solution. If that could easily be implemented, it would save me a lot of worry and lengthy debates like this one.

**Comment by Captainkirkdawson** [comment]
Have rewritten place creation. Better information. It will reactivate a disabled place and tell you.
Deployed to test3. You need to test all aspects of creation. I can give you ( @Sherlock21  ) a few disabled places in a county of your choice for testing.

**Comment by Sherlock21** [comment]
Thank you.
Yes, i will work to your list then you know where I am !
 let's use one of Doreens counties for convenience - CON or WOR

**Comment by Captainkirkdawson** [comment]
@Sherlock21  In CON you can try the following  disabled places Darley, North  :   Curry, West :  Croan, Lower ;  Comfort, Little

**Comment by Sherlock21** [comment]
I have tested these proposed additions, and they do create (by reactivate) the desired place name with a system message that indicated its a Reactivation of a deleted name. FINE.

I then tried to change Place Name on Curry, North. it failed with a red message: Somethings gone wrong.

Did i not leave it long enough for all the necessary processing?  i did not see why that would be the case - It works OK in Production to do that 
So I tried to change Place Name on a pre existing one: CON / Badgall and got the same FAIL. Same red message." Something's gone wrong."

EB

**Comment by Captainkirkdawson** [comment]
It's the law of unintended consequences at work! Had added a check on number of records prior to a rename or relocate to avoid an accidental attempt to rename a  place with a million records. Forgot that a re-enabled place would have nil for the number of records. Will fix

**Comment by Sherlock21** [comment]
That's right. Surprising how many of my "little jobs" take a day because I missed some key thing .
Thanks for doing this nevertheless.

**Comment by Captainkirkdawson** [comment]
@Sherlock21  I hope it is fixed.

**Comment by Sherlock21** [comment]
yes, it is fine now.

I tested it on Curry, West > Curry, West2
and that's ok

Not a big sample but I am prepared to put my shirt on it.
So GO when you re ready.

Thanks you.
