### ISSUE TITLE
Method to add extra name combinations to the list

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1081]

**Comment by edickens** [comment]
Mick has found that Ann does not find Anne or Annie.  How can this be added to the list?
I have a SysAdmin Action to add new Church Denominations, so a similar Action to add name combinations would be useful.
Also, are Surname and Firstname conversion lists different?
Where can I see what is in the list now?
E

**Comment by Captainkirkdawson** [comment]
This duplicates the stories #1040 which is under development at this time and #1071 the update capability which is unscheduled

**Comment by PatReynolds** [comment]
Eric, have you informed Mick?  If so, I will close this.

**Comment by edickens** [comment]
No.  It is something we need when we add extra fields and update 
WinFreeREG and the data entry.  V1.6.

Eric J Dickens
