### ISSUE TITLE
Child Surname field

### ISSUE THREAD

**Issue by CommsCoord** [FreeUKGen/MyopicVicar#1083]
A field for a child's surname is needed to accommodate records which are patronymic or any occasion where the child's surname differs from that of the father, or in some case, the mother. Pre 1813 records in Wales are primarily affected, but this may extend to some Cornish and IOM records where patronymics were also used.

**Comment by PatReynolds** [comment]
Has this been superceeded by flexible CSV?

**Comment by Captainkirkdawson** [comment]
Yes it is addressed in the new baptism fields

**Comment by PatReynolds** [comment]
TY, @Captainkirkdawson
