### ISSUE TITLE
Relocation tab not working

### ISSUE THREAD

**Issue by CommsCoord** [FreeUKGen/MyopicVicar#1085]
Have tried to relocate a number of files to their proper homes, but the 'We're sorry, but something went wrong with processing your request. A report has been produced and sent to the webmaster. Please return to your prior activity but try to avoid doing the exact same action again' tab keeps popping up. Most recent file was GLABRDBA, trying to relocate from Bridgend Wesleyan Circuit in Area Circuit Registers of Glamorgan

**Comment by Captainkirkdawson** [comment]
Issue is being worked on

**Comment by Captainkirkdawson** [comment]
Fixed

**Comment by Sherlock21** [comment]
Agree it oK now on my profile too.
