### ISSUE TITLE
Change Register Type function fails ( in Production)

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1086]
I tried to change Reg type on the file: Amanda.CONGRAMA [ 200 records only]
but get the dreaded red "oops sorry something seems to have gone wrong"

see also next report

**Comment by Captainkirkdawson** [comment]
Duplicate of 1085. Message about issue was placed on Member login earlier today

**Comment by Sherlock21** [comment]
Yes, I agree it works fine for Data Manager profile too now.
