### ISSUE TITLE
Is it time to drop FR and go back to FR1

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1088]
Given that people apparently still prefer FR1 as a search engine and coordinators appear to prefer its file management system perhaps we need to stop further development of FR and revert to the monthly update of FR1.
Moving back would take little or no effort. Perhaps 1 week at the most on the part of the developers and 1 week each for the coordinators to update their parish information.

**Comment by CommsCoord** [comment]
Against this 110%. Whilst it is true on some specific instances the old
system may have a bit better, the overall use for the new FR is much, much
better.

The old FR was a pain in terms of those coordinators having multiple
counties and/or large amounts of parishes to update. And let's not forget
the hassles of adding in or deleting parishes.

So the new FR still has bugs, agreed it can be a pain, but it is still
easier to deal with. Will the future updates planned not take some of the
issues faced now away?

Just thoughts and musings. ​

Kind regards
The Communications Team

**Comment by suffolkroots** [comment]
I too would be horrified by the thought of reverting to F1.

We can do so much more in F2, but are somewhat hampered by the usability and user-friendly reported concerns which hopefully will be addressed soon.

**Comment by Captainkirkdawson** [comment]
@CommsCoord  commented in 915.

Is there anything that we (coordinators and such) can do to help with the issues that are currently on the board? I am sure among us there are people that can help, even with simple tasks. We just need to know where we can help, if we can. I can relate to why you brought up FR1. It was much easier in some respects, but more time consuming for the coordinators. I don't wish to return there, but I can see that from the developers view, it would eradicate a number of issues in and of itself

**Comment by Captainkirkdawson** [comment]
The reason for this story is to a degree related to the comment by @CommsCoord 

In essence during the past sprint there have been 25 new stories added. 7 were dealt with as they were either duplicates or bugs.

Over this period we have cleared 10 stories as part of the sprint.

There is now a backlog of 260 stories.  Bottom line is we are adding 10 more stories each sprint than we resolve in that sprint.

The system performance is degrading  and at the same time we are being asked to force fit a real time online system to meet non real time needs.

**Comment by Captainkirkdawson** [comment]
PS just saw you were timed out on a contact delete!!

**Comment by PatReynolds** [comment]
@DeniseColbert's research showed that only a small minority of researchers preferred FR1.  I think the issue here is how to ensure that we have sufficient capacity to run FR2.
