### ISSUE TITLE
Colour inactive userids when UserIDs are listed

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#109]
Priority 10 ( 0	1	1	8)
Colour the text of inactive users in a display of lists of userids

**Comment by Captainkirkdawson** [comment]
@SteveBiggs is this still a requirement. If so I suggest we change to version 2

**Comment by SteveBiggs** [comment]
I didn't raise this, but it would be useful.

**Comment by Captainkirkdawson** [comment]
Applied to test3
