### ISSUE TITLE
Site_statistics

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1090]
Every single page display accesses the site statistics collection for information to display in the footer.
The site_statistics collection is retrieved from a database collection by a collection scan of all documents. ie all documents are being retrieved and examined
Requirement. To select based on an index and store for the session

**Comment by Captainkirkdawson** [comment]
Code has been added to load stats once using an index search.

**Comment by edickens** [comment]
The daily statistics have disappeared from the footer of all pages.

**Comment by edickens** [comment]
Back again now.  TY.  E

**Comment by Captainkirkdawson** [comment]
Yes I need to use yesterdays until todays is calculated. There is a lag that will lead to nothing in the footer for a period of time

**Comment by edickens** [comment]
No problem now that I know.
    
    TY
    
    E
    Eric J Dickens

    On 09/02/2017 16:06, Kirk Dawson wrote:
    
    
      Yes I need to use yesterdays until todays is calculated. There
        is a lag that will lead to nothing in the footer for a period of
        time
      
      
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #1090: Yes I need to use yesterdays until todays is calculated. There is a lag that will lead to nothing in the footer for a period of time"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/1090#issuecomment-278687135"}}}

**Comment by Captainkirkdawson** [comment]
Done
