### ISSUE TITLE
Add "No file processing emails" to UserID

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1091]

**Comment by edickens** [comment]
Some transcribers ask their SC to upload files on their behalf, and so they should not get the "File processed" emails, but they still need to get any other emails. 

This is what happens now:-

If a SC makes the UserID Inactive, then the transcriber will not get any emails.  But the SC can still upload files into their UserID.

If a SC keeps the transcriber's UserID Active, but puts an email address which comes back to them into the transcriber's UserID, then they will get two messages for each file upload and the transcriber will not get any emails, and we also lose the transcriber's contact details.

In both the above cases we cannot send the transcriber Message System Management emails, some of which could be very important.

So I suggest that we need a marker in the transcriber's UserID to say something like "SC uploading data", default False, and if it is set then no file upload emails are sent, the messages just being treated as if the UserID was Inactive.  The Server Message System does not look at this and so sends messages to the transcriber whose UserID should contain the their email address.  To stop all messages going to the transcriber their UserID should be set to Inactive.

E

**Comment by Captainkirkdawson** [comment]
Requirement:  1) Add a Boolean field to the UseridDetail that is called no_processing_messages that is by default false. 2) Add the field to the show of a document 3)Add the editing of this field to the edit of a userid_detail document 4) add a test of this field to the mailer for the processing_messages so that it does not go to the userid. The copies are still to go to the coordinators.

**Comment by Captainkirkdawson** [comment]
@edickens  and @Sherlock21  will you please test the implementation of your requirement that has been done by @bev-fc  on test3
The show of a profile now includes an additional field for SC loading data. Normally false (no). You can edit to yes (true) in which case there will be no email sent to the userid just the coordinator. The user is still active

**Comment by edickens** [comment]
Normally it seems that I cannot see that field when I look at my own
    profile.  Probably the right thing.  We do not want a transcriber to
    set this field  Only the SC or SA using Manage UserIDs sees the
    field.
    
    Can we be clear for the Help exactly what this marker will do.  My
    understanding is that is says that the UserID is Active and
    transcribing, but the SC is uploading files on their behalf so that
    no upload emails should be sent to this UserID, just the copy to the
    SC.  They should get all other emails.
    
    It is called SC upload data: which is perhaps not quite
    right.  It is a marker to say that no file upload emails to be sent
    to this UserID.  Or is it also to say that no emails to be sent to
    this email address other than those through the server message
    system.
    
    Do you think this is the right sequence?
    
    
    I suggest:-
    Role in FreeREG
    Skill  Level
    SC upload data
    Active
    Then the rest.
    
    The SC upload data perhaps could even come after the email address
    as it is saying not to send messages to this email address.
    
    E
    
    Eric J Dickens

    On 12/02/2017 21:13, Kirk Dawson wrote:
    
    
      @edickens and @Sherlock21 will you please test the
        implementation of your requirement that has been done by @bev-fc on test3
        The show of a profile now includes an additional field for SC
        loading data. Normally false (no). You can edit to yes (true) in
        which case there will be no email sent to the userid just the
        coordinator. The user is still active

**Comment by Captainkirkdawson** [comment]
You are correct this is a management level function.
It does what you understand.
I think the name is appropriate
Does it work????

**Comment by Sherlock21** [comment]
I have not tried to test it yet. - been too busy with other things today.
Perhaps tomorrow I may get a look at it.
EB
