### ISSUE TITLE
Blog post on FR2

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1092]

**Comment by richpomfret** [comment]
To write-up/convince old users just how magnificent the new site is!

**Comment by DeniseColbert** [comment]
See #1070

**Comment by richpomfret** [comment]
For Eric/Steve to review and add in comments as possible.

**Comment by edickens** [comment]
In #1070 Pat has shelved this to V1.7. I agree with this.  There is so much change coming up and we can promote the website then.  At present it is still undergoing too much change.

**Comment by PatReynolds** [comment]
I think we should still promote the website now - it is undergoing very little change (from the researcher point of view other than enhanced accessibility).  What was shelved to 1.7 was the advanced development required.

**Comment by Captainkirkdawson** [comment]
What is proposed is a management issue not a development issue propose to close
