### ISSUE TITLE
Rebuild UCF and Deploy

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#1099]

**Comment by Captainkirkdawson** [comment]
@benwbrum  could you give me a heads up on what may be involved before we chat?

**Comment by benwbrum** [comment]
The various bug fixes require us to:

* Re-process records of the "George?" variety.  We'll need a script that
finds those records and re-transforms them, updating the
`search_record.search_name` with the removed question mark.
* Re-process records of the "Ge[o_]rge" variety.  This will also need an
update to `search_record.search_name`
* Run the rake task `foo:refresh_ucf_lists`.  This depends on the
reprocessing mentioned above (at least the second item), but only updates
the `places` collection.

Obviously we need to be careful about performance updating the
search_record indexes.

**Comment by Captainkirkdawson** [comment]
In my opinion given the processing implication we are best to do an off line rebuild of the search record collection on vervet and then deploy the new version.

**Comment by benwbrum** [comment]
I'm still not 100% sure of the need in isolation, but if we'll need to
rebuild the indexes offline to pick up name_role, then I agree completely.

**Comment by Captainkirkdawson** [comment]
If we deploy the new code so we are not creating new occurrences we could prepare a list of records that need to be updated by examining the names in the freereg1_csv_entries collection  rather than the search_records collection. 

This should isolate the list creation from the search, Once the size of the list is known we  will be in better position to decide on best way of updating the search record.

We could get an estimate of the scope of the issue y running the list creation on test3

**Comment by benwbrum** [comment]
I am working with @Vino-S to do the following:

Create a new rake task that
* Loops through all  records in `freereg1_csv_entries` containing the characters `[]?{}`
* Print the `id` of that record to STDOUT so we can divert it to a file

After that, we will add a start date parameter to the task, so it can be run on production to pick up records created since test3 was copied to production.

Next we will (probably) write another task that reads the file of freereg1_csv_entry ids and rebuilds the search record for each one.

**Comment by benwbrum** [comment]
Thanks to @Vino-S's work, if we address the `*` issue, we will need to rebuild a million records.  @Captainkirkdawson suggests that this would be better done as a full rebuild, rather than an ongoing remediation, and I support that, much as I wish wish it wasn't so.

**Comment by Captainkirkdawson** [comment]
It appears that over 1 million records may be affected. This suggests that a crawler update is unlikely to be effective.

**Comment by Captainkirkdawson** [comment]
Can I suggest we consider running the recreation after we have done 1128 the evaluation of reverting to the MMap storage engine. If we decide to do that then a complete rebuild of the collections is required amyway.

**Comment by benwbrum** [comment]
I agree -- with sharding and other architectural changes on the horizon, it
makes sense to hold off on the UCF until we have a definite plan for these
bigger performance issues.

**Comment by PatReynolds** [comment]
I hope that's what I wrote on your order, Ben: UCF to deployment, but not deployment.

**Comment by Captainkirkdawson** [comment]
It would be important to deal with 1134 and 1136 so we are ready when we are ready

**Comment by benwbrum** [comment]
Agreed.  I'd like to schedule both #1134 and #1136 for the upcoming sprint.

**Comment by Captainkirkdawson** [comment]
The recreation of the search records for entries with ucf charcters has been done on both test3 and production. The update of the place list of UCF search records has been run on both. test3 is ussing and displaying ucf records. Production is still off. Are we ready to turn on?
