### ISSUE TITLE
Is file updating working correctly in Production?

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1104]
Consider the history on CON / LUXULYAN and its file by P Hoare: CONLUXMA.csv.
The Cc  is of the opinion that The download of the current file seems to have acquired duplicates  records .
The oldest in the attic and as such its the first uploaded. It is fine.
it has 153 records in it 

Now the next update just adds a few in - there are NO duplicates, 

Then look at the Last one in the attic. 
And also Look at how many Attic files are seconds apart. So what's happening here? - all on the same evening as the first update for some reason. is that possible by the user?

The last one I see in the Attic does not have any duplicate rows 
BUT comparing this last file in the attic, with a download from FR today, there is where things seem to go wrong.

Such a lot of these records show DUPLICATE FR record numbers. Why?

SO please can you provide a copy of the Transcriber's upload file that gives rise to the version I just downloaded So that I can check further to see what;s troubling the CC concerned.

**Comment by Captainkirkdawson** [comment]
You can get it yourself through the physical files collection. That is why its there. A download from is from the physical file which is the reason behind the name

**Comment by Sherlock21** [comment]
I had forgotten that one. thanks.

**Comment by Sherlock21** [comment]
CLOSE THIS ONE PLEASE> PROBLEM IS DIFFERENT - see
