### ISSUE TITLE
Store research record with result

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1106]
We currently store the id of a search result and retrieve the document at the display time. This currently means a double retrieval of the search_record and slows the display of search results.
Store the search record document with the search query. Thereby eliminating one document look up.
Will need clean up tasks to avoid overfilling the search_queries collection

**Comment by edickens** [comment]
When I select Witnesses and Family Members, I cannot tell which is which without looking at each individual record in detail.  See attached where Row 2 is perhaps a family member or witness.  E
![capture](https://cloud.githubusercontent.com/assets/8876165/23986785/e1c7614e-0a1d-11e7-813a-0394b5e03885.JPG)

**Comment by Captainkirkdawson** [comment]
Alignment looks OK to me. @AlOneill can you please look at
![dickens1](https://cloud.githubusercontent.com/assets/2874694/24003388/f21fe1a0-0a28-11e7-8284-0204b78c272e.JPG)
and the same as on production
![dickens2](https://cloud.githubusercontent.com/assets/2874694/24003481/33c8c3ec-0a29-11e7-90a8-a05ac77f8f2f.JPG)

**Comment by Captainkirkdawson** [comment]
wrt to the witness/family member the display is identical to production. No change was made in how the display was constructed

**Comment by Sherlock21** [comment]
I don't see anything odd about the display of this Dickens example when searched on my desktop Mac with neither Safari NOR with Opera.

**Comment by edickens** [comment]
Kirk,
I misunderstood the test we are to do.  I thought it was about speed and stability rather than replicating results.  I'll have another go.

To clarify my comments above.
In my first image the criteria selected is offset to the left.  I don't remember it like this before.
In the second, (and the image seems to have lost a bit off the bottom), the Row 2 does not have the name Dickens showing anywhere.  So the result must have been either a relative or witness.  But which?  I would need to look at the Detail to find out which.
But, as you say, this is format not performance and should be for V1.7.  Please ignore.
E

**Comment by Captainkirkdawson** [comment]
Sorry I was likely less than totally clear. This is very much speed, stability and same results. If this works then other things can be done in due course. This was quite a change in how the code fits together and my  stiching may not be what it should be.

I have not to my knowledge changed actual displays but things like sort, next and previous and the record to be displaid have all changed. Hence

**Comment by Sherlock21** [comment]
Considering the speed of the  first of a "NEW" search, and of subsequent "Refinements",  yes its impressive. But this is on T3 of course, which is  usually a bit quick.

So: I look forward to having a go in Production.

**Comment by Sherlock21** [comment]
ONE SNAG:  The link from the top of the Details Link  page in the table of search results, called: 
https://www.freereg.org.uk/contacts/5818b380e93790de6af578bd/report_error?query=58cad80f4325a6d3289d794

Returns the message: FORBIDDEN  - but I am logged on as DM at the time, so I would have expected it to work for me. I don't know if it ever worked, or is just a  feature of the changes we are concerned with here. I have had no need to use it in Production.

**Comment by AlOneill** [comment]
@edickens / @Captainkirkdawson: Page layout is as expected. Exact look will depend on content of results and width of window. (It has been like this since accessibility and other changes were made.)

**Comment by Captainkirkdawson** [comment]
Thank you Eric. Fixed. That is why we have to test. I had missed that required change

**Comment by Captainkirkdawson** [comment]
EricB has conducted an excellent test comparing the results of searches between test3 and production and concluded 
SO MY CONCLUSION:	there is a significant improvement in speed for the multiple features searches - ( Nearby, And where relevant, for  Witnesses, & Family).
The speedup in the case of a basic search will need the Tech Programmers to check the operations logs to see the actual times.
There was no apparent loss of any records nor any wrong records returned.
Exellent test. TY @Sherlock21

**Comment by Captainkirkdawson** [comment]
Deployed to brazza for evaluation. Found 3 small issues involving existing searches and their interface with the new scheme. Rectified.

**Comment by Captainkirkdawson** [comment]
24 hrs of running showed improvements expected. Search Query show down to 150 ms from 1200 ms; Search record show down to 100 ms from 850 ms. Search itself down to 2300 ms from 3400 ms. Number of time out of searches reduced to 0.2% from 1%. Propose to deploy to all servers. This is not through any reduction in the number of searches but simply how results are obtained and stored for further usage.

**Comment by Captainkirkdawson** [comment]
It has been deployed to all servers. Performance is showing anticipated improvements.
![capture](https://cloud.githubusercontent.com/assets/2874694/24252416/10d01f28-0fa3-11e7-8d8f-41cd4dd6e1ec.JPG)
