### ISSUE TITLE
SSL on FreeREG2.freereg.org.uk worrying people

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1108]
User reports https: not working - screenshot attached
https://drive.google.com/open?id=0B40Bs8RXWSWWVWNpalJhVloyaXM

**Comment by Captainkirkdawson** [comment]
That is because they are NOT using www.freereg.org.uk which is the official and secure website link.

They are using the 2 year old transitional link which has not been secured.

Likely have it bookmarked or otherwise stored on their computer.

Do not know how you were informed of this but you likely need to respond with asking them to use the official website link. If it came in through one of the UKFREEGEN routes then a general comment about that could be made.

This person is clearly a member.

**Comment by PatReynolds** [comment]
Did inform. Problem was reported by spokeswoman for three. Should we
communicate need to move away from freereg2? Redirect?

Pat Reynolds
Executive Director, Free UK Genealogy

**Comment by CommsCoord** [comment]
There was another contact today regarding the transitional link​. Told them
to delete the old link, along with bookmakrs, and gave correct link. This
is the second email Comms has had on the subject this month.

Kind regards
The Communications Team

**Comment by Captainkirkdawson** [comment]
Pat* it does redirect to www.freereg.org.uk <http://www.freereg.org.uk> *which
really is why people are still using it.

What we likely should do is kill the redirect as that is the only way we
can get rid of issues associated with its use.

*We should also send out another message saying use the official site and
not the freereg2*

You could also ask Lemon to make freereg2.freereg.org.uk secure but that
just propagates the issue into the future

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by SteveBiggs** [comment]
I have had a few direct emails about this and have directed them to the correct URL also. I agree that a general message should be sent out reminding everyone to use the correct link.

**Comment by richpomfret** [comment]
Agreed to kill the redirect. Also send out the necessary message (before the death of the link).

**Comment by SteveBiggs** [comment]
Email sent out.

**Comment by Captainkirkdawson** [comment]
Appears we need to notify researchers as well!!

**Comment by lemon-ukgen** [comment]
I've made http://freereg2.freereg.org.uk redirect straight to 
https://www.freereg.org.uk without going via https://freereg2, so 
there's now no certificate warning

Further, the redirect doesn't carry over any path info, so 
http://freereg2.freereg.org.uk/some/useful/path still just goes to the 
homepage. That might be enough to make people notice the change, and 
bookmark the live site instead.

If you have a different page you'd like freereg2 people to end up on 
please let me know its path.

**Comment by DeniseColbert** [comment]
Sent out on social media

**Comment by Captainkirkdawson** [comment]
Will write a short page on RefineryCMS that says you are using an obsolete link and ask people to use the correct url.

L can redirect to that. 

Then in a period we can drop the freereg2 url

**Comment by Captainkirkdawson** [comment]
@lemon-ukgen  could you redirect freereg2.freereg.org.uk  to https://www.freereg.org.uk/cms/incorrect-link

**Comment by lemon-ukgen** [comment]
On 23/2/17 08:05 AEDT Kirk Dawson wrote:
> @lemon-ukgen <https://github.com/lemon-ukgen> could you redirect
> freereg2.freereg.org.uk to https://www.freereg.org.uk/cms/incorrect-link

That's done.

**Comment by Captainkirkdawson** [comment]
TY
