### ISSUE TITLE
Bing is linking to FR1, Test, freereg2.freereg etc (related to #885)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#1122]
A search for FreeREG on Bing (default search engine - Microsoft Edge) points to undesirable places:

![image](https://cloud.githubusercontent.com/assets/19173257/23407000/9e5ba584-fdb9-11e6-98c4-bb1501fbcb06.png)

https://www.bing.com/%2fsearch%3fq%3dsite%3afreereg.org.uk%2bfreereg

**Comment by Captainkirkdawson** [comment]
Bugger bugger bugger

**Comment by AlOneill** [comment]
Could it just be that their update cycle is longer (or just way out of step with) Google??

**Comment by Captainkirkdawson** [comment]
No part of what I "fixed" was to tell the google search not to do certain
things with our various sites.

Looks like I have to do the same with bing!!!

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by DeniseColbert** [comment]
Sorry Kirk! Pat did mention that this might be a good task for Vinodhini
though, so maybe you can avoid the tedium this time...

Best wishes,

Denise

**********
*Denise Colbert*
Engagement Co-ordinator

[Usual working days: Monday, Tuesday and Wednesday]

E: denise.colbert@freeukgenealogy.org.uk <denise.colbert@freeukgen.org.uk>
T: +44 7825 338014
W: http://www.freeukgenealogy.org.uk/

*Join us on Social Media:*

* <https://www.facebook.com/freeukgen>    <https://twitter.com/Freeukgen>*


Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A Charitable Incorporated Organisation registered in England and Wales,
number 1167484.

VAT registration: 233 0105 70

**Comment by richpomfret** [comment]
For new volunteer (Leah) or Vino? Not high priority..

**Comment by richpomfret** [comment]
Interviewing for new SEO related volunteer to help.

**Comment by PatReynolds** [comment]
@DeniseColbert can you ask Anna?

**Comment by PatReynolds** [comment]
Anna cannot use Bing (Mac user).

**Comment by Captainkirkdawson** [comment]
It is clear that Bing is now linking to our main site and to other useful links
