### ISSUE TITLE
The file Processor seems to have stopped

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1123]

**Comment by Sherlock21** [comment]
it was not working this morning at o8:00 GMT and  there were 3 or 4 old files that were still there not done PLuS 12 from yesterday .
Kist got it going at about 14:00 GMT and it seems to have processed 6 files. But has done nothing since about 16:00 GMT today.

**Comment by SteveBiggs** [comment]
The backlog of files has now been cleared. Files are processing again.
