### ISSUE TITLE
Implement sharding

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1124]
We are currently using a 5 member replica set with each member also acting as an application server. 
It appears this may not be optimal for our workload nor the best set up for the future if additional apps are added.
A more optimal arrangement might be a set of shards with each shard having a 2 member replica set for ensuring data availability and reliability. Sharding over 3 or more clusters would spread update workload, reduce replication impacts and reduce index sizes. Our apps are ideal for such a onfiguration especially if we use a last-name or last-name.first-name sharding key. This set up would require an additional server.

**Comment by Captainkirkdawson** [comment]
Implementation Plan
1. Establish shard keys for search_records
2. Establish shard keys for freereg1_csv_entries
3. Design test configuration for testing sharded setup on vervet
4. Test vervet setup with small database
5. Test vervet setup with larger database
6. Finalize configuration for new servers
7. Setup sharded configuration on new servers
8. Load test database into new server
9 Test new servers with small database.
10. Load full database into new servers
11. Test new servers on full database.
12. Test update of database for ucf and incorrect search dates.
13. Revise configuration for new servers
14. Close production database to members
15. Load production database into new servers
16. Update new database for ucf and other search record corrections
17. Change production to new servers
18 Open new servers to Members.
19. Consider sharding other collections.

**Comment by Captainkirkdawson** [comment]
Steps 1-6 can be done with current hardware. 7-19 require new servers

**Comment by Captainkirkdawson** [comment]
1. Ben and I have concluded the best shard key for search_records is last_name.chapman_code.
Based on this analysis  https://docs.google.com/document/d/15YrdAl9ZdAdE2vN5vMDYfB3UqoTSPOI3vHlJGLFwfGk/edit#heading=h.gjdgxs
it would appear that a last_name.chapman_codec shard index might well be best. This would create only 1 jumbo chunk at 64MB. 60% of all searches would be directed to a single shard. The remaining 40% would be scatter gather searches hitting all shards unless we were to think of a way of directing soundex searches to a single shard. Since by definition; a soundex starts with the first letter of the surname. 50% of all such searches would likely be constrained to a single chunk.

**Comment by Captainkirkdawson** [comment]
2. Ben and I have concluded that the best shard key for freereg1_csv_entries is year.chapman_code

**Comment by Captainkirkdawson** [comment]
3. This is my proposed first test configuration @benwbrum 

3 shards; 3 replicas per shard 1 an arbiter; 3 configuration servers and 5 mongos. The latter gives us 1 per app sever. The latter are extremely light weight.
Have written it as a script

mkdir mongosharda0
mkdir mongosharda1
mkdir mongosharda2
mkdir mongoshardb0
mkdir mongogsharb1
mkdir mongogsharb2
mkdir mongoshardc0
mkdir mongoshardc1
mkdir mongoshardc2


mkdir configuration0
mkdir configuration1
mkdir configuration2


# config servers

mongod --configsvr  --dbpath configuration0 --port 26050 --fork --logpath log.configuration0 --logappend #--logRotate rename
mongod --configsvr  --dbpath configuration1 --port 26051 --fork --logpath log.configuration1 --logappend #--logRotate rename
mongod --configsvr  --dbpath configuration2 --port 26052 --fork --logpath log.configuration2 --logappend #--logRotate rename

# shard servers. Note the oplog size and small file size are for single server testing only
#mongod --shardsvr --replSet a  --dbpath /var/db/mongodb/wired_tiger/production --logpath log.mongosharda3 --port 27000 --fork --logappend #this second test version.
mongod --shardsvr --replSet a  --dbpath mongosharda0 --logpath log.mongosharda0 --port 27000 --fork --logappend --smallfiles --oplogSize 50 
mongod --shardsvr --replSet a  --dbpath mongosharda1 --logpath log.mongosharda1 --port 27001 --fork --logappend --smallfiles --oplogSize 50 
mongod --shardsvr --replSet a  --dbpath mongosharda2 --logpath log.mongosharda2 --port 27002 --fork --logappend --smallfiles --oplogSize 50 
mongod --shardsvr --replSet b  --dbpath mongoshardb0 --logpath log.mongoshardb0 --port 27100 --fork --logappend --smallfiles --oplogSize 50 
mongod --shardsvr --replSet b  --dbpath mongogsharb1 --logpath log.mongogsharb1 --port 27101 --fork --logappend --smallfiles --oplogSize 50 
mongod --shardsvr --replSet b  --dbpath mongogsharb2 --logpath log.mongogsharb2 --port 27102 --fork --logappend --smallfiles --oplogSize 50 
mongod --shardsvr --replSet c  --dbpath mongoshardc0 --logpath log.mongoshardc0 --port 27200 --fork --logappend --smallfiles --oplogSize 50 
mongod --shardsvr --replSet c  --dbpath mongoshardc1 --logpath log.mongoshardc1 --port 27201 --fork --logappend --smallfiles --oplogSize 50 
mongod --shardsvr --replSet c  --dbpath mongoshardc2 --logpath log.mongoshardc2 --port 27202 --fork --logappend --smallfiles --oplogSize 50 
#mongos processes
mongos --configdb vervet.freebmd.org.uk:26050,vervet.freebmd.org.uk:26051,vervet.freebmd.org.uk:26052 --fork --logappend --logpath log.mongos0 
mongos --configdb vervet.freebmd.org.uk:26050,vervet.freebmd.org.uk:26051,vervet.freebmd.org.uk:26052 --fork --logappend --logpath log.mongos1 --port 26061
mongos --configdb vervet.freebmd.org.uk:26050,vervet.freebmd.org.uk:26051,vervet.freebmd.org.uk:26052 --fork --logappend --logpath log.mongos2 --port 26062
mongos --configdb vervet.freebmd.org.uk:26050,vervet.freebmd.org.uk:26051,vervet.freebmd.org.uk:26052 --fork --logappend --logpath log.mongos3 --port 26063
mongos --configdb vervet.freebmd.org.uk:26050,vervet.freebmd.org.uk:26051,vervet.freebmd.org.uk:26052 --fork --logappend --logpath log.mongos4 --port 26064
echo
ps -A | grep mongo

echo
tail -n 10 log.configuration0
tail -n 1 log.configuration1
tail -n 1 log.configuration2

echo
tail -n 10 log.mongosharda0 
tail -n 1 log.mongosharda1
tail -n 1 log.mongosharda2
tail -n 1 log.mongoshardb0
tail -n 1 log.mongogsharb1
tail -n 1 log.mongoshardb2
tail -n 1 log.mongoshardc0
tail -n 1 log.mongoshardc1
tail -n 1 log.mongoshardc2
echo
tail -n 10 log.mongos0
tail -n 1 log.mongos1
tail -n 1 log.mongos2
tail -n 1 log.mongos3
tail -n 1 log.mongos4

**Comment by Captainkirkdawson** [comment]
Likely easier to read from a file

https://drive.google.com/drive/u/1/folders/0BykgQKwJtk6fN3lIX1U5aXVMOUU

**Comment by Captainkirkdawson** [comment]
4, Has been completed and the process for setup tested. Testing has shown we need to rethink  the search_record shard key proposed in Action 1 as that is inappropriate. That proposed in Action 2 for freereg1_csv_entries is fine.

**Comment by Captainkirkdawson** [comment]
The proposed shard key for the search_records will not work as it includes a multikey field.  All possible shard keys that distribute searches to individual shards will not work because they are multikey fields. This is because we adopted a multikey structure for the search record. This caught us out earlier with the search_dates field. We are left with using a shard key for serch records that will result in all searches being scatter gather on all shards or moving to searching on collections that do not involve a multikey.

**Comment by Captainkirkdawson** [comment]
The servers are now available for our setup. I have proceeded with step 6. to set them up using the configuration  proposed in https://drive.google.com/drive/u/1/folders/0BykgQKwJtk6fN3lIX1U5aXVMOUU
although the problems noted above meant that step 5 was never undertaken and ther has been no feedback on the porposal. 

I had hoped to be able to move to step 9 by weeks end but have yet to receive an appropriate test url from Lemon.

**Comment by Captainkirkdawson** [comment]
As the result of being able to talk with Ben following the on line meeting we have agreed an approach towards sharding.

We will deploy the search_record collection with the most efficient shard key that it can support. Specifically search_date and county 

We will develop code to support specific high frequency searches on ancillary collections derived from search records. These collections will have their own shard key designed to support that type of search. They will also have sufficient information to display the result without having to do a further database lookup.

General non specific searches will continue to run against the search_record collection

This means that these actions are now decoupled and independent activities.

**Comment by Captainkirkdawson** [comment]
Step 7 Setup sharded configuration on new servers now finished.

Moving to step 8 Load test database into new server

**Comment by Captainkirkdawson** [comment]
Test3 is now running against a small database on the sharded cluster. There is no sharding at this time as the database is too small.

This completes steps 8 and 9

Now for step 10

**Comment by Captainkirkdawson** [comment]
Step 10 is complete. Test3 connects and serves searches and member access. Now to shard.

**Comment by Captainkirkdawson** [comment]
Started sharding search_records at 14:30 MDT on May 17 using search_date:1 chapman_code:1. Created 1464 chunks, these are now being migrated to the 3 shards. Should end up with 488 chunks per shard.

**Comment by Captainkirkdawson** [comment]
Steps 10, 11 and 12 are complete
Have identified need for revisions  to search date correction and ucf rake task.
Testing showed that different shard would likely perform better.

Step 13 underway rebuilding with a shard key of  chapman_code:1. search_date:1 This localizes searches better to specific shards for our most popular searches. Basic configuration seems OK. Need script to simplify management. Need alert system for instance failure. 

Estimated time for deployment to production. Clone of database 6 hrs. Revise indexes 6hrs. Balance chunks across shards 3 days. (Will review preallocation). Search date correction 4hrs. UCF update TBD

**Comment by Captainkirkdawson** [comment]
Balanced sharding of the test production system completed in 3 days, There are no jumbo chunks.

**Comment by Captainkirkdawson** [comment]
Indexes rebuilt

**Comment by edickens** [comment]
When the servers are closed to Members who can then no longer log in, will it also be closed to new registrations?  Registration can start before logging in , but will then try to create a UserID.  If the password cannot be confirmed within 24 hours we will have an incomplete registration.  I recommend that the registration process cannot even start durng this time.

**Comment by Captainkirkdawson** [comment]
Registration is not permitted if servers are closed

**Comment by Captainkirkdawson** [comment]
Step 14  Server closed to members to stop database changes on Tuesday at 8am MDT 
Step 15. Load production database into new servers commenced at 8:30am MDT

**Comment by edickens** [comment]
UserID Jaycee was able to complete registration at 16:27 BST.

**Comment by Captainkirkdawson** [comment]
Quite possible. What is cut off is the new registration

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Database cloned from saki.
New indexes build to reflect sharding
Search_dates corrected.
Balancing underway

**Comment by Captainkirkdawson** [comment]
Commenced identification of UCF records

**Comment by Captainkirkdawson** [comment]
Balancing continues at 9am MDT on June 2; needs about another day to complete.

**Comment by Captainkirkdawson** [comment]
Have performed timing test on UCF search record recreation. Estimate 32 hrs of running time.
Now expect 1 day for completion of balancing; 2 days for UCF and  6hrs for FreeCEN
Let us say 4 days remaining.. So likely to commence transition of researchers to New Servers on Tuesday with Members on Wednesday if nothing untowards happens

**Comment by Captainkirkdawson** [comment]
Balancing finished at 8 MDT. Commenced UCF Search Record rebuild shortly there after.

**Comment by Captainkirkdawson** [comment]
UCF seach record rebuild completed at 3AM MDT.
Commenced clone of FreeCEN2 at 8:30 MDT

**Comment by Captainkirkdawson** [comment]
Vervet died at 8:45!!!!!

**Comment by Captainkirkdawson** [comment]
Following conversations with Doug I am replicating an earlier version of FreeCEN taken earlier that does not have the May/June updates  but does have the correct search record structure.
This will delay the FreeREG deployment by 12 hrs

**Comment by Captainkirkdawson** [comment]
brazza has been switched to the mongodb servers at 8 MDT

**Comment by Captainkirkdawson** [comment]
The transition to the sharded mongodb servers is now complete.

The Member access is reinstated.

test3 now points to a test production database on the same servers.

The mongod instances on the main servers have been shut down

For those that need to access the database through a mongo shell the command is 

mongo32 --host mongo1.freeukgen.org.uk:27017 --ssl --sslAllowInvalidCertificates

This will connect you to a mongos. Please make sure that is what you see in the response. ie mongos>

You may then work just as you would with mongo with additional commands to display and control the sharding aspects.

I will put togeather a document for the technical team on the actual setup

It is advisable that we set up a development test database on vervet

**Comment by Captainkirkdawson** [comment]
The research community has now been using FreeREG on the mongodb servers for 1 week, The search performance has been much better than anticipated. The average search time is now about 0,6 sec compared with the nearly 4 sec on the previous set up, There have been no search time outs in the past week, Indeed no search has exceed 45 seconds.

There have been no comments on member performance and we have no metrics to measure their service,

We were able to run an emendation update involving 1.7 million search records during normal production in 7.5 hrs with minimal service impact. (The average response time went from 0.6 to 0.8 sec). In the past we would have taken a month or more to do such an update/

The original servers are showing far less stress on their IO and colobus is much happier.

Lemon has developed the scripts needed to stop/start the various mongodb instances and to report on their status. They are now connected to the Nagios server monitoring system.

I would anticipate no issue running FreeCEN in this environment
