### ISSUE TITLE
Add tickboxes and links to documents on Sign-up pages

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1132]
To avoid unnecessary tidying up and in preparation for Researchers Registration

**Comment by edickens** [comment]
When someone first indicates their intention to volunteer they set up a Profile which is incomplete until they have registered a password by responding to an email with a Token.
Suggestions:-
- The Profile should be set to Active = False on the initial set up.
- The Profile should be set to Active = True when the password is set and the Registration Complete"  is set to Yes.
- Profiles with Registration Incomplete and the Registration date being more than a month ago are deleted.  Any problems with registration should have been sorted out by then.
- The Image Server file, which is created every night, should not include anyone whose registration is not complete.  This will avoid lots of Folders being set up which have to be deleted.

There may be other useful things to do when registering, so do add them.
E

**Comment by PatReynolds** [comment]
To add: "I have read and agree to follow the Code of Conduct" (which still needs to be written) and "I have read the Volunteers Handbook" (late draft stage).
Volunteer able to indicate that they wish their name associated with the items they have transcribed when it is shared or shown to the public.
Volunteer able to indicate that they wish their user name associated with the items they have transcribed when it is shared or shown to the public.

**Comment by richpomfret** [comment]
To push forward once the documents are ready.

**Comment by PatReynolds** [comment]
I think this is now covered by #842 and #843, and should be closed.
