### ISSUE TITLE
Problem with Image Server / FR Sync

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1133]
The file which passes information from FR to the Image Server is not deleting Destroyed UserIDs

**Comment by edickens** [comment]
I have deleted the recent Rogue UserIDs from both FR and the Image Server, but they have reappeared on the image server.  I suspect that they are still there on the overnight file which passes UserIDs and Passwords to the Image Server.

**Comment by Captainkirkdawson** [comment]
Is this still an issue. The listing we put out appears OK

**Comment by edickens** [comment]
Is OK now.  Did you make any changes or was it just necessary to update the sync file?
The sync file needs to be updated every day because it creates folders for new transcribers so that I can allocate images.  But it should not include incomplete registrations because once a folder is created in IS for a UserID it is never deleted, so it is best to just have completed registrations.

**Comment by Captainkirkdawson** [comment]
Made no changes

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Suggest you chnage from problem to request to change to non confirmed
userids only

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Will do.  But if you made no changes, how did the Incomplete registrations re-appear in the Image Server the next day.  Is it just a timing problem?  When is the IS Sync file updated?  I thought it was done at midnight GMT every day.

**Comment by edickens** [comment]
Request is in #1132 and that will do.  We don't know yet how the IS will be integrated, so no need to make changes now.

**Comment by Captainkirkdawson** [comment]
No idea
