### ISSUE TITLE
* as a ucf not functioning correctly

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1136]
The spec for * as a ucf character is for 1 or more unknown characters.
The example k*k is correctly retrieved as ucf by k-k where - is any character. 
It is not retrieved by k--k and is rerieved by kk.
ie it functions as 0 or 1 character

**Comment by Captainkirkdawson** [comment]
There is also a case sensitivity. kik retrieves the record while KIK does not.

**Comment by benwbrum** [comment]
I am utterly failing to reproduce this -- can you take a look at these test cases and see what I'm missing?
```
Test case # 1: Edward C__S_ should match queries for Edward CROSS
Test case # 2: P* WYATT should match queries for Prudence WYATT
Test case # 3: J* CROSS should match queries for JAMES CROSS
Test case # 4: Hugh? * should match queries for Hugh SOMETHING
Test case # 5: Ann? *ADY should match queries for Ann BRADY
Test case # 6: Charaty *OL should match queries for Charaty POOL
Test case # 7: John T_R* should match queries for John TOREY
Test case # 8: Marey NUTC* should match queries for Marey NUTCASE
Test case # 9: Sally C[E_]RR should match queries for Sally CARR
Test case # 10: Edmund J_{1,2}NSON should match queries for Edmund JOHNSON
Test case # 11: Wallah B_{1,2}NSON should match queries for Wallah BENSON
```

**Comment by benwbrum** [comment]
Spotted it!  None of my test cases had a star enclosed by non-wildcard characters.

**Comment by benwbrum** [comment]
This is pending a rebuild on vervet before it can be tested.

**Comment by Captainkirkdawson** [comment]
We should also look to deployment of these changes to production after we
have sharded and before we open to users

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Both test3 and production have been updated with new search_records

**Comment by Captainkirkdawson** [comment]
Needs a review

**Comment by SteveBiggs** [comment]
I tested by searching for this example - 
Ma*e PICKRYNG	Burial	28 Apr 1607	Norfolk	Hemblington : All Saints : Parish Register
It is found searching for Mae, Maae, Maee, Maaaaaae, Maeeeeeee,
But not by Mabe, Mace, Made, Mafe .....
I stopped at that point as there is clearly still something wrong.

**Comment by Sherlock21** [comment]
In the (T3) test I did this morning, BL*D is found as a surname when searching for BLAND.
So is R*NSON when searching for Surname of ROBINSON.

So whats the difference? I am searching in Surnames only in my tests - Steve seems to be in First names. Is the code meant to handle both first names and surnames?  

They both come in the Possibles section of the search results of course.

**Comment by Captainkirkdawson** [comment]
Please remember we are looking at correct functioning of UCF providing
additional possible results. We are not looking at Wildcard searching.So
searching with a wildcard is not appropriate

ie, If a record is encoded by the transcriber as KI_K Is it found by
searches for KIRK or KICK? remembering _ is one character that record
should not be found with a searchy of KIK or KIND or KIRST.

You know how UCF is defined so do we get the expected results.

This is only enabled on test3

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
Yes, indeed . I was on the wrong track wasn't I.

Back to the drawing board.
Is it intended that we work through all the possible combinations of 1, 2, 3, 4, 5 up to 20 UCF's?

Just be kind enough to remind me what should have been used for an unknown number of characters that could not be read, in the middle of a longer First Name or Surname.

**Comment by edickens** [comment]
Try here:-
https://freereg1.freereg.org.uk/howto/transcribe.htm
ED
![capture](https://user-images.githubusercontent.com/8876165/27510428-fe98e962-5907-11e7-90a4-1f720fbf2544.JPG)

**Comment by Sherlock21** [comment]
So, here, the single * which is not in [ ] is permitted in a name and is considered a UCF- like I have interpreted my tests to data. But Kirk's comment seemed to indicate that I was wrong in using that use as a UCF.

OR was in meant to tell me there were other considerations too, for other types of UCE?

**Comment by Sherlock21** [comment]
I have one snag here:-
using LANGSTAFFE, I had a previous file containing John Langstaffe.
this file I then revised off line and reloaded to change John Langstaffe into John3 Langstaffe And adding another line for a John LA{___}STAFFE.

Searched for LANGSTAFFE and found both the new John3 that has the ucf, and the original John which is not there in the current file so should have been removed in the Reload process.
Result sheet attached.
![error1](https://user-images.githubusercontent.com/9368704/27510488-52754700-5909-11e7-88d5-ce9401d6ad39.jpg)

**Comment by edickens** [comment]
Both Underscore and Star are used without the brackets.
The information in [brackets] is to tell you the alternatives or in {brackets} the number of characters involved.
ED

**Comment by Sherlock21** [comment]
there are 3 Johns in this test file - John1, John2 and John3 all LANGSTAFFE. but  John2 has the 3 letters after the initial LA all as UCF [___}.
its in ericb.WRYAAATSTMA55.csv

Furthermore, a search for Langstaffe finds John and John3 Langstaffe correctly BUT does not list in possibles the version for John2 LA{___]taffe - i.e. throne with the 3 UCF's in [  ].

I am Suspending testing for the present.

**Comment by Sherlock21** [comment]
I find that completely illogical!

Is Kirk's comment therefore just to remind us they there are more types of situation that we need to test in addition to the *  that I had done earlier?
 rather than telling me I had used the * in the middle of a name in the wrong manner ( as I took his comment to mean it should have been on parenthesis in the middle of the work just like alternative letters are?

**Comment by Sherlock21** [comment]
I confirm that i had just deleted a couple of comments of my own, because they were incorrect in the basic details of my observations.

Off on the right path now.

**Comment by Sherlock21** [comment]
Further testing shows:-

IF I have a mixture of UCF's in a single name - like LA___S*AFFE.  plus the proper full name in its 2 versions, LANGSTAFFE and LANGSRAFFE of which there is one of each of these 3 in the test table.
Then the version with a mixture of _ and * in it, does NOT get found in the search - whereas the correct full spellings do.

ALSO if I replace either: both the __ or the single * with a correct letter ( R or T), then the single ucf name does get found.

This sort of mix may not be regular feature, but I suggest its not unusual in hard to read images - instead to the Transcriber giving in and just putting one * after the first two real letters.

**Comment by Sherlock21** [comment]
UCF _{11,2} is found correctly.
UCF _ is found correctly
UCF * is found correctly
UCF ? is found correctly

So long as there is only one ucf in a Surname  - see above.

**Comment by SteveBiggs** [comment]
How is a UCF search performed? Is it by ticking the "Name Soundex" box or some other way?

Testing in test3 with an entry that was James MUZZLE, but I have modified the entry to be MU*LE and now searching for MUZZLE does NOT find the entry (with or without Name Soundex).

Feels like I am not searching for UCF correctly .....

**Comment by edickens** [comment]
You search for the full name, in this case MUZZLE.  The search should then find any relevant entries where the transcriber was not able to read the image and so had to use UCF .  Searching for MUZZLE should have found a transcription of MU*LE.  ED

**Comment by SteveBiggs** [comment]
That's what I thought. It doesn't find it though.

**Comment by Captainkirkdawson** [comment]
UCF records are often proposed as additional entries that a researcher could consider, They then appear as a separate list at the end. The exceptions are [ae] when both versions should be retrieved, also when there is an ? The record should be found with a search for the name with the ? stripped the detail will show the origina; entry

The best way of testing in the first step is using a file with the various known ucf encoding and then determining if you get the addition

A second phase is to check that making the change in an on-line edit works

**Comment by SteveBiggs** [comment]
But why doesn't searching  for MUZZLE find the entry MU*LE? Should it?

**Comment by Captainkirkdawson** [comment]
These extra' records are ONLY available on a place based search. Sorry I should have been clearer

**Comment by SteveBiggs** [comment]
Ok, so going back to my original example:
Ma*e PICKRYNG	Burial	28 Apr 1607	Norfolk	Hemblington
A search for example, Mabe does indeed return this entry as an additional entry.

I then made an on-line edit to the entry:
James MUZZLE	Burial	26 May 1809	Sussex	Newtimber
changing it to:
James MU*LE
and a search for MUZZLE does NOT return any additional entry so making changes in an on-line edit does not work.

**Comment by PatReynolds** [comment]
@Captainkirkdawson to have a look at this on return

**Comment by benwbrum** [comment]
This is covered in #1178
