### ISSUE TITLE
Revisit Researcher Registration page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1139]
Revisit registration page in light of changes made on Volunteer Registration, etc. before activation.

From discussion on #932:
EricD: For researcher registration perhaps we need a different, or cut down, registration form. I say this because they must not select "Syndicates available" because these are a reduced list of just those with data to transcribe. What might be more likely is the option to choose a county in which they are interested so that we can refine searches. But we are way ahead in V1.7 or even V2.

Pat:I think we need two distinct sign up forms.  One on the Volunteer tab, one
possibly with only an in-page icon, but that bit should be a separate story
in 1.7).

**Comment by Captainkirkdawson** [comment]
TY Pat.

I removed Alison's comments as they related to the Transcriber Registration form and have been fixed

**Comment by Captainkirkdawson** [comment]
Suggest this be closed until there is a clear rquirement
