### ISSUE TITLE
Prettify the browser URLs

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1145]
This might come as part of the FreePastPlace project, creating pages for each parish/piece/district, enhancing links to record offices, etc. etc.

**Comment by Captainkirkdawson** [comment]
Since I have no idea on what the FreePastPlace project might be nor what is the actual requirement this is responding to a size cannot be estimated

**Comment by Captainkirkdawson** [comment]
See #1144
