### ISSUE TITLE
Add option to manage userids to list incomplete registrations

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1146]
There has been a request for an option to be available to Syndicate Coordinators and to System Administrators that lists thhode userids that have not completed the confirmation process.

**Comment by Vino-S** [comment]
Thanks Kirk.
Are the incomplete registrations determined by the `sign_up_date`, `email_address_last_confirmed` in model `UseridDetails` or by any other logic involved ?

**Comment by Captainkirkdawson** [comment]
Good question. Only current place where it is computed is 
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/userid_details/show.html.erb#L49
Current registration process involves sign-up; receipt of email asking for change of password. The later has to be different from the temporary one which they do not know. Therefore registration is completed when password has been changed

**Comment by Vino-S** [comment]
Thank you very much Kirk.
I can use that logic.
I have another question: How can we determine the user is a `Syndicate Coordinators` and to `System Administrator`. 
I have gone through the `UseridDetail` model but could not find a appropriate column like is_admin to specify that.

**Comment by Captainkirkdawson** [comment]
I suggest we do it in 2 parts. 
The system administrator is the only person who has access to the Manage Userid action so lets deal with that first. 
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/controllers/userid_details_controller.rb#L203-L214 
generates the options list from the UseridRole list
https://github.com/FreeUKGen/MyopicVicar/blob/master/lib/userid_role.rb#L1-L159
The routes are unlikely to need modification
https://github.com/FreeUKGen/MyopicVicar/blob/master/config/routes.rb#L142-L159
As the selection goes to 
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/controllers/userid_details_controller.rb#L322-L355
From an appropriate action you can get the models to give you the userids to be listed and them then render the index with those

We will talk about the syndicate coordinator when this phase done

**Comment by Vino-S** [comment]
Thank you Kirk.

I will go through the reference and give a start.

**Comment by Captainkirkdawson** [comment]
Every userid has a person_role which defines their role within freereg and
UseridRole fines what a role can do

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Vino-S** [comment]
Hi Kirk,

I have pushed my code for this task for you to review and merge.
Please give me a feedback.

Many Thanks,
Vino

**Comment by Vino-S** [comment]
Hi Kirk,
I have done the following changes as per your suggestion.

1. Added an action link as 'SHOW' in the table to display more details
of the user.

2. Added border to the table.

3. Removed the 'ObjectId' from the table

Please Review and let me know if any changes required.

**Comment by Captainkirkdawson** [comment]
The code to list incomplete registrations has been implemented on test3 for review by 
@SteveBiggs  @edickens and a syndicate coordinator.

**Comment by edickens** [comment]
It works, but column headings do not line up.

![capture](https://cloud.githubusercontent.com/assets/8876165/24394693/dcfae7e6-1394-11e7-9c14-44d35f338347.JPG)

"Destroy" is still there when it was suggested that it be removed.  You can use "Show" and it will show the Profile, with Destroy if you have the necessary permissions.  So Destroy is not needed.

The breadcrumb after selecting "Show" does not take you back to listing the "Incomplete registrations" and so needs a lot of selections to get back to the list.

**Comment by edickens** [comment]
PS.  Showing the person's name as well could be helpful, but not essential as these are incomplete registrations.  But as a general principle when listing people we should show UserID, Name and email address, if there is room.

**Comment by SteveBiggs** [comment]
The columns line up fine on my PC using Chrome, but I agree about the
breadcrumbs problem. In fact, this issue is present with the all Manage
Userids options. They all point to 'Syndicate Options(all)' and when you
then select 'Incomplete Registrations' from there, you only get one result:

LLandeg lynnl58@yahoo.com all
Steve

**Comment by SteveBiggs** [comment]
This has now been addressed and tested by a Syndicate/County Coordinator and all appears to work fine.
