### ISSUE TITLE
Create action to return file from attic

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1148]
Create an action whereby a data manager can return a file from the attic.

**Comment by edickens** [comment]
Would it be better to allow SC to download from the Attic rather than actually return?  They can check that it is the right file before uploading .

**Comment by Captainkirkdawson** [comment]
Data manager can already download.

The attic should never be open to coordinators.

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
In retrospect this is likely a bad idea. Given that the DM can download from the attic any subsequent action can be done.
