### ISSUE TITLE
Record and Use data permissions - i.e. Open Data as it relates to the source 

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1150]
Part of #518, see also #525 which deals with other aspects of locks

**Comment by Captainkirkdawson** [comment]
Some clarification please
1.  This is a requirement to store permissions with the information on the source of the images from which the data is transcribed. As such the ability will be added to the source collection that is to be developed as part of the RAP/GAP/DAP

https://github.com/FreeUKGen/MyopicVicar/blob/master/app/models/source.rb

**Comment by Captainkirkdawson** [comment]
2. It is future assumed that open_data will be considered as such when a) the transcriber has accepted the agreement and b) we have documentation in the source collection that we have the required permission for it to considered open.

**Comment by edickens** [comment]
To show or distribute images of the registers requires the permission of the "owners" of the images or their copies.  So I suggest that permission needs to be recorded at Image Set level.  Not at individual images.  Even though the County Records Office may refuse, images can come from other sources with permission, so any level higher than the Set of Images would create exceptions.  I did think of Register Type level, but even then we could get some PR from one source and some more PR from elsewhere.

**Comment by Captainkirkdawson** [comment]
What is proposed is that it be at the source (As defined in the RAP/GAP/DAP specification) level which is what I believe your Image Set implies

**Comment by edickens** [comment]
Correct.  E

**Comment by PatReynolds** [comment]
@patreynolds to create flow chart

**Comment by PatReynolds** [comment]
Here is one way it might work: https://docs.google.com/a/freeukgenealogy.org.uk/drawings/d/1EXMcSgN0Gt20g61-GHezI73bKjDyst71CGaO3nSlYpc/edit?usp=sharing (with (1) and (2) and (3) being in any order).
But I am guessing that for the API it might be simpler to make a duplicate database by running the three rules.  And for our 'come here and pick it up' files, we make the files by running the three rules.  Only our 'bespoke' files, would we run a bespoke query using the two rules.
This story may be more about how a record relates to the three locks (or four if a DPA request and a 100 year rule are programmed differently).

**Comment by Captainkirkdawson** [comment]
I would suggest great care and thought needs to  carried out before ever adopting a duplicate database. Creating one takes  5-10 hours and  can lead to a lock out of active users unless done carefully. There have to be substantial benefits to warrant the cost

**Comment by Vino-S** [comment]
Would it be better if we can use existing database and create a new field that differentiates the new 3 rule processed records from the old ones.?

**Comment by PatReynolds** [comment]
Data protection requests are now covered by issue #1347

**Comment by Captainkirkdawson** [comment]
Image Sources are now defined as either open or not. Images will not be displayed if not open
Unless there is more that needs to be done I propose this be closed
