### ISSUE TITLE
Message system: permit mail outs by Open Data status of transcriber

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1151]

**Comment by Captainkirkdawson** [comment]
6, The message system will be amended to permit the inclusion/exclusion of recipients based on their agreement status.What status options do you envisage. Yes, No, Asked, Not asked, Considering

**Comment by PatReynolds** [comment]
Yes. No. Neither yes nor no. Also needs to have the options relating to
other emails (deceased, active, not active, do not contact, etc.)



Pat Reynolds
Executive Director, Free UK Genealogy

**Comment by Captainkirkdawson** [comment]
Suggest we use a new array field for the Open Data License agreement. Accepted. Declined. Unknown. Requested.

**Comment by Vino-S** [comment]
Volunteer Agreement for existing users is almost complete.  The default status of transcription_agreement will be "Unknown". The status will be updated to "Accepted" or "Declined" based on the user input. 
A mail will be sent to all users whose transcription agreement status is "Unknown" through our message system and the status of transcription_agreement will be updated to "Requested".
Do we have any existing message system or should it needs to be created from scratch?

**Comment by Captainkirkdawson** [comment]
There is an existing operational message system. See
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/models/message.rb
There are asociated views and controller.
Accessed through the Message System Action

**Comment by Vino-S** [comment]
I have noticed that if the user does not select any recipients in the **Send Message** page of message system and clicks on the **Send** button, it throws error(We're sorry, but something went wrong with processing your request....). 

Do you want me to add some validation to check the mandatory values before we click send? If so please tell me which are the column values are mandatory to select.

Thanks

**Comment by Captainkirkdawson** [comment]
The number of recipients has to be greater than 0 so  it is likely that the test should be in the communicate method
