### ISSUE TITLE
Ensure that volunteers' personal data is only viewable by their point-of-contact, and upwards

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1153]
Point of contact for Transcribers is SC and CC; policy/story may need broadening, so that others can see email addresses / contact through system as appropriate

**Comment by SteveBiggs** [comment]
@Captainkirkdawson can you clarify which others can see the email address and in which view? For example, transcribers cannot see others' email addresses.

**Comment by Captainkirkdawson** [comment]
I have misspoken and I am glad you have requested clarification.
There are 2 actions for Userids. 
Manage and Display. Display is a restricted set of actions permitted on userids, However BOTH currently use the same listing of the fields in a profile
Manage is restricted to volunteer_coordinator, system_administrator, project_manager and executive_director. They can browse, select, show, edit, create and destroy all profiles. (The latter only if there are no transcriptions). The syndicate_coorditor also has the full Manage actions but only for their syndicate members
Display is available to contacts_coordinator, county_coordinator, country_coordinator, data_manager, documentation_coordinator and engagement_coordinator. They can select (by email, userid and name) and show a profile. They cannot browse, edit, create or destroy a userid.
It would be quite practical to restrict the display fields to a small number of fields.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs You are quite correct a transcriber cannot access any other profile than their own

**Comment by PatReynolds** [comment]
It seems we are happy that only people with a business need to see an email address can see it.  So I'll close.  Please re-open if you know of someone who does not have a business need being able to see an email address.
