### ISSUE TITLE
Search without county.

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1162]
Currently we advertise the option of search for a named person anywhere provided that a record type and date range is included.
This search actually conducts a search in every county in the database. The probability of it actually ever completing the search is extremely low.
To make the search ever have a chance of completing we need to add a further set of indices that do not include a place or county. An alternative would be to never permit the selection of all counties but restrict it to up to 3 counties.

**Comment by edickens** [comment]
The problem with removing this facility is to do mainly with burials.  Someone may know where they died, but not where they were buried.  You need to search the whole country.  For example.  My Dad died in Bath but his grave is in Torquay, the family grave.
Similarly with marriages..  If you know where the groom lived, but he got married in the brides parish, then that may be at the other end of the country.

**Comment by Sherlock21** [comment]
I agree with Eric D, but for point 2 - marriages - if you implement the request of mine to allow search of ABODE, then you find all these persons who married outside the Bride's Place - if we count ABODE as a key field validated against Place Name.

**Comment by Sherlock21** [comment]
Searching on ABODE could also be useful for research Statistics purposes too.

**Comment by Captainkirkdawson** [comment]
As a minimum we should insist on both forename and surname to at least having a chance of limiting the search. How many smiths were born in a year in the UK???? Remember the search does not stop on number of records; the only limit is the amount of time! The return of records is limited but the search is not.

**Comment by Captainkirkdawson** [comment]
Soundex searches without a county rarely if ever finish as soundex is not very discriminating. It should not be permitted

**Comment by benwbrum** [comment]
In addition to burials, researchers in North America are often unlikely to know any place information except for nationality for ancestors who emigrated from the UK prior to 1800.

**Comment by Captainkirkdawson** [comment]
I agree there is a requirement but we need to be able to respond to that requirement.

I do not think that requiring forename as well as surname is unreasonable or is removing the soundex  for searches with no county given that their current searches produce  no results because they time out

**Comment by Captainkirkdawson** [comment]
Currently  0.3% of our searches time out. (Note this is  much better than it was 3 months ago) Half of those are searches without a county. If we were to impose the suggested limitations we could increase the time limit and thereby improve the likelihood of the search returning results

**Comment by PatReynolds** [comment]
I would be very reluctant to remove this feature.  One of our arguments for existence is that we allow researchers to search across the geographic boundaries of the institutions which curate the records.  Requiring a first name too would be ok as a temporary measure, but not ideal long term.  If it remains an issue after other performance issues are addressed, we should look at alternatives.

**Comment by Captainkirkdawson** [comment]
Replaced by 1170 and 1171
