### ISSUE TITLE
Image server access has stopped.

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1164]

**Comment by edickens** [comment]
Has anything been done to where the FreeREG images are held?  I cannot get in and just get "Connection closed".  I have tried a few times and get the same result.  I have never had this before.

**Comment by edickens** [comment]
Still cannot allocate images.

**Comment by edickens** [comment]
Steve says that Getscan works, but my BitKinex does not.
Transcribers waiting for image allocation.

**Comment by Captainkirkdawson** [comment]
L

Is this a byproduct of the https changes to FreeBMD???

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Could be.  I think BitKinex cannot get access to the folders.  This is what I get:-
![capture](https://cloud.githubusercontent.com/assets/8876165/24476963/331c1abc-14cd-11e7-98f2-e1e033a749c3.JPG)

Perhaps Ben Laurie or someone can tell me what I need to change.

**Comment by edickens** [comment]
PS.  See the dialogue  at the bottom of the image.  E

**Comment by edickens** [comment]
PPS.  It has only happened today.  I am allocating images twice a day, so it has happened since yesterday.

**Comment by lemon-ukgen** [comment]
The timing definitely corresponds to making images https-only.
The screenshot shows that the client is correctly following the redirect, but doesn't suggest why it can't access the URL.

Regular browser access to https://images.freereg.org.uk/regimages/ is fine.

So it looks like a shortcoming of BitKinex at this point. I've added some debugging to help see what's going on.

**Comment by edickens** [comment]
Thanks Lemon.  This is urgent, so if there is anything I can try,let me know.

This is my BitKinex login screen...
![capture](https://cloud.githubusercontent.com/assets/8876165/24493156/b5eb2340-1525-11e7-90ea-c6e7c6f1426f.JPG)

Is this a clue?

**Comment by lemon-ukgen** [comment]
On 30/3/17 08:49 GMT Eric Dickens wrote:
> Thanks Lemon.  This is urgent, so if there is anything I can try,let me know.
>
> This is my BitKinex login screen...
> ![capture](https://cloud.githubusercontent.com/assets/8876165/24493156/b5eb2340-1525-11e7-90ea-c6e7c6f1426f.JPG)
>
> Is this a clue?
>

What happens if you update the BitKinex configuration from

   http://images.freereg.org.uk/regimages

to

   https://images.freereg.org.uk/regimages

?

The debugging I turned on yesterday shows BitKinex trying to http:// 
version, being redirected but not then trying https://

This is contrary to what your first screenshot showed, so strange.

Please let me know if changing your local config to https:// helps.

**Comment by lemon-ukgen** [comment]
I have confirmed the WebDAV connection works on https using a CLI 
client. It's fine.

```
$ cadaver https://images.freereg.org.uk/regimages
Authentication required for Image Edit on server `images.freereg.org.uk':
Username: lemon
Password:
dav:/regimages/> ls
...
Coll:   zannetta                               0  Dec 15  2015
dav:/regimages/>
```

**Comment by edickens** [comment]
Have tried that change..

![capture](https://cloud.githubusercontent.com/assets/8876165/24502518/0985f2ee-1546-11e7-8c66-1b193f07edbb.JPG)

and I get a different dialogue but it still does not work...

![capture1](https://cloud.githubusercontent.com/assets/8876165/24502581/533cd40c-1546-11e7-8f6b-7af9ab4dae00.JPG)

**Comment by lemon-ukgen** [comment]
On 30/3/17 12:42 GMT Eric Dickens wrote:
> Have tried that change..
>
> ![capture](https://cloud.githubusercontent.com/assets/8876165/24502518/0985f2ee-1546-11e7-8c66-1b193f07edbb.JPG)
>
> and I get a different dialogue but it still does not work...
>
> ![capture1](https://cloud.githubusercontent.com/assets/8876165/24502581/533cd40c-1546-11e7-8f6b-7af9ab4dae00.JPG)

So your client is still connecting on port 80 (http) but instead of 
saying "please give me the listing at the path `/regimages`", it's 
saying "please give me the list at the path 
`https://images.freereg.org.uk/`" which is nonsense, that's not a path!

Is there any option to set port 443 / https in the data source config? 
All I can find in doc is this

   http://www.bitkinex.com/ftp/help/html/dsprophttp.html

which suggest there's a HTTP Server > Security option but not what 
options are available to you. What's it set to, and what options are there?

**Comment by edickens** [comment]
I just copied and pasted as requested above.

There is a Data Source dialogue...

![capture](https://cloud.githubusercontent.com/assets/8876165/24503057/6307fa72-1548-11e7-83d5-6677b86399d4.JPG)

What do I do here?

**Comment by lemon-ukgen** [comment]
On 30/3/17 12:57 GMT Eric Dickens wrote:
> I just copied and pasted as requested above.
>
> There is a Data Source dialogue...
>
> ![capture](https://cloud.githubusercontent.com/assets/8876165/24503057/6307fa72-1548-11e7-83d5-6677b86399d4.JPG)
>
> What do I do here?
>
>

Please check out what your options are in the Security knob. Choose SSL 
/ TLS or HTTPS.

**Comment by edickens** [comment]
What is the "Security Knob"?  Security does not seem to be an option that I can find.

**Comment by edickens** [comment]
Is this what you are thinking of?

![capture](https://cloud.githubusercontent.com/assets/8876165/24504387/0064b0d0-154e-11e7-8091-2eaf8e30a96c.JPG)

But it still does not work.

**Comment by lemon-ukgen** [comment]
On 30/3/17 13:37 GMT Eric Dickens wrote:
> Is this what you are thinking of?
>
> ![capture](https://cloud.githubusercontent.com/assets/8876165/24504387/0064b0d0-154e-11e7-8091-2eaf8e30a96c.JPG)
>
> But it still does not work.
>
>

1. Are there any other options, other then SSL? If not, please keep it 
on SSL.

2. Please try putting :443 after images.freereg.org.uk in the Server 
Address field

**Comment by edickens** [comment]
Set this up:-

![capture1](https://cloud.githubusercontent.com/assets/8876165/24507635/df564c2c-1558-11e7-9185-a6b6672cbd2b.JPG)

But then, although it looked as if it was looking for the folder, I got this message.

![capture](https://cloud.githubusercontent.com/assets/8876165/24507675/0087cc54-1559-11e7-9ae7-7b8bc07dd50f.JPG)

**Comment by edickens** [comment]
SSL and None are the only options in that Security pick list.

**Comment by lemon-ukgen** [comment]
So that's some progress. The failed SSL negotiation suggests BitKinex is using old ciphers. I've relaxed the set the server will accept. Please can you try again?

**Comment by lemon-ukgen** [comment]
Fresh BitKinex activity in the logs, so I guess that's working?

**Comment by edickens** [comment]
BINGO

I'm in.

Thanks.

Eric

**Comment by edickens** [comment]
I spoke too soon.

It won't let me copy.  And probably make other changes.

![capture](https://cloud.githubusercontent.com/assets/8876165/24508584/c10ba462-155b-11e7-91c1-aa2d7e5aeedd.JPG)


E

**Comment by edickens** [comment]
Still not working.  I cannot copy and paste.

Have I got edit permission?

**Comment by edickens** [comment]
Still not able to copy and paste so cannot allocate work to transcribers.

A better error report here, but difficult to trap it as it is scrolling...

![capture](https://cloud.githubusercontent.com/assets/8876165/24519635/adba63f4-157d-11e7-8f93-7638a78a7c4c.JPG)

**Comment by edickens** [comment]
Still the same problem so I cannot allocate work to transcribers.

**Comment by edickens** [comment]
Still not working and I now have images that need to be uploaded.  E

**Comment by edickens** [comment]
Hi Lemon,

Done,

But I cannot see the folders now.

![capture](https://cloud.githubusercontent.com/assets/8876165/24543275/eea431f0-15f6-11e7-8bf4-205f4a241af3.JPG)

**Comment by edickens** [comment]
I did this:-

![capture](https://cloud.githubusercontent.com/assets/8876165/24543343/32dd7854-15f7-11e7-8af4-f2688791b77b.JPG)

This is how it used to be,

**Comment by lemon-ukgen** [comment]
Please can you change the Server address to imagemaster.freereg.org.uk ?

**Comment by edickens** [comment]
If it is any help.  Getscan works fine.  Transcribers can see their images.  So it must be BitKinex and my write instead of read only permissions.

**Comment by edickens** [comment]
No luck.  I can't see the folders.  I still have security as None.

![capture](https://cloud.githubusercontent.com/assets/8876165/24543905/3ed074ac-15f9-11e7-9cf1-ac8ef4826433.JPG)

**Comment by lemon-ukgen** [comment]
Once more please?

Sorry about the back and forth, I don't Windows or BitKinex to test this 
with. All I can do is watch the logs and see what doesn't work :/

**Comment by edickens** [comment]
Great.  Copy and paste now works.

What now, because the transcribers use of Getscan.pl will not look at imagemaster.

**Comment by lemon-ukgen** [comment]
On 31/3/17 10:12 GMT Eric Dickens wrote:
> Great.  Copy and paste now works.
>
> What now, because the transcribers use of Getscan.pl will not look at imagemaster.

This is an exception just for you, using BitKinex, to do your work.

Transcribers can use the regular URLs (which are now redirected to 
https). The data is the same underneath.

We'll need to sort this out in the long term, since in this workaround 
we're still sending passwords over http://

**Comment by edickens** [comment]
Thanks Lemon.

This is all going to be replaced in FR V1.5 when we get the RAP (Records Available Page) and allocation of images is done through the server by Syndicate Coordinators.
Kirk and Bev have already done a program to link the images to FR, but they many need to see if this still works, although they are Read Only.
We will need a routine in FR for County Coordinators to upload images.  It is just not viable for me to do all the uploading and organising of the images.

Eric

**Comment by lemon-ukgen** [comment]
On 31/3/17 10:26 GMT Eric Dickens wrote:
> Thanks Lemon.
>
> This is all going to be replaced in FR V1.5 when we get the RAP (Records Available Page) and allocation of images is done through the server by Syndicate Coordinators.
> Kirk and Bev have already done a program to link the images to FR, but they many need to see if this still works, although they are Read Only.
> We will need a routine in FR for County Coordinators to upload images.  It is just not viable for me to do all the uploading and organising of the images.
>

Ah, great, thanks for the background. Cheers for your patience in 
getting this resolved, and sorry it broke in the first place.

**Comment by edickens** [comment]
No problem.  We are in a state of development throughout the database so these things happen quite frequently.
Eric
