### ISSUE TITLE
person_role

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1166]
The person_role check. We have not systematically checked that a person was entitled to execute the specific action being executed. We had assumed that since they were logged in (this is checked) and since they were using the action they were permitted to use the action. In most cases  there was implicit checking because because we were having to get their county or syndicate on which the action was to be executed. If we are to do this check on a systematic basis then we likely need consider moving the person_role from a hierarchical string to an array of roles. This would simplify understanding and coding. This has been suggested previously and most recently by Doug with respect to FC.

**Comment by richpomfret** [comment]
Into the archive - will return to it if needed.
