### ISSUE TITLE
Create userid

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1167]
The action to create a userid fails as a result of the code introduced to trap bot registrations.

**Comment by SteveBiggs** [comment]
Is this ready for test in test3?

**Comment by Captainkirkdawson** [comment]
Yes; has not been deployed to production which is why you just had that crash!

**Comment by SteveBiggs** [comment]
Good. Just tried it on test3 and that worked fine.

**Comment by Captainkirkdawson** [comment]
Plan to deploy that and other code changes including the incomplete
registrations code later today when it gets quieter. Missed my normal slot
on Friday!!

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by SteveBiggs** [comment]
Create ID tested and working on production site.
