### ISSUE TITLE
Viewing of Images

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1168]

**Comment by edickens** [comment]
I have just been uploading some more images and their quality is very variable due to different (faded) inks and damage.  So when the CC views them to assess the quality, or the transcriber views them for transcribing, or the researcher views them (subject to permissions) then it would be a great advantage to have an "Image enhancer".  This would allow the brightness and contrast to be varied, but not saved.  Quite often on one pages it is necessary to enhance some entries but not others, and the camera that created the image would only have taken the average.

**Comment by Captainkirkdawson** [comment]
Is there not one with WinFreeREG?

**Comment by edickens** [comment]
Yes, there is a split screen system to view images while transcribing.  But you have to be transcribing.  I'm suggesting that this is needed when uploading and assessing images for difficulty, and researchers will need it for when they can view the images.  I also think that the WinFreeREG viewer is a Windows facility, so not suitable to use on the website.
FreeBMD1 has such an action...
![capture](https://cloud.githubusercontent.com/assets/8876165/24585500/d0b0758a-1783-11e7-9340-c06140a48e98.JPG)
...and this allows different formats of the images.
But what prompted me to raise this was not the inclusion of a viewer, but that the view should let you change the contrast and brightness to cater for variations, even within the page.

**Comment by Captainkirkdawson** [comment]
But BMD does not provide a viewer. It downloads the image to your computer and you use whatever image viewer you have installed on your computer.

**Comment by edickens** [comment]
Is that all that is needed if researchers are using a Tablet or other device?  I don't know how they work.
Also, will we be able to download different formats?

**Comment by Captainkirkdawson** [comment]
Yes, tablets and smart phones all have good image viewers.
Expect we would download different formats as well.
