### ISSUE TITLE
batch name with Year range does not match the facts ion the batch concerned.

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1169]

**Comment by Sherlock21** [comment]
IN Production, WRY/ Active Places/ Queensbury/ Queenshead Baptist / Unspecified takes one to the 2 files there - a Baptism batch and a Burial batch.

BOTH are by UserID = JanetOgden . Its the Baptism batch that concerns us.
filename WRYQUBBA.csv.
But in the view that shows the year range in this batch, this one shows: 2020-1530 .

SO how can it show a year in the future, as the start year?
Furthermore  the decadal shows zero in every year.
Yet in the Header view, of this batch, it says: Number of Records = 1684.

File was uploaded 26 Nov 2013 with nil errors.

I have downloaded the file and checked it through: there is nothing I can find wrong with the data. Nor can the CC concerned.
I have done a search of a randomly selected record in the data, and the search lists the correct record.
SO where does the mystery year range come from?
And Why does the decadal show  all zeros?

**Comment by Captainkirkdawson** [comment]
There are no baptism dates just birth dates

**Comment by Sherlock21** [comment]
But I though that we had previously discussed the topic and determined that if there was birth date, to use it instead of the Baptism date?
Or did that not get into being?

**Comment by Captainkirkdawson** [comment]
We did.

We did not go back and reprocess existing files; we never do.

To reprocess the files after every change in code would be a massive
undertaking. We would have to essentially revert to BMD/FR1 style
processing.

Suggest you replace the file and see what happens

K



Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
Thanks.
We will give the Reprocessing a try.

I forgot about the "dont go back” bit.

Eric b
