### ISSUE TITLE
Require forename and surname for all county search

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1170]
Both forename and surname all county searches are max timing.
Implement requirement that both a forename and a surname are required for an all county search

**Comment by edickens** [comment]
Can the forename include Wildcard?

**Comment by Captainkirkdawson** [comment]
Yes

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Coded limit deployed to test3
