### ISSUE TITLE
Increase search time limit

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1172]
If 1171 and 1172 prove effective then increase max time to 180 sec from 100

**Comment by Captainkirkdawson** [comment]
As requested in the 26 April scrum we extracted the longest running 100 searches on brazza for April 26. There were 2500 searches in total so you will see that  only 1% of the searches timed out.
Column 1 is the running time. Column 2 the time of execution. Column 3 is the number of results. Column 4 is the search index used.

[brazza search times.xlsx](https://github.com/FreeUKGen/MyopicVicar/files/959558/brazza.search.times.xlsx)

**Comment by Captainkirkdawson** [comment]
@richpomfret @PatReynolds @benwbrum @dougkdev  @edickens  @SteveBiggs to review and comment

**Comment by SteveBiggs** [comment]
I assume running time is in msec? This suggests to me that we could increase the max search time to around 150 sec and the vast majority would not timeout.

**Comment by edickens** [comment]
Interesting that all but six which timed out had no results.  So I venture  to suggest that even if they went on for another 5 minutes they still would not have found anything.  It would be interesting to know what they were trying to find and then reproduce it.  The six which did find results may have just been unlucky.  My recommendation is that there is no need to increase the time out time and so save some totally unnecessary processing.

**Comment by SteveBiggs** [comment]
Kirk, why did some searches continue beyond 100 secs and return results while others appear to have stopped at 100 secs with no results? For example, the one that took 137 secs returned 1 result - presumably at the end of the 137 secs .....?

**Comment by Captainkirkdawson** [comment]
Steve, 1) yes they are msec. 2) The time out is not a precise measure. 

MongoDB targets operations for termination if the associated cursor exceeds its allotted time limit. MongoDB only terminates an operation at one of its designated interrupt points.
MongoDB does not count network latency towards a cursor’s time limit.
Queries that generate multiple batches of results continue to return batches until the cursor exceeds its allotted time limit.

**Comment by Captainkirkdawson** [comment]
EricD
If a search is terminated we do not know how any ,if any, results had been retrieved up to that point. 
As a result you cannot make any conclusion as to what they might/might not have done.

**Comment by edickens** [comment]
I had assumed that the third column in the spreadsheet was the number  of search results, but I suppose it would only be if the search had completed.  E

**Comment by PatReynolds** [comment]
What is sd and ssd?  Start date and stop date?
What is column C, please?

**Comment by Captainkirkdawson** [comment]
@PatReynolds 
sd; search date and ssd: secondary search date. The former is the main date in the event eg baptism, marriage, burial date. The latter is a second date for the same event eg birth date.
The 4th coulmn is the index used to satisfy the search,  It therefore reflects the type of search entered. If you see sdx it was a soundex search. If there is a fn then the search criertia contained a forename. etc
The third column is the number of results returned by the search, It is blank if the search timed out

**Comment by PatReynolds** [comment]
Thanks - nothing struck me.

**Comment by Captainkirkdawson** [comment]
No longer required
