### ISSUE TITLE
Dates in Burial Records: Death or Burial?

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1175]

**Comment by Sherlock21** [comment]
Registers of the Church of England use the Burial date in the main, but there are other denominations which do not record Burial date but rather have the phrase "Died".

SO in the spirit of TWYS, should we not have a field for Date of Death as well? And these 2 dates me well be months apart in modern times. 

Also in the case of taking our records form the GRO ' Death Certificate it is clearly Date of Death.

It would be too much extra effort to the Transcriber to have to write a note in each record in a Transcription saying " the date is actually the date died" in such cases.

**Comment by Captainkirkdawson** [comment]
Dependant on 809 Flexible CSV
