### ISSUE TITLE
Messages waiting expansion?

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1176]
The messages waiting system was designed for messages created and sent through the Message system
Does it require extension to other emails sent to users

**Comment by edickens** [comment]
Replies to Contact Us emails would be useful, but these are not usually for those with UserIDs.  But Replies to messages would be useful.

**Comment by Captainkirkdawson** [comment]
But this system only tracks messages sent by the message send system. It has no connection to other email/website messages

**Comment by richpomfret** [comment]
To review once we are in a position to implement further changes.

**Comment by PatReynolds** [comment]
Contact system needs a 'reply' function.

**Comment by PatReynolds** [comment]
'Messages waiting' for other communication would be useful (e.g. contacts, infomation from the Images system re. uploads, etc. etc.)
