### ISSUE TITLE
Access to update schedule denied

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1179]

**Comment by edickens** [comment]
I don't know why, but Firefox has denied me access to the update schedule at http://freereg1.freereg.org.uk/update.html
It has always worked for the last ten years or more...
![capture](https://cloud.githubusercontent.com/assets/8876165/25046580/1585f612-212a-11e7-9f71-5ec6e51e0cdc.JPG)

**Comment by edickens** [comment]
Perhaps this is why SpamCop is blocking us when someone has a look at FR1?

**Comment by Captainkirkdawson** [comment]
You have never user a secure connection to access F1. All Firefox is doing now is telling you that. We  have no plans to make F! secure.
I suggest that you use https://www.freebmd.org.uk/update.html
This has nothing to do with spamcop

**Comment by edickens** [comment]
TY
This can be closed now.
E
