### ISSUE TITLE
Migrate FreeCEN to FreeREG so that researchers can link people(Is this still relevant?)

### ISSUE THREAD

**Issue by graphiclunarkid** [FreeUKGen/MyopicVicar#118]
The migration requires a deep knowledge of:

1. FreeCEN's practices;
2. the problem domain of representing census records, and;
3. the FreeREG code-base @captainkirkdawson and @benwbrum developed.

The work will be divided as follows:

1. Converting the fixed-length text file format FreeCEN uses in order to load FC1 data into FC2
2. Modifying Kirk's CSV uploader/processor and the search record converter to handle FreeCEN data
3. Modifying the coordinator tools to accomodate FreeCEN's processes.

**Comment by PatReynolds** [comment]
This now happening as a separate project, with its own WaffleBoard
