### ISSUE TITLE
Can't logout

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1180]

**Comment by edickens** [comment]
I closed my browser before logging out, so when I went back in, I was still logged in.  But got this message...

![capture](https://cloud.githubusercontent.com/assets/8876165/25070545/7803af6c-2299-11e7-9a13-d1786f464514.JPG)

However, whne I went back to the HomePage, I was still shown as logged in and I do not have an option to log out.  Also, whenever I try to do anything, such as select "Actions" I get page not found, just as I do if I select "Logout".

**Comment by Captainkirkdawson** [comment]
Clear your cookies See solution to this in #949

**Comment by edickens** [comment]
Of course.  Perhaps such a note with the message because we never remember and it will always be necessary.  TY
