### ISSUE TITLE
Add donate button to search detail page

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1181]
Do in essence the same as #938 except no need to put a new helper in the helpers folder. Need to add the helper call in the search record controller similar to the search queries controller.
Modify the show view for search records

**Comment by Captainkirkdawson** [comment]
Could you pick this up as you have just completed 938

**Comment by Vino-S** [comment]
Sure Kirk. I will do.

**Comment by Captainkirkdawson** [comment]
Vino
Could you remove the second link to the donation page
![donate](https://user-images.githubusercontent.com/2874694/27157381-79593b62-511e-11e7-8ae7-944ab79ce812.JPG)

**Comment by SteveBiggs** [comment]
This has been completed.

**Comment by Vino-S** [comment]
Hi Steve,
You mean that the link(Make a Donation), the one Kirk asked me to remove has been done?

**Comment by Captainkirkdawson** [comment]
Not to my knowledge. It is still there in the details page (not the results page)

**Comment by Vino-S** [comment]
Thanks Kirk.
I will update and push the changes

**Comment by SteveBiggs** [comment]
My apologies, I was looking at the results page.

**Comment by SteveBiggs** [comment]
Extra link has now been removed.
