### ISSUE TITLE
Incomplete registration

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1184]
I was looking at the incomplete registrations. There are 100 of them. 
Looking at them I observed that 23 of them relate to the STS  syndicate.
Interestingly the majority of them have files loaded. 
It seems that they are userids set up by the coordinator for people he is either loading on behalf of or has to whom he has assigned files.
In some cases they are shown as active, in some cases they are inactive. In no case are they shown with the SC as loading for them.

At least one of them if for an email address for which we get spam responses

There are likely 2 actions 1) the SC should add the uploading flag for these people 2) we should not send processing messages to incomplete registrations

**Comment by edickens** [comment]
I go for 2).   And I would even delete incomplete registrations after 7 days.  The volunteer can only set their password within 24 hours, so after that the UserID has to activated by the SC sending a password reset and the volunteer should have contacted the SC if they are having problems.

**Comment by SteveBiggs** [comment]
But Eric, you can't delete the user if they have files uploaded. The SC should set the uploading flag which will stop processing messages being sent. If these have been set up by the SC, would it be useful if the SC could complete registration on behalf of the transcriber?

**Comment by Sherlock21** [comment]
So, transfer those files to the Cc's ID, (So as not to loose the effort) then you can delete the user?

**Comment by SteveBiggs** [comment]
EricB, the files should remain under the transcriber because they produced them and it is they who must be asked to sign the open data agreement for the files they 'own'.

**Comment by edickens** [comment]
The point is that the files should not have been there in the first place because the registration was not complete and so the agreement was not accepted or the UserID was not marked as files uploaded by the coordinator.  In the case of an incomplete registration with files, then the registration should just be completed, by the coordinator if necessary.  We shouldn't have incomplete registrations.  E

**Comment by SteveBiggs** [comment]
I think we are in agreement - these userIDs were (apparently) created by the SC in order to be able to upload files on their behalf. So when the SC creates such userIDs, they need to be sure to complete the registration.

**Comment by Captainkirkdawson** [comment]
You must remember these were created a) before we worried about the open
data; b)before we had the SC loading flag ; c)we have urged SC to create
userids for userds for whom they were uploading rather than putting them in
their own ID; d) where files had combined by an SC on FreeREG1 we asked CCs
to place them in  an appropriate Uuserid when the file needed cleaning up.;
and e) the SC/CC does not get the registration completion email so cannot
complete the registration.

So it is inappropriate to say they should not have been there, It is not
possible to delete those that have files (the system will not do it). Nor
can  a SC/CC complete the registration for a userid unless they use an
email address they own.

I recommend that we ask the SC to add the uploading flag.

We will add the incomplete registration to the filter on not sending emails
to userids

The incomplete status will be useful knowledge on sending messages
 regarding open data

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
But in my view, the answers buy Steve &Kirk do not get to the bottom of the real issue: we have batches online that are said to "belong" to a person, who very soon, will never have accepted the Agreement nor declined to do so.  

So you get the apparent owner to complete the registration properly or you throw then off. there are no other options in Pat's proposed Legal arrangement were there?

**Comment by SteveBiggs** [comment]
Why do you say they will not accept the agreement? We don't know if they've been asked to yet. They could be actively transcribing with the CC uploading their files (I have some in my syndicate) in which case they will be asked. If they are lapsed members then like all inactive transcribers we must attempt to contact them to sign the agreement. It's only those that we cannot contact that we need to decide what to do with their files - whether they have completed registration or not.

**Comment by Captainkirkdawson** [comment]
While these last comments are worthy of consideration it is part of the open data story not as part of the story on dealing with incomplete registrations created by a coordinator

**Comment by PatReynolds** [comment]
In what way are these registrations incomplete? Why have the Transcribers
not been asked to complete them (the ones with transcriptions)?

Thanks,

Pat

Pat Reynolds
Executive Director, Free UK Genealogy

**Comment by SteveBiggs** [comment]
I believe these are mainly userIDs that have been created by the SC/CC on
behalf of a transcriber who does not want to upload directly to FR. So the
transcriber sends their files to the CC who them checks and uploads them
into the transcribers ID. The transcriber would have been sent an email to
complete registration when the ID was created for them - assuming it used
their own email - but some CC's have created email addresses using the
'name+other@' format that may not have gone back to the transcriber to
complete registration.

Each one should be looked at individually to see how the ID was created and
if the transcriber is still active, registration should be completed.

Steve


Stephen Biggs
FreeREG Chairman

**Comment by edickens** [comment]
I created quite a few UserIDs when I divided up the files that Dave Newbury had uploaded in the early days.  Dave has died and I do not know the transcribers, although some files have names and some have email addresses in the headers.  Some could be Dave's own files.  Remember that a lot of transcribers are retired and we have been transcribing for nearly 20 years so we must be very sensitive when demanding acceptance of the Agreement as the transcriber may no longer be alive and a relative will get the email,  Dave's files were created around 2000 to 2005.

**Comment by PatReynolds** [comment]
Steve to contact coordinators, asking them to 
a) delete any incomplete registrations WITHOUT files and
b) mark up any incomplete registrations WITH files but where the transcriber cannot complete the registration (e.g. deceased, uncontactable) - nb do NOT change email address or name of person - just mark as 'deceased', etc.
c) ask contactable transcribers of incomplete registrations WITH files to complete them.
