### ISSUE TITLE
Incompletes not added to image server

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1199]
The Image Server file, which is created every night, should not include anyone whose registration is not complete. This will avoid lots of Folders being set up which have to be deleted.

**Comment by bev-fc** [comment]
Pat, I do not know the scripts running on Image Server

**Comment by edickens** [comment]
Bev,

There is a file created every night by the FR server which the Image Server uses to update its information on transcribers.  The point being made here is that the UserID of Incomplete Registrations should not be in this file so that the Image Server does not take them to be active transcribers.

EricD

**Comment by bev-fc** [comment]
Eric, Pat, sorry I am not aware of this task, is it a cron job? There are still a lot of functions supported by freereg I am not aware of, @Captainkirkdawson would be the best person to receive all issues at first place, it will be my pleasure to do what I can under the direction of Kirk.

**Comment by Captainkirkdawson** [comment]
@bev-fc its the simplest of rake tasks

FYI you will not have to access the cron task just modify the rake task. The cron tasks just takes the rake task.

https://github.com/FreeUKGen/MyopicVicar/blob/master/lib/tasks/extract_userids_passwords_for_image_server.rake

In addition to do passing incomplete userids @edickens  @SteveBiggs should we stop sending inactive?

**Comment by edickens** [comment]
A good idea Kirk not to send Inactive.  They will have been created in IS but this file could be useful in future.
