### ISSUE TITLE
Search engine features

### ISSUE THREAD

**Issue by graphiclunarkid** [FreeUKGen/MyopicVicar#120]
1. Support Multiple/Hyphenated Surnames
2. Search UCF
3. Search Wildcards
4. Visualize results on a map
5. Show number of records searched
6. Allow result to be bookmarked.
7. Non-soundex fuzzy search support
8. Remaining bug fixes

**Comment by Captainkirkdawson** [comment]
Many of these are already separate stories eg 1,2,3,7
