### ISSUE TITLE
Multiple contacts being generated

### ISSUE THREAD

**Issue by CommsCoord** [FreeUKGen/MyopicVicar#1201]
Today have had three separate issues with multiple duplicate contacts being generated. Here is the list:
Volunteering
75120514 
75121216 
75121215 
75121218 x3
75121219
75121220
75121221  
75121222 x2
75121223 

SSX
75098452
75098475 
75098430

STS
75085286   
75085380 
75084896 

As you can see for the contact Volunteering there were duplicates of duplicates being generated. Would have suspected it was the fault of person sending contact, but three times in a row makes me suspect the website is at fault

**Comment by richpomfret** [comment]
Could we have a bit more info? Perhaps we can try and replicate this.

**Comment by edickens** [comment]
An example:-
Comment 75120514 at 10:45 on 2017-05-19 from Jacky Long jackypat0809@gmail.com which said:-
Can you tell me what is involved in volunteering as a transcriber please. I have done some transcribing for another genealogy site. Can I do it from home? Will I be emailed or sent the data which needs transcribing? Thank you
There were a number of emails with identical text.  Unfortunately only one is left in the list of Comments, but if someone can look in the log, they may see how many there were and how close together.
This does not help us to know if she hit the send button many times or actually send a number of messages and just copied and pasted the text.
She is not a registered transcriber, as one would expect as she is interested in joining.  She has not done so yet.
Perhaps we need to catch this as soon as it happens.

**Comment by Captainkirkdawson** [comment]
Thank you Eric. 

While the duplication is irritating surely the volunteer coordinator is responding regardless to bring the volunteer on board?

**Comment by edickens** [comment]
I think it was more a concern for it being a program fault, but I cannot see a pattern as yet.

**Comment by Captainkirkdawson** [comment]
I was a) concerned that these were fake contacts similar to the registration issue we had and b) if real the volunteers were being recruited regardless of duplication.

**Comment by edickens** [comment]
Have not had notice of any more.  E
