### ISSUE TITLE
Add skill level and Latin questions to sign up

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1202]
Are these needed?

**Comment by edickens** [comment]
The reason for these is not at sign up, but later.  The SC needs to know the skill level so that appropriate images can be allocated.  And the RAP should be able to present to the transcriber for selection just those images which they capable of transcribing.

**Comment by edickens** [comment]
PS.  When we have an online training package, then transcribers will be able to learn how to do more difficult documents and so work their way up the skill ladder.

**Comment by PatReynolds** [comment]
OK - so data added by Jo (?) at the end of the training period?  Revised automatically on successful completion of training package?

as not needed on sign-up, I will change milestone.

**Comment by edickens** [comment]
Or revised by their SC as they get better.

**Comment by Captainkirkdawson** [comment]
SC can edit at any time now what is the new requirement?

**Comment by edickens** [comment]
I think the SC should set it when they are sure of the transcribers ability.  It should start as "Learning" but increased very soon or after training.  ED

**Comment by Captainkirkdawson** [comment]
In which case there is no development activity
