### ISSUE TITLE
IS Getscan access fails

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1205]

**Comment by edickens** [comment]
It is not accepting passwords.  I can find the program OK, but not get in.

A problem with the FR IS link file?

**Comment by edickens** [comment]
I'm getting lots of emails because no transcriber can get into the image server so work for them has stopped.
I cannot get in as well, so it seems to be everyone.

**Comment by Captainkirkdawson** [comment]
Have requested a reload of the Regusers passwords. If not action the new version will be uploaded tonight (Friday)
The code to eliminate incomplete and inactive userids had a bug and I have been unavailable to review

**Comment by edickens** [comment]
Thanks Kirk.  I will look out for any effect on getscan and let people know when it has worked.
Would your code to eliminate those UserIDs have corrupted the Regusers passwords file?  Eliminating those UserIDs is not essential as it has been like that for 18 years.

**Comment by SteveBiggs** [comment]
Login to IS now works (for me anyway).

**Comment by edickens** [comment]
Me too.  Thanks Kirk.  Done
