### ISSUE TITLE
Wildcard search issue

### ISSUE THREAD

**Issue by CommsCoord** [FreeUKGen/MyopicVicar#1206]
This was rec'd a few days ago: Hi guys, I have been trying to use a wildcard in a surname search and keep getting no results even though I know there are entries in the parish and time period that show up with full name searches. Is the wildcard function broken? Thanks Harry.

He was asked to send a screenshot in to highlight the issue, which he has, and he included one of the 'normal' search for comparison

**Comment by CommsCoord** [comment]
![search_normal](https://cloud.githubusercontent.com/assets/20557838/26491129/31b19e34-4206-11e7-8909-011a1e180d43.jpg)

**Comment by CommsCoord** [comment]
![search_wildcard](https://cloud.githubusercontent.com/assets/20557838/26491138/3890d04e-4206-11e7-9cb4-fb595032033f.jpg)

**Comment by Captainkirkdawson** [comment]
fixed
