### ISSUE TITLE
Why has the screen layout of tables been changed?

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1208]
See details below

**Comment by Sherlock21** [comment]
In Production, screen views which show lists of things - like My Batches, or the Details of records in a Church batch, have been changed,
They used to display 15 rows of eta per Screen Page.
Now in Prod, they only display 9 rows.

T3 on the other hand still has the 15 row display.

SO did this change happen by Accident from doing something else? if so what?.
OR did it get done for a reason?
IF the latter, then why was it not agreed by the general users, and tested via T3 in the usual way?

Compare the attached views of essentially same data
 (MY one batches in T3 and in Prod. Same computer, same Browser, nothing changed in my computer setup between the 2 view.

I would at show images but I can't attach them!

**Comment by Sherlock21** [comment]
![t3 list of batches-15rows](https://cloud.githubusercontent.com/assets/9368704/26519854/8294fdbe-42bf-11e7-98cf-2d604035dc1d.jpg)
![prod-list of batches-9 rows](https://cloud.githubusercontent.com/assets/9368704/26519859/91bc2998-42bf-11e7-8bfd-d73465f5446e.jpg)

**Comment by Captainkirkdawson** [comment]
A table change in the css was made in response to accessibility comments. We use the same css for all tables. Production and test3 are the same.

**Comment by Sherlock21** [comment]
If the code is the same in both Production and T3, then why the different visual appearance?
The sample images above were taken within minutes of each other.

And if the wide spaced view of only 9 records per screen is to be retained, despite those key users who want it in the T3 style,  there is a bigger issue.
