### ISSUE TITLE
Open 37018

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1210]
Need to open mongo servers so we can move databases

**Comment by Captainkirkdawson** [comment]
Required to complete FreeCEN move

**Comment by lemon-ukgen** [comment]
Done. I can't find a MongoDB listening on 37018 anywhere to test, but it works with netcat.

**Comment by Captainkirkdawson** [comment]
TY. Nothing normally listens to it. It is the port used by standalone when
I need to connect directly

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1
