### ISSUE TITLE
New server monitoring

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1211]
Add the new servers to our critical monitoring system. We need to be
informed if any of the mongodb instances goes down

**Comment by lemon-ukgen** [comment]
Basic monitoring added to Nagios. I don't have a check for "is MongoDB running?" yet because I haven't yet understood what instances should be running where. That will emerge as part of #1213.

**Comment by lemon-ukgen** [comment]
Pending: `gmirror` test.

**Comment by Captainkirkdawson** [comment]
mongo1
sudo -u mongodb mongod32 --config /usr/local/etc/mongodb-sharded.conf #
runs on port 27018 and replSetName: shard1
sudo -u mongodb mongod32 --config
/usr/local/etc/mongodb-arbiter_for_shard3.conf # runs on port 27020
sudo -u mongodb mongos32 --config /usr/local/etc/mongodb-mongos.conf   #
runs on port 27017
sudo -u mongodb mongod32 --config /usr/local/etc/mongodb-config_server.conf
# runs on port 27019 and replSetName: csReplSet

mongo2
sudo -u mongodb mongod32 --config /usr/local/etc/mongodb-sharded.conf #
runs on port 27018 and replSetName: shard1 primary
sudo -u mongodb mongos32 --config /usr/local/etc/mongodb-mongos.conf   #
runs on port 27017

mongo3
     sudo -u mongodb mongod32 --config /usr/local/etc/mongodb-sharded.conf
# runs on port 27018 and replSetName: shard2
sudo -u mongodb mongod32 --config
/usr/local/etc/mongodb-arbiter_for_shard1.conf # runs on port 27015
sudo -u mongodb mongod32 --config /usr/local/etc/mongodb-config_server.conf
# runs on port 27019 and replSetName: csReplSet
sudo -u mongodb mongos32 --config /usr/local/etc/mongodb-mongos.conf   #
runs on port 27017

mongo4
sudo -u mongodb mongod32 --config /usr/local/etc/mongodb-sharded.conf #
runs on port 27018 and replSetName: shard2 primary
sudo -u mongodb mongod32 --config /usr/local/etc/mongodb-config_server.conf
# runs on port 27019 and replSetName: csReplSet this one is primary
sudo -u mongodb mongos32 --config /usr/local/etc/mongodb-mongos.conf   #
runs on port 27017

mongo5
     sudo -u mongodb mongod32 --config /usr/local/etc/mongodb-sharded.conf
# runs on port 27018 and replSetName: shard3
sudo -u mongodb mongod32 --config
/usr/local/etc/mongodb-arbiter_for_shard2.conf # runs on port 27016
sudo -u mongodb mongod32 --config /usr/local/etc/mongodb-config_server.conf
# runs on port 27019 and replSetName: csReplSet
sudo -u mongodb mongos32 --config /usr/local/etc/mongodb-mongos.conf   #
runs on port 27017

mongo6
sudo -u mongodb mongod32 --config /usr/local/etc/mongodb-sharded.conf #
runs on port 27018 and replSetName: shard3 primary
sudo -u mongodb mongod32 --config /usr/local/etc/mongodb-config_server.conf
# runs on port 27019 and replSetName: csReplSet
sudo -u mongodb mongos32 --config /usr/local/etc/mongodb-mongos.conf   #
runs on port 27017


Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by lemon-ukgen** [comment]
The `mongoctl` script for #1213 now has a `nagios` mode that we can plug straight into NRPE.

**Comment by lemon-ukgen** [comment]
`gmirror` test added.

Nagios is about to complain about the missing mongodb processes on `mongo1`, `mongo3`. I'll ack the alerts.

**Comment by Captainkirkdawson** [comment]
Correct warning in place

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Is there just 1 general warning if any of the instances is not running. it is not explicit?

That is not a problem but just confirming

**Comment by lemon-ukgen** [comment]
```
PROBLEM - service alert: mongo3/MongoDB is CRITICAL at 2017-06-16 00:05:12 +0100

Additional info:
ERROR: config_server not running
```

Slack only gets the abbreviated version. Do you want me to add your email to the contact group? You'll get *all* UKGEN Nagios mails.

**Comment by Captainkirkdawson** [comment]
Not till I come back from Vacation!!

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1
