### ISSUE TITLE
Server scripts

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1213]
Write a script puts the names of the configs that each host should run in a file and have a wrapper that starts / stops either all of them or the one specified as a parameter.  The earlier we have this the better as it will avoid my making mistakes

**Comment by lemon-ukgen** [comment]
Done, but showing that some of the processes mentioned in #1211 aren't running as indicated on `mongo1` and `mongo3`

The script `/root/bin/mongoctl` uses `/usr/local/etc/mongodb.yml`. It has three modes, `status`, `start`, `stop`. The default mode is `status`. The mode is passed as the first and only parameter.

* `status`:  for each configured mongo process it checks the config file is present and if the process is running.
* `start`: if a configured mongo process is not running, prints the command to run it. when we think this script is ok we'll make it actually issue the command too.
* `stop`: if a configured mongo process is running, tries to kill it. if run under `sudo` this *will* stop mongo processes.

Example:
```
[lemon@mongo1 ~]$ /root/bin/mongoctl status
[mongo1] checking mongod32 /usr/local/etc/mongodb-sharded.conf
  running [80358]
[mongo1] checking mongod32 /usr/local/etc/mongodb-arbiter_for_shard3.conf
  running [80432]
[mongo1] checking mongos32 /usr/local/etc/mongodb-mongos.conf
  not running
[mongo1] checking mongod32 /usr/local/etc/mongodb-config_server.conf
  not running

[lemon@mongo1 ~]$ /root/bin/mongoctl start
NOTICE: this mode is not yet verified, start command will be listed but not run
[mongo1] starting mongod32 /usr/local/etc/mongodb-sharded.conf
  already running [80358]
[mongo1] starting mongod32 /usr/local/etc/mongodb-arbiter_for_shard3.conf
  already running [80432]
[mongo1] starting mongos32 /usr/local/etc/mongodb-mongos.conf
# sudo -u mongodb mongos32 --config /usr/local/etc/mongodb-mongos.conf
[mongo1] starting mongod32 /usr/local/etc/mongodb-config_server.conf
# sudo -u mongodb mongod32 --config /usr/local/etc/mongodb-config_server.conf
```

A summary of the current `mongoctl status` on all hosts:
```
[mongo1] checking mongod32 /usr/local/etc/mongodb-sharded.conf
  running [80358]
[mongo1] checking mongod32 /usr/local/etc/mongodb-arbiter_for_shard3.conf
  running [80432]
[mongo1] checking mongos32 /usr/local/etc/mongodb-mongos.conf
  not running
[mongo1] checking mongod32 /usr/local/etc/mongodb-config_server.conf
  not running

[mongo2] checking mongod32 /usr/local/etc/mongodb-sharded.conf
  running [62917]
[mongo2] checking mongos32 /usr/local/etc/mongodb-mongos.conf
  running [66346]

[mongo3] checking mongod32 /usr/local/etc/mongodb-sharded.conf
  running [17610]
[mongo3] checking mongod32 /usr/local/etc/mongodb-arbiter_for_shard1.conf
  running [96686]
[mongo3] checking mongod32 /usr/local/etc/mongodb-config_server.conf
  not running
[mongo3] checking mongos32 /usr/local/etc/mongodb-mongos.conf
  running [72098]

[mongo4] checking mongod32 /usr/local/etc/mongodb-sharded.conf
  running [15392]
[mongo4] checking mongod32 /usr/local/etc/mongodb-config_server.conf
  running [39246]
[mongo4] checking mongos32 /usr/local/etc/mongodb-mongos.conf
  running [72416]

[mongo5] checking mongod32 /usr/local/etc/mongodb-sharded.conf
  running [60855]
[mongo5] checking mongod32 /usr/local/etc/mongodb-arbiter_for_shard2.conf
  running [65891]
[mongo5] checking mongod32 /usr/local/etc/mongodb-config_server.conf
  running [28478]
[mongo5] checking mongos32 /usr/local/etc/mongodb-mongos.conf
  running [67054]

[mongo6] checking mongod32 /usr/local/etc/mongodb-sharded.conf
  running [80811]
[mongo6] checking mongod32 /usr/local/etc/mongodb-config_server.conf
  running [37395]
[mongo6] checking mongos32 /usr/local/etc/mongodb-mongos.conf
  running [70685]
```

**Comment by Captainkirkdawson** [comment]
TY Lemon

It would seem that the scripts are correct.

I stopped the 2 instances on mongo1 and the 1 on mongo3 whenwe had the comminications problem between mongo1 and mongo3 and never restarted them. So the status reports and proposed actions on start are correct.

Could I ask that we add the capability specify which instance we wish to stop or start as well as the full set. Most of the time we wish to stop a specific instance on a mongo server and leave the others running. There will also be times when we just wish to start 1 instance

For your information the sharded instance is the actual database. mongo 1 and 2 are members of shard1 replication set. mongo 3 and 4 are members of shard2 and; mongo 5 and 6 are members of shard3

The arbiter is a for the specified replication set. 

The config_servers are all members of a replication set; i disbled 2 members when we had the communications problem to avoid having an even number of members which would mean no election of a primary. The config_servers know where the various chunks are stored. If no primary then the configuration cannot be updated in terms of chunk moves hence it does not balance

The mongos are the conductors to which an app connects. They are individual instances. On receiving a request they get info from the config servers and ask the idenfified shards to provide the response. If multiple shards are contacted they merge the responses and send the final response back to the app.

Tthe mongos could be on the app server but there appears to be no "best" location so I kept everything on the mongp servers except the apps.

So an app connects to a mogos witha request

**Comment by lemon-ukgen** [comment]
How's this?

```
[lemon@mongo3 ~]$ /root/bin/mongoctl
[mongo3] checking sharded (mongod32 /usr/local/etc/mongodb-sharded.conf)
  running [17610]
[mongo3] checking arbiter_for_shard1 (mongod32 /usr/local/etc/mongodb-arbiter_for_shard1.conf)
  running [96686]
[mongo3] checking config_server (mongod32 /usr/local/etc/mongodb-config_server.conf)
  not running
[mongo3] checking mongos (mongos32 /usr/local/etc/mongodb-mongos.conf)
  running [72098]


[lemon@mongo3 ~]$ /root/bin/mongoctl help
mongodbctl command [ name ]

  command can be one of 'status', 'start', 'stop'
  'start' and 'stop' commands can take an optional name

  mongodb instances on this server: sharded, arbiter_for_shard1, config_server, mongos


[lemon@mongo3 ~]$ /root/bin/mongoctl start config_server
NOTICE: this mode is not yet verified, start command will be listed but not run
[mongo3] starting config_server (mongod32 /usr/local/etc/mongodb-config_server.conf)
# sudo -u mongodb mongod32 --config /usr/local/etc/mongodb-config_server.conf
```

**Comment by Captainkirkdawson** [comment]
/root/bin/mongoctl start [config_server]
NOTICE: this mode is not yet verified, start command will be listed but not run

but no command is provided

**Comment by Captainkirkdawson** [comment]
Will hold off starting the mongos on mongo1 so I can test the start

**Comment by lemon-ukgen** [comment]
No square brackets required, per example above.

**Comment by Captainkirkdawson** [comment]
OK TY I was going by the example mongodbctl command [ name ] 

Fine now; just started mongos on mongo1 and got the message from Nagios

PS Note the spelling error in that mongodbctl should be no db

**Comment by lemon-ukgen** [comment]
Ah, ok, that is "usage" in the help text, where by convention square brackets indicate optional arguments

```
[lemon@mongo3 ~]$ /root/bin/mongoctl help
mongodbctl command [ name ]
```

This was the example:

```
[lemon@mongo3 ~]$ /root/bin/mongoctl start config_server
NOTICE: this mode is not yet verified, start command will be listed but not run
[mongo3] starting config_server (mongod32 /usr/local/etc/mongodb-config_server.conf)
# sudo -u mongodb mongod32 --config /usr/local/etc/mongodb-config_server.conf
```

Will fix the 'db' bit, thanks.

**Comment by lemon-ukgen** [comment]
I've removed the guard so that the start commands are actually executed now.

I haven't tested that though because I don't want to needlessly interrupt MongoDB service.

**Comment by Captainkirkdawson** [comment]
Will consider as completed. If there are issues will let you know
