### ISSUE TITLE
HAProxy

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1214]
Since we no longer store search queries in a local database (they are are now part of the main database) there is no longer a need for HAProxy to set and use the freereg2_session cookie

**Comment by lemon-ukgen** [comment]
I'd like to coordinate this work with @Captainkirkdawson whenever suits.

**Comment by Captainkirkdawson** [comment]
Hold off on this until I have resolved the 1252 issue. In fact is there any benefit for you to remove?
