### ISSUE TITLE
Administration routing

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1215]
There is no technical reason for running the member actions on any specific server EXCEPT in the case of uploading and processing of uploaded files. Hence potentially we could get rid of the administration cookie or restrict its functioning to the csvfiles controller actions.

**Comment by lemon-ukgen** [comment]
I'm not sure if you're asking me to just drop the Administrator cookie logic in HAProxy or something else. Let me know :)

**Comment by Captainkirkdawson** [comment]
It was that but I think I will leave well enough alone and close this request
