### ISSUE TITLE
Log rotation on mongo server

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1217]
The shard database and config server logs are rotated OK.

However the mongos logs in Mongodb/mongos are not because they have no actual database
Need to add an automatic rotation

**Comment by lemon-ukgen** [comment]
I extended`rotate-mongodb-logs` to signal `mongos` processes too.

This script wants to, but doesn't yet, delete logs older than a month. @Captainkirkdawson do you want me to enable that?

**Comment by Captainkirkdawson** [comment]
Yes please add deletion after 1 month

**Comment by richpomfret** [comment]
@lemon-ukgen would be great if you can get a moment to to add in the deletion..

**Comment by lemon-ukgen** [comment]
Done.
