### ISSUE TITLE
Add Northern Ireland data

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1219]

**Comment by edickens** [comment]
Emails so far:-
Hi Eric

I have found a great guide to the churches and chapels of NI, and where records that exist are located. I also might have a contact who would be willing to start sourcing these.

The guide, PRONI, is really handy and I am wondering if we might think about liaising with the NI Dept of Culture, Arts and Leisure about access to the records?

In the meantime, I was wondering if I can take over the NI counties to get the churches and chapels set up in hopes that we soon may be able to get data!

Thank you
Sandra

Hi Eric

I think I will need either to make use of one of the spare IDs we have under Wales, or maybe just create a new one. When the server is back up I will have a look at what we have got and then decide what to do if that is ok?

Have not really negotiated before, but certainly am willing to try!

Sandra

Hi Sandra,

Apolgies for silence (goodness knows how it got to be Friday afternoon!). Libraries NI would also be worth contacting.  I'm happy for you to make the contacts.

Another organisation is placenamesni.org - now, if we could get them to open their data (and they should do, they are a government organisation) we could use it as the backbone of places in Northern Ireland.  I'll talk to Richard (Light) about this.

Best wishes,

Pat

Hello Kirk,

Sandra is looking at a coordinated push at getting NI records for transcription.  There is a nice gazatteer (placenameni.org) which Richard Light thinks is available as linked open data.

Assuming (big assumption) that the place name data is what we need, what format would we need it in?

Best wishes,

Pat

http://www.placenamesni.org/ works

We would need access to the database through an api.

We would need a location in the database; appears to be absent.

Resource looks far more like a university research resource at this point

Then would need someone to edit and finalize the place-name location information extracted. EricB did that for the rest of Britain using 

http://www.gazetteer.org.uk/index.php

I do not know if we actually have the data foir NI already



Kirk Dawson

Hi all. 

I think I have all the info regarding county place name and churches. Data is stored different matter and there are several possibilities for this already under scrutiny. I am in the Midlands for the weekend but will be looking into this further when I return home

Sandra

**Comment by edickens** [comment]
There may be some program changes needed as NI is excluded at present from some reports.  I will allocate the NI counties to Sandra when the server comes back.  E

**Comment by richpomfret** [comment]
To flesh out how we might do this and what's already in the code (i.e. NI being exclused at present).

**Comment by edickens** [comment]
All the NI counties are set up on the server and I can allocate CC and SC to them.  I suggest we do no more for the time being as we have no transcriptions so people should not think that they can search them.  First of all Sandra wants to set up the Places and Churches.

**Comment by Sherlock21** [comment]
There is a major difference between Britain and NI.
NI does not have the same County / Placename Structure as we do in the rest of Britain.

All the indexes I can find seem to have Countes / Parishes / Baronys.
Some indexes list the 5 Cities of NI, and sub list some of them into Townlands. such a City is Armagh.
But other Cities like Lisburn I can't find the similar sub division of that City in Wiki anywhere. 
So we can't use out location nomenclature as we do in Britain so far as I can see.
Other lists show the top 50 urbanisations, (by population in 2001) and the 50th in that list has a mere 2000 people registered.
And thats before I try and find a listing of their geo location refs !

So first thing i suggest is to get to the bottom of the matching Place Names structure in tha manner we which can incorporate.

**Comment by CommsCoord** [comment]
I found a guide which seems to follow the setup we already have, i.e. county, place, church/chapel name and denomination. I just selected one, but if needed I can look for the areas mentioned in the previous post if that would be of any help.


![ni](https://cloud.githubusercontent.com/assets/20557838/26799222/98f7a362-4a2c-11e7-85d9-ef79cf5b2e11.png)
