### ISSUE TITLE
All contact emails between 31 May and 8th June are not on the contacts page

### ISSUE THREAD

**Issue by CommsCoord** [FreeUKGen/MyopicVicar#1224]
There are approx. 15 emails received by Comms that are not on the contacts page. I assume they have not appeared on the relevant county pages. Without being able to see the details I have no way to determine the county, and there is no way for the coordinator to determine the record which the contact is writing to us about

**Comment by Captainkirkdawson** [comment]
Will see what I can do to retrieve

**Comment by Captainkirkdawson** [comment]
Retrieve the contacts that were made while we were shut down. It is likely that any uploaded images are inaccesible

**Comment by CommsCoord** [comment]
​All contacts were there as you said, and have now been dealt with. Images
were intact on contact which supplied them. Thank you for your help.

Kind regards
The Communications Team
