### ISSUE TITLE
Create additional test access url

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1225]
Currently we have test3 connected to a test database on the mongodb servers. This is to test shgarding changes and issues. This connects to /home/apache/hosts/freereg2/production
A separate url that connects to 
/home/apache/hosts/freereg2/development which we will connect to a vervet mongodb instance is required

**Comment by lemon-ukgen** [comment]
This already exists, but points to the now-gone MyopicVicar tree. I'll update it.

**Comment by lemon-ukgen** [comment]
Here we go: https://test2.freereg.org.uk/

**Comment by Captainkirkdawson** [comment]
Thanks L it points to development?

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by lemon-ukgen** [comment]
Yes - I dropped a test `index.html` into `~apache/host/freereg2/development/public` as demo

**Comment by Captainkirkdawson** [comment]
TY

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1
