### ISSUE TITLE
Add mongod instance restarts on reboot for Mongod servers

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1226]

**Comment by lemon-ukgen** [comment]
Are you happy with the commands printed by the `mongoctl` script? If so I'll make it run on boot with `start` argument.

**Comment by Captainkirkdawson** [comment]
Yes I am happy with the scripts

**Comment by lemon-ukgen** [comment]
`rc.local` set up to run this script on boot with `start` parameter. Not tested, but let's see next time we reboot one of these servers.

**Comment by Captainkirkdawson** [comment]
Will consider as completed
