### ISSUE TITLE
Reroute volunteering queries to Jo

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1229]

**Comment by edickens** [comment]
Sandra has given notice that she will step down from this post in October 2017.  So we need to take some action to replace what she does.
There are a few issues with this post:-
- Many messages received can get standard answers.  We need to direct the sender to some standard solutions before they send the message.
- Many messages are reporting transcription "errors".  The sender could record these, without changing the original entry.  An "Action" for the CC could provide a list for verification when convenient.  No action is then needed by the Comms Coordinator.
- Some CCs do not reply to forwarded messages.  The Comms Coordinator has to chase or apologise to the sender.  This could be automated.
- All three projects have the same need for a Comms Coordinator.  Perhaps one person could be employed to do all this work.  Once set up, it is fairly routine.

Thoughts?
EricD

**Comment by CommsCoord** [comment]
With a bit of time, I can give you a list of the most common questions asked, with could be addressed in the FAQs, such as the need for a more information for prospective transcribers. I get many questions asking what is involved in being a transcriber, and as it stands now, they have to sign up before they get any information, or send an email to Comms.

There are many coordinators who do not handle any email coming to the for various. Some is because the counties are unmanned, or they have asked Comms to handle them for a variety of reasons. Comms currently handles transcription errors by either amending the record when an original parish document is provided by the sender. Otherwise we add a note to say X  may be Y. In either event a note is always left to say Comms did something to the entry and when it was done. An email is then sent to the original sender to say er made the change, or we entered a comment highlighting the information they provided.

There are times that coordinator do not answer emails in a timely manner, however there are some who have made us aware of problems affecting their answering of emails. Most coordinators answer their email fairly quickly, and supply Comms a copy of their response which we then know is completed and then archived. There are a very small number of coordinators who do not supply copies of the responses, and only communicate with Comms to say they have emailed the sender. This causes concern as we do not know what is being said to the sender, and although the likelihood is that the content is completely innocent, there remains a remote possibility that responses could reflect in a negative manner on FR.

**Comment by suffolkroots** [comment]
As one of the supposedly small number of coordinators who---

a. prefers to handle her own communications and
b. only notifies comms coord that the matter has been dealt with---

I would respectfully suggest that if you need to keep a check on what is being communicated by coordinators then perhaps you should---- 

a. in your arrogance request copies of every email we receive from and send to anyone re FreeREG
b. publish (for coords info) on the coords list all emails and responses sent by coords to management.

Or perhaps you could just trust us.

I object most strongly to the suggestion that I may be inappropriate in my dealings with contacts.

**Comment by edickens** [comment]
I assume that "Suffolkroots" is you Julie.

I do take great exception at being called "arrogant" over this.  We have to face the fact that some, in fact coordinators for a lot of the counties, are not active and we never hear from them.  This is often for a very valid reason in that they do not have data to transcribe.  This is causing a lot of extra work.  It does not refer to Suffolk.

However, your suggestions are valid and are good practice.  All correspondence needs to be recorded and archived so that it is there for reference and for continuity should there be a change of coordinator or member of management.  This is being done for the programming of FR.  The correspondence does not need to be sent to everyone, but needs to be saved.  That is why I suggest an automated system where the server is used to process all messages from researchers.  It should not change the need for coordinators to deal with their own messages, in fact the system should assume that coordinators will answer their messages, but it needs to make sure that the message does get answered and has not got lost.

This is not to check up on coordinators, but to just make sure that the system is working.

Eric

**Comment by suffolkroots** [comment]
No, Eric, it's not Julie, it's Ali Hill.

You take exceptiom to being called arrogant, I take exception when my work is called into question. Quits.

I object to being asked to provide copies of emails in order that my work can be checked for appropriateness. I inform that the issue has been dealt with and that should suffice.

**Comment by edickens** [comment]
Sorry Julie.

Ali.  This is not to check up on what you are doing.  It is just good practice to save work for reference and to ensure that the system is working.  We are getting a lot of emails blocked by Spam Filters at present and so not getting through.

There are new coordinators who do need help, but that is a different problem.

Eric

**Comment by suffolkroots** [comment]
Sandra's statement---

_"There are a very small number of coordinators who do not supply copies of the responses, and only communicate with Comms to say they have emailed the sender. This causes concern as we do not know what is being said to the sender, and although the likelihood is that the content is completely innocent, there remains a remote possibility that responses could reflect in a negative manner on FR."_

QED

**Comment by CommsCoord** [comment]
Please do point out to me, if you would be so kind, as to where I referred to you by name or to your work in particular? 

And I would point out that in every business and charity I have ever worked for, it is routine practice that all communications are recorded or retained, in the unlikely event that something was ever called into question. 

This practice is not a reflection on the character of any employees or volunteers of the business or charities, but simple business practice in this day and age. Perhaps it is not something that would or should apply to FreeREG, but that is a decision for management to make.

**Comment by suffolkroots** [comment]
I did not suggest there was any mention of specific names, but ----
I have made my point.
I have copies of communications.
Over and out.

**Comment by CommsCoord** [comment]
I have withdrawn my original thoughts and subsequent replies. There is nothing to be served by offering thought when all it breeds is paranoia.

**Comment by PatReynolds** [comment]
#694 relates.  
I think the suggestions are best broken down to individual stories (many of them may be in the communication enhancement plan already, and others may be).

**Comment by Captainkirkdawson** [comment]
Separate stories are written for  para 1,2 and 4. If 1 and 2 are  dealt with there is no para 3 issue

**Comment by CommsCoord** [comment]
I have the standard answers in hand for things like login issues and such. What I am doing is trawling though Comms archive to collect the most common issues, and then can devise standard answers for these.

**Comment by SteveBiggs** [comment]
Since technical changes to automate parts of the comms coord role appear to be a long way down the road,  we need to urgently discuss how we are to deal with Sandra's departure from the post at the end of September.

**Comment by CommsCoord** [comment]
Is there any possibility of trying to break the role into more bite sized chunks and try to get some of the coordinators who are active to help a bit more in other areas?

**Comment by CommsCoord** [comment]
Provisions need to be made to ensure that all contacts are dealt with in the same manner, with transparency and consistency, throughout all counties. Continuity is something we have struggled with, and now more than ever we need to push this, especially as we are getting noticed more in the media and by the public.

This will also help long term when coordinators step down, or we lose contact such as in the case of a coordinator passing away. Being able to have someone come and pick up the reins and being on the same page as everyone else will make things so much easier down the road for everyone.

**Comment by PatReynolds** [comment]
Recruit: data coms coordinator and a feedback coordinator

**Comment by PatReynolds** [comment]
Suggested allocation of tasks:
Data Question > Data Question results page asks for evidence to be emailed to > Data Correction Manager (new role) see story #1294
Website Problem > goes to page which links to FAQ and asks that unresolved issues be emailed to > Communications Coordinator 
Volunteering Question > message is sent to ?Steve or ?Denise
Genealogical Question > Genealogical Question page says 'sorry, we are planning to host a forum where you can ask genealogical questions, but until this is developed, please visit http://www.freeukgenealogy.org.uk/about/links/ for some links we think you will find useful
Enhancement Suggestion > goes to Communications Coordinator 
Thank you > goes to ?Steve
General Comment > goes to Communications Coordinator

**Comment by richpomfret** [comment]
Next step is Jo helping to co-ordinate this. Vino to reroute where the comments go.
