### ISSUE TITLE
Write FAQs from comments and create new structure / pages for their presentation

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1230]
Priority 17 (0	4	8	5)
Many comments received can get standard answers. We need to direct the sender to some standard solutions before they send the message.
3 questions minimum.

FAQs completed, structure to be decided and implemented (10/9/2019)

**Comment by CommsCoord** [comment]
Is there any particular format these need to written in. Or do I simply submit the standards to someone? Who would that be?

**Comment by Captainkirkdawson** [comment]
Discuss with @AlOneill

**Comment by AlOneill** [comment]
Discussion started ...

**Comment by SteveBiggs** [comment]
Sandra asked what is the status of planning for her departure. Where are we with FAQs?

**Comment by Captainkirkdawson** [comment]
I was under the impression that Sandra was writing and that Alison was turning into FAQ. Has step one been done? Has there been discussion Alison/Sandra?

**Comment by CommsCoord** [comment]
Things are in motion

**Comment by PatReynolds** [comment]
FAQ for family history to inc. Facebook Group see also #1349

**Comment by PatReynolds** [comment]
see also #1231

**Comment by PatReynolds** [comment]
@DeniseColbert to create the initial questions for #1231

**Comment by DeniseColbert** [comment]
Draft pages are on Refinery, currently refining them

**Comment by benwbrum** [comment]
@SteveBiggs (and @AlOneill) to send feedback on the pages on `test3` to @DeniseColbert

**Comment by SteveBiggs** [comment]
@DeniseColbert there are several comments in square brackets. Are you working on addressing them?

**Comment by Captainkirkdawson** [comment]
The draft on test3 was destroyed by the backport of the refinery pages from production to test3

**Comment by PatReynolds** [comment]
see also #1243 - is that being done as part of this work?

**Comment by DeniseColbert** [comment]
Yes, it is part of the comms enhancements. 

FAQ pages are now up on Test3. Document for comments emailed 13/6

**Comment by DeniseColbert** [comment]
Draft FAQs on Test3 now updated with recent suggestions. Formatting / styling required.

**Comment by richpomfret** [comment]
@SteveBiggs to review next.

**Comment by AlOneill** [comment]
Have made a start on the Data Problem section of the FAQ:
https://test3.freereg.org.uk/cms/contacts-faq-data-question-draft

Some of the GoogleDocs edits do not seem to have made it into Refinery — have updated and made a few more edits for accuracy/clarity. Seems that the questions are better worded as if asked by a user, not by us, so have adjusted accordingly. All comments/suggestions welcome.

I do not know the details of how the FAQ pages are to be used, but wonder if they should all be on a single page, rather than a page for each type of contact. After all, it is not unknown for a user to randomly select a contact type, so maybe it's better to show them all FAQ in one place?

In any case, I can't finalise any of these pages until I understand the details how they will fit into the Contacts 'flow'.

**Comment by SteveBiggs** [comment]
A couple of suggested changes:

1) Add 'search' -
How do I tell you about a possible mistake in one of my **search** results?

2) The button text is changing:
Please use the ‘**Report an Error in this Data**’ button on the Search Detail page for that entry. That way, we know exactly which entry you mean.

**Comment by AlOneill** [comment]
@SteveBiggs TY. Changes sound — done.

**Comment by DeniseColbert** [comment]
Thanks @AlOneill , looks good!

The links (to familysearch and GENUKI) aren't hyperlinks. Is that intentional?

Re. how the FAQs will be used. On the Contact Us page, the querent selects their 'contact type' from a drop-down menu. That will then show the corresponding FAQ page for that type. We've tried to optimise the info on each page to cover what they *might* ask us, and plan to refine / enhance the pages based on queries we receive going forward.
Putting all FAQs on one page may be overwhelming for the user and put them off looking, or contacting us altogether.

Do we want to explore having an additional central FAQ page (where these exist together) for users who might be looking for extra information but haven't clicked 'Contact Us'?

**Comment by AlOneill** [comment]
No reason for the missing links — just have not done them yet.

My main reason for suggesting we put all the FAQ together is that users do not necessarily understand the/our distinction between say a Website Problem and an Enhancement Suggestion, or the former and a Data Question, &c. So a user could select the 'wrong' category, find no help in that FAQ section, and then go back to the form none the wiser.

But, if studies show that users would prefer plan A, then I'll take that.

As for an additional central page, the main concern will be duplicated info that could become out of step — but there is already duplication across the individual sections, so nothing new.

**Comment by richpomfret** [comment]
@DeniseColbert to mock up how this will work (flow diagram).

**Comment by DeniseColbert** [comment]
See https://docs.google.com/drawings/d/1VNtciOqrK7LIZxItihDO9Ey5tvY4vi-kkAKBkZVztBA/edit?usp=sharing

**Comment by AlOneill** [comment]
It seems that the proposed flow, including a 'back' button (for an already answered question), would require the FAQ pages to be part of the app rather than in Refinery, with all links to 'Contact us' being forms, since they would need to carry information re the starting page.

**Comment by DeniseColbert** [comment]
@AlOneill can we chat about this on Slack? There are a few different (yet related) issues and I don't want to clutter the story. I can make a channel for this story specifically.

**Comment by AlOneill** [comment]
@DeniseColbert Sure, if you think it would help.

I don't look at Slack on a regular basis, but I do have access.

**Comment by DeniseColbert** [comment]
Great; I've set that up. You might need to log in to Slack and toggle notification emails on.

**Comment by PatReynolds** [comment]
@DeniseColbert - in Scrum Alison suggested that intital button (just one button) goes to FAQ, as there are so few FAQ, and that FAQ are in sections, leading on to button about that section.

**Comment by PatReynolds** [comment]
Which is easier to implement, a single page of FAQ with user selecting topic and answering questions at the end, or multiple FAQ, one for each type of query?

**Comment by edickens** [comment]
I like a list of FAQ headings which are linked to a paragraph that brings up the answer.
If we get a lot, then perhaps divide them into major headings.

**Comment by PatReynolds** [comment]
Solution: Send to the Faq first, then 'go to to the Contact page.

**Comment by PatReynolds** [comment]
Actions now
a) create one page FAQ page (if does not exist)
b) link from 'contact us' to one FAQ page
c) revised 'contact us' page, if needed
d)  link from 'FAQ page' to 'Contact us'.

**Comment by DeniseColbert** [comment]
1-pg FAQ now there in Test3, looks OK after html-washing, however, the styling @AlOneill had applied has been lost, unfortunately.

Re. 'If you have further questions complete the contact form...' link: do we want this at the end of each section (as currently) or once, at the bottom of the page?

**Comment by PatReynolds** [comment]
At the bottom of each section. Maybe phrase "if you have further questions about [topic name] please complete the contact form' (where [topic]name]= the subject on the contact form.

**Comment by richpomfret** [comment]
@AlOneill to take a look at fixing the styling..

**Comment by richpomfret** [comment]
@DeniseColbert any update on this one?

**Comment by DeniseColbert** [comment]
All additions to FAQ now entered in Refinery, ready for @AlOneill to stye up. Once that's done we need to work out the 'shape' of the General comment page as far as I can tell from the yellow comment there. Then make live?

**Comment by AlOneill** [comment]
Have now resumed work on getting this ready.

**Comment by AlOneill** [comment]
The [draft FAQs](https://test3.freereg.org.uk/cms/frequently-asked-questions-faqs-draft) page is ready for Review.

**Comment by AlOneill** [comment]
I have two questions:

* What do we want the page name to be? As now, without 'DRAFT' or simply 'FAQs' or what?
* Where do we place it in the pages structure? As a child of 'Help', or somewhere else?

**Comment by DeniseColbert** [comment]
Looking good! Thanks, Alison 😀

**Comment by AlOneill** [comment]
Page name changed and page moved as per.

**Comment by AlOneill** [comment]
Bearing in mind that there are currently **no incoming links to the FAQ page**, the page is nevertheless sync-ready.

**Comment by DeniseColbert** [comment]
So is the plan to change the link in the footer to https://www.freereg.org.uk/cms/help/frequently-asked-questions-researchers?

**Comment by PatReynolds** [comment]
@Vino-S to change the link from 'Contact us' in the page

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by DeniseColbert** [comment]
As there are no FAQs for saying Thank You to the volunteers, should we reference this option on the contact form and perhaps give users the ability to fast-track straight to the Contact Form (or Reviews page)?

**Comment by PatReynolds** [comment]
Link through to the Reviews page

**Comment by Vino-S** [comment]
ready for testing in test3

**Comment by DeniseColbert** [comment]
Tested and looks good, links work etc.

**Comment by DeniseColbert** [comment]
@Vino-S Should the Thank-you option on the form take the user to the Reviews page? Because that's not working. I completed the form and selected Thank you and my form was submitted but a) didn't take me to the Reviews page to leave a review b) where did it go?

Also, I'm questioning the sense in making the user enter their info and comment (i.e. Review in this case) only to direct them to the Reviews page where they would have to enter it again on the form.

**Comment by PatReynolds** [comment]
@Vino-S to take a look and let @DeniseColbert know what to test

**Comment by Vino-S** [comment]
Ready for testing in test3. 
Contact Us footer link changed to Frequently Asked Questions.

**Comment by PatReynolds** [comment]
@DeniseColbert to test

**Comment by DeniseColbert** [comment]
Great, thanks Vino, works fine on REG. 

This has somehow found its way onto FreeCEN (live) though. Could you revert that back to the Contact form page?

**Comment by AlOneill** [comment]
Is it fair that a link described as "Contact us" actually takes a user to the Frequently asked questions page? Maybe. Maybe not.

I also note that the FAQ page needs some work to bring it into line with the revised info pages format.

**Comment by PatReynolds** [comment]
@Vino-S please add "FAQs & " before "Contact us" on the link. (let me know if this doesn't make sense, please!)

**Comment by AlOneill** [comment]
[DRAFT Frequently asked questions (researchers)](https://test3.freereg.org.uk/cms/help/draft-frequently-asked-questions-researchers) updated: fix casing of `h1`; edit lead paragraph to make connection with Contact clear; improve sub-menu markup; adjust layout.

**Comment by DeniseColbert** [comment]
What is "SO" in "optimise SO for all users"?

**Comment by AlOneill** [comment]
SO is source order

**Comment by PatReynolds** [comment]
@Vino-S please add "FAQs & " before "Contact us" on the link. (let me know if this doesn't make sense, please!)

**Comment by PatReynolds** [comment]
Hi Vino,


Thanks for working on this.
I've re-opened this as it doesn't seem to have had a final review (which should include correcting the size / giving it a size.

Best wishes,

Pat

**Comment by PatReynolds** [comment]
@Vino-S to change FAQs to FAQ

**Comment by DeniseColbert** [comment]
Done, closing
