### ISSUE TITLE
birth date not found in range search

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1233]
For a range based search a record with only a birth date is not found
{
        "_id" : ObjectId("58e81d428d994a1c4142514c"),
        "transcript_dates" : [
                "",
                "1 Dec 1784"
        ],
        "search_dates" : [
                "",
                "1784-12-01"
        ],
        "location_names" : [
                "Acle (St Edmund)",
                " [Transcript]"
        ],
        "search_soundex" : [
                {
                        "first_name" : "M600",
                        "last_name" : "B430",
                        "type" : "p"
                },
                {
                        "first_name" : "S540",
                        "last_name" : "B430",
                        "type" : "f"
                },
                {
                        "first_name" : "E421",
                        "last_name" : "T300",
                        "type" : "f"
                }
        ],
        "record_type" : "ba",
        "search_record_version" : "",
        "chapman_code" : "NFK",
        "line_id" : "Captainkirk.NFKACLBA.CSV.1",
        "transcript_names" : [
                {
                        "role" : "ba",
                        "type" : "primary",
                        "first_name" : "Mary",
                        "last_name" : "BALDE"
                },
                {
                        "role" : "f",
                        "type" : "other",
                        "first_name" : "Samuel",
                        "last_name" : "BALDE"
                },
                {
                        "role" : "m",
                        "type" : "other",
                        "first_name" : "Elizabeth",
                        "last_name" : "TAITE"
                }
        ],
        "freereg1_csv_entry_id" : ObjectId("58e81d428d994a1c4142514b"),
        "search_date" : "",
        "secondary_search_date" : "1784-12-01",
        "place_id" : ObjectId("53cd496feca9ebee4f006f1a"),
        "digest" : "rurZmGSWElmIHHyCTjbDfA==",
        "u_at" : ISODate("2017-04-07T23:14:10.985Z"),
        "c_at" : ISODate("2017-04-07T23:14:10.985Z"),
        "search_names" : [
                {
                        "_id" : ObjectId("58e81d428d994a1c4142514d"),
                        "first_name" : "mary",
                        "last_name" : "balde",
                        "origin" : "transcript",
                        "type" : "p",
                        "role" : "ba",
                        "gender" : "f"
                },
                {
                        "_id" : ObjectId("58e81d428d994a1c4142514e"),
                        "first_name" : "samuel",
                        "last_name" : "balde",
                        "origin" : "transcript",
                        "type" : "f",
                        "role" : "f",
                        "gender" : "m"
                },
                {
                        "_id" : ObjectId("58e81d428d994a1c4142514f"),
                        "first_name" : "elizabeth",
                        "last_name" : "taite",
                        "origin" : "transcript",
                        "type" : "f",
                        "role" : "m",
                        "gender" : "f"
                }
        ]
}

**Comment by Captainkirkdawson** [comment]
This has only occured since the move to the sharded configuration

**Comment by Captainkirkdawson** [comment]
Fixed

**Comment by SteveBiggs** [comment]
Tested and fixed.
