### ISSUE TITLE
Java script that loads places.json crashes

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1236]
ActionView::Template::Error: undefined method `places_json' for nil:NilClass
script type="text/javascript" >
  <% if @search_query && @search_query.chapman_codes.size > 0 %>
    var selection=<%= raw(PlaceCache.where(:chapman_code => @search_query.chapman_codes.first).first.places_json) %>;
    <% if @search_query.places.size > 0 %>
      selection["selected"]="<%= @search_query.places.first.id %>";
    <% end %>
  <% end %>
  (function($) {$("#search_query_place_ids").remoteChained({
    parents : "#search_query_chapman_codes",
    url : "/places/for_search_form.json",
    loading : "Loading..."
    <% if @search_query && @search_query.chapman_codes.size == 1 %>
      , bootstrap: selection
    <% end %>
  });})(jQuery);
</script>
The complaint is the line
var selection=<%= raw(PlaceCache.where(:chapman_code => @search_query.chapman_codes.first).first.places_json) %>;

**Comment by Captainkirkdawson** [comment]
This never happened untill we moved to sharding and added Northern Ireland counties and places with no data

**Comment by PatReynolds** [comment]
Perhaps best to take down NI. Changes may be needed anyway if we move to
linked open data for NI.

Pat Reynolds
Executive Director, Free UK Genealogy

**Comment by edickens** [comment]
We only need NI now for entering Place and Church names.

**Comment by PatReynolds** [comment]
These names can be imported from the Ireland gid linked open data.

Pat Reynolds
Executive Director, Free UK Genealogy

**Comment by Sherlock21** [comment]
re: the comment above That "We only need NI now for entering Places and Churches"
is not true.
Sandra is transcribing data as we write here.
So they are no different to any other place name in Britain which today has no data yet, so far as I am concerned.

**Comment by Captainkirkdawson** [comment]
The solution is not to remove NI places (that may not be the cause) but to add a further check to the javascript so it does not try to work on a nil instance

**Comment by Captainkirkdawson** [comment]
It is possible that these are the results of a bot accessing the search page in a different manner than in the past.
Have not been able to duplicate the crash and we have had no comments on such crashes.

A researcher accessing NI does not appear to cause any issue; it works as expected.

**Comment by benwbrum** [comment]
I determined that `NIR` was not in the place cache.  Rebuilding that should have fixed the problem:
```
irb(main):007:0> ChapmanCode.values.each { |c| p c unless PlaceCache.where(:chapman_code => c).first };0
"NIR"
=> 0
irb(main):008:0> exit
[benwbrum@brazza /home/apache/hosts/freereg2/production]$  RAILS_ENV=production sudo -u webserv bundle exec rake foo:refresh_places_cache
[benwbrum@brazza /home/apache/hosts/freereg2/production]$  RAILS_ENV=production sudo -u webserv bundle exec rails c production

-- DEPRECATION WARNING --
The use of 'xhr_paging' is deprecated and will be removed at version 3.1.
Overwriting existing field screenshot in class Contact.
Overwriting existing field screenshot in class Feedback.
Overwriting existing field attachment in class Message.
Overwriting existing field images in class Message.
Loading production environment (Rails 4.2.6)
irb(main):001:0>  ChapmanCode.values.each { |c| p c unless PlaceCache.where(:chapman_code => c).first };0
=> 0
```

**Comment by Captainkirkdawson** [comment]
@benwbrum   Did you rebuild?

**Comment by benwbrum** [comment]
I did refresh the places cache on production -- see logfiles above.

**Comment by Captainkirkdawson** [comment]
TY Bit sleepy still
