### ISSUE TITLE
Emails being sent after Bounce has sets invalid flag

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1237]

**Comment by edickens** [comment]
For example the UserID Popplefords.  This email message has been received a number of times:-
![capture](https://user-images.githubusercontent.com/8876165/27321220-4bc2b1de-5591-11e7-85c7-adb7493435f4.JPG) including 20 June at 01:35.
The UserID is set to Active = No
This is the full UserID:-
Field 	Value
Forename:	Jean
Surname:	Stickland
Email:	jean.stickland@lineone.net
Email address valid:	false
Reason for invalidating email:	550 5.1.1 sJUFbGasRQ1LG Recipient Undeliverable (TT512)
Email address last confirmed:	19 Nov 2009
Physical Location:	England
Signed up:	19 Nov 2009
Registration completed:	Yes
Telephone number:	
Fiche reader:	false
Syndicate:	Cambs and Hunts - Mary Korna
Previous Syndicate:	CAM
Transcription agreement accepted:	
Last upload:	01 Jan 2015
Number of files loaded:	81
Role in FreeREG:	transcriber
Active:	No
Skill Level:	Unspecified
SC upload data:	false
Date made inactive :	01 Nov 2015
Reason for making inactive (standardized):	
Reason for making inactive (explanation):	No longer transcribing 
So I don't know why a message was sent nor why the rejection email is created.  My only guess is that the SC has uploaded or corrected a file AND the UserID should be set to "SC Uploading data" = True.

**Comment by Captainkirkdawson** [comment]
The script has been adjusted to only report people whose email address is valid
