### ISSUE TITLE
Delete a RL file from the Awaiting Processing also deletes the original

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1240]

**Comment by Captainkirkdawson** [comment]
That is why you have the Remove button. Just removes the waiting file.

It is why the heading for the delete says Delete file and entries

**Comment by Sherlock21** [comment]
My misunderstanding. Sorry to trouble you.

**Comment by CommsCoord** [comment]
Closed by request of Sherlock21
