### ISSUE TITLE
Review and take forwards access to records initiative (O.R.G. Review)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1248]
Pat to advise where that initiative ended up and if there was any outcome to help us get access?

**Comment by PatReynolds** [comment]
Paperwork on this project now in the FreeREG sources and permissions folder on gdrive.

**Comment by PatReynolds** [comment]
The ORG report states that it would be helpful to have a court judgement on the copyright status of Parish registers - this has been superseded.
The ORG report states that it would be helpful to have a court judgement on the copyright status of images of original documents - this has been superseded.
A number of actions were suggested which are not superseded, and added as new stories.

**Comment by Sherlock21** [comment]
But what supersedes paras 1 and 2 please?

**Comment by PatReynolds** [comment]
Statement by CoE means we are now certain there is no copyright in parish registers (more complex for other churches, but ORG report only looked at CoE).
Notice by IPO means it is much clearer there is no copyright in images of original documents https://www.freeukgenealogy.org.uk/news/2015/12/14/no-new-copyright-in-photographs---notice-from-the-intellectual-property-office/).

**Comment by edickens** [comment]
Good news Pat.
My understand is that the parish registers are still under copyright as that is passed down to each new incumbent when the copyright is renewed.  So copyright has not expired.  But the Church of England has stated that the registers are freely available and they do not exercise that copyright.
Does anyone else have more information?
Eric

**Comment by SteveBiggs** [comment]
I'm not a lawyer, but I thought we already knew that the registers
themselves were no longer in copyright? The issue is whether the current
incumbent (generally ROs) can impose rights of usage through T's & C's of
using the record office to view them.

Equally, even if images are not in copyright, the issue is whether the
provider of the website holding them (e.g. Ancestry, FMP) can impose T's &
C's on usage (I think they can and do).

**Comment by PatReynolds** [comment]
Not copyright, Eric, right of access.  This thread is just about what the ORG report says, and it is restricted to copyright.  If there are other issues, please raise as new stories.

**Comment by SteveBiggs** [comment]
Pat, the title of this story is "Review and take forwards access to records initiative". I was not aware that was restricted to copyright. Perhaps the title should be made more specific?
