### ISSUE TITLE
Investigate why bouncing emails rake task has same content

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1254]
The nightly run of the rake tasks repeats the same person nightly

**Comment by edickens** [comment]
It has always only been "Shelley" and I think  that occurred when the rake task first started.  ED

**Comment by SteveBiggs** [comment]
I set Shelley's email address to 'False' a couple of weeks back, but it seems to have been reset to 'True' since.

**Comment by PatReynolds** [comment]
Could she have confirmed it as a correct address when entering the members area of FreeREG?

**Comment by SteveBiggs** [comment]
Most likely, yes.
