### ISSUE TITLE
Create Image Group (IG) Record Web Page

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1255]

**Comment by edickens** [comment]
This is the next stage of V1.5 to link the Image Server (IS) to FR.
When done, it will be possible for Coordinators to see the images from the Places screens.

**Comment by Captainkirkdawson** [comment]
Sorry but I do not understand how this fits in with our data model in which there is no such level.
This story is inappropriate until I have had a chance to review how the data model implementation has diverged over the past month from our original specification.

**Comment by edickens** [comment]
The point of this was to see how what we have been working on might fit in.  I have never seen the images in the data model.
I obviously do not understand how the server works.
As this story is deleted  I've deleted what Bev, Steve and I have done from my computer so as not to confuse myself.  We can start again when we know what can be done.

**Comment by Captainkirkdawson** [comment]
I realise that you want to see progress but before adding a story to implement something that you asked my opinion on a week ago and for which I have had not had time to review was and is in my opinion premature.
I have no idea what you havehave deleted. I am in the process of reviewing what has been done in my absense. But there have been other priority issues to be dealt with that have stopped me looking at it.

**Comment by edickens** [comment]
I've often been asked to create stories rather than ask for decisions by email.  There is no story for you to look at what I sent in an email.  This story was just to put this phase on the list of things to be done sometime.  Perhaps the title was wrong, but Steve, Bev and I did a lot of thinking while you were away.
