### ISSUE TITLE
add a check at batch upload, to identify all date errors

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1258]

**Comment by Sherlock21** [comment]
Any records which have a year error in their key date, cause the year range of that batch to be counted as 0.  This gives the wrong information to all users and prevents the record concerned from being found in researcher searches.
Please scan all  batches at  upload for a valid 4 digit year and flag any errors in the ER manner in User's Batch names listings so they can be corrected there.
Cope with genuine 3 digit years too, as these may be genuine 
Please Run this check on ALL existing batches as there are very, very many with these date errors, which a too numerous to find by hand.

[ THIS request has been input before but its present position is unknown ]

**Comment by richpomfret** [comment]
Proposed solution to partially cover this - UCF updates (we have other 0 date issues relating to date-ranges). @Captainkirkdawson to review current stories for these.

**Comment by Sherlock21** [comment]
The UCF solution may well cover some of these 0 such records, but what about typo errors where there are only 3 digits?

Seems wrong to close my Issue without either: saying why it was not needed in the first place, or how it has been addressed elsewhere on the other hand. 

And The system did not send me a email to say this one had been closed.

**Comment by PatReynolds** [comment]
Closed because in many other issues on the board Kirk is to create a report that lists the issues and the solutions, so we can decide and implement solutions.  It may be possible to start work on the solutions this week.

**Comment by Sherlock21** [comment]
Thank you, Pat. -It would have been useful to say this in the Issue concerned, and copy to the originator.
