### ISSUE TITLE
Backup of mongodb

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1262]
Hi Kirk,

It occurs to me that now MongoDB no longer lives on the app servers it's not backed up. Do you want me to set up a job to dump one of each pair daily and send somewhere?

Or do you have an internal solution?

Regards, l.

**Comment by Captainkirkdawson** [comment]
L

Have copied others.

Personally I wonder about the value of a backup. I was not aware you were so doing previously

Each database has a realtime copy ie we have a 2 member relica set for each shard. Should we loose a member we have a full copy on the other member. We can copy that should be need restore a damaged server.

Are you proposing to use the mongodump and restore or a file system snapshot?

https://docs.mongodb.com/manual/tutorial/backup-with-filesystem-snapshots/

Others may wish to comment

**Comment by Captainkirkdawson** [comment]
On 1/8/17 06:56, Kirk Dawson wrote:
L

Have copied others.

Personally I wonder about the value of a backup. I was not aware you were
so doing previously

Each database has a realtime copy ie we have a 2 member relica set for each
shard. Should we loose a member we have a full copy on the other member. We
can copy that should be need restore a damaged server.


If you're ok with that then so am I!

I'll just point out that replicas aren't backups. For instance, what happens if something mistakenly deletes swathes of data and the deletion is properly replicated? Having off-server historical backups would help recover but replicas wouldn't.

FreeBMD's approach is "we can regenerate all the database data from the input files", so we backup those to a remote server. The recovery time after a catastrophic loss of all databases is the time it takes to regenerate from cold. I don't know enough about FreeREG2 to know if an equivalent approach works.


Are you proposing to use the mongodump and restore or a file system
snapshot?

https://docs.mongodb.com/manual/tutorial/backup-with-filesystem-snapshots/

Whatever fits best, I've not looked too closely into it yet. That snapshot page seems pretty LVM oriented which isn't possible on FreeBSD's ufs, whose snapshots have different properties.

For the avoidance of doubt: I won't start doing anything about MongoDB backups unless you want me to.

**Comment by Captainkirkdawson** [comment]
On 1/8/17 08:37, Kirk Dawson wrote:
You raise a valid point.

But does the BMD approach protect against the deletion of files by the user?

Yes, by historical backups of the /raid tree: 1 per day, kept for 2 months.


How were you backing up when monfodb was on the app servers?

As part of the above on colobus, mongodb tree was included in the (ZFS) snapshots. I don't know how valid this was (probably up to resolution of MongoDB's disk checkpointing) so likely on the wrong side of "an unverified backup is useless" rule!

**Comment by richpomfret** [comment]
Ask @lemon-ukgen to back-up original CSV files (to store remotely), so recreating/rebuilding the database will be possible..

**Comment by Captainkirkdawson** [comment]
Reinstitute the backup of critical collections required to enable search records to be rebuilt from files

**Comment by lemon-ukgen** [comment]
Please can @Captainkirkdawson confirm the location of the CSV files and any other data needed for the rebuild-from-cold approach. Thanks.

**Comment by Captainkirkdawson** [comment]
@lemon-ukgen Its on colobus /raid/freereg2/users

**Comment by lemon-ukgen** [comment]
Great, the current backup of `colobus:/raid` covers that.

The current backup retention is 2 months of daily snapshots. If that's not enough then we can change it, but UKGEN will need a bigger storage server (currently `uakari`).
