### ISSUE TITLE
New transcribers not joining the FR transcribers group

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1263]

**Comment by edickens** [comment]
There have been quite a few new transcribers over the last month and I have sent out invitations, but very few have accepted the invitation.  Are these not for FR, or is there some other reason?  This is a very unusual pattern.
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8019b500bf208a4686b4be8e4ac6e03b37aa.JPG)
![Capture1.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791acdeabf301b44fff9e2c4533317346f6787586e22de61b2f595f581ca9415a5f44fdfadc2ba5e02e6c981e5ab38532022d8c6853beb2901cbe0bbb258b4e8cb5be884ac4ef3e21f5c6.JPG)

**Comment by edickens** [comment]
Is it worth me spending my time sending invitations to the transcriber group?  I now have 25 that I have sent out in the last month which have not been taken up.  Something is wrong.  Or are these not genuine transcribers?

**Comment by Captainkirkdawson** [comment]
IMHO Yes it is worth while. It is also worth your while asking those who did not respond what their intent was in registering if they did not wish to particiapate in the group. Lets find out some facts also are they following the trainig?

**Comment by SteveBiggs** [comment]
Eric, do you send out invitations as soon as they register? I would suggest it would be better to wait until the relevant coordinator for the syndicate they joined, contacts them to confirm why they signed up and gets them into training if appropriate. Even then, they may of course pull out, but that will at least ensure there has been some dialog with them before being invited.
If they do pull out, we should follow up with the questionnaire to find out why.

**Comment by edickens** [comment]
The GoogleGroup Transcribers group is very labour intensive and I would no like to have to keep a list and check with the SC before inviting.  I think we should continue as we are until V1.6 when we can bring it in house.  ED
