### ISSUE TITLE
14 PConfirm SendGrid Bounced emails system is working correctly

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1264]
Priority 14 (0	2	7	5)

**Comment by edickens** [comment]
Every day I get a copy of the Bounced emails log.
![Capture1.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791acdeabf301b44fff9e2c4533317346f6787586e22de61b2f595f581ca9415a5f44fdfadc2ba5e02e6c981e5ab38532022d8c6853beb2901cbe0bbb258b4e8cbfbb8848c0eb3427f5c6.JPG)
(Shelley is there every time.)
But none of the other bouncing emails appear.
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8019b500bf208a468cb1bf8f4ec6ec3d37aa.JPG)
What is more worrying is that the above is a coordinator.
ED

**Comment by Captainkirkdawson** [comment]
See 965

**Comment by PatReynolds** [comment]
@patreynolds to check with @lemon what the clearing process is.

**Comment by edickens** [comment]
On 09/09/17 I received three bounced emails all from UserID CER but these do not show in the overnight bounced email report.
![Capture1.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791acdeabf301b44fff9e2c4533317346f6787586e22de61b2f595f581ca9415a5f44fdfadc2ba5e02e6c981e5ab38532022d8c6853beb2901eb80bbb258b4a84bfb5894dc5eb3826f5c6.JPG)
We  are seen as an "open-relay" or "Abuser".
CER registered in 2013 and confirmed their email address in May.  This is a very active transcriber.

**Comment by Captainkirkdawson** [comment]
Is this sill an issue

**Comment by PatReynolds** [comment]
For review - is this still happening?

**Comment by PatReynolds** [comment]
No working fine, so closing.
