### ISSUE TITLE
Ability to add Record Source Catholic Records Society (to function as for adding church denominations)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1265]
Tasks include adding to picklist of sources, and modifications to DAP(?) and RAP (?) needed to provide transcribers with images from the digitizations made by the CRS and shown on the Internet Archive. (i.e. https://archive.org/search.php?query=creator%3A%22Catholic+Record+Society+(Great+Britain)%22)  E.g. https://archive.org/stream/miscellaneaix14unknuoft#page/32/mode/2up

**Comment by Captainkirkdawson** [comment]
Could you please add the url to where we can locate the images

**Comment by Captainkirkdawson** [comment]
@PatReynolds still awaiting a response

**Comment by PatReynolds** [comment]
https://archive.org/details/publicationscat26britgoog is an example

**Comment by PatReynolds** [comment]
https://archive.org/details/publicationscat26britgoog is an example

**Comment by Captainkirkdawson** [comment]
I still do not understand what is required. We can add new images to the image server, we can transcribe the additional fields for a CRS. 
It seems to me the matter is one of informing coordinators where to get these images.

**Comment by edickens** [comment]
Kirk,
Can you please check.  I think that when an entry has its zero year corrected online then the year range IS recalculated, and reprocessing is not needed.  But this does not happen when a blank, or other, entry is deleted.
I think that recalculate should take place every time any editing, insertion or deletion of an entry takes place.  I'm not sure that this happens.

**Comment by Sherlock21** [comment]
I too ma confused as to the requirements.
We don't have a Source List in FR for the existing records, so why just for the Catholic Society?
If you create such a feature, then who is going to back fit?
Where do you see it fitting in the present display(s).

**Comment by edickens** [comment]
Are we confusing Source and Register Type?  Do we want a Register Type for Catholic?  At present we use OR, Other Register type.  We have the Church denomination of Catholic.

**Comment by richpomfret** [comment]
Closing.
