### ISSUE TITLE
Print-friendly page of Search Results Detail still has  donate loto

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1266]
donate logo is still appearing on the printer-friendly page for detailed search results, and needs to be removed.

**Comment by Captainkirkdawson** [comment]
Thats because we have not yet deployed the fix to production.

As reported elsewhere I have not updated the servers since mid June

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1
