### ISSUE TITLE
Message at login about why and when the users' email address has been made invalid

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/MyopicVicar#1269]

**Comment by SteveBiggs** [comment]
@Vino-S where is this implemented to test? I've checked test2, test3 and production and don't see it.

**Comment by richpomfret** [comment]
Vino to merge and then move back into ready for testing for Steve to look at.

**Comment by PatReynolds** [comment]
Different message is needed for a regular check ( current text is fine for
that) and for after it has been made invalid. Sorry if the distinction is
already there.
The invalid check text should, I think say that it is invalid because we
cannot use it.

**Comment by SteveBiggs** [comment]
Yes, that makes sense, but when it _has_ been made invalid, the message should be on this login page so they get the explanation before they go ahead and confirm the address again.

**Comment by PatReynolds** [comment]
Agreed - contextual message on login.

**Comment by Vino-S** [comment]
Thanks @SteveBiggs and @PatReynolds .
 I agree with @SteveBiggs  that message should be on login(confirm_email_address page). I had updated the code in test3.

**Comment by SteveBiggs** [comment]
Thanks Vino, that looks much better as they have to take action before confirming.

**Comment by richpomfret** [comment]
To add screengrab here for review.

**Comment by SteveBiggs** [comment]
Here is a screenshot of the new login message:
![Capture.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588631f51e19621a00230146/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8316b500bf218b4e8db7bd884dc8ec3b37aa.jpg)

**Comment by PatReynolds** [comment]
Would it be clearer as "confirm your email by clicking the 'true' button below, and then Confirm"?

**Comment by SteveBiggs** [comment]
Yes.

**Comment by richpomfret** [comment]
@Vino-S to make the requested text update.

**Comment by Vino-S** [comment]
Updated the code in test3

**Comment by SteveBiggs** [comment]
Wording looks good now.

**Comment by Vino-S** [comment]
Pushed to live
