### ISSUE TITLE
Transcriber Help Notes explain pre-1000 date formats

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#1271]
If users are transcribing dates preceding 1000 AD, they need to use four digit dates by prepending a leading zero onto their year.  We should add this to transcriber help.

**Comment by AlOneill** [comment]
Year format clarified for 3-digit years in General guidance > Dates section of https://www.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers

**Comment by Sherlock21** [comment]
Yes, thats  fine.
