### ISSUE TITLE
test2 css issue

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1273]
EricB reports. The place name Initial Letters selection box suffers the same problem as My County selection box.

ie the A comes in the header space and I can’t pick places beginning A
As a development setup the css is recompiled every time it is accessed.
All other setups use a production setting where the css is precompiled
Appears only to affect safari

**Comment by Sherlock21** [comment]
This does not happen in the other test region T3 though. is that done differently, or am i just unlucky?
After my crash out results just emailed to you, you will be wishing i had not found a way around! sorry.

**Comment by Captainkirkdawson** [comment]
As noted in my opening "All other setups use a production setting where the css is precompiled" to be clear that includes test3

**Comment by Sherlock21** [comment]
Why can't this Test2 be set up the same way as the rest then please?
Its really difficult for me to use Opera for testing thisIS stuff [ because I ant drive it half as well as Safari]

**Comment by Captainkirkdawson** [comment]
Because the primary purpose of the development test site is for the developers to develop/test code. If we are testing new css we do not wish to have to do the compilation and deployment of the css each time a line is changed.
It is our intention to see why safari is acting differently from all other browsers
