### ISSUE TITLE
Images and Image Server Groups-default status

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1274]
Currently when loading an image link we assume it is UNALLOCATED. For the Image Server Groups we have made an assumption that if the register already exists then the Images have been transcribed.

**Comment by Captainkirkdawson** [comment]
I believe we should not make any assumptions. The Group should be UNALLOCATED by default.
I further believe that the content of the status field in the Image Server Group should reflect the status of all the Images. ie. The status of the images is set by the coordinator. We then compute a summary statement for the group based on what is in the image field for all images.

**Comment by Captainkirkdawson** [comment]
EridD commented.
At present this system is not linked to the transcriptions.  So "Status" = TRANSCRIBED is a default assumption.  This does apply to most, other than SSX, images.

UNALLOCATED means that no transcriber has been asked to work on them.  So unless they need to be done again, then if they have been TRANSCRIBED, they should not be allocated to a transcriber.  When the transcriber says that they have finished working on them, then the images revert back to UNALLOCATED.

**Comment by Captainkirkdawson** [comment]
If they are finished surely their status would become to TRANSCRIBED. (I had been planning that the allocation system would key in on images that were UNALLOCATED)

**Comment by Captainkirkdawson** [comment]
Steve noted:
On 18 August 2017 at 12:52, Eric Dickens-gmail <freereg.edickens@gmail.com> wrote:

At present this system is not linked to the transcriptions.  So "Status" = TRANSCRIBED is a default assumption.  This does apply to most, other than SSX, images.

That would make sense but is not the case. Places in Sussex that have not yet started at all have all their image groups showing as UNALLOCATED.

UNALLOCATED means that no transcriber has been asked to work on them.  So unless they need to be done again, then if they have been TRANSCRIBED, they should not be allocated to a transcriber.  When the transcriber says that they have finished working on them, then the images revert back to UNALLOCATED.

This suggests that individual images would never be marked as TRANSCRIBED. They would either be UNALLOCATED (not started) or IN_PROGRESS, but when completed they revert back to UNALLOCATED.

**Comment by Captainkirkdawson** [comment]
EricB commented
Eric D

So in the case of your last sentence, how do everyone understand the difference between Unallocated at the start of para 2, and Unallocated at the end of para 2 - shurely that would imply the already transcriberd images could be reallocated to another Transcriber? especially if the CC changes.

**Comment by Captainkirkdawson** [comment]
EricD responded:
Steve,

UNALLOCATED just means that it has not been assigned to anyone for them to transcribe it.  In fact Kirk in conversations has referred the act of giving images to someone to transcribe as "ASSIGNING".  So perhaps they would be better called "UNASSIGNED".

An image will be UNASSIGNED both before and after it has been worked on.  It is only as it is being worked on that it becomes ALLOCATED or ASSIGNED. This will be constantly changing.

If you need to know who did the transcription, then you need to look at the Batch.  When we get to matching batches to images, then you will know who worked on which images.  Remember that more than one person can work on one image, because it may be transcribed more than once, so you cannot put a person's name against an image.

**Comment by Captainkirkdawson** [comment]
The comment about transcriber is off topic please refer to 1277

**Comment by Captainkirkdawson** [comment]
EricD

I think we are getting confused here between the Status of the Image Group and the Status of the Image.

Some thought needed here.

**Comment by Captainkirkdawson** [comment]
I am of the opinion that the Status (and other fields) in the Image Group is a summary of the content in the respective fields in the images

**Comment by Captainkirkdawson** [comment]
EricB commented
EricD
yes, i am with your thinking about the use of Assigned.

BUT concerning the images in a pool: would it not be better at the basic Image level to know which images have been transcribed by someone, and which images have NOT?

of is this somewhere else that i did not find?

**Comment by Captainkirkdawson** [comment]
Steve noted.

Yes it is confusing. We need to agree on the meaning of the status at the group and image level. Ignoring the ERROR state, here is my initial take on it:

Image Group:
UNALLOCATED		None of the images in the group have been allocated
IN_PROGRESS		At least one image in the group has been allocated
TRANSCRIBED		The whole group has been transcribed
REVIEWED		The whole group has been transcribed and reviewed

Image:
UNALLOCATED		The image has not been assigned to a transcriber
IN_PROGRESS		The image has been assigned to a transcriber
TRANSCRIBED		The image has been transcribed
REVIEWED		The image has been transcribed and reviewed

If the image reverts to the UNALLOCATED (or UNASSIGNED?) state, how is it marked as transcribed? I would think it should stay at TRANSCRIBED unless there is a reason it needs to be re-transcribed and only then should the state revert to UNALLOCATED.

**Comment by Sherlock21** [comment]
Why are some dates in RED and most in BLACK in this view please?
![Data Colours.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/545bc5c91920350200d20f63/125516c66e82c728ace21e0d46cc958e22c2a0a683e6aa51b71fbcd6395428792c07b7692ac7b67bba417a0456564aa4415f0d41fcfb892ba7b56970890a19f1c32f0e2a92624cf5f2d75dad0ba8228d4584b3bc894ac5e13821e68b8b472c53.jpg)

**Comment by SteveBiggs** [comment]
Because they fall outside the range of dates at the Image Source level:
![capture](https://user-images.githubusercontent.com/25303607/29712280-fc96e6d2-8990-11e7-9271-2fc4ba3905b2.jpg)

**Comment by Sherlock21** [comment]
I though that might be the intent.
BUT in the case of the bottom one in my attachment ( SSX-Balcombe-GR-1568-1596-234-1-1-3)  in Test2, the PR shows start date 1565 an end date 1875.

So how then is the image for 1568 outside the limits?

**Comment by Sherlock21** [comment]
Steve - I just deleted my reply - I got the different images I was comparing, wrong.

**Comment by Sherlock21** [comment]
I do have an issue about it though, but am still considering the process.

**Comment by Sherlock21** [comment]
I am trying to work out WHERE the prime data comes from, with which this comparison is made to conclude the IMAGES list years is out of range.  And if the CC does not in fill the potential years range of records which exist on - say - the Details of Parish Register  page, then what? Please advise.

**Comment by edickens** [comment]
EricB
I may have misunderstood you, but the years showing now in the group have been created by Bev by extracting the year range from the image filenames.  In the future, when new images are uploaded, the year range and difficulty will be entered by the person uploading.

**Comment by Sherlock21** [comment]
No, it was me who expected the new program to extract this from/to  date range form the info put in by the CC in setting up the church name or something.

Need to see that working for real before I say any more. - no System Analyst input you see.

**Comment by SteveBiggs** [comment]
EricB,

See story #1284 for details of the relationship between Source date range
and Group date range.

Steve


Stephen Biggs
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
@SteveBiggs @edickens @Sherlock21 

I would like to return this story to its original intent which was to reach agreement on what defaults we set for Images as they are setup when creating from the skim of the Image Server.
Difficulty options are  
Complicated_Forms  / Damaged / Learning /  Post_1700_modern_freehand  / Post_1530_freehand_Secretary  /   Post_1530_freehand_Latin /  Post_1530_freehand_Latin_Chancery  /  Straight_Forward_Forms

Remember these can be set afterwards
Status options are ERROR /  UNALLOCATED / IN_PROGRESS / TRANSCRIBED / REVIEWED

**Comment by edickens** [comment]
As we do not have an "Unknown", then I suggest "Straight_Forward_Forms" for the default of existing images.  This will mean that all transcribers will be offered these images.  If the transcriber then reports that they are too difficult, then "Difficulty" can be changed.
Remember that at least 95% of the images on the Image Server have been transcribed, so this information is not too important.
The important use of this information is when new images which have not been transcribed are uploaded.  That is when the IG information MUST be entered.

**Comment by SteveBiggs** [comment]
Does there need to be a default Difficulty? Whatever we make it will be wrong for most Images/Groups so would it be better to just leave it blank when first created? That would then prompt the CC to check before allocating (which is what we do now) and set the appropriate Difficulty level for the Group.

Since most existing images on the IS have been transcribed as Eric says, then TRANSCRIBED would appear to be the best default for Status, but of course as new images are added in future, they are most likely to be unallocated so will need to be changed.

**Comment by Sherlock21** [comment]
If Difficulty (of image) is mandatory, then I agree with Straight Forward. and if someone decided its too difficult THEN the CC can adjust it.

For Status I think it dangerous to put Transcribed in as the starter to all. Those few that have not been transcribed will never get allocated as the CC can't sort out the wood from the trees.
Even if one says: pif there are some batches for that place/church, it does not  mean that it corresponds to All the Images are Transcribed. Would it take a lot of effort to scan the batches for a Minimum start & Max end date of the batches, and compute whether the images have ALL been transcribed, and base the default on that though?

**Comment by edickens** [comment]
I would like to see your last sentence.  We already have the first and last year in a Batch and that batch has County/Place/Church.  The Image Group has the same information.  So they could be matched, except that the Register Types do not always match.  Particularly those from FR1 marked "Unspecified".
With a suitable report and set of actions, I am willing to go through all the Image Groups and associated batches and match them up.  It just needs, within a County/Place/Church,  one column to show Image Group years and one to show Batch years.  Then just mark which batch has all or part of which Image Group(s).

**Comment by Captainkirkdawson** [comment]
We are not forced to set a default we can leave the field empty, That would have benefits in that we know it has not been set.

**Comment by Captainkirkdawson** [comment]
Erics your last postings although useful they were not relevant to the setting of defaults.

I would note that the register contains the start and end dates for the actual records, This can be compared with the image server first and last dates! Perhaps you need to start a story that asks for a special report to list this dates in register and image server.

**Comment by edickens** [comment]
Before we start new stories for reports, I would like to see this phase completed and live for all counties.  We can then see what is really needed.  I'm concerned that we will create a report and then spend time changing it.

**Comment by Captainkirkdawson** [comment]
I agree 100% in need to complete this phase before starting anything unrelated but the story needs to be there so it is not forgotten

**Comment by Captainkirkdawson** [comment]
Have changed the rake task to leave all defaults as nil. Bev will write actions for county coordinator to set status at the source level. Actions already exist to propagate at the group level.

**Comment by Captainkirkdawson** [comment]
Completed
