### ISSUE TITLE
Sources-Name

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1275]
It has been suggested that the Heading Names Sources be replaced with Image Sources or Data Sources.

**Comment by Captainkirkdawson** [comment]
MY own preference is Image Sources. I believe Data Sources is misleading

**Comment by SteveBiggs** [comment]
Leaving it as Sources allows for all types of sources, which may not always be images.

**Comment by SteveBiggs** [comment]
Since the button 'Manage Images' takes you to the Sources page and there it says; 'Sources of images for ....' , perhaps we should stick with 'Images' as the name for all source files, so use 'Image Sources' as Kirk suggests.

**Comment by Captainkirkdawson** [comment]
Summary of changes required. (Almost all these changes are cosmetic and require to internal code variable name changes)

On the current Sources Index display change 1) The heading for column 1 from Sources to Image Sources, 2) the title "Sources of images for ....' to "Image Sources for ...." 3) The Breadcrumb from Sources to Image Sources, 4) The Create new Source button lable to Create new Image Source.

On the current Sources show display change 1) Field 1 from Source Name to Image Source Name, 2) the title "Sources of images for ....' to "Image Source for ...." 3) Add a Breadcrumb for the display called Show Image Source and link to Image Sources, 4) The Create new Source button lable to Create new Image Source. 5) The List Image Server Groups button to List Image Groups 6) The Edit Source button to Edit Image Source, 7) The Delete Source button to Delete Image Source

On the current Sources edit display change 1) remove field 1 Source since this cannot be edited, 2) the title "Image Server for ....' to "Image Server source for ...."  (Or Other Server1 souce for ....) 3) Add a Breadcrumb for the display called Edit Image Source and link to Image Sources, 4) Source notes to Image Source Notes

The following is a new requirement. Remove the propagate selection at the bottom of the edit display. Add a new button to the show before the Delete button call Propagate Image Source Information. This links to a propagate action that works in the same mannaer as the propagate difficulty etc to images. 
Include a Select All option

**Comment by SteveBiggs** [comment]
Also change the header on column 4 of  Places from Sources to Image Sources.

**Comment by Sherlock21** [comment]
What do you expect to be put in here then?
Which RO? or which reference book if its a Transcription?

OR
who bought it?
OR which Place & church its for & a photocopy of a Church Register or  typed transcription?

**Comment by Captainkirkdawson** [comment]
Steve's comment refers to https://github.com/FreeUKGen/MyopicVicar/blob/bevbranch1/app/views/application/_place_index.html.erb
Will leave in this story

**Comment by Captainkirkdawson** [comment]
EricB your comments refer to the fields in the Image Source. An example of what could be there is shown in
https://test2.freereg.org.uk/sources/599626a6e937903587d0b06b

**Comment by bev-fc** [comment]
@Captainkirkdawson change is pushed, please verify if it works as expected, if I missed any needed change or there is any mistake, please let me know.

**Comment by SteveBiggs** [comment]
Results of my testing:

What is the Sources Index display?

Sources show display:
1)  Good
2)  Actually says "Image Server Source for ....", but this is fine.
3) Breadcrumb is actually called "Image Sources", but this is fine.
4) Good
5) Good
6) Good
7) Good

Sources edit display:
1)  Good
2)  Good
3) Breadcrumb is actually called "Image Sources", but this is fine.
4) Good

Propagate changes all good.

**Comment by SteveBiggs** [comment]
OK, I've found the Sources Index display:
1) Heading still says "Source", should be "Image Sources"
2) 3) 4) all Good

**Comment by Captainkirkdawson** [comment]
TY Steve
@bev-fc 
![image_source_index](https://user-images.githubusercontent.com/2874694/29567596-02cd325a-870b-11e7-963a-6b3f8e8fc9b6.JPG)
and 
![manage_images](https://user-images.githubusercontent.com/2874694/29567615-1082057e-870b-11e7-9e7d-ecf78b787a46.JPG)

**Comment by SteveBiggs** [comment]
There is something strange about the place Abbotsford. It does not show in All sources for County SSX yet it does have images. There could be others, but being the first in the alpha list, I noticed it.

**Comment by SteveBiggs** [comment]
It has Lyminster images (that EricB moved?) but why would that stop it showing?

**Comment by Sherlock21** [comment]
this is the place that I have used up to date for all my image testing stuff.

SO may well have been messed up by me when I was having difficulties with working out how it functioned. ON the other hand, what you see might well be some of my snags already reported are still there.

**Comment by Sherlock21** [comment]
I did not go into Lyminster so far as I recall - unless by accident that I did not notice!

**Comment by Sherlock21** [comment]
HAs someone taken Abbotsford off the listing of Images?
it was there a moment ago, and when I came back from writing my last post, it have gone from the list for SSX completely!

**Comment by bev-fc** [comment]
[SSX.docx](https://github.com/FreeUKGen/MyopicVicar/files/1242270/SSX.docx)
@SteveBiggs @Sherlock21 attach is the original file I used to retrieve SSX images' information into FR, it doesn't include place 'Abbotsford'

**Comment by SteveBiggs** [comment]
Thanks Bev, that would explain it.  It only has some images now because Eric (or somebody) moved some from Lyminster.

**Comment by bev-fc** [comment]
@SteveBiggs @Sherlock21 unless one case I can imagine, 

1. EricB created a new image source under 'Abbotsford' manually
2. he moved some images from Lyminster' to Abbotsford
3. the new source created by EricB disappeared

then, something was wrong, need to investigate.

**Comment by bev-fc** [comment]
sorry my mistake, currently if there is zero image source under a register, the code does not allow to go to source level action

**Comment by bev-fc** [comment]
@Captainkirkdawson change is pushed, please verify if it works as expected.

**Comment by Sherlock21** [comment]
Not guilty!

They were already there when started. and being lazy, just picked the first place name in the list. So have we a snag there,Steve?who else has been testing this feature?

**Comment by Captainkirkdawson** [comment]
@bev-fc  pulled into test2. Looks OK

**Comment by SteveBiggs** [comment]
Looks good to me too.
