### ISSUE TITLE
Image Server Groups Name

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1276]
EricD asks.
Should the Option be "List Data Groups" not "List Image Server Groups"? These groups will get created to show where to find data for transcribing which may not be on the Image Server and may not even be images, such as Phillimores Transcripts

**Comment by SteveBiggs** [comment]
I would suggest "List Source Data Groups"

**Comment by Captainkirkdawson** [comment]
I have real difficulty with the use of data in any of these links as we are not working with data but with images of data.
I had asked Bev to include Image Server to make it clear that we were working with material on our Image Server not other Image Sources.
It is not clear to me that other image sources will have groups of images hence the need to be careful

**Comment by SteveBiggs** [comment]
Perhaps "List Source Groups"? As Eric says, in the future they may not always be images or be on the server.

**Comment by Captainkirkdawson** [comment]
Agree that we should keep our internal naming needs away from their public usage. 

There will be separate internal actions depending upon the the actual image source

I fully agree that images may be in different locations. 

Find it hard to conceive that they will "not always be images" perhaps someone could expand

**Comment by SteveBiggs** [comment]
The most common other format if PDF from other transcriptions.

**Comment by Captainkirkdawson** [comment]
Ah now I understand.  But are we then not in danger of confusing a source with a type of "image". A source is a location somewhere that stores digital material that we can access. A group is a subset of that digital material defined by the owner of that digital material. Our Image Server "could" store PDF pages as images in which case a PDF document could be the group.

**Comment by edickens** [comment]
I have uploaded some CSV files which are post1917, just to keep them safe, and these need to be edited and incorporated into the database as the years go by, or until we have the 100 year rule processing in place.  ED

**Comment by edickens** [comment]
There are also some Word documents that are transcriptions done by people in the parish which need, or have been, converted and uploaded.  ED

**Comment by Captainkirkdawson** [comment]
OK EricD but where is the source  ie the location that stores this digital material that we can access

**Comment by edickens** [comment]
They are in the folders of the Image Server under the County/Place.  ED

**Comment by Captainkirkdawson** [comment]
In which case they should ultimately appear as "images" in "groups" as part of the Image Server Source

**Comment by edickens** [comment]
Yes.  And the Group description will describe content and years.  ED

**Comment by Captainkirkdawson** [comment]
Please provide a county place example

**Comment by edickens** [comment]
SOM Barwick
LAN Castleton Moor_St Martin-Post 1917 OD

**Comment by SteveBiggs** [comment]
If we agree that they are some form of 'Image', but not necessarily on the Image Server, then should we call it "List Image Groups"?

**Comment by edickens** [comment]
I agree with that.  We have been calling it that for ages, so no need to change, ED

**Comment by Captainkirkdawson** [comment]
Conclusion
The List Groups index display. 1) The title "Image Server Groups of......" should be changed to "Image Groups for the Image Server Source of" (where Image Server is either that or Other Server1 or Other Server2; do not hard code the latter but display the content of the variable holding that name). 2. Add a breadcrumb for this display List Groups linking back to

**Comment by bev-fc** [comment]
@Captainkirkdawson change is pushed, please verify if it works as requested, and let me know any needed changes or mistakes you see.

**Comment by SteveBiggs** [comment]
Results of my testing

List Groups index display:
1) 2) both Good

List Groups show display:
1) 2) 3) all Good

List Groups Edit display:
1) 2) both Good
