### ISSUE TITLE
Images-Transcriber field

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1277]
We have a Transcriber field at the image level and also at the Image Server Group level.
We had assumed that the transcribers userid would be entered when the image was allocated or assigned. That userid would be retained when the user confirmed completion at which time the status would changed to TRANSCRIBED

**Comment by Captainkirkdawson** [comment]
EricD commented.

If you need to know who did the transcription, then you need to look at the Batch.  When we get to matching batches to images, then you will know who worked on which images.  Remember that more than one person can work on one image, because it may be transcribed more than once, so you cannot put a person's name against an image.

**Comment by SteveBiggs** [comment]
Perhaps the field could be Transcribers in the same way as the one at Group level so that more than transcriber could be listed?

**Comment by SteveBiggs** [comment]
It would be useful if the Propagate Transcribers selection boxes worked so you could click the first, then shift-click the last so that all images in between were selected.

**Comment by Captainkirkdawson** [comment]
Agree that heading should be plural.
Multiple transcribers can be selected and are displayed.
Have created a new story on the propagate request as this is likely a general request (1278)

**Comment by Sherlock21** [comment]
Tested out the image Server boxes on my iPad.
No issues wight he overlapping key boxes as there are on  my iMac.
changed the Status of an in=mage to In Progress - OK
changed the difficulty to latin - OK
tried to allocate that image to a name: the list of transcribers showed in a drop down box  but i have no idea if the capability of the people in the box was correct for the class of image - I am in the list and in Prod, I am not Latin qualified so i suspect this is Allocation field name box is not linked to competency, SHOULD it be?
I  Actually allocated the same image to 4 people - all 4 highlighted as i clicked m=names, but I expected the name(s) to come up in the window under the label TRANSCRIBER.

IT DID NOT list names. just says 4 items. which I think is not the right solution for the CC.
BUT when I returned to the main Image Name list, these chosen 4 names did appear. So not an issue after all - just a bit surprising if one got distracted during doing the job, you might end up allocating to too many people?

tried to revise my list of people this image is allocated ( from the mail images listing.

I can't do ED nor SH on the item I just added allocate to.

I can't now do any of the 6 items in the free box at the top of the table: move multiple images; List image groups; propagate status etc. I just get Safari cannot open the page.

in fact I can't do anything at all  in this session
End of this test

**Comment by Sherlock21** [comment]
AN ISSUE.
I restarted my iPad from last test reported above. (about 5 minutes to get started again as i am not so nifty with it)).
Has someone else just changed ALL these images for Abbotsford into Transcribed? they were all Unallocated  when I started the above test. and one should have been left at In Progress.
Else can you tell me which images I was actually on in the above test?

**Comment by Captainkirkdawson** [comment]
No idea who/when they were changed

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by SteveBiggs** [comment]
I have not touched Abbotsford.

**Comment by Sherlock21** [comment]
Then there is a big SNAG here.

I just edited Abbotsford St Mary Magdalene PR 
Images of Image Server SSX-Lyminster-131-1-1-1-GR-1566-22056 of the Parish Register register for St Mary Magdalene in Abbotsford of Sussex

from TRANSCRIBED, and set it back to In PROGRESS.
Then set that back to Review.
Went to the page where you see all the image names and image numbers from 1 to 51  and they ALL have changed  status back to Unallocated.
SO am I getting mixed up between a single image (of which there are 51) and the group?
OR is the package getting crossed wires.

I don't keep swapping about - just Action & navigate on the page that the action takes me to.
Will someone else do this and see where you get to please.

**Comment by Sherlock21** [comment]
Withdraw my last post completely.

I had crossed over from IMAGE GROUP to INDIVIDUAL Images.

Very confusing nomenclature.

**Comment by Sherlock21** [comment]
Going back to the initial comments about allocating an image group to a single person: why  does entering a transcriber to the GROUP box not propagate down to each of the images in that group?
![Image Group allocation.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/545bc5c91920350200d20f63/125516c66e82c728ace21e0d46c1999b2487c38e9de6aa53e45cfc9826452667200bad693cc7f33ab0487e021b4d44be445b0a17adac8022a2be3c77d8590befd16d5e77933d12faaa9e0dfd50e474d412dcfce9c85ecafa3e24ed8a8a4f3d1d051e8ffd5932a3905985.jpg)

**Comment by SteveBiggs** [comment]
It may be that only a part of the group is allocated to one transcriber and another part to another transcriber. Arguably, it should only be possible to assign the images themselves to transcribers (using the propagate as necessary) and have the Group field automatically filled in with the transcriber(s) from the image level.

**Comment by Captainkirkdawson** [comment]
This story has been superseded by 1285
