### ISSUE TITLE
Propagate select range

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1278]
The current propagate action tool works on a selection and click selection on/off basis
A select of a range (cntl shift) would be useful

**Comment by Captainkirkdawson** [comment]
@bev-fc  this may be tough but it has a great payoff. Want to give it a go while we debate the other stuff

**Comment by bev-fc** [comment]
@Captainkirkdawson change is pushed, please take a look if it looks okay and/or if there is any mistake.

**Comment by Captainkirkdawson** [comment]
@bev-fc the test I ran did function as I would have expected. ie select image number click and hold shift key  go down (up) to a further image, click that and the range between the two is selcted.

**Comment by SteveBiggs** [comment]
When will this be implemented on Test2 for us to try?

**Comment by Captainkirkdawson** [comment]
I have clarified my earlier comment as it did not select a range. I really must read my posts more clearly. I read what I thought I had written. Unfortunately it was missing a not

**Comment by bev-fc** [comment]
@Captainkirkdawson it works on my machine. There is a conflict from your original post and your test post though, in the first post, you said it is (cntl shift), in your test post, you said it is shift, I don't know which scenario did you use for testing, the one coded is ctrl+shift

**Comment by Captainkirkdawson** [comment]
Boy it really is time for my retirement. 

ctrl+shift and then selecting first and last works perfectly in filling the range and it can be used multiple times. also a single image in the range can be deselected.

will deploy

**Comment by bev-fc** [comment]
@Captainkirkdawson I think that's because you need to put everything together and summarize, I pretty much read every reply very quickly for a brief idea only and just wait for your final conclusion post, this saves a lot of my time, otherwise it is too overwhelming.

**Comment by Captainkirkdawson** [comment]
Thats what I have tried to do in the stories that I have moved from incoming to ready. They are in order of priority. In each of them I have summarized the conclusion of the discussion. Those still in incoming have not yet reached a consensus.
You are free to take those ready stories and action them.

**Comment by SteveBiggs** [comment]
Took me a while to realise that I had to hold ctrl-shift for both FIRST and last selection, but knowing that it works fine, thanks Bev.
