### ISSUE TITLE
Search results performance tuning

### ISSUE THREAD

**Issue by graphiclunarkid** [FreeUKGen/MyopicVicar#128]
As a researcher I want searches to return within a maximum of 10 seconds so that the site feels responsive

ACCEPTANCE CRITERIA

- I can conduct a search likely to return a large number of records. The system spends a maximum of 10 seconds returning and displaying the results.
- If further searching needs to take place each subsequent search takes no longer than an additional 10 seconds per search.

**Comment by Captainkirkdawson** [comment]
Have added indexes to extent seems reasonable. Unlikely to achieve 10 sec response for complex searches. Are achieving good response on simple searches with limited results.

**Comment by Captainkirkdawson** [comment]
Longest running search today 28 March is 16 seconds; almost all are less than 10 sec
