### ISSUE TITLE
Source who can action create, edit

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1282]
Can we agree on what roles can

a) create new Sources

b)edit an existing Souce

**Comment by SteveBiggs** [comment]
I would suggest CC, DM and Sys Admin

**Comment by edickens** [comment]
CC to have access only to their Counties.

**Comment by Sherlock21** [comment]
I agree with that too - including ED's last item.

**Comment by SteveBiggs** [comment]
Agreed.

**Comment by Captainkirkdawson** [comment]
Conclusion:
Implement a check on the display of Image Source actions so that they can only be seen by those with the authority to use the action. This has been the FreeREG way. 

So  system_administrators and data_managers can see and use create, edit and popagate actions for all counties. County_coordinators can see and use create, edit and propagate actions for their county (ies).

**Comment by SteveBiggs** [comment]
It does not appear to be possible to create a Source in a register that has no existing Sources:
![capture](https://user-images.githubusercontent.com/25303607/29616606-00cff83e-880a-11e7-8485-63c12b8bbfff.jpg)

**Comment by bev-fc** [comment]
@Captainkirkdawson I put the change for both source and image group in one push marked for #1283 , please verify.

**Comment by Captainkirkdawson** [comment]
Pulled into test2

**Comment by SteveBiggs** [comment]
I'm not sure what I'm supposed to be testing here. CC's can already only access actions for their counties and it's still not possible to create an Image Source for a register that doesn't already have one. Please clarify what has changed.

**Comment by Captainkirkdawson** [comment]
The change permitted just system_administrators, country_coordinators and data managers to view all images for all counties. County_coordinators can access the images for their counties. Currently syndicate_coordinators and others not specified here should not be able to view any actions related to image sources, image_groups and images.

**Comment by Captainkirkdawson** [comment]
Bev corrects me "the code currently allows syndicate_coordinators and others not specified to view source, image group, images, but no edit, create, delete, propagate."

**Comment by SteveBiggs** [comment]
The point I'm trying to make is that if I login in with my CC/SC userid, the ONLY counties I can do anything at all with are the ones I coordinate:
![capture](https://user-images.githubusercontent.com/25303607/29706889-429ea982-897b-11e7-82f3-534f1ff910cd.jpg)
So I never could access other counties actions for managing images nor anything else.

What am  I missing here?

**Comment by bev-fc** [comment]
I realized there could be a misleading by what I said. 

'Sources' is a subset under 'manage counties', not all user roles can have 'manage counties' button, this is the first level of filtering, decide who can go to 'manage counties' level and see which counties, then, for those who accessed counties level, users are splited to 3 categories for sources' information: 

1. one is 'admin' and 'data manager', they can see all buttons under Source/Image Group/Images, they can assign/re-assign image_group or images to any userid 

2. the second is 'county coordinator', they can see all buttons too but can only assign to userids under their belonged counties

3. the third is all others, they can only use 'show' button to display source/image_gorup/images

Hopefully this time I make it clearer.

**Comment by SteveBiggs** [comment]
Thanks for clarification, Bev. That makes more sense now.

By "all others" in 3, I assume you mean all others who can manage counties (i.e. Country Coord and Documentation Coord)?

**Comment by bev-fc** [comment]
Yes
