### ISSUE TITLE
Image Server Group edit and create

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1283]
a) create new Image server group

b)edit an existing Image server group

**Comment by SteveBiggs** [comment]
Again CC, DM and SA

**Comment by Captainkirkdawson** [comment]
But with the same caviat that is on the the source i.e. the CC can only work on their county?

**Comment by Captainkirkdawson** [comment]
Conclusion:
Implement a check on the display of Image Group actions so that they can only be seen by those with the authority to use the action. This has been the FreeREG way.

So system_administrators and data_managers can see and use create, edit and popagate actions for all counties. County_coordinators can see and use create, edit and propagate actions for their county (ies).

**Comment by bev-fc** [comment]
@Captainkirkdawson change is pushed, please verify if it meets the requirement, and let me know if you see any missed modification or mistake.

**Comment by SteveBiggs** [comment]
Since a CC can only manage their own county, isn't this restriction inherently the case?

**Comment by Captainkirkdawson** [comment]
Pulled into test2

**Comment by SteveBiggs** [comment]
Per my comment above, what has changed?

**Comment by Captainkirkdawson** [comment]
See 1282. The key change is that people who are not permitted the actions do not see the action

**Comment by SteveBiggs** [comment]
Confirmed as tested and good.
