### ISSUE TITLE
Source and Group Date Range

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1284]
In the edit of the dates in these 2 documents we impose a requirement that the end is greater than the start, that it is 4 digits,
Is there an absolute minimum or maximum?
We could add a check at the group that it is within the range of the source?

**Comment by edickens** [comment]
Date range checking is always worthwhile.
A future check would be sensible, but most errors are 1800 for 1700.  Start less than end is the most useful.

**Comment by Sherlock21** [comment]
It would only be practicable to test that the end date is not earlier than the start date. And its not in the future. And it is a proper yyyy year. Whilst they are not total checking, they re a lot better than doing nothing aren't they.

**Comment by SteveBiggs** [comment]
I agree with both Erics. But it would make sense to check that group date is within range of the source as Kirk says.

**Comment by Sherlock21** [comment]
Sure.

**Comment by Captainkirkdawson** [comment]
Still awaiting views leading to agreement on weither to impose an absolute minimum/maximum  value ie do have have a minimum in source? Registers did not start until 1537 but there earlier records.  Do we reject a future maximum aa EricB has suggested?

**Comment by SteveBiggs** [comment]
My view is:
Absolute minimum = 0000
No absolute maximum except it cannot be in the future

Also group dates must be within source date range

**Comment by edickens** [comment]
Agreed  ED

**Comment by Sherlock21** [comment]
It would fit my criteria too - and save us going back to change things if/when we get images from the pre 1000 AD. ( if you use leading zero to make up the four digits - as in date range in the Transcriptions area.)

**Comment by Captainkirkdawson** [comment]
Summary conclusion:
The min year for a image source is 1000 (We may want to put it freereg_options_constants rather an hardcode). The max year is the current year.
The Image Group dates must lie within the min and max years for the Image Source they belong to

**Comment by SteveBiggs** [comment]
Is there a problem with making the min year 0000 as suggested?

**Comment by PatReynolds** [comment]
I don't think there's a problem.  Earliest writing in Britain is mid first century.

**Comment by Captainkirkdawson** [comment]
Revised summary conclusion:
The min year for a image source is 0000 (We may want to put it freereg_options_constants rather an hardcode). The max year is the current year.
The Image Group dates must lie within the min and max years for the Image Source they belong to

**Comment by bev-fc** [comment]
@Captainkirkdawson length of year will be 4 digits fixed or flexible ie. <= 4 digits?

**Comment by Sherlock21** [comment]
I would say: FIXED so that its common with year in the Parish Records section. and everyone will be on the same playing field, in Each sub application.

**Comment by SteveBiggs** [comment]
I agree - fixed 4 digits.

**Comment by bev-fc** [comment]
@Captainkirkdawson change is pushed, please review if it matches expectation, if there is any changes needed or there is any mistake, please let me know. 

1. for source eidt or create, the check will be: 
min year >= 0000
max year <= current year
source_min_year < source_max_year

2. for image group edit or create, the check will be: 
where source has min year, image_group_min_year >= source_min_year
where source has no min year, image_group_min_year >=0000
when source has max year, image_group_max_year <= source_max_year
when source has no max year, image_group_max_year <= current_year
image_group_min_year < image_group_max_year

3. For empty min_year and/or empty max_year source, after it is modified with a min_year and/or max_year value, the next first time when the image_group under this source gets edited, this group's image_group_min_year and/or image_group_max_year will be compared if they are within the new source_min_year and/or source_max_year value range

**Comment by Captainkirkdawson** [comment]
Pulled into test2. Will leave it to the team to test

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by SteveBiggs** [comment]
Testing so far:
1. All looks good.
2. It does appear to be possible to create a new Image Group in an Image Server that does not have any already existing:
![capture](https://user-images.githubusercontent.com/25303607/29613937-10d85de8-8800-11e7-9296-bd59157bdeff.jpg)
- No "Create Image Group" button

**Comment by SteveBiggs** [comment]
Further testing:
2. All looks good. However, if the Image Server dates are subsequently changed, there is no check the other way to see that the groups are still within date range.

**Comment by SteveBiggs** [comment]
3. Looks good. If Image Server dates are changed then the next time a group is edited, the date checks are applied (covers my comment in 2. above)

**Comment by bev-fc** [comment]
@Captainkirkdawson I pushed a small change, when display all image groups, for each group, if its start_date < its source's start_date or its end_date > its source's end_date, the value is marked in RED, so the admin can make choice either source's date or image group's date needs an edit. Please take a look if it helps with Steve's comment on item 2.

**Comment by bev-fc** [comment]
@SteveBiggs 
- No "Create Image Group" button

Currently other server1... is a fake name to allow go deeper, 'create new image group' is taken out from non-image_server sources, because I don't know the structure of other servers, are they going to replicate the same image server structure ie. source->image group->image with same fields or it is going to be different. Once the process definition is finalized, code can be added for other servers.

**Comment by SteveBiggs** [comment]
Thanks Bev, can we create an 'Image Server' source in a place/register that does not already have one or is this done automatically when there are images on the IS?

**Comment by bev-fc** [comment]
@SteveBiggs From code level, it is supported, from process level, if this will create confusion since the code is following changes on IS (at the moment), I am sorry I am not clear with it, how to balance between the process and the code, Kirk would be the best person to answer.

**Comment by Captainkirkdawson** [comment]
Pushed your change @bev-fc  to test2. My reaction was that is very helpful.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs the alternate servers will need a great deal more work once we have one and know more about it. It is in there as a "place holder" so that the basic code is set up to accommodate it .

**Comment by Captainkirkdawson** [comment]
@SteveBiggs @bev-fc at this point the "expectation" was that new image servers would be created by the task that adds new images from the image server when they appear there so had not thought that we would add into the REG app the ability to say that there was going to be something on the Image Server

**Comment by SteveBiggs** [comment]
OK, makes sense thanks.
