### ISSUE TITLE
Image Group - Image Field Relationship

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1285]
We have the same fields (status / difficulty / transcriber and reviewer) in both the Image and the Image Group within which the Image is located. How do these levels work together. 

We have agreed that Images in a group may have different difficulty and that we will allocate  images to transcribers NOT Groups.

We have the ability to set these fields to the same value for selections of images using the propagate action.

So what role do these fields play at the Image Group level?

**Comment by Captainkirkdawson** [comment]
As Ericb has reported in 1277 he had certain expectations that editing the Image Group field would propagate the fields to ALL the Images in the Image Group. 
As currently written it does not do that. 
It has been viewed, by me at least, that they are "Summary" fields and there would be no propagation as this would overwrite what was in the Image fields already.
If so should their content be obtained from the Images and that there should be no edit capability of those fields at the Image Group?

**Comment by Sherlock21** [comment]
Well.. Having eventually worked out the difference between the Individual image and the Group, I think its not totally intuitive as it is at present. 
If only the individual image is used to set details of allocation, and using the Propagate, one can repeat the settings of the one, to many, then is there an Active role for the Group? or just a summary role?

I would ( at this stage) be inclined to ask the view of a CC who is going to use it.

 As kirk says, I had expectations that were different to what this module actually does do. But when I worked it out, I perhaps could make it work if I were to do this allocation task regularly IMHO.

**Comment by Captainkirkdawson** [comment]
I am unsure what you mean by  "if I were to do this allocation task regularly" 

This is not the allocation module we have not yet written that. 

What we have written are the ability to index, show, edit, create and delete at the three model levels of Image Source, Image Groups, and Images.

We needed to get these correct before writing the Allocation or Assinment module as it will use these capabilities that you, EricD and Steve are testing.

Our original data model never had an Image Group level it was something that EricD and Steve requested and its role has yet to be clearly specified. Hence the reason for this story. What is the role of the Image Group in relationship to the Image.

**Comment by Sherlock21** [comment]
Thanks for that clarification. Obviously, everyone else knew this already! 
PS note that I have muse edited my above post, as you were writing yours! Perhaps my last para above is the solution in due course?

**Comment by SteveBiggs** [comment]
I think in general that the fields should be entered at the image level and that the group fields should be auto-populated from the images within it. For example, as transcribers are assigned to images, they get auto-copied at group level.  If the whole group is assigned to one userid, then you use the 'Propagate' and 'select all' button.

When at least one image is assigned, the group Status changes to "in progress". When all images are transcribed,  the group goes to "Transcribed", etc.

The 'Difficulty' field is really more the format of the source, e.g. 'Modern freehand, secretary, latin, etc. so perhaps this one could be set at the group level? However, it is likely that early images will be latin, but change to english later, so even this should be at image level in which case is there even any point having this field at group level (unless it has multiple selections)?

**Comment by Captainkirkdawson** [comment]
Useful comments by Steve and Ericb. Having the fields autopopulate from the Image fields make sense. In which case these fields would be removed from the Image Group edit. We would still have an edit for the remaining fields in Image Group

**Comment by Sherlock21** [comment]
starting on the Images screen that is the landing from MyActions,
it has this header & breadcrumbs:-
![Screen Shot 2017-08-22 at 14.54.52.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/545bc5c91920350200d20f63/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6456f16b7191a379eb0c2e55415a4cbe5d4a1f06a3a3dc78e2a436628f5f5ebe8038567dc23511abea871fbd01ba21881a85b5ea9850d2aa6c7bb3d4d216744b470a83ed5e34aa984ec85bf24ae14f5da01a3160f43b.png)

Usually, one navigates backwards via the breadcrumbs, and starting from the end of the list: the last one is the current page, then every one navigates backwards to that page. BUT here, the one before the end does not navigate to anywhere.
The remainder do go to the correct places.

**Comment by SteveBiggs** [comment]
That is true for Sources with only one Group, but if there are more than one (e.g. Albourne), it goes up to the Image Sources screen.

**Comment by Sherlock21** [comment]
On the individual Images page, can the title be done in BOLD please.

Its the key function of this page but the font is so tweak and tiny, its hard to see - especially when the rest of the key fields as in Bold.
![Screen Shot 2017-08-22 at 15.33.00.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/545bc5c91920350200d20f63/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6456f16b7191a379ea0c2852415f4ebe5d4a1f06a3a3dc78e2a436628f5f5ebe8038567dc23511abea871fbd01ba21881a85b5ea9850d2aa6c7bb3d4d216744b470a83ed5e34aa984ec85bf24ae34b53a412346bf43b.png)

**Comment by Captainkirkdawson** [comment]
Basic conclusion but some thought and discussion required on what we are to achieve.

Requirement is that the status/difficulty/transcriber and reviewer fields of the image groups reflect  a summary of the image in the group. 

The simplest solution is that the image_group field contains a concatenation of the Image fields that are entered.
eg for difficulty if image has some Post_1530_freehand_Secretary, some Post_1530_freehand_Latin and some Damaged. then the image group would show 
Post_1530_freehand_Secretary/ Post_1530_freehand_Latin/ Damaged

eg for status if image has some   UNALLOCATED, some IN_PROGRESS, some TRANSCRIBED then the image group field would show UNALLOCATED/ IN_PROGRESS/ TRANSCRIBED

The transcriber and reviewer fields would have a concatenation of those who were reported in the respective image fields.

**Comment by SteveBiggs** [comment]
Sounds reasonable to me.

**Comment by Sherlock21** [comment]
I too think thats a good solution.

**Comment by richpomfret** [comment]
It looks like a decision is needed here relating to the allocation module. Therefore lets have this paused for now.

**Comment by richpomfret** [comment]
Can now be tested in TEST2.

**Comment by SteveBiggs** [comment]
Tested and working.
