### ISSUE TITLE
Images-Name

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1287]
The title reads "Images of Image Server .... " and should read "Images of Image Group ..." This applies to all sub-pages too.

**Comment by Sherlock21** [comment]
Not so much "ImageName" but is this the screen on which the CC will record who its been allocated to to transcribe?
In which case the only way I can see how to get a Transcriber's name in the field on here, is to do ED and scroll down and put in the person form the pop-up list.
But that seems a long way round, and not at all intuitive.
SO is this another case of "we've not done that screen eat?"'
![Screen Shot 2017-08-22 at 15.07.02.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/545bc5c91920350200d20f63/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6456f16b7191a379ea0c2b56415f4cbe5d4a1f06a3a3dc78e2a436628f5f5ebe8038567dc23511abea871fbd01ba21881a85b5ea9850d2aa6c7bb3d4d216744b470a83ed5c37a19042c259f34be24954a5123563e17e3f6e0a.png)

**Comment by Sherlock21** [comment]
Having done Allocate to TR. and also Transcribed, both by Edit: I ask myself: if this does not need reviewing, how  do I indicate: "THIS Image Complete" and finished with?
And for that matter: whilst some transcribers will need ALL this efforts checked over  (for which:  Reviewed will do) are we implying that ALL transcriptions will need to be reviewed before upload? If not, how will this page keep instep with the reality of the Batches.This page seems to be based on the logic of Everything is controlled by the progress of The Image. is that so?

**Comment by SteveBiggs** [comment]
I think Eric's comments should go into story #210

**Comment by SteveBiggs** [comment]
Comments have been replicated in #210

**Comment by bev-fc** [comment]
@Captainkirkdawson I just pushed the change for 2 comments in this ticket.  (for Eric's comment, I will follow #210 )

1. change heading "Images of Image Server .... " to "Images of Image Group .... "
2. add 'select all' and ctrl+shift for 'move multiple images'

Please take a look if it works as expected, if any change is needed or you see any bug, please let me know.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs these 2 points are now in test2

**Comment by SteveBiggs** [comment]
Both points look good now.
