### ISSUE TITLE
Files rejected as TOO BIG when they appear not to be so

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1288]

**Comment by Captainkirkdawson** [comment]
As far as I can see those files were processed today at around 15:00

**Comment by Captainkirkdawson** [comment]
STSWEIMA was originally a very large file. Today it was split into 5 parts and all were uploaded and processed.
No issue

**Comment by Sherlock21** [comment]
But it was 16:33 BST when I wrote to the CC, and then raised this item. And they were still in the Not Processed set at that time. I did notice a big backlog of not processed files more than a day old.
Just checked now and in Prod, these files are loaded and OK.
Out of interest, is Your time check  your local time, or also BST time - the latter would then make sense.
either way close this now please.
