### ISSUE TITLE
Intermittent FR Site access Problem

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1290]
A number of users are reporting they intermittently can't access the website. I had the same problem this morning with Chrome, but no problem with IE. I cleared Chrome cookies and it worked, but others report that clearing cookies does not fix it.

**Comment by SteveBiggs** [comment]
Here is the error message:
![image](https://user-images.githubusercontent.com/25303607/29714257-44e23d3e-899a-11e7-9513-a1842f154aff.png)

**Comment by Captainkirkdawson** [comment]
Sorry but that is almost impossible to diagnose. Does it happen on initial access to the site, running a search or or; at what time did it happen.

**Comment by SteveBiggs** [comment]
For me it happened on trying to access the site this morning between 9 and 10am. Others seem to  have seen it from time to time since yesterday.

**Comment by PatReynolds** [comment]
Worth checking which server(s) are affected?

**Comment by Captainkirkdawson** [comment]
If I could I would. There have been no software changes in the recent past (10 days)

**Comment by edickens** [comment]
Have just tried to load the FR (not test) first homepage 
![capture](https://user-images.githubusercontent.com/8876165/29739194-bd32e014-8a2f-11e7-8bbe-eddd7243cecf.JPG)
screen.
I can't get in now.  Test2 and Test3 load OK.

**Comment by edickens** [comment]
OK now 07:37
Failed at approximately 07:28.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs @edickens @Sherlock21 Unfortunately it is not possible to determine which of the 5 servers is throwing this error. The standard reporting systems are not showing errors.
What is needed is for any of you who receive this message to click the blue link  "Information for the administrator of this website" that is an inch below the Error Message Block and put that information into the story

**Comment by Captainkirkdawson** [comment]
Have located the problem server as howler. Placed into maintenance mode for FR

**Comment by Captainkirkdawson** [comment]
Problem commenced on August 23 at 23:52 GMT or 16:52 MDT at which time passenger on howler stopped being able to load a configuration file. There is no indication of any file changes with that time stamp and I was on the golf course.

**Comment by Captainkirkdawson** [comment]
(<unknown>): did not find expected key while parsing a block mapping at line 37 column 7 (Psych::SyntaxError)

**Comment by Captainkirkdawson** [comment]
OK located a formatting error in the mongoid.yml deployed on 15 Aug. Unsure why it only became visible on 23 Aug. Guess we  had not done a restart

**Comment by Captainkirkdawson** [comment]
howler has been returned to service
