### ISSUE TITLE
Fine tuning of Image Processing on Test2

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1291]

**Comment by edickens** [comment]
What Bev has done works well and makes us think of where to go next.  But I would like to make sure that what has been done so far is suitable for showing firstly to a few experienced CCs who use the Image Server such as Doreen and Ali, and then to all CCs.  Then make this phase live on the main website.
This will involve some fine tuning such as adding Help pages and Information icons.  Also, all breadcrumbs will need to work.
If you think that this is what we do before going to the Allocation phase, then would you like examples of what we need to do/fix added to this story?

**Comment by Captainkirkdawson** [comment]
I am sorry to say that I would have expected comments about need for information icons and their content as well as "failures" in breadcrumbs to have come out of the current tests. To keep going back to code to add this that and the other is extremely inefficient and will stop the move forward.
I would urge you not involving other CCs UNTIL we have the allocation module. Otherwise they will be trying to do it using the basic tools and complain they cannot do want they want.

**Comment by Sherlock21** [comment]
I have said before that the Breadcrumbs did not work.
And I recall seeing another note from someone about Information Icons being needed. But they might not have been in 1291.

Its a bit hard to not get mixed up between these different topics!

I have also suggested before today, that its time to let a test-savvy CC have a look. 

I would strongly recommend that Kirk's very recent reply to one of my points about spelling out the scope (of The function of the IS)  be told to these Cc testers before asking them to take a look.

**Comment by edickens** [comment]
I have been concentrating on how the system works, rather than tidying up.  I had assumed that Help icons had been omitted for them to be added later because they are your standard.
I will add items to this Story, but feel free to create a new story with them if you think that the work involved warrants one.

**Comment by edickens** [comment]
Should "Manage Images" not be an Action at the top level but be part of "Places"?  I suggest this because there are now two routes to managing the images.
![capture](https://user-images.githubusercontent.com/8876165/29776534-c5801d40-8c00-11e7-9c30-f8b3cfa76ae4.JPG)
When working with Images the logical start is the Place, not the Image.
The Action just needs removing from this level.

**Comment by Captainkirkdawson** [comment]
We need specific information on where and when breadcrumbs do not work

**Comment by Captainkirkdawson** [comment]
Ericd I suggest you look at https://github.com/FreeUKGen/MyopicVicar/issues/1289 where this was being discussed

**Comment by edickens** [comment]
Manage Images brings up "All Sources":-
https://test2.freereg.org.uk/manage_counties/selection?option=Manage%20Images
This has no Breadcrumbs.  It also looks like the All Places list and will in due course be huge.  It needs to have an Alpha selection of the Places.

**Comment by edickens** [comment]
Selecting "Place" in the "All Sources" takes you to the Places Action and out of the Images Action.  Then Selecting Places lists All places with no Alpha selection.  You have to go back to "Your Actions" and start again to get into Images.  The same with "Churches" and "Registers".

**Comment by edickens** [comment]
Then selecting "Sources" to get the next screen:-
https://test2.freereg.org.uk/sources/599626afe937903587d0cc32
"Images Sources" breadcrumb does nothing.
Register Information takes you out of the Images Action.  But Manage Images is there to get you back again.

**Comment by edickens** [comment]
List Image Groups:-
https://test2.freereg.org.uk/image_server_groups/599626afe937903587d0cc32
needs Help Icons.  There is a Red "End Date" (Year?) but I cannot see why:-
![capture](https://user-images.githubusercontent.com/8876165/29777270-5ad74a1a-8c03-11e7-8892-196efbc087ee.JPG)

**Comment by edickens** [comment]
List Images:-
https://test2.freereg.org.uk/image_server_images/599626afe937903587d0ccac
is very useful, but later on we need to think about "Transcriber"(s?) and "Reviewer"(s?)  I would prefer to be able to list the Batches that have been created from these images so as to find errors and get back into the Edit Entries system.
![capture](https://user-images.githubusercontent.com/8876165/29777535-51953c22-8c04-11e7-9818-5999d9a4da5a.JPG)

**Comment by edickens** [comment]
Selecting SH from List Images gives me:-
https://test2.freereg.org.uk/image_server_images/599626afe937903587d0ccac
but does not show me the image, but only its Values.  I think we need a "View", either at this level and/or at "List Images".  I appreciate that Bev has not got the means to access the actual Image Server yet, but this will be needed quite soon.  A button needs to be there which takes you to "Not ready yet."

**Comment by Sherlock21** [comment]
Eric D's comment about adding Manage Images to be listed in Main Actions along with Places,  seems wrong to me - as Images is a stand alone Package to the rest of the FR data is it not?
But I agree with the basis of his comments - its tagged onto the end of other actions, without any clue that one is leaving the historic FR bundle. - At least that's how I am seeing it.

**Comment by Sherlock21** [comment]
On the subject of nipping in and out of Images on a different server, ( as we know it now):
 IS the design intent meant to run seamlessly in the future, too and fro across these boundaries, and the WE, the users, DONT need to know they are different sub=sets? SO having the brad crumbs from the 2 systems all mixed up, does not matter?
We could do with having a heads up at this point please.

**Comment by edickens** [comment]
I think Images is part of the Places Action because "Sources" is listed.  Also, when you go to "Manage Images" then you get a list of Places/Churches/Registers which must have come from the rest of the database.
Eventually images will be integrated with Batches.

**Comment by Sherlock21** [comment]
RE: Eric D's Selecting sources above here 30mins ago, 
I have made that one before and it was answered - Steve relied i think, & said to me: there is NO source for that or something of that nature. but I did not really understand the answer and assumed I had missed a bit  of the lesson.
Breadcrumbs is supposed to be "How I got to where I am now, SO I can go backwards: Well the logic breaks down here does in not?

**Comment by Sherlock21** [comment]
re: Selecting SH from List Images gives me:- by Eric D just above, actually adds nothing to life -as All one gets is exactly the same information as on the table that a one came from. SO it would be better removed, or was ED says:- show the right image.
OR if no image to show, then don't put up the code SH.

**Comment by SteveBiggs** [comment]
I agree with @Captainkirkdawson  that we are not ready to involve CCs yet, unless we can tell them the full details of how the manage images functions will be used, how it will help them and make it crystal clear how far we have got so far (i.e. that they do not yet have the ability to allocate images). It would seem better to wait until the allocation module is complete and we have at least a basic user guide written.

But I also agree with @edickens , that it seems to me more important to get the basic functionality working how we want it to before we worry about the issues of help icons and getting breadcrumbs perfect. As much as we don't want to hear it, there is clearly still some disagreement about this basic functionality. Once we are happy that all the actions are at the appropriate level and we can do the things we need to do, then we can do the tidying up. I don't think we are at that point yet.

**Comment by richpomfret** [comment]
To close (comments captured and work proceeding).
