### ISSUE TITLE
How to Create new Image Source and Image Group when none exist

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1292]
test2.freereg.org.uk/registers:

1.	If a place/church/register has no existing Image Sources, how is one created (e.g. for a non-IS source)? If you click Manage Images, you just get a message “No Source under this register” and cannot create one.

test2.freereg.org.uk/sources:

2.	Once there is at least one Image Source existing, you can create more. Should the “Create new Image Source” action be at the Register level too?
3.	If an Image Source has no existing Image Groups, how is one created? There is no button for it in this case. Only when a source has at least one existing Image Group can you select “List Image Groups” and then on that page:-

test2.freereg.org.uk/image_server_groups:

4.	You now have a button to “Create new Image Group”. Should this action be at the Image Server level?

**Comment by edickens** [comment]
Yes, this is needed.
When the overnight task to find new images is run, then these options are needed because I have been uploading images for places which never had images.

**Comment by SteveBiggs** [comment]
@edickens I was thinking more about the case where the images are NOT on the IS but are held somewhere else so that the overnight task would not find them. These need to be manually created.

**Comment by edickens** [comment]
That is needed too.  It should be the same routines.

**Comment by Sherlock21** [comment]
I had previously written a story that contained this topic of Create the First Image if none are there - its in amongst other coments from way back - doint rememebr the number and I dont have the means  of finding them
EB

**Comment by Captainkirkdawson** [comment]
Has been implement as part of the Image Server module
