### ISSUE TITLE
Recruit WinFREEreg developer

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1293]
Uses win.net

**Comment by richpomfret** [comment]
Richard Light to take a look at the source code.

**Comment by richardofsussex** [comment]
What is my brief in looking at the source code? Intended outcome? Just familiarization?

**Comment by edickens** [comment]
Could you make minor changes to it?  I can advise what is needed.  I had a look but do not know Visual Basic and Mike seems to have used a lot of complicated functions and it interfaces with .netframework.
Eric

**Comment by richardofsussex** [comment]
To be honest my own experience of VB is very limited.  However ... let me know what the issues are, and I will have a look and say what (if anything) I can do to help.

**Comment by edickens** [comment]
Hi Richard,
Mike got WinFreeREG working with FR when it downloaded Place and Church names for selection.  Kirk had set up a special screen with all the information needed.  But as FR developed this screen was changed and Mike never got WinFreeREG to interface with it.  So that needs fixing first because without the list of Places and Churches the rest gives errors when someone starts a new batch.
Eric

**Comment by richpomfret** [comment]
To see if Frank mght be willing to assist here.

**Comment by edickens** [comment]
I see now assigned to me so I will support the programmer.  But Frank who?  Ask him to make contact with me.  E

**Comment by SteveBiggs** [comment]
Eric, in the meeting discussion after you left, Denise seemed to think you knew Frank - that was why you were assigned to make initial contact with him. As you don't, I would suggest that Rich should contact him.

**Comment by edickens** [comment]
I need to look it up, but I think the name came up in a transcribers group message that he knew VB.  I have not had contact.

**Comment by PatReynolds** [comment]
Frank was featured in our news a few weeks back (I thought it was you who'd told me the article mentions he was a VB coder, but seemingly not.  Probably best that @DeniseColbert makes the contact, as she has been talking with him re the news.

**Comment by edickens** [comment]
The problem which is stopping us using WinFreeREG is the link with the server.  It did work until changes were made on the server.  It is the routine which brings down Place and Church names when someone starts a new file.  This ensures that the file will not be rejected when it is upload because of wrong/mispelt Place and Church names.  WinFreeREG uses a special page created to give it access directly to the database.
When this is working, we can see if there is anything else.

**Comment by SteveBiggs** [comment]
Interestingly to some extent the link with the server works. I can log on and fetch Registers Types and Counties, but fetching Places and Churches returns an error.

**Comment by edickens** [comment]
I think Register Type and Countries may be embedded in WinFreeREG because Mike asked me for them.

**Comment by SteveBiggs** [comment]
I am still seeing unhandled exception errors - this one always occurs when I select the "File Details" icon:

![image](https://user-images.githubusercontent.com/25303607/35282670-f5880a2c-004d-11e8-8c36-715ee371390a.png)

**Comment by Captainkirkdawson** [comment]
The last 4  comments should be part of a new story. They have zero to do with recruitment

**Comment by SteveBiggs** [comment]
Kirk, these comments were added because at the last meeting, Rich asked us to list any known outstanding problems with WinFreeREG to help define what would be required of the new developer.

**Comment by richpomfret** [comment]
Currently reevaluating WinFreeReg and tracking down source code for WinReg prior to moving ahead with recruitment and future development. Also need to account for flexible cvs functionality.

**Comment by edickens** [comment]
csv (comma separated variables)
CVS to me is the Council for Voluntary Service !!!!

**Comment by edickens** [comment]
Getting a developer working on WinReg is becoming urgent.  Something has happened in Windows 10 and WinReg does not work with it.  It reduces in size and will not enlarge again.  Transcribers are having to change to Excel.  We have spent years getting them onto WinReg and we don't want to have to do that all over again.

**Comment by SteveBiggs** [comment]
I have a potential candidate for the WinREG developer and am waiting for Rich to get back to see if we have access to the source code yet for him to take a look at.

**Comment by richardofsussex** [comment]
Isn't the code here:
https://github.com/FreeUKGen/WinFreeReg ?
I'm currently trying to get it to compile using the current VB Community edition.

**Comment by Captainkirkdawson** [comment]
@richardofsussex that is the code for WinFreeReg  which is the latest version that was never released. It is significantly different from WinREG.

**Comment by richardofsussex** [comment]
OK, thanks for the clarification.

**Comment by richpomfret** [comment]
Mike F is back so closing. To create specific stories for new changes.
