### ISSUE TITLE
display file size on the DM Actions tab of Show ALL files  and on the CC Actions equivalent

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1295]

**Comment by Sherlock21** [comment]
Many files are being revised by some CC's & Transcribers to update or correct values. IF its a Big File, then they get rejected by the Processor. Some Transcribers try to reload again, with same result. That is a waste of processing effort. CC's would prefer to find their big files and downsize them in an orderly manner so as to avoid  this issue.

Easier solution is for CC and DM to see the file size displayed not he appropriate file listing panel. For the DM profile this would be the Actions/ Physical files/ Files for Specific userid.
For CC's,  it could be: Manage County/ Review Batches by Userid then filename.

So that its easy for the user just to scroll down a big listing rather than having to access each and every single file and navigate to the fuel detail  page that shows the values.

Displaying file size by number of records is easiest for the DM & CC.

**Comment by Captainkirkdawson** [comment]
The number of records is available on the batch listing page I suggest the is adequate enough, Anything over 5000-10000 is likely to be a problem
