### ISSUE TITLE
remove advert from login page

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/MyopicVicar#1297]

**Comment by PatReynolds** [comment]
Many thanks, Vino.  That seems to be working perfectly on test2.  Can you transfer to live, please?

**Comment by Vino-S** [comment]
Sure Pat. The changes are live now

**Comment by PatReynolds** [comment]
@Vino-S  - advert is being shown again - can you urgently remove?

**Comment by Vino-S** [comment]
Hi @PatReynolds ,
I had checked the login page, it is not showing the google advert. I had also verified the code in both freecen and freereg(live websites). Could you please send me a screenshot with url so that I can investigate further?

**Comment by PatReynolds** [comment]
Thanks, @Vino-S - now seems to be fine!
