### ISSUE TITLE
100 year rule compromise

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1300]

**Comment by edickens** [comment]
At the Nottingham conference, listening to the different speakers, it seems to me that we should approach this differently.
The fields in FreeBMD are not covered by the Data Protection act, so they can be shown for more recent entries.  But FreeREG is showing much more detail.
So my suggestion is to amend the researcher results display like this:-
- Only if the viewer is NOT logged in.  (This lets transcribers have access.)
- If the entry date is < today less 100 years
- Only display County, Place, First and Last names, Sex, Entry type, Date.
- Do not allow "Show details".
- In the Church field say "<100 years. Details not permitted by Data Protection Act".
- We will then not show the Church (and hence religion), Abode, Occupation etc.

**Comment by Sherlock21** [comment]
This seems to me to be very much like FMP's way of doing it So presumably they got the legal bit sorted.?

**Comment by Sherlock21** [comment]
But if I am logged on as a CC/SC, I don't need to have  access to the full details of the records for ALL of a County other than my own - which I have anyway as CC.

And as a Transcriber,I have access to all my own records anyway - so how is this proposal of any interest to em.

Giving these 2 groups full Access to ALL of FR, seems to me to NOT be  in  step with  the "Reasonable and Necessary" bit of the Data Protection rules.

**Comment by edickens** [comment]
I'm only suggesting this is for those who do not log in.  That is researchers only.  And I deliberately did it this way so that when we get to V1.7 and researchers can log in for extra Actions, then they can agree to a confidentiality clause and so have access to all details.
You can get all details now by buying a certificate from the GRO for anyone.  But the know who you are.  And when we get researchers to register, we know who they are.

**Comment by PatReynolds** [comment]
?redact data (name)

**Comment by PatReynolds** [comment]
The new privacy notice is now live.
If someone says they are distressed by seeing their data, we will take it down.  If we are given access to transcribe on the condition that a "100 year rule", "75 year rule" "Not until 2030" or similar restriction, we need the capability of taking the records now into the database, but putting a lock on them (i.e. not serving them in response to a search query or as Open data).
The privacy notice will be revised in spring 2018, to reflect the changes of GDPR, but will not affect the coding needed to implement others' "100 year rules".

**Comment by SteveBiggs** [comment]
Pat, when you say the new privacy notice is now live, where can we view it?

**Comment by SteveBiggs** [comment]
I just found reference to it in #1017

**Comment by Sherlock21** [comment]
steve - have you got the wrong link in your last post.?
1017 is nothing to do with the "100 year rule" nor "the privacy policy"

**Comment by SteveBiggs** [comment]
If you open the google doc via the link in #1017 (which I know you averse to), the privacy notice is referred to in there.

**Comment by PatReynolds** [comment]
Privacy notice has replaced the former privacy notice on https://www.freeukgenealogy.org.uk/about/constitution-and-policies/
The most up-to-date version will always be here.
