### ISSUE TITLE
Pay to view

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1303]

**Comment by edickens** [comment]
This is very radical, but came to me at the Nottingham conference.
We just cannot survive if we want to expand and make more rapid progress.  The genealogy world is now driven by money and the Records Offices and Family History Societies are being forced to make financial deals.
But we do not need to go away from our core ethos of being Free and for not selling transcribers work which they have freely contributed.
So what do we do?
I suggest that the Search results show the bare minimum for Free.  A researcher can register for a modest fee, say £50 per annum, which must be less than the other major websites.  Then they can see all the detail.  And they can also have extra facilities that we are planning for V1.7, such as to be able to leave a request to be notified by email if the Place (or name?) in which they are interested has had more data added.
Regrettably, this is the way things are going.

**Comment by Sherlock21** [comment]
Even at the two tier level as suggested here, Its completely against the historical  'contract' with Transcribers.
If you go this way, then you must give everyone who has files in FR, the chance to either accept the proposal, or remove their files. Tagging the non free files so they don't get into the Greater Detail bundle, will be fought with issues and complaints  when the researcher find the First level results of his search has 187 records, but his paid for set only have 3 records in detail.

But if the financial issues are such as to merit such thinking, are there not other ways of reducing overheads?

**Comment by SteveBiggs** [comment]
I have to say that I'm very surprised that you suggest this Eric. It IS moving away from the whole ethos of FreeUKGenealogy and making the access model exactly the same as all the pay sites. Ancestry do more or less what you describe; allow a basic view of names in a free search and you have to subscribe to see the detail of dates and places, etc.

Most transcribers work for us because they believe in the totally free access that we give. I think you would get a massive negative reaction  if we became another pay site.

**Comment by edickens** [comment]
I do agree with you.  But the point the Nick Barratt made yesterday was that the reality of financial pressures are causing all websites and Records Offices to go back on their original purpose.  So yes, I am suggesting that circumstances may force us to follow suit.  But we can make the first search free and without any registration.  We can also have the best search options, and the easiest to use website.  Hopefully we do not need to go this way.

**Comment by Sherlock21** [comment]
I think its useful for someone to look outside the box from time to time - even if everyone then says: NO, stick to the present plan.
