### ISSUE TITLE
Monumental Inscriptions

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1305]

**Comment by edickens** [comment]
At the Nottingham conference, Nick Barratt,  said that promoting genealogy tourism would attract people to our website.  But most of this interest is in finding family graves.  And there are a lot of burial registers which are missing or there are graves which were not recorded.  Many parishes have recorded their graves, so we need to latch into this.  There are two ways:-
- Preferably we need to include their work in our website, and we ought to include the grave number or locations.
- We tell researchers that grave records exist for this Church, but that is not so useful for finding the grave.
Promoting the entry of Monumental Inscriptions should get us more work and more researchers.  Burials are often nowhere near the place stated in the Death record, so a national database needs to be used to find them.

**Comment by PatReynolds** [comment]
See also discussion on #1140.  I agree graveyard recording requires archaeological skills, including surveying, condition reporting and materials recording.   Harold Mytum's Recording and Analysing Graveyards (CBA Practical Handbook) is an excellent reader that shows the scale of what is needed.  It's often done by volunteers, but they are trained, e.g. by a local archaeological society .  So it's not something we could easily add to what we do (and many others are already doing it) BUT the data is in silos.  Sometimes it is not searchable, or only searchable via a paper index.

**Comment by edickens** [comment]
I'm only suggesting that the Name, Church and year are held by FreeREG.  We can then point them to the Church records or website.

**Comment by PatReynolds** [comment]
I am quite happy for the genealogical data to be served via FreeREG

**Comment by Captainkirkdawson** [comment]
As noted in #1140 MI's can now now be added to the burial record . Unless there is a proposal to go and search for sources of this information I suggest it be closed and a new story written for the latter aspect if it is to be pursued
