### ISSUE TITLE
change Location url which Links to Genuki

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1308]

**Comment by Sherlock21** [comment]
Genuki is in the process of changing their system of location referencing from OS  Grid Refs, to use Lat / Lon instead.

SO we need to  be ready to respond with a bulk change of  our LOCATION url.
They may change over by One Region at  time - or they may not. No further information yet.

B:Ut we have the Lat / Lon references already in FR - these being calculated form the OS Grid Ref within our coding. and displayed. So all thats needed it to harvest the County/ Place Name / GeoRefs,  and existing location url, and rewrite  our url with georefs replacing GR, and replace.
Doing the whole job by hand is too daunting and error prone.

They will be moving to a distinct Places gazetteer, sand another distinct Church Location Gazetteer.
Do wish wish to establish geo-referenced locations for our churches as well?

**Comment by richpomfret** [comment]
Needs further discussion.

**Comment by PatReynolds** [comment]
Discuss with Richard Light  (PR and EricB)

**Comment by edickens** [comment]
There is only one link per county in the Refinery, so is a fairly quick edit job.  It might even be just a copy and paste.  I suggest that programming is not needed.  ED

**Comment by Sherlock21** [comment]
indeed it could be a simple set of online keystrokes;
Navigate to the next place name
find & click on Edit Place information
delete existing Location Url
Paste in the new master url and then edit its Lat / Lon components based on reading the Lat/Lon from the rest of the onscreen  information.
Click UPDATE
Come back to the Location screen and click on  the Green Location button and await the new connection activating ( to check you got it right)
navigate back to the County list of places and pick next place name
Repeat loop.

It is not difficult. BUT how many Place names do we have? i would guess some 25,000 at least.
SO its would be a  massive job by hand, one at a time.
I created some 150 places in this manner to make our initial NI collection - it took me 2 weeks partly because of doing other thing at the same time, and partly because of the need to keep records so as not to miss any, nor to duplicate. And there is a danger of RSI too.

**Comment by Sherlock21** [comment]
Eric D

I have to nip out on a taxi job - I will do as soon as I get back - say 30 minutes.

eb

**Comment by SteveBiggs** [comment]
I believe EricB is referring to the Location link in each place:

[image: Inline images 1]

Steve


Stephen Biggs
FreeREG Chairman

**Comment by edickens** [comment]
Yes.  But do we need it and is it ever used?  We have a link at County level through which is easy to get to the Place.  We had this same problem in FR1 and decided to only have the link at County level.  But perhaps it is needed for something else?

**Comment by Sherlock21** [comment]
Hi, Steve - yes you are right - that is exactly what I was referring to. i have sent Eric D fuller instructions of  what I was requesting ( I will copy the mail to you in a moment) 


Eric B

**Comment by Sherlock21** [comment]
As to the question of "Is it ever used" by Eric D, the answer is I don't has access to the stats. So if anyone does, please tell.

If there are no stats on usage, then My answer would be: I expect that absolutely everyone except 4 persons a day will look at the Location map.

**Comment by Sherlock21** [comment]
And if you don't maintain it then you need to provide the resource to remove it as each time anyone who does use it, gets a fail, they will raise a problem report, won't they?

**Comment by Sherlock21** [comment]
If you  create a routine to check which are still functioning, and thus work out which have failed, then how do you propose to rectify these Location ones vie Genuki? - As it is my understanding within a year ( or may be sooner), I they all will be replaced. - which is the purpose of this story in the first place.

Replacing by the Genuki Location ones hand is not an option.

**Comment by Sherlock21** [comment]
Has this one died a death?

**Comment by PatReynolds** [comment]
GENUIK probably have a table that points from the old to new maps.  I'll ask if we can borrow it....

**Comment by PatReynolds** [comment]
They think we can do a global replace (which we can), I've asked how we generate the  urls of the new targets 12/03

**Comment by Sherlock21** [comment]
If Pat is saying: we get the revised urls from Genuki, thats a dangerous route.

NOT all our Placenames are in Genuki in the first place,
And I may not have used exactly the same OS Grid Ref for our place names that Genuki do have. - because I wanted to identify a remote rural church with its real location, not the name of the "Place" that it belongs to, which may well me mile away.

The only real way to do this is I have said before. READ the Lat/Lon value that FR holds, for our Place name, then put that into the url I gave earlier. And replace the present FR linking url with the one just created.

Really basic, and will do all the places regardless of the source.

**Comment by Sherlock21** [comment]
If the users want to replicate what we have had, and got used to, over the past 4 or more years, then my advice is as below. - i.e.: a map showing  the PLACE NAME they are dealing with, PLUS all the churches in the 3 mile radius ( 3 miles can be changed to a greater value if required) in distinctive colours.
IF they want just to link to a Gazetteer of data about a Place, then use Pat's idea. - which data incidentally is available as a secondary, if users use my method. BUT this method will only deal with Places that are in the Genuki Gazetteer that Pat refers to.

Method, for say, Sutton in Sussex as an example.
Take ( from FR's data) the Lat & Lon for the Place name concerned. 
Edit this url by replacing xxx and yyy by the above Lat and Lon values taking care of the sign.
REPLACE the exist ion url with the one created in the line above.
End
move on to next Placename .

EXAMPLE:
Present url is: 
http://www.genuki.org.uk/cgi-bin/gazplace?GR=SU970150,PLACE=SUTTON,CCC=SSX.

Replace this completely with:
http://www.genuki.org.uk/nearby-churches-map/50.92631,-0.6212048,3 

And the job is done. SEE Freereg Production for Sutton, Sussex

THIS method caters for ALL the Place names we have in FR. regardless of the original source - i.e. Genuki and others.

**Comment by SteveBiggs** [comment]
It seems there is no way to get the view we used to have. Eric's suggestion doesn't include the title SUTTON nor a description of the place. An alternative would be the place entry:
http://www.genuki.org.uk/node/60842

This includes a link to churches in the Sutton area amongst other things.

**Comment by Sherlock21** [comment]
Forgive me contradicting, but Sutton does appear on the map view which I see.
Right there between Bignor and Bariavington.

The red blob for Sutton's church: St John the Baptist is where that church is located. - right at one end of the village.  

The link that Steve provided in his comment above does not go to a map showing the location of Sutton - rather  to a map of all the (un named) Parishes of Sussex

**Comment by Sherlock21** [comment]
The version that I have provided in this Sutton example is the best fit that I can devise, to show where the Place is and where the churches are in and around that area.

If you want anything else - you will have to write it from scratch yourselves.

**Comment by PatReynolds** [comment]
EricB's proposal seems good to me - clicking on the church on the map, or moving to list view, gets you more information.

**Comment by Captainkirkdawson** [comment]
Had a look at the story and requirement.
Genuki does a redirect from http://www.genuki.org.uk/cgi-bin/gazplace to http://www.genuki.org.uk/maps/gmap so technically we do not need to change the address part of the url.
The only requirement is to change the , to an & in the remainder.
So for example for Sutton we could change the call to 
 http://www.genuki.org.uk/cgi-bin/gazplace?GR=SU970150&PLACE=SUTTON&CCC=SSX
where the only changes are the , to  &
However we might just as well change the /cgi-bin/gazplace while we are at it.
The code requirement is minimal to do this.
@Sherlock21 @PatReynolds  @SteveBiggs  @richpomfret Do you want me to proceed???

**Comment by SteveBiggs** [comment]
But taking @Sherlock21's point that loses us the information about nearby churches.

**Comment by Captainkirkdawson** [comment]
Totally correct. 

However it has the benefit of retaining the Place Name and we are linking from the place.

Personally I dislike the heading that comes up on the nearby churches page
Churches near 50.92631,-0.6212048,3

For example I far prefer the Cardiff map
![cardiffa.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46eb9588278b85af8eabf301b44fff9e2c4533317346f6787586e22de61b2f595f581ca9415a5f44fdfadc2ba5e02e6c981e5ab38532022d8c6853beb2901eb80bbb25894e85b0b9824bc6e03a22f5c6.JPG)
Than the nearby churches one
![cardiff.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46eb9588278b85afcda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8316b500bf228a4f83b3b58a4fc1e93437aa.JPG)

**Comment by SteveBiggs** [comment]
Yes, shame we can't have the nearby churches map with the title 'CARDIFF'.

**Comment by Sherlock21** [comment]
Having the collection of churches is an essential part of the display on my view.

and you get these in my solution + the Place name - Even if one has to zoom in a bit to get it displayed on the ma

**Comment by Sherlock21** [comment]
Take a look at the Northern Ireland counties that I recently did. All the places have my version of churches + place name ( form the map)
These together with Tadcaster, Sutton (SSX) and a few more I can t remember were done by me by hand, to my proposed method. The NI ones were created from scratch. the English ones by just converting the existing url to get to the present display.

**Comment by Captainkirkdawson** [comment]
I looked at Greencastle Down in NI could not see the name anywhere. Also says its an  obsolete link
![greencastle](https://user-images.githubusercontent.com/2874694/37435963-4180ff68-27ab-11e8-9f7e-519faeacad49.JPG)
I hate Norwich
![norwich](https://user-images.githubusercontent.com/2874694/37435983-615a6004-27ab-11e8-9ce5-96cdb3965928.JPG)

**Comment by Captainkirkdawson** [comment]
Will leave it to others to make a decision.

**Comment by SteveBiggs** [comment]
Looks like all the NI links are obsolete. 

For cities, the nearby churches maps are very cluttered such that you can't see the map properly nor pick out individual churches.

As Kirk says, the link is from the PLACE so should have a title of the place and show where it is on the map relative to surrounding places. If the researcher wants to find nearby churches, they can click on the relevant link on Genuki.

**Comment by Sherlock21** [comment]
If you zoom in enough, Greencastle is there on the map. - a least it was when created this place name. But if its not now, I will relook at these. I used what was supposed to be the new version.

As to a complete mass of churches in some places, zoom in enough to spread them out.

**Comment by Sherlock21** [comment]
In T2, I have tried out Kirk's alternative url that he used for CARDIFF above,to see how it copes with hyphenated place names. and used it on STS/ BARTON-under-NEEDWOOD.
That comes out fine except that My test did not generate the place name in  such a big font. 
I tried it out on a typical 2 word Placename,and it fails - due to the space character - so there needs  to be a workaround here perhaps. [tested on STS/ Biddulph Moor ]

I also tried on one of our Names like: WRY/ WOODHOUSE (SHEFFIELD) and it also will need a different method to cope with these type of names due to the ( ) and space I guess.

**Comment by Sherlock21** [comment]
WRT an earlier complaint that Castlegreen could not be found:
Here is the castle of that name, and the Township is the area around it, down to the coast.

**Comment by SteveBiggs** [comment]
EricB wrote:
"I tried it out on a typical 2 word Placename,and it fails - due to the space character - so there needs to be a workaround here perhaps."
Place names with spaces do work - insert a %20, e.g:
http://www.genuki.org.uk/maps/gmap?GR=SU970150&PLACE=SUTTON%20VILLAGE

![image](https://user-images.githubusercontent.com/25303607/37463843-5831d0a4-284e-11e8-90f8-96374cc77a13.png)

**Comment by SteveBiggs** [comment]
The old URLs were good because the map just had a marker for the church and a list of surrounding churches below the map. I think adding flags on the map for all the churches makes it unwieldy. Users don't want to have to zoom in and hunt for the place that the place link sends them to, they just want it to be there when they click.
If they want to find nearby churches, it is very easy in Genuki - navigate to the county from the top menu:
![untitled](https://user-images.githubusercontent.com/25303607/37464333-e97edb50-284f-11e8-83e9-50ad85643b9c.png)

Click on Sussex Towns and Parishes:
![image](https://user-images.githubusercontent.com/25303607/37464409-2163b5f4-2850-11e8-80f0-70f2ef5b6626.png)

then select Sutton and below the map is a link to Eric's suggested page:
![image](https://user-images.githubusercontent.com/25303607/37464519-7f823a5c-2850-11e8-8325-70e4b005fb22.png)

**Comment by Sherlock21** [comment]
I did have the %20 in my string, just like in the existing. it failed for me.

**Comment by Sherlock21** [comment]
OK, then.. So how about a test run of a three of Counties please?

say WRY and STS, and County Down.

With a csv file listing of before and after County/ Placename/ GR/ Lat/Lon/ old url/ new url/ result when tested by clicking on Location - if that can be managed somehow?

And this is irrespective of whether you show Churches or not, as the location bit will be the same won't it?

**Comment by Captainkirkdawson** [comment]
The format conversion being suggested simply changes the existing http with the new format requirement imposed by Genuki.

They have changed from perl coding to ruby coding which simply requires the , to be replaced with an &
The existing codes all have %20 to indicate a space already.

There are no brackets in the current html they are a part of our internal place name convention.

If the requirement is to simply make the location link work again as it did before then an automatic conversion is quite practical and will take less than a day and will be a pure database update

If the requirement is to change the nature of the link from a place on a genuki map then the story needs to be changed to reflect the new requirement. Such a change will take some time to research after a spec is provided and our links will remain broken until the new code is written, tested and deployed

**Comment by SteveBiggs** [comment]
My suggestion is to make the location link work again as it did before.

**Comment by Captainkirkdawson** [comment]
The location links in NI do not use the place map capability. They use the older version of church locations hence the automatic conversion being proposed would not apply. They would be left as is until we know what their churches 
For example Greencastle is a manor within Kilkeel. It is not a church. There is a node for both Kilkeel and Greencastle. There is no church or register in our database for Greencastle. We have named the church as Birth records. Down also has Kilkeen place entry but no church and a single record (That is the same as the Greencastle entry) with the location going to Kilkeen ugh

**Comment by Sherlock21** [comment]
As you imply, Ni is a totally different naming structure to the rest of the UK. SO Sandra and I cane up with a compromise that enables 2 requirements to be satisfied:
1) Churches that Sandra could identify  with a habitation name,
And 2) These Habitations that I could find on the maps that are available to us.
and that I could locate on a Map.

WRT Greencastle, there is an old derelict church here, for which Sandra is doing the Transcription.
here is all we had to go on for its location:-

**Comment by Sherlock21** [comment]
RE Kirk's last posting above:

The existence of a single record for Greencastle, in the Place name for Kilkeel, was a test for Sandra. Before I found the above map and location for the church in Greencastle itself.
It needs relocating which I will no do.

IF all of the NI records are going to take as much effort as this, we may have to consider the worth of  having them at all perhaps.

**Comment by Sherlock21** [comment]
RE Kirk's last posting above:

The existence of a single record for Greencastle, in the Place name for Kilkeel, was a test for Sandra. Before I found the above map and location for the church in Greencastle itself.
It needs relocating which I will no do.

IF all of the NI records are going to take as much effort as this, we may have to consider the worth of  having them at all perhaps.

**Comment by Sherlock21** [comment]
Now that I have logged on to FR to do the above church relocation, I find in fact they the single record that Kirk refers to was already under DOW/Castlegreen. And not under Kilkeel as claimed. It has been in its right Placename since 4 Feb 2018.

**Comment by Captainkirkdawson** [comment]
Sorry to be difficult but the record shows under Kilkeen as well. 
But we have gone way off topic now
![kilkeen](https://user-images.githubusercontent.com/2874694/37494877-532e6b40-2870-11e8-8515-b8ebe97fd120.JPG)

**Comment by Captainkirkdawson** [comment]
Have run an automatic conversion on test3 and test2. Please review @Sherlock21 . If OK let me know and will run on production
By email I have sent a listing of those approved places without a link.

**Comment by Captainkirkdawson** [comment]
In my opinion it is at least as good as the previous map displays and should be deployed.

However Ericb has new  reservations on the automation that was done. Since I have no further ideas and the currently links are all broken  we might as well get rid of the link and abandon any attempt to give map location

**Comment by Sherlock21** [comment]
But we still need the grid ref or better: the Lat/Lon ref to use in our 'Nearby' calks.

SO whilst we might not have managed to retain the mapping link, the doublets I threw into the discussion following the conversion of T2 and T3, need to be fixed for this reason.
SO before you remove the Location Map link, lets have a think on how to try & recover the position. FR Production Lat/Long data is still good  as it ever was, isn't it even though the link does not go anywhere.So can't we copy the them back over to T2 and T3 (where the place name exists in T2 & T3)? and at least we are back to where we came from.

If I accept that I we are not getting a map with churches at this point, a map to places in Genuki is better than nothing I think. SO I will experiment a bit further if you wish?

**Comment by Sherlock21** [comment]
I have just had a thought on some  of the discrepancies  I noticed in my testing.
GENUKI uses Lat / Lon for locations in NI, rather than OS Grid Refs. SO I had used Only Lat / Lon refs in the rest of the UK for any recent changes and additions. So if Kirk is using GridRefs for the automatic conversion of the Genuki link program, then for theses records, the conversion will not work, will it? 

SOME places in the test areas T2 and T3 had been used to try out the GridRef Free location link, together with my own version of the Linking url to Genuki. So might this have been the cause of some of these non matching 'conversions' that I reported on?

**Comment by Captainkirkdawson** [comment]
test2 and test3 databases are not and never will be the same as production and there are no plans to make them so.
The automatic change proposed was a very simple replacement of an existing grid reference call with a correctly formatted one that now works against their current app. It makes no attempt to change any other type of link that uses lat/lon or nodes.
It makes no attempt to verify the link.
It was proposed as a means of solving the current breakage of our location links.
The discussion on this has consumed an inordinate amount of time and we are no further forward than when we started. I suggest we put this back into the incoming until thereis a clear statement of what we are required to do and a clear statement on what genuki is or is not going to do.

**Comment by SteveBiggs** [comment]
Currently, all the Genuki place links are broken and we are starting to get researcher comments about them. Kirk's automatic URL conversion on test2 has fixed the vast majority of them so that the map is displayed showing where the place and church is.

I would like to go ahead and deploy that to production now. We can look at fixing the NI links and few other anomalies in slower time.

**Comment by Sherlock21** [comment]
If this is the same now as that which I tested in T2 and T3, then OK. But can you provide me with a listing FROM PRODUCTION of  county/ Placename where the final Url is not in the form that Kirks process assumes it is. - i.e. those that fail - I will consider changing them by hand so all are of the same style.

**Comment by Captainkirkdawson** [comment]
That will require additional programming/
It requires a definition of " final url is not of the form that kirks process assumes it is. ie those that fail" 
Nothing fails.

**Comment by Captainkirkdawson** [comment]
The production location links that contained cgi-bin/gazplace were changed to maps/gmap and the ,'s changed to & 
A report shows 9559 places with no location link and 696 with some other form of link which were unchanged.
I have no idea if this is the first or last change to genuki mapping

**Comment by Sherlock21** [comment]
May I have a copy of the report please? i might be able to throw some light on "why", and easily do some by hand. 
And is this the Production version now - begin that the T2 and T3 have already been done?

**Comment by SteveBiggs** [comment]
Copy sent via email.
This is now in production.

**Comment by richpomfret** [comment]
Closing - let's create any separate/new stories if required.

**Comment by PatReynolds** [comment]
I have emailed Genuki 12/4/2017 to thank for their help and ask if they have any plans in this area.  Will create stories if any arise from that.  Added 'Place' label to bring together all issues relating
