### ISSUE TITLE
CC to allocate image_server_group to syndicate

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1309]
The first step in the image allocation process is for the CC to be able to allocate a specific image group to a syndicate.
Need to add an allocation action in the group index and show displays. ALL in list of actions in Index. Allocate to Syndicate as action in list of actions in header of show. Action brings up list of syndicates. Only 1 can be selected. Date assigned generated.
Need to add 3 fields to group. 1) Syndicate field (Syndicate has collection of available syndicates) and 2) Date assigned field. 3) Number of images. These 3 fields should be added to both group index and show displays, The Number of images should be loaded as part of the image server loading/creation process.
Incomplete specification and story is not open for comment it is an internal requirement

**Comment by edickens** [comment]
Hi Kirk,
In FreeREG we don't do this now, but the principle may be needed for the other projects.
Now the SC just asks for an Image Group to be Allocated to one of the transcribers in their Syndicate.
Is the CCs role is to set up the Image Groups ensuring every image is covered and try to get a complete set of images?
Following your suggestion, how will the CC know which image group to allocate to which syndicate?  Transcribers within a Syndicate can work on any county.
Best wishes, Eric

**Comment by SteveBiggs** [comment]
Tested and working.

**Comment by edickens** [comment]
Tested and working, but needs the next stage to see how it will be used.
