### ISSUE TITLE
Draft help materials for elements new to FreeREG

### ISSUE THREAD

**Issue by graphiclunarkid** [FreeUKGen/MyopicVicar#131]
Document new features

**Comment by edickens** [comment]
We never discuss it at the Scrum, but
      is this a documentation story and so should be on...
      https://waffle.io/FreeUKGen/FreeREGNonProductIssues
      EricD
      
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 22/01/2015 16:30, Kirk Dawson wrote:
    
    
      Assigned #131 to @edickens.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Yes

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
