### ISSUE TITLE
"Provide an option for transcribers to decline to have their transcription work acknowledged"

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1310]
Transcribers  able to indicate they do, or do not, want to be creditied, and whether, if they do, they want their real name or their user name, or some other nickname used.  Credit shown on Detail page and 'about' page, if they want shown.

**Comment by edickens** [comment]
We  have recently had transcribers and donors saying that they have not been acknowledged for their work.  But the information is there, it is just many levels down.  I think we need some prompts at a higher level, much like Alison's new Contents for Transcribers' Help.

**Comment by PatReynolds** [comment]
See also #1307 (making access-giver, e.g. record office) more visible on detailed results page

**Comment by edickens** [comment]
I knew that there was another story that I should have added this to, but I tried all the filters I could think of and did not find it.

**Comment by Sherlock21** [comment]
There is also 1267 from myself
and 1289 also.

Cant we run these stories together as they will need all considering in the solution?

**Comment by PatReynolds** [comment]
I have created a new label 'Enhanced credit' to cover everything which is about giving credit (i.e. to the researcher).  1289 uses the same underlying data, but is about providing information to the coordinator.  I think the underlying data is part of the larger GAP/DAP/RAP project, and associated developments (including "the 100 year rule", open data, and persistent URLS.  How best to manage? Another label? Or putting all in the same sub-phase?

**Comment by Captainkirkdawson** [comment]
May I remind you to be careful in the use of "credit" in relation to acknowledging transcribers. The latter is clear and meaningful. We do not use credit in that context. We use credit in the context of acknowledging other people and/or entities who played a role in making the transcription done by the transcriber available,

**Comment by SteveBiggs** [comment]
I agree with Kirk. In the publicly viewable "Transcriptions" tables we list two fields; "Transcribed by" and "Contribution by these people or organizations is acknowledged", so if we are to show these in the individual search detail, they should be kept separately identified.

There is a concern though due to the historic naming of fields in the batch header. WinREG has been used for creating the majority of existing files and in the new files box there are fields named "Source" and "Credit to". Many (including myself) have used the "Source" field to enter the provider of the source images (e.g. West Sussex RO) rather than the "Credit to" field which implies an individual person. This "Source" field becomes  the "First set of comments about the batch" in the Batch information on FR, but is not shown publicly in any view. So we either need to make this visible in the search detail or edit  files to move/copy this information into the "Credit to" field (a huge undertaking).

**Comment by Captainkirkdawson** [comment]
THis story has gone off track, It is reverted to its original purpose.
Transcribers able to indicate they do, or do not, want their name associated with their transcription and whether, if they do, they want their real name or some nickname used. Transcriber is acknowledged on the search record Detail page and in the Transcriptions action.
Default will be showing the users name.

**Comment by Sherlock21** [comment]
In this day & age, I think its risk displaying anyone's userid. - its half way to cracking their account is not it. there are a lot of security topics attaching, and here is not the place to put them in my view.
 Please reconsider this default.

**Comment by Captainkirkdawson** [comment]
Where did it say the default was the userid. It says users name eg Eric Booker

**Comment by PatReynolds** [comment]
The default should be no-show.  This needs to be an opt-in (see [background document]([url]https://docs.google.com/document/d/1XFNnRR7GYGLQkHpRjH30oMtvwT3c6XYj0n4VAz4Rbj0/edit?usp=sharing(url)))

I have changed the title to reflect this.  

What option(s) do we want to give?

**Comment by Captainkirkdawson** [comment]
But over 95% of our transcribers are no longer active and will never change their profiles to opt-in.  Many are dead. Most are uncontactable. This means almost all work will go unacknowledged even though when they were active it was acknowledged.

**Comment by Captainkirkdawson** [comment]
Hence in terms of the default for the field will leave it unset (nil) that way we can make/change our action based on the a 3 way flag. true false nil.

**Comment by Captainkirkdawson** [comment]
Still prefer the other title as this story 
"Provide an option for transcribers to decline having their transcription work Acknowledged"
as it will add a field to the userid_detail and the ability to set/edit and show it
Story #1267 will use that field to display/not display the acknowledgement.

**Comment by Captainkirkdawson** [comment]
Fields have been added that a) Members wish to be identified with their transcriptions ) To be identified with either their name (eg John Smith it is NOT their userid) or a Pseudonym c)enter a  Pseudonym.

Code has been added to the flexible_csv branch to display, edit and create these fields.

**Comment by Captainkirkdawson** [comment]
Have added the action to download a copy of their profile. Part of flexible_csv branch

**Comment by Captainkirkdawson** [comment]
It is possible that the transcriber agreement MAY provide the required consent either by implication or directly. If so we will need to connect the 2 approaches. We will need field b and c  noted 2 comments above irrespective of the transcriber agreement

**Comment by Captainkirkdawson** [comment]
On test2

**Comment by PatReynolds** [comment]
I am checking to see if a does-not-require consent reason could be used (and therefore default could be a "show" option).

**Comment by Captainkirkdawson** [comment]
Pat has advised that our lawyers have advised that we can continue to acknowledge the contribution of transcribers  and credit people without explicit consent; but we need the ability for transcribers to request that their contribution not be acknowledged.
Have modified the title to reflect change in process.

**Comment by Captainkirkdawson** [comment]
Revised code placed in test2.
@Vino-S  @SteveBiggs  I have integrated this code with Vino's code into the edit with some formatting changes. It now looks like
![edit.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46ed909337c0cfeb9ffbb049a15ee4d6730472202c07a22e29dcb770ef1579545f5d4eac405b0a44ffaf9b37b4f46d2ede0356b49b381d66cc2f13acb2831abe08b8258b4f87b5b88f4ed2a5.JPG)

**Comment by Captainkirkdawson** [comment]
Deployed to production

**Comment by SteveBiggs** [comment]
Looks good.
