### ISSUE TITLE
18 Change Transcriptions to Coverage

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1311]
0	3	9	6	18

**Comment by edickens** [comment]
We  have had donors offering their work but we already have it.  People are still not using the "Transcriptions" link to see what we have done.  On the search screen the list of places includes only those with entries.  But there is nothing to suggest that the researcher checks our coverage.  Julie has suggested:-
Would it be an option to have something on the search page where you can request a summary of the coverage of a given place - a drop down box  where you can select to  jump straight to the summary page for that place.

**Comment by PatReynolds** [comment]
@pat_reynolds to add  link from main freeUKgen page on offering images and data

**Comment by PatReynolds** [comment]
Also add to the Contact FAQ.
Update information for Coords - tell potential donors to check transcriptions availability and the free uk genealogy website.
Change 'Transcription to coverage'.

**Comment by richpomfret** [comment]
Will require documentation update.
