### ISSUE TITLE
Enhanced credit/acknowledgement

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1312]
Add details such as Record Office, Church, transcriber, to the Details page.  This covers various stories, inc. #1267, #1307, #1310.

**Comment by richpomfret** [comment]
Adding at the details level rather than documentation level.

**Comment by Sherlock21** [comment]
please also see my latest comment of 5 minutes ago on #1267

**Comment by richpomfret** [comment]
Closing as now covered by other stories.
