### ISSUE TITLE
DM profile has mysteriously changes NO 2.

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1316]

**Comment by Sherlock21** [comment]
on the Profile for DM, the Physical Files/ ACTIONS tab / Waiting to be Processed there should be actions:-

a) Process NOW
b) Remove file  or something similar
c) Destroy new file and all its trail - or something similar

[ I can t remember there may be more actions and different titles! ]

These are Key actions.
 Please file why the profile got changed 
and rectify AASAP

**Comment by Sherlock21** [comment]
Further more I am surprised that there it=s nothing queued awaiting to be processed at they time of the day - 19:55 BST. would you agree?

**Comment by SteveBiggs** [comment]
Fixed in story #1317
