### ISSUE TITLE
CC/SC access to all FR IDs

### ISSUE THREAD

**Issue by suffolkroots** [FreeUKGen/MyopicVicar#1318]
When I go to CC or SC actions/Upload new batch, I am presented with a full ist of FR IDs, not just WRY.

Should this only be available to CC?

**Comment by SteveBiggs** [comment]
Yes all IDs should only apply to the CC action. The SC action should only
present that syndicate's IDs. This appears to be a bug.

**Comment by richpomfret** [comment]
Further testing needed.

**Comment by SteveBiggs** [comment]
The issue is a problem with breadcrumbs. If as SC I select:
'Select Specific Member by Userid'
I only see the userids in my syndicate, but if I then select the breadcrumb:
'Userid Management Options' followed by:
'Select specific userid'
I see ALL userids in the list.

**Comment by Captainkirkdawson** [comment]
Thank you for the clarification

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  @edickens  A fix to the breadcrumbs has been applied, please heck thoroughly as it may have management the manage userid breadcrumbs in the process 
Is available of test3

**Comment by SteveBiggs** [comment]
Select Specific Member by Userid breadcrumbs look good now, but if as CC, I click Select Specific Member by Email Address, choose an email address then click the breadcrumb Select Specific Email, I see ALL userid email addresses. Same thing happens with Select Specific Member by Surname/Forename.

The original issue reported was that when a CC/SC selects Upload New Batch they are presented with a list of ALL userids, not just those for their county/syndicate. This is still the case on test3. Should it be?

**Comment by Sherlock21** [comment]
That feature works the same way for the DM profile.
I don't use it often, but I think that as the Member could be transcribing for ANY County, the way it is configured int he DM profile suits me.
Otherwise, i would have to mess about finding which SC group the person was IN before I could upload in their name.

And in case you ask: why am I even doing such a task. it comes with the role of sorting out the occasional dividing up of big files, or working out why a particular file won't upload. Not an every day task I agree, but when Its needed, I would prefer the present arrangement of ALL userid's in the select list.

**Comment by SteveBiggs** [comment]
Yes, it makes sense for DM (and Sys Admin) to have ALL userids, but the issue here is whether CC/SCs should. It is possible that the transcriber is in a different syndicate, but theoretically it should be their own SC who does their uploading no matter what county the batch is for. Having said that, I have some transcribers who are in other syndicates where I do upload their Sussex files, so it's not a clearcut decision.

**Comment by edickens** [comment]
Without trying to confuse the issue!!!
This is perpetuating the problems from FR1.  Transcribers should upload their own work.  The new system for assigning work allows for images to be managed by any SC.
If a transcriber really cannot upload their own files, and they work for more than one county, then it would be best to create a UserID for each Syndicate.  But this should be the last resort.
Allowing DM and above access to everywhere is a different matter.

**Comment by Sherlock21** [comment]
Steve: I only mention my point above, because I did not want a solution that actually removed the present ALL userid's feature that is in the DM profile

**Comment by SteveBiggs** [comment]
@edickens this has nothing to do with managing images. The issue is simply the fact that right now when a SC uploads a file on behalf of a transcriber, they currently are presented with a list of ALL userids not just the ones for their syndicate. You know as well as I that their are reasons why a few transcribers need their files to be uploaded for them.

In my view, the SC should only see their own syndicate IDs listed, but the CC should see ALL because they need to be able to sort out issues with ANY file in their county regardless of which transcriber originally created it and this may require downloading, fixing and replacing.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  this fix was in response to  your clarification that breadcrumbs were not functioning correctly for a SC in their abilities to manage their syndicate
You are correct in observing that the Display Userids has a different breadcrumb issue. Will look at that.
I will then look at the original issue about uploading

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  have corrected the display Userid breadcrumb for CC and others

The display userid for CC and DM is now limited to basic information only

As fair as I can tell on the upload the SC gets their members the CC and above get the full set which is I believe correct

**Comment by SteveBiggs** [comment]
@Captainkirkdawson have you applied the fixes to test3? The breadcrumbs still do not work as I described above for Selecting userids. Also, as SC I still see all userids when I click Upload New File.

**Comment by Captainkirkdawson** [comment]
Yet again I am confused by "The breadcrumbs still do not work as I described above for Selecting userids"

As far as I am aware it works as you specified. The following are taken from test3

The action you as CC or SC or DM have is Display Userid 

![cc display userid](https://user-images.githubusercontent.com/2874694/41391182-5719aeae-6f56-11e8-8aa7-aa71b2dfb5cc.PNG)

Selecting an option gives the appropriate action with a Breadcrumb back to the previous display

![cc display userid 1](https://user-images.githubusercontent.com/2874694/41386250-c32de72c-6f3d-11e8-9f2b-7559c94a7d4d.PNG)

If you are a CC/DM/SA/VC on upload you get a display of all userids to upload to 

![cc upload](https://user-images.githubusercontent.com/2874694/41391249-b6fb96ac-6f56-11e8-9b0f-80b9441cfc7e.PNG)

The SC on upload gets their syndicate

![sc upload](https://user-images.githubusercontent.com/2874694/41391258-caf75a2e-6f56-11e8-819d-1b2c266e549f.PNG)

This was my understanding of the requirement

**Comment by SteveBiggs** [comment]
Interesting, when I checked yesterday on test3 I saw all userids when I selected Manage Syndicate-> Upload New Batch, but now it only shows the syndicate members as expected, so it's good now thanks!

This is the breadcrumbs problem:
Select Manage Syndicate->Select Specific Member by Userid then select any userid to see:

![image](https://user-images.githubusercontent.com/25303607/41400307-b1e179e4-6fb4-11e8-8b7f-fde92fe74ac1.png)
then click the breadcrumb circled and I see:

![image](https://user-images.githubusercontent.com/25303607/41400368-dbf25280-6fb4-11e8-875b-b258b2e1c782.png)
i.e. a list of ALL userids.

This happens for all of the 'Select Specific ....' buttons.

**Comment by Captainkirkdawson** [comment]
Perhaps the server had not been restarted with the new code. Sometimes I
forget (do that a great deal these days)

TY Now I can investigate

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
@SteveBiggs I hope I fixed the correct issue this time and did not cause a regression. Added to master and deployed on test3

**Comment by Captainkirkdawson** [comment]
I need you to confirm that you are running your test on test3. Because I get a very different response

![capture](https://user-images.githubusercontent.com/2874694/41564326-ad43809a-730f-11e8-9181-319f52066416.PNG)

**Comment by SteveBiggs** [comment]
I am definitely using test3 - just checked again and get the same result.

But could it be that I am logged in as a CC role (steveroland) using Manage Syndicate from there?? (I don't have a SC only account).

**Comment by Captainkirkdawson** [comment]
It is possible that that in combination with your role as a system_administrator is causing the difference between our 2 results. Will investigate further.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs Please see if this tweak helps your unique situation on test3.

**Comment by SteveBiggs** [comment]
No difference. Have you tried logging in as a County Coord and then using Manage Syndicate? As you know, the vast majority of coords have this dual role so login as a CC to do both CC and SC actions.

**Comment by Captainkirkdawson** [comment]
I am totally unable to duplicate what you see.
logging in as traditional CC/SC
![ccsc.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46eb978920c0cfeb9ffbb049a15ee4d6730472202c07a22e29dcb770ef1579545f5d4eac405b0a44ffaf9b37b4f46d2ede0356b49b381d66cc2f10abb2831abd08be22884685b4bf834cd2a5.PNG)
Select Manage Syndicate
![sccs1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fb979930d3c1e5cdf9ad4cae58f3806b1c65267a01a02a75dcba7ce7122c035a5f4cac41595c11fcfadf39baa47e21d40854b088270a36d43703adbf881eba03b324894c8cb3bd8a4ec1fa70.PNG)
Select  by userid
![sccs2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fb979930d0c1e5cdf9ad4cae58f3806b1c65267a01a02a75dcba7ce7122c035a5f4cac41595c11fcfadf39baa47e21d40854b088270a36d43703adb1881eba03b324894b85b7b98e4bc7fa70.PNG)
Functions as it should
Made that userid a system_administrator and removed his syndicate
Manage the Devon syndicate
![sa1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fb95cb61cec1b99de6b546a749b2ce6b1374762a05a67229d1bb78e8402e515d5f4ead420d5f47aaeb9539e4e76224d50152a7842f4d7ed43c19a6b9871db605b824884a8cb6b98d5e8d

**Comment by SteveBiggs** [comment]
I think that much works for me, but if in your last image above you then click the breadcrumb 'Select specific userid', do you still only see the IDs for that syndicate? That's where I am presented with all IDs.

**Comment by Captainkirkdawson** [comment]
Now I understand

**Comment by Captainkirkdawson** [comment]
@SteveBiggs Yet another tweak; this time in a very different area.

**Comment by SteveBiggs** [comment]
That appears to have done the trick - all looks good now, thanks.

**Comment by richpomfret** [comment]
Ready to be deployed.
