### ISSUE TITLE
Revise provision of information on batch headers - all at once glance? (was Changes needed to the documentation of batch headers (was Changing my Profile email address has not changed the my Transcriber email value in some batches))

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1319]

**Comment by Sherlock21** [comment]
I changed my email address some 18 months ago. I changed the email in my  FR Profile. and have confirmed it as the current one at least twice since. BU:T the original email address at virgin.net is still there in some batches for my earlier work.
![still old email.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/545bc5c91920350200d20f63/125516c66e82c728ace21e0d46fb80932f8ec3a683edff46a95cf9986b0a65633b0ba92e7391a172fd1728040c0e1ba5485c5744fbab8c2ba4b63c7189090bee877f4366846c4ff8e7df46f554f832815d84beb68b49c0ee3426e1888a4a3a1f040ac4.jpg)

**Comment by Sherlock21** [comment]
I was in a different syndicate (Norfolk) in the early days if that is significant? Now in WRY. and these seem right.

**Comment by Captainkirkdawson** [comment]
For whomever may have to address this in the future, 
There is no connection between the email stored in a batch (freereg1_csv_file) and the email in the userid_detail. 
The email address in the batch is not used anywhere in the system except to be displayed in the header of the file,. It is only visible to the owner,and coordinators.

**Comment by Sherlock21** [comment]
Ok

But this then begs the question: is the Transcriber therefore supposed to find all their files and reload them  in order to update that email ref on each batch?
or to edit the file header on line if they can?

And thinking further,  is there much use in putting ones email address in the file header any longer?

**Comment by Sherlock21** [comment]
On the Help to Transcribers page, under File Headers, is this:-
![filehdr help](https://user-images.githubusercontent.com/9368704/31093170-c01c892e-a7a8-11e7-871f-252b60be61b6.jpg)

So may I request :  please mark each field that gets Validated against something, with V  and which are MANDATORY with M. So the users know which to fill in with what, at a glance, and to match the list below.
In view of the above reply by Kirk, the help notes appear a little out of date.

**Comment by AlOneill** [comment]
That screenshot is but a small part of the page. The field-by-field descriptions **do** indicate which fields are mandatory, together with explanations of the consequences (trivial or otherwise) of either leaving a field blank or filling it with an unexpected value.

I'm not going to add "at a glance" letters to the s'sheet images for fear of transcribers copying those letters into their own files! But I will review the clarity of the guidance when I'm not so busy ...

The last update to the page was done with Kirk's help, so I believe the information to be correct.

**Comment by Sherlock21** [comment]
Thank you for that input AlOneill

But what's need is what the users want. And an 'all in once glance to check" is the view that is 80% there, just needs this extra bit.

As to the Transcriber copying in the Letter code I suggested is nonsense. No more likely than the Transcriber putting  in the rest of what you have in red oblique text.

**Comment by richpomfret** [comment]
We can explore option of adding this into 'help' - to discuss further.

**Comment by AlOneill** [comment]
On reflection ...
Looking at the requirements, it will not be straightforward to mark the fields without a degree of ambiguity. For instance, most of the fields that are mandatory have a restricted set of acceptable, actual inputs, but one of them (Character set) can be left blank on Windows if the file is saved using the standard Win char set: everyone else needs to specify the char set used. So would this count as M or not?

Of the fields that any user can leave blank, some (e.g. Transcriber's Email, File Name, Syndicate) will be filled for the database — but Transcriber's Name will *not* be filled. Should this difference be made apparent on an "at a glance" illustration?

I will continue to ponder ...

**Comment by Sherlock21** [comment]
I too have had further thoughts after looking at other websites which ask the user to register
 ( and have some fields which are Mandatory and some that are Optional) I have revised my thoughts too. 

Rather than have a code marker of  V or M in every red box, as I suggested above,  we only need to have one marker: * or *:*
And a note in the adjacent body text: say  *  Optional .
And for the Character field could be ** and its text say: Not necessary for Windows generated spreadsheets.

This way would remover the M or O text letters from getting read as part of the field words, AND be more in line with common practice.

**Comment by richpomfret** [comment]
Let's update the documentation to reflect this.

**Comment by SteveBiggs** [comment]
Does this mean #1331 can be closed?

**Comment by PatReynolds** [comment]
For change needed to the documentation of email addresses in batch header, please see #1331, this story now only refers to Eric's proposition above that there is an 'all in one glance' view of mandatory, etc. fields.

**Comment by Sherlock21** [comment]
I see it as One or the Other needs changing.

the basic issue is the header info did not work as I expected it to. - as it was a hangover form F1, and not having been specifically advised the FR was to be different, ( and having asked many time: " where doe the info in each header field go to? , but no definitive reply,"  I had got the wrong idea.

SO if the software is to remain as it is, then the header Examples in the notes need to be revised to identify Mandatory and Not mandatory as described elsewhere.

Then these 2 issues can be closed.

**Comment by AlOneill** [comment]
@Sherlock21 Is this the kind of thing you had in mind? Any comments?

![file-headers-generic-ods-annotated.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ee9d9626cf8bac8eedba51b710f7912743357a2a49ac2f63c8e226b14d6f001b0a1abe5d4a1f06a3a3dc78e2a436628f5f5ebe8038567dc23511abea871fbd01ba21881a85b5ea9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec95df24fe24f56ad103f60f43b.png)

**Comment by Sherlock21** [comment]
AlOneill	
yes exactly so.
One little thing: the first token in the key (! ) which means Mandatory, does not actually appear in the header table below. like all the other keys do.
Now I can work out what it means. But did you intend it to be shown  in each mandatory field?

regards,

**Comment by AlOneill** [comment]
Oops — the symbol was there, but the layer was hidden under the others!

This alternative has *all* the fields annotated, and the symbols are reversed out, to give a little more punch. The final version could have either style of symbol.


![file-headers-generic-ods-annotated-full.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ee9d9626cf8bac8eedba51b710f7912743357a2a49ac2f63c8e226b14d6f001b0a1ab1171d0318eee59b6be4e96625d91819e7c3685c21956c44a5b18617bf06e8258b4d85b6bd8919c0eb6b37fb99cd1e604a5a45d0b50877b29359c950fc4ae44c50a1123561e4753e79448653.png)

**Comment by AlOneill** [comment]
I should've waited a bit (sigh) — the blue is too intense. This is better, I think.


![file-headers-generic-ods-annotated-full.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ee9d9626cf8bac8eedba51b710f7912743357a2a49ac2f63c8e226b14d6f001b0a1ab1171d0318eee59b6be4e96625d91819e7c3685c21956c44a5b18617bf06e8258b4d85b6bd8919c0eb6b37fb99cd1e604a5a45d0b50877b29359c95ffc4ae44c50a1113466e4703e7b478653.png)

**Comment by Sherlock21** [comment]
i am completely content with this version now, Thank you Alison.

**Comment by AlOneill** [comment]
Thank you, @Sherlock21.

Page updated on live site:
https://www.freereg.org.uk/cms/information-for-transcribers/file-headers

@PatReynolds Because I've added an image to this page, I won't be copying the updated page to the not-development test site: I believe it would be counter-productive to do so (because the Refinery image tables would not match), although I could be wrong on that!

**Comment by AlOneill** [comment]
Had further thoughts re the image: removed misleading icon from cell A5. Image is now:

![file-headers-generic-ods-annotated.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ee9d9626cf8bac8eedba51b710f7912743357a2a49ac2f63c8e226b14d6f001b0a1abe5d4a1f06a3a3dc78e2a436628f5f5ebe8038567dc23511abea871fbd01ba21881a85b5ea9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec95df04ce8495ca5113264f43b.png)

**Comment by SteveBiggs** [comment]
I know it's explained above about the 5th line being optional, but would be clearer to create one more symbol to mean 'row is optional' or something similar?

**Comment by Sherlock21** [comment]
If I understand the processing as of now ( rather than when this row header of +LDS  was created in F1 days) it matters not whether one puts it in the file or not. If there is any data in the +LDS field in a row of the uploaded batch file, then the processing uses that data in the Batch row. IF Nothing ( i.e. doc record numbers) is in the  uploaded file row, then the processing does not reject the job - it just puts nothing in the record.

SO Why done we say: OMIT this +LDS from the header all together.

OR have i got it wrong?

**Comment by edickens** [comment]
WinReg counts the number of commas in the entry, and rejects if it is wrong.  So the +LDS tells it to expect two more commas for the File and Image number fields.
But I don't think the server does the same.  It just rejects any extra commas.  It is also happy if the +LDS is there but the extra fields are not.
We are planning to use the +LDS record to describe the columns when we get to the free format input.  So it is best to always put it in as a matter of habit.

**Comment by Sherlock21** [comment]
Thanks for that information.

But in the beginning, LDS actually meant something at the time. As you are suggesting its used for other things in the future, (and indeed is at present where all the doc sources are now not LDS origin), should we change the text int he header to be more realistic. After all, those Transcribers who were there when the source was actually only LDS, are being replaced by new members who don't know that history. - And as we are in the game of removing ambiguity and confusion form the online displays, its very illogical even now.

**Comment by edickens** [comment]
Yes, the name LDS is now not really what it is about.  It just means that File and Image reference fields have been entered.  And this should be done whenever possible so that if a correction has to be made the image can be found easily.  Not just when the images were donated by LDS.  It was LDS that asked for it so that when we gave them the transcriptions they could tie it back to the image, hence the name,

**Comment by AlOneill** [comment]
I am reluctant to label row 5 as "optional" because of its everyday "if you want to" connotation: NQWWW!

How about "required if you have entered Film and Image numbers" ? 
The symbol/colour would take some more thought: maybe dark grey on orange. And maybe no symbol, just the text, "required if ..." — there is plenty of space.

**Comment by Sherlock21** [comment]
i agree with you, Alison.
My comment (2 above) was intended to elicit some management decision on the subject of: do we actually need to make ref to LDS - however its used - when as i though, the code processes the drawing / image numbers whether one puts +LDS here or not.

Or is my memory wrong? do the image numbers get omitted if one does not put +LDS in the header?

**Comment by SteveBiggs** [comment]
Currently +LDS is required by WinREG (used by most transcribers) to create the extra fields of fiche and image number and as EricD says we need to encourage transcribers to add these numbers whenever possible for referencing purposes.

I don't know how the FR website processes the +LDS line, but again as EricD says, there is a future plan to use that header entry to define columns when we implement free format data entry, so perhaps we should actually mark it as mandatory?

**Comment by Sherlock21** [comment]
In that case, Steve,
Yes I agree with your conclusion.

**Comment by AlOneill** [comment]
We cannot mark as 'required' without qualification: that would be disingenuous (i.e. a lie!) and transcribers would either know it's not true or discover the truth and the 'Help' would be discredited.

I cannot remember exactly what Kirk told me would happen if  Film and Image numbers are entered *without* +LDS. @Sherlock21 Would you be up for uploading a couple of test files, both with Film and Image numbers, but one with +LDS and one without?

Surely *future* plans are a red herring as regards how we use line 5 *now*.

**Comment by Sherlock21** [comment]
I created a small test file, which I then used in T3.
Outcome:-
1) the Search results never who the "2 LDS Fields" regardless of whats in the batch.
 2) if there are "LDS " entries in the record being uploaded, then they only get into FR if the file header carries the +LDS marker - and the upload does not crash if the header does not have the " +LDS."
3) if the "+LDS" marker is present, but there are no actual entries in the appropriate fields, then that does not crash the upload.

SO my conclusion is: put the +LDS header marker in there every time out of habit, so that for occasions when you need it, you don't forget to  have it in the Header.

SO for simplicity, call it REQUIRED?

**Comment by AlOneill** [comment]
@Sherlock21 Thank you! You have confirmed that **+LDS is required for files where Film and Image numbers are entered**. Otherwise, it matters not.

It cannot be good practice to *lie* to volunteers, so I'll stick by qualifying the "required". This would be the image:


![file-headers-generic-ods-annotated.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ee9d9626cf8bac8eedba51b710f7912743357a2a49ac2f63c8e226b14d6f001b0a1abe5d4a1f06a3a3dc78e2a436628f5f5ebe8038567dc23511abea871fbd01ba21881a85b5ea9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95dff4ee64a54a7143e62f43b.png)

**Comment by SteveBiggs** [comment]
@AlOneill, no one is suggesting or condoning lying to volunteers. Why not simply say that the +LDS line will be used for other purposes in the future so it would be helpful if it was entered in every file now?

**Comment by Sherlock21** [comment]
My original point was: change the legend from LDS to something more general.

As it is, there is NO logic in putting +LDS if the record refs being used is the Local RO record file numbers, or perhaps the FR Member's own images system. And in these cases, Alison is actually correct: the use of +LDS does imply these Images come from the LDS Organisation, which is NOT CORRECT. - or even its strictly: a Lie.

**Comment by SteveBiggs** [comment]
Yes, we are all agreed that the wording +LDS is historical and now simply means that the two extra fields of fiche and image number are present. And yes, we should change it to something more meaningful when it becomes used for the free format data entry, but we can't do that until everything is implemented to support the change including the FR website update and WinREG is either updated or replaced with WinFreeREG, etc.

**Comment by Sherlock21** [comment]
But for the present time, when Transcribers are having to find their own images, and put those refs into the record, then this title is simply WRONG and misleading, as Alison says.
so change it to "+Image Refs" or just "+Refs" if that makes the coding easier to swap one work for another.

**Comment by SteveBiggs** [comment]
Changing the wording requires coding changes to both WinREG and FR. We currently have no WinREG (or WinFreeREG) developer and have been looking for one for some time (#1293).  If we change it on FR now, we will likely have to change it again when we get to implementing free form entry and with limited developer resource, we don't want to create nugatory work if we can avoid it.

What Alison was objecting to was stating that the line is mandatory when it's not, which is why I suggested caveating it.

**Comment by edickens** [comment]
And don't forget that there are tens of thousands of files in the system with the +LDS entry so everything would still have to allow for this.

**Comment by AlOneill** [comment]
As per scrum decision, updated image on page (live site) to be the final one, suggested 3 days ago.
