### ISSUE TITLE
Write to all CRO and DRO

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1324]
An open letter should be written to all County Record Offices and Diocesan Record Offices to gain access to data, especially parish registers on microfilm / fiche, digital images and out of copyright publications, encouraging collaboration with FreeUKGEN projects.
To cover: permission to use images on Family Search

**Comment by PatReynolds** [comment]
@PatReynolds to write to Coords list with result of communication from John Sheridan. Contact with Diocesan Record Offices now #1015

**Comment by PatReynolds** [comment]
Wrote to coords 8/11/2017

**Comment by PatReynolds** [comment]
Include request for film/fiche no longer wanted

**Comment by SteveBiggs** [comment]
@Captainkirkdawson are you sure you mean #1104? There are two issues with this number and neither are to do with writing to ROs ....

**Comment by SteveBiggs** [comment]
Agreed, thanks.
