### ISSUE TITLE
18 Write to all FHS

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1326]
An open letter should be written to all family history societies, urging greater collaboration across the sector and requesting volunteers to work on transcription with the three projects, highlighting the potential to share data on FHS websites provided it is not commercialised; offer of volunteer support to FHS initiatives in local areas (e.g. at FHS fairs).  If they have completed transcription, can transcribers come and work for us.  Can we make their transcriptions more widely available?  What can we do to promote them / their resources more? 
	AP: Executive Director to draft letter for Trustees approval, and then send to Executive of the Federation 	of Family History Societies for circulation to their membership

Requires #1520
requires #54
Priority (2  3 9 4) 18

**Comment by PatReynolds** [comment]
Wrote to FFHS 3/9/2020

**Comment by PatReynolds** [comment]
Now (27/4/2021) being undertaken as part of the work of the Fundraising Team.

**Comment by edickens** [comment]
I hope  that this brings in some cooperation.  The problem with FHS is that a researcher needs to subscribe to each of them and there is no easy way to search everywhere for someone who may have moved away.
But I don't think we do enough to promote those who have helped us.  For example, when a researcher looks at a the Detail of an entry we must assume that they have found what they are looking for.  If that Entry is also say donated by a FHS then a banner needs to come up to say so and suggest that they contact the FHS for further research.  This also applies to Churches, many of which have their own websites with more information.

**Comment by PatReynolds** [comment]
Joined Federation of FHS

**Comment by PatReynolds** [comment]
FFHS had sent us a form, but we hadn't recieved it - now have it.

**Comment by PatReynolds** [comment]
@DeniseColbert has checked, and we are on the list.

Pat to contact FFHS with 'chanage notification'.

**Comment by DeniseColbert** [comment]
@PatReynoldsFUG did you let FFHS know about your retirement?

**Comment by DeniseColbert** [comment]
Denise to check

**Comment by DeniseColbert** [comment]
Denise to check

**Comment by DeniseColbert** [comment]
Check Pat's correspondence with FFHS re open letter

**Comment by DeniseColbert** [comment]
Done closing
