### ISSUE TITLE
Editing file details offline does not work - update help

### ISSUE THREAD

**Issue by suffolkroots** [FreeUKGen/MyopicVicar#1328]
If file details/header details are changed locally (ie on transcriber's PC) then file replaced, details are not changed on processing.

**Comment by suffolkroots** [comment]
A resolution to this problem would be appreciated as I am in danger of losing a transcriber over their perception of an apparent lack of concern.

**Comment by SteveBiggs** [comment]
I tested this and can confirm it is still a problem. A workaround would be to edit the file details on the FR site, but the issue should be addressed. I have added the Urgent label.

**Comment by Captainkirkdawson** [comment]
Steve

Vino and I had agreed to work together to deploy the fix this afternoon
(GMT). It is not a trivial deployment as master contains the image server
code

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by SteveBiggs** [comment]
OK thanks Kirk.

**Comment by Vino-S** [comment]
Hi @SteveBiggs , The changes have been updated in the live server. Please have a look.

**Comment by Captainkirkdawson** [comment]
I believe what I and Vino were working on had NOTHING to do with this issue. I have never seen the issue. before. Sorry for the mistake, I was just being pushed in too0 many directions at the same time

**Comment by SteveBiggs** [comment]
I don't know how long the problem has been there (this issue was raised last October), but it was working at one time. 
@Vino-S your changes have not fixed it. The file (header) details are still not being updated when they are changed offline and the file replaced. Please have another look. Thanks

**Comment by Captainkirkdawson** [comment]
@SteveBiggs what I and Vino were deploying was the editing of a userid profile. We commented in the wrong story.

**Comment by Captainkirkdawson** [comment]
It would be helpful to know what specific fields are being discussed.

As @SteveBiggs noted these fields can be edited on line

**Comment by SteveBiggs** [comment]
Probably all of them. I've tried editing the transcribers name and comments in both lines and none are accepted on replacement of the file. I will do a test changing every header detail to see if any are accepted ....

**Comment by Captainkirkdawson** [comment]
Personally I would ask myself why we would want to replace them anyway. The on-line edits are much easier. Afterall we have been trying to get away from file driven thinking. 
I think that it is likely better to eliminate all header fields feeding into the database.

**Comment by Captainkirkdawson** [comment]
I have confirmed that NO header field is updated other than date of upload
The header fields can all be updated on line by either the transcriber or the coordinator
I would suggest that it stays that way. Allowing them to be replaced would overwrite any on line edits

**Comment by PatReynolds** [comment]
That sounds good to me, Kirk.

**Comment by richpomfret** [comment]
Let's make a note in the help i.e. these fields can only be updated online. We can then close once done.

**Comment by AlOneill** [comment]
Note added to top of 
https://www.freereg.org.uk/cms/information-for-transcribers/file-headers

**Comment by Sherlock21** [comment]
I support suffolkroots opening complaint.

If its the Transcriber who wants the change,
There re 3 ways to tackle it:
1) edit the file header online - but this needs to get the CC to do it for the transcriber, and then for the Transcriber to download a copy of the then locked file, to use as their future copy in case of further data changes.
OR 2) Transcriber delete the file one day, then (the Transcriber) having edited the header off line, Uploads the new file as a NEW batch on the next day. NOT straight away, was there are other things that have to tidy up in programs that don't run immediately so i understand.

OR 3) revise the software to check the header as well as the data, each time a revised version of the batch is uploaded.

**Comment by SteveBiggs** [comment]
The Transcriber can edit the header of their own files online. They don't need the CC to do it for them.

**Comment by richpomfret** [comment]
In which case let's close this task.
