### ISSUE TITLE
Changing my Profile email address has not changed the my Transcriber email value in some batches (was #1319)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1331]
Documentation needs to explain that the email address in a batch header is a feature that was needed in FR1 (when we did not have user IDs).  Now we have user IDs, it does not matter what is in this field.

**Comment by richpomfret** [comment]
Updating documentation to reflect this.

**Comment by Captainkirkdawson** [comment]
The text has been updated 
Cell 1B is the email address of the transcriber: it is not made public and is accessible only to coordinators, for information. You may leave it empty, in which case the database field is filled from the Profile (please note that this will not be updated if you change the email address in your Profile)
