### ISSUE TITLE
Create CSV files for RO that provided source images

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1332]
West Sussex RO provided us their entire set of LDS images on the agreement that we give them copies of the transcriptions we make from them. An efficient way to do this would be to write a rake task that extracts the userid/filenames for a register and then copy and merge the original CSV files into 3 files; one each for ba, bu and ma.

**Comment by edickens** [comment]
Or a system whereby the RO can have access to the CSV of selected Registers and then they can download them themselves.  This will avoid a lot of passing of files.  Do you know how they want to organise them on their computers?
I had the same request from SOM when I was CC.   Very quickly they did not want the CSV but just appointed FreeREG as a research resource for their staff and they look up what they need.
But access to look into a file in more detail in case of a query could be useful to them.  It all depends on what they want the CSV for.

**Comment by SteveBiggs** [comment]
This can be put on the backburner. WSRO are considering how they would like the data and do not need anything for some time yet.
