### ISSUE TITLE
SC to assign images to transcriber/reviewer

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1333]
1. Add a Manage Images Action to the SC Actions. 
That action generates an an index display with heading Image Groups Allocated to Syndicate eg Image Groups Allocated to Surrey and Sussex - Steve Biggs
2. The display will be identical to the "Image Groups Allocated by Place"  for a CC but the content will only be those places that have groups assigned to the syndicate
3.The breadcrumb will go back to Your Actions: › Syndicate Options(Surrey and Sussex - Steve Biggs) > All Image Groups Allocated
4. The image group and image displays will got bacK to that chain
5. Required actions are shown in https://docs.google.com/spreadsheets/d/1cz6pOwIEv-vsLYdtc6e1MifvcX0eOaoEqOXGL2wy8PQ/edit#gid=1054387997

**Comment by Captainkirkdawson** [comment]
Basic testing has been done on cloud9.
Next step deploy to test2.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs has tested and requested changes; in progress

**Comment by Captainkirkdawson** [comment]
Code rewritten and deployed to test2

**Comment by richpomfret** [comment]
Suitable for wider testing.

**Comment by SteveBiggs** [comment]
Has been in test by 4 coordinators for some weeks. No problems reported so far.

**Comment by richpomfret** [comment]
@Captainkirkdawson Should Steve/wider testing be done on Test3 rather than 2?
