### ISSUE TITLE
Transcriber can list assignments

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1334]
1.Add a new Action for the transcriber and all other roles (all roles have batches, profile and roadmap) Called Manage Assignments.

2.That action displays all assignments for the userid_detail. Can use the same display as provided to the SC

3.There should be 2 header level Actions. 1) List Available Groups for my syndicate (Essentially the same as what the SC gets) 2) List Available Groups for a County. (Have transcriber select the county prior to display). The purpose of these is for the transcriber to be able to look at what work they might be able to request from their SC. Suspect we will add an action that permits the userid to send a message to their SC requesting that they be assigned the group in question. Available means 1) Those groups that are allocated to the syndicate. 2) Those groups that are Unallocated.

4.In the List of images there should be no header actions. The first row has 3 actions, VW,DL,COM. The rest have 2 VW,DL.

5. The actions VW is for view of the image. Just do a simple display of a message in the action at this time I am working on the code to link with the image server.

6.The action DL is for download of the image.  Just do a simple display of a message in the action at this time I am working on the code to link with the image server.

7.Use view and download as controller methods in imageserverimages

We will add more code for these shortly

8. The Action COM is for Complete. It is to send an email from the userid to the SC saying that the assignment (and what it is) is now complete.

**Comment by Captainkirkdawson** [comment]
Code written and under testing

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  has tested and requested changes

**Comment by Captainkirkdawson** [comment]
Rewrite of the assignment code is nearly complete. Estimate release for testing  prior to Christmas.

**Comment by Captainkirkdawson** [comment]
Code rewritten and deployed to test2

**Comment by SteveBiggs** [comment]
Requested changes tested and accepted.
