### ISSUE TITLE
Transcribers and other can view and download images

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1335]
Add the ability to view or download an image on the Image Server through the main application.

**Comment by Captainkirkdawson** [comment]
1. Lemon has installed ruby on langur and provided a basic url for communications with the server
2. Have written a skinny rails app that interfaces with the Freereg image storage system.
3. Have written code for FR2 to view and/or download an image file from a specified assignment/allocation/source. Tested and working in the cloud9 environment.
4. Working on the capability for the system administrator to list folders and images on the image server.
Yet to do provide the ability to create folders on the image server that are linked to FR2.
Integrate the code with the allocation/assignment code being written  by Bev as part of #1334

**Comment by edickens** [comment]
Brilliant.  Cheers EricD

**Comment by Captainkirkdawson** [comment]
Integrated process now completed. Leave as in progress

**Comment by Captainkirkdawson** [comment]
Need to add the ability for a system administrator/data manager to delete an image from the server,
Need to add the ability for a CC to list and remove? physical images for their county on the server

**Comment by Sherlock21** [comment]
Yes, Kirk
I agree with you. Cc's should be able to do everything to their own county images in my view.
including all the Open or Closed flagging too if theta where they are.

**Comment by SteveBiggs** [comment]
I believe that deleting images from the IS should be a Sys_Admin / DM only action. The only reason for deleting should be that the original provider of the image changes their mind about permission for FR to transcribe from it. If that happens, the CC should discuss with management first to see why this is and if anything can be done about it before going ahead and deleting images.

**Comment by Captainkirkdawson** [comment]
Remove feature will be required during testing phase.

Have added CC access to their county images but no removal

Have added ability for SA/DM to remove

Deployed to test2

**Comment by Sherlock21** [comment]
Unless there is a means in this application for correcting a wrongly labelled image,  or the wrong image was put up by the CC in the first place, then the CC should be able to delete if for no other reason than to make such corrections.

If the reason for not letting CC's delte their County images if necessary brings into question the whole matter of the CC's credibility to do the job at all in my view.

**Comment by SteveBiggs** [comment]
View and downloading of images tested and accepted.
