### ISSUE TITLE
Errors accessing getscan.pl - to update documentation/text

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1338]

**Comment by edickens** [comment]
These last few days I have had people contact me with a number of different errors about not being able to access the images server.
Some think they can access it through the website and are looking for links.  Some are too quick to try to access it when their details have not been passed across overnight.  Some have problems accessing then change their password but that will not work until the next day, but they do not know that so change their password again.
Please, as soon as we can, may we access the images from within the website, using getscan if necessary.  It is the fact that it is stand alone and in FR1 style that is causing confusion.  At least accessing from within the website we can embed the correct link and tell them that any UserID or password changes will not take effect until the next day.  It just needs to be in the Transcribers's Help.
EricD

**Comment by SteveBiggs** [comment]
This is in work (#1335) as part of the Manage Images project underway by Kirk and Bev. The SC will assign a batch of images to a transcriber who will then be able to list what is assigned to them and download the images for transcription.

**Comment by richpomfret** [comment]
In the meantime, shall we update the help documentation as discussed?

**Comment by richpomfret** [comment]
Eric to write and then send to Alison to update.

**Comment by edickens** [comment]
This is all that there is at present.
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8317b500bf218b4f80b0bc8948c3e83c37aa.JPG)
and it comes under a section that is not obvious.  It took me a while to find it.
Should we have a section in Transcribers' Help for "Viewing images for transcribing"?  If so I will write something.
The getscan link here is correct and works.
EricD

**Comment by AlOneill** [comment]
Done. See https://www.freereg.org.uk/cms/information-for-transcribers#accessData
