### ISSUE TITLE
Birth date with no Baptism date showing up as 0 year in some files

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1340]
Some (but not all) files that have entries with a Birth date and no Baptism date are flagging up as a zero (0) year for the file. This affects at least two files in Sussex: SSXCUCBA & SSXBOLBA1.

**Comment by Sherlock21** [comment]
Have you removed the offending file please?
I cannot find it in T3.

I did see lots of others Zero Dates flagged. - one I looked at was because there is a row at the end of the file that has some values in, but no dates

e.g. row 371 in Mike Bennett's SSXSOBMA.

**Comment by SteveBiggs** [comment]
Eric, have a look in file SSXBOLBA1 by Mike_Bennett:
![Capture.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588631f51e19621a00230146/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8318b500bf218b4c80b6bf8949c3ec3e37aa.jpg)
click on 'Zero Start Year Entries' and you will see the results.

**Comment by Sherlock21** [comment]
Odd things are going on here.

IF I start with your way above and find the file SSXBOLBA1 by Mik_Bennett, then chose the first record in the list of error rows ( record 548) and go to open access to it as if to edit the error, but actually don't do anything except scroll down to the bottom of the view, pausing at the BAPTISM date field with the cursor in that data box to see if it was a blank space char ( which it was not). Then backing out with the breadcrumbs having done nothing except look,  I got the messed: record updated and locked etc.!

Then back at the start screen,I got the next surprise message below. WHY?

IF I start from my usual place - ALL files, and navigate via physical files / Files for specific userid /Mike_Bennett/ All files. then find the one we are interested in. this file is there, but I cannot NOW download it - msg says: there is a problem with the file you are attempting to download. - when I tried this earlier in the day, I did download it OK - but could not find the error row 548.
A mystery.

![surprise2](https://user-images.githubusercontent.com/9368704/32691858-211eb4dc-c706-11e7-9d6c-e8d4a8b6a295.jpg)

**Comment by SteveBiggs** [comment]
Yes there appears to be an error with the breadcrumbs. If you go into SH or ED for an entry in the list of zero dates and click on breadcrumb 'List of Records' it sends you to this error.

It would appear that record 548 has been deleted. The first in the list is now 550.

**Comment by Sherlock21** [comment]
The main point in my post 2 above there, is that it appears to be the case that if one approaches from 2 different routes, one appears to get 2 different conditions for the same batch.

 Please put this into  new issue if you wish.

And  split out likewise the Breadcrumbs topic. > leaving this topic solely for the issue of  the Mystery zero dates.
 Please can anyone identity what is the real cause of the Zero Dates records in Mike_Bennett's batch?

**Comment by richpomfret** [comment]
No longer an issue relating this specific task on production. However, looks like there could be a separate story here - Steve to explore.

**Comment by SteveBiggs** [comment]
Have opened #1345 with breadcrumb issues.

**Comment by SteveBiggs** [comment]
I've found another case where a birth date with no baptism date is flagged as a zero start year. The file is in Surrey - SRYCAPBA (on production website):
![Capture.GIF](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588631f51e19621a00230146/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8316b500bf218a4d84beba8d4dc9e13537aa.GIF)

**Comment by SteveBiggs** [comment]
However! I just clicked back to 'List of Records' and the file is no longer showing as Zero Years! Something very strange if happening here .....

**Comment by Sherlock21** [comment]
I am please to see that someone else can replicate this strange happening.
I was beginning to think that it was me doing the wrong thing!

**Comment by Captainkirkdawson** [comment]
We have over the years changed the way baptism/ birth dates and the year of a record are computed as well as what will be entered into the search record. When we have made code changes we do not go back and reprocess the old files. Those code changes will only apply when a file is reprocessed . Hene you may well find old files that do not reflect today's expectations. Some changes will be applied ONLY by a reprocessing of the file. Others may be applied when 1 record is edited on line. Others that are summary indicators may be applied by the act of examining the file.

**Comment by SteveBiggs** [comment]
Thank you Kirk. I think that completely explains what I've been experiencing.
