### ISSUE TITLE
Getscan FR compatability

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1341]

**Comment by edickens** [comment]
Michael and I have come across a problem in STS.  I have made the place names on the image server match the FR places.  But getscan does not like any place name with a &, or (, or ).  I have left them compatible with the FR places, but it means that until V1.5 is live, I have problems allocating images for these places.  Michael can also not look at these images.  getscan produces a file error report.

**Comment by edickens** [comment]
I should have said that it is the Church names which are the problem.  The Image Server has the Place and often the Church name in the file folder's name.

**Comment by PatReynolds** [comment]
How big is the file?  A possible solution is to create a folder on the gdrive to hold a copy of the images, which Michael can use until V1.5 is live.  But there is a max 13gb on this.

**Comment by edickens** [comment]
Michael has copies of the images and we can get around it.  Also, most of STS has been transcribed.  I'm just flagging up a problem and that we need to get off getscan as soon as possible.

**Comment by Captainkirkdawson** [comment]
It would be interesting to know which specific folder/file names were causing a problem to see if we can access them through the new system

**Comment by edickens** [comment]
Hi Kirk,
I've been away for a few days but am back now to sort out my many emails.
It is the folders that are the problem now.  I have sorted out all the files.
The first one here in STS is a problem having an &.  The CC cannot get past it with getscan to see the files.
![image](https://user-images.githubusercontent.com/8876165/33006749-7dc3792a-cdc3-11e7-98be-63fbc3e65857.png)
Eric

**Comment by SteveBiggs** [comment]
Eric,
Why does it use an '&'? All such church names on FreeREG use the word 'and', so would the answer be to change all '&'s to 'and's?

**Comment by edickens** [comment]
These are Place names and match how they are set up in FR.  The Church names are OK.  E

**Comment by SteveBiggs** [comment]
In your example, the place is Adbaston and the church is St Michael & All Angels (St Michael and All Angels on FR):
![image](https://user-images.githubusercontent.com/25303607/33020516-9902b808-cdf6-11e7-9f0d-243e6038bfa9.png)

**Comment by edickens** [comment]
Of course, it comes after an underscore so is a Church name.
![capture](https://user-images.githubusercontent.com/8876165/33022883-733b7de6-cdfe-11e7-8c35-5c08c810dc6b.JPG)
I have corrected the Image Server.
But there are also brackets which give problems:-
![image](https://user-images.githubusercontent.com/8876165/33022925-9084f24c-cdfe-11e7-874f-d3842dad4768.png)
and this does match FR.
E

**Comment by Sherlock21** [comment]
The brackets in an FR Place name come from the need to distinguish between multiple occurrences of a Place name within the one County. They have been there since the beginning of FR. - as explained in another similar query.
I consider they are not changeable just to fix an issue with GetScan

**Comment by SteveBiggs** [comment]
Something must have changed recently on getscan because you allocated Woodmancote (Henfield) to some of my transcribers in 2016 and they downloaded the images with no problems. However, as you say they now give an error and can no longer be downloaded.

**Comment by edickens** [comment]
I'm hoping that we will not be using getscan for mush longer!  E

**Comment by richpomfret** [comment]
To close (no longer applicable).
