### ISSUE TITLE
Unique Names update to reflect user feedback

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1342]
A number of coordinators have requested the ability to obtain list of unique surname/forenames in files. This should enable them to spot then subsequently correct incorrectly transcribed names

**Comment by Captainkirkdawson** [comment]
Unique Names option added to actions on display of a file

**Comment by richpomfret** [comment]
@SteveBiggs to review and feedback on.

**Comment by SteveBiggs** [comment]
The action works to list all forenames and surnames in a given file. So you can easily see if there is a gender issue (e.g Mother's name Thomas) or if a spelling looks wrong compared to similar names. You can then browse the file and quickly locate the name in question and edit as required.

**Comment by PatReynolds** [comment]
Potential for this to be a Summer of Code project -  @benwbrum is this issue all the information you need for story #41 on NewProjects?

**Comment by Captainkirkdawson** [comment]
This is currently only  available on test2 in a bev development branch. It would not move to production for some time. Do you want it added into master earlier?

**Comment by PatReynolds** [comment]
Summer of Code won't start until June at the earliest. I'll leave it to @benwbrum to comment on where it needs to be by then

**Comment by Captainkirkdawson** [comment]
The code was not aimed at any other project. It was developed in response to a desire from the current suite of transcribers, and coordinators for a means of them checking a file  after it was uploaded. It would  essentially correct the record at the point of entry rather than maybe at sometime in the future. It does nothing for the 40000 existing files.

**Comment by PatReynolds** [comment]
Thanks - that means this isn't the story about resolving the gender issue ... I'll find (or create that).

**Comment by benwbrum** [comment]
New story is tracked in #1362.

**Comment by richpomfret** [comment]
@Captainkirkdawson Can I ask why this would not be moved into production for some time, as you mention above?

**Comment by Captainkirkdawson** [comment]
As part of the bevbranch it would not go into production until we merged that branch into master which is likely to be March.
The could be extracted and applied to master earlier if that were required

**Comment by NirmalKumarJoshi** [comment]
Hey, I want to work on this issue and come up with better results.

**Comment by Captainkirkdawson** [comment]
@NirmalKumarJoshi the story is closed. However we would be interested in hearing what you might be proposing bearing in mind the specification of the story

**Comment by Captainkirkdawson** [comment]
@AlOneill we need to adjust the help Information for Transcribers for this action its now available on all servers

**Comment by SteveBiggs** [comment]
Reopened because a suggestion has come in:
Could certain very common names be excluded from the list since there is no value in having for example, John, James, Henry .... as these would not flag up as a potential mistranscriptions? This would reduce the size of the list of names making it easier to focus on likely problem names.

**Comment by Captainkirkdawson** [comment]
Issue reported by STSCoord at 2018-02-27 10:42:48 UTC
Time: 2018-02-27T09:48:47+00:00
Session ID: cc81637eabe9491af675ca023709ffdb
Problem Page URL: /freereg1_csv_files/unique_names?object=59ded296f493fd76c068f12c
Previous Page URL: https://www.freereg.org.uk/freereg1_csv_files/59ded296f493fd76c068f12c
Reported Issue:
The text of the names is very light in comparison to the background and so it is not easily visible.

Would it also be possible to highlight the name headings by using bold or underlines?

A scrolling facility would be useful to work through the names.

Thought needs to be given to the possibility of a full marriage file (400 entries) with bride/groom/brides father/grooms father/witness 1/witness 2. Potentially 400 (entries) x 6 (named persons) x 2 (forename/surname) need to be scrolled through. This scenario is almost unworkable as the system currently stands.

What about correct
punctuation? It should NOT be "Brides Name" but "Bride's Name" etc. "Brides" means "more than one bride", "Bride's" means "belonging to the bride"

Another useful report would be a comparison of the surname of the bride and groom with the surname of their father. Sometimes there are spelling differences in original registers but, theoretically, those differences should be picked up by the Transcriber and noted.

**Comment by Captainkirkdawson** [comment]
I think it is important to include all names as  I think one does need to know that one of the entries is possibly a mismatch. Without that one would never know.

**Comment by Captainkirkdawson** [comment]
Will deal with formatting changes as part of this story.
But request for a new type of report will be put into a new story.

**Comment by Captainkirkdawson** [comment]
Newly formatted and deployed to test2

**Comment by SteveBiggs** [comment]
Format is much improved making the names easier to read.

**Comment by SteveBiggs** [comment]
@Captainkirkdawson wrote:
"I think it is important to include all names as I think one does need to know that one of the entries is possibly a mismatch. Without that one would never know."

That may be true for surnames, but users won't be trying to match forenames. They will likely scan the list for a name that looks wrong, e.g. if they see 'Janes', it looks unusual so could be James (if male) or Jane/Janet (if female) so they would go and check the image. If it says 'James', they would have no reason to suspect a problem.

**Comment by Captainkirkdawson** [comment]
I guess my fundamental problem is that it is either unique names or something else and what that something else  might be called is totally unclear. It certainly would not be called Unique Names

As you say it would apply to only to forenames,

However the number of forenames is much much smaller anyway so is there any real value in doing something? A quick scan of forenames is all that is needed.

**Comment by Captainkirkdawson** [comment]
Deployed to production

**Comment by SteveBiggs** [comment]
This can be closed
