### ISSUE TITLE
[production][freereg_contents#index] NoMethodError: undefined method `county_coordinator' for nil:NilClass

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1343]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/562a65f7e93790333a00002f/problems/59b015bce93790509f000000)
# NoMethodError: undefined method `county_coordinator&#39; for nil:NilClass #

**Comment by Captainkirkdawson** [comment]
There have been 20+ system crashes from this in the past week on all servers. There have been a further 20+ earlier.
The problem is caused by the inclusion of Northern Ireland in the drop down list of counties within Northern Ireland. Similar crashes were encountered with England, Scotland and Wales when we first wrote the system
The solution is straight forward. Add Northern Ireland to the exclusions list in https://github.com/FreeUKGen/MyopicVicar/blob/master/lib/freereg_options_constants.rb#L4

**Comment by richpomfret** [comment]
Thanks Kirk. Vino will take a look.

**Comment by Captainkirkdawson** [comment]
Continues to happen on a regular basis. Why is this not fixed?

**Comment by Vino-S** [comment]
Fixed and pushed to live
