### ISSUE TITLE
Creation of a new Church appears to be causing rejection of file uploaded to the place/church

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1344]

**Comment by Sherlock21** [comment]
Following complaints by Michael Clarke & Doreen Olds that a file they each tried to uploaded to Production ( for BKM  / Walton ( Milton Keynes) / St Michael) that the uploaded file got rejected on upload, I created the same Church name in to the existing Place name in  T3 and used the same  datafile as they had used  ( except for changing the Char set code from windows to UTF-8 to suite my Computer) . Then tried to upload that file.

it was rejected with this error msg:-

"Eric,

The file submitted for processing has been completed. Please review the following report.

Started on the file BKMWALBA1.csv for ericb at 2017-11-17 16:05:20 +0000.
The place name at field Walton (Milton Keynes) is invalid at line 1. 
The church name St Michael is not in the database for Walton (Milton Keynes) at line 1. 
The place name at field Walton (Milton Keynes) is invalid at line 2. 
The church name St Michael is not in the database for Walton (Milton Keynes) at line 2. "

- etc for all of the 298 records in the file)
Now: - history
This Place name has existed since day 1.

The church name had just been created  in Production by Michael to use and  just  now by myself in T3 for this test.
There is no issue with that Pacename  nor the church so far as I can see,

SO: what has changed please that is affecting this routine activity?

**Comment by Captainkirkdawson** [comment]
Nothing has been changed in months

**Comment by Sherlock21** [comment]
OK, thanks.

Is the Register type of OT  not approved then please? and so that's the issue?

**Comment by Sherlock21** [comment]
I think that I may have found the problem

there is a double space between the Place name Walton and the opening bracket of (Milton Keynes) so I have fixed that, and testing upload again (in t3)

**Comment by Sherlock21** [comment]
Solution tested and worked OK

SO please close this.

**Comment by SteveBiggs** [comment]
Closed.

Steve


Stephen Biggs
FreeREG Chairman
