### ISSUE TITLE
Zero years breadcrumbs issues

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1345]

**Comment by SteveBiggs** [comment]
As discussed in the pre-sprint meeting, here are the issues I've seen with breadcrumbs using the new Zero Years implementation Vino has done.
Listing files in Surrey by filename, the first two with zero years are in Banstead:
![breadcrumb0.GIF](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588631f51e19621a00230146/125516c66e82c728ace21e0d46ea869f228680bb9ae4bd13e611b2843b492d762a10e17132d0b02dbc437e58565b46ac460a5a44fef9892aa5e33c73dc4e17ff933c0120996048e6edc00db513bb29814e80b7bd884cc5e93b25e0898e5d73.GIF)

I selected Zero Years for file SRYBANBU, then clicked 'Batch Information' followed by 'Listing of zero years entries' and the place / church / register are not showing:
![breadcrumb1.GIF](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588631f51e19621a00230146/125516c66e82c728ace21e0d46ea869f228680bb9ae4bd12e611b2843b492d762a10e17132d0b02dbc437e58565b46ac460a5a44fef9892aa5e33c73dc4e17ff933c0120996048e6edc00db513bb27814e80b7bd884cc5ec382de28e865d73.GIF)

I then clicked SH followed by 'List of Records' and correctly see the records for that file.

Now I click 'List of Batches' then select Zero Years for file SRYBANMA, then click SH followed by  'List of Records' and the display lists the previous file SRYBANBU rather than this one:
![breadcrumb3.GIF](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588631f51e19621a00230146/125516c66e82c728ace21e0d46ea869f228680bb9ae4bd10e611b2843b492d762a10e17132d0b02dbc437e58565b46ac460a5a44fef9892aa5e33c73dc4e17ff933c0120996048e6edc00db513bb28814e80b7bd884cc5ef3d23e48f8e5d73.GIF)

**Comment by edickens** [comment]
From Michael Clarke about using the breadcrumbs which make him having to start the search again.

Nope. It does not work.

Ok. Sequence:

    Your Actions
    Manage County
    Review Batches by Filename
    Receive list of batches, sorted alphabetically by filename - many pages of this
    Scroll down to a "Zero Years" entry and then click on "Zero Years" button
    Receive a display of a record and with two buttons, "Create new entry" and "Listing of all Error Records in this Batch" - eh? to the "listing button"
    Now, where? I have seen that the record is not blank and I will go back and process it later.
    The first "active" breadcrumb, in reverse, is "Batch Information" - click it
    The standard "batch" display appears
    The first "active" breadcrumb, in reverse, is "List of Batches" - this takes me back to the display of 4, above.

The above sequence is illogical. To get where I want to go (back to the list of batches), I have to skip one of the breadcrumbs as I go backwards through the breadcrumbs. I feel that the "Batch Information" breadcrumb should not be around.

Well, it does work -ish! but not sensibly.

**Comment by SteveBiggs** [comment]
I will reply directly to Michael.

**Comment by SteveBiggs** [comment]
We should remove the two buttons  "Create new entry" and "Listing of all error records in batch" from the page listing zero years.

**Comment by Vino-S** [comment]
Updated the code in test3

**Comment by SteveBiggs** [comment]
The buttons  "Create new entry" and "Listing of all error records in batch" are still present. These should be removed from this view:
![image](https://user-images.githubusercontent.com/25303607/33714255-31105982-db46-11e7-9834-86f81849cd74.png)

**Comment by SteveBiggs** [comment]
From list of zero years page, if I click 'SH', then 'Batch Information' followed by 'Listing of zero year entries' I see the following:
![image](https://user-images.githubusercontent.com/25303607/33714390-aeb39a20-db46-11e7-9fb9-dbbb780c5108.png)
The userid, register, church, place, and county are not being displayed.

**Comment by richpomfret** [comment]
Ready for test on test3

**Comment by SteveBiggs** [comment]
All looks good now in T3.

**Comment by Vino-S** [comment]
Thanks @SteveBiggs . I shall push it to live.

**Comment by Vino-S** [comment]
Pushed to live
