### ISSUE TITLE
Transcriber (etc) can contact ExDir, SC, CC, etc via buttons from landing page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1350]
Messages to go to in-system in box

E0, u10, S 7, c 4?: P=23

**Comment by PatReynolds** [comment]
Needed for GDPR - added urgent and moved up priority

**Comment by Captainkirkdawson** [comment]
Could I ask what "in-system in box" means please

What is

**Comment by PatReynolds** [comment]
In-system in box is where messages from people reporting data errors, etc. go.  
Volunteers should be able to directly contact the CC for Blankshire, etc.  without knowing their email address.

**Comment by PatReynolds** [comment]
Header needs to  indicate that it is coming from a transcriber.

**Comment by Captainkirkdawson** [comment]
@PatReynolds  @richpomfret  @SteveBiggs Have the basic code mapped out but there are some questions.
1. Is this a capability that is to be available for all members not just transcribers?
2. Do we wish to the member who initiates a communication to be able to manage multiple communications in the same manner as we now do with messages. ie multiple communications active at one time; replies to be associated with the original communication.; communications to be archived and kept in the same manner. Note this is the easiest to program. The more different the more code and work involved. 
3. Communication is to their own syndicate coordinator or can they select?
4. Communication to a County Coordinator is a selection? are multiples selections allowed?
5. For other roles with multiple people (eg system administrator) do we go to all or just the first or allow a selection?

**Comment by SteveBiggs** [comment]
My views:
1. All members
2. Same as now
3. Select any SC
4. Select any CC
5. Select a specific (any) SA, etc.

**Comment by SteveBiggs** [comment]
Selecting multiple recipients could be useful if it's practical.

**Comment by Captainkirkdawson** [comment]
Initial version has been deployed to test3 for evaluation

**Comment by PatReynolds** [comment]
Not sure I'm looking in the right place (communications?).  It shows roles that are not associated with my role (e.g. syndicate coordinator).  Executive Director is, on the other hand, not shown (perhaps because it assumes I don't want to talk to myself!)

**Comment by SteveBiggs** [comment]
Exec Dir does not appear in the list as a transcriber either.

**Comment by Captainkirkdawson** [comment]
@PatReynolds  Yes we do remove the role of the person from the list for the reason you specify
@PatReynolds Yes you were looking it the correct place. Could change the Action name to Contact Managers or something similar if you wish
@SteveBiggs  why the executive director was missing is beyond me. I did a restart of the server and its there now for my test volunteer
![communications7](https://user-images.githubusercontent.com/2874694/50702710-f9520780-100e-11e9-98b7-391e9d7f7a0a.JPG)
