### ISSUE TITLE
Tickybox to record that a message sent to an individual  has been answered by the individual outside the system (e.g by a phone call, on slack or otherwise).

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1351]
A tick box for showing intent to reply 'outside the system'.
Priority 20 (Economic 0, Urgency 8, Strategic 8, Cost 4)

**Comment by Captainkirkdawson** [comment]
I believe that this has been addressed by the contact system reply system

**Comment by SteveBiggs** [comment]
I don't believe the system allows recording of replies sent outside the system does it? (other than by manually destroying the contact).

**Comment by SteveBiggs** [comment]
Please clarify what I am being asked to do.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  guess I forgot to save my comment which was a question. 
Does this apply to just contacts or to all types of communications (messages feedback etc}

**Comment by SteveBiggs** [comment]
I would suggest it should apply to all comms that could be replied to outside the system.

**Comment by Captainkirkdawson** [comment]
Technically someone can always respond outside the system to all types of communication

**Comment by SteveBiggs** [comment]
Yes, so any communication type that can be replied to within the system should have a tick box

**Comment by Captainkirkdawson** [comment]
Got it. Now do we wish to collect information as to whom replied off line? 
It is likely wrong to assume its the person ticking the box. ie it could be me you or someone else ticking the box knowing a coordinator had done so.
Do we want date?
ie how complex /simple do we want to make it?

**Comment by Captainkirkdawson** [comment]
Thank you for the clarification. I think the simplest solution is to implement the requirement as a reply to the communication that does not get sent to anyone but simply gets stored with the communication. That way we know who provided the input and they can put in as much or as little as they wish. It could also be used to record other information about the communication. Will leave it open for  comments for a while and do 1350 first

**Comment by SteveBiggs** [comment]
I agree with that approach.

**Comment by PatReynolds** [comment]
That is an elegant solution, Kirk.

**Comment by Captainkirkdawson** [comment]
Comment capability added to comments, feedbacks, messages and communications. Deployed to test3

**Comment by Captainkirkdawson** [comment]
EricD suggests
My only comment is that after selecting the role, then you need to know the person's UserID.  Could the pick list give the name in brackets after the UserID?

Eric

**Comment by PatReynolds** [comment]
Pat to test
