### ISSUE TITLE
Refine "Report A Problem" for volunteers

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1353]
This is the story about moving from the current pathway to one that takes people to a FAQ, and then to an email contact, if the FAQ is not sufficient.  It may be a duplicate, but I can't find this story on the board.

**Comment by Captainkirkdawson** [comment]
There is story #1230 that was to have a series of FAQs written based on the comments received by coms. It was to be made available on the contacts page when it was written. That was 3 months ago.
It was not designed for volunteers but for researchers. Volunteers already have their help pages and report a problem.

**Comment by PatReynolds** [comment]
Yes, I was mistaken: this story doesn't make sense!
