### ISSUE TITLE
Contact system and Feedback system need a 'reply' function.

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1359]
Person receiving a contact should be able to reply directly, rather than needing to use private email.

**Comment by suffolkroots** [comment]
Contacts should be automatically forwarded to COORD's email address. There should be no need to visit the site to access messages.

**Comment by richpomfret** [comment]
Duplicate?

**Comment by PatReynolds** [comment]
#1380 only covers this function for CCs.  @richpomfret do you want to change the title of that one to cover other roles, reopen this one, or create new stories for management, SCs, and other volunteers?

**Comment by SteveBiggs** [comment]
FYI, SCs do not have access to Contacts, but other roles do. All who have access should be able to reply to them within the FR Contacts system. We can close #1380 and expand this story to include Feedback too.

**Comment by richpomfret** [comment]
Updated 1380 and will close this story.
