### ISSUE TITLE
Split the private from the public in the Transcriber's notes field

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1361]
This story is possibly a duplicate.
This story is possibly dependent on #809 (flexible CSV).
The proposal is to split information which should be shown to the public (and shared as Open Data if open), from that which is for internal use only, and should not be shown.

**Comment by SteveBiggs** [comment]
@PatReynolds Can you give an example of something that should be recorded in the notes of a specific transcription, but not made viewable by the public?

**Comment by edickens** [comment]
The  transcribers notes are to be viewable by the public.  It is just to separate TWYS from interpretation or hints for the researcher.

**Comment by Captainkirkdawson** [comment]
The original implementation of FR2 includes 2 notes fields.
field :notes, type: String
field :notes_from_transcriber, type: String

Unfortunately the CSV format does not permit the additional field.  It was this requirement that drove the flexible CSV format story.  #809

Implementation of #809 will require mods to winreg and winfreereg. 

That will require a Winreg developer.

**Comment by Captainkirkdawson** [comment]
Being address as pert of #809
