### ISSUE TITLE
Duplication of data rows in a file and multiple attic records.

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1364]

**Comment by Sherlock21** [comment]
The record concerned is CON / St Gluvias Marriages.
CONGLUMA.csv by Pedlar.

It was a file that have no dates. 
I downloaded the latest good file from the Attic, and then reloaded it this morning. at about 12:30 GMT on 10th Dec 2017.
Now, the CC tells me that there are  duplicates in that file .

in a download copy of the present batch at about 16:00 hrs, I see there are some 215 records. A look at them indicates there actually is a difference between these duplicate rows, in the witness names. .

Checking against the file I reloaded ( at 12:30 pm) there are NO duplicates in the file which I reloaded . And the CC confirms she has not done anything to it today.

Looking at the attic listing right now: there are 5 entry times for today! Some of which are within minutes of each other.

SO until the reasons for this situation are clear, and rectified, I will suspend doing any of the actions associated with Marriage dates disappearing.
Please investigate and advise.

**Comment by SteveBiggs** [comment]
I do not know why there are so many versions in the attic, but all except one of the files are the same and the transcriber has clearly written that they have created duplicate lines due to there being more than 2 witnesses. The one file without the duplicates appears to be an earlier version.

**Comment by Sherlock21** [comment]
Ahhh.i did not see that note.

So I will discuss that with the CC.

please destroy this problem note then.
eric
