### ISSUE TITLE
CCs can create new IS county and register folders and upload images

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1365]
Provide the ability for CCs to create new register folders on the IS including ability to create county if it does not exist. 
Provide the ability for CCs to upload images to the IS register folder.
Provide the option for the system to generate and prepend the county, place, register and group names to the image name on the IS
These creations generate the appropriate entries in register, source, image_server_group and image_server_image collections.

**Comment by Captainkirkdawson** [comment]
Multiple file uploading will likely require a version bump to carrierwave our uploading gem or an alternative piece of software

**Comment by Sherlock21** [comment]
For all the reasons that we ended up with a queuing system in the Transcriptions/batch input system, I think thats a good point IF the Image System is to be shared across multiple servers like the data is.

and that leads to a little point: can the IS Manager 'jump the queue' if necessary like I do on Data files?

**Comment by PatReynolds** [comment]
Discussions/suggestions moved to email list.

**Comment by Captainkirkdawson** [comment]
There is no queuing system for uploading. There is a queuing system for processing csv files.
What is more interesting is the question of how many coordinators have service contracts with their ISPs that provide a service level required to upload GBytes images at a reasonable speed. 
The elimination of net neutrality as currently proposed may well have a much more significant impact on both this and our overall services.

**Comment by Captainkirkdawson** [comment]
Feature added and deployed to test2.

Creation of image_server_image document for uploaded image NOT active

**Comment by Captainkirkdawson** [comment]
Creation of image_server_image document now integrated into upload.
This story is completed from a feature perspective.

**Comment by Captainkirkdawson** [comment]
The list of permitted file types for upload and download is jpg jpeg pdf txt png tif tiff rtf doc docx

**Comment by edickens** [comment]
Can we include CSV?  Same formatting as TXT.  The reason is that I have some CSV without permission to include in the database, or are for recent years to be included in due course.  The IS is a good place to save them until they can be uploaded into the database.  If easier I can just change the file type to TXT and the filename will look like a transcription ready for uploading.

**Comment by Captainkirkdawson** [comment]
Do you want xls xlsx as well???

**Comment by edickens** [comment]
Might as well.  We get donated transcriptions in Excel.  And odp, although I have never had a transcription with that?

**Comment by Sherlock21** [comment]
I am sure that would be more efficient to do all these now, rather than ask in 6 months time for these.

**Comment by Captainkirkdawson** [comment]
csv xls and xlsx added as whitelisted file types.

These can be uploaded/downloaded to the Image Server but not viewed (an attempt to view will be responded to as a download) nor will there be thumbnails.
