### ISSUE TITLE
Add thumbnail image to Image Server

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1368]
Currently there is a list of images and one has to display them in turn. It would likely be helpful to attach a thumbnail to the image name

**Comment by Captainkirkdawson** [comment]
Added a thumbnail  display to the Image Server listing of images. Works for jpg and tif  images

**Comment by Sherlock21** [comment]
Great news and thanks for suggesting the idea.

Which test region is it deployed in please?

**Comment by SteveBiggs** [comment]
I'm getting a gateway timeout trying to access the images now. Whether as Sys Admin through 'Manage Image Server' or as CC through 'Manage Images' > 'Access Image Server Directly', I click 'Show Registers' then click 'Show Images' for any place with images and get:

![capture](https://user-images.githubusercontent.com/25303607/34460979-66c4a726-ee16-11e7-84ba-da165554d46f.GIF)

**Comment by Captainkirkdawson** [comment]
Uh well; wondered if that might happen. The first time the images are listed we create the thumbnails if they do not exist. For a register with a large number of images this could take some time. 
Guess we need to run a rake task and do a one time creation.
Out of interest which register images were you listing?

**Comment by SteveBiggs** [comment]
I believe I started with Albourne. Just tried again and it came up instantly this time reinforcing your comments.

**Comment by Captainkirkdawson** [comment]
Yes the code looks to see if the thumbnail is there; if it is not there we creates it and saves it for the next time.
Not sure if the thumbnail will be useful but the only way of answering that question was to create it and see it it adds anything useful

**Comment by SteveBiggs** [comment]
It's useful for SC's like me who only allocate images that have something to be transcribed on them, so I can check the thumbnail for having records or not. But I believe that most SC's just allocate the whole batch (group) including title, blank, end , etc images regardless of whether there is transcribleable content or not.

**Comment by Captainkirkdawson** [comment]
Rake task written to create thumbnails.
Currently running on langur

**Comment by SteveBiggs** [comment]
Did the rake task complete successfully? I'm still getting gateway timeouts trying to 'Show Images'

**Comment by Captainkirkdawson** [comment]
Currently up to LIN. As noted lagnur is a weak server primarily used as a file manager with large amounts of disk

**Comment by Captainkirkdawson** [comment]
At Midnight MST on Jan 6 we are half way through SOM. Estimate 3 more days

**Comment by Captainkirkdawson** [comment]
Creation of all thumbnails is now complete
