### ISSUE TITLE
Missing images associated with fallback CSS for icons

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/MyopicVicar#1369]
Without Javascript:

On Safari 8 and Firefox 56 (Mac), `icons.fallback.css` is served up correctly, but none of the icons are rendered.

URL for site icon image is:
`url("../../images/png/freereg.png");`

Is this URL correct? Is the failure to do with the specific server?
And does it matter? — have we had any complaints?

I do not know how to force a browser to serve up icons.data.png.css, but as the images are actually *in* that file, as data strings, there should not be an issue.

It would be good to know how many times FreeREG gets asked for either of these backup CSS files. My guess is never (except twice, a few minutes ago, and a couple more a few weeks ago when I was not thinking straight!). Can I find out out by looking somewhere?

![search_query___freereg](https://user-images.githubusercontent.com/14852554/34450066-b0db7e62-ecf8-11e7-89fd-768b20c93d79.png)

**Comment by AlOneill** [comment]
There is no such problem on FreeCEN 2, where the image URL for the site icon is given as:
`url("/assets/png/freecen-699abc4a436786b253015b9c1960966c2f9f8e0b4ebcadc764ab4fca22bdfa27.png");`

It seems that the FR reference is a standard relative address (not app-ified), whereas the FC one, starting with a /, looks more like how we typically format internal links.

**Comment by AlOneill** [comment]
Note: I turned JavaScript off merely as a way of forcing the fallback CSS to be served. The actual intention is that the fallback CSS is served to those browsers that cannot display SVG-data or PNG-data images. It relies on being able to 'find' the (ordinary) PNG images of all our icons.

Currently, the donate-icon is only available as inline SVG. Have we had any complaints/comments about the donate-icon? I am really not sure what exactly would show, if anything, in a browser that cannot display inline SVG! In theory, I think the user would see a link with the text 'Donate', but ...

**Comment by AlOneill** [comment]
@benwbrum GruntIcon.js sets up the icon stylesheet tag based on its assessment of the OS/browser capabilities. The best combos get `icons.data.svg.css`; less capable combos get either `icons.data.png.css` or `icons.fallback.css`.

There will be a couple of instances where icons.fallback.css was served to my browser: 19 days ago and perhaps up to a month before. I don't know how to force the serving of the PNG-data version, so any references to this in the logs should be genuine.

**Comment by benwbrum** [comment]
TODO for @benwbrum: mine logs for this.

**Comment by PatReynolds** [comment]
Is this needed to implement the new colour scheme?

**Comment by AlOneill** [comment]
@PatReynolds More an issue of needs to be addressed for current and new colour schemes OR not at all — if we choose not to cater for users with browsers that can't use data.png (have a feeling that could be expressed a lot more clearly!)

**Comment by Captainkirkdawson** [comment]
Have changed the url, perhaps @AlOneill can check to see if the change works

**Comment by AlOneill** [comment]
@Captainkirkdawson Not working if javascript disabled on test3 or live.

**Comment by Captainkirkdawson** [comment]
It is important to remember that without javascript there is no ability to search by place; solely by county. Suspect there are similar limitations within FreeCEN without javascript.

**Comment by Captainkirkdawson** [comment]
@AlOneill please try again on test3

**Comment by AlOneill** [comment]
@Captainkirkdawson Now working on test3 — i.e. without javascript*, CSS fallback is finding associated images.

* Turning off javascript is the only way I can think of to force Firefox to use the fallback CSS: I do not have a browser that does not understand data.png

**Comment by Captainkirkdawson** [comment]
TY

**Comment by richpomfret** [comment]
Ready for deplpyment
