### ISSUE TITLE
Extra MA fields

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1375]

**Comment by edickens** [comment]
I hear that the Marriage Certificate is to be changed to include Groom's and Bride's mothers' name and occupation.  We will need new fields for this.

**Comment by Sherlock21** [comment]
Shall we bite the bullet and also add extra witness fields as well?
And include a method of handling Old style Files as well as those with these extra fields - since some transcribers may well not be able to cope if they have to Resize their spreadsheet before they do a revision upload.

**Comment by edickens** [comment]
There are quite a few other fields that we would like and there are plans to add them when we get flexible data entry in V1.6.  But the fields need to be allowed for on the server and in the displays.

**Comment by PatReynolds** [comment]
Dependent on #809 (flexible CVS)

**Comment by Captainkirkdawson** [comment]
Part of #809
