### ISSUE TITLE
How should Nuns be entered?  Help needs updating

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1377]

**Comment by edickens** [comment]
For example.  How do you enter "Sister Mary".  If the lastname is omitted, then the name is not found in the Search.  Try Mary, PEM, BU, 1976.  Four results should be returned.

**Comment by SteveBiggs** [comment]
@edickens what is the place in PEM?

**Comment by edickens** [comment]
Place is Bridell filename PEMBRABU UserID JayAnn.

**Comment by SteveBiggs** [comment]
It would appear that there is a bug in the search algorithm. You should be able to enter just a forename (together with first & last year, county, place and type) and it should return all results with that forename. This works if you search a forename only where there is a surname in the record, however when a record has no surname listed, this search does not work.

The help notes correctly states "Enter only the actual name: anything else, such as Revd or Snr or Laird, belongs in the Notes field." But the search is not working correctly.

**Comment by edickens** [comment]
Should Sister (when a Nun), Revd or Laird etc. go in Occupation if the record has that field?

**Comment by SteveBiggs** [comment]
That would make sense yes, but the important thing is to fix the search algorithm. I'll raise a new story for that.

**Comment by richpomfret** [comment]
This shoud already be covered in Help without an update needed. Closing.
