### ISSUE TITLE
Search for Forename only not working

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1378]
It would appear that there is a bug in the search algorithm. You should be able to enter just a forename (together with first & last year, county, place and type) and it should return all results with that forename. This works if you search a forename only where there is a surname in the record, however when a record has no surname listed, this search does not work.

**Comment by Captainkirkdawson** [comment]
Please provide an example of such a search

**Comment by SteveBiggs** [comment]
I've realised that the problem is that burials of Nuns have been recorded as for example, forename 'Sister' and surname 'Mary' which is of course wrong. The forename is Mary and no surname should be recorded.
This issue can be closed.
