### ISSUE TITLE
Editing a record online appears to cause the LDS refs to drop off the record

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1379]

**Comment by Sherlock21** [comment]
File   Nosirrah.WRYACKBU1.CSV contained 7 records with errors.
These were edited online by the CC, on 8 Jan 2018.

SO the process created 7 entries in the Attic.

**Comment by richpomfret** [comment]
Needs to be further investigated.

**Comment by SteveBiggs** [comment]
I have tested with some of my files (WinREG generated) on live site and cannot reproduce the problem.
