### ISSUE TITLE
Add link to privacy notice in footer

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1383]

**Comment by benwbrum** [comment]
The Privacy policy is on the Free UK Genealogy website; scroll down to the footer and see the URL used there.  (And wording)

**Comment by DeniseColbert** [comment]
Link: https://www.freeukgenealogy.org.uk/files/Documents/Privacy-Notice.pdf

**Comment by smrr723** [comment]
Deployed and now on live.

**Comment by richpomfret** [comment]
Duplicate.
