### ISSUE TITLE
Cleanup GitHub Branches

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1385]
We are developing a major [problem with Github. I have flagged this on Slack to no avail
We have 74 branches; most of them stale. With such a number it is not clear what has been incorporated into Master and what has not.
We even appear to be running test branches on vervet that are not in Github eg #1034

**Comment by Captainkirkdawson** [comment]
Vino has reduced the number to 30

**Comment by benwbrum** [comment]
30 is still pretty high -- moving back to in-progress for further pruning or comments.

**Comment by Captainkirkdawson** [comment]
Down to 20
