### ISSUE TITLE
Update of software used by FreeREG and FreeCEN

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1386]
FreeREG and FreeCEN have both started to get out of date with respect to the the major software components they use, While they are both not experiencing any apparent glitches from the use of out of date components it is undesirable to get too far behind the current status of those component,
perhaps we should conduct a short analysis of our current status compared to the current status of the software.

Priority (for conducting the analysis) (24)
Economic 2
Urgency 6
Strategic  9
Cost  7 (please feel free to change!)
Needs #1676
needs #1793
needs #1163

**Comment by Captainkirkdawson** [comment]
Currently restricting my thinking to Ruby, Rails, Mongodb and Mongoid

**Comment by Captainkirkdawson** [comment]
Have built upon ruby 2.4.3, Rails 5.1.5, mongoid (6.4.0), mongo (2.5.1), refinerycms (4.0.1), devise (4.0) as well as appropriate bumps to many other gems.
All is good EXCEPT i cannot get refinerycms-authentication-devise (2.0.0) to play correctly. as I cannot access a field with the ORM using the key. I can with a symbol but the code base does not work without the key access. eg currect_refinery_authentication_user does not respond to email even though currect_refinery_authentication_user contains. It is as if the reader and writer are not present.

**Comment by Captainkirkdawson** [comment]
Found the issue. Appears you cannot have 2 attr_accessor statements in a model

**Comment by Captainkirkdawson** [comment]
test2 now running the very latest code set

**Comment by Captainkirkdawson** [comment]
Only component unchanged is mongodb remains at 3.2. Bumping this requires action by lemon. Not sure I have enough enthusiasm to undertale

**Comment by Captainkirkdawson** [comment]
Bev has discovered that rails 5 has depreciated redirect_to :back on favour of  redirect_back fallback_location: ...............
We will need to check our code for its usage and apply those changes to the software_update branch. 
This may also affect unique FreeCEN code @Vino-S  @benwbrum

**Comment by Captainkirkdawson** [comment]
Only code changes remaining are the image server changes

**Comment by bev-fc** [comment]
@Captainkirkdawson Assignment/ImageServerGroup/ImageServerImage/Source have been modified

**Comment by Captainkirkdawson** [comment]
@bev-fc  The use of a  fallback_location: root_path is quite inappropriate as it will take the member back to the search page. We should take the member back to an appropriate page in the app according to what they were doing. eg what was done with the earlier changes
redirect_back fallback_location: { action: "show" } and 
fallback_location: "/manage_resources/new"

**Comment by bev-fc** [comment]
@Captainkirkdawson can you show me a link that it falls back to search page so I can take a look?

**Comment by Captainkirkdawson** [comment]
@bev-fc  any and all of the links that uses  fallback_location: root_path will by definition go to the search page should the actual returning address have an error ie it does not exist or is incorrect.  So to get an example you will have to force an error condition. So one selects a fallback_location that enables the app to take logical control again at an appropriate place in its logic. fallback_location: root_path is effectively restarting the app.  But we know we can restart somewhere else.  The previous post gave a couple of examples you can go to some action in the Assignment  ImageServerGroup  ImageServerImage Source code

**Comment by bev-fc** [comment]
@Captainkirkdawson In previous code, when an accident/error condition happens, it will call redirect_to :back to go back to previous page, since the syntax is deprecated in the new version of rails, I replaced them and they are now still go back to the previous page, the same as previously. I am sorry I didn't catch up with what is needed here.

**Comment by Captainkirkdawson** [comment]
Removed from test2. Ready for deployment in my opinion. 
Failure to deploy leaves us open to certain issues.

**Comment by Captainkirkdawson** [comment]
We are not in compliance with our security policy

**Comment by PatReynolds** [comment]
Hi Kir, deleted your comment but it is noted and will raise in discussion with Rich in 5 mins!

**Comment by Captainkirkdawson** [comment]
Reactivated after 6 months. Bumped rails to 5.1.6, mongoid to 7.0,  mysql2 to 0.5.2, refinerycms to 4.0.3.

**Comment by Captainkirkdawson** [comment]
Changes required. 
1) redirect_back fallback_location: { action: "show" } and
fallback_location: "/manage_resources/new" (or similar) instead of return_to :back
2) dependent: restrict_with_errors instead of :restrict

**Comment by Captainkirkdawson** [comment]
To do

Place location

**Comment by Captainkirkdawson** [comment]
Changes
1) skip_before_action not skip_before_filter
2) redirect_to :back changed to redirect_back with fall back

**Comment by Captainkirkdawson** [comment]
Need to check places location

**Comment by Captainkirkdawson** [comment]
Deployed to test3 for checkout

**Comment by Captainkirkdawson** [comment]
One minor bug noted and fixed (spelling error). 3 county coordinators, the 2 Erics and Pat have been using. Ericb has commented no issue in his transcriber related testing. ie upload/replace/download. Search has been exercised no issues.

**Comment by SteveBiggs** [comment]
Testing Image Management:

Selecting 
![image](https://user-images.githubusercontent.com/25303607/51625598-764d0e80-1f35-11e9-9cb8-190d5b4d23e8.png) and 
![image](https://user-images.githubusercontent.com/25303607/51625654-a4325300-1f35-11e9-819b-5ebaaa003dac.png) and 
![image](https://user-images.githubusercontent.com/25303607/51625708-c88e2f80-1f35-11e9-8712-8300ec0cfa24.png)


returned red error page

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  All 3 fixed.

**Comment by Captainkirkdawson** [comment]
Excellent TY @SteveBiggs

**Comment by Captainkirkdawson** [comment]
Ericb reports he has finished his testing. No issues.

**Comment by Captainkirkdawson** [comment]
Would like to proceed with deployment again

**Comment by Captainkirkdawson** [comment]
Deployed to all production servers a few minor bug tweaks were required. A second deployment was done on 5 Feb 2019 late in the day.
