### ISSUE TITLE
Move Images Features to Staging for wider testing

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1387]
Move Images features to Staging (when initial testing completed)

**Comment by Captainkirkdawson** [comment]
I am unsure of the relationship between this story and the comment request to me in closed story #1333
Should Steve/wider testing be done on Test3 rather than 2?

In my opinion we should now be merging the image server software into Master and deploying to test3. The use of test2 has served its purpose of developing the code base.

One of the difficulties with testing this software in test3 is that data changes to the Image Server collections, allocations and such things are not forward transferable to production. Hence coordinators and transcribers may not be willing to invest too much effort in testing.

We may want to consider moving the image server software  rapidly from test3 into production. The software adds new functionality that is in essence independent of the current software base hence should not interfere with current functionality of FreeREG

**Comment by edickens** [comment]
I agree with Kirk's last paragraph.  These routines will only be used by Coordinators to start with, although I  realise that there are also Actions for Transcribers.  There are also not that many Counties that are actively using the Image Server.  But there are images for many counties which may or may not have been transcribed.  The CC needs to check this out.
When we launch we need to tell everyone that we are just starting and getting the database set up.  We can open to actual assignments on a County by County basis.
I have to set up the active assignments, and I have some that go back to the end of 2016.
But it is working with real data which will see how easy it is to use.  Like all things new, it will take time to learn, but it is a huge step forward.  Thanks.
PS.  When we left FR1, we took a gamble when we opened to transcribers.  It was then just a few weeks before everyone stopped using FR1.  I see the same happening here.  I also hope that when those counties who do not use the Image Server realise that their county RAP will show nothing, that they will start to use the server.

**Comment by SteveBiggs** [comment]
I agree with getting into production soon, but would like to give a little more time for the coordinators who are currently testing it before we do.  Perhaps another two weeks? I'll ask them if they have any more comments which might prompt them to complete the testing quicker.

**Comment by Captainkirkdawson** [comment]
Good idea @SteveBiggs. Let's plan to make a decision in the next scrum which I plan to attend

**Comment by Captainkirkdawson** [comment]
Bev is currently merging master into our branch to bring it up todate.

**Comment by Captainkirkdawson** [comment]
Done. Conflicts resolved and deployed to test2. It is now possible to update master with bevbranch5 should we wish to proceed with deployment

**Comment by benwbrum** [comment]
Awaiting decision by @SteveBiggs on whether to merge to `master` and place on `test3`.

**Comment by SteveBiggs** [comment]
I suggest we go ahead. I have not had any constructive comments from testers for several days so lets progress with it to test3.

**Comment by Captainkirkdawson** [comment]
Thank you @SteveBiggs we will start the process and keep you posted

**Comment by Captainkirkdawson** [comment]
We have done all required merging; have retested the ingestion of the list of files from the image server.
We cannot proceed further until we get confirmation from @Vino-S  that testing of the current branch on test3 is complete, #843

**Comment by Captainkirkdawson** [comment]
Deployed to test3

**Comment by PatReynolds** [comment]
Very happy with how this is going and proposed plan for next steps.

**Comment by SteveBiggs** [comment]
What is the recommendation now in terms of testing? We have already had 6 testers using it on Test2. Do we want to open Test3 up to all coordinators before it goes live?

**Comment by edickens** [comment]
I like that idea.  It will give them a chance to use it without messing up the live set of images and IGs.
Should we ask them to decide if they will use this or not.  And if not, what arrangements are they going to make for managing their transcribers?  I am happy to help them along with any changes they may make, and I hope that there will be a lot of new images to be uploaded, although this should be those that have not been transcribed, at least to start with.
If they are going to use it and have images already uploaded, then they may need guidance on the management of the Image Groups.  Some Places have groups of a few thousand images each, so may need dividing up.

**Comment by Captainkirkdawson** [comment]
test2 still has the image server code and everything people have done to date.
test3 is there. It uses the same test image server files as test2. So some cross talk is possible but unlikely.
test3 does need testing by experienced people before further opening as the merge was complex.
Is the documentation in #999 complete? Do we need a video first #1394 first?

**Comment by Captainkirkdawson** [comment]
In which case we do not tell anyone yet (some may notice) leave the current testers where they are unless you have someone who can walk through test3 image server

**Comment by Captainkirkdawson** [comment]
The image server code is in master and deployed to production but remains inactive as there are no collections.

**Comment by edickens** [comment]
I wonder if any CC will notice the new Action!  No feedback yet.

**Comment by richpomfret** [comment]
Steve to write the documentation and Kirk to put together a video.

**Comment by SteveBiggs** [comment]
I have written a simplified document and sent it to others for review and comment.

**Comment by Captainkirkdawson** [comment]
Deployed to production
