### ISSUE TITLE
Identify means to Write program to be able to remove "bleed-through".

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1388]

**Comment by edickens** [comment]
I have asked around and nobody knows of a program which will remove, or reduce "ink bleed-through" on images when the offending page is available.  There are programs which will try to identify what looks like bleed-through when looking at the page.  But we have access to the page which is causing the bleed-through.  So it should be possible to take the offending page, mirror it left to right, freely rotate and resize to overlay it on the front page, then change the transparency to eliminate the bleed-through, then save the result.  This should be much more accurate than trying to just work on the front page.
This needs to be a stand alone program for transcribers and could be marketed.
But this is not urgent, just a very interesting academic exercise for a programmer.  In theory it should not be too difficult as it uses established routines for image manipulation.

**Comment by DeniseColbert** [comment]
@edickens I'm working on this now, but we should address @PatReynolds comment above.

**Comment by edickens** [comment]
Yes.  I have three pairs.  But email me because you will need them in high definition![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/73ba4d4b-27cd-4db7-b7ca-e50904a2a955).
For example...

**Comment by DeniseColbert** [comment]
Thanks Eric, I see Pat has sent an email to us and Helen on this and we should be able to move forward, especially if Helen has some too (for a greater range of examples). I don't think I need the HD files, you can send them directly to the furlunteer when they're on board.

I'll send you the RD shortly.

**Comment by DeniseColbert** [comment]
RD sent to @richpomfret @Captainkirkdawson @edickens @SteveBiggs 29/04

**Comment by edickens** [comment]
The programmer required for this should have experience in writing programs to manipulate graphic images.  The package used for this does not matter, because the resulting program will be offered as a standalone program to run on the transcriber's computer.  It must work on both Windows and Mac.

**Comment by edickens** [comment]
PS.  Program to be free to FreeUKGenealogy registered transcribers, but could be sold on the open market.

**Comment by richpomfret** [comment]
Reviewed and updated with a few extra bits. @DeniseColbert let's put this out there and see who comes back in.

**Comment by PatReynolds** [comment]
Role dscription written, advert up, and already had one applicant, so now closing.
