### ISSUE TITLE
9 Update County Coordinators Information Pages with current information re. contact with CROs

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1392]
Needs re-writing with SWAT team in mind - @PatReynolds to talk to Mick about what they need.

Priority (0 1 3 5) 9

To be developed by/in consultation with the SWAT team (see story #2319)

**Comment by Captainkirkdawson** [comment]
IMO  Thi is NOT a responsibility of the SC but one for the County Coordinator.

These document used to exist on FR1 help materials

**Comment by SteveBiggs** [comment]
Many coordinators have tried sending letters of various formats to CRO's over the years with little success (they are generally ignored). Rather than giving them another letter to send, they are looking for an official approach to the CRO with some kind of legal back up that we are entitled to have access to images.

**Comment by PatReynolds** [comment]
Sure, I have changed the title to reflect the changes needed (i.e. the process we now have for me contacting record offices unless a CC contact is well established).

**Comment by SteveBiggs** [comment]
No programming requirement, this is only a documentation update.

**Comment by Captainkirkdawson** [comment]
Does @AlOneill know what is required?

**Comment by SteveBiggs** [comment]
I'm assuming @PatReynolds will tell her.

**Comment by PatReynolds** [comment]
Nothing for Alison to do at the moment.  Just me.

Text last edited in 2008, so complete re-write is needed, which I've begun.

**Comment by PatReynolds** [comment]
I've now updated the 2008 version.

Things to be done noted in the story at the top.  Anything else to be added? Example of letter of permission to photograph / transcribe from a CRO?

**Comment by PatReynolds** [comment]
Moved bulk to the "Information for the SWAT team" page (story #2319).

Text updated at Information for Coordinators DRAFT needs review.  Possibly needs a direct link to the Information for the SWAT team page, too, between the links to the Image Server and Behind the Scenes?

**Comment by PatReynolds** [comment]
Mick, Steve and Eric to take a look.

**Comment by edickens** [comment]
I suggest that CCs should NOT approach CROs while Mick is finding out the best approach.  My experience says that CROs just say NO to avoid any extra work and without any real reason behind it.  So we need to set a precedence and then we can approach CROs to say that the XYZ county have given permission and for what reason, so please do the same.  They then know that what we are doing is legal and approved.  It may need TNA's endorsement.

**Comment by PatReynolds** [comment]
In line with Eric's comment on 17 Sept, 

I have put a section between 'The Image Server' and 'Acquiring transcriptions from other projects' in the Information for Coordinators page on test3.

Text:
Obtaining images to transcribe has proven to be very difficult. FreeREG has therefore set up a team of volunteers who will take the lead in working with potential partners to secure access to images to transcribe. Please contact SWAT@freeukgenealogy.org.uk with any specific requests, or if you are aware of a source which might be available to us. Under  no circumstances can a Free UK Genealogy volunteer transcribe from an image which has been downloaded "for personal use only" (or similar condition), e.g. from a commercial genealogical site.

I have replaced point 3 in the Coordinator's responsibilities with this:
Liaise with existing sources of transcriptions (e.g. the relevant County Record Office / Archive). Where there is no existing relationship, support the SWAT Team in obtaining permission, if requested.

Line 2 of transcription workflow now:
Inform the SWAT team 

Feedback on the above is requested @edickens @SteveBiggs (also Mick - will inform by email)

**Comment by edickens** [comment]
Pat,
I can't see your new section in Test3.

In "Acquiring data from other transcription projects" the CC is asked to contact the source.  I suggest that they do not but contact the SWAT team so that a formal approach can be made and proper permission obtained.

Also "Obtaining the approval of The Church of England" suggests that the CC does it.  No mention of the SWAT team.
Eric

**Comment by PatReynolds** [comment]
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/bb7918f7-8ef3-430d-bd4c-1a856d758612)

Changed the 'acquiring data' section and removed 'obtaining approval' link.

Do we ask the SWAT team to upload donated transcriptions, or the Coord?  @Captainkirkdawson is implementing a role on FreeCEN2 to do something a bit similar, so it may not need to be a DataManager who needs to do this.

I've removed the link to Church of England approval.

I have made a copy (DRAFT) of the Other Sources and removed links no longer needed.

**Comment by edickens** [comment]
I suggest that whoever has the images should upload them.  Even the donor if they are prepared to register and be given permission.  It is much better than having to transfer huge amounts of data over the internet only to transfer it again to the image server.  But whoever uploads it needs to understand about Image Groups or the CC needs to set them up in advance.

**Comment by PatReynolds** [comment]
Transcriptions should be uploaded by the cord.  Ditto for images.

**Comment by PatReynolds** [comment]
Added: Please continue to work as normal with the Record Office / Archives for your County, but do not make any new approaches at this time.

Added: Only the County Coodinator should upload images to the server.  You can use the Free UK Genealogy Dropbox account to transfer images to the appropriate County Coordinator.

Added: Transcriptions received from others, such as a community project, church project or museum or archive, should only be uploaded by the County Coordinator.  Please use the name of the Project or institution (e.g. "St James' Local History Group", or "Little Wittering Museum" rather than the name of the person who you have corresponded with (e.g. "Rev. Jo Bloggs") as the name of the transcriber.  

Please let me know if further changes are needed.

**Comment by PatReynolds** [comment]
Pat to ask Mick to take a look

**Comment by PatReynolds** [comment]
Contacted Mick 6 Jan 2021

**Comment by DeniseColbert** [comment]
Pat to check for reply

**Comment by PatReynolds** [comment]
Thanks all, now needs final proofing

**Comment by PatReynolds** [comment]
@PatReynolds to check which page and let  @AlOneill

**Comment by AlOneill** [comment]
The draft page, "Information for Coordinators DRAFT" promoted to "Information for Coordinators". Page is sync-ready.
