### ISSUE TITLE
Acknowledge people who contributed to the preparation of a transcription in the search details

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1396]
Currently we record the names of people who have made a contribution to preparation of a batch of transcriptions in the header for a file.
We currently extract this information. It is then processed and associated with the information provided on transcriptions for a register, church and place.
The information is freeform and not subject to any automatic quality control.
The information CAN be updated by the transcriber and coordinator.
How do we deal with this information in the light of the EU GDPR? We have no means for collecting or storing the acceptance by the identified person to have their name published. Do we add the display of this information to the search record details as was proposed as part of #1267

**Comment by Captainkirkdawson** [comment]
Have set up so that after 25 May 2018 the credit field in the search details will no longer be displayed.
There is no known way of  obtaining and recording the authorization of someone being given credit in our historial files.

**Comment by PatReynolds** [comment]
Working fine for me on test3 and test2.

**Comment by Captainkirkdawson** [comment]
Deployed to production
