### ISSUE TITLE
Loops to load view/search_queries/new.html.erb

### ISSUE THREAD

**Issue by rahul2240** [FreeUKGen/MyopicVicar#1399]
Hello 😄 , I was setting up the project and I am facing this error (from rails s terminal window, you can see it loops to load view/search_queries/new.html.erb until timeout) the solution mentioned in doc(install node) is not working for me, I think its with mongodb.Can someone please help.
![myopic](https://user-images.githubusercontent.com/25618739/36348740-9b5fdabc-149c-11e8-82ee-0d3c37eba002.png)

**Comment by rahul2240** [comment]
After reinstalling the mongodb,Now i am getting this error
![pic](https://user-images.githubusercontent.com/25618739/36352351-b4ff6550-14dd-11e8-9d1a-b08dbc1c1e06.png)

**Comment by Captainkirkdawson** [comment]
@richpomfret  @benwbrum @PatReynolds 

Was it the intention that persons  proposing to work on projects with us make use of the team cloud9 or struggle to install the app on their own from scratch?

This is the sort of issue that I would expect to see if working from scratch. It is NOT an easy process and I for one do not have the time to assist in such installations.

The cloning of the team app on cloud9 resolves most issues.

**Comment by rahul2240** [comment]
@Captainkirkdawson Yes you are right I should have setup the project on cloud9 I apologize but the documentation was there to install on os/windows so I thought it will be easier to setup.
Also, I followed all the steps and everything is working fine, all the dbs are working but this is the error that I got at the end.
I will try to setup the project on cloud9 😄

**Comment by Captainkirkdawson** [comment]
rahul what version of mongodb did you install? 
I suspect the issue is that we are using v3.2.11 in our work. 
Mongodb changed changed a default sometime after that to require authorizations to access a database.
I strongly suspect that if you install that earlier version of mongodb your issue will go away.
