### ISSUE TITLE
SC Changes not promolgated to UserIDs

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1402]

**Comment by edickens** [comment]
I have received this message:-
"Syndicate Leicestershire and  Rutland - John Holiston with no correspondent object in database -  these users have latter syndicate in their object: jebsquirt"
but the Syndicate is now:-
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8317b500bf21824785b0b4884fc5ea3e37aa.JPG)
This UserID has had a failure of the email address, but who has received the message to try to make contact some other way?  My message came through freereg-contacts.

**Comment by SteveBiggs** [comment]
There is something odd here. The profile of userid jebsquirt shows the syndicate as this:
![image](https://user-images.githubusercontent.com/25303607/36781153-f62b95ee-1c6c-11e8-830c-332bbdb5b4cf.png)

but in the list of Syndicate coords, Doreen is listed. Who is the correct coordinator?

**Comment by edickens** [comment]
Doreen is the SC for LEI and RUT, which are inactive.  No data.

**Comment by SteveBiggs** [comment]
So why does the profile say John is?

**Comment by edickens** [comment]
Because when I amended the SC for LEI & RUT from John to Doreen and changed the description accordingly, the UserID was not updated.  It is still the same syndicates, but just the name has changed.

**Comment by SteveBiggs** [comment]
Surely the userid's profile should be automatically updated when a syndicate changes coord? Otherwise we cannot rely on the profile details being correct.

**Comment by edickens** [comment]
Or, when the UserID is brought to the screen, the latest description is selected for the SC to which the UserID is linked.

**Comment by Captainkirkdawson** [comment]
I fail to understand why you are changing the names when coordinator changes> All it does is cause these unnecessary "requirements"

**Comment by edickens** [comment]
At present each Syndicate has a name and the name of the coordinator.
![capture](https://user-images.githubusercontent.com/8876165/36796443-7ed61524-1c9d-11e8-9e7c-9eae17e216db.JPG)
I did this at the beginning because there was no way for the transcriber to know who their SC was.  And even now we do not yet have a communications system for the transcriber to contact their SC.
It also helped me to know who is the SC because the list does not give the person's name and the email address is not always obvious as to who it is.

**Comment by SteveBiggs** [comment]
I refer to this list frequently to find out who is the SC for a given syndicate for various reasons. It is important that the correct SC is listed. At times, I need to look up a userid to check what syndicate they are in and up to now, I assumed I could rely on the fact that the SC named in the userid profile was the correct one for that syndicate.

**Comment by Captainkirkdawson** [comment]
See 1002

**Comment by Captainkirkdawson** [comment]
Have done further research. There are 26 userids showing  "Leicestershire and  Rutland - John Holiston"

**Comment by Captainkirkdawson** [comment]
@SteveBiggs wrote "Surely the userid's profile should be automatically updated when a syndicate changes coord? Otherwise we cannot rely on the profile details being correct."

This is not correct. A userid does NOT have the Syndicate Coordinators name it has the the Syndicate name. This is why I have said time and time again a change in coordinator does not have to promulate anywhere. It is only kept in the syndicate document and it is listed in the Syndicate Coordinators report.

**Comment by Captainkirkdawson** [comment]
A report on unique syndicate names in userids gives the following list
(blank) (122)
all  (1)
Any questions? Ask us. (13)
Anywhere - Transcribe for any county
Ayrshire - Mick Claxton
Banffshire - Margaret Shand
Bedfordshire - Bev Bonning
Berkshire - John Slann
Caithness-shire - Rosemary Skea
Cambs and Hunts - Mary Korna
Cheshire - Emma Treloar
Cumberland - John Holiston
Derbyshire & Nottinghamshire - John Turton
Devon - John Pingram
Durham (1)
Durham - Amanda Doyle
East Lothian - Rob Morgan
England
Essex - Julie  Harold
General (2)
GENManager (2)
Gloucestershire - Doreen Olds
Hampshire
Herefordshire - Lindie Prior 
Hertfordshire - Mick Claxton
Kent - Sue Hawkins
Lancashire - Jo Summerfield
Leicestershire and  Rutland - Doreen Olds
Leicestershire and  Rutland - John Holiston (26)
Lincolnshire - Mick Claxton
Middlesex and London - Kyran Payne
Norfolk and Suffolk - Julie Harold
Northamptonshire - Anna  Rufer
Northumberland - Eric Wealleans
Oxfordshire - Eric Booker
Peebles - Nicky Young 
Researcher
Scotland
Shropshire - Tasman Stewart
Somerset - Assistant David Hartley
Somerset - Jackie James
Staffordshire - Michael Clarke
Surrey and Sussex - Steve Biggs
Technical
Training - Jo Summerfield
Unknown (1)
Wales - Glen Jenkins
Warwickshire - Barrie Robinson
Yorkshire

**Comment by Captainkirkdawson** [comment]
The preceding report shows only one syndicate where there is a problem although the blank (122) and Any questions? Ask us. (13) are a potential issue

**Comment by SteveBiggs** [comment]
If we cannot rely on the SC named in the "Syndicate name", I suggest that the Syndicate name should be precisely that and NOT include the name of the coordinator.

**Comment by Captainkirkdawson** [comment]
The  SC name in a syndicate name is a human convention adopted by the current REGManager and therefore is as good as that convention.
The new name of a syndicate once it has been changed is propagated to all userids who are members of the syndicate with the old syndicate name,
The personal name of a SC is not included in the syndicate ONLY the userid of the person with that role. This is the same for any role. The ONLY place where a person's name is stored is in their profile. This is standard computing practice. The SC name in the display of a syndicate is obtained from their userid
The previous post shows the syndicate names that appear in userids. Why some have Leicestershire and Rutland - John Holiston  and others Leicestershire and Rutland - Doreen Olds is an interesting question. The answer is pure speculation. The change in name is reported to have occurred on 12 Aug 2015.  This was a short time after the transition to FR2. During the transition we used a one time table to create the syndicate code based on the naming conventions used in FR1. If there was a trailing space for Leicestershire and Rutland - John Holiston in the one time table. and there is not in the syndicate names then the selection of userids would not have found those with a trailing space. As I said pure speculation.
Will fix these.
It does leave open the question why we have members of the Any questions? Ask us syndicate

**Comment by SteveBiggs** [comment]
Thanks for the explanation Kirk.

I just tried to look at the Any questions syndicate via Manage Syndicate and it does not allow it, so I can't check who the members are.

**Comment by edickens** [comment]
And the"Any questions" has a UserID of "C.C Syndicate" which is not a UserID.  Was this designed for when a researcher wants to register but does not want to transcribe?

**Comment by Captainkirkdawson** [comment]
Replied with details off line


Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Who knows I don't. Syndicate name changed

**Comment by Captainkirkdawson** [comment]
SC changed

**Comment by Captainkirkdawson** [comment]
Corrected "Leicestershire and Rutland - Doreen Olds"

**Comment by Captainkirkdawson** [comment]
Problem was that at some stage Leicestershire and Rutland was spelled as Leicestershire and  Rutland

**Comment by Captainkirkdawson** [comment]
All users now in the one syndicate
