### ISSUE TITLE
Roll out user access to the Image Server

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1404]
Further development of documentation and code requires an actual usage of the system in real life.

**Comment by SteveBiggs** [comment]
Here is my suggested roll out plan:

1. Eric stops uploading images
2. Bev runs her routine to create sources and image groups linking to the batches on the IS
3. Eric starts setting up sources, groups and images, initialising status, etc. for all counties EXCEPT SSX
4. While Eric is doing that, I start initialising, allocating and assigning SSX images using the new actions to my transcribers. This will allow me to test out the full process for real to check it is robust and works smoothly.
5. When Eric has finished initialisation, we choose one of the CCs who currently uses the IS to role out the CC actions to first. When they've allocated some groups to their syndicate, we then introduce them to the SC actions and start moving their transcribers across to access images through their assignments action.
6. After this we move on to each of the other CCs who use the IS one at a time.
7. In the meantime, Eric can be working through the image upload process with the LAN images Jo is giving him, creating new sources and groups and finalise the help doc for that.
8. We then start introducing the image upload process to any CCs who currently send them to Eric so they can upload themselves.
9. We encourage other CCs who currently don't use the IS to move across to it.

I sent out a message to all CCs and SCs yesterday forewarning of the roll out.

**Comment by Captainkirkdawson** [comment]
@edickens  @SteveBiggs  please be aware that the image server access through the app is now to the live image server files NOT its testfiles

**Comment by Captainkirkdawson** [comment]
Have provided bev with the list of files on the image server to create the collections on production

**Comment by SteveBiggs** [comment]
I assume it's only the live site that links to the live image server? Test2 and Test3 still link to the testfiles?

**Comment by Captainkirkdawson** [comment]
No all point to live. We only have one image server application. Likely need a second one.

**Comment by edickens** [comment]
Does that mean that we must stop testing on Test2 and Test3?  Or just not test the upload and image edit routines?  Should these routines be blocked in Test2 and Test3 if they are now using live data.

**Comment by SteveBiggs** [comment]
We should certainly not upload or delete any images through Test2 & Test3. I don't know how feasible it is to remove those actions from Test2 & Test3 - Kirk or Bev can advise on that.

**Comment by Captainkirkdawson** [comment]
I would not start trying to customize the app according to server. 
It would be easy for you to create a test location ie place; church and register on test2 or test 3 for upload testing if you wanted to. The documents created would only appear on those servers. OK there would be such folder on the image server but it would not be connected to the app except through the system admin ation that talks directly to the image server
We could ask Lemon to create a development url on langur. This is the safest long term solutiom

**Comment by Captainkirkdawson** [comment]
Bev has commenced building the collections

**Comment by Captainkirkdawson** [comment]
Collections created. 
@edickens to assess the logs.
