### ISSUE TITLE
Remove email addresses from the credit name field

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1407]
A report on the presence of email addresses in the credit name field has identified 508 files with that condition. 
Selection was based on there being an @ in the credit name. A review shows them all to be email addresses.

Since we use the credit name field publicly to give credit this should not be permitted.

Rather than asking SCs to update those files on-line  have the rake task change the field to blank.

**Comment by Captainkirkdawson** [comment]
Awaiting the modification of the csv file processor to stop further creations

**Comment by Captainkirkdawson** [comment]
We are no longer permitting the creation of credit names containing an email address.

How shall we deal with the 508 files? We could simply put them to blank @SteveBiggs  @PatReynolds  Advise please

**Comment by PatReynolds** [comment]
If this is (potentially) the only occurrence of an email address, I would be loath to loose it.  A dump to spreadsheet of the ID and addresses would be fine.

**Comment by SteveBiggs** [comment]
I'm assuming most, if not all are the email address of the transcriber? In which case, their email address is also recorded in header line one (and in their FR profile). If it is a non-volunteer email address, it should be deleted, so I suggest set them all to blank.

**Comment by PatReynolds** [comment]
It may be an old email address, which may still work, so useful to have.  But doesn't need to be in the database any more.

**Comment by Captainkirkdawson** [comment]
@PatReynolds there is no ID associated with a credit name.
Yes there is a list of the values. Who wants it? I don't
Will blank them out.

**Comment by PatReynolds** [comment]
What is associated with the credit name if not a user ID?
I am happy to curate the spreadsheet.

**Comment by Captainkirkdawson** [comment]
Why would an ID be associated with a credit name?????????????????????
The credit name is a field in a header entered by a transcriber. It can be anything or anyone the transcriber feels like saying needs to be given credit for the transcription IN ADDITION to themselves (unless they do not want to be identified. 
So if I as a transcriber said Patricia Reynolds should be given credit how are we to know who Patricia Reynolds is or has an ID?????

**Comment by SteveBiggs** [comment]
The intent of the credit field is to acknowledge someone/institution who contributed to the transcription. It could be the donor of images, a FHS or a RO, etc. The transcriber themself has their email address automatically recorded in header line 1. Their ID is not recorded in the header (unless they manually put in the credit field as some have).

**Comment by Captainkirkdawson** [comment]
All email addresses appearing int credit name field have been eliminated. There were 513.
A list has been provided to @PatReynolds
