### ISSUE TITLE
Modify the csv file processor to store the credit email address

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1408]
Credit names should not contain an email address. Check for an @ in the credit name and reject the rentry

**Comment by Captainkirkdawson** [comment]
Check added. Deployed to test2

**Comment by Captainkirkdawson** [comment]
@SteveBiggs reports that the code rejects valid credit names.
New version is deployed to test2 for testing

**Comment by SteveBiggs** [comment]
Looks good on test2. Having just a name works fine.
I also see that it is stripping out an email address but still processing the file which is what we want. 
Please deploy to production.

**Comment by Captainkirkdawson** [comment]
The check does NOT strip the email address it refuses too process the file and gives a message

The credit person name June@Doe cannot contain what might be an email address in the third header line. 

Personally I believe the user should be advised they are doing something wrong and correct it

**Comment by SteveBiggs** [comment]
I agree that we should tell users to stop putting email addresses in (and I already have), but I've just uploaded 2 files to test2 with an email address in the credit field and they processed fine. When I look at the batch header, the email address has gone. This may have been unintentional, but I would like it to stay that way.

**Comment by Captainkirkdawson** [comment]
You will have to show me how you did it because all my tests do not get processed either as replacements or as new uploads
Started on the file NFKACLYBA.CSV for Captainkirk at 2018-03-21 17:31:17 +0000.
Processing was terminated because of a fatal header error.

The credit person name June@doe cannot contain what might be an email address in the third header line.

**Comment by Captainkirkdawson** [comment]
An email address in the 4th field is fine

**Comment by SteveBiggs** [comment]
Here is the header for one of the files I uploaded.
![image](https://user-images.githubusercontent.com/25303607/37727235-37f976a8-2d2f-11e8-904c-e356c2d35aa5.png)

**Comment by Captainkirkdawson** [comment]
The email address is in the 4th field. The 3rd field contains CER which is fine as a name. We only object if the email address is in the 3rd field

**Comment by Captainkirkdawson** [comment]
Am deploying to production

**Comment by SteveBiggs** [comment]
Yes. The email address is in the forth field because that is the field called email address. The 3rd field is called name so has the name in it. I've not seen any files that have used the fields the other way round.
Anyway, I think it works how we want it - strip out the email address and allow the name to stay.
We (I) need to make it clear that using a pseudonym will not stop the credit name being visible.

**Comment by Captainkirkdawson** [comment]
But the issue we were fixing was that some people HAD put an email address in the third field the name field! There were 512 batches with an email address in the credit name field that have now been fixed.

**Comment by SteveBiggs** [comment]
OK, I guess that completely passed me by! I thought we were removing addresses generally for confidentiality. I blame overwork .... :-(

**Comment by Captainkirkdawson** [comment]
No the email address is fine in an email address field but not when it is put into the name field because then the email address get displayed in the credit as part of the acknowledgement.
Yep I think we volunteers are working too hard.
I plan on a break of at least a week if not longer

**Comment by SteveBiggs** [comment]
But the uploaded file does not show the email address:
![image](https://user-images.githubusercontent.com/25303607/37735384-c3e11066-2d45-11e8-8cee-dddad3ce3b4d.png)
hence why I thought it had been stripped out.

**Comment by Captainkirkdawson** [comment]
Will look again in a weeks time.

**Comment by Captainkirkdawson** [comment]
I have confirmed we do NOT record the email address for the credit person. Trivial to store it. But @PatReynolds  @richpomfret  given all the issues should we now store it

**Comment by richpomfret** [comment]
Agreed. Although if we do store it, we need to ensure this is explicitly communicated and permission is given to do so (where-ever that might occur in the process).

**Comment by Captainkirkdawson** [comment]
Agreed to what? It was a question.

We have no means of ensuring  "explicitly communicated and permission is given to do so".

The fields in questions refer to the transcriber saying person Jane Doe at doe@xxx.com should also be given credit for the transcription or it could be Sussex Records Office  at RO@sussex.org.uk should also be given credit for the transcription.

**Comment by Captainkirkdawson** [comment]
Have changed story name to reflect what is actually the current question.
Given the GDPR I am of the opinion we should NOT store the credit email address

**Comment by PatReynolds** [comment]
We don't need explicit permission to store the email address of the person or body who has provided access to images/originals, as this is legitimate business use.  We do need to store contact details _somewhere_ for such persons/bodies, if they are not easily findable and identifiable (West Sussex Record Office is, West Wittering Methodist Circuit is, John Smith isn't). If the fourth field of the header is held confidentially - visible to those who need to know this information - then it can remain in use.  Looking at the record for the marriage of Richard and Ruth Alcock 17 Dec 1716, I can see a credit name, but no details.  Looking at the page for Society of Friends (Quaker) of Besthorpe in Nottinghamshire there is no credit name (and no details).  I've not been able to pick up any pages for churches with a credit name here.

**Comment by richpomfret** [comment]
Closing - the data is there if we need it.
