### ISSUE TITLE
Upload failure to image server

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1411]
EricD has reported that the upload of images is failing with the message
Image Server Error. This is a general error message when the http message is malformed in some unspecified manner. The message coming into the server is extremely long
upload_return?register=5a90505bf493fd0d70450e81&folder_name=Lancaster%20Mount%20Street%20Congregational%20Chapel%20PR&image_server_group=5aa665dff493fd14469ab40c&files_exist=%20&files_uploaded=LAN-Lancaster_MountStreetCongregational-BA-1760-1857_001.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_001a.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_002.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_003.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_055.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_057.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_058.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_059.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_060.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_061.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_062.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_063.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_064.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_065.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_066.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_067.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_068.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_069.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_070.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_071.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_072.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_073.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_074.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_075.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_077.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_078.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_079.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_097.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1700.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1759.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1760.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1762.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1770.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1772.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1777.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1786.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1791.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1794.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1795.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1796.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1799.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1802.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1805.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1807.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1809.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1814.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1819.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1823.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1825.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1828.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1831.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1833.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1835.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1837.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1838.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1839.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1840.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1841.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1843.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1844.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1846.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1847.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1848.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1849.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1850.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1851.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1852.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1853.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1855.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_1856.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1760.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1786.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1789.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1794.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1795.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1796.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1796a.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1797.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1799.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1799a.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1800.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1800a.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1801.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1802.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1803.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1803a.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1804.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1804a.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1805.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1805a.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1807.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1808.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1809.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1810.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1812.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1813.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1815.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1816.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1816a.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1817.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1818.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1819.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1820.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1821.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1822.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1823.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1823a.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1824.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1824a.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1825.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1827.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1828.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1829.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1830.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1831.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1832.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1833.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1833a.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1834.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1835.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1836.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1836a.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_b1837.jpg/%20LAN-Lancaster_MountStreetCongregational-BA-1760-1857_blank.jpg

**Comment by Captainkirkdawson** [comment]
Added a check to limit the total number of characters for all files being uploaded to 1500 characters

**Comment by edickens** [comment]
Now working well.
I upload 10 images at a time.  I can do a maximum of 15, but 10 is easier to remember where I have got to.
When an IG is completely uploaded, I then have to check the number of uploaded images against those held on my computer to make sure that I have not missed any.  So far no mistakes.
I have about 7,000 images (5GB) waiting to be uploaded, so this is going to be a long job.  And I can't just set a batch running and leave it to work as each group of 10 only takes a few seconds.

**Comment by Captainkirkdawson** [comment]
Did you encounter the limit?

**Comment by edickens** [comment]
Yes.  And that did not create a problem.  I just had to select a smaller range to upload.  That is how I worked out how many I could upload at a time.
I have now cleared all the "Error" reports from Bev's log.
