### ISSUE TITLE
Create text for home page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1414]
Brief text to introduce the members' area

**Comment by Captainkirkdawson** [comment]
The page is on refinery at

https://www.freereg.org.uk/cms/system-message-texts/information-for-members

**Comment by Captainkirkdawson** [comment]
Also inserted on that page are the messages waiting block and something on open data which gets its text from somewhere else
You have 11 messages.
Open Data: Your transcriptions currently will not be shared as Open Data. To choose to make your transcriptions Open, please click here and update your Transcription Agreement status. To find out more about Open Data, and what signing the transcription agreement means, please visit: http://www.freeukgenealogy.org.uk/about/opendata/

If you have any questions about transcribing or the documents linked below, please ask us. We are sorry that this is a google group, as we know some of you would prefer not to use this tool. If you are aware of an alternative, or prefer not to sign into the group, please let us know (info@freeukgenealogy.org.uk).

**Comment by richpomfret** [comment]
Closing, should be FreeCEN.
