### ISSUE TITLE
Document Allow dash (-) in Sex field for Baptisms

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1417]
Some transcripts show unknown sex of baptised child with a dash (-). This used to be allowed in FR1 but is not now in FR. We need to add it as an allowable entry for Sex.

**Comment by Captainkirkdawson** [comment]
Have cleaned up the tables. Note the variations are based on what was found in the F1 entries at conversion time
  M is displayed for entries of "M","M." ,"SON","MALE","MM","SON OF"
  F is displayed for entries of "F","FF","FFF","FM","F.","FEMALE","DAUGHTER","WIFE","DAUGHTER OF","DAU", "DAU OF"
 M? is displayed for entries of "M?","SON?","[M]" ,"MF"
 F ? is displayed for entries of "F?", "DAU?"
The following are displayed as is "?", "-", "*","_","??",""," "
Other UCF characters are displayed as ?
Anything else is invalid

**Comment by Captainkirkdawson** [comment]
Deployed to test2 for testing

**Comment by SteveBiggs** [comment]
All variations tested OK except a space " " was displayed as nothing "", but that's not a problem.

**Comment by AlOneill** [comment]
I have 2 questions:
* do we need to alter the guidance to transcribers?
* if we display "Wife" as "F", are we not losing/hiding information?

**Comment by SteveBiggs** [comment]
That's a good point Alison, but in the new flexible csv we have a new field in baptisms called Relationship to provide for this.

Yes the help notes will need updating.

**Comment by Captainkirkdawson** [comment]
Have deployed to production

**Comment by SteveBiggs** [comment]
Tested and verified as good.

**Comment by AlOneill** [comment]
Have updated the help, on production, 
https://www.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers#bapH

Please note that I have referred to a '-' by its proper name, a **hyphen**. A dash is something else, either an en-dash (–) or an em-dash (—): we do not allow either of these because of possible encoding issues.

**Comment by SteveBiggs** [comment]
Looks good.
