### ISSUE TITLE
Add new burial fields

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1418]
Provide support for the following new fields in a burial record.

Date of death	(To be used if date of burial is absent)
Burial person's title
Male relative's title
Female relative surname (To be added to search_names)
Female relative's title
Cause of death
Grave number
Place of death
Burial memorial coordinates

**Comment by Sherlock21** [comment]
Titles etc:
I would think it easier to have all positioned at the same place, as you suggest.

Constrained or not: 
Are these titles likely to form a key part of a search in future?
IF so, can you rely on everyone using the same abbreviations? I doubt it.
SO my view would be to have a lookup list with an easy route to add others to that list as necessary, without loads of extra effort by yourselves if that's not too late to fit in?

**Comment by Sherlock21** [comment]
Do we try and cater for people who have more than one of each?

i.e. Major General Sir Willm.  Smith jnr
or Rt. Hon Dr Mary Williams L.D.

**Comment by Captainkirkdawson** [comment]
There are no proposals to make the title a searchable field. It was considered and rejected.
TWYS argues for go constraints. Multiple titles would require an array of elements for the field if constrained. If unconstrained it can be whatever is in the entry this would support Major General Sir  Jnr and Rt. Hon Dr  L.D.

**Comment by SteveBiggs** [comment]
The default order for titles can be after.

I think the titles will have to be unconstrained because there are so many possible values that it is inevitable some would be missed in a constrained list. WinFreeREG could have a lookup list that users can add to as required, but to allow for multiple titles as Eric lists would require an almost infinite lookup list. I suggest it is kept as free form entry.

**Comment by Captainkirkdawson** [comment]
Code has been developed; including  using date of death if date of burial is absent or in different period and searches on family members will include female relative surname .
Waiting to deploy to test2

**Comment by Captainkirkdawson** [comment]
Deployed to test3 ans @Sherlock21 asked to review

**Comment by Captainkirkdawson** [comment]
redeployed to test2

**Comment by Captainkirkdawson** [comment]
Initial testing is now completed by Ericb. Stories written to reflect findings.
