### ISSUE TITLE
Add new marriage fields

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1419]
Provide support for the following new fields in a marriage record.

Contract date
Groom's title
Groom marked
Bride's title
Bride marked
Bride's father's title
Bride's mother's first name
Bride's mother's surname
Bride's mother's title
Groom's father's title
Groom's mother's first name
Groom's mother's surname
Groom's mother's title
Licence
Relationship (Bride/Groom prior)
Extend number of witnesses to 8 persons

**Comment by Captainkirkdawson** [comment]
'register_entry_number','marriage_date','contract_date','marriage_by_licence','groom_forename','groom_surname','groom_title','groom_age','groom_parish','groom_condition','groom_occupation','groom_abode','groom_marked','groom_father_forename','groom_father_surname','groom_father_occupation','groom_mother_forename','groom_mother_surname','groom_mother_title','groom_mother_occupation','bride_forename','bride_surname','bride_title','bride_age','bride_parish','bride_condition','bride_occupation','bride_abode','bride_marked','bride_father_forename','bride_father_surname','bride_father_occupation','bride_father_title','bride_mother_forename','bride_mother_surname','bride_mother_title','bride_mother_occupation','witness1_surname','witness2_forename','witness2_surname','witness3_forename','witness3_surname','witness4_forename','witness4_surname','witness5_forename','witness5_surname','witness6_forename','witness6_surname','witness7_forename','witness7_surname','witness8_forename','witness8_surname'

**Comment by Sherlock21** [comment]
Is there one name fields missing?
witness1_forename

sorry its a late comment!

**Comment by Captainkirkdawson** [comment]
TY @Sherlock21

**Comment by Captainkirkdawson** [comment]
Code has been developed; including using date of marriage contract if date of marriage is absent or in different period and searches on family members will include female relative surnames .
Waiting to deploy to test2

**Comment by Captainkirkdawson** [comment]
There was a proposal for the relationship between the groom and bride eg cousins or something similar ie the bride and groom were related prior to marriage.
I forgot it. 
Is it needed? Does it truly warrant its own field? If so will add

**Comment by SteveBiggs** [comment]
It must be extremely rare - I've never come across a case with relationship prior to marriage. I would have thought it could go in the notes.

**Comment by Captainkirkdawson** [comment]
It was originally proposed as some catholic records contain it.
Perhaps we need confirmation from the original proponent but seems likely a good notes entry

**Comment by PatReynolds** [comment]
I was the original proponent - agree, it is a good notes entry.

**Comment by Captainkirkdawson** [comment]
Deployed to test3 ans @Sherlock21 asked to review

**Comment by Captainkirkdawson** [comment]
redeployed to test2

**Comment by Captainkirkdawson** [comment]
Initial testing is now completed by Ericb. Stories written to reflect findings.
