### ISSUE TITLE
Edit help materials for language and consistency

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#142]
As a contributor I want the help files to be consistent and to use correct language so that I can learn about FreeREG effectively and not get confused.

ACCEPTANCE CRITERIA

 - I can read the same term wherever it appears and see that it is used to mean the same thing.
 - The language used throughout the documentation is consistent.

**Comment by PatReynolds** [comment]
We do need to agree a standard terms (and create a glossary with for X see Y so that people searching under the wrong term still get to the answer) and a style guide - do you all have access to the style guide on the FreeUKgen website?  We have a potential volunteer, maybe two, and the new Engagement Co-ordinator can help too.

**Comment by Captainkirkdawson** [comment]
What do you mean "style guide on FreeUKGEN website". Not aware of any accessible style guide.
FR2 uses the same basic styling as FreeUKGEN and all styles are available for pages placed onto Refinery which is used to deliver the output of pages to the user
