### ISSUE TITLE
Add new baptism fields

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1420]
Provide support for the following new fields in a baptism record.

Confirmation date
Person's surname (Add to search)
Person's relationship
Person's title
Person's condition
Person's status
Person's occupation
Person's age
Person's parish of birth
Person's county of birth
Father's title
Father's  abode
Father's parish
Mother's title
Mother's abode
Mother's condition at marriage
Mother's parish before marriage
Mother's occupation
Private baptism
Witness or Godparent Forename (Up to 8) (Add to search)
Witness or Godparent Surname (Up to 8) (Add to search)

**Comment by Sherlock21** [comment]
K

I notice a little typo -but maybe by now you has actually picked it up:-

Mother's ABODE

And Whats the value in the Private Baptism field please? blank and Yes?

or what

**Comment by Captainkirkdawson** [comment]
Not yet coded but likely will be Y Yes or yes; blank for no

**Comment by Captainkirkdawson** [comment]
#,DEF
chapman_code,place_name,church_name,register_type,register_entry_number,birth_date,baptism_date,confirmation_date,received_into_church_date,person_forename,person_surname,person_title,person_age,person_relationship,person_sex,person_abode,person_condition,person_status,person_occupation,person_place_birth,person_county_birth,father_forename,father_surname,father_title,father_abode,father_occupation,father_place,father_county,mother_forename,mother_surname,mother_title,mother_abode,mother_condition_prior_to_marriage,mother_place_prior_to_marriage,mother_county_prior_to_marriage,mother_occupation,private_baptism,witness1_forename,witness1_surname,witness2_forename,witness2_surname,witness3_forename,witness3_surname,witness4_forename,witness4_surname,witness5_forename,witness5_surname,witness6_forename,witness6_surname,witness7_forename,witness7_surname,witness8_forename,witness8_surname,notes,notes_from_transcriber,film,film_number,image_file_name

**Comment by Captainkirkdawson** [comment]
Code has been developed; including using date of confirmation date or received into church date if date of baptism and date of birth are absent or in different period and searches on person surname or person male relative surname.

Waiting to deploy to test2

**Comment by SteveBiggs** [comment]
Search should also be on female relative surname.

**Comment by Captainkirkdawson** [comment]
Already did

**Comment by Captainkirkdawson** [comment]
Deployed to test3 ans @Sherlock21 asked to review

**Comment by Captainkirkdawson** [comment]
There is no attachment; please send to me off line
Others should comment on usage of fields and collate those for inclusion in the documentation.
" how do you get Pre- Marriage data into Baptism files like this? - is that an oversight. Cols AG to AI: in my file" do not understand question. We are simply transcribing the baptism record. Apparently catholic baptisms may include such prior information.
But the initial test I asked for was that the original structures still worked.

My email to you was
I need an extended period of your time to test the mods to the system to support the new entry fields.

They are running on test3.

Please work at this systematically.  First with baptisms, then burials and finally marriages.

For each test that the current uploads, replaces, edits  and downloads for an original file ie NO #,DEF

Then for each test that the you can upload, replace ,edit and downloads with any or all of the new fields. 

Edits can involve fields in the file and new fields not in the file. In the latter case the new column header is added 

Possible fields in the baptism Story 1420

Possible fields in the burial Story 1418

Possible fields in the marriage Story 1419

Restrictions chapman_code,place_name,church_name MUST be present.  register_type can be there IF NOT it is expected as part of the church as currently. 

Work with a few records in a file.

TAKE YOUR TIME AND DOCUMENT WELL PLEASE

This is a BIG ask I know

PS It has taken me nearly a month of work to code these changes and has involved many ancillary changes both to displays and support code as well as to the processor.

So if you take a week or more on each type that is fine.

**Comment by SteveBiggs** [comment]
EricB, the reason for the additional fields is to capture data from the original source that doesn't fit in one of the existing fields. We should not change the way we currently enter data if it fits within the current fields. So your example of abode - if there is a single abode for the entry, then enter it in the person's abode (i.e. baptisee for baptism). Only add the others' abodes if the register states them explicitly.

If the Abode is the same as the Place of the Event, I would not enter anything as it is the assumed default place.

**Comment by Sherlock21** [comment]
Testing held, pending info from Kirk at=s to why my test1 failed with the msg: Sorry something seems to have gone wrong..
Report Details sent in email direct to Kirk.

**Comment by Sherlock21** [comment]
How is  one supposed to correct typo errors now? there used to be a pencil icon to click,  that unlocked the Edit mode - but no longer.

in post above: for at=s please read: as.

**Comment by SteveBiggs** [comment]
There is a drop down option top right:
![untitled](https://user-images.githubusercontent.com/25303607/39519026-0b321852-4dfd-11e8-9f35-194d928432ab.png)

**Comment by Sherlock21** [comment]
I found that, but it did not respond to Edit. ( on Safari")

and neither did it work on Opera.
thanks for trying to help though.

**Comment by SteveBiggs** [comment]
Very odd. Just tried it on Windows/Chrome and it works as expected.

**Comment by Captainkirkdawson** [comment]
@Sherlock21 crash issue fixed Caused by an interaction of the new witness fields with old files. Please repeat and continue

**Comment by Captainkirkdawson** [comment]
redeployed to test2

**Comment by Captainkirkdawson** [comment]
Initial testing is now completed by Ericb. Stories written to reflect findings.
