### ISSUE TITLE
Add new common fields

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1424]
Provide support for the following new fields in a all record types

Register Type (Separate field instead of combined in church name).
Notes from Transcriber
Image File Name (As used in Image Server)

**Comment by Captainkirkdawson** [comment]
Fields added. Need to generalize the entry show. Need to link image if open data

**Comment by Captainkirkdawson** [comment]
Have generalized the entry display code.
@SteveBiggs  do we show all fields even if they are entry? That is the current practice for members since they field might have had to have something and the empty field acts as a reminder. (The research show only has fields with data but that is appropriate). It does mean that as we add fields there will be more and more empty fields in the display

**Comment by Captainkirkdawson** [comment]
Internal viewing of image coded. Need to code researcher component. Need to check update record computation in light of DEF and extra fields.

**Comment by SteveBiggs** [comment]
Perhaps the 'SH' view for a record could only show those with data, but if 'Edit' is selected then all possible fields are available to edit? It should be obvious that there are more fields available for data, so having the reminder of empty fields would not be necessary.

**Comment by Captainkirkdawson** [comment]
Generalize edit code

**Comment by Captainkirkdawson** [comment]
TY Steve

**Comment by SteveBiggs** [comment]
This is fine. If a transcriber wants to add new fields, they can download the file, add DEF, etc, and then replace the file on FR.

**Comment by Captainkirkdawson** [comment]
Needs to be deployed to test2 for evaluation

**Comment by Captainkirkdawson** [comment]
Deployed to test3 ans @Sherlock21 asked to review

**Comment by Captainkirkdawson** [comment]
redeployed to test2

**Comment by Captainkirkdawson** [comment]
Initial testing is now completed by Ericb. Stories written to reflect findings.
