### ISSUE TITLE
Display and make editable the secondary_role

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1426]
Priority (0 6 3 6) 15

We introduced a secondary_role for a userid.
This is invisible and has to be set in the database.
We should add it to the display of a userid and make it editable. 
We also need  to add it to the display of roles. also

**Comment by smrr723** [comment]
Quick question for you @Captainkirkdawson - will there ever be a case where we have to assign more than one secondary_role to a user?  secondary_role is currently stored as an array, as opposed to the person_role being a string, so I assume this was the reason for the difference?

I'm just wondering whether I need to give the ability to select multiple secondary roles, or just one.

**Comment by Vino-S** [comment]
Hi @smrr723 ,
A user can have multiple secondary roles, that is the reason I had created it as an Array field.
However the person_role field describes the primary role of User so it has been kept as String field.
We do have users with multiple secondary role in our project.

**Comment by smrr723** [comment]
Ok - thanks for confirming @Vino-S.

**Comment by smrr723** [comment]
on Test3 now ready for testing, with Issue #1456

**Comment by Captainkirkdawson** [comment]
@smrr723  could you give me a hint as to how we get access to this capability please

**Comment by Captainkirkdawson** [comment]
Ah; I was expecting an option that displayed those userids with a secondary role

**Comment by SteveBiggs** [comment]
Looks good - and it shows Jo Summerfield's secondary role of Volunteer Coord.

**Comment by smrr723** [comment]
Thanks @SteveBiggs
