### ISSUE TITLE
Server upgrades and implications

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1430]
Lemon has commenced a systematic update of the server software (Not the mongodb servers) that leads to an update to both passenger and ruby. These change require an update to the rails version and an update of a number of gems used by the applications.
This update was effected by a hard code change to the Gemfile on vervet.
I have created a branch Rails_4_2_8 which introduces those changes. This is the branch running on test3
When lemon proceeds to the update of the production servers (Week of 16 April) we will need to merge that branch into master so that lemon can update our applications appropriately.
We also need to take care over our branch and merge activities during this period to ensure all relevant changes are made and in the correct order.
There is a software_update branch created as part of #1386 that reflects the update of rails, refinerycms, devise, mongo and mongoid and their support gems. This is currently running on test2

**Comment by richpomfret** [comment]
Need to also review this on FC. @Vino-S to review (perhaps with Ben?).

**Comment by lemon-ukgen** [comment]
Thanks @Captainkirkdawson. Can the 4_2_8 branch be merged and deployed in advanced? (ie: does it run on Rails 4.2.6 ok?)

If not, perhaps it can be merged on master prior to the work, and during the OS upgrade we either

* I co-ordinate with you (and others?) to update the checkout on the servers when Ruby is upgraded

or

* I do update the checkout on the servers myself

We can use HAProxy to remove each server in turn from FreeREG2, FreeCEN2 production. I suggest we do this for the first production server at least.

**Comment by Captainkirkdawson** [comment]
master and freecen_parsing updated on Github

**Comment by Captainkirkdawson** [comment]
lemon has completed all of the server upgrades and they are all working as expected.
