### ISSUE TITLE
Online edits and flexible csv

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1434]
@SteveBiggs We addressed the matter partially when discussing what to do when doing online edits to standard files.
There we concluded that standard files would stay as standard files.
But now we need to consider an on-line edit that wants to add a field that is not in the original set of fields that were defined in the DEF for the file. Do we permit the addition and modify the DEF or do we not permit additions to the DEF

**Comment by SteveBiggs** [comment]
Hmm. I think if a file already using flexible csv is edited on-line, we have to allow extra fields to be added, but this will make on-line editing somewhat more complex.

**Comment by Captainkirkdawson** [comment]
Actually adding a field into the DEF will be easier than disabling a field in the edit display.

I don't think it will happen often but we have to deal with the situation. If we do not then a download will lose the new field

**Comment by edickens** [comment]
I think you should just not allow a field DEF to be deleted.  It should never be necessary, and if an entry has the field content removed, the empty field can stay.

**Comment by Captainkirkdawson** [comment]
There is no suggestion of a deletion. The requirement was do we add if a
new field is entered on_line

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Code written and tested. Awaiting deployment to test

**Comment by Captainkirkdawson** [comment]
Deployed to test3 ans @Sherlock21 asked to review

**Comment by Captainkirkdawson** [comment]
redeployed to test2

**Comment by Captainkirkdawson** [comment]
Incorporated as part of overall testing. May be closed
