### ISSUE TITLE
`search_id` should not be required to view record.

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#1435]
Currently, if a user bookmarks a record they have found, they will store a URL of the form `http://freereg.org.uk/search_records/58ea2b94a020dd02bffac8ec?search_id=5ad110b5a020dd61f05d321c&ucf=false`.  Of the parameters in this URL, 
* the initial segment (`58ea2b94a020dd02bffac8ec`) is needed to retrieve the record they have bookmarked, but
* the following parameters (`search_id=5ad110b5a020dd61f05d321c&ucf=false`) are needed to allow them to browse back and forth within a search query result listing.

If the user removes the `search_id` and `ucf` parameters from the link (or if the records those objects refer to expire), their link will fall afoul of the `show_value_check` method in `search_records_controller.rb`, and they will be unable to retrieve the record.  This makes bookmarking non-permanent, and may hinder #1123.

I would like to consider removing this check and presenting the user a stripped-down (and possibly apologetic) view of the record when they are visiting an old bookmark, suppressing any UI features that depend on `search_id`, rather than redirecting them to the new search screen.

I'm not 100% sure this is the correct behavior, however.

**Comment by Captainkirkdawson** [comment]
But the show depends upon the search_id to navigate back and forth when reviewing records retrieved by the search and to revise the search before any attempt i made to save any specific record.
The show_value_check is used to provide a meaning error message should the record id be invalid. This happens frequently and helps us deal with bots.
Agreed that saving a url is problematic as the search_id is deleted after 60 days.
Personally I believe any researcher should take a copy in print csv or json format and store that rather than relying on a url which is always likely to be problematic.

**Comment by PatReynolds** [comment]
@benwbrum is this needed for permanent urls?

**Comment by benwbrum** [comment]
This is needed for permanent URLs, as (at a minimum) it gets us over the problem of URLs expiring when the search query record is deleted.

**Comment by PatReynolds** [comment]
If show_value_check method in search_records_controller.rb is removed, will it prevent the search_id  URL being used for navigation?  Will it have any other effects?

**Comment by Captainkirkdawson** [comment]
If eliminated without instituting an equivalent capability then researchers will start experiencing system crashes again and we will have to expend resources into why are we getting system crashes. bots are forever executing  incorrectly formed searches and search record displays.

**Comment by benwbrum** [comment]
I am modifying `show_value_check` to be tolerant of bad or missing `search_id` parameters, not eliminating it.

**Comment by benwbrum** [comment]
Here is an example of how we display the search record if there is n
![mv_screenshot](https://user-images.githubusercontent.com/199961/41045165-68e59038-696d-11e8-9249-112866e9edd1.png)

**Comment by Captainkirkdawson** [comment]
Is your image deliberately cut off to have only 3 fields? If not the record is missing

**Comment by richpomfret** [comment]
Question over how readable the options are (which may not be an issue) and suggestion to have a report error button at the bottom.

**Comment by benwbrum** [comment]
Sorry -- that was an artifact of my screen resolution.  Here's the whole page:
![mv_screenshot_whole](https://user-images.githubusercontent.com/199961/41049846-6fccaa6c-6977-11e8-9ad9-52d7ae8e8fb6.png)

**Comment by benwbrum** [comment]
Ben to move the button and deploy to `test3`

**Comment by Captainkirkdawson** [comment]
@benwbrum master already has changes to the detail record page layout and buttons with their text, Please no NOT change these.

**Comment by Captainkirkdawson** [comment]
![detail.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46ec918e228b8febc3abaf51ab57f5973d047d317c57a6287180ba71eb1a2b560d5a4eae41585e47a9f98a7db4aa2e32db025fb28c341521842f1bbeb98a15be04b9228b4f8cb5b5884bc2e12f68.JPG)

**Comment by richpomfret** [comment]
@benwbrum can you comment?

**Comment by benwbrum** [comment]
Sorry for the delay.  Yes, the screenshot was deliberately cropped, since the only part of the screen I changed with this work was the navigation links.

**Comment by richpomfret** [comment]
On TEST2.

**Comment by richpomfret** [comment]
Ready for deplpyment

**Comment by Captainkirkdawson** [comment]
@benwbrum  This is what is now displayed
https://test2.freereg.org.uk/search_records/58184368e93790eb7f7955d5/ann-crack-daniel-cranness-marriage-norfolk-wymondham-1783?search_id=5c5b1d7fe937904a6b77e9a3&ucf=false

**Comment by richpomfret** [comment]
I'll take a look at this - we have a sep story for removing optional parameters.

**Comment by richpomfret** [comment]
@benwbrum have we tackled Kirk's point as part of the sep story?

**Comment by benwbrum** [comment]
Kirk's point is addressed in #1854, so I think this is ready to be merged.

**Comment by Captainkirkdawson** [comment]
@benwbrum Having looked at the code integration of this branch with the current master I have concluded that the better solution is to use the search_id from the session parameter as well as the ucf parameter so that neither are expected in the url from the get go this will eliminate the need for special handling using the show value check; we will still need that check for a valid search record id.
Hence I suggest this pull request be closed and that we instead focus on story #1854 which we raised back in February.
