### ISSUE TITLE
Create Image Source is not adding the Register Type

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1436]

**Comment by edickens** [comment]
When a new set of images is received for uploading, a new Image Source record is created.  This creates a folder on the image server into which all images for this County/Place/Church/Register Type will go.  But the register type is not being added to the folder name.
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8318b500bf22884780b6ba8e4dc3ed3837aa.JPG)
So if images for a different register type are received for this same County/Place/Church there will be a duplication of the folder name and it will not be possible to create the folder.
I think this needs fixing urgently, but no retrospective action is needed.

**Comment by Captainkirkdawson** [comment]
The register type is added to the folder name IF IT EXISTS.

If you create a folder for a register that has an unspecified register type then a blank will be added to the folder name and you will not see it.

You can avoid this by always changing the Unspecified register type to what it should be before creating the image server source.

We could also decline to create a folder for an unspecified register type

**Comment by Captainkirkdawson** [comment]
Have added a check so we will not create a folder for an unspecified register type

**Comment by edickens** [comment]
Sorry Kirk.  I missed that.  Leave it as it is and do not put in the check.  This story can be closed.  It is not a problem.

**Comment by Captainkirkdawson** [comment]
Already done

**Comment by edickens** [comment]
In which case leave it.  People should not be uploading against Unspecified.  We want to get rid of them.
