### ISSUE TITLE
Only show counties with images to transcribe in the RAP Report

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1440]
E0U3 P8 C8@ P19

**Comment by edickens** [comment]
At present all counties come up:-
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8316b500bf228f4f80bebd8f45c1ed3f37aa.JPG)
I can see transcribers getting very frustrated looking at a county to find that there are no images.  So only list counties that have Unallocated Image Groups.
This is a CC function as it is determined by IGs set to Unallocated.  SCs have a function to say that they are looking for transcribers, but that is different because it means that they are wiling to train, whereas a county with images for transcribing might not be on the list of those wanting to train, but would accept experienced transcribers. 
The pick-list under Volunteering should stay the same as it is for SCs willing to train.

**Comment by Captainkirkdawson** [comment]
Bev has coded a change. Running in test3

**Comment by edickens** [comment]
Works.
TY
E

**Comment by Captainkirkdawson** [comment]
Isn't this finished

**Comment by edickens** [comment]
Yes.  I think so.  There are 61 folders with images on the image server, and 43 counties on the list to choose from under Assignments.  The difference should be that these counties have had all their images transcribed, but it may be that they are not yet set as Unallocated.
My only comment is that the sequence is not in Chapman Code order:-
![capture](https://user-images.githubusercontent.com/8876165/48829873-3d44c200-ed6b-11e8-832e-e82870ab922a.JPG)

**Comment by edickens** [comment]
Those counties are still like this at the bottom of the list.
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8318b500bf248c4f80b3bb8a48c5ef3c37aa.JPG)
Waiting deployment?

**Comment by PatReynolds** [comment]
Foiund this because I'd written another story down incorrectly - moving to needs review - is this now fixed @edickens

**Comment by edickens** [comment]
Yes.  But comment above of 21 November 2018 is not fixed.  Sequence of counties has some at the bottom out of sequence.
