### ISSUE TITLE
Write help documentation for the new fields.

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1442]
Priority (2 3 6 3) 14

We need to document the new fields for the transcriber.

Needs #1371

**Comment by Captainkirkdawson** [comment]
@AlOneill seems like I am running into a problem with the page being too long to store in the mysql database. May have to split the page into sub pages.

**Comment by AlOneill** [comment]
No worries — separate sub-pages are fine — at least to start with. 

I am thinking that there will be some sense in treating fields that are essentially the same, like all the _surname fields, in one entry. But let me think about that some more. When I suggested something similar (aggregating field descriptions) a couple of years ago, no-one seemed too keen, but given the sheer number of fields now available, and the increased duplication of information, a more elegant solution seems sensible.

**Comment by Sherlock21** [comment]
I am inclined to agree with Kirk. If the fields behave the same way as each other, then no point in yards of text being repeated. The user has to be credited with some mental dexterity after all.

**Comment by Captainkirkdawson** [comment]
@Sherlock21 it was a suggestion from @AlOneill not me.

I had definitely been inclined to follow that suggestion for the common fields.

However I seem to have run into a size limitation that may force a different solution.

**Comment by Captainkirkdawson** [comment]
A first draft of the extended baptism fields document
https://test3.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers/extended-baptism-fields-draft#baptisms

**Comment by AlOneill** [comment]
@Captainkirkdawson Thanks.

To make for more pleasant reading, the markup needs a bit of an overhaul — I will need to do this offline, in a proper editor. When I take a copy of the page, probably in the next few days, I will leave a note at the top warning that any edits made in Refinery will be overwritten when I paste in the offline edits. If there is no such warning present, then you may edit freely. (Please let me know if that strategy looks ill-thought-out in any way.)

**Comment by Captainkirkdawson** [comment]
@AlOneill have added your styling to the pages

**Comment by AlOneill** [comment]
@Captainkirkdawson Thanks. Still a couple of issues — will solve offline.

**Comment by Captainkirkdawson** [comment]
Have completed marriages

**Comment by Captainkirkdawson** [comment]
Have completed burials

**Comment by Captainkirkdawson** [comment]
@SteveBiggs @edickens  @Sherlock21 

The 4 new flexible csv format and the extended field pages are drafted.

@AlOneill is editing styling and formatting

https://test3.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers/flexible-csv-format-draft

https://test3.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers/extended-baptism-fields-draft

https://test3.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers/extended-marriage-fields-draft

https://test3.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers/extended-burial-fields-draft

**Comment by AlOneill** [comment]
Question: are the 2 systems, flexible and fixed, going to be used alongside each other, or does flexible replace fixed?

**Comment by Captainkirkdawson** [comment]
@AlOneill they can and will coexist. BUT once a batch uses flexible it cannot go back

**Comment by AlOneill** [comment]
@Captainkirkdawson Thanks.

Next question: am puzzled by _status field — if _condition field is for marital status, what kind of status goes in the _status field? Standing wrt  'church' ?? (No examples are given in baptisms.)

**Comment by Captainkirkdawson** [comment]
@PatReynolds @SteveBiggs 
Alison raises a breate question. The reason I did not enter an example was I did not understand what the field was all about. Perhaps you can clarify.

https://test3.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers/extended-marriage-fields-draft

**Comment by SteveBiggs** [comment]
Sorry I don't understand the question. Which field are you asking about? Is this in marriages or baptisms?

**Comment by AlOneill** [comment]
@SteveBiggs I was asking about the baptism fields: person_condition and person_status

If person_condition is for recording marital status, then what goes in person_status?

https://test3.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers/extended-baptism-fields-draft#bapQ and following field

**Comment by SteveBiggs** [comment]
Person status - e.g. Illegitimate, Twin, etc.

**Comment by AlOneill** [comment]
@SteveBiggs So, if we describe the field contents as  anything to do with the person's status in their family, does that about cover it?

**Comment by SteveBiggs** [comment]
Yes that should work, and give the examples.

**Comment by Captainkirkdawson** [comment]
Drafts have been updated

**Comment by AlOneill** [comment]
Still refining the wording &c. to be more user-friendly.

I have some doubts/queries about some of the fields:
* I have assumed that *some* dates require an entry (even if that is only a best-guess year), whereas others do not: if any of my assumptions are wrong, please let me know
* The examples for the 3 Notes fields are taken from my transcribing work: if you can improve on these, by suggesting a more common or less obscure entry, then please do so
* The details (Guidance) for groom_condition and bride_condition are not clear — suggestions?

**Comment by SteveBiggs** [comment]
1. My understanding is (@Captainkirkdawson can confirm):
BA requires at least a year in EITHER the baptism or birth date field.
MA requires at least a year in EITHER the marriage or banns date field.
BU requires at least a year in EITHER the burial or death date field.

3. I suggest - "If any additional information is provided, for instance a name or a date, enter this in the Notes field"

**Comment by Captainkirkdawson** [comment]
That is correct

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by AlOneill** [comment]
@SteveBiggs @Captainkirkdawson Thanks — that is kinda what I thought! Now to work on expressing the tricky 'at least in either' concept in friendly terms!!

**Comment by Captainkirkdawson** [comment]
@AlOneill  the links to the 3 header csv files no longer work they die with the error message

The SHA parameter you gave is incorrect

**Comment by AlOneill** [comment]
@Captainkirkdawson Fixed.

**Comment by AlOneill** [comment]
There is no 'date of banns' field unless it's the same as 'date_of_contract'?

And, if 3 dates are offered for banns, do we want the final one?

**Comment by Captainkirkdawson** [comment]
@AlOneill That is because banns would be implemented through a new record type rather than as part of a marriage record. date_of_contract is separate and distinct from dates of banns (and applies only in Scotland I believe)

**Comment by SteveBiggs** [comment]
I still need to define the required fields for the new record type of Banns per #1427

**Comment by AlOneill** [comment]
Thanks.

Have noticed that the place_of_death details are missing from burials: is the 'place' as per our specific usage or can it be any kind of location information such as a farm, body of water, hospital, &c?

**Comment by Captainkirkdawson** [comment]
@AlOneill  good catch. It is general (TWYS) whatever was written in the register

**Comment by Sherlock21** [comment]
An interesting question, AlOneill.
it depends upon whether we wish to make it a searchable  Place or not. If YES, then it need to be a County + PlaceName as in FR already. IF No searching, then you can put what you want.

My view is:  researchers need all the help & clues they can get when trying to find "Strays' - i.e. out of base area events.
Often, when a bride moves away form her birth place, its very hard to find her "New" place name without having as many clues was possible.

But to do this, there needs to be the rules set at the start - else one will get all sorts of unhelpful stuff as you describe above.

**Comment by SteveBiggs** [comment]
@AlOneill the links to the 3 header csv files do not work again - they die with the error message

The SHA parameter you gave is incorrect

**Comment by Captainkirkdawson** [comment]
@AlOneill not the foggiest. I have not touched refinery for some time and certainly not those files.Why are we using the SHA anyway?

**Comment by AlOneill** [comment]
@Captainkirkdawson Can't give a technical answer, just that Refinery complains if there is no SHA as well as if it is 'wrong'. (Apologies if your question was rhetorical!)

The SHA for each has definitely changed since the last fix. When I get a chance, will check whether or not the FC file downloads are still working, FWIW.

**Comment by Captainkirkdawson** [comment]
I have just been able to download the files.
The SHA is a dragonfly requirement nothing really to do with Refinery which uses Dragonfly to display the resources (images and files)

**Comment by SteveBiggs** [comment]
Yes, the links now work again. Thanks.

**Comment by SteveBiggs** [comment]
@AlOneill when do you expect the help documentation to be ready to deploy to production? I would like to get something sent out to transcribers who use spreadsheets so they can start using flexible csv. Thanks.

**Comment by edickens** [comment]
Have just looked at the Test3 Help.  The link to the header rows does not work.  I also think that a comment somewhere near there is needed to say that unwanted columns, and hence field names, can be deleted.  Only those required need to be in this row, and they can be in any sequence.

**Comment by SteveBiggs** [comment]
This information is already in the introduction page:

![image](https://user-images.githubusercontent.com/25303607/44273171-949c3900-a236-11e8-8324-cbcc5c78e842.png)

**Comment by AlOneill** [comment]
Before copying to production, there are a couple of issues:

* Why are the file download links failing every few days?

* How visible do we want these pages to be? In other words, do we want a link to the introductory page in the Transcriber Help menu; or should the only route be via the existing 'Entering data from ...' page; or what?

**Comment by AlOneill** [comment]
Turns out, FreeCEN downloadable files (test2) have also stopped working, with the same message from Dragonfly(?) as on FR. Have not fixed either.

All I can think of is either Refinery is updating the SHA off its own bat, for some reason, or that it is being instructed to do so by something else. Have we set an expiry date on our downloadable files or some-such? — @Captainkirkdawson @smrr723 any ideas?

**Comment by richpomfret** [comment]
Suggestion of moving location (for now) to avoid above issue.

**Comment by richpomfret** [comment]
In answer to the second Q above - Separate link for flexible csv (until we have it supported by WinREG).

**Comment by AlOneill** [comment]
@SteveBiggs Pages re-ordered in Refinery as per: Flexible CSV introductory page now at
https://test3.freereg.org.uk/cms/information-for-transcribers/flexible-csv-format-draft

NB: Some links will not work until I update them.

**Comment by AlOneill** [comment]
@SteveBiggs Links updated on all four pages — E&OE!

The only bar to moving this story to "Needs review" is the repeated failure of the download links: we need a solution.

**Comment by PatReynolds** [comment]
@smrr723 @Captainkirkdawson any idea why the download links are failing?  If no idea / not fixable, I suggest they are uploaded to the F U G website.

**Comment by smrr723** [comment]
Searching for "The SHA parameter you gave is incorrect" shows it's a known issue, but I don't see any single, simple solution.  

@Captainkirkdawson https://github.com/markevans/dragonfly/issues/387#issuecomment-142123474 seems to be the clearest solution I've found but from what I can see in our Gemfile, we should have the highest working version of the `json` gem anyway.

**Comment by Captainkirkdawson** [comment]
@smrr723 As you likely have perhaps perceived I have not the foggiest idea of how to keep the SHA from changing. My solution would be to eliminate it totally and put a straight link to the file and ignore any complaints from dragonfly

**Comment by Captainkirkdawson** [comment]
SHA gets changed by a server restart. Testing a solution

**Comment by Captainkirkdawson** [comment]
@AlOneill  Problem has been fixed by adding a dragonfly secret code to resources. Have sanitized the initialization to use a mongo_config constant rather than hard code. SHA survives a server restart now.

**Comment by SteveBiggs** [comment]
Can we deploy the help info to production now?

**Comment by AlOneill** [comment]
There is an outstanding query about the Notes field — link is to the Baptisms page, but also applies to other record types.

See: https://test3.freereg.org.uk/cms/information-for-transcribers/flexible-csv-format-draft/extended-baptism-fields-draft#bapAN

**Comment by SteveBiggs** [comment]
I would say the answer is no. Leave that comment out as it could cause confusion.

**Comment by AlOneill** [comment]
@Captainkirkdawson Thank you — looks good.

@SteveBiggs Thank you. Will begin clean-up of new pages.

**Comment by AlOneill** [comment]
@Captainkirkdawson The 4 new pages are now ready for syncing, as are the other pages in the (Transcriber) Help section that required menu updates.

Please note that the edit required by #1226 has been done as part of the above.

**Comment by Captainkirkdawson** [comment]
@PatReynolds @richpomfret @lemon-ukgen 

Rather than my doing a one off would it not be far better to use this as an opportunity to have you ans lemon test the syncing task envisaged as part of #1371

**Comment by SteveBiggs** [comment]
When will the sync task be run? We need to get the flexible csv help onto the production site.

**Comment by richpomfret** [comment]
@lemon-ukgen has been given the go-ahead to create the script to automate this. We will try and roll it out over the next sprint.
