### ISSUE TITLE
Log in autofill

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1444]

**Comment by edickens** [comment]
Test2 autofills my UserID and password (hidden), but Test3 and production do not.
I don't think it is my Nortons security that does this.  Is it the same for anyone else?

**Comment by SteveBiggs** [comment]
All servers autofill for me. I use Chrome on Windows 7. I wouldn't think antivirus s/w would prevent autofill working.

**Comment by SteveBiggs** [comment]
I understand what you're asking. All I'm saying is that all 3 websites behave exactly the same for me. They all autofill the userid and password.

**Comment by smrr723** [comment]
Just save the login details for test3 & production in your browser, at the prompt after you login.

**Comment by edickens** [comment]
Thanks for that information.  It must be Nortons which has not asked me to save it.  I have this secure save system.  That is those symbols at the end of each field.
This story can be closed.

**Comment by edickens** [comment]
I've worked it out now!
In Test2 I have only logged into one UserID, whereas in Test3 and Production I have more.  So Nortons has to give me a choice and cannot autofill.
