### ISSUE TITLE
Download as csv with fields that contain a comma in a field

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1446]
A Little snag with this. File attached. The field contents are all moved over to the right by one, compared to the field names - on account of the mis translation of the county name of "Yorkshire, West Riding" where the comma in it is handled as ffield separator .

**Comment by Captainkirkdawson** [comment]
Code to correct this bug has been developed.
It has been added to complete_flexible_csv branch
@Sherlock21  can you please test this. It is only on test2

**Comment by Sherlock21** [comment]
Testing files that have one or more fields containing a comma in the text.
The 2 batches that identified this problem have been  downloaded satisfactorily.
One of them was edited online, and then downloaded again, satisfactory.

An old pre flexi file was downloaded satisfactorily.
A new file was  created, uploaded and then downloaded satisfactorily.

SO in respect of the subject of this bug: I have not found any combination of actions which now repeat the original problem - SO I consider that it is now Resolved.

**Comment by Captainkirkdawson** [comment]
Thank you Eric

Need to think about applying the fix to master so it can be deployed to production which is currently experiencing the bug as wll

**Comment by Captainkirkdawson** [comment]
Code deployed to master
