### ISSUE TITLE
Updating of UserIDs with SC and CC information

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1454]

**Comment by edickens** [comment]
When a County or Syndicate changes Coordinator, or a Syndicate name is changed, the UserID profile is not updated.  I suggest that it does not need to be until the Profile is next viewed.  For example the UserID "KirkDawson" is SC of Oxfordshire, but although it says that he is an SC, it does not list the Syndicate.

**Comment by richpomfret** [comment]
Could be a bug or simply not set-up to update initially. Investigate and fix as appropriate.

**Comment by Captainkirkdawson** [comment]
This is all caused by the continual changing of syndicate names when coordinators are changed. This was never expected in the design and as a result members are not updated

**Comment by edickens** [comment]
Even if we didn't have names, Syndicates might still change.  For example we have "Rest of England", but this will get split up when it grows bigger.  Also, some counties, such as Somerset, have so many transcribers that it is divided into sub groups.  But as a principle I do agree that changes are rare, and we have had very few, even with the names.

**Comment by Captainkirkdawson** [comment]
I misspoke, tried to edit but it appears the edit was lost.
The code does update the userids if there is a name change

**Comment by Captainkirkdawson** [comment]
On my test server
A member of a syndicate prior to a name change
![prioir.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46f886932c8b91ebc3abaf51ab57f5973d047d317c57a6287180ba71eb1a2b560d5a4eae41585e47a9f98a7db4aa2e32db025fb28c341521842f1bbeb98515be04b8288d498cbebd8d44c8ef2f68.PNG)
I change the name
![change.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46eb9c9b2d8586ebc3abaf51ab57f5973d047d317c57a6287180ba71eb1a2b560d5a4eae41585e47a9f98a7db4aa2e32db025fb28c341521842f1bbeb98515be04b8288d498cbeb98f4ac5ec2f68.PNG)
The same user after the change
![after.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46e9928e2690c1e5cdf9ad4cae58f3806b1c65267a01a02a75dcba7ce7122c035a5f4cac41595c11fcfadf39baa47e21d40854b088270a36d43703adbf881eba03b2268d468dbeba8b4dc8fa70.PNG)
All other users in the syndicate have the new name

**Comment by edickens** [comment]
TY

**Comment by Captainkirkdawson** [comment]
Based on all my testing I can find no situation in which a syndicate name change is not promulgated to all members of the syndicate.
There is no promulgation of a syndicate coordinator change if the syndicate name remains unchanged as the syndicate coordinator is not stored in the userid.
There is no promulgation of a county coordinator change or a county name change as neither is stored in the userid.
Hence I believe this should be closed.

**Comment by edickens** [comment]
Yes.  Close this.  Many more important things.
