### ISSUE TITLE
Adsense banner ads don't appear below 950px

### ISSUE THREAD

**Issue by smrr723** [FreeUKGen/MyopicVicar#1455]
Priority (3 3 7 5) 18
Need to make the adsense banner responsive and add ads for tablet and mobile devices to capture potential ad revenue from these visitors.

**Comment by richpomfret** [comment]
To test and ensure adverts are working/responsive.

**Comment by PatReynolds** [comment]
Adverts 9011588433, 4776188342 and 8870759291 (the three ad versions currently live for FreeREG) are all responsive.  But not showing on my mobile (android) or tablet (android, chrome).

However (looking at the 'about' page, where he html is laid out neatly enough for me to read, I notice that 
      <div class="banner-horz reg_adsense">
              <style>
        .adSenseBanner { width: 320px; height: 100px; text-align: center; margin: auto;}
        @media(min-width: 500px) { .adSenseBanner { width: 728px; height: 90px; text-align: center; margin: auto; } }
        @media(min-width: 800px) { .adSenseBanner { width: 728px; height: 90px; text-align: center; margin: auto; } }
    </style>

is included - perhaps this is constraining the display of the advert?

The line   is also missing (yes, just info, but helps if one cannot remember the numbers, and when we move to individual advert slots for positions, it will help keep track when placing them (for those of us who cannot remember long strings of numbers as easily as we can words).

**Comment by smrr723** [comment]
@PatReynolds you're on the right tracks.

That code is to make the adsense container responsive to page width changes, so if you have ads set to responsive in the Adsense settings, they _should_ auto resize.  Someone has set another property to override the above though, setting display: to 'none' below 950px, so the code above is redundant at the moment.

The changes I had made earlier removed that `display: none` code, which helped slightly but caused the ad to jump off page a little, and not load in some circumstances so haven't made them live on test3 yet. There's a large set of guidelines on making adsense responsive which I'm following here - https://support.google.com/adsense/answer/3213689?hl=en-GB - have to play with it a bit more to get it right.

**Comment by richpomfret** [comment]
@smrr723 is this still in progress or done?

**Comment by smrr723** [comment]
Still in progress but should be finished with it this week.

**Comment by smrr723** [comment]
Banner ads should now show down to 810px (468x60 size) rather than cutting off at 950px.  Will be in production after the update - on test3 for testing.
