### ISSUE TITLE
Add multiple empty witness fields in an edit

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1460]
Currently we offer only 1 additional witness field on an edit. Do we offer up to 8 additional witness fields?

**Comment by SteveBiggs** [comment]
I would suggest yes, up to 8 (total) to line up with the flexible fields.

Steve


Stephen Biggs
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
My only concern is that few baptisms will have a witness and to provide 8 empty fields seems likely to cause negative feedback

**Comment by Sherlock21** [comment]
I am inclined to agree with Kirk. In all the Transcribing that I have done I have not had one Baptism with any 'Witnesses'.

**Comment by SteveBiggs** [comment]
But we must be consistent. Either we reduce the number of allowable BA
witnesses in flexible csv to 1 or allow up to 8 to be added.

Steve


Stephen Biggs
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
Ah I see the miss understanding.
The system permits 8 witnesses and there is no proposal for reducing that.
The edit/create on-line is written on the basis that only 1 new witness will be added at a time. If there are currently no witnesses you are just offered the addition of 1. You can do multiple edits to create the 8 witnesses.
We "could" add all the empty fields in the edit if desired. But there is the downside that in almost all cases of baptisms none will ever be used. 
Remember this is the on-line edit only
