### ISSUE TITLE
Add link to field headers in help

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1462]
The new fields are an increase of 100% over the past. It should be possible to download the field names.

**Comment by Captainkirkdawson** [comment]
Yes, it proposes the download of a template.

**Comment by Captainkirkdawson** [comment]
The field header should be in a logical order

**Comment by Captainkirkdawson** [comment]
Have added the extended fields into the draft of a subsection of the entering data from registers help page called Flexible CSV format and Extended fields.
https://test3.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers/flexible-csv-format-and-extended-fields-draft

**Comment by AlOneill** [comment]
TY.
Baptism and burial files download OK, but marriage file gets a "Not found". Will investigate.

Not straightforward to integrate info on this page with that of parent page: have a half plan which has been simmering for a while and which I hope will bloom as I proceed! (Apologies for mixed metaphor.)

**Comment by AlOneill** [comment]
Refinery > Files offers baptism fields when I attempt to download marriage fields: i.e. the marriage fields file is not there (a big clue is the unexpected matching file sizes).

@Captainkirkdawson Could you please replace the marriage fields file in Refinery? TY.

**Comment by AlOneill** [comment]
Refinery will not allow a `<wbr>` element — it converts it to a XML-style closing tag `<wbr />` which, unlike `<br />`, has no meaning: this empty element has no closing tag in HTML5.
The `<wbr>`element is needed to allow breaking of  field listing which itself has no spaces.

I will open an issue.

**Comment by Captainkirkdawson** [comment]
@AlOneill will fix the marriage download
I had planned as part of #1442 to write the explanation of the new fields into the subsections on baptisms etc in this child page.
In fact I had almost completed the baptism section  (it took 4 hrs) when I realised I needed to change the order and LOST everything I had done! so left it and went for a glass of wine.
Do you want me to do draft the subsections? there are large numbers of new fields to be defined. If so I will recommence

**Comment by AlOneill** [comment]
@Captainkirkdawson Link fine, TY.

That would be very helpful if you draft the subsections. I already have some questions, but will hold fire until I see your draft as that will likely answer a few at least! And do save often :-)

**Comment by Captainkirkdawson** [comment]
The links are in the various pages so this may be closed
