### ISSUE TITLE
Download to follow logical field order

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1463]
When a new field is added it is added at the end of the list of fields.  (There is no system requirement for any specific order) The on line show of a record forces a "logical" order.
The download of the file could follow that order.
The downside is that the uploaded file may use a preferred order from the perspective of the transcriber. This proposal would override the transcribers order!

**Comment by Sherlock21** [comment]
Ah!!
Well: as it is most likely to be the same Transcriber uploading and downloading their own file, is it therefore a better idea:-
To have the standard file header fields in the logical together style ( i.e. title, first name, Surname, condition, Occupation. say, when one downloads the basic header blank. thereafter download a file in the same order as that Transcriber uploaded the fields in originally - as you refer to above?

Then scrap my original suggestion.

**Comment by richpomfret** [comment]
@Captainkirkdawson thoughts on Eric's suggestion?

**Comment by Captainkirkdawson** [comment]
My difficulty is what is logical in one persons mind is different from another person. I prefer to add at the end as then the transcriber knows where it will be. I suspect few will ever add a field on line. So retaining the original order makes more sense to me.

**Comment by Sherlock21** [comment]
I accept that I can shuffle fields into any order that I like. but it would be more sensible to have a standard order In all cases:- County Code, Placename, Church name, Register type. as we do now, and then:- 
EG I would prefer for Baptisms: record number; Subject's first name, Subject's Surname if given, Father's first name; father's surname; father's Title [eg Mr]; mother's first name; Mother's surname; Mother's title [eg Mrs; Other fields, then  Witnesses at the end if any.
And similar for the other types: all the parts of a person's name, kept all together like this.

This is what I mean as: in logical order

**Comment by Captainkirkdawson** [comment]
Opinion of others is required

**Comment by SteveBiggs** [comment]
I have no problem with there being a default order as Eric suggests as a starting point, but if a transcriber changes that order before they upload the file. Any subsequent download of the file must have the fields in the same order as when uploaded, with any additional fields added to the end as Kirk states.

If the transcriber then wants to move the new fields to where they consider logical before they replace the file, that's up to them.

**Comment by Sherlock21** [comment]
I agree with Steve's comment above.

**Comment by Captainkirkdawson** [comment]
In which case there is no requirement for any change. The download follows the transcriber field order and adds on-line created fields at the end.

**Comment by richpomfret** [comment]
No change - closing.
