### ISSUE TITLE
Final test of flexible csv and New Fields

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1473]
Depends on #1459
Depends on #1465
Depends on #1462
Depends on #1446
Depends on #1496

**Comment by Captainkirkdawson** [comment]
Depends on #1459
Depends on #1465
Depends on #1462
Depends on #1446
Depends on #1442

**Comment by Captainkirkdawson** [comment]
Ensure that all aspects of the new baptism, burial and common fields work as expected

**Comment by Captainkirkdawson** [comment]
Testing of all identified issues and improvements is now complete and available on test2.

@SteveBiggs @edickens we need an extended test of the flexible csv and the new fields prior to deployment.

Initial documentation is at 

https://test3.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers/flexible-csv-format-draft
https://test3.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers/extended-baptism-fields-draft
https://test3.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers/extended-marriage-fields-draft
https://test3.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers/extended-burial-fields-draft

**Comment by Captainkirkdawson** [comment]
@edickens did you get any volunteers?

**Comment by edickens** [comment]
Yes.  Four.  And Steve is in contact with them.  The only problems have been understanding it.

**Comment by SteveBiggs** [comment]
I pointed them to the draft help notes, but I think they struggled a bit due to the notes not being complete yet. Once I explained the format required, they have been able to successfully upload files.

**Comment by AlOneill** [comment]
@SteveBiggs @edickens  Burials are pretty much done — E&OE! Baptisms are incomplete (Refinery issues); marriages need further work (links not all working, for example), but all the fields are there. So, I suggest burials would be the best choice for now, if possible — please let me know if anything is obscure/unhelpful/incorrect.

Of course, each set of fields should be read in conjunction with:
https://test3.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers/flexible-csv-format-draft
which has links to the 3 field description pages .
