### ISSUE TITLE
Add volunteer policy to sign up process

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#1475]
https://docs.google.com/document/d/1U4t9tkB34CbFR7CPx6gQ2qbvzbiGGu5tDv-Njsz1BwQ/edit?usp=sharing

Priority 22
Economic 0
Urgency 8
Strategic 7
Cost 7

**Comment by PatReynolds** [comment]
Working fine for me, thank you.
