### ISSUE TITLE
Add find-a-clergyman tip?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1477]
Richard Light spotted this and asks if it would be useful for transcribers
http://db.theclergydatabase.org.uk/jsp/search/index.jsp

**Comment by SteveBiggs** [comment]
In what way would it help transcribers?

**Comment by Captainkirkdawson** [comment]
Nine of the links work and it has minimal data, looks dangerous to me

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Site is working properly today. Interesting as a research database. See no value for transcribers

**Comment by richpomfret** [comment]
Closing.
