### ISSUE TITLE
Multiple Completed Group Selection

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1484]
Priority ( 0 3 8 7)  18
I tend to deal with accepting completion submitted groups once a week and sometimes it can go longer, so there may be 20 plus groups to accept as complete. Doing them one at a time is very time consuming so would it be feasible to have a select button against each or just 'select all' so many/all can be accepted in one go?
depends on #1584

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  Bev has developed the code for this, it is running on test3. Would you please test to see if it meets your expectation

**Comment by SteveBiggs** [comment]
I submitted three groups to myself as SC and clicked 'Accept All Assignments' and it returned this:

![image](https://user-images.githubusercontent.com/25303607/42733787-a378d56c-882f-11e8-885a-a4291146b214.png)

**Comment by SteveBiggs** [comment]
Can @bev-fc also provide an 'Accept All' for the CC to accept as complete? Thanks

**Comment by bev-fc** [comment]
@Captainkirkdawson can you either deploy it to test2 or increase my account's privilege? I do not get error Steve got on my machine, my account on test3 is technical, hard to guess what's going on.

**Comment by bev-fc** [comment]
@Captainkirkdawson %2F is decoded to / on test3, is it a config issue?

**Comment by Captainkirkdawson** [comment]
@bev-fc Could you point me to the code involves

**Comment by bev-fc** [comment]
@SteveBiggs Can you verify again?

**Comment by Captainkirkdawson** [comment]
@SteveBiggs its on test3

**Comment by SteveBiggs** [comment]
Accept All Assignments (as SC) worked fine this time.

Just need the same button on the CC Completion Submitted page please.

**Comment by richpomfret** [comment]
@SteveBiggs to check/review to see if this request has now been fulfilled.

**Comment by SteveBiggs** [comment]
It has not. Needs to be on this page:

![image](https://user-images.githubusercontent.com/25303607/43543808-04ea0dc4-95c9-11e8-90e4-d67c876d56b2.png)

**Comment by bev-fc** [comment]
@SteveBiggs only accepted all for SC is finished, accepted all for CC is next step.

**Comment by SteveBiggs** [comment]
Thanks @bev-fc. Let me know when it's done and ready to test.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs bev has added the CC accept all code; it is available on test3 for you

**Comment by SteveBiggs** [comment]
Tested in test3 and working, thanks.

**Comment by SteveBiggs** [comment]
This is the other page that I would like a button to send complete email to CC for all groups at once:

![image](https://user-images.githubusercontent.com/25303607/44158166-0300c000-a0ac-11e8-8167-5df3847a5b20.png)

**Comment by SteveBiggs** [comment]
Just tried the CC Accept All Groups as Completed button and it returned an error page:

![image](https://user-images.githubusercontent.com/25303607/44282986-c2907600-a254-11e8-8892-0d111dc37945.png)

**Comment by Captainkirkdawson** [comment]
Have never seen such a message before. Can it be duplicated and if so please note time of event? There is nothing in the logs to indicate any failures so do not know where to even start

**Comment by SteveBiggs** [comment]
Accepting one at a time still works.

**Comment by Captainkirkdawson** [comment]
@bev-fc regarding this CC multiple selection failure the normal log entry is
Started GET "/manage_counties/manage_completion_submitted_image_group" for 5.9.125.163 at 2018-08-18 18:30:09 +0100
App 43613 stdout: Processing by ManageCountiesController#manage_completion_submitted_image_group as HTML
There is then
App 43613 stdout: Started GET "/manage_counties/manage_completion_submitted_image_group.SSX" for 5.9.125.163 at 2018-08-18 18:31:39 +0100
App 43613 stdout: Processing by ManageCountiesController#manage_completion_submitted_image_group as

NOTE it does not have HTML as a result it is attempting to process manage_completion_submitted_image_group again but in an unspecified manner
Any ideas?

**Comment by bev-fc** [comment]
@Captainkirkdawson tested on test3, works without error, there is a possibility it's not code related issue.

**Comment by Captainkirkdawson** [comment]
@bev-fc then what might it be. Number of groups being accepted is too many, size of html request??

**Comment by Captainkirkdawson** [comment]
@bev-fc Something is generating the GET "/manage_counties/manage_completion_submitted_image_group.SSX" 
that is not a correctly formatted get with the .SSX

**Comment by SteveBiggs** [comment]
I start by clicking Accept All Groups as Completed:

![image](https://user-images.githubusercontent.com/25303607/44303813-a23ee500-a342-11e8-92c4-fe8f6f423fdc.png)

this brings up a popup box:

![image](https://user-images.githubusercontent.com/25303607/44303821-dadebe80-a342-11e8-8308-4d819ef1bc21.png)

I click 'OK' and get the Forbidden result page

**Comment by SteveBiggs** [comment]
btw I assume "Click Yes" really means "Click OK" ....?

**Comment by Captainkirkdawson** [comment]
@bev-fc I believe there to be an issue with the code
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/manage_counties/image_server_group_completion_submitted.html.erb#L9
passes @group_id, :type=>'complete', :completed_groups=>@completed_groups),  method: :put to image_server_group_path. The problem I see is that @group_id is just far too big in this case and that the action request is getting truncated. Tests with one or two groups will work but large numbers of groups will fail because the list is truncated
The code in https://github.com/FreeUKGen/MyopicVicar/blob/master/app/controllers/image_server_groups_controller.rb#L228-L238 cannot handle the incomplete parameter list
Just my opinion

**Comment by SteveBiggs** [comment]
I think @Captainkirkdawson is right. I reduced the list down gradually by accepting one group at a time and the Accept All button worked when the list was down to 5 groups long. (Did not work with 7 in the list)

**Comment by bev-fc** [comment]
@Captainkirkdawson The length limit of any URL and query stem combination in Internet Explorer is 2048 characters, how come it's a code level of issue?

**Comment by Captainkirkdawson** [comment]
@bev-fc because @group_id is an enormous hash @group_id[place_name][church_name][register_type][sourceName][group_name] = key  look at what it is trying to send in the error
Should we not be just sending a list of ids

**Comment by bev-fc** [comment]
@Captainkirkdawson I think it's time for me to quit volunteering with Freereg, please reassign everything under my name to someone else.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs could you review how I could go about creating a list of groups for a county so that I can test this feature.

**Comment by SteveBiggs** [comment]
SRY would be a good county to use because all of the images have been transcribed before the manage images functions were added. I can assign a bunch of groups to myself then submit them as completed. You could then act as CC to Accept All.

How many groups do you want in the list?

**Comment by Captainkirkdawson** [comment]
I have developed a fix for the CC acceptance. It was as anticipated an issue of using a hash as an id .Waiting for access to test3 for you to test for me.

In my testing I had trouble with the SC multiple acceptance; did not seem to always work but that could be because I have a messed up database/ Does it work for you?

**Comment by SteveBiggs** [comment]
SC mutliple acceptance seems OK for me.

Let me know when test3 is ready to test CC acceptance.

**Comment by Captainkirkdawson** [comment]
It is now running on test3

**Comment by SteveBiggs** [comment]
Yes I tested it last night and am sure I added a comment here that it worked with accepting 16 groups

Maybe I dreampt posting! Anyway, it looks good.

Just need the final button for SC sending the emails to CC in one go now.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs would you want that send email on the List Fully Reviewed Image Groups page as well as the Fully Transcribed Image Groups?

**Comment by SteveBiggs** [comment]
Yes sounds logical. Must admit I've never had any groups reviewed yet so didn't think about it.

**Comment by SteveBiggs** [comment]
When will the button to send complete email to CC for all groups be ready to test in test3?

**Comment by Captainkirkdawson** [comment]
Project assigned to bev currently under development

**Comment by SteveBiggs** [comment]
OK thanks

**Comment by Captainkirkdawson** [comment]
bev's code deployed to test3 as part of #1101

**Comment by SteveBiggs** [comment]
Deployed to production and gives the same red error page "Something went wrong ....."

**Comment by bev-fc** [comment]
@SteveBiggs fix is pushed to test3, please test it again.

**Comment by SteveBiggs** [comment]
@bev-fc it would appear to work now without error.

**Comment by SteveBiggs** [comment]
Please push to production
