### ISSUE TITLE
Remove getscan link and text from Help

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1485]
The getscan image process system no longer functions. We should remove reference to it from the Information for Transcribers Help and if the new Image Help is not yet available place some interim text

**Comment by AlOneill** [comment]
@SteveBiggs @Captainkirkdawson 

I propose replacing the text from the heading, 'View images allocated to you', to the list of copyright restrictions with:

"We now have an automated system for allocating images for transcription, linked to the Image Server (IS) — GetScan no longer works. 

From your Actions, select **Image Server**. This will give you access to a number of new Assignment Actions that allow you to request and work with the images that have been allocated to you. Communicating with you SC about images is also done within your IS pages: you can contact your SC when you have finished an assignment, and then to request more work. (More details to follow — in the meantime, please ask your SC if you need support.)

You can download images to your computer, but please be aware of the copyright restrictions: ... "

Is this OK?

**Comment by edickens** [comment]
Steve can confirm, but a transcriber does not have "Image server" in their Actions.  They need to look at "Assignments".
![capture](https://user-images.githubusercontent.com/8876165/41837527-a73ae3f0-7855-11e8-8509-add914744812.JPG)

**Comment by SteveBiggs** [comment]
Eric is correct. Can I suggest the following wording -

"The method of accessing images for transcription, from the Image Server (IS) is now done through your login to the FreeREG website — GetScan no longer works.

From your Actions, select Assignments. This will give you access to a number of new Assignment Actions that allow you to request and work with the images that have been assigned to you. Communicating with your SC about images is also done within your Assignments actions: you can contact your SC when you have finished an assignment, and then to request more work. (More details to follow — in the meantime, please ask your SC if you need support.)

You can view images directly on the IS or download images to your computer, but please be aware of the copyright restrictions: ... "

**Comment by AlOneill** [comment]
Mea culpa! Thanks for that — it makes so much more sense [sigh]

**Comment by AlOneill** [comment]
This edit is a 'minor' one, so both production sites (plain and test3) updated directly with revised text.

**Comment by Captainkirkdawson** [comment]
Thank you for the prompt action. It looks good to me.

**Comment by SteveBiggs** [comment]
Looks good to me too.

**Comment by richpomfret** [comment]
Done and on production.
