### ISSUE TITLE
Undefined method `get_sorted_group_name' for ImageServerImage:Class

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1490]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/5b323385e937906ce1a37093)

**Comment by bev-fc** [comment]
@Captainkirkdawson the fix is pushed together with issue #1484

**Comment by Captainkirkdawson** [comment]
@bev-fc see nothing new on github

**Comment by bev-fc** [comment]
@Captainkirkdawson the change is mixed within the push for multiple completed groups
