### ISSUE TITLE
Undefined method `new_url' for #<MessagesController:0x000000081bbd0380>

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1491]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/5b23bd70e93790a01e361f75)
depends on #1380

**Comment by Captainkirkdawson** [comment]
Likely associated with the changes in the story #1380

**Comment by smrr723** [comment]
Issue #1380 has been deployed and Vino confirmed this issue is now resolved as a result.
