### ISSUE TITLE
Undefined method `model_name' for NilClass:Class

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1492]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/5b314165e937906ce1a3708d)

**Comment by Captainkirkdawson** [comment]
Somehow someone found a way to enter a value into our bot trap
Propose to ignore

**Comment by richpomfret** [comment]
Super rare case so closing.
