### ISSUE TITLE
Volunteer Coordinator should have the ability to destroy Volunteering Question contacts

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#1494]
Jo cannot currently destroy (delete) volunteering contacts

**Comment by SteveBiggs** [comment]
More fundamentally, she cannot see volunteering contacts at all in her contacts list. They should be included as part of her dual role as Volunteer Coord.

**Comment by Vino-S** [comment]
Hi @SteveBiggs ,
The code is ready for testing in test3.

**Comment by Vino-S** [comment]
Hi @SteveBiggs , Jo has both CC and VC roles in test3. So she able to test the code changes in test3.

**Comment by SteveBiggs** [comment]
Jo has confirmed that she can now see the Volunteering Questions in her Contacts on test3.

**Comment by smrr723** [comment]
Deployed to production.
