### ISSUE TITLE
18 Review server setup

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1495]
On July 2 we had a data center failure that took our 3 of our servers. While we remained serving most users some were impacted. We should review our structure and see if it can be improved.
Priority (0 6 7 5) 18

**Comment by Captainkirkdawson** [comment]
Server upgrade summary. Freereg has been operational using the mongodb1 for 3 days since the transition. The transition took 2 12 hr days. Lots of spare time during the days. We were moving collections of 50 million records and a database of 60GB. Completely new index structures were used a) because we are no longer sharding the database; it is now a 5 member replica set.  All are using Mongodb v4.4 the latest version. of the severs are in Finland, 2 are in datacenter 1 in Germany and the last in a separate datacenter in Germany. Brazza, drill, howler and saki all prefer to read from secondary's while colobus prefers a primary.  b) experience over the past 4 years has shown that better index structures could be implemented.

Performance since. I was blindsided by a change in Mongo 4.2 that affected our nearby search capability. Capability disabled while solution developed. In addition one member action was found to fail. The download of a file failed. This has since been corrected, In the last 3 days there the longest running search has taken just 14 seconds. Almost all are below 5 seconds. This includes wildcard searches. This i s far far better than the previous performance when we would have seen at least 10 searches timeout at 100 seconds and there would have been hundred taking 50 or more seconds.

**Comment by SteveBiggs** [comment]
Thanks for this Kirk, sounds like a huge improvement in performance.
