### ISSUE TITLE
Report an Error in Data button didn't work

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1497]
From a researcher:

I found another error shortly before I got this reply and, when I tried to us the "Report an Error in this Data" on the record (as you suggest I do with my original email (this issue) back at the end of May, it seemed to not work. I filled in all the fields as requested and clicked "Submit". The page refreshed and I got the same page as before with the addition of a "Nature of Contact" and the "Please add your name again" being blanked. Set it to Data Question, adding my name again, clicked "Submit" and it repeated the refresh. Over and over ... it never said "got your report" or sent me a confirming email.

I am happy to submit this original issue the way you prefer (and I am sorry it didn't occur to me at the time to do it that way) but O need to understand why it isn't working (or at least does not appear to be working to me).

I am running Centos 6 Linux with Firefox ESR 52.8.0 (64 bit). To the best of my knowledge I have no script blocking on your site (allowing freereg.org.uk, google.com, nr-data.net, newrelic.com, googlesyndication.com, and googleanalytics.com). I tried both without accepting cookies and accepting cookies and it made no difference.

**Comment by SteveBiggs** [comment]
The button has now disappeared completely from the detailed search result page.

**Comment by richpomfret** [comment]
Tested on firefox and button appears at the top and bottom just fine. The report flow seems much improved over the original and I think we can now close this issue. A user reporting a problem submits and is taken back to the results screen and informed 'Thank you for contacting Us'.
