### ISSUE TITLE
Information about "Review batches by filename"

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1498]
Priority (0 2 3 6) 11

**Comment by edickens** [comment]
The description of the Register Type in this report varies for the same Register Type.
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8316b500bf238b488db4bb8c44c8ea3f37aa.JPG)
If one is OT and the other TR, then this is a great help in resolving another problem.  Please confirm.
It would be easier if the Register Type code is put here, and left blank if Unspecified.
TY  Eric

**Comment by Captainkirkdawson** [comment]
@edickens I accidently deleted the comment can you remind me what it was about I think it was something to do with register type

**Comment by edickens** [comment]
This where we need the Start and End year to be added.
This is the CC report.  It is so that we can skim it and put it into a spreadsheet and then compare it with the IGs.  If space is needed for the new columns, then Editing is not needed.

**Comment by Captainkirkdawson** [comment]
This was originally a n issue associated with the display of Register Type as a name rather than a code

**Comment by richpomfret** [comment]
Has this been completed/deployed?

**Comment by SteveBiggs** [comment]
Yes, this is deployed to production and available.

**Comment by SteveBiggs** [comment]
Have found Eric's original issue:

The description of the Register Type in this report varies for the same Register Type.
![image](https://user-images.githubusercontent.com/25303607/46090559-e37bad80-c1a8-11e8-9f99-dff57af74f19.png)
If one is OT and the other TR, then this is a great help in resolving another problem. Please confirm.
It would be easier if the Register Type code is put here, and left blank if Unspecified.

**Comment by edickens** [comment]
Yes, that was my request.

**Comment by Captainkirkdawson** [comment]
As far as I am aware this issue was resolved before I left on vacation. I corrected the display to use the actual register type and not the internal code and to do so in a consistent manner.

**Comment by edickens** [comment]
Perhaps it needs to be pushed to production.  This is what is there now:-
![capture1](https://user-images.githubusercontent.com/8876165/46856408-4488bf80-cdfe-11e8-8e11-498d6439aad5.JPG)
where there are entries with no Register Type.  Just the two letter code in this column would do.

**Comment by Captainkirkdawson** [comment]
It is in production. 
This "may" be a one off.  None of the displays I have used have a blank. 
It would be helpful to know how you generated this one.

**Comment by edickens** [comment]
Hi Kirk,
Angus (ANS) and list batches by filename.
Eric

**Comment by edickens** [comment]
All the batches now have a description, but it differs from the original (cf above)...
![capture](https://user-images.githubusercontent.com/8876165/46913885-c8bd7d00-cf8d-11e8-8ac5-4fb265d01c1c.JPG)
But would it be better to just put PR, OT, TR or whatever rather than converting to a description?  This is a Members report so they know what it means.  It would also help to know how the batch has been coded because there are some with OT and some with TR...
![capture1](https://user-images.githubusercontent.com/8876165/46913942-8e081480-cf8e-11e8-8089-a16ef177156e.JPG)
I think that these have created different Sources and we need to know which to move to where to make just one Register Type/Source.

**Comment by Sherlock21** [comment]
I agree with Eric D about the use of code letter for Reg Type

and also wonder why a couple of file names now have a different Reg Type in the 2 days between the postings?

**Comment by edickens** [comment]
@Sherlock21 it could be because my first example was from production and the latest is from Test3.  Different databases.

**Comment by Captainkirkdawson** [comment]
As Ericd noted the 2 reports are from different databases. The first was production the second was development.
There is no difference between an OT and a TR. We can change the display to say Other Transcript.
We try wherever possible to display external translation rather than internal codes.

**Comment by edickens** [comment]
WRT your last paragraph.  If that is the standard, fine.  But there are places in the code where OT and TR are not treated the same.  I would also like to see these transcriptions standardised so we need to know which has been coded OT and which TR.

**Comment by Captainkirkdawson** [comment]
I am sorry to have to disagree but there is no difference between how OT and TR codes are processed. They are one and the same.
There are no files with an OT code. They are all Transcripts (or Other Transcripts if you wish the display to use that terminology and be consistent with the documentation)

**Comment by edickens** [comment]
TY Kirk.  Done.  E

**Comment by richpomfret** [comment]
To be deployed.
