### ISSUE TITLE
Seek backup contact details for Coordinators

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#1507]
To aid communication. Possibly for transcribers too

**Comment by Captainkirkdawson** [comment]
The system stores that information so this story involves a personal effort in getting that information for  existing coordinators if not available

**Comment by richpomfret** [comment]
Already have capacity to collect this info - we just need to request it. @SteveBiggs to send out request.

**Comment by SteveBiggs** [comment]
Request message sent to all coordinators.
