### ISSUE TITLE
Place Google Tag Manager code on every page of website

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#1519]
IIUC, once the code is on the website, we will configure Tag Manager, and then we will need the existing analytics code to be removed.

Copy the code below and paste it on to every page of your website.
Paste this code as high in the < head > of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PJP93GW');</script>

Additionally, paste this code immediately after the opening <body> tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PJP93GW"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

Priority (4,3,7,6)
20

**Comment by Captainkirkdawson** [comment]
Are we sure we know what we are doing and have considered unintended consequences

**Comment by DeniseColbert** [comment]
This definitely does need discussion, particularly as we're currently having issues with analytics. By the time it gets to 'Ready', we should be good to go.

I've now assigned Rane (@jiun0426), our Google Analytics specialist volunteer. She is away until mid-August but can advise best.

**Comment by Captainkirkdawson** [comment]
Interesting reading.
What may make it easy to implement may also make it very difficult for a tag manager to use is that in reality we only have one page. 
All information is displayed within one layout 
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/layouts/application.html.erb

**Comment by richpomfret** [comment]
@DeniseColbert to give Scott access.
