### ISSUE TITLE
Copy comscoord email address to replies to Contacts

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1525]
Required by #1380

**Comment by Captainkirkdawson** [comment]
@SteveBiggs please clarify if that is via the contracts coordinator email address or by a person with that as a secondary role

**Comment by SteveBiggs** [comment]
Via the contracts coordinator email address please.

**Comment by SteveBiggs** [comment]
Commscoord received copies of messages and replies. Wording looks good.

**Comment by richpomfret** [comment]
Deployed once 1380 is good to go.
