### ISSUE TITLE
Replace Destroy button in Contacts with an Archive button

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1526]
Required by #1380

**Comment by Captainkirkdawson** [comment]
This is feature request will do bug fixes first

**Comment by Captainkirkdawson** [comment]
Deployed to test3

**Comment by SteveBiggs** [comment]
Used Archive button on a Contact and it disappeared from the list as expected. Where is it archived and how can a CC retrieve it?

**Comment by SteveBiggs** [comment]
Checking out SA access to archived contacts, when you change the "List by" selection, the 'List Archived' button changes to 'List Active' when it is showing active already.

**Comment by SteveBiggs** [comment]
Cannot see any way for CC to access their archived messages. I think the CC should be able to.

**Comment by Captainkirkdawson** [comment]
Are you sure about last but 1 comment?
![active](https://user-images.githubusercontent.com/2874694/47377788-7548de80-d6b3-11e8-9d44-01313c65410d.JPG)
![archived](https://user-images.githubusercontent.com/2874694/47377800-7a0d9280-d6b3-11e8-84db-502f58a82bea.JPG)

**Comment by Captainkirkdawson** [comment]
OK back to drawing board

**Comment by Captainkirkdawson** [comment]
@SteveBiggs Have added the capabilities for all contact types to see their archived contacts. Its on test3

**Comment by Captainkirkdawson** [comment]
One thing for you to think about is the default order of the display. Currently it is  contact_time  ASC ie oldest is displayed first. The display by date and identifier also use that order. It might be better to have the default as the most recent and let the other 2 remain as is. 
There is an argument to drop the by identifier as it and the by date are the same order

**Comment by SteveBiggs** [comment]
The default order looks like it is newest first in Feedbacks and oldest first in Contacts - I think we want newest first in both.

List by Name is alphabetic (a-z) - good
List by Posted Date is oldest to newest - should it be newest first?
List by Identifier looks wrong (not same as date):
![image](https://user-images.githubusercontent.com/25303607/47576525-996b2080-d93c-11e8-845d-446ce16b33cf.png)
List by Userid is alphabetic (z-a) - should it be a-z?

**Comment by Captainkirkdawson** [comment]
Thank you @SteveBiggs 
I have yet to push the revised feedback code that makes it function in the same way as contacts with archiving and replies. So testing should be restricted to contacts
I will adjust the contact default to be by most recent first. I suggest the by date should allow the oldest first. 
I believe the contact by identifier works correctly. Please confirm.
Personally I see no real value to having both date and identifier as they are effectively one and the same if date gives oldest.
There is no userid option on contacts just name.
I need confirmation that contact archiving and the displays for cc (and webmaster) work as you would wish.

**Comment by SteveBiggs** [comment]
If List by Date is to be by oldest then it should say "List by Earliest Date". How do we get back to the default of by most recent date (other than backing out of Contacts and going in again)?

List by Posted Date of Contacts gives this:
![image](https://user-images.githubusercontent.com/25303607/47588386-f2977c00-d95d-11e8-8718-66e381908b9c.png)
List by Identifier gives this:
![image](https://user-images.githubusercontent.com/25303607/47588429-0cd15a00-d95e-11e8-9e3f-144c59022d46.png)
They are different.

Contact archiving for CC looks OK notwithstanding the above comments.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs 
Feedback and contact management system update in now on test3 for final check out.
I submitted a Data Problems Contact and a subsequent Feedback on a real problem
We need to test these thoroughly on test3

**Comment by SteveBiggs** [comment]
Replied to Contact Reference 120097220 and got the red error:
![image](https://user-images.githubusercontent.com/25303607/47665761-c36d4e80-db99-11e8-83ea-61e23a49b519.png)

Tried replying to another contact with same result.

**Comment by SteveBiggs** [comment]
List by Identifier is still not correct:
![image](https://user-images.githubusercontent.com/25303607/47665990-6920bd80-db9a-11e8-9f27-202ba2bf68d8.png)
Appears to be sorting by the first digit rather than the entire number?

**Comment by Captainkirkdawson** [comment]
Red screen fixed

**Comment by Captainkirkdawson** [comment]
The identifier field is a string not a numeric.  
If all field are of the same length (number of characters) then the string sort will be the same as an integer sort. 
If the fields are NOT of the same length, as in this situation where one is shorter than the others by 1 character,  then the positions in the sorted list will differ between integer and strings since the sort does the comparison from the first character in each field. Hence 75371361 as a string will sort into a higher place then 120097220 since 7 is larger than 1.
It was for this reason that it was suggested we drop the identifier sort. Since the identifier is nothing more than a unix date the date field sorts give the desired results.

**Comment by SteveBiggs** [comment]
Reply now works.

I agree with removing List by Identifier.
