### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1549]
Update information for Coords - tell potential donors to check transcriptions availability and the free uk genealogy website.
Priority (0  1 3 7) 11

**Comment by richpomfret** [comment]
@PatReynolds to write the text.

**Comment by PatReynolds** [comment]
Needs review - still needed?

**Comment by edickens** [comment]
This is about duplicatoin of effort and having duplicate batches and hence getting duplicate results in a search.
So is it worth accepting transcriptions from a different source which may be transcribed slightly differently?  A second opinion could be worth having.
We definitely don't want to transcribe the same thing again.

**Comment by DeniseColbert** [comment]
Draft to be checked by Denise, @AlOneill and @edickens

**Comment by DeniseColbert** [comment]
I've copied Pat's document so we can comment/edit: https://docs.google.com/document/d/1N9aSeq37iDYhyjCIJHmoqB9Naa50zK6tgLFySU4Fd1k/edit?usp=sharing

**Comment by edickens** [comment]
I have added a sentence to explain why a UserID needs to be created.  Otherwsie I am happy htat this can go live.

**Comment by DeniseColbert** [comment]
If @AlOneill is happy too, let's go ahead

**Comment by AlOneill** [comment]
@DeniseColbert The part that I had questions about has gone from the document, so will update Info for Coords as per Pat's suggestions ASAP.

**Comment by AlOneill** [comment]
Info for Coords page being edited off-line for stories #2317 and #1549 — it will be overwritten to create a new master version. AO 31 Dec 2022

**Comment by AlOneill** [comment]
[DRAFT Section on acquiring data](https://test3.freereg.org.uk/cms/draft-information-for-coordinators) updated as per Pat's document.

**Comment by DeniseColbert** [comment]
Done closing
