### ISSUE TITLE
Cannot logon to FR website via WinFreeREG

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1554]
Priority (0 4 9 7) 20

When trying to logon, this error is returned:

![image](https://user-images.githubusercontent.com/25303607/44276820-a682d980-a240-11e8-9605-45126a975f10.png)

**Comment by Captainkirkdawson** [comment]
The additional diagnostics show that the password coming in from WinFreeREG for the computer access has a spelling mistake hence the inability to log into the system. Since I have no ability to access or change WinFreeREG I will see if I can change the expected password to the incorrect one.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs can you please retry on test3 WinFreeREG should be able to log into the system
If it works I will fix production

**Comment by SteveBiggs** [comment]
Have successfully logged in on test3.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs production login should now be OK

**Comment by SteveBiggs** [comment]
No, it's giving this error now:

![image](https://user-images.githubusercontent.com/25303607/44291606-452a2d00-a277-11e8-92c3-7b3372f9a4ab.png)

**Comment by Captainkirkdawson** [comment]
That is very different. WinFreeREG has successfully logged into the system. The barf is an objection to something about you

**Comment by Captainkirkdawson** [comment]
FREEREG::COMPUTER logged in with transreg   
App 43613 stdout: FREEREG::COMPUTER for user steveroland   
App 43613 stdout: "Known Transcriber"
App 43613 stdout: "Password matches"

**Comment by SteveBiggs** [comment]
Hmm interesting, I can login with some of my FR userids but not my CC one of steveroland. Not sure where we go from here?

**Comment by Captainkirkdawson** [comment]
Well having done the password check it then seems a message back to WinFreeREG
render(:text => {"result" => "success", :userid_detail => @user}.to_xml({:dasherize => false, :root => 'authentication'}))
Now the @user document contains a great deal of information. It will be different between test3 and production and also between users. I do not know how much of it is used.
The line that it is objecting to part of the userid_feedack_replies that was recently added. Specifically the line is
        "5b6e0191f493fd11a68e5d80" : [ ],
The 5b6e0191f493fd11a68e5d80 is an objectId for the document.
Clearly winfreereg is not able to process those elements.
There are a couple of options. I can delete the this field from the user document being sent back to WinFreeREG (a bit of a cludge) or we may be able to limit what is sent to what is needed what ever that might be or Steve may know of a way of handling the conversion to xml eg what does :dasherize do I have not the foggiest

**Comment by Captainkirkdawson** [comment]
@SteveBiggs want me to do anything or shall I move it to review or close?

**Comment by Captainkirkdawson** [comment]
@SteveBiggs can you test the WinFreeRg cludge on test3 please

**Comment by SteveBiggs** [comment]
Yes that worked. I can login as steveroland on test3.

**Comment by Captainkirkdawson** [comment]
Thanks Steve removed from test3 and being queued for release

**Comment by Captainkirkdawson** [comment]
Different version of WinFreeREG?

**Comment by SteveBiggs** [comment]
No Ali is using v1.1.13 same as me which is the most recent available.

**Comment by Captainkirkdawson** [comment]
All I can suggest is that either Ali or you are using a different copy of the package. What about your new developer can he log in with it?

**Comment by Captainkirkdawson** [comment]
Have added another kludge in case there are 2 packages with different passwords.
You and Ali should test on test3 NOT production

**Comment by Captainkirkdawson** [comment]
@SteveBiggs from where can I download WinFreeReg

**Comment by SteveBiggs** [comment]
I can still logon to test3. 

Earlier I asked Ali to change her password temporarily and I was able to logon as userid alsibk to test3, so it appears there is something different on her PC. She tried reinstalling WinREG v1.1.13 and it still did not work for her.

WinFreeREG download link: http://stash.freeukgen.org.uk/winreg/

**Comment by SteveBiggs** [comment]
See email I forwarded with all the things Ali tried this morning to no avail.

**Comment by SteveBiggs** [comment]
Ali just successfully logged in. Thanks

**Comment by Captainkirkdawson** [comment]
Sent an email on why the problem occurred.
