### ISSUE TITLE
Notify users of saving a search success/failure

### ISSUE THREAD

**Issue by graphiclunarkid** [FreeUKGen/MyopicVicar#156]
As a user saving a search I want to be informed whether it was successful so that I don't feel I have to go and check

ACCEPTANCE CRITERIA
- I can save a search. The system indicates that the save was successful.
- If the save was not successful I can see an error message that tells me what happened and what I should do to correct the situation.

**Comment by Captainkirkdawson** [comment]
I suggest we close this until we actually decide that there will be a researcher member function and what it does do
