### ISSUE TITLE
[production][freereg1_csv_entries#show] NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1561]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/5b69c28de937903469d2e6ba)

**Comment by Captainkirkdawson** [comment]
Fix added into 11o1 and deployed to test3

**Comment by Sherlock21** [comment]
I started to test this out.
Went to Batches, and picked my test batch ericb.TSTZEROBA1.csv
Did SH to display the batch details, and then Destroy to completely remove previous debris.
Crashed out with the Red Oopps somethings gone wrong.

Stopped, and have gone out for the day ( cultural of course!).
  I will pick up when I get back

**Comment by Captainkirkdawson** [comment]
Deployed to master and to master
