### ISSUE TITLE
nil field in DEF fields crashes processor

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1562]
Priority (0 6 5 8) 19
It appears that a file WRYTADBA2.csv is crashing the file processor

**Comment by SteveBiggs** [comment]
Not sure why it should be a problem, but he appears to have defined ALL possible fields in the file when only a small number actually have any data. I have downloaded the file and deleted it from FreeREG. Hopefully this will free up the processing.

**Comment by Captainkirkdawson** [comment]
The problem with the field definition is that there is a trailing , which creates a nil field. While not in this file a nil field anywhere in the list of fields would also cause the processor to crash.

**Comment by Captainkirkdawson** [comment]
Code added to detect and avoid crash with message to transcriber.

**Comment by richpomfret** [comment]
Ready for deployment
