### ISSUE TITLE
Edited entry still displays as previous version in summary search page

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1566]
Priority (3 6 9 5) 23
Given an economic benefit as incorrect search reduces credibility and hence reduces revenue

**Comment by SteveBiggs** [comment]
Yesterday morning a coordinator edited a 'zero year' record for Tho Harman Daneman born in Little Paxton, Hunts from 171_ to 1710. It does show up in a search but with the unedited old date of 171_:

![image](https://user-images.githubusercontent.com/25303607/44729296-6b04cc80-aad6-11e8-8af3-67d7af7f5e6f.png)

 When clicking on the row, it correctly shows the edited date of 1710:

![image](https://user-images.githubusercontent.com/25303607/44729363-94bdf380-aad6-11e8-83ac-4fc6327a6b1f.png)

**Comment by Captainkirkdawson** [comment]
The entry is 
{
        "_id" : ObjectId("5463eb42e9379027821fa891"),
        "error_flag" : "false",
        "line_id" : "meo2imma.HUNLPABA.CSV.329",
        "file_line_number" : 329,
        "register_entry_number" : "",
        "birth_date" : "17 Apr 1710",
        "baptism_date" : "",
        "year" : "1710",
        "person_forename" : "Tho. Harman",
        "person_sex" : "M",
        "father_forename" : "Robert",
        "mother_forename" : "Rachel",
        "father_surname" : "DANEMAN",
        "mother_surname" : "",
        "person_abode" : "",
        "father_occupation" : "",
        "notes" : "In a list headed 'Born and not baptized in the parish of Paxton Parva' Last digit of date year lost in fold of volume.  1710 is estimate",
        "film" : "1040746",
        "film_number" : "1656-1749-1- 029 & 031",
        "county" : "Huntingdonshire",
        "place" : "Little Paxton",
        "church_name" : "St James",
        "register_type" : " Parish Register",
        "record_type" : "ba",
        "freereg1_csv_file_id" : ObjectId("5463eb41e9379027821fa4b8"),
        "u_at" : ISODate("2018-08-28T10:03:59.678Z"),
        "c_at" : ISODate("2014-11-12T23:20:34.527Z"),
        "multiple_witnesses" : [
                {
                        "_id" : ObjectId("5463eb42e9379027821fa892"),
                        "witness_forename" : null,
                        "witness_surname" : null
                },
                {
                        "_id" : ObjectId("5463eb42e9379027821fa893"),
                        "witness_forename" : null,
                        "witness_surname" : null
                }
        ],
        "record_digest" : "CZdKBNJIHiP3C3NKNfuKqg==",
        "private_baptism" : false,
        "bride_marked" : false,
        "groom_marked" : false,
        "marriage_by_licence" : false,
        "transcribed_by" : "Michael Outlaw"
}

**Comment by Captainkirkdawson** [comment]
The records show a slightly different process from what is described. 
The entry shows that it was first created on "c_at" : ISODate("2014-11-12T23:20:34.527Z"). It was updated TODAY "u_at" : ISODate("2018-08-28T10:03:59.678Z"). 
However the search record shows it was updated YESTERDAY at "u_at" : ISODate("2018-08-27T10:33:14.538Z")
The attic shows that **an entry** was edited 2018-08-27T10:09:13+00:00 and again 2018-08-28T10:03:05+00:00. The latter coincides with the current version of the entry in question yet that shows that the entry in question at that time ie today was still HUN,Little Paxton,St James PR,"",17 Apr 171_,"",Tho. Harman,M,Robert,Rachel,DANEMAN,"","","",In a list headed 'Born and not baptized in the parish of Paxton Parva' Last digit of date year lost in fold of volume.,1040746,1656-1749-1- 029 & 031
So I do do not know what generated the update of the search record yesterday but it does not appear to have been the date change in the entry which appears to have been applied today and certainly did not generate an update,

**Comment by Captainkirkdawson** [comment]
Available on test3

**Comment by Captainkirkdawson** [comment]
Deployed to master and to colobus

**Comment by SteveBiggs** [comment]
Tested and good in production.
