### ISSUE TITLE
Rationalize secondary search date usage

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1568]
(1 3 5 5) 14
Until the new fields were added no record type had more than 2 dates; burials and marriages only had 1. Under the new fields ba has 4, and bu 2 and marriage 2. There should be no issue with bu and ma having 2 dates. However we can use only 2 dates used in ba for searching.
Need to rationalize order and usage.

**Comment by Captainkirkdawson** [comment]
Code has been developed to address this requirement as part of #1101

ma and bu now will search both dates. 
ba will search for any 2 of the 4 date fields, Priority  is the baptism field if it is there followed by the birth date (if there ) confirmation date (if there) and received into church (if there).
If there is no baptism field it will use birth date in preference to the other 2, if there are no baptism and birth fields it will use the other 2 if there,

**Comment by Captainkirkdawson** [comment]
Deployed to master and to colobus

**Comment by SteveBiggs** [comment]
Tested and good in production.
