### ISSUE TITLE
Delete a saved search

### ISSUE THREAD

**Issue by graphiclunarkid** [FreeUKGen/MyopicVicar#157]
As a researcher I want to delete a saved search so that my list of saved searches contains only those that are useful to me at any given time.

ACCEPTANCE CRITERIA
- I can delete a saved search. The system removes it from my list of saved searches.
- I cannot delete a saved search with a single action - confirmation is required.

**Comment by Captainkirkdawson** [comment]
I suggest this be closed until we specify what the researcher member facility is designed to do
