### ISSUE TITLE
[production][assignments#assign] ActionController::UrlGenerationError: No route matches {:action=>"my_list_by_county", :controller...

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1570]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/5b8aa242e93790bded257d24)

**Comment by smrr723** [comment]
For info - appears to be resolved and now in production.

**Comment by richpomfret** [comment]
@bev-fc can we confirmed this has been resolved?

**Comment by bev-fc** [comment]
@richpomfret last time it happened was 20 days ago, I think it's confirmed the issue has been solved.

**Comment by richpomfret** [comment]
To be deployed.
