### ISSUE TITLE
Accept Allocation Request is Failing

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1571]
Trying to accept the request via 'AL' results in error screen (Something went wrong ...)
depends on #1585
E - 0/10
U - 7/10
S - 8/10
C - 6/10

21

**Comment by SteveBiggs** [comment]
Files failing:
WOR, Belbroughton, Bap 1813-1852 JPG
WOR, Balsall Heath, Mar 1884-1886

**Comment by SteveBiggs** [comment]
Note also that the Report a Problem button has stopped working.

**Comment by Captainkirkdawson** [comment]
This is issue #1569 the specific errbit crash is https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/5b8a902ee93790bded257d1e

Proposed we close this one

**Comment by SteveBiggs** [comment]
Now deployed to production and gives the same red error "Something went wrong ....."

**Comment by Captainkirkdawson** [comment]
The initial fix created another one #1585

**Comment by bev-fc** [comment]
@SteveBiggs Can you verify if this issue is solved too?

**Comment by bev-fc** [comment]
@SteveBiggs Can you test it again?

**Comment by SteveBiggs** [comment]
@bev-fc it all seems to be working fine now thanks. Please push to production.

**Comment by bev-fc** [comment]
@SteveBiggs @smrr723 Can you ask Scott to push it? Kirk is on vacation.

**Comment by smrr723** [comment]
@bev-fc if you push up the branch for this Issue Bev, I will create a pull request and merge to master (to be deployed to production on Thursday).

Is it just the current bev_develop branch which needs merging?

**Comment by bev-fc** [comment]
@smrr723 Yes only bev_develop branch.

**Comment by SteveBiggs** [comment]
Reported as working on production now. Can close.
