### ISSUE TITLE
On line edit does not update the year field in the list of Register Batches

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1575]

**Comment by Captainkirkdawson** [comment]
Fixed and deployed in #1101 on test3

**Comment by SteveBiggs** [comment]
Tested and working.

**Comment by richpomfret** [comment]
Ready to deploy to production.

**Comment by Sherlock21** [comment]
But Rich
Isn't Kirk saying in 2 above yours, that he has already deployed this to Production as part of 1101?

**Comment by SteveBiggs** [comment]
Tested and working in production. Can be closed.

**Comment by Sherlock21** [comment]
With respect, this is NOT working correctly.

I discovered earlier this week that editing a Date Error in a Baptism file ONLINE, does NOT get rid go the ZERO on the date field of from-to dates hat appears in front of the file name in the ; 'Files for a church' page.
I:t does get rid of the RED flag for date errors, in ones list of Batches.

I just created a test file  eric.DEVTESTBA2.csv in T3.

item 3 in the file had the date 15 Dvc 1853.
the remaining 5 records in that file have correct dates.
Uploaded file OK
The date range of the batch was correct - (1853-1854) where it appears in front of the file name in church records.

Went to My Batches and as expected, the file shows a red Date Error warning
Looked up the error using the feature :Edit Dates Online and  corrected Dvc to Dec,
That correctly for rid of the date Error warning.

But then when I went to look at the church register records, the date range of the records has changed and now shows (0-1854) ericb (DEVTEST2BA.csv. And one can't shift it by doing a  reprocess batch.

**Comment by Sherlock21** [comment]
With respect, this is NOT working correctly.

I discovered earlier this week that editing a Date Error in a Baptism file ONLINE, does NOT get rid go the ZERO on the date field of from-to dates hat appears in front of the file name in the ; 'Files for a church' page.
I:t does get rid of the RED flag for date errors, in ones list of Batches.

I just created a test file  eric.DEVTESTBA2.csv in T3.

item 3 in the file had the date 15 Dvc 1853.
the remaining 5 records in that file have correct dates.
Uploaded file OK
The date range of the batch was correct - (1853-1854) where it appears in front of the file name in church records.

Went to My Batches and as expected, the file shows a red Date Error warning
Looked up the error using the feature :Edit Dates Online and  corrected Dvc to Dec,
That correctly for rid of the date Error warning.

But then when I went to look at the church register records, the date range of the records has changed and now shows (0-1854) ericb (DEVTEST2BA.csv. And one can't shift it by doing a  reprocess batch.

**Comment by Sherlock21** [comment]
here are related screen prints.
![screen shot 2018-11-16 at 09 18 13](https://user-images.githubusercontent.com/9368704/48613390-7bb13a00-e983-11e8-868f-deb83433eb50.png)
![screen shot 2018-11-16 at 09 17 37](https://user-images.githubusercontent.com/9368704/48613397-81a71b00-e983-11e8-96d4-c1ed64bfd6af.png)

**Comment by SteveBiggs** [comment]
This is a different issue covered by #1611

**Comment by Captainkirkdawson** [comment]
Resolved by #1611 and other matters
