### ISSUE TITLE
Unallocate Image Group not working

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1576]

**Comment by SteveBiggs** [comment]
Tried unallocating this:
![image](https://user-images.githubusercontent.com/25303607/45171600-bb78da00-b1fa-11e8-810d-0d235f807b8b.png)
and got red "Something has gone wrong ...." error

**Comment by Captainkirkdawson** [comment]
@SteveBiggs Is this still a live issue?

**Comment by SteveBiggs** [comment]
No, it is working fine now.
