### ISSUE TITLE
Include a name of sender within a 'from field' which will appear in the email/message when sent.

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#1578]
Priority 0,6,7,?

**Comment by PatReynolds** [comment]
Current 'from' is, e.g. "

freereg.edickens+REG@gmail.com via freeukgen.org.uk
--

"

Can you give an example of what is wanted?

**Comment by DeniseColbert** [comment]
E.g. 

"Eric Dickens at FreeREG" <Eric's email address>
"Denise Colbert, Free UK Genealogy" <denise.colbert@freeukgenealogy.org.uk>

**Comment by Captainkirkdawson** [comment]
In what way is this story different from #1218 above and does what has been done for that story meet the requirement

**Comment by edickens** [comment]
Sorry.  Yes, the sender name is fine.  I was looking to see if other things have been done and should have commented under the other story.

**Comment by DeniseColbert** [comment]
Got you test Kirk, still firstname.lastname
![image](https://user-images.githubusercontent.com/19173257/48851727-acd6a380-eda3-11e8-9a2b-06d2f179ba3b.png)

**Comment by Captainkirkdawson** [comment]
But what is wrong with that? 
The message has has the email address in the from field and if you had done a reply I would have received it. 
Also you will note that if you log into test3 you will see the message there waiting for you. You can also reply from there

**Comment by edickens** [comment]
I don't think the last message got into my Test3 log in.  All I have is this:-
![capture](https://user-images.githubusercontent.com/8876165/48853900-6e8fb300-eda8-11e8-9e30-154cba274799.JPG)
The problem with "reply all" is that you do get a message, but I don't think the freereg-contact reply gets tagged to the message.

**Comment by SteveBiggs** [comment]
I see I've been assigned this, but it's not clear to me what I should be testing for? Please clarify.

**Comment by DeniseColbert** [comment]
I think testing = review of the work done so far

**Comment by SteveBiggs** [comment]
Against what test criteria? Just to check that the sender's name is in the from field or something more?

**Comment by DeniseColbert** [comment]
Kirk to add 'Friendly From' field
