### ISSUE TITLE
Export search results

### ISSUE THREAD

**Issue by graphiclunarkid** [FreeUKGen/MyopicVicar#158]
As a researcher I want to export my search results so that I can preserve them in case FreeREG goes away

ACCEPTANCE CRITERIA

- I can see a link to download the results of a search in CSV format.
- I can click the link. A CSV file containing the results is downloaded to my computer.
- The CSV file has column headings that match those on the search results page.
- The CSV file columns are in the same order as presented on the search results page.

**Comment by Captainkirkdawson** [comment]
Implemented as part of print. User can do anything after saving
