### ISSUE TITLE
Rationalize the zero year calculation

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1581]
The selection and display of zero year entries makes no use of the year field and hence does unnecessary lookups and calculation.
In addition the code pays no attention to the other fields

Priority (0,4,5?)
required by #1094
required by #1118

**Comment by Sherlock21** [comment]
Ar you saying here, that the year part (yyyy) of a Baptism Date in ddmmmyyyy terms, is not used to for the Zero Years calc & display?
If so, in an old BA file say, where there is usually only  one date, where does zero Years come from?

**Comment by Captainkirkdawson** [comment]
Nothing to do with any aspect of the zero year from a user perspective.

This is simply a requirement to clean up inefficient coding

**Comment by Captainkirkdawson** [comment]
@Sherlock21 Clean up of code has been done. Deployed to test3 for checking

**Comment by Sherlock21** [comment]
Used one of my DEV files ( from MY Batches listing which showed a 0 year)- to check if editing the zero date online functions correctly: -YES OK.

Noticed the new feature: listing ALL Zero Year records for the County.
Tried this out and picked one record at random - bright.DEVNTABU.csv 
it actually contained 2 records with no YEAR - edited them online OK
It also contained one other error - a few with only a record number - Deleted that online OK

Returned to main County / Place listing and this file does not now show as having any Zero dates errors . 

SO additional feature of quick listing of all Zero Dates errors and ability to go from that list, to each error to correct it, and return to the same start point in this Zero Years subset, works Great.

These two features can all go into production now in my opinion.
Thank you

**Comment by Sherlock21** [comment]
Used one of my DEV files ( from MY Batches listing which showed a 0 year)- to check if editing the zero date online functions correctly: -YES OK.

Noticed the new feature: listing ALL Zero Year records for the County.
Tried this out and picked one record at random - bright.DEVNTABU.csv 
it actually contained 2 records with no YEAR - edited them online OK
It also contained one other error - a few with only a record number - Deleted that online OK

Returned to main County / Place listing and this file does not now show as having any Zero dates errors . 

SO additional feature of quick listing of all Zero Dates errors and ability to go from that list, to each error to correct it, and return to the same start point in this Zero Years subset, works Great.

These two features can all go into production now in my opinion.
Thank you

**Comment by Sherlock21** [comment]
Used one of my DEV files ( from MY Batches listing which showed a 0 year)- to check if editing the zero date online functions correctly: -YES OK.

Noticed the new feature: listing ALL Zero Year records for the County.
Tried this out and picked one record at random - bright.DEVNTABU.csv 
it actually contained 2 records with no YEAR - edited them online OK
It also contained one other error - a few with only a record number - Deleted that online OK

Returned to main County / Place listing and this file does not now show as having any Zero dates errors . 

SO additional feature of quick listing of all Zero Dates errors and ability to go from that list, to each error to correct it, and return to the same start point in this Zero Years subset, works Great.

These two features can all go into production now in my opinion.
Thank you

**Comment by Sherlock21** [comment]
Used one of my DEV files ( from MY Batches listing which showed a 0 year)- to check if editing the zero date online functions correctly: -YES OK.

Noticed the new feature: listing ALL Zero Year records for the County.
Tried this out and picked one record at random - bright.DEVNTABU.csv 
it actually contained 2 records with no YEAR - edited them online OK
It also contained one other error - a few with only a record number - Deleted that online OK

Returned to main County / Place listing and this file does not now show as having any Zero dates errors . 

SO additional feature of quick listing of all Zero Dates errors and ability to go from that list, to each error to correct it, and return to the same start point in this Zero Years subset, works Great.

These two features can all go into production now in my opinion.
Thank you

**Comment by edickens** [comment]
Have heard from EricB and Ali who  have checked this and they are happy for it to go production.
