### ISSUE TITLE
[production][image_server_groups#update] NoMethodError: undefined method `first' for #<ImageServerGroup:0x000000081ebb3ea8>

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1585]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/5983c4fce937903cff000006/problems/5b93e801e93790f616e3aabc)

**Comment by smrr723** [comment]
I'm seeing a commit message in the latest bev_develop branch for this issue, so appears to be complete.
