### ISSUE TITLE
CC actions zero dates

### ISSUE THREAD

**Issue by suffolkroots** [FreeUKGen/MyopicVicar#1599]
Please could we have the opportunity to "Review batches with zero dates" included in the list of CC actions.
needs #1581

**Comment by SteveBiggs** [comment]
Makes sense to add this.

**Comment by Sherlock21** [comment]
But in view of the response to #1611  how are you intending to advise CC's to correct these zero dates?

**Comment by SteveBiggs** [comment]
That requires resolution of #1581 first.

**Comment by Captainkirkdawson** [comment]
Have added a list files with zero years for a)transcriber b) syndicate and County coordinators
Deployed to test3 for evaluation

**Comment by suffolkroots** [comment]
Thanks Kirk.
Really useful.

**Comment by Sherlock21** [comment]
Yes, a most useful way for the CC to find and fix these records. TY.

**Comment by SteveBiggs** [comment]
Works as expected. Please deploy to production.

**Comment by Captainkirkdawson** [comment]
Cannot be  deployed on its own. Depends on #1581
