### ISSUE TITLE
Research creation of source with nil source_name

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1619]
Using same priority as original story.

**Comment by Captainkirkdawson** [comment]
It was created on September 29.
"_id" : ObjectId("5bafd24cf493fd72687a9a8f"),
"original_form" : {
"type" : "fiche",
"name" : ""
},
"notes" : "",
"start_date" : "",
"end_date" : "",
"creating_institution" : "ManCity",
"holding_institution" : "",
"restrictions_on_use_by_creating_institution" : "",
"restrictions_on_use_by_holding_institution" : "",
"open_data" : false,
"url" : "",
"register_id" : ObjectId("5bafd1bff493fd72687a97fe"),
"u_at" : ISODate("2018-09-29T19:28:12.014Z"),
"c_at" : ISODate("2018-09-29T19:28:12.014Z")

**Comment by Captainkirkdawson** [comment]
Log shows there was an error during creation
App 94824 stdout: Processing by SourcesController#create as HTML
App 94824 stdout:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"RuFi6z03VuvpqKyvJ0Lwvy9j16VwAf0UYG2PCxZHwrS9zOJ81VWV1CqeRGiND0QG7VNy4LLTU/4z8s2BYo8gxg==", "source"=>{"notes"=>"", "start_date"=>"", "end_date"=>"", "original_form"=>{"type"=>"fiche", "name"=>""}, "creating_institution"=>"ManCity", "holding_institution"=>"", "restrictions_on_use_by_creating_institution"=>"", "restrictions_on_use_by_holding_institution"=>"", "open_data"=>"false", "url"=>"", "register_id"=>"5bafd1bff493fd72687a97fe"}, "commit"=>"Submit"}
App 94824 stdout: Completed 500 Internal Server Error in 28ms (ActiveRecord: 0.4ms)
App 94824 stdout: ** [Airbrake] Success: Net::HTTPOK
App 94824 stdout: 
App 94824 stdout: TypeError (no implicit conversion of nil into String):
App 94824 stdout:   app/controllers/sources_controller.rb:27:in `+'
App 94824 stdout:   app/controllers/sources_controller.rb:27:in `create'
App 94824 

Crash was at
flash[:notice] = 'Addition of Source "'+params[:source][:source_name]+'" was successful'
ie :source_name was missing at that point.

**Comment by edickens** [comment]
Interesting.  It was created by Jo (LAN), but in WRY.  So was Jo creating something and it crashed and ended with a part created Source in WRY?  WRY is the last County.

**Comment by Sherlock21** [comment]
If this story is about  the Parish Church of Barnoldswick, then the Placename was in LAN ( in error) so thats why Jo started off the Transcriptions. and asked me to confirm the church name. My investigation eventually gave rise to the "relocation" or the place, into WRY. and Jo sent the source material to Ali to continue with. After much further research, Ali & I determined the Church name to be St Mary le Ghyll - 
As My tool for relocating a place name into another County has been removed, I could not just 'shift it over' but instead had to create a new Placename in WRY, add the Church Name we needed, then delete the place from LAN. At no time had there been any actual records in the LAN version. I don't know anything about the Images

**Comment by Captainkirkdawson** [comment]
Research shows that it was possible crash the source creation process due to the need for confirmation that the action was being done by a permitted user. Since the image server  never logs in there is a possibility that the action to complete the source document does not complete. Under those circumstances though there should be no entry rather than a partial entry with no folder or source name.
Have added code to ensure that the image server can communicate with the app on both source and image creation.

**Comment by Captainkirkdawson** [comment]
The change made should reduce  the possibility of problems with source document creation but 100% certainty cannot be guaranteed. I suggest we deploy the change and monitor
