### ISSUE TITLE
Document use of refinery message alert

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1620]
There are occasions when an alert needs to be presented to the community.
We have the ability to display an alert message on the search page but this process is undocumented
The search page will display a refinery message file that can be used to alert the community to an existing problem with the app or its servers.
This needs documentation and perhaps a tweak. The message is currently displayedat the bottom of the page and might be better at the top.

**Comment by Captainkirkdawson** [comment]
@PatReynolds  @richpomfret  @AlOneill  @DeniseColbert  @Vino-S  @smrr723  Document has been written and is available at
https://drive.google.com/drive/u/1/folders/0BykgQKwJtk6fN3lIX1U5aXVMOUU

**Comment by PatReynolds** [comment]
Thank you - that is great!
