### ISSUE TITLE
14 P Check message attachment types

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1630]
Check the file types and image types on message attachments to avoid crashes on message display. We currently have a list of supported types but no not appear to validate them on a message creation.

**Comment by richpomfret** [comment]
Ready for test on TEST3.

**Comment by richpomfret** [comment]
@DeniseColbert to test this out.

**Comment by Captainkirkdawson** [comment]
Deployed
