### ISSUE TITLE
[production][freereg1_csv_files#destroy] NoMethodError: undefined method `file_and_entries_delete' for nil:NilClass

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1647]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/5af6a35de93790b24fdc7125)
The user see this as #1136

**Comment by richpomfret** [comment]
Duplicate of 1582 - closing.
