### ISSUE TITLE
[production][image_server_groups#my_list_by_county] NoMethodError: private method `select' called for #<Source:0x000000081fab8278>

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1655]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/5be74565e937907298d68133)

**Comment by bev-fc** [comment]
![20181111_003](https://user-images.githubusercontent.com/22349799/48317522-8e152780-e5c1-11e8-9671-a26bfdd103ef.jpg)
errbit link does not exist

**Comment by Captainkirkdawson** [comment]
@bev-fc  Please try again
