### ISSUE TITLE
uploading a batch to Test3 crashes out

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1660]
I had previously  deleted a batch DEVTEST2.csv successfully, all at about 19:05 hrs GMT. Friday 16 Nov.
Then I tried twice to upload a new batch ericb.DEVTEST3.csv to Test 3.

It crashed out  on both attempts with the Red Oooops message.

**Comment by Captainkirkdawson** [comment]
It would help if you uploaded csv files and not ods files ie  DEVTEST3BA.csv and not DEVTEST3BA.ods same for DEVTEST2BA.csv and not DEVTEST2BA.ods

**Comment by Captainkirkdawson** [comment]
Of course we could introduce a test to tell people they were trying to load an incorrect file type. This is the first known occurrence in 3 years

**Comment by Sherlock21** [comment]
Oh drat!!!!

trying to be too quick. i will do better in future.
No need for you to do anything.

CLOSE this now
