### ISSUE TITLE
Online Edit of a date field generates zero as the start year of that batch

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1661]
This is a rewrite of the problem I wrote up earlier and which was closed (Cancelled) as it was said to have been included in another, related issues which also is now closed ( as in Completed) BUT the issue still exists. 
My story is now written up here, with screen shots at each step, to try again to get the point over.

Please refer to Test 3 region,  where I have repeated the sequence again today.
The file is DEV/ HARPFORD/ St Gregory church. File is ericb.DEVTEST3BA.csv

1) the file consists of 6 data records, of which one has a date that shows Dev instead of Dec so correctly this gets flagged as a date Error. it is register record number 643.

Screenprint1:
The church Register content showing the just uploaded file with the one date error - Note correct start finish dates in the file name.

![screenprint1](https://user-images.githubusercontent.com/9368704/48662292-0a06e800-ea78-11e8-95b0-b0bb6afc66e9.jpg)

Screenprint 2 RED error shows By Batch have a date error = correct.
![screenprint2](https://user-images.githubusercontent.com/9368704/48662320-797cd780-ea78-11e8-89f5-8d1b95be3b9d.jpg)

Screenprint3 is what I see immediately after doing an online Edit to correct the red error shown in print 2.

![screenprint3](https://user-images.githubusercontent.com/9368704/48662443-efce0980-ea79-11e8-8594-b796836b2779.jpg)

Screenprint4 is what I see in Church Register view. This shows the creation of the Zero Start year as a result of editing the file online.

![screenprint4](https://user-images.githubusercontent.com/9368704/48662347-d4aeca00-ea78-11e8-935e-361fe117f51f.jpg)

If I use my option to Reprocess batch: it does not get rid of the 0 start year.

Depends on #1581

**Comment by Sherlock21** [comment]
clicked comment button in error

**Comment by Sherlock21** [comment]
The other important player ( User) of this information is the Transcriber, looking up which places we have transcriptions for:-

Screeshot5
/Users/eric/Desktop/Screenshot5.jpg


And Screenshot6 - the details:
/Users/eric/Desktop/Screenshot6.jpg

**Comment by richpomfret** [comment]
We shall address this as part of a batch of zero date tasks e.g. 1581.

**Comment by Sherlock21** [comment]
May I ask that on this particular occasion, you include a once off batch job to deal with all the existing batches that exhibit this zero?

Subjectively, I feel there are very many such zero start date batches that have accumulated, and will never get fixed by their Transcribers of CC's.

**Comment by Sherlock21** [comment]
Do you mean you don't understand the request in the item just prior to your post?
OR do you mean  you don't get what the whole of this Issue is about?

**Comment by Captainkirkdawson** [comment]
Fix to the issue off on line editing sometimes apparently causing a zero date has been developed and deployed to test3 for testing

**Comment by Sherlock21** [comment]
I will get on to begint testing it this evening.
