### ISSUE TITLE
Accept zero date for a record

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1679]
@SteveBiggs @edickens  Do you wish to have the ability for a user/coordinator to "accept" that an entry has no dates and to exclude it from the date min/max and range calculations? This would mean that it would no longer cause a zero minimum. It is anticipated that this would be a new option on an entry edit.
needs #1581

**Comment by Sherlock21** [comment]
Is this such a big problem?
How many such records are there in FR at present please? 

I can see some benefits form doing this, but would i be correct that it would result in those records only appearing in a search that had no date limits?
-and there are several types of search using the range-expanding features like: Soundex and Family Members to name 2 that come immediately to mind, where there are results lists that are over 250 records, and the researcher is told to narrow down the search - usually this is only possible by narrowing the data band, - so what happened then? will these nil dates not get found?

Or would you put these nil dates into a separate set at the end of the results?

**Comment by edickens** [comment]
I think that every record should have a year, even if it is an assumed or approximate year based on the position in the register.  So there should be no option to allow a zero year.
Does flexible CSV have the means to enter an assumed year?  Is this used in the search?
My reasoning is that the year is very useful to find the entry in the register and in the batch listing, which could be sorted into year order.  The old registers do not have register entry number, and sometimes no page numbers, so we rely on Film and Image number, which is no help to a researcher who may be looking at the register.

**Comment by Sherlock21** [comment]
My reason for asking him many such records re there was: 
if only few dozen then I would vote don't waste time and don't provide for them.

if a thousand or more, the go the way Eric D suggests above. Estimate a date ( year only)  from the position in the source document that is next to the record with no date - as discussed at length in the original design stages by the Review Group.  so then the problem of what you do here, does not arise.
Accepting a UCF in year is the worst option and the estimate a year could easily replace those.

**Comment by Captainkirkdawson** [comment]
UCF in a date has always been accepted; there are hundreds of * dates.
If zero years are not an issue why have people been pushing so hard for them to be fixed?

**Comment by edickens** [comment]
Because the listing of batches in a Register Type does not show the year range, so you do not know what has been transcribed.
e.g. What years does the first MA batch cover.
![capture](https://user-images.githubusercontent.com/8876165/49026895-e5f18800-f196-11e8-908d-72db2d5cb86c.JPG)

**Comment by Captainkirkdawson** [comment]
@edickens do not understand the point of your last post

**Comment by edickens** [comment]
If you look at the left hand batch of MAs, the years covered are 0-1930.  But the second is 1903-1908.  So are these duplicated in the 0-1930?  We need to know the range of years covered in the first batch.

**Comment by Captainkirkdawson** [comment]
I fully understand and appreciate that. 
That is why I was proposing to remove UCF dates AND ACCEPTED zero dates, as suggested in this story. Otherwise legitimate zero date entries and UCF dates will always give a zero start year and you will never know.

**Comment by Sherlock21** [comment]
The big issue is that in some cases where a record has been edited online, a good, sound real year changes to a 0 ( i.e. a Zero) and thats the reason why people are pushing hard to get the problem that generates this issue, fixed.

I am not really against UCF's in years so long as they don't mess up the real years and the facts as Eric D points out above.

**Comment by Sherlock21** [comment]
The big issue is that in some cases where a record has been edited online, a good, sound real year changes to a 0 ( i.e. a Zero) and thats the reason why people are pushing hard to get the problem that generates this issue, fixed.

I am not really against UCF's in years so long as they don't mess up the real years and the facts as Eric D points out above.

**Comment by edickens** [comment]
I'm not against UCF in the date, but not in the year part of the date.  And definitely not a * year.  An entry such as 165_ would be quite useful, but better to be more accurate.  The Day and Month are not important.
But this is a variation to UCF and does not show what is unreadable.
Is there a generate year only field used for Searching?  If so, could we put something in there if the year in the dates is unreadable?

**Comment by SteveBiggs** [comment]
I agree with EricD. The year must be searchable. 165_ is OK because it would come up in a search between 1650 and 1659, but a simple * would only show up in a search without start and end years.

**Comment by Captainkirkdawson** [comment]
3 things. 
1. You cannot cherry pick parts of the UCF that you like/do not like
2. How the search deals with UCF is not part of this story.
3. This story does not deal with UCF.

To repeat the story

Do you wish to have the ability for a user/coordinator to "accept" that an entry has no dates and to exclude it from the date min/max and range calculations? This would mean that it would no longer cause a zero minimum. It is anticipated that this would be a new option on an entry edit.

Yes or No. 

Yes means such dates will not show as a minimum date. 
No means such dates will continue to show as zero in a minimum, date for file/register/church and place and you will have to convince coordinators/ transcribers to change them to non zero

I have no opinion either way but if you adopt no you will not be able to complain about the appearance of zero as a date minimum in the range

**Comment by edickens** [comment]
No - Eric D

**Comment by SteveBiggs** [comment]
How the search works may not be part of this story, Kirk, but it is important in deciding the answer to your question. If we allow entries with no date to exist in the database, those entries will not be returned by a date bound search. I think it important that we ensure every entry has at least a year.

So my answer is No.

I would not complain about the appearance of zero as a date if it only applied to entries that truly have no date (and can be dealt with). The complaint that I and other CCs are making is that entries which DO have a valid date are being flagged as zero (but this also is the subject of other stories).

**Comment by Captainkirkdawson** [comment]
TY for the clear answer

**Comment by Sherlock21** [comment]
I agree with Steve's summary and conclusion, in 2 items above this post of mine.

**Comment by suffolkroots** [comment]
Re UCF----Steve said that a UCF of 165_ will bring dates from 1650 and 1659, but how useful is that in a city register where there may be squillions of entries between those dates?

There should always be a date, whether actual or estimated.

**Comment by Sherlock21** [comment]
After a lengthy debate in the early days, I though it had been agreed all round, that the policy on incomplete dates should be: if the year is not present, with 4 useful digits, then the transcriber should use the year of the last satisfactory record prior to the one concerned, and just enter the date as * yyyy  with a commenting notes to say what you have done. and put the part readable date in the notes so the Transcriber has all the information for the record, and the record will be found in every search. Which is not to use a UCF in the year for one or more unreadable digits.
Its no good having thought out systems, and not all working to them in my view.

**Comment by edickens** [comment]
The other alternative format is yyyy?

**Comment by Captainkirkdawson** [comment]
This story as a development activity is closed. All the last comments comment on practice and documentation.
