### ISSUE TITLE
Changes to communications

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#1685]
Agreed that we should direct the volunteer to the message they have received by including a link in the email. 
"Please ensure you are logged in to FreeREG Members' Area before clicking this link".

Keep 'Archive' and set messages to be destroyed after expiry period (1 year?). Ability to tag messages as important (Kirk suggests add another field to state "this is not to be destroyed/retain in perpetuity", otherwise unarchived messages are deleted after a period of time (1 year).

To be applied to all message types.

Suggestions/enhancements should all be tagged as "keep in perpetuity" until dealt with, whereupon the tag can be removed.

**Comment by edickens** [comment]
Leave as is.  Especially if we going to get a link to take us direct to the relevant message.
It is useful to see what is going on.

**Comment by SteveBiggs** [comment]
Happy to leave as is.

**Comment by PatReynolds** [comment]
Yes, happy to leave as is.

**Comment by Captainkirkdawson** [comment]
Noting the responses and will leave the message selection as it currently is..

**Comment by Captainkirkdawson** [comment]
Unfortunately I cannot do a direct link to the message as the setup of the breadcrumbs is not established. The instructions are quite clear and simple.

**Comment by Captainkirkdawson** [comment]
Keep implemented for messages and deployed to test3
