### ISSUE TITLE
Keep for Feedbacks

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1687]
Keep 'Archive' and set messages to be destroyed after expiry period (1 year?).

**Comment by Captainkirkdawson** [comment]
Doing both this and #1686 together as they are almost identical

**Comment by Captainkirkdawson** [comment]
Committed changes to test 3

**Comment by Captainkirkdawson** [comment]
@SteveBiggs ready for you to look at. Cleaned up a couple of aspects of the presentation while it was open. No rush.

**Comment by SteveBiggs** [comment]
All looks good to me.
