### ISSUE TITLE
Witness being returned by search when Witnesses box not ticked

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1691]

**Comment by SteveBiggs** [comment]
Searching for Thomas Shorthouse as follows:
![image](https://user-images.githubusercontent.com/25303607/49344544-b9df7680-f670-11e8-967d-74914595ca08.png)
gives 18 results, but they are all with Thomas as a witness even though the Witnesses box is not ticked.

(If the Witnesses box is ticked, there are 200 results - he was obviously a professional witness!)

**Comment by Captainkirkdawson** [comment]
Unable to duplicate on basic test ie test with known witness only retrieves that record when witness option selected

**Comment by SteveBiggs** [comment]
Looking at the example above, all of the groom's forenames are Thomas, so the search appears to be combining the groom forename with a witness surname to return results even though the witness option is not selected.

**Comment by Captainkirkdawson** [comment]
Agree with your analysis so far but need to check if a search forename /surname might return a bride forename with a witness surname

**Comment by PatReynolds** [comment]
This search: Search Logic: Records with a first name of MICHAELA (ignoring capitalisation) . Records with a last name of LOWE (ignoring capitalisation) This search will match against the primary names in the record (i.e. baptisee, bride and groom, or deceased). In addition, it will search witnesses mentioned in a record.

Date
Search Criteria: Start Year is 1900. End Year is 1960.

Did not find this record (with, or without, indexes checked) - ie. is working fine.

County	Staffordshire
Place	Wednesbury
Church name	St Bartholomew
Register type	Parish Register
Register entry number	324
Marriage date	18 Oct 1947
Groom forename	Cyril John
Groom surname	HOUGHTON
Groom age	25
Groom parish	
Groom condition	
Groom occupation	Clerk
Groom abode	32 Simcox Road Wednesbury
Bride forename	Michaela Theresia
Bride surname	ROSEGGER
Bride age	21
Bride parish	
Bride condition	
Bride occupation	
Bride abode	32 Simcox Road Wednesbury
Groom father forename	Joseph Cyril
Groom father surname	HOUGHTON
Groom father occupation	Plumber, deceased
Bride father forename	Michaela
Bride father surname	ROSEGGER
Bride father occupation	Coast Guard
Witness1 forename	Carold Denis
Witness1 surname	SMITH
Witness2 forename	June Adelaide
Witness2 surname	LOWE
Notes	Licence
Film	
Film Number	
Transcribed by	Alan Harward
Credit	Alan Harward
File line number	332
Line id	Alanharward.STSWEDMA52.CSV.332

**Comment by SteveBiggs** [comment]
Perhaps the problem only occurs when the groom or bride forename is the same as a witness forename?

**Comment by PatReynolds** [comment]
June ROSEGGER (witness forename, bride surname) also fails to find the record used before.

**Comment by SteveBiggs** [comment]
Yes, the bride forename is different from the witness forename. Need to test a case where they are the same.

**Comment by Captainkirkdawson** [comment]
Have fond the issue in the code. A fix is under test on my server.

**Comment by Captainkirkdawson** [comment]
My texting reveals that we currently are returning witnesses and family members in a wildcard search. This may delay coming forward with a full solution unless we separate the 2 issues

**Comment by Captainkirkdawson** [comment]
Fixed both normal search and wildcard search to not return witnesses.
Also added a search validation to avoid wildcard / soundex searches
Deployed to test3

**Comment by SteveBiggs** [comment]
The original Thomas Shorthouse search now returns no results in test3 as expected, so looks good.
