### ISSUE TITLE
[production][search_records#show_citation] NoMethodError: undefined method `titleize' for nil:NilClass

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1695]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/5983c4fce937903cff000006/problems/5c06cb1ae9379095573f48a9)

It is essential to check that the field exists before applying a method

**Comment by richpomfret** [comment]
@sudaraka94 can you take a look at this and fix?

**Comment by sudaraka94** [comment]
Hello @richpomfret I am on this

**Comment by sudaraka94** [comment]
Found this issue. What is the branch I should fix this ? @richpomfret @benwbrum

**Comment by PatReynolds** [comment]
@smrr723 can you help @sudaraka94 with this, please?

**Comment by smrr723** [comment]
Hi @sudaraka94 - please make your change on a new branch off the current master branch, titled "Issue_1695".  Push up your new branch and create a new pull request in Github and assign it to me.  I'll then put it on test3 for you to test and merge into master when resolved.   

Drop me a message on slack if you are unsure of anything!

P.S. remember you will need to do the same process for FreeCEN off the latest `freecen_parsing` branch, if the issue also exists there.

**Comment by richpomfret** [comment]
@sudaraka94 have you had an opportunity to do this ?

**Comment by Captainkirkdawson** [comment]
Avoided titleize of blank fields. Deployed to test3

**Comment by Captainkirkdawson** [comment]
Needs to be extracted from software update branch
