### ISSUE TITLE
Review and fix links in help pages

### ISSUE THREAD

**Issue by graphiclunarkid** [FreeUKGen/MyopicVicar#172]
As a researcher viewing the FreeREG 2 help pages I want hyperlinks to link to the correct pages so that I can navigate the documentation successfully

ACCEPTANCE CRITERIA

- Existing hyperlinks from F1 documentation are updated to point to the correct F2 pages
- There are no dead links
- Hyperlinks are relative - so if the domain name is changed they will still work.

**Comment by berhew** [comment]
As a newbie I would like to take up your offer of a video explanation.
