### ISSUE TITLE
20 Provide means for SC to easily access Open Data status of their members

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1730]
There is presently no easy way for the SC to know the open data status of their team members without looking at each individually.

E3 U3 S 8 C6:Priory 20

**Comment by Captainkirkdawson** [comment]
At this point there are: 1849 'Unknown", 412 Null; 678 "Accepted". There are 0 Declined or Pending

**Comment by Captainkirkdawson** [comment]
Deployed a test version to test2

**Comment by SteveBiggs** [comment]
The new actions work, but the 'Review Active Members' action on test2 returns an error page.

I also notice that the message asking to sign the TA on login is not there even if you have not yet signed - this is the case on both test2 and test3 (perhaps this is expected?)

**Comment by Captainkirkdawson** [comment]
@SteveBiggs correcting spelling mistake that caused the crash; the other was due to my misunderstanding of #2080

**Comment by Captainkirkdawson** [comment]
@PatReynolds 

The action to list those who have accepted the Transcriber Agreement and those that have not taken action are now available for Syndicate coordinators and those members who can manage Userids

The open status of syndicate, county and country coordinators is now included in the display of those coordinators.

A new message is produced on the action page if the member has not actioned the agreement. New text has been written and the message is personal.

I note there is ONLY ONE option on the edit of the profile. That is to accept. Should there not be the option to decline???????

Needs your review Pat and others on **test3**

**Comment by SteveBiggs** [comment]
All works as expected.

**Comment by PatReynolds** [comment]
What does 'Not Accepted' show?.  Also somepeople have dates against their name - again, no one should have for Null or  Unknown.

I'm assuming I'm seeing "all" because of my permissions? Coords will want to see those they can give work to.

**Comment by PatReynolds** [comment]
An option to Decline will be needed in due course.  I estimate a minimum of 18 months.

**Comment by SteveBiggs** [comment]
@PatReynolds this is what I see for 'Not Accepted' as a SC:

![image](https://user-images.githubusercontent.com/25303607/68673382-862cf200-054b-11ea-8403-20753da067ad.png)

Currently, all who have not accepted are shown as 'U' (Unknown)
The dates are that of the last file upload - nothing to do with the TA
Coords only see transcribers in their syndicate.

Why must we wait 18 months for a Decline option?

**Comment by Captainkirkdawson** [comment]
@PatReynolds As Steve noted above There are actions for the SC to view the status for their syndicate. There are also the same actions for system administrators and others who have access to the Manage Userids action that list the status for all members. The date is as Steve observed associated with the upload of files; nothing to do with the transcriber agreement. At this point we do NOT have a date of signature with the transcriber agreement field (story #1152 in backlog). Will move the date to after the number of files. Not accepted is anything other than Accepted. There are 412 Null; 0 pending; 0 declined and 1849 'Unknown"
Like Steve I do not understand why the only option provided is accept.
