### ISSUE TITLE
SC needs to add non members to some messages

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1731]
A syndicate often has one or two members who are members of other syndicates to whom they would like to send messages.
e0 U1 S0 C6:PP7

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  Adding a simple selection from the volunteer list is problematic as the list would be 1000 entries long.  We could introduce the ability to augment the list of members with ancillary members for the purpose of communications. That would need the ability to add and delete from the list. Is it worth the effort. Likely a size 8 task

**Comment by edickens** [comment]
Would they be Active members?  If so then select just those for the list.
I can see the need because some transcribers work for more than one SC but can only be appointed to one syndicate.

**Comment by SteveBiggs** [comment]
I wouldn't worry about it. Very few transcribers are active for more than one county at the same time and some of those that are use separate userids for the different counties. If they need to be contacted, regular email can be used.
