### ISSUE TITLE
Volunteering Questions not appearing in Contacts

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1733]
Jo Summerfield has a secondary role of Volunteer Coordinator and gets emails when Volunteer Questions come in, but they don't always appear in her Contacts list on the FR website.

**Comment by Captainkirkdawson** [comment]
A little unsure of this one.

There is as action request email that goes out when a contact comes in. There is no Volunteer Coordinator so we always go to look for a volunteer with that as a  secondary role. There are 2 people Jo and Vino. (Why Vino I do not know). We just do a first selection so it is possible that Vino may get some of these action requests. If that is what is missing.

I am unsure what you mean by 'her Contacts list'.  Access to the Contacts system is restricted to people according to their primary role. I presume that she has access to it according to her role as a county coordinator. Originally CCs only got access to county contacts data problems but Vino in adding the secondary role did some jiggering of the code to add and subtract based on secondary roles. I presume this means that Jo would see volunteer question in the Contacts list if the code worked correctly.

It is almost impossible to diagnose further based on "but they don't always appear in her Contacts list". We need example of when they do and when they do not.

**Comment by SteveBiggs** [comment]
Understood. I'll ask Jo to give examples of VQ's she has received in her Contacts list.

But I think your supposition that Vino sometimes gets them sounds very plausible and perhaps the first thing we should do is to take the secondary role away from her profile.

**Comment by richpomfret** [comment]
@Vino-S can you take a look at this one?

**Comment by Vino-S** [comment]
Hi @Captainkirkdawson ,
I just gone through the above conversation to investigate the issue and  found the code I wrote to return an array of contacts according to users' primary and secondary roles has been modified. 

The code now uses `return` the Contact list if the person is County Coordinator, which is why Jo is now, only able to view County contacts not volunteering contacts.
https://github.com/FreeUKGen/MyopicVicar/blob/master/lib/contact_rules.rb#L41

Can I revert back to old method to return an array of contacts according to user's primary and secondary role?

**Comment by Captainkirkdawson** [comment]
Might have to change it  just a little. We display contacts either as archived or not

**Comment by Vino-S** [comment]
Thanks @Captainkirkdawson

**Comment by Captainkirkdawson** [comment]
ps I cannot spell

**Comment by Vino-S** [comment]
Hi @SteveBiggs , added the code changes to test3 for testing. Please have a look and let me know your feedback

**Comment by SteveBiggs** [comment]
I sent three VQs and Jo can see them all in her Contacts so I think it is working now.

**Comment by Vino-S** [comment]
Thanks Steve

**Comment by SteveBiggs** [comment]
This now working in live.

**Comment by Sherlock21** [comment]
Sorry to tell you that Eric had a stroke on the 4th and is in hospital, but making a good recovery.    from Jill, his wife.
On 4 Mar 2019, at 15:52, Stephen Biggs <notifications@github.com> wrote:

This now working in live.
