### ISSUE TITLE
Convert to issue doesn't work

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1739]

**Comment by SteveBiggs** [comment]
Clicking convert to issue from here:
![image](https://user-images.githubusercontent.com/25303607/50384371-ed378300-06bb-11e9-82d7-5058e59e534b.png)
returns an error page as follows:
![image](https://user-images.githubusercontent.com/25303607/50384380-04767080-06bc-11e9-8fc2-8208fe350a75.png)

**Comment by Captainkirkdawson** [comment]
Fixed as part of issue_1350 and is deployed on test3
