### ISSUE TITLE
Cookie acceptance colour has changed

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1748]
The REG house colours are no longer being applied to the cookie acceptance banner. They are using the CEN house colour scheme

E2 U6 S 7 C 8: P23

**Comment by Captainkirkdawson** [comment]
![cookie.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46eb9b95288b86ebc3abaf51ab57f5973d047d317c57a6287180ba71eb1a2b560d5a4eae41585e47a9f98a7db4aa2e32db025fb28c341521842f1bbeb98b15be04be26894887b0bd894dc8ed2f68.JPG)

**Comment by smrr723** [comment]
The CSS file for this hasn't been modified for a while, so I assume it's always been yellow (which does catch the eye).  I've changed it to look like so:-
![screenshot 2019-01-21 at 14 35 24](https://user-images.githubusercontent.com/2768445/51480826-de5ef180-1d89-11e9-840a-ba8554e5fd5c.png)


@DeniseColbert I don't suppose we have a styling/typography guidelines document of any sort, do we?  Something like this - (http://www.roguefitness.com/media/styleguide/RogueFitness-brand-standards-manual.pdf).  I'm sure I've seen one somewhere but can't recall where.  Would be useful for this sort of thing.

**Comment by DeniseColbert** [comment]
You may be recalling the fact that one of our previous volunteers was working on a Style Guide for us, but they didn't submit it. I shared the (very limited) document that we do have (from the people who designed the website) with you yesterday @smrr723. We plan to create one in-house in the near future.

**Comment by smrr723** [comment]
Ah ok, thanks @DeniseColbert
