### ISSUE TITLE
20 How to proceed with implementing online transcriptions - IMAGES

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1751]
E4, U6, S7, C3: P20

**Comment by edickens** [comment]
I've had a suggestion that we should use Googlesheets to do online data entry.  It proves the spreadsheet format and allows copy and paste, sort and so on.  But it can also be adapted for validation and interfacing with the website.  Or so I'm told.  I've only used it for recording image allocations and not the more advanced functions.
The advantage of this is that the transcriber does not have to install anything on their computer.

**Comment by Sherlock21** [comment]
So long as this does not become the exclusive way of uploading data. There are many who will not use anything but their own spreadsheets.

**Comment by suffolkroots** [comment]
Transcribers should still be able to use their own spreadsheet app, or WinREG---ie be able to choose whether to use Google or not. There are a great many who avoid it wherever possible

**Comment by edickens** [comment]
It is new transcribers that I would like to get onto an online system.  They keep trying to use WinReg to upload batches when it doesn't work.
The online system should be better at linking transcriptions to images held on the image server.

**Comment by edickens** [comment]
A GoogleDoc to be created so that ideas on what to include in online data entry, and how it will look to the transcriber, to be created.

**Comment by edickens** [comment]
To include in the GoogleDoc:-
For new batches:-
Create header by selecting County, Place, Church, Register Type from pick lists.  Other details added from transcribers UserID.
OR - The SC and CC can create the header and then the transcriber can select the batches to enter from information in their Assignments Action.  This must be possible even for images that are not on the image server.
Select images from the Image Server (if the images are there) using the image groups assigned by the SC.  Add copyright restrictions to the batch header.  Use the batch filename created by the CC in the Image Group notes.
If the images are not on the images server, then the CC must supply these details.
Images to be shown in a separate Tab for split screen viewing.
Data entry to be spreadsheet style and to look as much like WinReg as possible.

This to be a new Action of Online Data Entry.  The existing upload Actions to stay.

This is just basic thoughts as to what to include.  How this is done needs more thought.

**Comment by richpomfret** [comment]
@edickens I've made a start on the requirements document and included what you've added here. Please take a look and add in further key requirements and details where appropriate. This document is only accessible to those with a Free UK Gen email sign-in, so you'll need to use that account to access/edit/comment: https://docs.google.com/document/d/1ffeqYWDwYZP--86puoVap4bPRY1J9uJLLvL-VqplvnM/edit?usp=sharing

**Comment by richpomfret** [comment]
I should add that Google Sheets provides many, many compelling features for data entry - including benefit of collaboration/multiple users inputting to the same sheet and ability to use various scripts to automate aspects of it. Drawback being the necessity of having a google sign-in - but easy to set up an account. Note how it has been used for transcribing here: http://www.railwayaccidents.port.ac.uk/transcription-tuesday/

**Comment by edickens** [comment]
Rich - We have to end up creating a batch of entries that are in a fixed format, including flexible CSV, and validated against the database.  Google Sheets may be able to do this, but it will be quite complicated and the transcriber must not be able to change the format.

**Comment by edickens** [comment]
With th Google Doc that you have created, can any Coordinator access it and make comments, or is it only for those to whom you have given permission?

**Comment by richpomfret** [comment]
@richpomfret to open up permissions so others can edit/comment .

**Comment by richpomfret** [comment]
Changed so that it allows anyone with the link to 'comment'.

**Comment by PatReynolds** [comment]
NB Google drive means people can use google sheets off-line.

**Comment by SteveBiggs** [comment]
Why does this have a milestone tag of 1.6? It's in the Roadmap for 2.0.

**Comment by PatReynolds** [comment]
It was brought forwards due to the lack of a developer to work on WinREG/FreeWINreg.

**Comment by SteveBiggs** [comment]
I would rather see the Banns record type implemented.

**Comment by edickens** [comment]
I wouldn't because at present Mac and Linux have to use free from spreadsheets.  And WinREG does not work for uploading.

**Comment by SteveBiggs** [comment]
@edickens wrote:
I wouldn't because at present Mac and Linux have to use free from spreadsheets. 
- This has been the case for the last 15 plus years and many transcribers prefer working offline
And WinREG does not work for uploading.
- Uploading through the FR website is now routinely accepted and working well

Many counties have run out of source data, but there are lots of banns records waiting to be done. I would argue that allowing more records to be transcribed is more important than changing the way we transcribe the diminishing source data we have.

**Comment by Captainkirkdawson** [comment]
@richpomfret @Captainkirkdawson and @PatReynolds how to move forward

**Comment by PatReynolds** [comment]
I have gone through the document and turned what I can in to suggestions for discussion. @richpomfret have all the comments now been answered or turned into discussion points?

**Comment by suffolkroots** [comment]
I find the google doc re online transcription extremely user un-friendly, and question its use as a tool ----

 "for developers and users to understand what is planned"

I have images which can't be online as their terms of use dictate that they must be destroyed following transcription, but now I note that online transcription won't work unless they are.

Surely WinREG use will not be discontinued?

Please could we have this desseminated in a more accessible form for wider discussion and understanding?

**Comment by edickens** [comment]
The link to an image must be optional.  Perhaps even have a note to say where it is if it is not on the image server.

**Comment by SteveBiggs** [comment]
Online transcription will be an OPTIONAL alternative to offline (which can continue to be via WinREG or a standard spreadsheet program). It is intended to look and feel similar to WinREG but have the advantage that the entries will be added directly into the FreeREG database as they are transcribed and immediately checked for errors.

Online transcription does NOT require the source images to be on the image server. They can be from another online source or could be a physical print out of a register.

IF the images are on the server and IF that have the permission of the source provider then there can be a link from the entry to the image which will make future query checking much easier.

**Comment by edickens** [comment]
And, with permission, we could make the image available to the researcher, and if the researcher registers, they could leave a suggested searchable alternative - Version 2.+

**Comment by PatReynolds** [comment]
Needs a Ruby developer who has experience of transcription, or work with a transcriber to create the tools.

**Comment by PatReynolds** [comment]
Quick question on the location of images - I think we have concluded that it is possible to restrict access to images to a transcriber and their managers, so no reason why there is a requirement for FROTT to work with images locally.

**Comment by edickens** [comment]
The main thing that we want to do is to tie the transcription to the image so that if there is a query then the image can be brought up by a link in the Entry.  There is a field for this.  It would be good if this was automatic.  The transcriber calls up the image that they are to transcriber and the FROTT stores the link in the Entry.
The transcriber also needs to look at the image while they are transcibing and WinReg has a split screen option so that you can see the image and the format into which to put your transcription.
But there is very seldom, at present, for the link between the researcher finding the Entry and the image.

**Comment by PatReynolds** [comment]
I think I have now moved all the above to the FROTT Product Definition https://docs.google.com/document/d/1WJN4RWbhJ_6c8M_CuOcpOHEBvE4h9tQJJmGJfzJOcWM/edit?usp=sharing

This document needs a final review / sign off (I have asked some questions to individuals, and others just highlighted in yellow as needing a decision.

**Comment by edickens** [comment]
Pat - I have added a lot of comments.  But I am concerned that we are restricting the developer too much.  The best way is to use WinREG to get a feel for what transcribing involves, then work with Kirk for the interface with the server.  We need the simplest and most efficient system.  There could be a better way than trying to replicate WinREG.

**Comment by edickens** [comment]
I keep thinking of other things.
FROTT must not require anything to be saved on the transcriber's computer.  This may mean a lot of internet traffic, so any transcriber using FROTT should have a fast connection and able to transfer a lot of data.  It may mean that some transcribers will have to use a spreadsheet and work offline.
A transcriber should be able to pick up a batch that they have done before and work on it again, even after they have said it was completed.

**Comment by edickens** [comment]
And the Help needs to be written.  This is best done while the program is being written.  As well as some Help within FROTT, some Help will be needed under "Transcribers Help".  In particjular how to get started with FROTT.

**Comment by edickens** [comment]
Pat - Yoiu say that FROTT must be written in Ruby and Rails.  I think it just needs to interface with them, but can be written in html, C++ or any other well known language.  When run, FROTT will be run in a separate window or tab.

**Comment by Sherlock21** [comment]
Or pick up previous entries in the same file, and correct errors if necessary. - or they have second thoughts having come across a record in better handwriting for example.
