### ISSUE TITLE
Review the Review Process(es)/Tools

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1754]
Tools are there, but not used. Will certainly be needed on FreeCEN.

**Comment by PatReynolds** [comment]
@SteveBiggs to review

**Comment by SteveBiggs** [comment]
Sorry @PatReynolds , I don't understand what I'm being asked to review. What processes/tools?

**Comment by richpomfret** [comment]
Steve has documentation for process - therefore shall close this one.
