### ISSUE TITLE
Add person name to the userid selection for the Communicate Action

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1764]
Currently the list of individuals displayed for selection in the communicate action is just their userid. It has been suggested that it should be either their name or their name should be associated with the userid

E0 U3 S9 C8: P20

**Comment by Captainkirkdawson** [comment]
@edickens  If there is only one individual do we need to add name?

**Comment by Captainkirkdawson** [comment]
Deployed to test3

**Comment by Captainkirkdawson** [comment]
I guess I was being too clever! I assumed you would not want to send a message to your own role! But maybe you do.

**Comment by edickens** [comment]
But others may have the same role.  ED

**Comment by Captainkirkdawson** [comment]
Agreed. Have removed elimination. All roles now being showed. deployed to test3

**Comment by Captainkirkdawson** [comment]
Needs to be extracted from software update branch
