### ISSUE TITLE
Flaw in assignments code

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1774]
The current code has an image server as belonging to an assignment.  When an image is created it should have a link to an assignment. The current mongoid code permits a creation without that assignment. The new mongoid code will not. 
The fix is not trivial as an assignment belongs to a source, userid and syndicate.
This will stop the deployment of the software update.
Required by #1386

E0 U6 S9 C4: P30

**Comment by Captainkirkdawson** [comment]
Have done an ugly kludge to enable upload. Provided an assignment id that is meaningless

**Comment by benwbrum** [comment]
It looks like we can add `optional: true` to our models and be OK, according to [this](https://stackoverflow.com/questions/38527205/disable-mongoid-belongs-to-association-validation)

**Comment by Captainkirkdawson** [comment]
added optional: true applied to test3

**Comment by Captainkirkdawson** [comment]
Needs to be extracted from software update branch
