### ISSUE TITLE
Attachment missing from reply.

### ISSUE THREAD

**Issue by suffolkroots** [FreeUKGen/MyopicVicar#1775]
Data Problem with a reference 127840702 at 15:11 on 2019-01-19

It has been reported that no attachment was received on the reply to this contact.

E0 4 S7 c7: P18

**Comment by suffolkroots** [comment]
I presume this has been closed as now deemed OK?
But---Attachment missing from reply sent yesterday.
![attachment missing](https://user-images.githubusercontent.com/10379655/52197470-934be080-2857-11e9-8abc-ae5e019f2946.jpg)

**Comment by SteveBiggs** [comment]
Hi Ali, the attachment is showing up in the FR message system:
![image](https://user-images.githubusercontent.com/25303607/52209507-0d8e5c00-287c-11e9-974e-9191228ad178.png)

**Comment by suffolkroots** [comment]
Yes indeed it is Steve but unfortunately not on contact's received email. I've had to re-send it from my address.

**Comment by Captainkirkdawson** [comment]
Unfortunately this is one of several fixes that was removed when reverted the software_update.
The fix will become operational again when the software_update branch is reapplied to the servers.
