### ISSUE TITLE
Return from password set is incorrect

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1807]
Goes to syndicate all

E0, U4, S3, C8: P15

**Comment by edickens** [comment]
Is the message the same as "Registration completed"?  If so, I don't get a copy.  I ask everyone to join the transcribers group, and if I were to repeat this, then I would get and error if they had already joined.

**Comment by Captainkirkdawson** [comment]
No this is simply the return after the email a password reset to a userid.

**Comment by PatReynolds** [comment]
@Captainkirkdawson I may have not prioritised this correctly - does it seem right to you?

**Comment by Captainkirkdawson** [comment]
Completed
