### ISSUE TITLE
Display "processing" indicator where search results take a long time to return

### ISSUE THREAD

**Issue by graphiclunarkid** [FreeUKGen/MyopicVicar#182]
As a researcher performing a search taking longer than 3 seconds to complete I want a visual indication that a search is in progress so that I know I should continue to wait.

ACCEPTANCE CRITERIA

- I can perform a search. Once the results have taken more than three seconds to return I am shown an indication that I should wait.
- The indication disappears once the search is complete so that I know it has finished.

**Comment by Captainkirkdawson** [comment]
Visual indicator added to search and key parts of the Transcriptions displays to indicate that we are working on the request.
