### ISSUE TITLE
Google analytics appear to have stopped functioning

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1835]
It would appear that the google analytics are no longer functioning correctly.
The number of users has dropped dramatically from 18,000 to 2500. 
The average session time is now 10 seconds instead of a couple of minutes.
The bounce rate has climbed from 8% to 95%.
At the same time of search statistics are showing the same number of searches and New Relic is showing no change in performance

**Comment by Captainkirkdawson** [comment]
![analytics1.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46e99a9b2f9b97a08cfaee01e81fe086264c22703d46f96925d6e62bbe4722585b574eab135d5f46fcf98828f3b63f26984019af80330b2b9b645bf9fa9015ad03ba2a8a4a81bfb98248c1e13c21e58b9d02.JPG)
![analytics2.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46e99a9b2f9b97a08cfaed01e81fe086264c22703d46f96925d6e62bbe4722585b574eab135d5f46fcf98828f3b63f26984019af80330b2b9b645bf9fa9015ad00bd2a8a4a81bfb98248c1e13421e08b9d02.JPG)

**Comment by smrr723** [comment]
Google Analytics is still working as far as I can see - the drop in numbers is a correction back to pre-GDPR changes (May 2018).  We were never actually getting 20k visitors per day - so this is working as expected.
![screenshot 2019-02-08 at 09 32 43](https://user-images.githubusercontent.com/2768445/52469847-847d6a80-2b84-11e9-94be-4ca9e93701e9.png)

**Comment by richpomfret** [comment]
It looks like the 'fix' to the cookies was only just deployed on the 5th Feb - is that right @smrr723?  This would explain the big drop back down to 'normal' numbers which are comparable with the previous year.

**Comment by richpomfret** [comment]
Did we have an original story for this analytics cookie fix? I took a look but couldn't find it (I'd be very surprised if we didn't). This is in part, why I would also like a nice/easy export of search stat data (to csv) for our projects in order to cross-check analytics. Perhaps the latter could be something for a volunteer or data-ery type to undertake?

**Comment by smrr723** [comment]
Correct @richpomfret - and yes, that's the reason for the traffic returning to normal.  

There was a story for this specific problem on FC2 - "Review FreeCEN2 Analytics", but not one specific to FreeREG, or FreeCEN1 (that I can see on waffle).  FC1 still needs seeing to.

**Comment by Captainkirkdawson** [comment]
@smrr723 Sorry but if the analytics are correct then there is something wrong with our site set up. 
Guess I never was aware of any cookie or GDPR changes that inflated our user numbers. What caused the "inflation"?
Why are we now showing a bounce rate of 98%?
![analytics1.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46e99a9b2f9b97a08cfaee01e81fe086264c22703d46f96925d6e62bbe4722585b574eab135d5f46fcf98828f3b63f26984019af80330b2b9b645bf9fa9015ad00b22a8a4a81bfba8e48c2ee3f21ee889d02.JPG)
Why has the number of sessions exploded
![analytics2.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46e99a9b2f9b97a08cfaed01e81fe086264c22703d46f96925d6e62bbe4722585b574eab135d5f46fcf98828f3b63f26984019af80330b2b9b645bf9fa9015ad03bb2a8a4a81bfba8e48c4e83d23e7839d02.JPG)
Which in turn has blown the number of sessions per user out to 20
![analytics3.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46e99a9b2f9b97a08cfaec01e81fe086264c22703d46f96925d6e62bbe4722585b574eab135d5f46fcf98828f3b63f26984019af80330b2b9b645bf9fa9015ad00b32a8a4a81bfba8e48c5ec3425e2829d02.JPG)

**Comment by Captainkirkdawson** [comment]
@richpomfret  you can always see the actual number of searches graphically for the past week at https://www.freereg.org.uk/search_statistics
![searches.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fb919b31818bac9cabf301b44fff9e2c4533317346f6787586e22de61b2f595f581ca9415a5f44fdfadc2ba5e02e6c981e5ab38532022d8c6853beb2901eb70bbb258f4683b2b88244c6e83823f5c6.JPG)
You can look at the raw data since we started if you login and select the Site Statistics action
![stats.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fb809b3791c1e5cdf9ad4cae58f3806b1c65267a01a02a75dcba7ce7122c035a5f4cac41595c11fcfadf39baa47e21d40854b088270a36d43703aeb9881eba05b3268f4a84b5b58349c9fa70.JPG)

**Comment by richpomfret** [comment]
That is good to know - thanks @Captainkirkdawson

**Comment by smrr723** [comment]
Reporting where I am on this:- 

1. Checked the Tag Manager implementation on FreeREG versus FreeCEN - both identical.
2. Checked the Google Analytics setup on FreeREG versus FreeCEN - both identical. 

The Analytics and Tag Manager setup on both sites seems to be the same, yet we have the discrepancy on FreeREG with the high bounce rate.  The only area of code which I suspect could be causing an issue is the `cookie_control.js` file since cookies are how analytics data is recorded.  

Looking back in Google Analytics history, the bounce rate also shot up to the same level (90%+) when certain GDPR / cookie changes were made last summer - between May & July - so it's most likely something cookie related.

Next steps are to disable the `cookie_control.js` file for a day or so and monitor the impact on our bounce rate.

**Comment by Captainkirkdawson** [comment]
@smrr723  our google analytics statistics are still meaningless with bounce rates of 95% and session duration of 9 seconds. Is there any chance you can resolve this before leaving please.

**Comment by richpomfret** [comment]
I believe the Tag manager has now been reverted? In which case, do we still get the same bounce issue? Vino to push reverted code.

**Comment by Captainkirkdawson** [comment]
Clearly is not in production. Bounce rate still at 95%

**Comment by Captainkirkdawson** [comment]
David Houseman reported. `The property was not configured to exclude freereg as a referring site. So each page view was seen as a referral from FreeREG to FreeREG, which triggered GA processing a sequence of page views as a series of single page visits instead of one multi-page visit   This was inflating the bounce rate. I've updated the configuration on freereg to resolve the issue. This issue looks to have impacted session-level metrics as well as the goals on that site. I'll monitor this change going forward to make sure this seems to work properly. `

**Comment by Captainkirkdawson** [comment]
We are back down to 16% for Monday which is the rate of a year ago but still higher than 6 months ago when it was 9%

![analytics 3.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/03fbf264-219c-4839-87e5-78aba4cbcd54)

**Comment by richpomfret** [comment]
Brilliant. Shall close this one.
