### ISSUE TITLE
[development][search_records#show] undefined method `display_fields' for nil:NilClass

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1836]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/562a64eee93790333a000028/problems/5c5dcbbae937903f6543b708)

**Comment by Captainkirkdawson** [comment]
Caused by the change to record_not_found to false. ie no longer creates an error that we were trapping.
Fix developed

**Comment by Captainkirkdawson** [comment]
Deployed to test3

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  @Sherlock21  Could you run some searches on test3 please to check out that these changes have not introduced a regression

**Comment by Sherlock21** [comment]
I tried to upload this flex file  in Test3.
Selected  this file from my computer library attached it to Upload a New file in my Batches
Got the message: No such file.

/Users/eric/Desktop/DEVSIDASMA1.csv

**Comment by Sherlock21** [comment]
tesing with a if marriages file.
The groom is William Geowrg LIVERTON
The Groom's father is also Willian George LIVERTON.
NO witnesses have this name though.

RESULTS: search for George Liverton 1920 to 1920 in DEV / Sidmouth./ marriages
Found Correctly.

using revise search: I ticked Witnesses. - there are no witnesses with this name yet the result shows the same record as above.
Revised  search again, ticked Family this time and removed Witnesses. one result returned 

SO question is: does ticking Witnesses ADD in Groom + Witness names match search? or is it Just Witnesses?
Similarly ticking FAMILY: is it only Family - i.e. Groom's or Bride's parents? that should be returned?
as it is in this test, I think the result is unclear - or wrongly labelled in the search setting screen.

more tests to follow this afternoon.

**Comment by Captainkirkdawson** [comment]
Thanks @Sherlock21, the selection of a witness file for testing was not especially good (depending on ones view) because of issue #1172 on multiple witnesses and their display.
But key question was does search perform or crash?

**Comment by Sherlock21** [comment]
The search ran and did not crash.

It did find some data - but note I am still not sure if it finds the correct data as I explain above.

I used this file because it was just the start of my testing and it happened to be one that I had to hand for a Flexi file - wishing tho check that it would cope with that - not knowing exactly what you expected to make it crash.

I will continue with some more from the old LDS files and the other types of register now.
Having looked up 1172,I will do a rubbish names test  if you watch that one now!

**Comment by Sherlock21** [comment]
Interesting:I got 716 results for this Soundex search WITH Nearby. it gave up with the comment of too many results:  Display limit is 500.
Restricted the years span and got 501 records!  speedy result though, (using Revise Search)
Revised timescale down to 1600 - 1750 but added family mends as well.
this time there are 187 results within 10.2 miles radius - very speedy.

I will do this one again from a cold start but for all the same terms. ( i.e. not a revise parameters.
And subjectively this is just as speedy - too fast for me to time - like count up to 2 and the result is there,

**Comment by Sherlock21** [comment]
IS this a bit nit-picky?

the result of this search was exactly 500
but the message says: 
Your 500 results exceeds our display limit of 500 to avoid overloading your device with too much information at one time.
Pedantically, should this be a pass - only a reject if it is 501 or greater?

**Comment by Sherlock21** [comment]
ONE query point about NEARBY searches please:

Is there a Radius limit of 10.2 miles?
Several tests just now,  with NEARBY, seem to have stopped at 10.2 miles. And the number of records is only 293. - I used to get them up to 100 miles radius with no problems.
A Snag? or design change?

**Comment by Sherlock21** [comment]
Here is an issue for you:

trying to look at the detail of this file, I get an error message: this file is not correctly linked  -and I can't go anywhere!

screen copy jpg image WONT attach so its in the email

**Comment by Sherlock21** [comment]
These 2 rubbish names to test the timeout:

Both of course failed to find any result - the second theist I did as a "Revise parameters."
First test did seem to take a while but did not time out.
Second was much much quicker and again, did not time out.
NOW for some real testing. results tomorrow unless its a disaster!

**Comment by Captainkirkdawson** [comment]
None of your tests ran longer than 20 seconds from what I can see and that was for Bear RUPERT.
Purpose of the testing is:
I have put in a fix for the Display_Fields crash and need to try to make sure there are no unexpected consequences

Nothing has changed in nearby. It selects the nearest 40 places to start with and then narrows from there. So actual initial radius is a function of density of places. You are thinking way back when we initially experimented with broadening. We never put that into production

You crash is because the the test3 database is likely damaged. That message appears if the upward chain of file/register/church/place/county is broken somewhere.

**Comment by Sherlock21** [comment]
Thanks.

For the  Nearby issue, since we have accepted increasing the selection to 500 records, could we not increase the number of nearby places a bit - 40 little villages is not much in rural area - whereas 40  places in London will swamp you. - so say to 80 places?

**Comment by Sherlock21** [comment]
CONCLUSION

Given the answer to my points, if you just deal with  the >500 records notice,  then I am content you can move to production

**Comment by Captainkirkdawson** [comment]
Deployed to production
