### ISSUE TITLE
23? [development][image_server_groups#new] undefined method `to_s=' for :en:Symbol

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1841]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/5c5ef10ce937907b31af932b)

**Comment by Captainkirkdawson** [comment]
Incorrectly formatted url request
{
  "action" => "new",
  "controller" => "image_server_groups",
  "locale" => "en](https://www.freereg.org.uk/image_server_groups/new?locale=en"
}
Looks almost like a double click.

Suggest we just monitor to see if it is a frequent occurrence.

**Comment by Captainkirkdawson** [comment]
Is a daily occurrence on all servers. Its a bot with an ill formatted url

**Comment by PatReynolds** [comment]
Needs info before I can prioritise

**Comment by Captainkirkdawson** [comment]
It is now appearing with search queries on all servers  with the index method. We do not use the index method so it has to be a bot or similar.

**Comment by Captainkirkdawson** [comment]
Since we do not use the index method( we have a referral to the new which we use) we could look at putting a trap into the index method

**Comment by Captainkirkdawson** [comment]
On further research it is being caused by refinery; have posted on gitter for advise
![refinery.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/1c00cbdd-5c71-47f3-8e89-39be909ee07f)

**Comment by Captainkirkdawson** [comment]
This is a known bug in refinerycms-i18n. Fixed as a PR after release of 4.0.2. We cannot bump to the next version 5.0 as that involves movement to refinery CMS to version 5 which is designed to support Rails 6 and we are NOT ready for RAILS 6 as that really has a large number of changes.
Have changed our gem file to use the bug fix version BUT THIS MUST BE CHANGED WHEN WE BUMP REFINERY

**Comment by Captainkirkdawson** [comment]
Deployed
