### ISSUE TITLE
Generalize removal of received messages

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1851]
General message replies cannot currently be removed.

**Comment by Captainkirkdawson** [comment]
Fix developed and deployed to test3. Will leave to others for deployment to production

**Comment by SteveBiggs** [comment]
Works in test3. Thanks @Captainkirkdawson

**Comment by SteveBiggs** [comment]
@smrr723 when will this be working in live?

**Comment by smrr723** [comment]
@SteveBiggs should be in live now Steve.

**Comment by SteveBiggs** [comment]
Yes it's good now, thanks @smrr723
