### ISSUE TITLE
Update links to security policy in Volunteer sign-up and/or Members' Area

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#1857]
Version for Transcribers: https://freeukgen.page.link/SecPab

**Comment by DeniseColbert** [comment]
I'm not sure at what point during sign-up the policy is provided

**Comment by Captainkirkdawson** [comment]
Neither am I and can see no link hence the question. There does not appear to be an existing link

**Comment by DeniseColbert** [comment]
Ahh, I see from your screenshot that it's a PDF of an older version. The GDoc link is always current, but PDFs will become out of date. If we're going to continue to provide PDFs we need a story to update them perhaps every 6 months?

**Comment by Captainkirkdawson** [comment]
You do raise an interesting point that is worthy of more general discussion than this particular item. That is how we provide and keep up to date access to our support materials be they policies or advise or instructions or help. We appear to have evolved into a clutch of different processes and procedures.

**Comment by richpomfret** [comment]
Add to volunteer handbook?
