### ISSUE TITLE
Update Volunteer Induction Handbook

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1858]
E0, U10,S7,C9:P28

**Comment by DeniseColbert** [comment]
This sounds like a previous version; the CofC is in the handbook.

**Comment by Captainkirkdawson** [comment]
![conduct](https://user-images.githubusercontent.com/2874694/54285036-c1af9080-4566-11e9-8a58-fb1d6ad7c027.JPG)

**Comment by Captainkirkdawson** [comment]
We need a link to the appropriate updated document

**Comment by PatReynolds** [comment]
Correct document needs to be at the other end of the link

**Comment by richpomfret** [comment]
Duplicate for story on coord board.

**Comment by DeniseColbert** [comment]
Could somebody click this link and confirm that it takes you to the version updated April 2019 (on page 2) please? https://www.freeukgenealogy.org.uk/files/Documents/Volunteer-Induction-Handbook.pdf

**Comment by DeniseColbert** [comment]
( @richpomfret - I can't find coordination board story)

**Comment by richpomfret** [comment]
All done.
