### ISSUE TITLE
22P Remove misplaced advert on volunteer registration page

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1859]
In researching #1857 I noted that we have both adverts and a donate button on our volunteer page. Personally I think both are inappropriate. The advert in particular makes the text incorrect

E0, U4, S5, C9: P18

**Comment by Captainkirkdawson** [comment]
![volunteer.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fe9b96368c97ac8afbfd0fe64de29b234324676b5ee17e2380e029ba1b2255575f49fe44585d44fcf88a7ea6b56a62964e49bc8f3900299f7744eeaa880dbe08b0218e4a87b2bc884fc6eb3c23e799c2.JPG)

**Comment by richpomfret** [comment]
We can simply remove this advert - although check to see why it isn't in the correct position.

**Comment by Vino-S** [comment]
Done. Closing
