### ISSUE TITLE
Update website search Help to explain why wildcard and soundex do not work together in a search

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1861]

**Comment by SteveBiggs** [comment]
@Captainkirkdawson stated - we would not expect that a combination of these 2 very different techniques would work. Soundex assigns a numeric value to similar sounding letters. ; a wild card in that sense has no value. A wild card accepts any letter after the wildcard.

**Comment by Captainkirkdawson** [comment]
Test added to search to avoid such selection as part of #1691

**Comment by SteveBiggs** [comment]
Tested in test3 and looks good.

**Comment by AlOneill** [comment]
'Help' updated on test3 and live.

**Comment by richpomfret** [comment]
@SteveBiggs can you take a look at the text change?

**Comment by richpomfret** [comment]
Done.
