### ISSUE TITLE
Master recognizes multi modal switch

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1884]
The freecen_parsing branch recognizes the requirement for the code to run as the FreeCEN application. As the first step in making the Myopicvicar code base run as FreeCEN, FreeREG or FreeBMD or some future application we need to have the master code support this identification.
This will be done using a configuration file freeukgen_application.yml that identifies the application to be executed. Current options are freebmd, freecen, and freereg. This file should be placed in all application configuration files for all servers. In the event that the file is not present the code will assume that it is running freereg.

**Comment by Captainkirkdawson** [comment]
Have made application.rb read and use the application name from freeukgen_application.yml. deployed to test3 reg

**Comment by benwbrum** [comment]
I have tested this myself.
