### ISSUE TITLE
15 Citation link to copy to clipboard

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1887]
Currently the citation link creates the text in a new tab which the researcher must copy and paste to their file.
It has been suggested by @richardofsussex  that we should provide a copy to clipboard link of the text rather than the multi step process.
This could be done by changing the link or adding a copy button to the page that displays the citation.
Both approaches require a js component as RoR has no native way of doing a cut or copy.
Depends on

E1 U 3 S5 C6: P15

**Comment by Captainkirkdawson** [comment]
@PatReynolds @richardofsussex @richpomfret 
We have made a first pass at the provision inline of a copy to clipboard link of the citation text 
Please review on test2.freereg.org.uk
@alison could you please also review from an accessibility perspective

**Comment by richardofsussex** [comment]
Works fine. However, why are there two newline characters at the start of the pasted text?

**Comment by AlOneill** [comment]
@Captainkirkdawson Don't know what is going on here: am unable to tab through the buttons or the main menu items (was able to do so last time I tried). However, I note that the Citation button on the Details page has (reverted to) `href="#"` which will never be tab-able because # is not a proper link address.

Will try to work out what is going wrong, but will probably need some help.

No point trying screen-reader test whilst tabbing not working.

The warning that the formatted citation link will open in a new tab is good.

**Comment by Captainkirkdawson** [comment]
Where are you trying?

test2.freereg.org.uk

The text reads Please choose the format for one of these citation types. It
will appear below and may be copied:

Tabbing works fine for me

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by AlOneill** [comment]
@Captainkirkdawson Hmm. Works in Chrome but not Firefox. Will close FF and try again. (Was using a mixture of live and t2 — doh!)

**Comment by AlOneill** [comment]
Seems to be FF issue. Will investigate further ...

**Comment by AlOneill** [comment]
The Webaim site (with excellent accessibility) works as expected in Chrome. In Firefox (on OS X 10), the tab key cycles through some form elements only. So definitely a Firefox issue.

An internet search is not throwing up anything useful (other than advice to check basic settings).

Will do a screen-reader test (VoiceOver) in Chrome.

**Comment by Captainkirkdawson** [comment]
@PatReynolds  what do you think of the copy citation?

**Comment by PatReynolds** [comment]
Still opening in a new tab to be copied for me. (Chrome), test3.  Generator does not appear at all on test2.

**Comment by Captainkirkdawson** [comment]
Not deployed to test3 just test2
Display a searchresult detail
![citation1.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/cb76ec52-d905-43cb-b572-18b43c2d5e55)
Select Generate citation and citations appear
![citation2.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/1e8f3a89-e3a0-4392-8434-72aab8a0cdc1)
Select a citation and the proposed citation appears
![citation3.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/2012007e-cb66-4cad-9df1-0efc7fe0c60c)
Only reason for this not to appear is that Java Script is disabled in a browser

**Comment by PatReynolds** [comment]
There now ...
Wiktree does not have the correct data:  (https://test2.freereg.org.uk/search_records/58184787e93790eb7f81036e : viewed ) marriage Richard Miller to Sarah Wyman 30 Aug 1802
should be 
Higham Ferrers : St Mary the Virgin : Register of unspecified type : "Parish Register" database, FreeREG (https://www.freereg.org.uk/search_records/58184787e93790eb7f81036e : viewed 22 Jul 2019) marriage Richard Miller to Sarah Wyman 30 Aug 1802

**Comment by PatReynolds** [comment]
Family tree:  missing date viewed.

**Comment by AlOneill** [comment]
VoiceOver (Mac, on Chrome) found all the content OK and I was able to copy the citation. Suspect that Narrator (Windows) will be as capable.

However, am concerned about those (probably older) users without sight who do not have their own device: they rely on community/local authority computers which are more likely to be old, have a screen-reader that *is* the browser, and may have no choice but to have JavaScript disabled. I have no way of testing this directly, but will see if I can find any useful info.

**Comment by PatReynolds** [comment]
Can Citation(evidenceexplained): be Citation (Evidence Explained): (etc.) throughout, please?

Apart from the missing dates, no other issues to add to those in slack.
-

**Comment by PatReynolds** [comment]
This feature was greatly liked at a webinar I was at on Monday - idea of it being a single click thought an improvement on perfect.

**Comment by ShemJM** [comment]
I have fixed the missing dates and edited the citation titles. Just need to decide what to do when JavaScript is disabled. I think it might work to have the citation open in a new tab as it currently does, for users without JavaScript. Which would involve creating two sets of links and then showing/hiding the relevant ones with JavaScript.

**Comment by PatReynolds** [comment]
Thanks, @ShemJM  We think this is a good solution, but needs to work for those using screen readers - can you inform (in some way) users that the data will be in a new tab, ready for them to copy and paste?

**Comment by ShemJM** [comment]
I have updated the branch for this issue. Users with JavaScript disabled will now have their citations appear in the new tab and users with JavaScript enabled will have it appear on the page with the copy button. The message is different depending on which method is used. One will mention the new tab and the other will say the citation will appear below.
