### ISSUE TITLE
Asterisk is not found by a surname search

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1888]
Following recent discussion in the Transcriber's Google group around what to enter when a surname is blank in the register, I have been testing search options. TWYS would suggest leaving the field blank in the transcription but it seems that the record cannot be found in a search - even if the search has nothing in the surname. I would have expected that if a single asterisk was put for the surname then ANY surname search should return that record, but none do - only a search with NO surname finds it.

Should an * be returned when searching for a specific surname?

**Comment by edickens** [comment]
Is this part of the UCF search?  I thought that a research had to ask for the UCF entries because otherwise there could be too many results.  But there is no UCF option, or is it part of Soundex, or has UCF just not been implemented yet?

**Comment by SteveBiggs** [comment]
UCF is implemented to an extent. If you search for SMITH it will find the surname S*, but it doesn't find just * on it's own.

**Comment by Captainkirkdawson** [comment]
The search producing UCF results has not been released.
Using * or ? in the manner suggested will be problematic as they are used in a wildcard search and are not consistent with UCF specification

**Comment by PatReynolds** [comment]
Would typing "[blank]" (or other characters meaning 'there was nothing to transcribe' be returned (possibly as a separate search function)?

**Comment by edickens** [comment]
Star and ? are in the UCF specification, but ? should only be at the end of a field, not as an unsure character:-

The format in detail

_ (underscore)
    A single uncertain character. It could be anything but is definitely one character. It can be repeated for each uncertain character.
* (asterisk)
    Several adjacent uncertain characters. A single * is used when there are 1 or more adjacent uncertain characters. It is not used immediately before or after a _ or another *.
    Note: If it is clear there is a space, then * * is used to represent 2 words, neither of which can be read.
[abc]
    A single character that could be any one of the contained characters and only those characters. There must be at least two characters between the brackets.
    For example, [79] would mean either a 7 or a 9, whereas [C_] would mean a C or some other character.
{min,max}
    Repeat count of preceding character occurs somewhere between min and max times. max may be omitted, meaning there is no upper limit. So _{1,} would be equivalent to *, and _{0,1} means that it is unclear if there is any character.
?
    Sometimes you will be able to read all of the characters but remain uncertain of the word. In this case append a ? at the end of the word, e.g. RACHARD? However, the most frequent use of the ? is with transcripts that have been donated to us and then converted for entry into FreeREG.

**Comment by PatReynolds** [comment]
@Captainkirkdawson to take a look at this.

**Comment by PatReynolds** [comment]
@Captainkirkdawson to take a look

**Comment by Captainkirkdawson** [comment]
You cannot use * for an empty field. The * implies that there are characters in the field that are unreadable. So an empty field cannot be an *. There are 230 UNKNOWN surnames in Norfolk 81 in Somerset and it is used elsewhere. So my advice is that the term UNKNOWN is used for a purely blank surname.

It is clear that the use of * and ? as wildcards are in conflict with their use in UCF. Perhaps we should have selected something else for wildcard. or have it activated as a wildcard by having it in association with A Wildcard Search option

**Comment by SteveBiggs** [comment]
In that case, a search for any name should return UNKNOWN. Does it?

**Comment by Captainkirkdawson** [comment]
Why? That record would only be retrieved by a search for UNKNOWN

**Comment by SteveBiggs** [comment]
Because it's effectively a wild card search. Why would researchers search for the surname UNKNOWN?

**Comment by richpomfret** [comment]
Finish UCF and add in 'unknown' as a further category as proposed solution.

**Comment by richpomfret** [comment]
Closing as will be resolved via completing UCF tasks.
