### ISSUE TITLE
Transcriber's Help needs updating on use of asterisk for missing names in UCF

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1892]
An asterisk should also be used when a forename or surname is missing (completely blank). Change this:
![image](https://user-images.githubusercontent.com/25303607/56213426-e90ce800-6053-11e9-82d5-5d0c95e6ae5b.png)
and this:
![image](https://user-images.githubusercontent.com/25303607/56213517-15286900-6054-11e9-888d-6f5c6b5a4a1b.png)

**Comment by Captainkirkdawson** [comment]
@SteveBiggs Could I ask for clarification on what it is you are suggesting. I am totally unsure

**Comment by SteveBiggs** [comment]
The current help talks about using an asterisk for a group of characters that are present but unreadable. I think we concluded that the asterisk should also be used if the name is not present at all (rather than leaving the name blank) so that it is searchable with UCF.

**Comment by AlOneill** [comment]
How has this sat around for so long? (rhetorical)

OK, will update the 2 relevant sections on these pages: Entering data …, General Guidance; and Dealing with Uncertainty, UCF

**Comment by AlOneill** [comment]
A third section/page will also be updated: Flexible CSV, General guidance

**Comment by AlOneill** [comment]
All 3 draft pages now ready for review.

**Comment by SteveBiggs** [comment]
All updates look good to me.

**Comment by AlOneill** [comment]
@SteveBiggs Thank you.

**Comment by AlOneill** [comment]
All 3 pages ready for syncing. Moving to Ready for User Testing.

**Comment by Vino-S** [comment]
Deployed to production
