### ISSUE TITLE
Make Search Records Multi Modal

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1894]
MyopicVicar search record assumes that FR is running. Need to make views other aspects multi modal.

**Comment by Captainkirkdawson** [comment]
Completed and deployed to test2.

Testing is does the search and display of records etc all work as before

**Comment by PatReynolds** [comment]
Tried a search for Alcock, Ra* 1700-1890, all types, no other filters.  Ran for more than 50 seconds.

Alcock, Ra* 1800-1850, baptism, family members. Ran for more than 50 seconds.

**Comment by SteveBiggs** [comment]
This search never completed:
![image](https://user-images.githubusercontent.com/25303607/56890684-0a1d0200-6a72-11e9-9454-ca1be88fb1e9.png)

and no error/warning message.

**Comment by Captainkirkdawson** [comment]
Code updated to give message

**Comment by Captainkirkdawson** [comment]
The display of search results and all functionality should work correctly on test2
