### ISSUE TITLE
Make Search Performance Action Multi Modal

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1898]
The Search Performance statistics action needs to be sensitive to the different search fields in the different applications.

**Comment by Captainkirkdawson** [comment]
Search performance now responds to the different search fields in different applications.

**Comment by Captainkirkdawson** [comment]
Please review to ensure that search performance  still works as expected on Freereg test2

**Comment by PatReynolds** [comment]
All working fine (searching Lowe in Derbyshire and Nottinghamshire), but print function does not work.
E.g.
https://test2.freereg.org.uk/search_records/5817f7e2e93790ec8b7df27c/show_print_version?locale=en
gives blank screen.
