### ISSUE TITLE
Chuch name wrong?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1899]
freereg.org.uk/search_records/5818712fe93790eca31b4ae2/elizabeth-lowe-baptism-nottinghamshire-worksop-1801-09-25?locale=en shows church as "Our Lady and St Cuthber" should be "Our Lady and St Cuthbert"

**Comment by Sherlock21** [comment]
This needs to go direct to the CC concerned ( Anna) who can do it online with a bit of luck - else to Steve or me who can do it for her

Eric B
On 2 May 2019, at 10:48, PatReynolds <notifications@github.com> wrote:

freereg.org.uk/search_records/5818712fe93790eca31b4ae2/elizabeth-lowe-baptism-nottinghamshire-worksop-1801-09-25?locale=en shows church as "Our Lady and St Cuthber" should be "Our Lady and St Cuthbert"
