### ISSUE TITLE
[production][search_queries#new] undefined method `places_json' for nil:NilClass

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1910]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/562a65f7e93790333a00002f/problems/5ce8afe1e93790080b487683)

**Comment by Captainkirkdawson** [comment]
@edickens @SteveBiggs @PatReynolds what is status of Ireland? We have all of the Irish counties in the county drop down list. None of them bring up places and if you select such a county you get no search results. Under certain conditions the system appears to crash. If there is no data for a county should we not remove the county rather than give false expectations that lead to frustration.

**Comment by edickens** [comment]
We did have Ireland blocked off, but then there was talk of us being donated some registers, which never materialised.  Perhaps it needs to be blocked off again.
Alternatively; perhaps Eric Booker can add the place names if they are easily available.

**Comment by Sherlock21** [comment]
All the appropriate Place Names for the NI counties were created by me about a year ago (when Sandra was getting some data)
But that set never appeared

I agree with the suggestion that if there is no likelihood of any data coming along, then let's have all the NI Counties and Places hidden.\\


At my last involvement there was a strong feeling of "closed shop" being applied.

**Comment by Captainkirkdawson** [comment]
Ran a place_cache refresh just in case

**Comment by PatReynolds** [comment]
Asked Sandra 28/5/2019

**Comment by PatReynolds** [comment]
Sandra says, yes, they have data.  The transcriber has had to take a break, but hopes to be in a position to return to in the next few months.

**Comment by Captainkirkdawson** [comment]
Issue has not reappeared since place cache refreshed
