### ISSUE TITLE
Mozilla browser intermittently  flags up warning that its not safe to connect to the FreeREG website

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1916]
Mary Korna has reported this. Has anyone else experienced it?

**Comment by richpomfret** [comment]
This might result if an old version of the site is being accessed (http rather than https).

**Comment by SteveBiggs** [comment]
Mary has confirmed here bookmark used http. She has changed it to https so should be good now.
