### ISSUE TITLE
Run the delete the orphan search record rake task

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1919]
I had a file eric.DEVNPOPBA1.csv
Yesterday, I needed to rename it as DEVNPOPBA5.csv but that required me to delete it and load again with the BA5 ending. I did the 'delete' either from My Batches, or from the Browse Batch screen - can't remember as I was also doing other file deletes.
I then uploaded my BA5 file ( with the exact info that had been in the BA1 version. - it uploaded as a new file OK.
Then today I did a search  that was constrained to data that should have only been in my BA5 file:- 
lie search for DEV / Newton Poppleford/ Baptisms/ 1500-1600/ Surname RUGG.
There are 2 records returned.
Pick 1st, to view details and it gives error message - to the effect that the data does not exist - try again later - but it is no better, when tried later.
Pick 2nd of the pair, that is 'OK' and details quote correct file source - BA5.

SO I am speculating: the Deletion of the original batch BA1 did not fully clear out all the data when I did the delete yesterday.

P0 U4 S7 C6: P17

**Comment by Sherlock21** [comment]
Any chance of some action on this issue please?

I have 3 emails'worth of other large batches to delete.

If this is no longer the way of getting snags addressed, please advise me

**Comment by Captainkirkdawson** [comment]
It is the only way of getting issues dealt with but it does take time as there are always competing demands

**Comment by Captainkirkdawson** [comment]
I can confirm that the delete of the files did not completely delete the search records although it did delete the entries. 
I will run the task to deleting the orphan records.
The prevention of further occurrences will be difficult without knowing how the batch/file deletion was attempted.
.

**Comment by Captainkirkdawson** [comment]
A file was scheduled for deletion during May 28th. That night as expected the files and records were processed for deletion
Starting entry deletes at 2019-05-29 05:20:57 +0100
5ceaba88f493fd4e6aafb29b,ericb,DEVNPOPMA1.csv
ericb.DEVNPOPMA1.csv.1,DEV, Newton Poppleford,St Luke, PR, ma
66 records deleted for 5ceaba88f493fd4e6aafb29b,ericb,DEVNPOPMA1.csv
 66 records deleted

**Comment by Captainkirkdawson** [comment]
The file that was deleted had the following content
+INFO,,PASSWORD,SEQUENCED,MARRIAGES,Utf-8,,,,,,,,,,,,,,,,,,,,,,,,
#,CCC,Eric Booker,"Yorkshire, West Riding - Ali Hill",DEVNPOPMA1.ods,07-Nov-2017,,,,,,,,,,,,,,,,,,,,,,,,
#,CREDIT,ericb,,,,,,,,,,,,,,,,,,,,,,,,,,,
#,26-May-2019,Images by E B,,,,,,,,,,,,,,,,,,,,,,,,,,,
+LDS,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,5 Jun 1581,Edward,SEWELL,,,,,,Jane,CARTER,,,widow,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,22 Jun 1581,John,STREAT,,,,,,Jane,MITCHELL,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,26 Nov 1582,John,CRUTCHARD,,,,,,Johan,COMB,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,23 Jun 1583,William,MANLEY,,,,,,Margerie,*,,,,Servant to wm. Rugge,,,,,,,,,,,,bride's surname not given
DEV,Newton Poppleford,St Luke PR,,20 Sep 1583,Robert,PALFRIE,,,,,,Jone,BESSE,,,,Servant to ellys force,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,8 Oct 1583,Robert,STONEYNGE,,,,,,Johan,REDMOND,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,8 Jan 1587/8,Thomas,CARTER,,,,,,*,*,,,,,,,,,,,,,,,,bride not named!
DEV,Newton Poppleford,St Luke PR,,14 May 1590,Robert,LEY,,,,,,Wilmot,HELLIARD,,Broadcliste,widow,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,5 Nov 1590,Thomas,LAVNDER,,Wythicomb Rawleigh,,,,Thomasine,KNIGHT,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,14 Feb 1590/1,Thomas,SMITHE,,,,,,Sydwell,DARTER,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,15 Jul 1594,John,GALLOPPE,,,,,,Susan,WYNTER,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,27 May 1596,Nicholas,COMB,,,,,,Thomasine,BUSSELL,,Axminster,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,21 Oct 1598,John,EDMOND,,,,,,Thomasine,HAMBLYNE,,,widow,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,4 Dec 1598,Peter,KELLEY,,Honitons Clyst,,,,Johan,SPETE,,,widow,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,8 Sep 1600,John,POWELL,,,,,,Dorothie,FILMORE,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,24 Feb 1600/01,Richard,NORCOTT,,,,,,Marye,CHANNON,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,7 Jan 1600/01,Richard,CARTER,,,,,,Elizabeth,*,,,,,,,,,,,,,,,,bride's surname too feint to read.
DEV,Newton Poppleford,St Luke PR,,15 Feb 1600/01,Thomas,CARTER,,,,,,Jane,*,,,,,,,,,,,,,,,,bride's surname not recorded.
DEV,Newton Poppleford,St Luke PR,,2 Nov 1601,William,PESTELL,,,,,,Mary,HEYDON,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,19 Nov 1604,Richard,COCKS,,,,,,Jane,PERSE,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,9 Jan 1605/6,William,PERSON,,,,,,Hellen,PERSE,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,28 Jan 1605/6,Richard,NORCOTT,,,,,,Alice,TALLENT,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,3 Mar 1605/6,Robert,SERRELL,,,,,,Thomasine,STOKES,,,,,,Edward,Serrell,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,29 Jul 1607,Henry,POWNINGE,,,,,,Ja*,WHITE,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,19 Feb 1608/9,Water,WHITE,,Exeter,,,,Eddeth,ANTHONIE,,Herocomes,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,19 Feb 1609/10,Thomas,MANNINGE,,,,,,Thomasine,FULBROOKE,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,2 Jul 1610,John,KNIGHT,,,,,,Johan,FROST,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,28 Oct 1613,Henry,RATLEVE,,,,,,Thomasin,HAMELINGE,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,4 Jul 1614,John,STANSBI,,,,,,Thomasin,PERSON,,,widow,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,16 Jan 1614/5,James,PESTELL,,,,,,Thomasin,AXE,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,7 Jan 1614/5,John,WALTER,,,,,,Marie,CAPEL,,,,,,,,,,Thomas,,,,,,
DEV,Newton Poppleford,St Luke PR,,29 Nov 1619,George,ROOKE,,Alphington,,,,Jane,COCKE,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,2 Dec 1620,*,GILES,,,,,,Joane,FEATOR,,,,,,,,,,,,,,,,Groom's  first name not recorded.
DEV,Newton Poppleford,St Luke PR,,1 Oct 1621,Christopher,GOODRIDGE,,,,,,Katherin,SMITH,,,,,,Chas.,Smith,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,25 Jul 1622,Thomas,DALL,,,,,,Elizabeth,CARTER,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,15 Jul 1622,John,BAKER,,,,,,Mary,CAPELL,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,25 Nov 1625,Andrew,LIVERINGE,,,,,,Florence,MARTINE,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,18 * 1627,Nicholas,COMBE,,,,,,Joane,CAPLE,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,22 Apr 1630,Nicholas,PALMER,,,,,,Agnes,FARTOR,,,,,,,,,,Thos:,Fartor,,,,,
DEV,Newton Poppleford,St Luke PR,,28 Jun 1630,William,RUGGE,,,,,,Sarah,WHITE,,,,,,Wm:,Rugge,,,Thos:,White,,,,,
DEV,Newton Poppleford,St Luke PR,,14 Aug 1645,Richard,CRASSE,,,,"Serge weaver &.,servant to william kunnot - a serge weaver",,Joane,TOWNINGE,,,widow,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,28 Dec 1655,Robert,COLE,,,,"Tailor& a servant to wm. Clarke,",,Elizabeth,CLARKE,,,spinster,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,29 Dec 1655,Thomas,NEWCOMIN,,,,"Servant of wm. Cannat, a serge weaver",,Dorrothey,PESSEL,,,,,,,,,,Dan:,Pessel,,,,,
DEV,Newton Poppleford,St Luke PR,,3 Mar 1655/6,Jonathan,MADOCK,,,,Woosterd komer,,Hannah,HIGGINS,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,6 May 1656,Robert,MAN*,,,,Husbandman,,Brigget,DOWNE,,Ottery St Mary,widow,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,26 Dec 1657,James,SOUTHWOOD,,,,Husbandman,,Eliz:,JONNES,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,16 Sep 1658,Niccales,WHIDDON,,,,,,Grace,TREGOS,,,,Silk weaver,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,14 Mar 1661,Thomas,GODFREY,,,,,,Joane,MIDWINTER,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,3 * 1661,Thomas,MIDWINTER,,,,,,Ann,DAVID,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,1 Aug 1661,William,PERIMAN,,,,,,Elizabeth,LUCKKES,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,19 Sep 1661,William,BANFIELD,,,,,,Hanna,WILLS,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,26 Dec 1661,Hennery,ELLEAT,,,,,,Eleanor,KAPELL,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,13 Jul 1662,William,STREET,,,,,,Elizabeth,FALKNER,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,11 Sep 1662,Robert,FARRANT,,,,,,Grace,HART,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,16 Sep 1662,Nicklas,SQUIER,,,,,,Marey,PERREYMAN,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,20 Oct 1662,*es,TUCKER,,,,,,Grace,CLARCK,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,20 Oct 1662,John,GOBBER,,,,,,Prudence,PIN,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,20 May 1663,Hennery,TROOT,,,,,,Jonne,GOWLDE,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,23 Jul 1666,John,SANDER,,,,,,Elizabeth,GREENE,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,19 Sep 1667,John,CLARKE,,,,,,Graceiqon,BARNES,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,20 Oct 1668,Edmond,BARNES,,,,,,Gane,GALLAY,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,10 Dec 1668,Robert,SENSAM,,,,,,Elnor,LEVERMORE,,,,,Colerton Ralley,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,6 Jan 1668/9,Robert,COLES,,,,,,Agnes,WILLS,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,22 Oct 1669,John,FALKNER,,,,,,Hanna,WARREY,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,18 Nov 1669,Hennery,CLARCK,,,,,,An,KNIGHT,,,,,,,,,,,,,,,,
DEV,Newton Poppleford,St Luke PR,,29 Mar 1670,Charles,RUGGE,,,,,,Mary,CLARKE,,,,,,,,,,,,,,,,

**Comment by Captainkirkdawson** [comment]
There are no RUGG entries in that file. Hence it seems unlikely that the deletion of the file DEVNPOPMA1 was responsible for the reported error.

The user folder for ericb contains a file DEVNPOPBA5.csv and the attic contains files for DEVNPOPBA1 and DEVNPOPBA5 of identical sizes with the latter having been uploaded on the 28 May.

Looking at the duplicated records for Thomas RUGG. One, which is correctly connected, was created "2019-05-28T19:14:10.873Z"  from an entry "ericb.DEVNPOPBA5.csv.5" .The other which is an orphan was created "2019-05-25T15:59:49.397Z" from an entry "ericb.DEVNPOPBA1.csv.5"

The detailed logs show the file DEVNPOPBA1 being replaced at 2019-05-26 14:21:31. The file DEVNPOPMA1 was uploaded 2019-05-26 17:10:29 and replaced 2019-05-26 17:13:36.

Show no actions being taken with either DEVNPOPBA1 or DEVNPOPBA5 on 27 May 

Show the file DEVNPOPMA1 was uploaded 16:14:02 on 27 May and again at 16:46:02 It was forced into processing with Physical Files at 16:46:16

Show the file  DEVNPOPMA1.csv being scheduled for deletion on 2019-05-28 20:11:16

There are 2 PhysicalFilesController#submit_for_processing in quick succession on the 28th at 2019-05-28 19:44:58 DEVNPOPBU5  and 2019-05-28 20:12:14 DEVNPOPBA5  both of which entered a file into processing

**Comment by Captainkirkdawson** [comment]
What can one conclude? 
According to the logs there was no attempt to delete or remove a file DEVNPOPBA1. There was a deletion of the file DEVNPOPMA1 on the stated day. That deletion completed correctly.
There are orphan records for DEVNPOPBA1 which are duplicated in DEVNPOPBA5.
The logs do not appear to offer any clue as to the cause of the duplication.

I would recommend caution by any data manager in using the Remove file option in physical files as this could create orphan files (not the current situation). The Delete option in physical files does an immediate deletion as opposed to the scheduled deletion of a file.

Based on these finding there does not seem to be a reason to not use the delete a file action.

Once the scheduled software release is completed I will run the delete the orphan search record rake task.

**Comment by Captainkirkdawson** [comment]
Have commenced background cleanup

**Comment by Sherlock21** [comment]
Yes, I agree I was working on both the files that you refer to and both together on line and off line.
Perhaps in future, it would be wise to only do one juggling job at once.
Sorry to have put you to so much trouble.

**Comment by Sherlock21** [comment]
Yes, I agree I was working on both the files that you refer to and both together on line and off line.
Perhaps in future, it would be wise to only do one juggling job at once.
Sorry to have put you to so much trouble.

**Comment by richpomfret** [comment]
@Captainkirkdawson to run the delete the orphan search record rake task in due course - returning to incoming for now.

**Comment by Captainkirkdawson** [comment]
Planning to use the Freereg slot on the week of August 12 to conduct the clean up

**Comment by Captainkirkdawson** [comment]
Uncertain if it is still required until after creation of #1236
