### ISSUE TITLE
Wildcard Search Support

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#192]

**Comment by benwbrum** [comment]
I'm not quite sure why this is assigned to @PatReynolds, as we have a pretty good idea of what needs to be done.  Reassigning to myself and removing the "research" from the title.

**Comment by benwbrum** [comment]
Any opinion on whether to throw an error message on `wildcard + soundex` to the user, or just to quietly remove the soundex part of the search?

**Comment by Sherlock21** [comment]
I like your long analysis at post 3. And I agree with your approach in it as satisfying the user's view of what's needed. -[ if that's not too presumptive of me!]
As to the question on your last post above this, I would just do whichever is the easiest to write and to process. soundex + wild card of single or multiple type is meaningless. The user need to bring a bit of logic to the situation.
 My view would be not tell, nor ask, just do as you suggest.

**Comment by edickens** [comment]
Quietly do not process Soundex, but keep the box ticked.  People do
    not like their entry to disappear with no reason.
    
    E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 26/10/2015 16:15, Ben W. Brumfield
      wrote:
    
    
      Any opinion on whether to throw an error message on wildcard
          + soundex to the user, or just to quietly remove the
        soundex part of the search?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
I would not error the situation. I would ignore the soundex. I would however tell the user that we had so done in the About this search.

**Comment by benwbrum** [comment]
Thank you all -- it sounds like there is a consensus, and I will implement Kirk's suggestion.

A note about performance from [the MongoDB docs](https://docs.mongodb.org/manual/reference/operator/query/regex/):
* A regular expression is a “prefix expression” if it starts with a caret (^) or a left anchor (\A), followed by a string of simple symbols. For example, the regex /^abc.*/ will be optimized by matching only against the values from the index that start with abc.

* Additionally, while /^a/, /^a.*/, and /^a.*$/ match equivalent strings, they have different performance characteristics. All of these expressions use an index if an appropriate index exists; however, /^a.*/, and /^a.*$/ are slower. /^a/ can stop scanning after matching the prefix.

**Comment by benwbrum** [comment]
I've completed wildcard search with a single exception:  "ends-with" searches on e.g. "*ohn *mith".  These work, but will not use an index efficiently.  Here are the options I see:

* _Full support_: In this case, we jump through some hoops in the record transformations to create additional fields and indexes for ends-with searches.  Researchers can use ends-with searches anywhere they can use name searches at present.   Full support might double or quadruple the number of indexes on the `search_records` collection.
* _Limited support_: In this case, we use existing data structures but restrict users to searches criteria that will use indexes to narrow down the records searched.  I.e. we create an index on `chapman_code, place_id, search_date` and require the researcher to select a place (including nearby) for ends-with wildcard searches.  This would give users full liberty to do whatever kinds of wildcard searches they want, so long as they have a restricted set of records to search against.
* _No support_: Don't allow ends-with searches at all; just allow begins-with and infix searches.

Opinions, @captainkirkdawson, @edickens, @EmJayFry, @Sherlock21?

**Comment by Captainkirkdawson** [comment]
I do not like Full support; we already have performance issue with the current number of indexes.

I do like the limited support option. I don't believe we should support wide open searching with wildcards period. It is there to assist the researcher who knows what they are trying to do. Limiting to a specific place is quite appropriate

**Comment by Sherlock21** [comment]
I would like to support Wild Card searching both at the start or at the end of surnames [ not together thought!!]

But perhaps we should discuss WHY do users need a Wild card search? 
My own reason, as a researcher, is to pick up those Transcriptions which:-
end in [*] or
end in a multitude of mis-spellinds by the clerk which would escape Soundex.

But as it has the problems which you refer to:
I prefer always to Manage By Facts, 
So, is it reasonable to ask: how many surnames in the whole database have  an ending in * or [*] or ? which other wise will never get picked up.
Then we can see the value of putting in the extra effort in one of the ways that you suggest.

I would come down on the side of Ben's "Limited support" at this stage, unless the figures indicate otherwise.

**Comment by benwbrum** [comment]
Matching UCF characters in the transcripts is covered in another story.

I can easily imagine searching for the surname "Br?mfield" to pick up
common variations in spelling, or (in Eric's case) "Di*ns" for "Dickens",
"Diggins", etc.  Similarly I can imagine looking for "Sara*" to match both
"Sarah" and "Sara", or "Eli?abeth" for the s/z alternation.

Consensus seems to be in favor of the limited support option, which I hope
to complete today.

Ben

**Comment by benwbrum** [comment]
One additional note: it turns out that (limited) wildcard support only
required changes to code, and does not require a separate database build.
This means we can--if desired--ship it before the other 1.4 search engine
changes.  We might want to do that for performance testing, even if we
don't announce the feature.

**Comment by Captainkirkdawson** [comment]
That is encouraging. Likely we should kick it about on t3 first

**Comment by benwbrum** [comment]
That's a good idea.

Because the index work proved a bit harder than expected, and because you
folks gave me some clear guidance on the limited support option, the state
of the `wildcard` branch of MyopicVicar on my dev box is thus:

* Wildcard search works as described: begins-with and infix searches work
as normal name searches; ends-with searches are restricted to place-based
searches.
* Witness searching is supported, but requires a rebuild to populate the
new witness names.  Deploying the code as-is should not interfere with
other searches, though a witness search will not find any records (until a
rebuild is done).

I've done some work on UCF this week, but most of that has been focused on
creating a representative dataset for the automated integration tests, so
none of that is committed.

Given that, here's what I propose:
* I commit and push the last changes to the `wildcard` branch to support
wildcard and witness search.
* I push the `wildcard` branch to GitHub.
* I merge the `wildcard` branch into `master` on my dev box.
* I disable the _witness_ checkbox on the search form in `master`, thereby
hiding the witness functionality.
* I push `master` to Github
* We deploy `master` onto test3 when it won't interfere with ongoing 1.3
work.  (Note that that interference worry might be better applied to the
previous step.)
* We do perfomance testing for wildcard searches on test3 at leisure.
* We deploy to production when we're satisfied that the wildcard/witness
work didn't break anything else.
* After we're happy with everything and feel it's ready, we announce
wildcard support.  That might be bundled with announcements about other
functionality, but it might not.

**Comment by Captainkirkdawson** [comment]
Would it not be better to deploy as a branch initially on t3?

I am having to commit bug fixes to master on a daily basis and would not
want the wildcard to go out until we have done some testing

Do we know what we have to do to get witness names in place. Is it a full
rebuild or can we do an update for just witness records? Marriages are only
15% of our records and less than 50% have witnesses so seems pointless to
do a full rebuild when less than 10% of the records are affected. Mind you
given the issues around indexes who knows

K

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by benwbrum** [comment]
Thanks, Kirk -- that adds some information I was not previously aware of regarding the activity on `master` and the production servers now.

Upon reflection, I think the right thing for me to do is avoid merging `wildcard` into `master`, but instead branch off of `wildcard` for the UCF work, so that we can test the wildcard code in a stable state without interference from my UCF development.  That means that we can deploy `wildcard` as you suggest on test3 whenever development slows down enough that we don't need it for ongoing bug-fixes.

**Comment by Sherlock21** [comment]
If its not much extra trouble, shipping it out on its own helps testing - there is only one new variable, and no cross actions to worry about.

Ericb

**Comment by Captainkirkdawson** [comment]
Ben

It is perhaps unfortunate that it is only now that we are moving transcribers over to FR that coordinators are themselves starting to do far more cleanup on FR. These are exposing a number of hidden issues most of which seem to be related to navigating to documents that have been relocated. There are also critical usability issues that are being addressed. eg eliminating paging in favour of scrolling.
Anyway I far prefer your revised proposal to keep wildcard as a separate branch and commit that. We can bring it into t3 when we want and also still use t3 for testing master code changes as well by switching between branches. The latter is important as my development framework does not always exhibit code problems.

**Comment by benwbrum** [comment]
Okay.  After fighting with the indexing code most of the morning, I finally
got it working and pushed it to github, along with a pull request.

**Comment by Captainkirkdawson** [comment]
PS what is the wildcard?

**Comment by benwbrum** [comment]
Oh, it supports `*` and `?` the same way filesystem glob wildcards do.  If you think it's useful, I could add support for SQL-like `_` and `%`.  In fact, it will handle any regular expression that doesn't contain `*` or `?`, so someone could search for "Br[uo]mfield" and it'd match any records with "Brumfield" or "Bromfield".

**Comment by Captainkirkdawson** [comment]
Sounds like a far more powerful approach that a straight forward single character!! 

In which case Alison needs to be an early adopter/tester so we get the documentation right

**Comment by benwbrum** [comment]
I agree.

One thing to consider (and I'd actually be tempted to get @benlaurie's
opinion here as well) is this:  If we're providing support for full
javascript regular expressions as a side-effect of the wildcard work,
should we document it?  Most users will be well served by `?` and `*`
wildcards, so generally only programmers will use regular expression syntax.

If we do document it, should we catch users who have entered real regular
expressions and avoid munging their search criteria by the
wildcard-to-regex converter?  In other words, if a user has searched for
`"di.*ns"`, the wildcard code will change that to `/di..*ns/`, which is not
the same regex at all.  (Most users will search for `"di*ns"` and get
`/di.*ns/`, which is correct.)  In these cases, we can look for patterns
that indicate that the user is actually using regex syntax (like `.*`, for
example).  Similarly, `"br?mfield"` is converted to `/br\wmfield/`, which
could play havoc with a user who wants to search for `/joh?nathan/` with
the question mark indicating optionality of the `h`.

I'm not sure how much effort to go to for a pretty obscure use case.

**Comment by Sherlock21** [comment]
But this is going into the totally public domain isn't it?
So don't you need to guard against the professional hacker types and those who like fiddling with: I wonder what if....."

I dont have an opinion on the specific question,as its out of my frame. hut my comment on here now, is something I have strong views on preventing.

**Comment by benwbrum** [comment]
I'm not too terribly worried about bad regular expressions, though perhaps
I should be.  Certainly it's something worth testing -- what happens if a
user puts in a mal-formed regex?  Are there regular expressions that can
cause performance problems?

Good points, Eric.

**Comment by dougkdev** [comment]
I would guess that the number of people wanting to do full regex searches
is very small.  Wildcard searches are probably powerful enough for > 99.9%
of normal use cases, and if someone is technical enough to enter formal
regex expressions, they are probably also technical enough to just do a
second or third wildcard search to pick up any results that wouldn't be
returned by their first wildcard search.  I think the wildcard support you
have already provided is a powerful and useful tool, and one that is
familiar to more users.  Even though it might be easy to add support on the
backend, I am not sure there is much to be gained by providing the full
regex functionality and documenting it unless there multiple users who
request it.

If we aren't already, we may need to require a minimum number of
non-wildcard characters when wildcards are used.  An overly general
wildcard like "s*" or "*" is probably not something we want people doing
and may cause a performance problem since I believe mongo applies the 250
limit after the find, not during.

**Comment by edickens** [comment]
We agreed to exclude " * " otherwise someone could access the whole 
database, although now they cannot do it as it will bring up more than 
250 records and so not work.  I think it should be excluded if only to 
stop wasted searches.  E

**Comment by edickens** [comment]
I have not been following this thread that carefully.  But will Wildcard 
also be applied to Firstnames?  I would have thought that just entering 
the first letter would be enough.  A researcher should leave the 
firstname blank for the first attempt, and only when they have narrowed 
it down by place and year, and they still have too many results, should 
they need to enter a wildcard and then just the first letter.  Leaving 
blank is equivalent to " * ".  E

**Comment by AlOneill** [comment]
Noted! Will adopt when test3 is readied...

**Comment by benwbrum** [comment]
Wildcards will work on both first names and last names.  Doing a wildcard
search on "*" will be interpreted as an "ends-with" search, and will force
the user to select a place.  If we need to prevent users from doing a
search on "*" (which seems like it might be wise) then I can add that
prohibition.

**Comment by edickens** [comment]
Some clarification please.
We are providing wildcard input by the researcher, but are we finding 
all the records which have been entered using UCF/Wildcard, such as 
including a lastname of " * "?
In the older registers there are many entries where much of the name is 
unreadable, if not all, but there is a date and other information.
I'll create a new story if you think this has not been addressed.  E

**Comment by benwbrum** [comment]
This story only covers researcher-entered wildcards for searching.  Story
#42 covers transcriber-entered UCF, which is not covered by this story.  It
is my next priority, modulo input from the group.

**Comment by AlOneill** [comment]
Initial thoughts after playing with the wildcard search: the automatic * at the end of a wildcard search string will need careful explaining. For example, whereas Jacob* finds Jacob, Jacobs, Jacobson, Jacoby, etc., Jacob? fails to find Jacob.

Contrast this with Davi?s which finds Davis, Davies, Davidson.

I guess the simplest thing to say (if I have it correctly!) would be:  "Do not use ? at the *end* of a name."

PS Am loving the way that, with a bit of tinkering, the wildcard search is finding so many of the odd spellings of some surnames. Grand job Ben!

**Comment by Sherlock21** [comment]
But the ? at the end has traditionally been used if the Transcriber was a bit unsure if they had read the whole name correctly.
so we need to advise better or we need to ban the ? and revisit all the existing records?

**Comment by Captainkirkdawson** [comment]
Very interesting performance stats

![wildcard](https://cloud.githubusercontent.com/assets/2874694/11054752/0e8998fc-872d-11e5-8ddf-05ca6402b1b5.JPG)
