### ISSUE TITLE
21 Page on other sources of transcriptions

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1922]
Draft written.  Needs input from coords, and Kirk on best download format from internet archive.

P21

**Comment by richpomfret** [comment]
Looks like this is done (or tell us otherwise @AlOneill or @PatReynolds. Shall flag for deployment.

**Comment by AlOneill** [comment]
TODO: Need to add menus to the page and update menus on other pages under "Info for Coords".

Will make it my next task.

**Comment by AlOneill** [comment]
Menu added to pages and other menus in Coord Help updated. "DRAFT" removed from page title.

Ready for syncing to live.

**Comment by richpomfret** [comment]
Deployed to live, so let's close.
