### ISSUE TITLE
Revise letter to incumbents

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1949]
Include letter from the Rev McGregor.

**Comment by PatReynolds** [comment]
Added links to new letters, and amended text on "Obtaining the approval of The Church of England."  page - in test 3 for comments/improvements.

**Comment by Captainkirkdawson** [comment]
The draft is OK but are the draft letters available?

**Comment by Captainkirkdawson** [comment]
Found the letters. Made a couple of formatting changes which am passing to you.

Only comment to make is the expression 'commonest' in use in the UK now. In my youth it was 'most common'
