### ISSUE TITLE
Add remove button to list of messages (was My own replies to Contacts and Feedbacks appearing in my Messages on landing page)

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1950]
Every reply I send to a Feedback or Contact gets added to my list of messages on the landing page. This is not useful. The reply is accessible in the Feedback / Contact message system, so all I do is delete them from my list. If I don't keep on top of it, the list rapidly grows and is time consuming to deal with:

![Capture.jpg](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/85f4ab6c-77a1-4185-8f42-5d81e3ada507)

The list of messages on the landing page should only be INCOMING messages sent directly to me by others.

E0 U3 S8 C6: P17

**Comment by Captainkirkdawson** [comment]
It was done as a way of confirming to you that the message had actually be sent

**Comment by SteveBiggs** [comment]
I see. But now we have confidence that the message system is working, perhaps we could stop sending the copy to the sender? Alternatively, could an auto-delete after say, 24 hours be applied to them just to give enough time to check it was sent?

**Comment by edickens** [comment]
I think I would like to retain the sending of copies back to the sender, but I like Steve's idea of deleting them from "My messages" list after 24 hours.
On the same theme, I do not Archive a message after I have replied to it in case the recipient sends a reply and this will not be part of the message system, if they have just done "Reply".  So to save me doing an occasional tidy up of messages sent to me (which is not an easy job) then an automatic Archive of any message and its replies which has been replied to more than a month ago.

**Comment by Captainkirkdawson** [comment]
Added. Available for review on test3 reg/cen

**Comment by SteveBiggs** [comment]
Tested and working OK in test3.

**Comment by Captainkirkdawson** [comment]
Deployed to production

**Comment by SteveBiggs** [comment]
Tested and working OK in production
