### ISSUE TITLE
Retain contact information if validation error

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1958]
Currently in the creation of a New Contact document if rails validation finds an error it goes back to the new action and destroys what was previously submitted.
With an edit the information is retained; the form code is ready to display the previous input. We need to pass the contact id back to new and use that. If nothing passed then we created new contact

**Comment by richpomfret** [comment]
Ready for testing on TEST3.

**Comment by richpomfret** [comment]
May be an issue for screen reading software - @AlOneill to take a look.

**Comment by SteveBiggs** [comment]
I'm not sure how to test this. The live FR website seems to work the same way as test3. If I click submit having not filled in a box, I get a prompt  telling me I must fill it in and all other information in the form is retained:
![image](https://user-images.githubusercontent.com/25303607/60674962-350d4300-9e73-11e9-96ad-5559db95e668.png)

Should the live site behave differently to test3?

**Comment by ShemJM** [comment]
@SteveBiggs Hi Steve, you can add a novalidate attribute to the form in the browser developer tools, then you will be able to submit without filling in the fields. ![image.png](https://images.zenhubusercontent.com/5cf698a776a8fc3bbb13e904/84e5449c-bc23-4bd2-899f-51768700be68)

**Comment by Captainkirkdawson** [comment]
Deployed

**Comment by AlOneill** [comment]
Need to check for accessibility by screen-reader software: will do ASAP (for me).

**Comment by AlOneill** [comment]
Good — VoiceOver, the built-in Mac screen-reader app, picks up the "Please fill out this field" pop-ups straight away.

Unfortunately, this does not guarantee that other screen-readers will do the same, but it is very promising.

Maybe some adventurous soul would be willing to try the built-in Windows screen-reader, the name of which escapes me? My main advice is be sure you know how to quit the reader app *before* you start; and make sure you open a fresh Contact Us page once you are in the app.

@ShemJM What did you use in the markup to get the screen-reader's attention. We will need something similar to ensure the Cookie Notice is accessible (unless that has been done and I missed it).

**Comment by ShemJM** [comment]
I have just tested this using the windows screen-reader(Narrator). If a field is missing it says "field name, editing text, alert."

When I disable the validation and submit a form with errors, the screen reader does nothing to notify the user that the submission failed. It just says the name of the page "Contact Us, FreeREG"

I will see if I can fix this.

@AlOneill I did not do anything regarding screen-readers in the markup, the validation is done by the browser.

**Comment by AlOneill** [comment]
@ShemJM Thanks. So, VoiceOver and Narrator are OK, as long as in-browser validation is not disabled — an unlikely situation?

In contrast to those two, which look at any part of a screen from the outside (as it were), some screen-reader apps *are* the browser and may not be capable of in-browser validation: will see what I can find out. And, will be interested to see what can be improved here.

**Comment by Captainkirkdawson** [comment]
The whole point of this story was to provide validation in the event that there was no browser validation.

**Comment by richpomfret** [comment]
In which case, we can consider this complete and deploy.
