### ISSUE TITLE
Add information on contacting CoE incumbents to Coords help

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1960]
Pat to make new versions of .doc (as .rtf) as not properly displaying in open office.

**Comment by PatReynolds** [comment]
Added links to new letters, and amended text on "Obtaining the approval of The Church of England." page - in test 3 for comments/improvements.

**Comment by richpomfret** [comment]
@PatReynolds to upload to TEST3.

**Comment by PatReynolds** [comment]
On test3

**Comment by richpomfret** [comment]
@AlOneill to sprinkle magic over it.

**Comment by AlOneill** [comment]
@PatReynolds @richpomfret Have made a start, but am not sure how to handle the email address in the final paragraph: we do not publish email addresses in plain sight, even if it is text and not a working link.

**Comment by PatReynolds** [comment]
Thanks,  @AlOneill  I have replaced the email address with a request to use the contact system.

**Comment by AlOneill** [comment]
Magic sprinkled: page ready for deployment.

**Comment by AlOneill** [comment]
The letters open in OpenOffice (which can read .docx files), but the images are distorted.

![image](https://user-images.githubusercontent.com/14852554/64922775-f678fa80-d7ca-11e9-990b-82b75b7eef37.png)

**Comment by PatReynolds** [comment]
Oh _bother_.  Have now installed word as an app, and both letters are displaying fine.   I will make .rft versions and see if they have the same problem.

**Comment by AlOneill** [comment]
Sound.

There are some spacing issues, in OO at least, around the foot of the first page. I found them rather distracting.

The two black paras have different line-spacing: in the top one they are too close. The bottom para is good.

On the other hand, line-spacing for the teal question is too loose: a 2-line block in heading sizes will need adjusting to look best.

Lastly, the text in the footer is too close to the grey rule above it

**Comment by AlOneill** [comment]
Oops, forgot the screen-shot:

![Information_for_Incumbents_of_Church_of_England_Parishes__first_contact_version__v4_docx_-_OpenOffice_Writer.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/cf88a6fa-9897-4515-adab-f27439a197ff)

**Comment by PatReynolds** [comment]
Not sure that formatting is being downloaded into RTF - sent to Alison to check.

**Comment by richpomfret** [comment]
@PatReynolds to send to @Captainkirkdawson and @richpomfret

**Comment by PatReynolds** [comment]
Sent to @Captainkirkdawson and @richpomfret

**Comment by PatReynolds** [comment]
Sent link to @Captainkirkdawson and @richpomfret for testing.  Noted that it is now 34 mb.  This is the original:

**Comment by Captainkirkdawson** [comment]
A pdf version is less than a MB

**Comment by AlOneill** [comment]
@Captainkirkdawson These letters are for Coords to edit — how likely is it that a Coord will have access to suitable software for editing a PDF document?

@PatReynolds How much does the use of colour contribute to the file size? (Have not seen newest version, but there were several colours in a previous version.)

**Comment by Captainkirkdawson** [comment]
The issue of size is caused using a rtf file with scanned images in it

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by PatReynolds** [comment]
Thanks @Captainkirkdawson I will make a PDF with the q+a and letter from CoE in it, and then only the letter to the incumbent will be a RTF.

**Comment by PatReynolds** [comment]
Thanks for your changes, @Captainkirkdawson . I have changed the wording of the page to reflect the separate pdf with the CoE letter and FAQ.  Ready for you to check, @AlOneill

**Comment by AlOneill** [comment]
This how the first-contact letter looks when opened in OpenOffice. The top is clearly awry.

![Information_for_Incumbents_of_Church_of_England_Parishes__first_contact_version__v5_rtf_-_OO-top](https://user-images.githubusercontent.com/14852554/69351352-14ebee00-0c73-11ea-8dc7-98b459ba404d.png)
.
.
.

![Information_for_Incumbents_of_Church_of_England_Parishes__first_contact_version__v5_rtf_-_OO-bottom](https://user-images.githubusercontent.com/14852554/69351386-27febe00-0c73-11ea-97f4-8167bb6eceb3.png)

**Comment by AlOneill** [comment]
The second-contact letter has similar issues.

**Comment by richpomfret** [comment]
@richpomfret to help with Office export to rtf.

**Comment by richpomfret** [comment]
Sent through rtf files exported via Word to @PatReynolds and @AlOneill to scan for any issues (or to tell me they actually wanted it in an entirely different format).

**Comment by PatReynolds** [comment]
I cannot review as do not have word, and does not open in my machine as "too large".

Suggest we abandon rtf, and just have word and gdoc.

**Comment by richpomfret** [comment]
@richpomfret review how it looks in Word (rtf version).

**Comment by richpomfret** [comment]
@PatReynolds letter 1 and 2 (rtf) look just fine in my ancient (2011) version of Word. The oddly large version I created actually ended up causing an error, so I'd delete it. The Gdocs also opened/looked fine upon being downloaded and opened too. Reassigned back to you.

**Comment by PatReynolds** [comment]
Implemented and ready for testing (links, spelling, etc.)

**Comment by PatReynolds** [comment]
@DeniseColbert  could you review, please?

**Comment by AlOneill** [comment]
The links all appear to work as expected: have not done any checking of the documents themselves.
