### ISSUE TITLE
Entries with no date or point of reference

### ISSUE THREAD

**Issue by suffolkroots** [FreeUKGen/MyopicVicar#1969]
Many entries in MIs have no date or any point of reference from which to estimate a date which therefore must remain blank.
Clicking the zero date button is fruitless, as no amendments can be made
They will stay in the list with "zero dates" even though TWYS and perfectly correct.
Perhaps this is something else which we can usefully start ignoring.

**Comment by PatReynolds** [comment]
Experiment with what happens with an asterisk or question mark.

**Comment by richpomfret** [comment]
Treated the same as zero date.

**Comment by Captainkirkdawson** [comment]
What action is required. We could ignore the zero year test for MI register entries

**Comment by suffolkroots** [comment]
Yes, ignore for MIs and possibly consider ignoring for all types.

**Comment by edickens** [comment]
We need to agree on what will happen in a Search where the researcher has put in a Date range.
This will be the same as presenting UCF years to researchers, but "No Year" needs to be included in the routine.
The Researchers' Help will need updating.

**Comment by suffolkroots** [comment]
How then do we explain this to researchers?
![Zero date](https://user-images.githubusercontent.com/10379655/71673006-6c4fa480-2d6f-11ea-9044-42d16bcdb680.jpg)

**Comment by SteveBiggs** [comment]
In reality, we do not know what the earliest date is so perhaps the researcher's view should display 'Unknown' where there is a zero date?

**Comment by PatReynolds** [comment]
Deciision is to implement "Unknown" rather than "0" in this display.

**Comment by suffolkroots** [comment]
Not acceptable. "Unknown" suggests that we have a rather insouciant view of our data. We know the first and last date of the file---why not admit them? Also, where is the sense of "not knowing" the first date, when we apparently "know" the last date, which might also not be the real last date?

Captainkirkdawson suggests that the zero year test could be ignored for MIs. This would seem acceptable.

**Comment by SteveBiggs** [comment]
I think we are talking at cross purposes. The suggestion to put 'Unknown' is in the individual search result when a researcher finds a MI result that we do not know the date of. This would be a true and accurate statement - the date is unknown.

In the range of years through the 'Transcriptions' path, I agree that the First date should be the earliest known date of the records in the register. However, this would still give us a problem if the register ONLY contains MIs with no dates in which case we truly would not know the First or the Last date. Perhaps we should leave them blank in that case? Thoughts?

**Comment by suffolkroots** [comment]
Captainkirkdawson suggests that the zero year test could be ignored for MIs. This would seem acceptable.

**Comment by SteveBiggs** [comment]
I agree with ignoring the zero year test Ali, but if ALL of the entries have no date then what should be displayed to the researcher for the First and Last date?

**Comment by suffolkroots** [comment]
There are some with no date whatsoever, but the majority have dates. 
They are however death dates, not burial dates.

As dates of death are not returned atm, perhaps this is what needs 
sorting out, so that the first and last of entered dates could be 
displayed to the researcher.


>

**Comment by PatReynolds** [comment]
@SteveBiggs to clarify proposed solution with Suffolk roots

**Comment by SteveBiggs** [comment]
The first and last recorded death dates are now being shown in the Records table and the blank dates are ignored:

![image](https://user-images.githubusercontent.com/25303607/119364957-5ebdf600-bca7-11eb-8f87-9a3002070a64.png)

We could ignore the zero year test for MI register entries but I would not want to remove it for all types as that would take away the ability to find entries that should have an estimated year or blank lines in batches.

**Comment by suffolkroots** [comment]
@SteveBiggs this looks good thankyou.

**Comment by SteveBiggs** [comment]
Need to implement removal of zero year test for MI type.

**Comment by DeniseColbert** [comment]
@Vino-S to take a look

**Comment by SteveBiggs** [comment]
MI files with zero dates are still being flagged with a blue box but the Start year shows the earliest recorded year in the file:

![image.png](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/a68ef0f7-8fe8-4c01-b092-e07b02f06f16)

This seems like a good implementation to me.
