### ISSUE TITLE
Statistics calculator error

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1977]
Statistics calculator displaying to too many decimal places for percentage of records = Open Data.  (Answer is almost 42! (41.78 %).

**Comment by PatReynolds** [comment]
@PatReynolds to add screenshot

**Comment by Captainkirkdawson** [comment]
Displaying percentages as integers

**Comment by Captainkirkdawson** [comment]
For review on test3

**Comment by richpomfret** [comment]
@PatReynolds to take a look/test.

**Comment by PatReynolds** [comment]
Fixed, thank you.

**Comment by Captainkirkdawson** [comment]
@PatReynolds can you please review reg #1977

**Comment by PatReynolds** [comment]
Statistics caluculator error fixed, thank you.
