### ISSUE TITLE
Link to Statistics calculator missing from Manage User ID button on Free REG 

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1978]
Issue #708 on FreeCEN also on FreeREG.

**Comment by Captainkirkdawson** [comment]
In what way is it missing?
![trans1.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/94d776bb-afda-49d2-b920-833454ac2a4c)

**Comment by richpomfret** [comment]
@PatReynolds to check this again.

**Comment by PatReynolds** [comment]
Like this.

![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/435ef65e-284f-430a-b65e-0e8dfe77bc82)

**Comment by Captainkirkdawson** [comment]
With that clarification issue detected. Old code for when we did not have the Display Userid Option.

**Comment by richpomfret** [comment]
@PatReynolds to test (assuming it is now ready to test).

**Comment by PatReynolds** [comment]
There and working fine (as a  link) in Test3.  Issue with results - will post to slack.
