### ISSUE TITLE
The Transcriptions coverage code was never updated to conform with the GDPR

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1983]

**Comment by Captainkirkdawson** [comment]
This will include the reimplementation of #1396 that introduced the removal of the credit  from the search detail display. It went walk abouts in the great merge.

**Comment by Captainkirkdawson** [comment]
It will also include #1387 that displays the register credit field in the search detail

**Comment by Captainkirkdawson** [comment]
Code updated.
In search record detail we display transcriber and give credit to register credit field content if present #1387 and #1386
In transcription we have removed contributions field as we would never have this free form field follow GDPR. The Transcriber credit is the Userid information. It follows wishes of transcriber as contained in userid. ie uses pseudonym or no display if requested.
Cleaned up displays so that only fields with information are displayed
Deployed to test3.
Transcriptions collection rebuilt on test3

**Comment by Captainkirkdawson** [comment]
@PatReynolds @SteveBiggs Urgent review needed so it can be deployed. to production

**Comment by PatReynolds** [comment]
https://test3.freereg.org.uk/search_records/58187b57e93790eb7fe8dd4f/susanna-alcock-thomas-mould-marriage-warwickshire-wolfhampcote-1702-10-11?locale=en shows two names - have both consented?

Only fields with information are displayed.

**Comment by Captainkirkdawson** [comment]
All I see is one transcriber name

Transcribed by | Ken Davies

He has not requested anonymity

**Comment by PatReynolds** [comment]
I now see my problem (not a FreeREG issue): if logged in, I get to see the line ID.
Now tested again (not logged in) and works fine, as do the two Isabel INMANS of Tadcaster, so fine for release.
