### ISSUE TITLE
'Contacts' button has vanished from my Actions list (Denise)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#1984]

**Comment by richpomfret** [comment]
Looks like this is specific to Denise.

**Comment by Captainkirkdawson** [comment]
It would seem that engagements coordinator has not been assigned that role.
Adding

**Comment by Captainkirkdawson** [comment]
Available for review on test3

**Comment by DeniseColbert** [comment]
Tested; all good. Thanks @Captainkirkdawson
