### ISSUE TITLE
question arising from online transcription discussion: How do all the currently transcribed “images” get incorporated into this system so that it is uniform?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1988]
See comment on draft document in #1751

Possilble answers
a) no, they won't
b) as per new images?

**Comment by richpomfret** [comment]
@Captainkirkdawson can you comment on this.

**Comment by PatReynolds** [comment]
Conclusion: yes it is good for this to happen, and simply uses the existing system.

Need to encourage those with images to upload them.  Need to reassure that this is not a violation of their t&c.

**Comment by edickens** [comment]
Kirk,
You said that you, and perhaps Julie, have a lot of NFK images that have been transcribed and that are not on the image server.  Are they viewable through FamilySearch or Ancestry?  If so, there is no point in loading them onto our image server.  If you have a spreadsheet of what they are, do you think that we should create a Source with no Image Groups, but with a note to say "See FS/Ancestry if you need to check the images".  I am happy to create these sources if you send me the spreadsheet.  Eric D

**Comment by PatReynolds** [comment]
'See ..." should only be used where we have express permission to do so, or where the images are available without the viewer having to declare that they are only accessing them for personal use (as is the case with some images at the TNA, for example).

**Comment by edickens** [comment]
Pat.  I agree, but it is very useful to the researcher to know where to find the images if we do not have permission.  This subject is not really to do with online transcription which can only be done from images for which we have permission, even if they are not on our image server.
