### ISSUE TITLE
Confirm that results are not returned if maximum results number is exceeded

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1989]
We should not return results if the maximum number of search results is exceeded because there is NO systematic order in the results available up to the maximum.

**Comment by Sherlock21** [comment]
I agree with you. 
I had thought that the present arrangement was not giving a logical sub set, but I could not prove it.

**Comment by Sherlock21** [comment]
I agree with you. 
I had thought that the present arrangement was not giving a logical sub set, but I could not prove it.

**Comment by Captainkirkdawson** [comment]
Confirmed that in the great merge we had changed the test on Maximum number of results to > from >= The mongodb software update changed how this feature worked such that it no longer returned a number >. Hence if the limit was reached we would display the first maximum number of results. This would change depending upon how the various shards responded and in what order. Have reverted the test back to >=
@Sherlock21 could you please test on test3 if you have the time. The test has to involve a search that will provide 500 or more results.

**Comment by SteveBiggs** [comment]
I did a search on test3:
![image](https://user-images.githubusercontent.com/25303607/61521658-9e12c000-aa08-11e9-97fb-f686d3b81a7e.png)
so looks good.

But I then did a search on the live site:
![image](https://user-images.githubusercontent.com/25303607/61521717-c0a4d900-aa08-11e9-8c77-13078c3928b8.png)
which also looks good. Has it been deployed already?

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  it has not been deployed. Look at the message and you will see the text is changed.
Suggest on production you try a search for Cooper burial in Somerset. It will give 499 results (wrong) put a year limit 1600 1800 it will give 499 results (wrong) put a year limit 1600 1850 it will give 499 results (wrong and different from preceding search).  Repeat on test3 and all will give max message

**Comment by SteveBiggs** [comment]
Yes I saw the different text, but why did my search not return 499 viewable results on production?

**Comment by Captainkirkdawson** [comment]
Did you try the searches I suggested that demonstrated the issue?

**Comment by Sherlock21** [comment]
I did not have any time to do your test until just now.
but done it with the following results:-

in Test3
NFK/ SMITH/ BAPTISMS .    no date restriction & no forename

Result: almost instant return of: too many search results.  -exceeds toe 500 display limit etc.... 
Did again as a Revise Search., with from 1850 to 1860
-again TOO MANY RESULTS etc.

note there is in both these cases, there iOS not a partial listing.

Reduced the reach period to 1850/1850 and search succeeded.  325 results returned.\\

SO: seems you have cracked it! A sensible result now - if you pardon the grammar -not intended to be critical.

I would go forward to production now with this.

**Comment by Sherlock21** [comment]
I did not have any time to do your test until just now.
but done it with the following results:-

in Test3
NFK/ SMITH/ BAPTISMS .    no date restriction & no forename

Result: almost instant return of: too many search results.  -exceeds toe 500 display limit etc.... 
Did again as a Revise Search., with from 1850 to 1860
-again TOO MANY RESULTS etc.

note there is in both these cases, there iOS not a partial listing.

Reduced the reach period to 1850/1850 and search succeeded.  325 results returned.\\

SO: seems you have cracked it! A sensible result now - if you pardon the grammar -not intended to be critical.

I would go forward to production now with this.

**Comment by SteveBiggs** [comment]
@Captainkirkdawson wrote - Did you try the searches I suggested that demonstrated the issue?

Yes, but I was asking why it's not a consistent problem. Perhaps it no longer matters.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs because of the way results are handled and 500 results is not greater than a 500 limit ; this a case to a degree of trust me if I make the test >= then we do not have an issue
