### ISSUE TITLE
Update advice to Coordinators with best practices for offline editing.

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1992]
Update advice for coordinators on best practices for editing batches off line that strongly recommends editing and replacing a transcriber's batches in the transcribe's folder.
Note that personal information may be made visible, if this is not done.

E0 U10 S 9 C6: P25

**Comment by PatReynolds** [comment]
@SteveBiggs and @edickens I have two notes from yesterday which may be to include here - "upload rather than replace" and "Batch upload (not using online transcription) should ask 'Using images on the server?'" - do either/both belong here - or need re-writing/clarification?  If they do, or if they belong to other stories, please let me know and I will edit here and there, as needed.

**Comment by edickens** [comment]
@PatReynolds The questions as to whether the images are on the server or not, and if they have been obtained legally, only needs to be asked at "Upload".  Once a batch has been started, adding more records uses "Replace" and the image information will not have changed, so no need to ask again.

**Comment by PatReynolds** [comment]
I've had a look at current information for Coordinators, and there's nothing about uploading on behalf of a transcriber (please let me know if I've missed something.

Draft here for new section: https://docs.google.com/document/d/16VAFm8Swgvejnliu8HFITa5OZ1-sZjSdCzjC1dpcVvI/edit?usp=sharing

**Comment by SteveBiggs** [comment]
@PatReynolds I don't understand why you refer to the image system. When a coord uploads a file on behalf of a transcriber, they just select the transcriber's userid and upload to that. Nothing to do with the image system.

**Comment by PatReynolds** [comment]
sorry @SteveBiggs - misled by Eric mentioning images!  What's the correct name 'file management system'?

**Comment by PatReynolds** [comment]
Just need to say 'adding to user ID'.

**Comment by PatReynolds** [comment]
Put in warning that file name is unique.

**Comment by AlOneill** [comment]
@PatReynolds Where are we with this? The Google doc seems to need some revision …

The current information that refers to coordinators who upload on behalf of one of their transcribers can be found on [**Info for Coords**](https://test3.freereg.org.uk/cms/information-for-coordinators), in the 2nd bullet-point at the top of the page.

The basic info about Uploading/Replacing/Editing is under Info for Transcribers: it includes [**a note for coordinators**](https://test3.freereg.org.uk/cms/information-for-transcribers/file-and-batch-actions#edit):

"Note for Coordinators: if you are making a lot of changes on behalf of a transcriber, Download the file, make the changes in a text editor, then Replace it."

The current instruction does rather imply rather than make crystal-clear. It would be logical to expand/upgrade what is there already and perhaps consolidate the 2 bits of information — where would be best?

**Comment by PatReynolds** [comment]
HI @AlOneill I am about to start work on this, but realised that copying the html from the current page on test3 and pasting that into a copy strips the html of leading spaces ... making it look a mess / harder to edit.

Perhaps we need to change the protocol to:
Make a copy of the page call it 'DRAFT awaiting name' (other names are available)
Rename the original page  with "[the original name] DRAFT
Rename the copy with the original name, and move both into the correct positions (the new version on top, old version just below.
what do you think?

**Comment by AlOneill** [comment]
@PatReynolds I'm puzzled — it works for me. I click in HTML pane, do select all (can't remember how to do on Windows, but it is cmd-A on a Mac), then copy, then paste in new page.

Is there an example of the issue I can look at? Maybe the HTML got messed up before you tried to copy it??

Suggested protocol change should not be necessary (and looks confusing!), unless I'm missing something!

**Comment by PatReynolds** [comment]
OK, no issue with spaces being lost now!  

But I can't find any instructions about offline editing to update! @SteveBiggs can you point me at the page, and heading name?

**Comment by AlOneill** [comment]
@PatReynolds See my comment of 16 Jul about where the current information is.

**Comment by PatReynolds** [comment]
@AlOneill  the link goes to 'best practices' on the Information for Transcribers page, not the Information for Coords page.   Shoul,d I add the 'best-practices' information (currently only in draft) to the Information to Coords page, and update it as per this story?

**Comment by AlOneill** [comment]
@PatReynolds I'm a little lost as to what you want to move or put where. If you are suggesting that the current note to coords, on the "File and batch actions" page be moved to the Info for Coords, then we need to make it clear, on F & B actions, where coords need to look for that additional info. Does that make sense?

**Comment by PatReynolds** [comment]
I want to add a little text: You are strongly recommended tp  edit or replace a transcriber's batches ONLY in the transcribe's folder.  If you edit or replace elsewhere, the transcriber's personal information may be made visible to the public.

I want to add it to the Coordinators help.

**Comment by edickens** [comment]
@SteveBiggs  Is Pat correct when she says in the last comment "If you edit offline and upload elsewhere, or replace elsewhere, the transcriber's personal information may be made visible to the public."?  My understanding is that the personal information shown is only from the UserID associated with the batch and then only if the UserID has the appropriate fields set.  The Header is not used.  It may be differrent in the other projects.

**Comment by SteveBiggs** [comment]
@edickens yes that's how it should work, but we've had reports from Michael Clarke that the wrong name was showing in the 'Transcribed by' field in some cases.

**Comment by edickens** [comment]
But amending the Help pages to get around a bug is not the solution, unless you state that it is a temporary because of a the bug.  Pat does say "may be made visible" so perhaps is correct.

**Comment by SteveBiggs** [comment]
I didn't suggest it was. I just answered your question, Eric.

**Comment by PatReynolds** [comment]
_Souldn't_ be a problem, so no need for this addition to help, and closting.
