### ISSUE TITLE
Credit at Church and Place level

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1997]
We have a field in the register collection that allows us to assign credit information. Should we also have such a field at the church and place level? It would ONLY be visible to a researcher in Transcriptions displays.

**Comment by edickens** [comment]
Is this to thank the person who donated the images or the transcription, or is it the transcriber, or is it to thank the Church for giving permission?
I think that at Register Type is sufficient.
We have the Church website field, which is a good way to promote the Church.
