### ISSUE TITLE
Server security backups

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1998]
I am uploading a lot of images direct to the image server ready for FreeBMD2 or the Wills package.  But before I delete them off my computer permanently, I want to be sure that they have been backed up from the server's processors.  There should be copies made and held in a separate location should there for example be a fire.
Assuming this is the case, when are these copies taken?  Should I wait a week after uploading before deleting from my computer?  I have put in many hours converting and uploading these images and do not want it to be wasted.
The same principle should be applied to the website for images and batches that are uploaded.

**Comment by Sherlock21** [comment]
yes. Eric D, that is a very valid point and we all would benefit from knowing what the 'secure backup' policy and timescales are please.- even if for commercial reasons, you don't say exactly WHERE the backup stores are.

**Comment by edickens** [comment]
I wouldn't mind if the backup is on The Cloud.  But a lot of storage is needed so will be expensive.

**Comment by Captainkirkdawson** [comment]
We have a separate server that contains a copy of the main image server files. They are kept in sync on a regular basis. It already has all your OTH images. You should feel free to clean your computer as and when required.

**Comment by edickens** [comment]
Having been involved with mainframe security many years ago, this would not be enough security.
One backup server would be sufficient in today's world of reliability, but it does not cover for the whole data centre being lost, either from being closed down or fire.  The backup server should be in a different location owned by a different business.

**Comment by PatReynolds** [comment]
Is the server (main or back up) also synced to Glacier on AWS?  (For those for whom Glacier on AWS is a new thing: we have a grant from AWS which we have to spend on their services, among other things a very very cheap back-up that costs a lot if we have to extract the data.  The Glacier data is in Europe, but not the same part as the main servers.

**Comment by richpomfret** [comment]
Yes image server is backed up on Glacier. :)
