### ISSUE TITLE
Breadcrumb issues with Zero years

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2000]
If you start here:
![image](https://user-images.githubusercontent.com/25303607/61805622-04934600-ae2e-11e9-8850-5abb06efd5bc.png)
and click 'Listing of zero year entries' you see this:
![image](https://user-images.githubusercontent.com/25303607/61805670-1c6aca00-ae2e-11e9-80ea-c903dffdb3a6.png)

So the breadcrumb will not get you back to the previous screen.

E1, U4, S8, C7: P20

**Comment by Captainkirkdawson** [comment]
@SteveBiggs Improved breadcrumbs are on test3 for evaluation. May not be perfect but likely better

**Comment by SteveBiggs** [comment]
Yes this specific case has now been fixed. I'll carry on testing other cases for a while.

**Comment by SteveBiggs** [comment]
Have not found any other breadcrumbs problems so can close.
