### ISSUE TITLE
Investigate: UserID 'Eiddac' email address appears in the Log of bounced emails everyday even though the ID has been set as inactive.

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2027]
Need to find whether this is coming from a test or live.
E U 3 S 5 C7: P15

**Comment by SteveBiggs** [comment]
Eiddac has no files uploaded and cannot be contacted, but we are unable to destroy the userID as reported in #1240

**Comment by SteveBiggs** [comment]
FYI, I have changed Eiddac's email address and taken control of the userid to stop the bounces, but the cause still needs addressing.

**Comment by edickens** [comment]
I don't think that the bounced list is getting cleared.  There would not be an email send every day.

**Comment by SteveBiggs** [comment]
Every day I receive 2 bounce log emails to my Sys Admin address. I never thought much about it but now I believe one of them is being sent from one of the test sites rather than live, and that one is not being cleared which is why we get the same Eiddac bounce log every day. (Eiddac is inactive on all sites)

I have changed my SC email address on each test site so that when I get the next SC email of the bounce, I'll know which site is sending it.
