### ISSUE TITLE
Investigate the addition of all churches

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2028]
E0 U 3 5 C5: P13

Pat/Rich to see if Pelagios data contains such a listing.

**Comment by Sherlock21** [comment]
Being the person responsible for adding new Church Names to Placenames, I have had this debate before - in the early days - and concluded that there was no way of doing bulk Church Names. and doing the job be hand was a waste of CC's and my time. Furthermore, the result would be a massive list of churches that users would have to wade through to get down to the one being shout.
And for what benefit?

The sources that we used for Placenames was a different kettle of fish entirely.

**Comment by SteveBiggs** [comment]
This arose from a discussion about how we could identify where no registers exist for certain churches to avoid researchers searching for something they will never find. That led onto the question of identifying places where there is no church hence no registers. If all churches were added, we would know where there is a place with truly no church. Kirk said he would look into the possibility of automating the addition of churches.

**Comment by Captainkirkdawson** [comment]
The Church of England has a list of all Churches on their Website. It provides names a location near a place. Clearly behind that must be a complete list. I have written to see if we can obtain access to the complete list.
In the meantime I have been able to extract a partial list of churches from Genuki. Unfortunately it is location based rather than county based. 
I propose to see if there are means of matching that with our place based collection. It will never be fully automatic but may be able to reduce the amount of grunt work required.

**Comment by Captainkirkdawson** [comment]
The list that I have extracted has about 20,000 churches that while Anglican do contain Church of Scotland and Church of Ireland. The formatting of the file is inconsistent in terms of fields. It took me 6 hrs to get 10% of the place names into the same field. So estimate it would take  a further 60 hrs just to do that part. Whether the place names match ours is unclear. The formatting of the church names is inconsistent often having  'The church of' or  'The parish church of' or St X's church' The pluralization is inconsistent as is the "and". There are many Mission churches and other oddities.
It seems that several months of clean up would be required. 
It is likely better to try to find a volunteer who extracts the church names one by one from known places in the CoE search engine

**Comment by edickens** [comment]
This looks like a manual operation.  So is it possible to split up your file by County?  If so can you send the parts to the relevant CC?  In this way the work can be divided up.

**Comment by suffolkroots** [comment]
@edickens ---this still applies---ATM churches and place codes for WRY are added/assigned when needed. If I had a hundred years and a hundred hands------

**Comment by Captainkirkdawson** [comment]
Unfortunately the county is NOT part of the information. In most cases it is just church name, place name and denomination. Other information is often provided such as prior name, street name etc.

**Comment by SteveBiggs** [comment]
I believe many CCs have an Excel spreadsheet with places and churches that was created some time ago to set up the 3-letter place/church codes. Here is an extract for Sussex:
![image](https://user-images.githubusercontent.com/25303607/69060629-94798300-0a0f-11ea-92bb-1927b0a76ae5.png)

It would need a bit of cleaning up, but would it be easier to automate from this format?

**Comment by suffolkroots** [comment]
@SteveBiggs I have such data but it is nowhere near complete, this is why I add church and code when needed, as do you I understand.

**Comment by edickens** [comment]
The reason for wanting to add all Churches was so that we could add Gap or Embargo information for all those Churches where we do not have transcriptions.
Just this week we have had a researcher ask why Cardiff transcriptions were not there.  So if "Not done yet" or "We don't have the register images" had been there, then the researcher would be able to find that information for themselves.  Looking at "Transcriptions" will show that we have not transcribed Cardiff, but not the reason.  So how important is it to give a reason?

**Comment by SteveBiggs** [comment]
Isn't the main reason for implementing the GAP feature to give a reason for the gap?

**Comment by PatReynolds** [comment]
Not sure what the link to policies was!  Probably linked to the wrong story.

Yes, the Pelagios data includes both Civil Parishes and Ecclesiastical Parishes.

**Comment by richpomfret** [comment]
@PatReynolds to fetch the data and we can then see if it is suitable.

**Comment by PatReynolds** [comment]
Asked Richard 20/1/2020

**Comment by richardofsussex** [comment]
Turns out that neither the AUO data nor the online C of E list of parishes includes the names of churches (although the C of E list does have all incumbents, with dates!). I have a query outstanding with a C of E contact, which may yield something more useful.  

Meanwhile, an enquiry to English Heritage about their near-defunct PastScape resource yielded a useful CSV file with county, parish and lat long for all the 'church' entries they hold. (This resource is created from an Ancient Monuments perspective, so some of them will be too old to be useful for our purposes. Some are not churches at all.  Still ...)  I have mapped 3242 entries to Kirk's 'no churches' spreadsheet, where there is an exact match on parish, and either an exact match on county or a simple mapping from our 'old county' to the modern units found in the EH data.  This will leave a number of entries where the parish name is recorded differently between the two resources. Kirk has given me the file of the churches we do have, and I need to consider how to use all this information to home in efficiently on the remaining 'churches we don't have'. One problem I have is there are so many places in our file, most of them irrelevant.

**Comment by Captainkirkdawson** [comment]
Definitely very encouraging. One part of this exercise is be able to cull
the places for which where are no known churches


Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Unless there is a very good reason to cull the places with no Church, I would prefer to keep them.  A Church may be founded there, but better is the fact that we can say that there is no Church if someone was born there, is shown in FreeBMD and the researcher is trying to find FreeREG entries when there never can be any.

**Comment by Sherlock21** [comment]
This whole idea of removing place names that don't have a church, seems to me to be a case of 'the tail wagging the dog'/
The list shown by Steve above looks like just a list of C of E churches Therefore, what are you doing with all the other denominations? Under the implied rule they would be deleted. then who is going to recreate them when someone finds a Methodist Chapel or a Catholic church? 

Not me for sure!

And out of interest, let me record that when Jo for example asks me where a certain Chapel goes, it can take me half a day to research and find out the answer, so that we can use the (ready existing) right place name. And that's an easy one.

**Comment by suffolkroots** [comment]
@Sherlock21 Well said!

**Comment by suffolkroots** [comment]
@richardofsussex "One problem I have is there are so many places in our file, most of them irrelevant"
Please could you expand on this startling piece of mis-information?

**Comment by richardofsussex** [comment]
Sorry, folks: I didn't mean to cause alarm. I was looking at the file from the perspective of the task I had taken on, which was to find churches which aren't currently in our database. Therefore I was assuming all the places I was given to look at would be parishes. As there are about 12,500 parishes, and nearly double that number of places without churches, I was simply observing that most of them could not be relevant to my matching task. I wasn't proposing that we get rid of them from the database.

What I _would_ like us to do is to create a coherent geographical database which puts all of these places into context (both civil and ecclesiastical). I'm hoping that the AUO data will help us with this task. For example, it includes information on what type of unit a place represents and what larger and smaller places it is contained in and contains - all we have is place name, county and lat/long.  However, to make use of the AUO we will have to match 'our' places to their data.

**Comment by Captainkirkdawson** [comment]
Let me assure you, like Richard has done, that this is and never was any suggestion that we would remove any place from our list of places as part of this project. 
Places have never ever been removed or deleted. Some, as a result of the excellent work by @Sherlock21, were "disabled" and therefore not displayed. These were places that were not nor ever had been places of habitation e.g. a crossing of 2 roads.
The purpose of this story and the work Richard is undertaking is to see if we can add churches where they are known to exist to places in an automatic manner to avoid coordinators having to do this task manually

**Comment by Sherlock21** [comment]
Richard: Please don't refer to Places as Parishes. The words are not interchangeable as far as FreeReg  is concerned.
 If a Place name does just happen to be a Parish of the same name, then that's not relevant to FreeReg./
We  have a set of displayed PLACE NAMES.

My own view - from the point of a CC and a Transciber - is that it works well left alone - and just add the churches as they start being transcribed. Adding churches any other way will never be 100% accurate and would only lead to confusion with no benefit.

**Comment by Sherlock21** [comment]
Kirk
Your input just above is welcomed. The tone of the discussion before that point had given a very different impression of the Managemen's intentions, which I am lease to see will not be the outcome.

**Comment by Sherlock21** [comment]
Richard
What is AUO as you use above?
And what is wrong with the present FR Placenames that require them to be brought into line with this AUO?
As you acknowledge, FR places are uniquely identified both by County/ Place Name (as the populous identifies with) and by their GeoLocation code.

And what doe you man please by Places within Places? Who's terminology are you using in your version of "place" here.

**Comment by Captainkirkdawson** [comment]
@Sherlock21 I believe you and others will agree that we have the technology to manage and display UK baptisms, marriages, and burials for family historians around the world, we in general have or can get transcribers. 
We have as @edickens noted just surpassed 47 million records. However there are many 10s of millions yet to be transcribed and made available. I hope you will agree that one of the major obstacles facing us is the availability of parish registers from which transcriptions can be made. 
We believe there are many people out there who are likely willing to assist us in obtaining access to those registers if they know what registers we need to complete our work. What are the gaps in our database; not just gaps within a register but gaps in the availability of registers; gaps in the availability of registers for specific churches and other religious institutions for specific places.

Hence we are transforming the Transcriptions reports to cover not just those records we also where we have gaps.  i.e. those places and churches where we simply do not have the registers to transcribe for one reason or another. (You know the issues as well as I do). We hope that this will assist us in finding people willing to work with us to fill those gaps.
Through your excellent work we have the places; we need to add now information on the churches and registers where there are gaps in our availability. We know that many coordinators may have this information but they have indicated that the work in getting that onto the system is just too much hence this project. Can we find sources of digitized information on for a start all CoE churches. That is what Richard is attempting.

**Comment by SteveBiggs** [comment]
I mentioned way back in this thread that most counties already have an Excel spreadsheet listing most CoE churches against places. As has been pointed out, these sheets are not complete but they do cover a large amount of the CoE churches in each county. 

Currently most CC's create the church for a place from this spreadsheet as they assign the first batch for it. Surely we could extract the list of churches from these sheets to automatically create them as a first step?

**Comment by Captainkirkdawson** [comment]
@SteveBiggs Could you or @edickens collect them and  I can use them. But I am sure there are many counties where they do not exist.

**Comment by suffolkroots** [comment]
In the interests of not re-inventing the wheel, may I point out that there already is an available list of GAPs, in the case of WRY these gaps are mostly where we have no data, ROs being very wary of infringing their agreement with Ancestry.  Obtaining such data would seem to be infinitely more important than attempting to add all churches. I attach an example clip from the beginning of WRY places list. Also, best of luck with industrial areas and their squillions of Methodist churches, not to mention Catholic, Quaker, Jewish etc etc.

![image](https://user-images.githubusercontent.com/10379655/73915606-9edf4680-48b3-11ea-855c-462d6ac65fd9.png)

**Comment by richardofsussex** [comment]
I'm now on holiday for a week: back next Wednesday. Will pick up the conversation then.

**Comment by SteveBiggs** [comment]
Hi Ali, you are right and you will have seen that we have a number of open issues related to obtaining more registers for transcription including creating a 'SWAT' team to focus on approaching ROs and churches for permission. That exercise would not involve Kirk or other developers who are looking at this issue.

Also, we don't know from the current GAP list which places do and don't have churches. If we could populate at least the CoE churches automatically, we would immediately know where we need to target to get the data.

**Comment by suffolkroots** [comment]
@SteveBiggs Richard's statement concerns me greatly---"What I would like us to do is to create a coherent geographical database which puts all of these places into context (both civil and ecclesiastical)" 

We already have a "coherent geographical database" thanks to EricB, no need for CEN-related irrelevant Ecclesiastical context.  

If churches could be added automatically to the places database we have already, that would be ideal.

**Comment by suffolkroots** [comment]
"If churches could be added automatically to the places database we have already, that would be ideal"

As long as existing churches were not over-written in the process.

**Comment by Captainkirkdawson** [comment]
@suffolkroots if you provide me with a listing of all churches for places in WRY I can develop the task to add them to the database and we would at least have a start. I promise not to overwrite anything. Presume that these are COE.
Then if @SteveBiggs or @edickens could get other coordinators to do the same we can move forward. 
That still leaves us with the counties where there are no such lists for which we have to find other sources.

**Comment by Sherlock21** [comment]
Kirk:
your long statement about 9 items back does clarify the intension. and lays to rest the wrong that was generated by some of the comments earlier on in the dialogue, which then gave rise to my opposition to what came over as a scheme to add all church names and then  remove all place names that had no church.

**Comment by suffolkroots** [comment]
Kirk I am sorry but I do not have a listing of all churches for places in WRY. My list is nowhere near comprehensive. If that was the case, I would have added them myself over time.

**Comment by Captainkirkdawson** [comment]
@suffolkroots Would you be willing just to send me what churches you have and we will add those that are not there now. Save you the time and then we will also know what churches we do not need to find as part of this story.

**Comment by suffolkroots** [comment]
Kirk within the next few days I will send a file which may fit your purpose.

**Comment by richardofsussex** [comment]
Has anyone approached the Methodists to get a list of their churches? Their advanced web map https://www.methodist.org.uk/for-churches/statistics-for-mission/methodist-church-advanced-map/ clearly has relevant data behind it. (If no-one has, I'll do it.)

**Comment by richardofsussex** [comment]
... and the Congregational Church: https://www.congregational.org.uk/find-a-church/church-finder ?

**Comment by richardofsussex** [comment]
Baptists: https://www.baptist.org.uk/Groups/221161/Church_Finder.aspx ? (I'll stop now!)

**Comment by suffolkroots** [comment]
@richardofsussex  FYO I am a grandmother and I do know how to suck eggs. I would refer you to WYAS Nonconformist collections guide etc. Most counties have such. If Kirk really wants his list, no more of this please.

**Comment by richpomfret** [comment]
@Captainkirkdawson to write a rake task here.

**Comment by suffolkroots** [comment]
Please could it be possible for CCs to download/add churches/reload the County Content File?
![County content file](https://user-images.githubusercontent.com/10379655/79064627-6fc5c680-7ca2-11ea-9393-67f138534510.jpg)
