### ISSUE TITLE
Freeze FR1 for researchers when FR2 can provide the search and then no more FR1 updates are needed.

### ISSUE THREAD

**Issue by graphiclunarkid** [FreeUKGen/MyopicVicar#203]
Once F2 is available for researchers we should redirect people from F1 to F2 for this purpose.

**Comment by Captainkirkdawson** [comment]
This is not a development story; developers do nothing for this

**Comment by edickens** [comment]
Program changes are needed in FR1.  But
      perhaps just html changes.  Needs discussion.
      EricD
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 02/01/2015 03:46, Kirk Dawson wrote:
    
    
      This is not a development story; developers do nothing for this
      —
        Reply to this email directly or view
          it on GitHub.
