### ISSUE TITLE
County is missing from Wikitee citations from the generator

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2033]
Format no loninger to specification: models:

Free UK Genealogy, “Register of unspecified type, St Mary’s Church, Kingsclere, Hampshire” database, FreeREG (https://www.freereg.org.uk) : accessed 4 January 2018), [data about person(s)]; citing Register number 658

Free UK Genealogy, “Memorial at Cemetery, Trawden, Lancashire” database, FreeREG (https://www.freereg.org.uk) : accessed 4 January 2018), [data about person(s)];  citing Grave number 551

E2 U 4 S9 C7: P22

**Comment by ShemJM** [comment]
Sorry, could you give me an example of what the citation should be? I can not see anything in the code that is missing from the generated citation.

**Comment by PatReynolds** [comment]
The citations above are for 
https://www.freereg.org.uk/search_records/5818370de93790ec8bee6d03/john-smith-baptism-hampshire-kingsclere-1692-08-13?locale=en (this is a different person in the same church register, hence line number being different - I couldn' remember who I'd looked for the first time).
https://www.freereg.org.uk/search_records/58182836e93790ec75d5868f (this is a different person in the same graveyard, hence grave number being different - I couldn't remember who I'd looked for the first time).

**Comment by ShemJM** [comment]
Is the county still missing?

**Comment by PatReynolds** [comment]
Hi Shem,

Yes, county is still missing: e.g. 

Piddington : St John the Baptist : Register of unspecified type : "Parish Register" database, FreeREG (https://www.freereg.org.uk/search_records/58188eece93790eca35a8b87 : viewed 24 Feb 2020) baptism Richard Whitebread 08 Jul 1759

Should be
Northamptonshire, Piddington , St John the Baptist : Register of unspecified type : "Parish Register" database, FreeREG (https://www.freereg.org.uk/search_records/58188eece93790eca35a8b87 : viewed 24 Feb 2020) baptism Richard Whitebread 08 Jul 1759

**Comment by PatReynolds** [comment]
Citation format now with Wikitree users for approval.

**Comment by PatReynolds** [comment]
@IanHMartin citation format  now approved - https://docs.google.com/document/d/19a9U3Y1JnvFJsMmooPrVxXC-uSWWUFAD6G_NGxelPBE/edit?usp=sharing

**Comment by DeniseColbert** [comment]
@IanHMartin to push change to Test3 so we can test the fix.

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by PatReynolds** [comment]
@PatReynolds to test, thank you @IanHMartin

**Comment by IanHMartin** [comment]
Hi Vino

 

I’ve tested about 20 records across all three types and it’s working in all these cases.

 

What happens next?

 

Thanks

Ian

**Comment by PatReynolds** [comment]
Hi @IanHMartin next you move this to 'needs review', and tag me (or whoever opened the story, or is appropriate to test for some other reason) so we go and test it.... 

Lincolnshire : Gainsborough : All Saints : : "Parish Register" database, FreeREG (https://test3.freereg.org.uk/search_records/58188dffe93790ec8ba9068a : viewed 1 Mar 2021) baptism Richard Alcock 02 Jan 1830 is the first I looked at, could you remove the second colon after All Saints, please?

Many thanks, Pat

**Comment by DeniseColbert** [comment]
Vino thinks this was deployed but not closed; closing
