### ISSUE TITLE
Download a list of batches by Place/Church/Register Type

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#2043]
Although some CCs have marked images as Transcribed from records that they keep, it is not easy to do this on the website.  It is necessary to look at the transcribed Batches and the years that they cover, while at the same time looking at the Image Group and marking that as Transcribed if necessary.
So either the "Manage Images" action needs to be in a separate Tab, or it should be possible to download a list of batches by Place/Church/Register Type for a county showing the entry type and range of years in each.  This could be saved to a spreadsheet for reference.  The website under Manage Images and the Spreadsheet can be open at the same time thus avoiding switching between batch and image actions within the website.

E0 U2 S8 C6: P16

**Comment by SteveBiggs** [comment]
I do that kind of dual viewing of the website with two separate browsers - e.g. Chrome for image actions and Edge for batches in split or dual screen. That way, the cookies are kept separate too so breadcrumbs don't get confused.

**Comment by edickens** [comment]
That will work on your computer, but if you are using the same UserID in both versions that you have open, will the server get in a muddle?  Probably OK if you only make changes with one of the versions that you have open.  I don't think this is the best solution.

**Comment by edickens** [comment]
If we are going to leave it that the CC has to open the two reports in different browsers and not create one report in a separate tab, then this technique needs to go into the Help.  Not sure where, but it is to do with matching images to batches.

**Comment by Captainkirkdawson** [comment]
Sorry @edickens I had failed to save the post I had written which I needed the review on.
I am concerned that attempting to create the download in realtime will timeout for counties with large numbers of batches. Some of them have 10,000 + batches. What I suggested was adding an Action for both SC CC that submitted a rake task to prepare the report as a CSV file and then email it to them. It would run in the background

**Comment by edickens** [comment]
Yes.  That is much better as having a spreadsheets lets the CC mark it up as they work through it.
Originally I think they had to ask you to run the rake task, but if you can set it up as an Action, that would be better.

**Comment by Sherlock21** [comment]
If you do the job as just described above could you please put DM on the list of persons who can request it?

**Comment by edickens** [comment]
I am waiting on this story in order to find out what images we need in SOM so that @PatReynolds can try to get us access to them.  Even a SOM version offline would help.

**Comment by Captainkirkdawson** [comment]
Have sent a first cut at the requested report to the Erics and Steve for evaluation

**Comment by Captainkirkdawson** [comment]
EricD and Steve replied it was useful.
It should be noted the report can be used for multiple requirements. The image server one, to identify those **places for which there are no churches** and those for those **churches which we have no registers**.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs @edickens @Sherlock21 A new option has been added in the Manage Counties Action.

Its called County Content Report.  This submits an offline task to extract a report of all Places, Churches Registers and Files. 

Some 5 -10 minutes after requesting the report the person will receive the report as a comma separated text file

For each file it reports the owner, the number of records, the min year and the max year.

No church, No registers and No files statements are included where this is the case.

The report has multiple uses including which images have been transcribed, the places for which we have no churches, the registers which have yet to be transcribed etc.

It is available on test3 for evaluation.

**Comment by SteveBiggs** [comment]
Tested it and it arrived in my inbox within a minute or so. It actually came as a .txt file but I simply renamed it to .csv to make it viewable in Excel. Seems to have what we need:
![image](https://user-images.githubusercontent.com/25303607/69836179-130bc700-123f-11ea-88c8-a970feb65c19.png)

**Comment by edickens** [comment]
May I suggest that you add an "Are you sure - Yes/No" with a brief description as above.  If in a hurry it could be easy to hit the wrong button by mistake.  At present the report processes as soon as you hit the button.

**Comment by SteveBiggs** [comment]
Good idea, Eric.

**Comment by SteveBiggs** [comment]
It's also useful for scanning down for likely data errors - e.g. I can see a range of 1550-1971 in one file straightaway.

**Comment by Captainkirkdawson** [comment]
@edickens I cannot put a challenge on the list of subactions in an action or the actions themselves. You may observe that there are none on any of them.
The only way of doing that is to have a Reports action rather than the specific report as currently coded. The Reports section would have the reports available for generation. Those specific reports could have a challenge. Of course at this point there is only 1 report and someone is going to complain about too much clicking to get to it!!. At the same time we may want to add additional reports in the future

**Comment by Captainkirkdawson** [comment]
@SteveBiggs the mail out is done from a common function (the same one as sends out other logs) I will look to see if we can retain the original file name and file type

**Comment by edickens** [comment]
Having a "Reports" section then listing them would be my preference.

**Comment by Captainkirkdawson** [comment]
@edickens @SteveBiggs @Sherlock21 

Added an Offline Reports action for Manage Counties. Only current report is the County Content Report.

The attachment is now a csv file type.

Running on test3.

**Comment by edickens** [comment]
Great.  Works fine.

Do you have any other Rake tasks that could be useful?

**Comment by Captainkirkdawson** [comment]
@AlOneill I have added a new section on Offline Reports in the Coordinator Actions {DRAFT] page for your review and editing as appropriate on test3

**Comment by SteveBiggs** [comment]
Yes works fine.

**Comment by AlOneill** [comment]
@Captainkirkdawson Thank you. The **page** is now ready for review but *not* yet ready for deployment — I'll remove DRAFT from the title once passed by @SteveBiggs or @edickens.

View at: https://test3.freereg.org.uk/cms/information-for-coordinators/coordinator-actions-draft#reports

**Comment by edickens** [comment]
Help report is fine.  TY

**Comment by AlOneill** [comment]
@edickens Thank you.

@Captainkirkdawson Page now ready for deployment.

**Comment by Captainkirkdawson** [comment]
@AlOneill TY will go when we deploy the software
