### ISSUE TITLE
Remove freereg2_session cookie

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2044]
This cookie is a carry over back to the days where there was an individual mongodb database instance on each server. In those days there was no replication and the search query and its results were only on the server on which they were generated.

With the current server architecture having a common mongodb database it is not required. 

We should ask Lemon to remove it from HAProxy

E0 U3 S5 C6: P14

**Comment by lemon-ukgen** [comment]
Cookie removed!

**Comment by Captainkirkdawson** [comment]
Thank you
