### ISSUE TITLE
Give researchers the ability to see a list of gaps

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/MyopicVicar#2052]
As per GAP requirements.

Questions (similar to those in story #2054, are they  the same answers): 

Is this a separate table to the number of records transcribed table, or combined with that?

Looking at the data that might be in table, do you need word GAP and the year?  Perhaps a short version of the reason?  

E2 U6 S8 C6:P22

**Comment by Captainkirkdawson** [comment]
Deployed to test3.

**Comment by edickens** [comment]
Looks fine.  Researchers'  Help under Transcriptions needs something about this.

**Comment by Captainkirkdawson** [comment]
Deployed
