### ISSUE TITLE
Source documents exist on the image server for registers which are not (yet) on the server

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2053]
Fix bug in system - ignore earlier text in square brackets!!! [This story is to implement a possible solution to the point raised on "Document Current Status of GAP (Freereg story 1931)" - if this won't work/a better solution is available, open story to implement that, and close this.

Point: No one can create a gap document because access is rejected if there is no gap document

Resolve this by creating an image (e.g. a pdf) that says 'This is a placeholder for the Register of Births, St Mary the Virgin, Dodford, Northamptonshire, 1720-1793; the photographs of this register were taken by a volunteer, and are not available to view on the image server, to view, please contact the county coordinator' (or other appropriate text).]

E2 U6 S8 C7:P23

**Comment by edickens** [comment]
Every image on the image server, and these are the source documents, has to have a Source within a Register Type.  So in your example above, this information needs to be tagged to the Register Type.  Perhaps a new field, the GAP field, and this is displayed to a researcher if they select this Place and Church.  This gets over the access problem of only CC being able to access images.  But let Kirk think up the best solution when he returns.

**Comment by Captainkirkdawson** [comment]
IMO the system allows CCs to create register and link them to the image server. Fail to see any requirement.

Bev made a mistake by linking the gap to the source not to the register. I have changed it so that the gap belongs to a register. There are many many gaps not related to anything we may may not have on the image server.

I believe this can be closed.

**Comment by PatReynolds** [comment]
Thanks, Kirk, I agree.
