### ISSUE TITLE
Revise list of GAP reasons, based on what is to be displayed and how

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2056]
E.g. one current reason is "Many pages unreadable due to bleed through"  

Two questions: what is 'many' - why not record that _one_ page or more is unsuitable, with text

Page(s) unsuitable - bleedthrough

E2 U6 S8 C6:P22

**Comment by edickens** [comment]
I have the means to add reasons at any time...
![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/bdc73307-433d-4aa3-a105-806c96430d1a)
and this is the current list...
![Capture1.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/f4c8485a-cc65-4152-9643-51e72d34bbb0)

**Comment by edickens** [comment]
Updated.

**Comment by Captainkirkdawson** [comment]
@edickens are there any more reasons to be added as we are about to deploy?

**Comment by edickens** [comment]
Not that I can think of now.  But Sysadmin can add them if necessary.

**Comment by Captainkirkdawson** [comment]
@PatReynolds @edickens Surely we need to add reasons for when we do not have access to registers?

**Comment by edickens** [comment]
Have added that to the list.

**Comment by PatReynolds** [comment]
@edickens  this is what I see on test3:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/6a867d92-d1eb-48e1-a8d6-b643215941d0)

Please add your list above, plus
No Access (Register with CRO)
No Access (Register with Church) 
No Access (custiodian/owner untraced)

Thanks, Pat

**Comment by edickens** [comment]
This is what is on Production:-

![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/69ce8e27-5749-4a73-ae8f-93e3d8056ebb)

I will add what you suggest.
