### ISSUE TITLE
Snags when trying to delete 6 files for STS

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#2057]
I was asked to delete the following 6 files that are larger than the STS's CC permissions.

STSNEWBU1 (JOYNSONJ)
STSNEWBA (JOYNSON)
STSWVMba10 (davejo)
STSWALBU2 (Steffy)
STSCODBA50 (oxydolstaffs)
STSDARBU33 (jonny)

STSNEWBA (JOYNSON) was a locked file, so I asked the STS CC to unlock it for me first, This he did, using the L/U tab on the user;s batches. OK.
So I try to delete the first on my list, only to get the system message:
"The physical file entry no longer exists. Perhaps you have already deleted it. "
this message is also received for all the others above in turn - including the one the CC just unlocked.

Yet if i look at the file data, I can read it all.

If I pick a person at random, from STSNEWBA (joynsonj) -say Joshua BIRKS baptised 1707 in STS and do a standard Researcher search for hon, it returns the right person, with details that he is in Row3 of the file Joynsonj/STSNEWBA.csv.
-whilst the attempt to delete this file generates my error message above.

ALL 6 files listed above are in the same position.

**Comment by Sherlock21** [comment]
ps:I did manage to delete other STS files today, without any problems.

**Comment by richpomfret** [comment]
@Captainkirkdawson to take a look and clean it up.

**Comment by Captainkirkdawson** [comment]
Deleted as requested but please be careful with the userids. 
JOYNSONJ in 1 was really Joynsonj
JOYNSON in 2 was really Joynsonj and
jonny in 6 was Jonny

Case is important

**Comment by Sherlock21** [comment]
thank you Kirk
and yes I will triple check emails.

eb
On 25 Oct 2019, at 22:50, Kirk Dawson <notifications@github.com> wrote:

Deleted as requested but please be careful with the userids.
JOYNSONJ in 1 was really Joynsonj
JOYNSON in 2 was really Joynsonj and
jonny in 6 was Jonny

Case is important
