### ISSUE TITLE
Add 'Policies' to the member actions

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2058]
To include security policy, volunteer handbook and code of conduct.

**Comment by PatReynolds** [comment]
E3 U6 S6 C8: P23

**Comment by Captainkirkdawson** [comment]
Code written; need to add page to refinery in both REG and CEN to provide the description and links; will do when deployment notes have been processed

**Comment by richpomfret** [comment]
Tested on TEST3 and looks fine - it now just needs actual content in there - all it currently says is 'holding'. @PatReynolds can you add the required text? @Captainkirkdawson we will need the text in there before I run the test3>production refinery update again.

**Comment by Captainkirkdawson** [comment]
Refinery page s are there and action is there. Just needs content to be added

**Comment by PatReynolds** [comment]
Adding content is #2028, closing this again.
