### ISSUE TITLE
Document the use of GAP for cc and transcribers.

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2059]
E2 U6 S8 C5:P21

**Comment by Captainkirkdawson** [comment]
The document is available at
https://drive.google.com/file/d/1FBa33h0UQMupQ8jsvDD4l6-NO2pdwsHb/view?usp=sharing

**Comment by AlOneill** [comment]
Coord "Help" done. Have restructured text to make more compact.

Next: Transcriber pages.

**Comment by AlOneill** [comment]
Transcriber pages also done.

NB Pages are not completely ready for sync — will make ready once changes are approved.

**Comment by Captainkirkdawson** [comment]
@AlOneill have reviewed and is OK by me @PatReynolds please review and/or sign off on Gap changes for CC and Transcriber

**Comment by AlOneill** [comment]
Refinery pages tidied and checked: ready for sync.

**Comment by Captainkirkdawson** [comment]
Deployed
