### ISSUE TITLE
Individual record can be marked as embargoed by Trustee decision

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2066]

**Comment by Captainkirkdawson** [comment]
As noted  in basic epic
**Who has authority to edit the field? Do we need to record the REASON for the change?**

**Comment by edickens** [comment]
I think it is more likely that we would respond to a message from a researcher who has asked that their entry is embargoed.  So CommsCoord or SysAdmin and above?
Reason would be useful in case someone asks in future years why the entry is embargoed.

**Comment by SteveBiggs** [comment]
Does every researcher request for embargo need to go to the Trustees for a decision as implied by the title? If so, perhaps only Sys Admin should be able to edit.

**Comment by richpomfret** [comment]
Individual records only embargoed by sys admin - or unembargoed.

**Comment by Captainkirkdawson** [comment]
Integrated with 2073
