### ISSUE TITLE
CC can indicate length of embargo, by record type, for a given register

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2069]

**Comment by Captainkirkdawson** [comment]
Either a fixed period of years can be applied or a specific end date in the future

**Comment by PatReynolds** [comment]
I do not see any types of record to select:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/6defcc9d-c9ac-48a4-b6e3-0340143efe92)
- I was expecting to see Ba Ma Bu as per instructions.

I tried without filling in, and then editing, but there was no option to edit type of record.
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/30d4426d-0714-47ea-8df1-753f3bf09ab1)

**Comment by Captainkirkdawson** [comment]
@PatReynolds you should NEVER see an empty Record Type UNLESS you have established a rule for each. I have no idea why it occurred it should never happen. I see @Sherlock21 must have encountered the same issue. 
I restarted the server and it seems to be OK now
I corrected your and ericb's rules created in error.
Raised a story to make sure that one cannot create a rule without a record type

**Comment by PatReynolds** [comment]
This error has not recurred, although I have since reloaded batches, without encountering it. I think this issue can, therefore, be closed.
