### ISSUE TITLE
Automatic release of records from embargo once closed period has ended

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2070]

**Comment by PatReynolds** [comment]
This could be done annually - e.g. on 1/1/2020, all baptisms from a register which have reached 100 years (i.e. 1/1/1919 to 31/12/1919 or daily (or any other suitable time period).

**Comment by edickens** [comment]
Annual will be fine as sometimes there is only a year in the date field.  But the actual number of years back from now needs to be based on the embargo that has been set up.
Should there be a default if no embargo ise set?  I suggest not.  At present if there is an embargo the entries have not been uploaded.  We have to assume that, with no embargo system now, anything that has been uploaded is not under an embargo.  If the entries have been uploaded in error, then an embargo should be set and these entries already uploaded can be hidden.

**Comment by PatReynolds** [comment]
Actual number of years of the embargo will be set as implemented in #1759 
The default if no embargo is set is nothing. In future, all entries can be uploaded, and those with embargos will just wait their day in the system.  This will mean less work for coordinators, and removes the potential for transcriptions being accidentally lost.

**Comment by Captainkirkdawson** [comment]
It is proposed that there be a once a year rake clean up task.
