### ISSUE TITLE
CC can record the authority embargoing a register

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2072]
Eg. Blankshire County Record Office, Little Blankton Baptist Chapel, Diocese of Blank, City of Blank Environmental Services Department, Blankham Local History Group, Jo Blank.

With this information, a researcher wanting the data will be able to ask the embargoing authority and ask for special permission to see the records - might be used, for example, as part of mortality research, where the names of indivudals will not be further shared, but statistical data will be.  We will also be able to go back to the authority and ask for a reconsideration in light of future Data Protection changes, community ethics or policy advice provided to such institutions.

**Comment by PatReynolds** [comment]
Good point, Eric. - for individuals we would want to keep their information private, and have enquirers go through an intermediary (e.g. the cc).
I think  for churches, we would want to do that, too.  But for Repositories/Archives and for other institutions (e.g. Civil Cemetery authorities) I think the cc could send that  information back to the researcher.

**Comment by PatReynolds** [comment]
While places in more rural areas do only have one CoE church, they often have an independent chapel, or civic graveyard so we cannot assume that an embargo can be set at place level. At a county level, there is always more than one entity which could set an embargo.  
Perhaps you are confused by my examples - these are just the names of the authorities which have placed the embargo.  I see no need for the system to know that Blankshire County Record Office being given as the authority for St Stephens, Little Blankton is the same entity as Blankshire County Record Office being given as the authority for St Marys, Great Blankton.

**Comment by Captainkirkdawson** [comment]
Reasons can be recorded in the rule being applied to the register
