### ISSUE TITLE
Individual embargoed record can be manually unembargoed

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2073]
Reasons for doing this would be knowledge of the death of such an individual, or at the request of the individual.

**Comment by Captainkirkdawson** [comment]
Who or what role has authority?

**Comment by PatReynolds** [comment]
Trustees, or the Executive Director (upon instruction from the person requesting the Embargo in the first place, or upon review of death/probability of death).

**Comment by Captainkirkdawson** [comment]
Sorry
who within REG management cab enter? CC DM SA EX can enter this embargo

**Comment by richpomfret** [comment]
System admin here too.

**Comment by Captainkirkdawson** [comment]
SA and ED have been assigned with the role

**Comment by Captainkirkdawson** [comment]
Code in place,

**Comment by Captainkirkdawson** [comment]
Going to extend the code to handle all changes and validation
