### ISSUE TITLE
Remove Open Data Message on Login screen (once TA signed)

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2080]
I've had a question as to why the following Open Data message always comes up on login:
![image](https://user-images.githubusercontent.com/25303607/68124789-0f1eaa80-ff08-11e9-9bb2-e9401ac1ace7.png)

Even if you have accepted the Transcribers Agreement it still states "Your transcriptions currently will not be shared as Open Data .... please click here ..."

Can this message be removed or changed based on whether the TA has already been accepted?

E0 U3 S9 C8: P20

**Comment by Captainkirkdawson** [comment]
Hard coded message deleted

**Comment by Captainkirkdawson** [comment]
Completed as part of 1730
