### ISSUE TITLE
User Search feature that uses the 'nearby' tool does not include any data from an adjacent County

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#2081]
Full details and example to follow.
this is a spin off from Reader Issue note 152616967 by Tom Brooks.

E3 U 3 S5 C6: P17

**Comment by Sherlock21** [comment]
I did some research in  Production, with 2 places that I know are nearby and in different counties. These are YORK (NRY) and TADCASTER (WRY)
search for surname = GREEN
no first names
FROM 1550 to 1600
ALL record types.
result:
YORK on its own: 63 records
YORK with NEARBY selected: 86 places but none form any WRY places though looking at ABOUT, it shows plenty of place names within Range, from both NRY and WRY but only NRY records are listed in the result.
SIMILARLY
TADCASTER on its own: 58 records
TADCASTER wit 'NEARBY selected: 339 records but again, all these are from WRY places even though YORK is listed in the ABOUT tab.

York is shown as 9.5 miles from Tadcaster - about correct from my memory. 

This  test is completely repeatable. 
From my memory of the original days of developing this 'Nearby' tool, I would have checked that the across boarders capability worked just as well as 'all within one county' - because I can remember getting some results of well into triple figures radius where the records were sparse.

Whilst this test is only across 1 border, the application needs to work across any number of county boundaries. I will try and find some examples for use later.

**Comment by Sherlock21** [comment]
Done my report - it is in #2081 - please move assignee on now,

Eric b
On 4 Nov 2019, at 17:08, Rich Pomfret <notifications@github.com> wrote:

Assigned #2081 to @Sherlock21.

**Comment by PatReynolds** [comment]
Repeated test, but for Newport Pagnell, Buckinghamshire.  Cosgrove Northants and Ampthill Beds were among places listed as search.
NP - 1 result
Cosgrove - 3 
Ampthill - 2
All three places appear in a search for 'nearby places' for all three.

**Comment by Sherlock21** [comment]
yes, I agree the PLACE appears across the boundary, but NO PEOPLE do. - that's the key bit.

e.g.: James Clarke baptised in 1691 in Cosgrove, Northants, does not appear in a Nearby search based on Newport Pagnell - Bucks..
etc.\

**Comment by PatReynolds** [comment]
Thanks for the clarification. I did record how many results for each search but didn't make it clear that a result = a person.

**Comment by Sherlock21** [comment]
richpomfret 

Richard: I completed my bit a week ago, so could you move this along please

I consider this as a matter of our credibility.

**Comment by richpomfret** [comment]
Noted @Sherlock21 we shall add to the list and move it along.

**Comment by Sherlock21** [comment]
By chance, as I was checking a researcher's complaint, I discover that the NEARBY tool worked again - at least across the Derbysshire/Yorkshire border. 

What has anyone done?

**Comment by Captainkirkdawson** [comment]
Nothing

**Comment by Sherlock21** [comment]
Stranger than fiction here. I cant now repeat the cross boundary results I got this morning now.

SO leave the issue open please.

**Comment by richpomfret** [comment]
@Vino-S to possibly take a look (assess priority and see if a new tech volunteer might be suitable).

**Comment by Captainkirkdawson** [comment]
This has been fixed by story #2444
