### ISSUE TITLE
add content in refinery in both REG (and CEN) for Policies

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/MyopicVicar#2082]
In members actions. FUG policies.

E0 U10 S7 C7:PP24

**Comment by PatReynolds** [comment]
Volunteer Induction Handbook link will need replacing when document updated/replaced by Volunteer Handbook (see Coordination #891)

**Comment by AlOneill** [comment]
@PatReynolds Have worked some magic on this, but it is incomplete — the link to policies on the FUKG, the last link, did not have a proper address.

Have replaced with link to FUKG site home as temporary measure. Could you please inset the full address as I could not see where to go once on the FUKG site. Thanks! (Will copy link address to CEN page myself, i.e. you need only update REG page.)

**Comment by PatReynolds** [comment]
This link works for me: https://www.freeukgenealogy.org.uk/about/constitution-and-policies/

**Comment by AlOneill** [comment]
Thanks. The link may not be missing on the FUKG site, just that I couldn't see it!

**Comment by AlOneill** [comment]
@PatReynolds OK, the link is there, but you have to go to About, then Links: the link to Constitution and Policies then appears as a sub-item of Links.

**Comment by AlOneill** [comment]
@PatReynolds Ready for review on REG and CEN (test3, both).

**Comment by PatReynolds** [comment]
Realise I haven't linked to security policy and cut down versions...  Now added to FreeREG.

**Comment by AlOneill** [comment]
@PatReynolds Checked on REG; copied to CEN, files uploaded to CEN, file links re-inserted and checked.
