### ISSUE TITLE
Large ad at bottom of all pages

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2092]
@PatReynolds It would appear that we are displaying a large ad at the bottom of all pages on reg including search results page
Not sure if this was an unintended consequence of the last release.
Certainly having BOTH a donation request and an ad on the search results page looks very odd

**Comment by PatReynolds** [comment]
Looking at the design (shared on slack): no advert at bottom except on mobile (the right hand column in the design. Hoever there are adverts that are supposed to be at the sides (in details).

**Comment by Captainkirkdawson** [comment]
@PatReynolds We are not adding this large ad directly. There is no change to our code that would have added this ad. 
Inspecting the ad shows that it is generated by google ads.
I suspect that it is yet another change in how google ads behave

**Comment by Vino-S** [comment]
As @Captainkirkdawson pointed out we only have header adverts for FreeREG and ads are auto placed by Google. 
Recent advert changes are still in testing phase not yet deployed.

**Comment by PatReynolds** [comment]
Thanks @Captainkirkdawson and @Vino-S  I have contacted Sheila re overlap in detailed research results page.
GoogleAds seem to have forced auto-placement into our account, and are showing on live, but not test3.
I don't seem able to get into our account other than to 'accept' AutoAds.

**Comment by Captainkirkdawson** [comment]
@PatReynolds It appears that Autoads had been turned on for REG. I have turned off; lets see in an hr
