### ISSUE TITLE
Add "Help with Citations" to Help for Researchers

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2101]
E1 U3 S2 C7: P13

**Comment by PatReynolds** [comment]
Draft page on refinery (test3) for review A ("fit for purpose") and re-iterations before @AlOneill does review B "is the html good" (answer, no, it isn't ...).

**Comment by PatReynolds** [comment]
Now ready for you to sort the html, Alison.

**Comment by richpomfret** [comment]
@AlOneill another one for you to take a look at. ;)

**Comment by AlOneill** [comment]
@PatReynolds I have some questions.

Do we want to make the academic formats project-specific, i.e. reference CEN on CEN, REG on REG, or leave as they are?

Is the BMD-related note about GRO references intended for the BMD site only or is it a more general note?

Our URLs are https rather than http. The latter will work, but is there a reason for not using https in the academic formats?

The quotation from ESM: … "is built on one core principle: We cannot judge the reliability of any information unless we know exactly where the information came from; and the strengths and weaknesses of that source." I am wondering about the capital w in "We" — seems wrong. Suspect the original was probably formatted as a block-quote. Can find something similar in Foreword to book, but the phrasing is somewhat different (in my 2007 edition).

Thanks!

**Comment by AlOneill** [comment]
Am also wondering (!) if this section is more suited for "About" page than "Help"?

**Comment by PatReynolds** [comment]
1/ Could make them project specific - why not!
2/ cannot see anything about the GRO
3/ I have changed http to https: (hangover from two years ago ...).  
4/ ESM is American.  Some of them put capitals after colons.  (see this which I picked at random http://www.sussex.ac.uk/informatics/punctuation/colonandsemi/colon).

**Comment by PatReynolds** [comment]
Yes, it does seem more 'About-like' than 'Help-like', doesn't it.

**Comment by AlOneill** [comment]
@PatReynolds TY

2. Look for BMD in text (GRO not actually mentioned, I added to question for clarity (!)
4. That was my 2nd thought: it goes with "artifact" [sic]!

**Comment by PatReynolds** [comment]
If making versions for each site (and I think that's a good idea) then the note on GRO references is only for FreeBMD.  And the three examples all use the  url of the project.

**Comment by AlOneill** [comment]
@PatReynolds Have tidied up text/HTML/CSS but have not yet made the project-specific changes. Please view actual page — rather than preview — to see the layout of the academic formats. Do you like?

Suggest that, if approved, the (generic) page can then be copied to CEN and BMD (and there made project-specific).

As to where the text goes, I suggest putting the full version on 'About', together with putting the 'Citation buttons' part, with some context, on 'Help', with a link from there to the full version on 'About'.

**Comment by PatReynolds** [comment]
That looks lovely, thank you @AlOneill  I agree with your suggestions about copying on, placement, and linking.

**Comment by PatReynolds** [comment]
Added to created DRAFT About in test3, and added there.  I think we need to have a menu now on About (on the right, as for other long pages).  If agreed in Scrum this evening I will make a new story for that.

Added to DRAFT Help in test3.  The anchor to take  the reader to the About page is there, but I don't think I've recollected correctly how to write the href to take the reader there (and can't think how to test).

Could you take a look @AlOneill ?

**Comment by AlOneill** [comment]
@PatReynolds Your link to About was not quite right: have corrected. 

For future reference, you can test links by viewing the page (eye icon on "Pages" page).

Will add a page menu to About — no need for a story!

**Comment by AlOneill** [comment]
@PatReynolds Before I wade in, on the DRAFT About page, what is the
 `<style class="darkreader darkreader--sync" media="screen"></style>`
line all about? I note that it is also on the live About page.

The indentation is well messed up on the DRAFT page and there is some apparently unnecessary markup. I would like to sort it out but don't want to tread on someone else's toes.

**Comment by PatReynolds** [comment]
I don't recognise the style - it may be on About too because I copied and pasted it there from the citation draft before I realised I'd put the whole lot into the wrong version, and moved to the DRAFT About.

I didn't touch indentation or markup - other than to add the links from menu on Help and to add the links / targets.

Please do make lovely again!

**Comment by PatReynolds** [comment]
Hi Alison,  I couldn't test the link as the target (at the moment) is in DRAFT About, and wil need to link to About.

**Comment by AlOneill** [comment]
Will delay edits to "DRAFT About" until after Scrum as **someone** has put the `<style class="darkreader darkreader--sync" media="screen"></style>` line there, and it wasn't me or @PatReynolds — so who was it and why? Neither does it come from the "DRAFT Help with Citations" page. I am baffled.

**Comment by Captainkirkdawson** [comment]
Well was not @Captainkirkdawson either if that is what you think.

**Comment by AlOneill** [comment]
@Captainkirkdawson no, I didn't think it was you! — I can't think who would've done it.

"darkreader" appears to be the name of a Firefox/Chrome add-on for rendering web pages as light on dark. Remain baffled.

**Comment by AlOneill** [comment]
Page menu added to DRAFT About. ("darkreader" line deleted.)

Question: is the section on Citations sufficiently REG-ified? I was imagining that all refs to FUKGen would be replaced by FreeREG, but maybe what is there now is better?

**Comment by PatReynolds** [comment]
I have had a look, and think it better, as it futureproofs and also gets the information there for the other websites.  Unless anyone has any strong objections - if they do, I can edit.

**Comment by PatReynolds** [comment]
Not sure why this is in backlog - anything still to be done before transferring to live?

**Comment by AlOneill** [comment]
Not sure who edited these pages last, but I do not recognise some of the edits. Will check and report back here.

**Comment by AlOneill** [comment]
@PatReynolds On CEN, 'Help with citations' is a child page of 'Help'. Here on REG, it is a section of the 'About' (draft) page. We should be consistent. So, which way to go?

**Comment by PatReynolds** [comment]
On FreeBMD2 it s a section in About, and a section in Help - which is what I thought it was on both the others.

**Comment by AlOneill** [comment]
@PatReynolds Yes, I described the situation badly: the short version is on the 'Help' page for all projects, it is the full version, with the academic info, I was asking about.

I will move the full version on CEN to the 'About' page, to match the other two.

**Comment by AlOneill** [comment]
Both pages, Help and About are sync-ready.

**Comment by Vino-S** [comment]
Deployed to production
