### ISSUE TITLE
Add an Embargo Rules collection with edit, show index and create actions 

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2102]
The embargo rule  must be specific and contain either a number of years for a record type or a specific year.

**Comment by edickens** [comment]
Just number of years.  Unless you have suggested this to allow for entries where the year is unreadable.
I don't think that an embargo applying to all Enries in a Register would be applied to a specific year.

**Comment by SteveBiggs** [comment]
If a date is unreadable, it would be required to enter an approximate year in the transcription to make the number of years embargo work for it. I think having a specific year option would be useful as a condition of the source could state a specific year for the register being searchable.

**Comment by Captainkirkdawson** [comment]
First version developed

**Comment by Captainkirkdawson** [comment]
Add an additional field to the model. 'Reason.

**Comment by Captainkirkdawson** [comment]
Collection created
