### ISSUE TITLE
Write simple documentation on the embargo system

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2119]

**Comment by Captainkirkdawson** [comment]
All testing must await this document

**Comment by Captainkirkdawson** [comment]
The document is available at https://drive.google.com/drive/u/1/my-drive

**Comment by edickens** [comment]
I am about to get around to testing the Embargo Actions, but the link above to the Help does not come up with the Help instructions.  Where are they?  I would also like to let CCs have a look at them in preparation to their use in 2020.

**Comment by edickens** [comment]
Ignore my last comment.  I used the link in the Github message on 16th "The document is available at https://drive.google.com/drive/u/1/my-drive" which doesn't work.  The one above does.

**Comment by edickens** [comment]
After reading the Help (some of these may have been answered and I will find out when I test).

Should the Entity and Reason imposed fields be from a pick list which SysAdmin can edit, just like Denomination and Gap reason?  This will provide some standardisation for analysis in the future.

I assume that the List Embargo Rules come up when you select Embargo Rules at Register level.

If a single entry has been Embargoed by Trustees, how do we find it when there is no other Embargoes in the Register Type?  Should there be something in the Register Type Actions to show that such an embargo exists then list them?

This system is much more comprehensive than I envisaged and should work well.

Search Result reporting is not mentioned here.  Are we going to tell a researcher that they have asked for an Embargoed entry?  They should then be advised to refer to the "Entity".

I will do some testing soon.
