### ISSUE TITLE
F1 to F2 Update Transcription Entries only

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#212]
When Coordinators start to work on their data live, then only Register entries should be updated

**Comment by edickens** [comment]
May I suggest an improvement in the matching of transcriptions to the MPN, both Places and Churches, if this is possible...
I think at present the update matches ignoring the case, so that sometimes the transcription is matching with an unapproved place, or a church which is not the one that the CC wants to use.
So can the matching work like  this...
- First an exact match, including case matching.  (This means that the transcriber has used the correct version.)
- If that match fails, match ignoring case, and if that works, accept the version on the MPN or Church that is already on the server. (Here the transcriber has not used the correct version, and so the one on the server is accepted.)
- if that fails, set up a new Unapproved Place/Church. (This is a No match, so the CC may have to sort it out.)
Further to that, if the matching, once the exact match fails, could also ignore hyphens and full stops, we could get rid of more extra entries which  include things like "St." or "-upon-".
If that is not easy to do, then we should consider validation, and only Exact, including case, matching should be allowed.  Non-matched files will not be uploaded.  This means that CCs must set up Places and Churches prior to transcribing starting.  Perhaps this should be the next task that we give to CCs.

**Comment by Captainkirkdawson** [comment]
The current match is case sensitive.

It is certainly feasible to do a second match based on case insensitive
matching if the first fails.

Clearly there could be unintended consequences of such a fundamental change

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
WRT " could also ignore hyphens and full stops, we could get rid of more
extra entries which include things like "St." or "-upon-"."

Much of this is already done. Periods, hyphens, brackets.

CHURCH_WORD_EXPANSIONS =  {
    'Albans' => 'Alban',
    'Albright\'s' => 'Albright',
    'Andrews' => 'Andrew',
    'Andrew\'s' => 'Andrew',
    'Annes' => 'Anne',
    'Augustines' => 'Augustine',
    'Augustine\'s' => 'Augustine',
    'Barthlomew' => 'Bartholomew',
    'Bartholemew' => 'Bartholomew',
    'Bartholemews' => 'Bartholomew',
    'Batholomew' => 'Bartholomew',
    'Batholomews' => 'Bartholomew',
    'Benedict\'s' => 'Benedict',
    'Benedicts' => 'Benedict',
    'Bololph' => 'Botolph',
    'Boltolph' => 'Botolph',
    'Boltoph' => 'Botolph',
    'Boltophs' => 'Botolph',
    'Botoph' => 'Botolph',
    'Catherines' => 'Catherine',
    'Catherine\'s' => 'Catherine',
    'Chads' => 'Chad',
    'Clements' => 'Clement',
    'Clement\'s' => 'Clement',
    'Cuthberts' => 'Cuthbert',
    'Davids' => 'David',
    'David\'s' => 'David',
    'Dunstans' => 'Dunstan',
    'Edmonds' => 'Edmond',
    'Edmunds' => 'Edmund',
    'Edwards' => 'Edward',
    'Edward\'s' => 'Edward',
    'Elphins' => 'Elphin',
    'Faiths' => 'Faith',
    'Georges' => 'George',
    'George\'s' => 'George',
    'Germans' => 'German',
    'Guthlac\'s' => 'Guthlac',
    'Helens' => 'Helen',
    'Helen\'s' => 'Helen',
    'Johns' => 'John',
    'Julians' => 'Julian',
    'Leonards' => 'Leonard',
    'Loenard\'s' => 'Loenard',
    'Lukes' => 'Luke',
    'Margarets' => 'Margaret',
    'Margaret\'s' => 'Margaret',
    'Marks' => 'Mark',
    'Martins' => 'Martin',
    'Martin\'s' => 'Martin',
    "Marys" => 'Mary',
    'Mary\'s' => 'Mary',
    'Matthews' => 'Matthew',
    'Michaels' => 'Michael',
    'Michael\'s' => 'Michael',
    'Oswalds' => 'Oswald',
    'Pauls'=> 'Paul',
    'Paul\'s' => 'Paul',
    'Pega\'s' => 'Pega',
    'Peters' => 'Peter',
    'Peter\'s' => 'Peter',
    'Philips' => 'Philip',
    'Stevens' => 'Steven',
    'Steven\'s' => 'Steven',

    'Swithen' => 'Swithin',
    'Swithins' => 'Swith1n',
    'Swithin\'s' => 'Swithin',
    'Swithuns' => 'Swithun',
    'Wilfreds' => 'Wilfred',
    'Wilfrid\'s' => 'Wilfrid',
    'Cemetry' => 'Cemetery',
    'Marys' => 'Mary',
    "Mary\'s" => 'Mary',
    "Marys\'" => 'Mary',
  'Nicholas\'' => 'Nicholas'}
  COMMON_WORD_EXPANSIONS = {
    'Saints\'' => 'St',
    'Saint\'s' => 'St',
    'Saint' => 'St',
    'SAINT' => 'St',
    'St.' => 'St',
    'ST' => 'St',
    'Gt' => 'Great',
    'GT' => 'Great',
    'Gt.' => 'Great',
    'GT.' => 'Great',
    'Lt' => 'Little',
    'LT' => 'Little',
    'Lt.' => 'Little',
    'LT.' => 'Little',
    '&' => "and",
    'NR' => 'near',
    'nr' => 'near',
  }
  WORD_SPLITS = {
    "-" => /\-/,
  "&" => /\&/}
  WORD_START_BRACKET =  /\A\(/
  DATE_SPLITS = {
    " " => /\s/,
    "-" => /\-/,
  "/" => /\\/}
  CAPITALIZATION_WORD_EXCEPTIONS = [
    "a", "an", "and", "at", "but", "by", "cum", "de", "en" ,"for", "has",
"in", "la", "le", "near", "next", "nor", "nr", "or", "on", "of", "so",
  "the", "to", "under","von", "with", "yet", "y"]



Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
<SNIP> The current match is case sensitive.<SNIP>
Sorry, it is not.  That is the problem.
I have uploaded ERY Kingston upon Hull and it put the file in ERY 
Kingston Upon Hull, which is the Unapproved Place
There is only one file involved so this is a good example to see the 
problem.
I think the capitalisation rules were useful to initially set up the 
Places, but I don't think that they are needed now, but what do others 
think?
E

**Comment by Captainkirkdawson** [comment]
I must disagree. It is case sensitive checking. As noted "upon" is
automatically capitalized since it does not appear in the list of
exclusions as part of the Standardization. Hence the check is using an
incoming file name of  ERY  Kingston Upon Hull. The check being case
sensitive finds a match against the Unapproved Place and puts it there

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
So how are we going to get the batches put against the Approved Place?

**Comment by Captainkirkdawson** [comment]
If one uses the Standardization approach then "upon" is added to the list
of words than are not capitalized. Other issues could be added to the list

If one abandons the Standardization approach then we could adopt the
approach you suggest of matching case insensitively in selecting the Place.
In this case I would add a further check that is was not matching to an
unapproved name. As noted I will not be responsible of there are unintended
consequences of such a change.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
I need to ask about this.  I do agree that having decided on this we 
need to take care if we now remove it.
E

**Comment by Captainkirkdawson** [comment]
Removal of standardization will lead to at least an order of magnitude
increase in errors in Place Names and Church Names that coordinators will
be forced into correcting.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
I agree.  That is why I'm thinking very carefully about it.  Perhaps we 
should only do this when we have validation and we reject anything that 
does not match.
E

**Comment by Sherlock21** [comment]
Unfortunately, I have missed out on a lot of this due to being off on hols.

But I would say that over the years, CC's and myself have corrected an awful lot of place names to fix CASE to match the Approved NAME in my MPN.
I vote for doing the data job properly and insist on things uploaded from now onwards, still have to match Case. I & CC's will have wasted a lot of time & effort doing needless work if we go for the "anything will do" approach and I for one will not be best pleased.

**Comment by Captainkirkdawson** [comment]
After 1 year where is this issue?

**Comment by edickens** [comment]
Now that we do not update from FR1 this is no longer relevant.  E
    

    On 13/04/2016 05:01, Kirk Dawson wrote:
    
    
      After 1 year where is this issue?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub
