### ISSUE TITLE
Loss of Advert Personalization

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/MyopicVicar#2120]
With the new advert code implementation, we no longer control the advert personalization in our code. So we may need to remove the user consent for Advert Personalization option from the cookie-policy page.

**Comment by richpomfret** [comment]
To review/update cookie policy as applicable.

**Comment by richpomfret** [comment]
Getting info from MM on how their personalised code works for this. Will look to implement this over the next sprint if we can and update our own cookie policy page/consent form to reflect cookies.

**Comment by richpomfret** [comment]
Still establishing how we toggle MM code with our own code (or via cookie consent). @Vino-S is assisting.

**Comment by Captainkirkdawson** [comment]
@richpomfret in my mind the real issue is should we have a cookie option the permits use of cookies on the website EXCEPT adverts? Personalization turn on/off of adverts is likely a second level option. .

**Comment by PatReynolds** [comment]
Pat to ask for a manual review.

**Comment by PatReynolds** [comment]
Manual review requested 20/2/2020

**Comment by richpomfret** [comment]
Perhaps we should have an option @Captainkirkdawson for users to switch off Adverts - but ONLY if they are a specific user type e.g. Patrons (or logged in researchers). 

@Vino-S I wonder what tests we can do to move forward with this story. It appears personal adverts are served but how can we toggle them?

**Comment by Sherlock21** [comment]
or staff - ie Volunteers.

**Comment by Captainkirkdawson** [comment]
Got to be careful we don't get into the situation we are in with the login page and getting everything blacklisted

**Comment by richpomfret** [comment]
Yes indeed! That is a bit of a concern..

**Comment by richpomfret** [comment]
@Vino-S can you advise on how we might resolve this issue?

**Comment by Vino-S** [comment]
Hi @richpomfret ,
I can think of following three solutions:

1. As I suggested before to get two codes from MM, a) Personalised advert code b) Non Personalised advert code. We will display respective advert based on user input for Personalised Advertising on Cookie Policy page

2. As you mentioned: We will not show any advert when user switches off Personalised Advertising on Cookie Policy page.

3. Similar to 2nd point but instead of having no adverts when Personalised Advertising is switched off we can use specific adverts like: Blackwells(as in FreeCEN1) or Amazon or similar adverts

Let me know your thoughts, I am open to suggestions

**Comment by Captainkirkdawson** [comment]
I would prefer option 1 or 3
I think 2 will get us into trouble with the google ad cop

**Comment by PatReynolds** [comment]
@PatReynolds  to ask for code from MM.

If that does not work, fall back is option 3.

**Comment by PatReynolds** [comment]
Asked MM for codes 17/4/2020.

Default will be accept, but  I propose that personalization is the first/large/close without choice option, and no-personalisation  can be selected on the 'more information' page - see https://docs.google.com/document/d/1d4pGLJSG3yqFc1Kkb6_7rJNvxeQc1XbHazEMRFtt90I/edit?usp=sharing

**Comment by PatReynolds** [comment]
New cookie consent now in place, so can be closed.
