### ISSUE TITLE
CommsCord stale messages

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2121]
Even after the monthly cleanup there remain stale messages.

**Comment by Captainkirkdawson** [comment]
It would appear that the issue is associated with our failure to deleted replies to contacts when the latter are deleted.

**Comment by Captainkirkdawson** [comment]
Have added a clean up task to ensure that old replies are deleted from the list of messages for a userid.

Deployed to test3

**Comment by SteveBiggs** [comment]
Has the clean up task ran yet? I still have some replies in My Messages on test3 from Feb 2019.

**Comment by Captainkirkdawson** [comment]
Yes it has. Clearly issue was more complex! The message you refer to was a reply to a message and that reply was still there. Hence my logic did not delete it. Back to drawing board.

**Comment by Captainkirkdawson** [comment]
Revised code deployed to test3 and executed

**Comment by SteveBiggs** [comment]
All login page messages have now been deleted so it appears to have worked.
