### ISSUE TITLE
Add Keep status to contact reports

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2123]
The being kept status is not obvious; It is only apparent by the appearance of an action to remove the keep status

**Comment by Captainkirkdawson** [comment]
Adde the keep status to the display of messages. Reformatted to be scrollable with a sticky header
Deployed to test3

**Comment by AlOneill** [comment]
I would be interested in seeing the sticky header in action, but cannot find an actual list of active feedbacks (or whatever) for any county on t3: all the tables I've looked at are empty, except for the headers.

Could someone please point me in the right direction? Thanks!

**Comment by Captainkirkdawson** [comment]
@AlOneill Go to feedbacks and list archived.

**Comment by AlOneill** [comment]
@Captainkirkdawson Thanks. Cool! So much better all round than the 2-table solution.

But why do th elements look like main-nav items (or buttons) and have :focus/:hover styling?

**Comment by Captainkirkdawson** [comment]
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/assets/stylesheets/styles/scss/lap_and_up.scss.erb#L268-L284

**Comment by AlOneill** [comment]
I phrased the question badly: I can see the styles! Why make them *look* like links/buttons when they are not? The tables should *not* be deployed to live looking (and behaving) like that. 

**The basic idea is sound**, but we need to think carefully about how sticky headers might be used, then adjust the colours accordingly (offering a few variations) and drop the focus/hover styling (remembering that Safari will only honour focus on actual links). Also, the style rules do not belong directly in that file.

Suggest we set up the style rules *first*, in a similar manner as, say, the banner/island/islet group, using a similar naming pattern. This would involve a fair chunk of work. Incremental changes would be messy and involve extra work — changes to markup in the main.

**Comment by Captainkirkdawson** [comment]
I disagree that this is a reason that we do not deploy an important change. The keep status was to all intents invisible.
Sorry you do not like my choice of colour for the header but IMO a sticky header has to stand out in a scrollable table. 
Other comments in a new sticky story on systemwide

**Comment by AlOneill** [comment]
I have absoluteky no wish to delay the change to visibility of keep status. But we do wrong to deploy the *styling* as it is on t3.

The bottom line is that we should not style things that aren't links so that they look and behave like links. We have other colours available to make the headers stand out: $navy and $dark will both work vs white text, and on all three sites without confusion. That is the quick fix, along with removing the focus/hover style.

**Comment by richpomfret** [comment]
To decide/action within SystemWide.
