### ISSUE TITLE
Update link to Roadmap

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2146]
Link should be to a generated by googledocs link, settings 'anyone with the link' 'can comment'.  Document should open in a new tab.

**Comment by richpomfret** [comment]
Roadmap link for members works fine when logged in - current SHARE is set to 'those with FUG accounts can comment'. Why would we want anyone/non FUGers to have ability to comment directly?

**Comment by Captainkirkdawson** [comment]
Do you want coordinator or transcriber  or data manager input?

**Comment by PatReynolds** [comment]
Yes, all members should be able to coment (link should be set to 'anyone with link' - ie. those reaching the document via the link on the members pages of FreeREG.

**Comment by richpomfret** [comment]
Share link options have been updated - to test to see if this has changed the options or not.

**Comment by PatReynolds** [comment]
Now done, ready for user testing.

**Comment by PatReynolds** [comment]
Tested, link works as expected, so closing
