### ISSUE TITLE
Ad issue when width reduced

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2157]
I had my screen split and noticed this issue with 2/3 ads (not all of them)

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/0f5657c3-b17c-4090-aa06-b952e2283c58)

**Comment by Captainkirkdawson** [comment]
Not convinced its a width issue as I  have experienced it without changing width. Seems intermittent

**Comment by Captainkirkdawson** [comment]
The add responds by decreasing and behaving as it should but it definitely goes outside the proper size from time to time for no apparent reason

**Comment by PatReynolds** [comment]
Box with shadow my not be shrinking as the advert does.
