### ISSUE TITLE
The Transcriptions display only contains data on places with data.

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2162]
There has been discussion over the past year about encouraging new transcribers and access to new registers and records.
One means discussed was to use the transcriptions display.
It should however be noted that `The Transcriptions display only contains data on places and churches with data.`
Should this be changed?

**Comment by edickens** [comment]
I agree with Kirk that the Transcriptions display that shows what we have done should not be changed.  There is more that we haven't done compared with what we have done.  It would just clutter up the data information.
But perhaps more publicity should be given to the Gap report, and that should contain information on Places and Churches where we have no information.  If someone at the Church could give us Gap or Embargo information, that would be very useful.

**Comment by Captainkirkdawson** [comment]
Eric

If you recall the idea was that by saying we don't have transcription beca we cannot get access to the information to transcribe we could get people to put pressure on getting them released

**Comment by edickens** [comment]
Showing Gaps and Embargoes is slightly different to showing Places and Churches with no information.  What we do should not be changed, but what do we do to encourage people to help us with those Churches which are not embargoed, as far as we know, and we have no data?

**Comment by PatReynolds** [comment]
@edickens I think prompting researchers to ask Churches (etc.) is part of #1939 but could be a separate story, to precede / run at same time as #1938

**Comment by richpomfret** [comment]
@Captainkirkdawson to go ahead with implementation and to then review in terms of how we point towards the information.
