### ISSUE TITLE
[production][search_records#show] No route matches {:action=>"show", :citation_type=>"wikitree", :controller=>"search_records", :id...

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2166]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/562a6215e93790333a00001a/problems/5e085c74e93790c8ca771995)
# No route matches {:action=&gt;&quot;show&quot;, :citation_type=&gt;&quot;wikitree&quot;, :controller=&gt;&quot;search_records&quot;, :id=&gt;BSON::ObjectId(&#39;59929d36f493fd5bb2b992d2&#39;), :locale=&gt;:en}, missing required keys: [:friendly] #

**Comment by richpomfret** [comment]
@ShemJM another set of eyes on this might be useful (it has @Captainkirkdawson a tad perplexed).

**Comment by ShemJM** [comment]
Is this related to https://github.com/FreeUKGen/MyopicVicar/issues/2046?

**Comment by Captainkirkdawson** [comment]
Its one and the same has been with us for months now; do not understand it
:friendly is a parameter used in cen but not reg; we get 4-5 of these
crashes a day

Have to be a bot but how to trap them
Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by ShemJM** [comment]
Can you set a  Nocrawl?

**Comment by Captainkirkdawson** [comment]
Supposed to be disallowed in the robots txt

**Comment by ShemJM** [comment]
Could it have something to do with this view? https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/search_records/_nav_header.html.erb

**Comment by Captainkirkdawson** [comment]
In what way it is s partial rendered by the actual view

**Comment by ShemJM** [comment]
I am not sure, I was just thinking of places I used "Friendly"

**Comment by Captainkirkdawson** [comment]
@ShemJM Lets walk through this.
The search record show is just a navigator to a partial 
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/search_records/show.html.erb#L1-L15
Depending on the app we either go to https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/search_records/_show_search_records_freereg.html.erb for Reg or
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/search_records/_desktop_search_records_freecen.html.erb for CEN (ignoring the _mobile for CEN)
In REG we had pulled out the citation code into a _nav_header partial to make it easier to follow; it was left inline in CEN

Now the citations code is different between REG and CEN for the javascript option

In CEN we have 
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/search_records/_desktop_search_records_freecen.html.erb#L31-L40
While in REG we have 
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/search_records/_nav_header.html.erb#L16-L25
The REG version is going to the friendly show path friendly_search_record_path(@search_record[:_id] but without the :friendly parameter set.
We have 2 routings https://github.com/FreeUKGen/MyopicVicar/blob/master/config/routes.rb#L382-L383 one for show and one for friendly. The friendly routing expects the parameter.
So it seems to me the :friendly parameter is need in REG if we route to friendly_search_record. but NOT if we were to route to show_search_record. 
I do not follow citations well enough to know which is correct or maybe neither is correct
When we create a citation we are likely working with a friendly.
But when we subsequently use a citation we are likely not using a friendly as we do not have a friendly
This seems to imply that this is a real issue and not a bot issue

**Comment by ShemJM** [comment]
@Captainkirkdawson So we should try adding the friendly parameter to REG when it uses the JavaScript citation but not for the old citation?

**Comment by Captainkirkdawson** [comment]
It is either that or use the show path rather than the friendly path.

**Comment by Captainkirkdawson** [comment]
Will try adding the friendly parameter

**Comment by Captainkirkdawson** [comment]
@ShemJM That was not the issue.
Finally found the cause. 
If you immediately tried the citation while still having an active search the code wanted to present the navigation menu for the search results but it did not have the friendly that was required with the attempt to display the record and therefore crashed.
Fixed code. Deployed to test3.

**Comment by Captainkirkdawson** [comment]
Deployed
