### ISSUE TITLE
To tell or not to tell researchers about embargoed records

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2172]
Lots of discussion about this in the epic. But what do we say and where? Lets focus our discussion here.

**Comment by Captainkirkdawson** [comment]
@edickens first said
Are we going to tell a researcher that they have asked for an Embargoed entry? They should then be advised to refer to the "Entity". (Search results does not include NOR comment about embargos)

@Sherlock21 in his testing also makes a similar comment about the search result " It says No results but there is a transcription matching the search criteria, but its subject to the Embargo I just created"
In my mind as far as the researcher is concerned it does not exist. Interesting policy question

@edickens added
The event has occurred so can't be ignored. But interesting policy. If we say "It is there but we cannot show you", then we have given the researcher the information that they have found the entry. They may not need to know more. But we must not show the detail.
So in the list of results, should we just say "There are embargoed entries in these results." Or will that just frustrate researchers?
Perhaps we need a separate discussion on this. For example, nearly all of OXF is embargoed, so if someone does a whole country search there will be embargoed entries every time. And how do we handle a Register Type which is embargoed because of lack of permission, and there are no entries for it? Or should that situation be entered as a Gap and how is that shown to researchers?

**Comment by Captainkirkdawson** [comment]
@PatReynolds responded
Embargo rules (i.e. rules imposed on us by the body controlling the document) can be announced in the search results, or with the church/locale information (e.g. as another table or in the records transcribed table with a convention such as square brackets to indicate the records are subject to an embargo. At itts simplest, a statement on the church/locale page could say 'Records of events in the last 100 years, will not be presented in search results, at the request of Barsetshire Archive and Museum Service".

An embargo applies to a record, on the other hand, cannot be indicated to the researcher as it would indicate that such a record exists (not a problem if the search is for John Smith 1981 baptism in Suffolk, but if it is John-Jaque Twiddly-Pomme 1981 in Ravengalass, Cumbria, then it is going to be pretty clear that JJ was baptisted, which is just the information that JJ has asked be removed (and which the Trustees agree should be removed.

**Comment by Captainkirkdawson** [comment]
@edickens replied
Pat,
I'm not sure that your last paragraph is quite correct. An embargo on an individual entry would have been put as personal details do not want to be given out. And this can be an address. So just saying that an entry exists without giving any details, would protect the identity. The researcher could not be sure that it was the right person, especially if no date is shown. If the researcher had put in as much information for JJ as you suggest, then they must know the person. They would be seeking dates, addresses and parents. We will not give out this information.

**Comment by Captainkirkdawson** [comment]
So what do we say and where??????????????

**Comment by PatReynolds** [comment]
Embargo rules (i.e. rules imposed on us by the body controlling the document) can be announced in the search results, or with the church/locale information  - WHICH IS PREFERRED?  I would have thought with the church/locale information would be easier to implement.  Also, it would be in the same place as GAP information, and embargo is another kind of gap.

An embargo applied to a record: say nothing, anywhere, about this record.

**Comment by SteveBiggs** [comment]
It may be harder to implement but I would suggest that the embargo (imposed by a body) should be announced in the search results to immediately alert the researcher. It would be useful to be in the church/register info as well.

**Comment by Captainkirkdawson** [comment]
I fail to see how we can announce a specific rule on a register in the search results.
If you do a search for xxxxxxxxxx in SSX and get no results. There are several hundred register in SSX, one or all of them COULD have embargo rules (unlikely I know but) what are we going to do list them all?
Even if the research were restricted to a place which is a large city there are still dozens of registers.
In my option we should change the no results text to something like:

This could be because for the Places you were searching: we have yet to transcribe the registers; Record Offices will not permit us to access the registers for transcription; do not have access to the registers; there are gaps in the registers or they do not exist; or the transcriptions are subject to an embargo on their publication:e have no transcriptions ; or we do not have access to the registers. Our Transcription pages can tell you what we have transcribed and availability. Alternatively you may need to recast your search options: see our Help for advice on how to get the most out of your searches.

The transcriptions pages should be expanded to include information on availability, gaps and embargoes at the Church Register level.

**Comment by SteveBiggs** [comment]
What I had in mind was that if the search DOES find one or more records which are subject to an embargo, then the search result states something like "Records matching your search criteria exist but are currently not permitted to be published due to restrictions set by the register owner" but thinking it through, maybe this is too vague and of little help to them so let's not worry about it.

**Comment by richpomfret** [comment]
@AlOneill to assist with updating the text! ;)

**Comment by Captainkirkdawson** [comment]
Deployed
