### ISSUE TITLE
Create help documentation for the Embargo System

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2175]
Based on the material drafted by the programmer write help material for the coordinator.
https://drive.google.com/open?id=1PCuoE1y2N3QiqB8bsXzvtU7FarMN-WGD

**Comment by Captainkirkdawson** [comment]
An initial draft for finialization by @AlOneill is available at

https://test3.freereg.org.uk/cms/information-for-coordinators/coordinator-actions/coordinator-actions-draft.

**Comment by AlOneill** [comment]
Work in progress but page layout is broken, so editing off-site.

**Comment by Captainkirkdawson** [comment]
Sorry about that; was perfect with just embargo. I clearly creamed it adding the GAP stuff; got called away before final checks. Since I did it I would have fixed but given your comments on webpage will not touch.

**Comment by AlOneill** [comment]
Updated/corrected page returned to Refinery. 

(Next I'll add appropriate info re Gaps to Transcriber Info pages.)

**Comment by AlOneill** [comment]
Will make final edits (removing DRAFT status) once contents, plus those for Gap system, approved.

**Comment by Captainkirkdawson** [comment]
@AlOneill reviewed and fine by me. @PatReynolds please review and/or sign off

**Comment by PatReynolds** [comment]
To avoid confusion, I would change
There are two types of embargo: one establishes a period of up to 125 years for the embargo; the other establishes a specific year when the embargo ends.

to 

There are two types of embargo rule: one establishes a period of up to 125 years for the embargo; the other establishes a specific year when the embargo ends.

and make it a separate paragraph lest the two types of rule are confused with the embargo rule and the one-off, Trustee authorised embargo.

**Comment by AlOneill** [comment]
@PatReynolds TY: "rule" added (to HTML) as suggested.

Don't understand what you mean by make it a separate para as that sentence is not in same para as the one-off Trustee embargo. Unless you are referring to the PDF (which I don't have the means to edit) rather than the HTML???

**Comment by Captainkirkdawson** [comment]
Agreed in scrum that paragraph as structured is OK

**Comment by Captainkirkdawson** [comment]
Edited pdf to match text. Replaced version on test3 refinery. @AlOneill to remove drafting notes and eliminate draft.

**Comment by AlOneill** [comment]
Refinery pages tidied and checked; PDF file link re-inserted. Ready for sync.

**Comment by Captainkirkdawson** [comment]
Deployed
