### ISSUE TITLE
Plan integration of Images that are on the image server

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#219]
Integrating the image server, even on a manual basis, is key to how transcribing works.
We need to agree how this will work in F2 V1.1.
While discussing this, we need to have some idea as to how it will work when integrated in V2 or V3 so that we don't end up undoing changes we have just made.

**Comment by PatReynolds** [comment]
Eric also has 'All images to match register records and 'Add image numbers. - again: what about backfit to all the records online that do actually have images, but which were not recorded on the Transcription at the time. ' as stories with this number

**Comment by edickens** [comment]
Hi  Pat,
    
    As with all new facilities, the best we can do is to included this
    information in all new work we do it, from the time that the program
    is working.  That will be, in the first instance, when new images
    are uploaded or past images are allocated for transcribing.  Then,
    when convenient, we can add this information to past transcriptions.
    This will be when a Coordinator needs to check a researchers
    question and looks up the image and then they can link the
    entry/batch to the image(s).
    
    The images on the image server are well organised and I can do quite
    a lot when the program is working.
    
    There will be two levels of matching.  Batch and Entry.  Batch level
    will be the easiest to set up and use, provided there is a browse
    facility though the matching images.  So to sort out past images, we
    can do this at batch level.
    
    Eric
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 22/03/2016 16:18, PatReynolds wrote:
    
    
      Eric also has 'All images to match register records and 'Add
        image numbers. - again: what about backfit to all the records
        online that do actually have images, but which were not recorded
        on the Transcription at the time. ' as stories with this number
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub
