### ISSUE TITLE
Discrepancy between Help and file processing behaviour

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2190]
STS Coord wrote:

There is a problem with FreeREG.

According to FreeREG Help https://www.freereg.org.uk/cms/information-for-transcribers/file-headers header line 4 does not need any fields because all are optional BUT when the attached file was processed, I got the error message " The fourth header line has no usable fields. ".

Either Help is wrong or the file processing is wrong.

[https://app.zenhub.com/files/3918508/2e156722-4c68-4897-a62e-388e69fcab3f/download](https://app.zenhub.com/files/3918508/2e156722-4c68-4897-a62e-388e69fcab3f/download)

**Comment by Captainkirkdawson** [comment]
@SteveBiggs I am confused. Description says its a STS issue yet the file is one of yours that appears perfect. Without access to the original I cannot comment

**Comment by SteveBiggs** [comment]
Sorry I attached the wrong file!

[BKMMOUBA.txt](https://github.com/FreeUKGen/MyopicVicar/files/4071104/BKMMOUBA.txt)

**Comment by Captainkirkdawson** [comment]
A change made to permit 4th line with no content after #, eg #,,,,,,,,,, will deploy to master shortly

**Comment by Captainkirkdawson** [comment]
Deployed to test3

**Comment by SteveBiggs** [comment]
Tested and working on test3

**Comment by Captainkirkdawson** [comment]
Deployed
