### ISSUE TITLE
New Register Fields and Registration procedure

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#220]
The register record needs more fields to provide information prior to transcribing.
For example Date Range; Images on image server; to whom allocated; and others.
EricB,  Ali and I have  been trying to do the procedure that a CC needs to do from the time that they get data to the finished transcription.  This information is needed in the RAP for the transcriber to be able to select work, and it to be allocated.

**Comment by Captainkirkdawson** [comment]
No development is required
