### ISSUE TITLE
Data problem reports archived

### ISSUE THREAD

**Issue by suffolkroots** [FreeUKGen/MyopicVicar#2201]
All my WRY data problem reports have been archived, including those from the past week. I have no recollection of clicking a button which said "Archive all" or some such instruction.

**Comment by Captainkirkdawson** [comment]
There is no such 'bulk' action available to anyone. All contacts must be dealt with individually.

**Comment by suffolkroots** [comment]
Then how/why have they been archived please?

**Comment by SteveBiggs** [comment]
Resolved. Can be closed.
