### ISSUE TITLE
Revise Transcriptions to reduce white space

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2202]
Deployed to test3

**Comment by AlOneill** [comment]
On a page less than c1200px, the Select button on the "Choose place" page is hard up against the left-hand edge of the screen. I think it is because it is in a .grid, but not in a .grid__item, unlike the other list items.

**Comment by Captainkirkdawson** [comment]
Umm my testing on chrome shows it is fine down to 780 px screen width

**Comment by Captainkirkdawson** [comment]
Found a solution. Deployed to test3

**Comment by AlOneill** [comment]
@Captainkirkdawson OK-ish (!). I think the use of .grid and .grid__item could be improved further to obviate the need for centring the select button, but it would take me some effort to work out the details.

The browser differences are down to the different ways they resolve CSS oddities/weirdness/inconsistencies: in other words, the .grid contents are not marked up as the CSS was designed to be applied. 

Have also spotted a typo on the "Choose Place" page:

![Bedfordshire_Contents___FreeREG.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/a6d2d0d9-913f-4216-a1e8-eaab760e15cc)

**Comment by Captainkirkdawson** [comment]
There is no specific centering of the select in the form action. The basic css for simple_form centers the action under the rest of the form. Do not understand why you feel there is a problem with that page. It is fully responsive.
Will fix the typo.

**Comment by AlOneill** [comment]
I agree that it 'works', for now, but misapplied CSS (.grid contents) will bite us in the end. Also list-items without a list-container is not a good idea. So would argue for a review, either immediately or as soon as reasonably possible.

On a mobile-size screen the spacing between the form and the info doesn't look right — too close. It could be part of the same CSS issue, or something else — have not had opportunity to check details.

![Bedfordshire_Contents___FreeREG-2](https://user-images.githubusercontent.com/14852554/73105124-0e3a5b00-3ef0-11ea-9813-4d430579d2bf.png)

**Comment by Captainkirkdawson** [comment]
I have no inclination to make further changes. This is a very complex page involving forms in one grid item and tables in the other. Perhaps others can do better. Lots of luck.

**Comment by Captainkirkdawson** [comment]
Deployed
