### ISSUE TITLE
Update Help for revised Transcriptions

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2204]

**Comment by Captainkirkdawson** [comment]
Drafted on test3

**Comment by richpomfret** [comment]
@AlOneill can you take a look at this for us?

**Comment by AlOneill** [comment]
@Captainkirkdawson Have done a first-pass edit and made page ready for sync.

**Comment by Captainkirkdawson** [comment]
TY @AlOneill we can sync any further changes any time; does not have to wait on a deployment of code

**Comment by Captainkirkdawson** [comment]
Deployed
