### ISSUE TITLE
Typo in automated Comms emails

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2207]
> You are requested to take action on the correspondence preferably using the on-line contact system
> 
> Copies of the action request were sent to the following. Please include them in any correspondence
> **### Communiations** Team comscoord.freereg@freeukgenealogy.org.uk
> 
> The following is the information submitted.
> 
> General Comment:
 
Not sure if this is affecting all types of comms via Contact Us.

**Comment by Captainkirkdawson** [comment]
@DeniseColbert I am afraid that the miss spelt name is not part of the message. What you see there is the Forename from the userid (Team is the surname).  I was under the impression that Coms had corrected this certainly on REG

**Comment by DeniseColbert** [comment]
I also thought this had been dealt with. I'll see if I can change it within the Admin area of G Suite.

**Comment by DeniseColbert** [comment]
In G Suite, the Name for this email address is Sandra's full name. Is this definitely not an artefact from a time when it may have been the name on the email account?

**Comment by Captainkirkdawson** [comment]
I am sorry but I do not understand the relevance of GSuite to this matter. 
The message system uses the userid from the app database to look up forename, surname and email address to insert in the mail.
CommsCoord had an incorrect forename until recently (~2 months). It is currently correct.

**Comment by DeniseColbert** [comment]
Totally misunderstood, sorry Kirk. Closing as I think this has been done and is an old example.
