### ISSUE TITLE
Problems after outage on 29 January

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#2217]
We have had reports of uploaded batches not appearing in the batch list and replaced batches not having the replacements,.
So I did a message to send to transcribers (see message system) but got red message on trying to send it.  However, I did send my Coordinators report successfully, but not to Transcribers.
Not sure what is going on.

**Comment by Captainkirkdawson** [comment]
@edickens insufficient detail to do any diagnosis

**Comment by edickens** [comment]
I received:-

**Comment by Captainkirkdawson** [comment]
@edickens but what file names; I am sorry but with every thing else I am not going to go trying to research without specificity

**Comment by edickens** [comment]
We've now had an email from Amanda Willliams...

**I have a message on the website as below so guess we just have to wait?
“Your file is already waiting to be processed. It cannot reprocess it until that one is finished”**

There are 38 files waiting to be processed.  The oldest being 30 January 11:06.  So nothing to do with 29 January outage.

I have asked Eric Booker to look into it as he has seen this before.

**Comment by edickens** [comment]
PS.  In my first comment I mentioned a Red error message when I sent the news to transcribers.  But  it seems that the message did go, so the error was just reporting to me that it had gone.  Can be ignored.

**Comment by edickens** [comment]
Problem solved by someone.  The backlog is being cleared.  Barrie reports that the missing files are there now.
Thanks.

**Comment by Captainkirkdawson** [comment]
I wonder who. Twas not I.

**Comment by Captainkirkdawson** [comment]
Can this be closed? I know of no issues

**Comment by edickens** [comment]
Yes.  The problem was that more than 38 files got stuck and were waiting for processing.  The statistics showed that no records were added this day.  I don't know how processing got going again, but when it did everything went back to normal and nothing was lost.
