### ISSUE TITLE
[production][messages#update] SMTP To address may not exceed 2kB: "Eric Dickens <freereg.edickens@gmail.com>, Eric Booker <eric...

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2219]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/5e342235e9379082dafc1f40)

**Comment by Captainkirkdawson** [comment]
@edickens seems that you had too large a number of recipients

**Comment by edickens** [comment]
I was sending a message to all transcribers.  So what you say fits the facts.  But the message seems to have got through to some people as I got a message back from a Coordinator.
So how do we send a message to all transcribers?  And it was only Active transcribers.

**Comment by Captainkirkdawson** [comment]
You had included almost all roles not just transcribers. So step 1 would be just transcribers. You could subset active transcribers by their open data status.
Unfortunately this is a system limit that I have no control over

**Comment by edickens** [comment]
TY.  Perhaps advice needs putting on website for anyone who may want to send a message to every transcribers.

**Comment by Captainkirkdawson** [comment]
Who is likely to do? you steve maybe pat

**Comment by edickens** [comment]
and Denise for her newsletters, unless she has another FreeUKGenealogy system.

**Comment by PatReynolds** [comment]
We (mostly Denise and Jeff a FreeBMD volunteer) are setting up on "groups.io" to mail out to FreeBMD volunteers (Rootsweb demise being imminent) and for the general Free UK Genealogy Newsletter. For messages out to "all" I am guessing that we will need to keep the total under 2k individuals?  Is this likely to be an issue (e.g. if we divide transcribers between active and inactive, and then by signed agreement and not signed, how long before the largest approaches 2000?

**Comment by Captainkirkdawson** [comment]
Have split emails into no more than 100 recipients at a time. Added a spinner and reduced whitespace
