### ISSUE TITLE
Process for adding names to emmendation list

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2221]
There is a convesation on the transcribers group "Anyone Seen This" where some new-to-the-transcriber abbreviations are noted.

Should we have a process for adding such names to those searched?

**Comment by Captainkirkdawson** [comment]
Duplicate of Emendations table - make arrangements for updating.#823 which is version 2

**Comment by PatReynolds** [comment]
Ty @Captainkirkdawson , closing as duplicate
