### ISSUE TITLE
Create a County Record Office SWAT team

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2222]

**Comment by Captainkirkdawson** [comment]
How is this different from Create a 2 or 3 person Church swat team to obtain additional register for transcription.#2176

**Comment by PatReynolds** [comment]
The CRO team do work that the Coord sometimes does. They may be the same people as the Churches SWAT but need not be.  The stories in the two teams are different (or should be, if I have them in the correct places).
