### ISSUE TITLE
Recruit Register Acquisition SWAT team leader 

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2240]
E3 U6 S7 C6: P22

**Comment by richpomfret** [comment]
@SteveBiggs send out a message to all coords asking for volunteers for this.

**Comment by SteveBiggs** [comment]
Message sent.

**Comment by SteveBiggs** [comment]
Mick Claxton has been recruited as team leader.

**Comment by richpomfret** [comment]
Done so closing.
