### ISSUE TITLE
Add "report a problem" button to mobile screen

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2257]
I can't see a 'report a problem' button on my phone (first noticed this morning).  Phone is a Pixel 3 XL running Android 10.

**Comment by Captainkirkdawson** [comment]
Why? The member access was never designed to be run on a mobile

**Comment by PatReynolds** [comment]
I encountered this problem while trying to do a search - the message told me to report the problem, but there was no way to do so.

**Comment by Captainkirkdawson** [comment]
It would be through the contact us action which is I believe available on the mobile version
