### ISSUE TITLE
Not showing pear drop on map on LOCATION

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#2258]
Following the recent change from GENUKI mapping to show the Location of a place name, to using Google mapping, the teardrop which pinpoints the LOCATION concerned, is no longer shown on the map. Nor is the name of the Place concerned.

Example: WRY / FERRY.

E0 U1 S1 C8:P10

**Comment by PatReynolds** [comment]
Confirming that the pin is missing (example Northamptonshire, Denton

**Comment by Captainkirkdawson** [comment]
Some time ago I switched from Genuki map locations to Google map locations because of a number of broken links with Genuki
The Google map display does not include the Pin. The Map is always centered at the location and can be manipulated in the same manner as all Google Maps

**Comment by Sherlock21** [comment]
The implication of the place being at the exact centre of the Google map is beset with possible misunderstandings. - especially if the user does not know the logic, or has moved the map about a bit on the screen.
If that means there is no way of putting a pin on the Google map, then I would prefer to revert to the previous arrangement - I would be quite happy correcting all the broken links that you refer to, if you can provide a spreadsheet of County / Placename and any scraps, of either Grid Ref or other location ref.

**Comment by richpomfret** [comment]
@PatReynolds to look at alternatives. Or can we modify URL to include pear/pin drop on GMaps?

**Comment by PatReynolds** [comment]
Links are not simply broken, they re-break freequently.

**Comment by Sherlock21** [comment]
Im that case, I agree its better to have the location mapping in our own hands - as it were - so If you can manage to put the pin into our code, all the better,
But remember: not all of our place names appear on Google Maps - so they need to be part or the code.  I put the text of the place name in the code already so that's not another job I would have to do.

**Comment by PatReynolds** [comment]
Hello @Sherlock21 - just reviewing stories.  This one seems to be fixed - is this correct?

**Comment by DeniseColbert** [comment]
Seems done so closing
