### ISSUE TITLE
Report a data problem seems to have vanished?

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2265]
It used to be around the top of the table IIRC:

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/899be349-565f-4f89-b957-175f3026c4fa)

It's not on the search results page either.

**Comment by Captainkirkdawson** [comment]
It is because you are logged in as a member. Because this page is used by members we keep it cleaner.
