### ISSUE TITLE
Additions to Help for Researchers/Transcribers

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2269]
Eric's suggestions

- Witnesses: We record all that is in the register and that quite often a witness could be the Vicar or sometimes local Gentry and so not a relative
- WinREG: Windows updates play havoc with my Windows 10 computer.  Whenever there is an update I have problems following it.  I now run a Norton power scan when I have problems after an update and all is fixed.  I have never lost anything. 
- Advice on the correct way to record Banns: The “notes” column should clearly state the type of entry, Banns/Publication etc. and also include the fullest date possible. The “marriage_date” column should be the year only followed by a question mark.

**Comment by SteveBiggs** [comment]
Disagree with bullet 3. Banns should not be recorded using the Marriage record type. We plan to create a new record type called Banns where they will be recorded. For now, Banns only records should be put aside until the new type is ready.

**Comment by PatReynolds** [comment]
Banns: 

The transcriber should not transcribe, and should inform the Coordinator.
The Corrdinator shou,ld put a note in the Image file, so that the records can be transcribed, once we hae enhanced for Banns.

**Comment by SteveBiggs** [comment]
Suggested addition:

If a transcriber is not receiving "File Processed" or any other automatic emails from FreeREG, they should contact their coordinator to investigate why.

**Comment by PatReynolds** [comment]
DRAFTS for checkinging on test three for:
Banns (I have put this below 'Illiegible or not clear' for transcribers@ @SteveBiggs where should this go for Coordinators, if anywhere?)
WItnesses (I have put this below  Names)

@edickens  could I have text for WinREG, please.

**Comment by edickens** [comment]
For WinReg Windows 10 problem, see the help:-
https://www.freereg.org.uk/cms/information-for-transcribers/creating-a-transcription-file#winReg
These settings may get replaced when Windows 10 does an update.

**Comment by PatReynolds** [comment]
Pat to add  "Whenever there is an update I have problems following it.  I now run a Norton power scan when I have problems after an update and all is fixed.  I have never lost anything."

**Comment by SteveBiggs** [comment]
@PatReynolds wrote:
"DRAFTS for checkinging on test three for:
Banns (I have put this below 'Illiegible or not clear' for transcribers"

I can't find the text for Banns on test3, but I suggest you put it on this page:
https://test3.freereg.org.uk/cms/information-for-transcribers#transcribe 

here:
![image](https://user-images.githubusercontent.com/25303607/79261737-2e8f0b80-7e88-11ea-8165-58bde3e0b1ee.png)

**Comment by PatReynolds** [comment]
Banns,
Processed email missing and
WinREG issues are now all in:
Entering data from registers DRAFT
and ready for checking

**Comment by SteveBiggs** [comment]
@PatReynolds I can see the Banns details on that page but not the WinREG or missing email - where have you put that new text?

**Comment by PatReynolds** [comment]
No idea where they went - I have put them back, just above 'genearal guidance'.

![image](https://user-images.githubusercontent.com/6338822/80613981-cd456b80-8a35-11ea-9e9c-96a1ce0b9a48.png)

**Comment by SteveBiggs** [comment]
@PatReynolds would it make more sense to put the WinREG issue on the 'Creating a transcription file' page under WinREG:
![image](https://user-images.githubusercontent.com/25303607/80750495-1a057100-8b20-11ea-8c17-cb62f2ca8978.png)

and the File Processed email missing issue on the 'File and Batch actions' page under Uploading a new file:
![image](https://user-images.githubusercontent.com/25303607/80750713-79fc1780-8b20-11ea-9ed1-2fbafea48174.png)

**Comment by PatReynolds** [comment]
I have moved the windows 10 issue to WinREG DRAFT .... but I think you may be talking about a different page ... please could you check what page you want me to put it on?

**Comment by SteveBiggs** [comment]
The page I'm referring to is 'Creating a transcription file'.

**Comment by PatReynolds** [comment]
Thanks @SteveBiggs - done, and ready for checking.

**Comment by SteveBiggs** [comment]
I also suggested that this text:
"If  you do not receive "File Processed" or any other automatic emails from FreeREG, you should contact your coordinator who will investigate."
be put under File and Batch actions here:
![image](https://user-images.githubusercontent.com/25303607/86445096-b2c79100-bd09-11ea-9231-b02b1e352861.png)

**Comment by PatReynolds** [comment]
Thanks @SteveBiggs now done.

**Comment by SteveBiggs** [comment]
Thanks Pat.

**Comment by richpomfret** [comment]
@PatReynolds ready to be moved over to Production?

**Comment by PatReynolds** [comment]
@Patrecynolds to remove draft status

**Comment by PatReynolds** [comment]
@richpomfret do I delete the existing and remove the draft on test 3?  and delete the draft from live?

**Comment by AlOneill** [comment]
@PatReynolds If I may chime in here, I don't quite understand your suggested workflow. The details of how to get pages ready for syncing depends on whether the page is a 'child' or a 'parent'. You may also need to re-order the pages as part of the process.

Please give me some time to look at this particular set of steps and think how best to explain. (Brain squashed today.)
Please confirm which pages we are talking about as there is a lot of activity in Refinery.

**Comment by PatReynolds** [comment]
Sure - I've noted on another story (?FreeBMD?) that the instructions are no clear, so nothing is moving anywhere until it's been addressed. 

The page in question here is Help for Transcribers.

**Comment by AlOneill** [comment]
@PatReynolds The two updated files, 'File and Batch Actions' and 'Creating a transcription file', are now sync-ready. Fixed a couple of typos, the passive voice, the quotation marks and the indentation :-D

**Comment by Vino-S** [comment]
Deployed to production
