### ISSUE TITLE
Revise/enhance Donate button on Volunteer sign-up page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2279]
David writes:
I added custom event tagging on the donate button on the freereg volunteer page. After publishing, I noticed that the "donate" button hasn't really been clicked since the 12th... I wanted to see if you were aware that the "donate" link on this page: 

https://www.freereg.org.uk/cms/opportunities-to-volunteer-with-freereg

looks like this in Chrome:

https://drive.google.com/open?id=1lt285bJ49gq0750q0y42wFiRrf0g-qg5

And like this in safari: 
https://drive.google.com/open?id=19CV9D70DT0C5e2wBdJk76BYhBWgi7zYe
So it looks like the link is broken or missing an image? Is this expected?

Pat notes: image seems to be missing, but link is still there (on Chrome)

**Comment by AlOneill** [comment]
Had a look on t3 and noted that:
* image referenced is listed on page 3 of list view, dated October-03, 2017
* it has an upper-case file extension of `.PNG` (which may not be relevant in any way)
* when I tried to view it, I got a "Not found"
* when I tried to edit it, the thumbnail displays as "Donate"

[Also noted that `style` block at top of Refinery page (and so in body of page) is missing `scoped="scoped"` and so will be surprised if that does not cause any issues — will investigate.]

So, I conclude that **the donate image is no longer in Refinery**. 

I would then proceed as follows:
* add copy of image to Refinery images, with a file extension of `.png` [sic] —I trust we have a copy somewhere?!
* insert into page, close to where current `img` is, **from the Preview pane** (with HTML pane closed) and with "Re-size" box unchecked
* check that has worked!
* then open preview  and tweak HTML to replace current `src` attribute with the one that works

Then check and troubleshoot as necessary. If someone can provide the image, I'll do the Refinery shenanigans [sigh].

**Comment by AlOneill** [comment]
@Captainkirkdawson On reflection, I realise that my comments above may not cover the issue you have — can you review and re-state your issue with this page? Thanks.

**Comment by Captainkirkdawson** [comment]
@AlOneill go to Opportunities to Volunteer with FreeCen within refinery on test3 and click on html and nothing happens. Never happens elsewhere

**Comment by AlOneill** [comment]
@Captainkirkdawson Ah, CEN. Same result as you. (Child page and others — HTML pane opens OK.)

Never seen that before. I would try re-building a DRAFT version of the page, a section at a time, from browser source, to see if that sheds any light. I'll give that a whirl, unless you have a better plan?

Issue of missing donate images on CEN and REG remains …

**Comment by AlOneill** [comment]
@Captainkirkdawson DRAFT re-build fine with everything put back except the ad-block, the final `aside`. The REG version (which is editable) does not have the JavaScript, so will put back in without the JS initially — am thinking that is the likely trouble spot, though I have no idea why except that it seems just the sort of thing that Refinery might baulk at! Will do that tomorrow, with a clear head.

@richpomfret @PatReynolds Do we really want a Donate button **and** an ad-block … on a page that is recruiting volunteers??

Another (unrelated) issue is links that open in a new page, without warning. Also a scattering of typos and a couple of clunky phrases and sentences.

**Comment by AlOneill** [comment]
@Captainkirkdawson The re-built DRAFT version of the FreeCEN page is behaving as expected in Refinery: the HTML pane opens, so the editing issue is fixed.

Will not promote from DRAFT status until checked by someone who can confirm that all is truly working as expected. And I still have no idea what the original problem was.

As well as the issues mentioned above, the markup of the page seems overly complex and probably could be simplified somewhat, with a more logical, and thus accessible, flow. However, the positioning of the ad-block — using `position: fixed` — does restrict the possible source order.

Er, shouldn't these comments be on the CEN board rather than here? (Or perhaps on system-wide as the page for each project will be very similar??)

**Comment by richpomfret** [comment]
@richpomfret follow-up on this.

**Comment by AlOneill** [comment]
@richpomfret Have replacement images (a choice of) from @DeniseColbert and will experiment to see which works best in situ (got interrupted by work on UCF Help for researchers and transcribers).

Will need to replace image on CEN too.

**Comment by AlOneill** [comment]
@PatReynolds @richpomfret @SteveBiggs 
Image replaced and viewable on DRAFT version of page. No other changes made by me.

I have 2 questions:

1. Is this how we expect it to look, in a box with a white background? I suspect, yes.

![DRAFT_Opportunities_to_Volunteer_with_FreeREG-1169.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/16ec13a8-6814-444d-980e-0a3350406016)

2. Is this how it should look on a laptop-width screen (c 900px), wider but still floated right? I'm thinking, no.

![DRAFT_Opportunities_to_Volunteer_with_FreeREG-974.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/a18015c0-890f-44ff-8656-19b0c90e7c62)

**Comment by AlOneill** [comment]
@PatReynolds @SteveBiggs Have a third question: do we wish to keep the extravagant focus/hover behaviour of the "Proceed for Registration button?

I don't remember why this was done, unless to compensate for previous contrast-ratio issues across the projects? This bevaviour is not used anywhere else, AFAIK.

**Comment by PatReynolds** [comment]
1. Yes that's how it should look
2. No, that's not how it should look
3. I'm easy.  It's eye-catchying but if people want to register, I think they know they do and don't need to be attracted by graphics.

**Comment by AlOneill** [comment]
I've sorted out the behaviour of the Registration button and the display of the Donate button, removed the ad and made an attempt to simplify the crazily-complicated markup, correcting some typos, improving accessibility and adjusting some clunky sentences on the way.

However, I could've inadvertently broken other aspects of how this page is meant to work. In particular:
* @richpomfret is David's event tagging for the Donate button still intact?
* @PatReynolds is the responsive behaviour of the page, *across all window widths*, as you asked for?

Please both confirm that all is well with the [draft opportunities to volunteer page](https://test3.freereg.org.uk/cms/draft-opportunities-to-volunteer-with-freereg). Thank you!

**Comment by AlOneill** [comment]
PS Probably just me, but I could not find a link to the (current) page, except on the the Members page.

**Comment by PatReynolds** [comment]
Responsive behaviour seems fine.  The donate button drops beneath the first paragraph, and if it could drop to the end, that would be better in this instance (where the 2/5 is an index, it is a perfect position).

The link to the donate page (https://www.freeukgenealogy.org.uk/help-us-keep-history-free) works fine.

On a large android phone:
![image](https://user-images.githubusercontent.com/6338822/91879326-e413fd00-ec77-11ea-907d-8d79a21500b1.png)

**Comment by AlOneill** [comment]
@PatReynolds I don't understand. The phone screen-shot is of the current page, not the DRAFT page. So not sure what you are asking for.

**Comment by AlOneill** [comment]
@PatReynolds OK, I _think_ I understand you. Have moved Donate to last in source order, so that it displays at the foot of the page on a 'mobile-width' screen, that is at 570px and less. Is that what you meant?

https://test3.freereg.org.uk/cms/draft-opportunities-to-volunteer-with-freereg

**Comment by PatReynolds** [comment]
Oooh - that is _exactly_ what I meant!  And now I can see the new text, and the button!  Happy to see this deployed.

**Comment by PatReynolds** [comment]
Using your link, I see the draft, using https://test3.freereg.org.uk/cms/opportunities-to-volunteer-with-freereg I see the old version (I get there by clicking on 'volunteer' in the header.

**Comment by AlOneill** [comment]
@PatReynolds Will make ready as long as @richpomfret (or someone!) can confirm that David's custom event tagging has not been disrupted — I have no idea how it works!

**Comment by PatReynolds** [comment]
Thanks, @AlOneill I will check with David.

**Comment by AlOneill** [comment]
Will do the equivalent pages on CEN and BMD next.

**Comment by Vino-S** [comment]
Deployed to production
