### ISSUE TITLE
Birth dates are  not validated properly

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2282]

**Comment by PatReynolds** [comment]
May be implicated in #2278

**Comment by Captainkirkdawson** [comment]
Believe this is fixed on test3

Please note January, February etc are valid months and handled correctly in the search

**Comment by SteveBiggs** [comment]
Can you clarify what has been fixed as it's not clear to me how to test?

**Comment by Captainkirkdawson** [comment]
A birth or baptism date edited on line (or entered in the batch for that matter) should be declared invaild if it is incorrectly formatted eg  the month misspelt  (Entered as 3 letters or 4 for Sept; or in full as in January) day is too big or negative or year comes first

**Comment by AlOneill** [comment]
The fact that full names for months are valid, along with the 4-letter Sept, is not covered by the current transcriber instructions. Will open an issue to update the instructions.

**Comment by SteveBiggs** [comment]
Transcribers are used to the rule that the date should be entered as DD Mmm YYYY. I think it will only confuse things if we now tell them they can use full month names or 4 letters for Sept and lead to the likelihood of more errors.

**Comment by Sherlock21** [comment]
I completely agree with you, Steve.

**Comment by SteveBiggs** [comment]
Made a number of tests on test3 with dates:
(27 Feb 1859 is the original date). Results:
Accepted: feb, february, February, sep, sept, september, 
Rejected: fev, februaru, febr, septembet

Given the issue of #1310 where lower case is considered a data error, why is feb, sep, etc. not rejected?

**Comment by SteveBiggs** [comment]
Also tried FEB which was accepted but not found by the single year search of #1310 so that should be rejected too?

**Comment by Captainkirkdawson** [comment]
I have run some of my own tests again and am now deeply confused as the results seem dependent on either record type or month or perhaps both hence I withdraw all prior comments on this issue until further research has been conducted.

**Comment by Sherlock21** [comment]
given that the situation appears a bit more difficult that first thought, ir=s it not time to change all dates that are in the various inherited forms, into ones that are in the format ddMmmyyyy?
or of course * as appropriate if necessary
a list of how many are non standard dates would help in this process and show if its easier to correct the data buy hand online, or devise complex code fro processing,  including.

then with only one format to deal with, it should be relatively simple - and the user instructions would not need updating.

**Comment by Captainkirkdawson** [comment]
If only it were so simple. We only have some 60 million date fields to review.

**Comment by Sherlock21** [comment]
I am not suggesting that it would be easy, but,,
isn't it better to know the size of the problem - ie how many records have the now not valid date format, then it would suggested one to decide whether to get them corrected or alternatively to struggle and revise the code to cope with them?

**Comment by Captainkirkdawson** [comment]
Story 2278 identified the scope of the problem
Full file uploaded to gdrive
https://drive.google.com/open?id=1K_RhemeZcpe2BydLMK4bgBd_nx01vtdm

**Comment by Captainkirkdawson** [comment]
Propose to close in favour of #2278
