### ISSUE TITLE
Embargo rules problem

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2284]
From Jackie James:

The entries from 1920 -1924 are showing when I look at the file, and I've just tested a couple in searching, and they were not embargoed.

This is the screen print of the rules I created. What should I have done differently do you think?
![image.png](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/9f781587-9e1b-41ed-873c-7d58c39c9486)

It looks to me as though Jackie has entered the embargo correctly but when you go to the Batch Information and click 'Listing of embargoed entries' there are none in the list.

**Comment by SteveBiggs** [comment]
Latest from Jackie:

I have just created an embargo for the PR MA register of SOM Backwell, and uploaded SOMBACMA7, MAs from 1917 to 1921, and this embargo seems to have worked. 

The only difference between this one and SOMMERMA2, so far as I can tell, is that there is only 1 Backwell embargo (for the MAs) whereas for Merriott I created 3 one for each of BA, BU and MA, although so far I have only uploaded 1 file.

**Comment by Captainkirkdawson** [comment]
Issue is that the process that reviews existing batches for embargoed entries against a new rule is currently stalled.
A new file uploaded against an existing rule is correctly processed at the time of creation of the file.
Will investigate the reason for the stall; the files that are to be processed are known and will be processed at the end of the investigation so Jackie needs to undertake no corrective action at this time nor does she need to undertake investigation herself. Issue is clear and well understood.

**Comment by SteveBiggs** [comment]
Thanks @Captainkirkdawson. I'll inform Jackie.

**Comment by Captainkirkdawson** [comment]
I believe it may well be resolved

**Comment by SteveBiggs** [comment]
Jackie reports it all looks good now and says thank you.

**Comment by SteveBiggs** [comment]
Jackie reports a new problem that may be a consequence of this change?

Another little difficulty with Embargo this morning. 
I went to set the Embargo rules for SOM Brockley PR. It was only showing 2 record types, bu and ma, NOT ba.

I thought maybe I'd forgotten that I'd done it earlier, and ploughed on, set the bu and ma embargoes. Although it allowed me to start creating a third embargo, when I get to the screen, there's no record type option see screenprint
![image.png](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/beee5afc-c42c-4e4d-9dbe-0f02cbbef599)

There are three record types in the Transcriptions though, so it's not that. 
![image.png](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/26ca2728-6349-4903-85ea-4d70381e160a)

**Comment by Captainkirkdawson** [comment]
Totally different issue. Placed in its own story
