### ISSUE TITLE
Update transcriber instructions for entering months in dates

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/MyopicVicar#2293]
As the full name of a month is valid, as is the 4-letter 'Sept', the instructions for transcribers should be checked and updated as necessary. Currently, only the 3-letter abbreviations are described as acceptable.

There are 3 pages to be checked and potentially updated: Information for transcribers, Numbers and dates, and Flexible CSV.

**Comment by Captainkirkdawson** [comment]
The preferred format remains the same; do not really want people using the others which are there for historical reasons

**Comment by AlOneill** [comment]
Noted. *If* we decide to update, then info would reflect comment above from @Captainkirkdawson

**Comment by SteveBiggs** [comment]
Per my comment in the original story, I would vote we do not update the instructions please.

**Comment by AlOneill** [comment]
Sound. Will close.
