### ISSUE TITLE
Multiple witnesses

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#23]
Andy reports:

Where there are more than two witnesses to a marriage the instruction is to repeat the entry and change the witness names. This currently results in more than one result eg

     # Record Type Marriage Date Surname Forename County Place Name Found As
     1 Marriages 03 Mar 1853 ROYNON Thomas Somerset Churchill Groom Father Surname, Groom Surname
     2 Marriages 03 Mar 1853 ROYNON Thomas Somerset Churchill Groom Father Surname, Groom Surname
     3 Marriages 03 Mar 1853 ROYNON Thomas Somerset Churchill Groom Father Surname, Groom Surname

The details on each are the same except for thw witnesses and Notes eg

Search Record Details
     County Somerset
     Place Churchill
     Church St John the Baptist
     RegisterNumber 52
     MarriageDate 03 Mar 1853
     GroomForename Thomas
     GroomSurname ROYNON
     GroomAge 36
     GroomParish
     GroomCondition Bachelor
     GroomOccupation Farmer
     GroomAbode Churchill
     BrideForename Mary
     BrideSurname SHORLAND
     BrideAge 30
     BrideParish
     BrideCondition Spinster
     BrideOccupation Servant
     BrideAbode Churchill
     GroomFatherForename John
     GroomFatherSurname ROYNON
     GroomFatherOccupation Farmer
     BrideFatherForename John
     BrideFatherSurname SHORLAND
     BrideFatherOccupation Labourer
     WitnessOneForename Ann
     WitnessOneSurname JENKINS
     WitnessTwoForename James
     WitnessTwoSurname CLEGGE?
     Notes Duplicate entry, 6 witnesses. Bride and Groom sign X
     FileNumber 12946

In such situations could the additional entries be combined so that just one record is displayed with all the witnesses shown?

**Comment by PatReynolds** [comment]
Is this still open?

**Comment by Captainkirkdawson** [comment]
Yes to a degree.

While FR2 handles the storing of multiple witnesses there are a number of issues that need addressing  as to how this is implemented in CSV files

**Comment by Captainkirkdawson** [comment]
System already supports multiple collection with on_line entry and edit capability. Need
1. Display multiple witnesses, See 570
2. Download multiple witnesses in current csv format See 741
3. Combine current csv multiple records 
4. Search on witnesses
5. Use new format csv to input.
6. Download in new csv format

**Comment by edickens** [comment]
5.  Do we have a definition of the new format csv?  It is needed to
    handle more than two witnesses.  Mike might like to know and is it
    being built into WinFREEREG?  TY  E
    
    On 26/05/2016 15:18, Kirk Dawson wrote:
    
    
      System already supports multiple collection with on_line entry
        and edit capability. Need
        1. Display multiple witnesses, See 570
        2. Download multiple witnesses in current csv format See 741
        3. Combine current csv multiple records 
        4. Search on witnesses
        5. Use new format csv to input.
        6. Download in new csv format
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly or view
          it on GitHub

**Comment by Captainkirkdawson** [comment]
With respect to 813 we do have a concept for a new format of which Mike is aware

**Comment by Captainkirkdawson** [comment]
I believe we have written the stories required for this epic
