### ISSUE TITLE
Issue with layout on small screens

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2300]
FreeREG has started to write boxes on top of one another. Daniel also commented that adverts are appearing over the table (I assume a similar cause).

https://photos.app.goo.gl/S2bnhTjXD7Z8TtNx9

**Comment by richpomfret** [comment]
Outline specific steps for replicating. @PatReynolds let's discuss and then move over.

**Comment by PatReynolds** [comment]
No overlap on android 10 

Next and previous results buttons missing.

"Details" appears twice at the top of the entry in the search results:

![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/ca8739d1-c45d-4a23-b9f4-a73b67be091e)

**Comment by PatReynolds** [comment]
Need to change the "Detail" link to "View".

**Comment by PatReynolds** [comment]
Suggest we recruit volunteers who would be able to test on common/recent phones (e.g. via a post in the Transcribers group).

**Comment by PatReynolds** [comment]
The Information About ... tables do not scroll sideways, and do not re-orient when a phone is turned on its side.

**Comment by PatReynolds** [comment]
@PatReynolds to check the rotation on other phone.

@Vino-S to look at scrolling

**Comment by PatReynolds** [comment]
Tickyboxes not working on small phone.  Tables do not scroll sideways there, either.

See image from Pixel3 - worse overlapping on the little phone but had no screenshot function.
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/d1796e10-f0bf-4b86-bfcf-728ce676b9dc)

.

**Comment by Captainkirkdawson** [comment]
Sorry @PatReynolds but what were you doing and how. The picture on its own is not enough

**Comment by PatReynolds** [comment]
I was looking at the 'Information About' table.  This is the view, and there is no scrolling to see more.

**Comment by SteveBiggs** [comment]
FYI it looks fine if you rotate the phone to landscape - at least on my Samsung Galaxy A71.

**Comment by PatReynolds** [comment]
Ah - had my phones locked not to auto-rotate.  Now works fine. :-)

**Comment by PatReynolds** [comment]
@AlOneill to add note to supported browser box to note the need for rotate to be on.

**Comment by PatReynolds** [comment]
@PatReynolds to check the help

**Comment by AlOneill** [comment]
Have updated https://test3.freereg.org.uk/cms/help-draft with the amended text. (Awaiting verdict on whether we replace "Unique names" with something more appropriate. See issue re the source order of Help.)

**Comment by AlOneill** [comment]
Tried to update CEN, but there is no such notice on CEN, Help. I will add it — unless there is a reason not to?

**Comment by AlOneill** [comment]
The BMD notice does not have that paragraph.

**Comment by PatReynolds** [comment]
~Unique names now repaced - can you take another look at the text @AlOneill ?

**Comment by AlOneill** [comment]
Text re smart phones added to CEN: https://test3.freecen.org.uk/cms/draft-help#usingSite

**Comment by PatReynolds** [comment]
Thank you, @AlOneill - this is good to go.

**Comment by PatReynolds** [comment]
@PatReynolds to check that it has been deployed
