### ISSUE TITLE
Sequence of Counties presented to a new volunteer?

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#2301]
When someone starts registration they aer offered a list of Syndicates looking for transcribers.  The sequence used to have "Anywhere" and "Ask a question" at the top, but it is now:-
![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/412893ec-39b0-45d9-a132-f9b791992f89)
I would like to know how this is decided.
The important ones are near the bottom:-
![Capture1.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/91ea2b9f-60b1-4f55-81be-c188d952de2d)
I think this change has only happened recently because many do choose "Anywhere".

**Comment by Captainkirkdawson** [comment]
Changing order to alphabetic

**Comment by Captainkirkdawson** [comment]
@edickens Changed sequence to alphabetical. On test3 for review

**Comment by SteveBiggs** [comment]
Looks good on test3.
