### ISSUE TITLE
Update Transcriber info pages re use of UCF in dates

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/MyopicVicar#2303]
Update General guidance section on Entering data from registers.
Update same on Flexible CSV page, noting use of single * for missing dates in MIs.
Put note/link to revised instructions in UCF section of Dealing with Uncertainty.

**Comment by AlOneill** [comment]
Duplicate so closing

**Comment by AlOneill** [comment]
Oops, not a duplicate, so re-opening.

**Comment by AlOneill** [comment]
@SteveBiggs @Captainkirkdawson  Am I right in thinking that anyone transcribing MIs should be using flexible CSV and *not* the standard/original fixed format? Thanks.

**Comment by SteveBiggs** [comment]
Flex CSV has extra fields for memorial information, burial location, etc. If the standard format is used, all that would have to go in the Notes.

**Comment by Captainkirkdawson** [comment]
Absolutely correct, MI should use Flex as @SteveBiggs notes

**Comment by AlOneill** [comment]
@Captainkirkdawson Thank you for being so clear.

@SteveBiggs I wasn't sure what to make of your comment — I understand the issue but was wondering if I had read between the lines correctly. My problem, not yours!

**Comment by SteveBiggs** [comment]
@AlOneill I was deliberately non-committal as you COULD use either but flex is clearly better.

**Comment by SteveBiggs** [comment]
It would be useful to also copy the details of UCF in dates to the "Dealing with Uncertainty" page

**Comment by AlOneill** [comment]
@SteveBiggs It is not a good idea to duplicate instructions as one set could be updated but not the other (flexible CSV page is exception and seemingly unavoidable). That is why I proposed (in issue description) to provide only a note and link to General Guidance from the Dealing with Uncertainty page.

I am assuming that a transcriber is more likely to consult/review General Guidance than Dealing with Uncertainty. If you think I have this the wrong way around, then do say.

**Comment by SteveBiggs** [comment]
A link from Dealing with Uncertainty to the 'UCF in dates' section under General Guidance should be fine as long as the link is obvious.

**Comment by AlOneill** [comment]
@SteveBiggs I'm putting in the finishing touches to: Flexible CSV, General Guidance, Dates. Is the missing date in MIs, that should be recorded with a *, the date of death, the date of burial, or both? (I can argue it all sorts of ways in my head!) Thanks.

**Comment by SteveBiggs** [comment]
The important one is the date of burial. The date of death is only entered if it is present.
If neither dates are present, it's only necessary to put a * in the burial date.

**Comment by AlOneill** [comment]
@SteveBiggs @Captainkirkdawson  The 3 pages listed in the description are ready for review.

Please note that the links between these 3 draft pages will take you to the current pages and not the revised, draft pages. This is to comply with our protocol for editing pages in Refinery.

**Comment by SteveBiggs** [comment]
For the date of death, would this be clearer?:
- if the date of death is missing, leave it blank

**Comment by AlOneill** [comment]
Fair enough! Amended.

**Comment by suffolkroots** [comment]
Now I'm baffled. In MIs there is only the date of death, and I was informed that * should be used if this date is missing. Are we now to return to blank dates?

**Comment by SteveBiggs** [comment]
@suffolkroots is that the case for all MIs? I thought in some cases, the burial date was included and sometimes not. The intent was that wherever it is not stated, a * should be put (regardless of whether the death date is present).

AFAIK, we could put a * in either (or both of) the death or burial date, but only one is required. Perhaps it would better to say that if either date is missing, put in a *

**Comment by suffolkroots** [comment]
@SteveBiggs in the MIs we have there is hardly ever a burial date. Feel free to check on WRY.

**Comment by SteveBiggs** [comment]
Of course, I should have thought about it that gravestones usually state "Died on ...." and rarely include burial date. But the record type we are using for MIs is a burial so if there is neither a death nor burial date stated, would it make most sense to put the * in the burial date field?

**Comment by suffolkroots** [comment]
Not really, it's the death date that is missing, all entries with a date 
are in the deaths column. The * indicates "no death date".

It would make no sense to enter "no burial date", as there clearly will 
be a burial date in the relevant burials record.

**Comment by AlOneill** [comment]
I'm not sure what the conclusion is for dates in MIs. The draft reads:

*    if the date of death is missing, leave it blank
*   if the date of burial is missing, enter a * for the burial date

Should that be:

* if either date is missing from your source, enter a \*

PS if you want a literal asterisk when writing on ZenHub, you will need to escape it with a backslash: `\*`. This is because an asterisk is used as Markdown markup.

**Comment by AlOneill** [comment]
PPS use the Preview tab to check that your comment reads as intended :-)

**Comment by SteveBiggs** [comment]
Because there is usually a death date but rarely a burial date on graves, for MIs we want:

if the date of death is missing, enter a * for the death date 
if the date of burial is missing, leave it blank

P.S. I use GitHub for replies and * works fine in that. Just looked in Zenhub and they look fine too so I'm confused by your comment.

**Comment by AlOneill** [comment]
@SteveBiggs Thanks for the clarification re dates.

I should've been clearer — the problem with asterisks occurs where using 2 of them in the same para — they are interpreted as delimiters, so the asterisks disappear whilst the text is made italic, as here, in an earlier post of yours:

![pair of asterisks.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/c4705016-8e6f-4b49-946d-a307aaf5199a)

**Comment by AlOneill** [comment]
Flexible CSV page updated as per.

Are we done? Should I make all 3 pages ready for publishing?

**Comment by SteveBiggs** [comment]
Thanks for the clarification @AlOneill. As I said, I always reply in GitHub where the problem does not occur, but I'll bare it in mind for the future.

**Comment by SteveBiggs** [comment]
Pages look good to me.

**Comment by AlOneill** [comment]
@SteveBiggs  Thanks.

All 3 pages now replaced with updated instructions and ready for syncing.

Moving to: Ready for user Testing
