### ISSUE TITLE
The 'Number of files' in userID Profile looks wrong

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2304]
Under Profile for userID LINCC it says that the 'Number of files' is 52, but clicking 'List batches' returns No files exist.
Eric thinks the 52 refers to all files uploaded BY LINCC rather than TO LINCC, but Michael Clarke says he has uploaded many more than 52 on behalf of other userIDs.

What should the 52 refer to?

**Comment by Captainkirkdawson** [comment]
@SteveBiggs Used consistent method. Please test on test3

**Comment by SteveBiggs** [comment]
Looks good on test3
