### ISSUE TITLE
Restructure Unique Names

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2309]
When unique names was introduced it was included as part of the Place , Church Register and File collections.
This clearly makes a performance problem when using these collections.
The unique names should be moved to separate collection  as referenced single collections 

E0 U6 S7 C4: P17

**Comment by richpomfret** [comment]
@PatReynolds to add in a priority.

**Comment by Captainkirkdawson** [comment]
This is urgent as it is causing memory problems on the production servers I believe

**Comment by Captainkirkdawson** [comment]
Moving fields from the Place , Church and Register collections and placing in separate collection. This should improve performance of the Place load

**Comment by Captainkirkdawson** [comment]
Restructured unique names to use separate collections to reduce size of Place document. Deployed to test3
