### ISSUE TITLE
Improve the format of the Message notification email.

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#2310]
The Contact system shows the text in the incoming request as part of the email sent to Coordinators.  Please can the email for the Message system do the same.  The Subject line should describe the content, but at present it is necessary to log in to see it and so decide whether it is urgent or not.

E0 U3 S8 C6:P17

**Comment by richpomfret** [comment]
@PatReynolds can you add a priority for this.

**Comment by PatReynolds** [comment]
@PatReynolds  to talk to @Vino-S about this

**Comment by PatReynolds** [comment]
It needs to work like the contact system message.

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by edickens** [comment]
I don't know if the original message works, but a Reply to a message does NOT include the text of the message in the same way as Contacts does.

**Comment by edickens** [comment]
@Vino-S the email sent when a new message comes in is not in the same format as the Contacts email.  You have added the text of the message, but it is embedded in the message and not at the end.  I think that the two should be same because we get a mixture of them every day.  The contact looks like this...
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/d067308d-9f53-41be-ac65-d3bfca695e84)
whereas your is like this...
![image.png](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/2dfd01e9-e54b-41c3-81ce-600fd706c717)

Thanks,
Eric

**Comment by PatReynolds** [comment]
@Vino-S to make the changes

**Comment by Vino-S** [comment]
Made the changes. Ready for testing in test3.  
Added the Message content to the end of the notification email.

**Comment by SteveBiggs** [comment]
Looks good in test3.

**Comment by DeniseColbert** [comment]
New story for updating text - closing
