### ISSUE TITLE
List GAPs for a batch shows the GAPs from a different batch

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2311]
If I List GAPs for batch LINCACBU2 (which has no GAPS entered), it displays the GAPs in LINCACBU:
![image.png](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/21959c04-fab7-4a6a-a5e2-033f17d6622c)

**Comment by Captainkirkdawson** [comment]
Fix applied to test3

**Comment by SteveBiggs** [comment]
test3 still has the same problem:
![image](https://user-images.githubusercontent.com/25303607/86487195-62762080-bd55-11ea-8ab5-0411fa9e9ba5.png)

**Comment by Captainkirkdawson** [comment]
@SteveBiggs sorry about that please test again

**Comment by SteveBiggs** [comment]
Looks good now, thanks.
