### ISSUE TITLE
Add pop-up 'Are you sure' box when using 'Convert to Issue' action

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2313]
In Contacts and Feedback adding the box will help prevent unintended issues being created.

**Comment by Captainkirkdawson** [comment]
Added to both contacts and Feedback; committed to test3

**Comment by Captainkirkdawson** [comment]
Had finger problem with first commit. OK now on test3

**Comment by SteveBiggs** [comment]
Tested and looks good.

**Comment by Vino-S** [comment]
deployed to production.
