### ISSUE TITLE
LIN File not linked

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#2316]
UserID Mick, file LINLEDMA1.CSV

![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/96b480a2-9e6d-4c62-95f1-d797ea026465)

**Comment by edickens** [comment]
This may have occurred when relocating from Unspecified Register Type.

**Comment by edickens** [comment]
This is a bit more complicated.  The clip above is Batches.  There should not be two files of the same filename in the UserID.  If you can just let me have the file I can sort it out.

**Comment by edickens** [comment]
I have got this file from FR1.  It has records with no Church.  Michael was unlucky to try to relocate this batch.  I will see if we can sort it out.  Probably delete, sort it out, and upload.

**Comment by edickens** [comment]
The Download of LINLEDMA1.CSV under Physical files (26 December 2008) for UserID Mick does not seem to work.  Please let me have the file.

**Comment by richpomfret** [comment]
No longer required.
