### ISSUE TITLE
Update Help section on Responding to Contacts

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2317]
The Coordinator Help for Responding to Contacts refers to the old system of replying via email and destroying the Contact:
![image.png](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/e69f1cd8-fd56-44aa-8076-b033dd8dad88)

Need to update to reply via FreeREG website and Archive rather than Destroy.

0 3 S7 8: P18

**Comment by SteveBiggs** [comment]
Assigned @AlOneill

**Comment by AlOneill** [comment]
DRAFT Info for Coords page being edited off-line for stories #2317 and #1549 — it will be overwritten to create a new master version. AO 31 Dec 2022

**Comment by AlOneill** [comment]
It looks like the necessary changes have been made already. @SteveBiggs can you confirm that this DRAFT page is now correct? https://test3.freereg.org.uk/cms/information-for-coordinators/draft-coordinator-actions
 Thanks.

**Comment by SteveBiggs** [comment]
Yes, looks good, thanks.

**Comment by AlOneill** [comment]
Thanks @SteveBiggs .
Page is now sync-ready so moving to "Ready for user testing".

**Comment by SteveBiggs** [comment]
This is superseded by #1492 so can be closed.
