### ISSUE TITLE
 Consider changing modified place name to standard place name as done for Freecen2Place

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2318]
We changed the handling of the modified place name to a standard place name in Freecen2 for both place name and alternate place name to ensure consistent testing

**Comment by Sherlock21** [comment]
I really don't understand what this is about - if I am supposed to
Else was I meant to ignore this?

**Comment by richpomfret** [comment]
Opted to close for now.
