### ISSUE TITLE
Add details on old abbreviations to the Transcribers' Help

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2320]
Cathy Jury has written some useful notes on abbreviations that we should add to the help. I've sent details by email to @AlOneill 

E0 U3 S6 c5:P14

**Comment by SteveBiggs** [comment]
I had a question today asking what to do with abbreviations when transcribing so it would be good if we could get this added to the Help asap please.

**Comment by AlOneill** [comment]
I have made a start on getting this into shape, but would appreciate some guidance on the exact form of the UCF for this paragraph:

"Figure 3 is an example of the Greek letters ΧΡ used as an abbreviation for ‘Christ’, in this case for Christofer. This should be transcribed with ‘Christ’ in UCF and with a note such as — Start of first name 'XP-' (the Greek letters 'chi' 'rho' are an abbreviation for Christ)."

Would the UCF be: Chr[i_][s_][t_]ofer ? Although it may be obvious for the quick-witted amongst us, it took me a good while to think it through …

Thanks!

**Comment by SteveBiggs** [comment]
@AlOneill I discussed this with Cathy and she admits she is being somewhat over-cautious by suggesting the use of UCF. We have agreed that so long as a suitable note is included stating that the original register entry read 'Xpofer', then the transcription should simply be 'Christofer' with no UCF.

However, I've just looked at the forename abbreviations listed in the emendations and see that:

- Christofer is NOT listed at all (should it be a variant of Christopher?)
- xpian is NOT listed as a variant of Christian
- xpine is NOT listed as a variant of Christine
- xpopher is NOT listed as a variant of Christopher

Should these be added?

**Comment by AlOneill** [comment]
Have hit a Refinery issue — will not save page (DRAFT Dealing with uncertainty, t3). 

@Vino-S can you shed any light here? The Refinery content of the page is not as big, at around 30kB, as our biggest page, at 53kB. Most recent failed save at about 15:45 on Saturday (26th). Several attempts failed on Friday (25th). Markup is valid.

**Comment by Vino-S** [comment]
Hi @AlOneill , MySQL threw a Character Encoding error. 
There might be a text or character that might not comply with UTF-8 encoding.
I have copied the DRAFT Dealing with uncertainty HTML on a test page and I was able to save it.

**Comment by AlOneill** [comment]
@Vino-S Thank you. Yes, what is there now is what it _would_ save — but there are another 40-odd lines that it would not save. So, I'll examine those carefully for non-UTF-8 characters. That sounds promising as the source text is from a Windows user. Fingers crossed :-)

**Comment by AlOneill** [comment]
@Vino-S Eventually discovered that the issue was two innocent-looking characters (on Mac) that turned out to have Windows encoding: what looked like Latin X and P were in fact the actual Greek capital letters 'chi' and 'rho'. So all now well. Thank you again for pointing me in the right direction.

**Comment by AlOneill** [comment]
@SteveBiggs Thank you. I agree that all the four variants you mention should be added to the forename emendations.

**Comment by AlOneill** [comment]
Refinery will not save the Greek letters where entered as HTML entities, so will have to stick with the Latin close-match characters in the explanation.

**Comment by AlOneill** [comment]
@SteveBiggs The page, [DRAFT Dealing with uncertainty](https://test3.freereg.org.uk/cms/information-for-transcribers/draft-dealing-with-uncertainty) is now ready for review.

I took the opportunity to replace all non-semantic use of the `q` element with (curly) single quotation marks and to update the styling of the UCF section, now that brown is no longer in our palette.

**Comment by SteveBiggs** [comment]
Looks good to me.

**Comment by AlOneill** [comment]
"Dealing with uncertainty" is now sync-ready.

**Comment by Vino-S** [comment]
deployed to production
