### ISSUE TITLE
Emails not being sent/received

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2324]
Email from John, via Eric D 

I have received an email this morning from Jo regarding a new
> transcriber who apparently joined my team last week. I did not receive
> any notification about this and also sometimes I get auto emails about
> uploads of files and sometimes I don't. A couple of transcribers have
> also not received auto emails recently either about uploads. I haven't
> changed my email address and neither have any of my team. Is there
> something wrong with the FreeREG email system.
>
> Best wishes
> John

**********
> Mick has reported similar.

**Comment by PatReynolds** [comment]
closing as duplicate
