### ISSUE TITLE
Accessing images in T3

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#2327]
My understanding is that there is not a set of images for use in T3.  So what happens if someone sets up an Image Group in T3?  And what happens if someone accesses images through T3?  Would this change the production access to images?
If working with Image Groups and Images in T3 could cause problems, then a caution message should come up or some actions need to be blocked.

**Comment by suffolkroots** [comment]
I have various sets of WRY images for access/use through T3, although I've never used them.

**Comment by PatReynolds** [comment]
Delition is not possible, renaming is not possible, images cannot be replaced.  A new mage could be loaded, but that would not be a problem. If they were then uploaded on live, that would not be possible - but easily fixed.

So closing.
