### ISSUE TITLE
Wrong place showing to researchers

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2331]
From Michael Clarke and Eric Booker:

I did an ordinary user search for surname - Kirmington in Lincolnshire in 1807 - see result:

![image.png](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/97808d0b-ceed-4b73-9e90-fd3a140db735)

notice that the person is in 2 places at once!

then I selected View1:

![image.png](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/b619d380-0996-44ec-830d-cc8b950d1ea3)

note the header place name: WRAWBY
and note the place name in the table insert : Place - Baumber despite the header saying WRAWBY.

I repeated this for a randomly selected 4 names from the WRAWBY file, and the same outcome: there is one creation for Wrawby and another identical one for Baumber.

So it seems to me that something serious went wrong here.

I therefore ask for a detailed investigation by the programmers.
What went wrong?
it it just this file or are there more like it?

should we hold off any more file uploads 
should we hold off any more changes of anything?

or worse!

**Comment by PatReynolds** [comment]
@PatReynolds to look for other examples.

There are no files in Baumby.

@Vino-S to take a look

**Comment by PatReynolds** [comment]
Search ![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/f1f3c8b2-42fe-4e77-b9e7-292653476a0d) - all good apart from:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/5abee6d7-cf6a-48a9-9ab4-fcd75e2e7dbf)

![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/84f7f14c-5daa-4b7b-aa77-62736b75f4ce) all good apart from
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/38d66bd9-cf67-4fc6-ab98-72e2edd89d93)
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/efe9420c-0c63-434b-a0ad-396c133a74f7)
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/5941d301-4d5f-4d94-a274-ed16ab883382)
Presume the following are different sources of the same event:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/60634a9a-5672-4be1-a976-52bc266af31f)
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/e912c72f-bddc-4738-bb11-b6ef579f9e43)
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/9ad99691-5048-4760-83d2-47c2a0e60e32)

![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/ff20979a-da46-46c9-b6f7-a3c6ac8aa277) all good apart from
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/864f441b-e6a0-40a0-a2f5-95fc10c09726)


![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/4acbe331-8977-487b-a73b-8852d98eacfd)

A search for John Austin Burial Norfolk 1790-1800 shows a range of duplication, possible duplication and non-duplication.


A ser4ach for Jones, all types, county by county found
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/a42f852a-765f-43b3-b3e4-9aadad0f10fb)
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/500160d1-e9f6-42f5-816a-26b679677c9d)
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/e742ccea-43cc-4f56-befb-21039a08be83)
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/d83cead8-de7f-4701-bcd1-3eb468d4f52f)

**Comment by edickens** [comment]
What we don't know here is whether the Batch has ever been relocated.  The Place, Church, Register Type are held in too many records.  The original file which can be on the transcriber's PC, the uploaded file, the indexed Batch entry, and in the Place's information.  So when a Batch is relocated, these all have to be changed.  I don't think this happens, at least not to all of them.

I can't see any other way as to how this problem could occur.  And I don't know how it can be fixed other than downloading the file, amending it, and uploading again as a new file.  But how many of these are there?

Eric

**Comment by PatReynolds** [comment]
Only resolution is to use just the parish - making two look-ups rather than current single look-up.

Make parish relocate a Data Manager only function.

Drop church and register type from the detail.

**Comment by edickens** [comment]
I will send a message to Coordinators to tell them what we intend to do.

**Comment by Captainkirkdawson** [comment]
I have now had time to look at the original posting by  Michael Clarke and Eric Booker:
Focussing on the record in view 1. 
The record was the 3rd record of the original file LINWRABA.CSV. It was loaded onto Freereg1 on  20 Oct 2014 (23:24) and had a size of 596,894 bytes. It was processed into Freereg2 on 10 Mar 2015 (19:04) with location : LIN,Wrawby,St Mary, There is sat until 8 June 2020 15:30:47 when it was processed and changed to LIN,Wrawby,St Mary  ,  or relocated and downloaded. Then on 24 October 2020 16:14:59 it was relocated to LIN,Wrawby,St Mary  PR, and downloaded. The same file was downloaded on 10 November 2020 15:44:48. The file was online updated again after that with no downloads. The file is 7500 records and 768,000 bytes so cannot be processed by an upload or replace. My suspicion is that an online relocation was undertaken with an incorrect selection. A file of this size could well exhibit a gateway time out on a relocation. 
**I have done an on line relocation back to its state as LIN,Wrawby,St Mary  PR.**
The file for the second record retrieved and viewable as View 2 is from a different file entirely  Mick.LINWRABA50.CSV.3 uploaded and processed on  08 Jun 2020 (15:58).
There is nothing wrong with the upload system. Files of this size are strongly discouraged. It appears the duplication has been caused by having 2 files with the same record.
The erroneous place name is most likely an error in relocation. 
The observations by @PatReynolds  will have to wait for more quality time.

**Comment by SteveBiggs** [comment]
Thanks Kirk. You don't mention Baumber in your explanation - how did that get into the mix?

**Comment by Captainkirkdawson** [comment]
Someone selected it as the name in the relocation sequence of selections. Easily done

**Comment by Captainkirkdawson** [comment]
Dealing now with @PatReynolds observations.
WRT Vicars search. 
The spelling on View 6 is a result of an incorrect entry by wither the coordinator or the data manager. 
Do not understand why the others are problematic.
7 and 8 are from different files patsmith.LINCSABU.CSV.501 and Mick.LINCMCBU9.CSV.998. The first is a parish register the othe is the cemetery record.
WRT Alcock. a) There is no issue.
15 is from sam.WORBROMA1.CSV.258 and 16 sam.WORBROMA1.CSV.259 is from which contains the following note **Copied To Add Extra Witnesses**
49 is from Mick.LINWRAMA3.CSV.12 and 50 wattnb.LINWRAMA.CSV.19 One has witnesses the other does not hence likely different sources. You would have to ask the coordinator what the different sources were
59 is from Louise.NFKNORMA.CSV.3 the other from JJJSearles.NFKNORMA.CSV.302. They contain different information hence from different sources, You would have to ask the coordinator what the different sources were
Refuse to look at the others as there is NO system issue here; just different sources
Talk about wasting my time.

**Comment by PatReynolds** [comment]
Many apologies for not checking thoroughly 

https://www.freereg.org.uk/search_records/5da2177df493fd577f9d2513/emma-jones-baptism-cheshire-burwardsley-1849-02-04?locale=en
and
https://www.freereg.org.uk/search_records/5e0a51caf493fd2538a76d6b/emma-jones-baptism-cheshire-burwardsley-1849-02-04?locale=en

appear to be identical to me.

**Comment by Captainkirkdawson** [comment]
They may be identical but they are 2 different records in the same file
ManCity.CHSBURBA.CSV.216 and ManCity.CHSBURBA.CSV.63
