### ISSUE TITLE
Add a link to FAQs to Researcher Help

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2332]

**Comment by PatReynolds** [comment]
I have made a new DRAFT (called Help (DRAFT), under Help, as I didn't want to confuse it with DRAFT Help (above Help),.

I have added a link to faq in list at the top, and also a paragraph right at the bottom.

Needs review for placement, text, html.

**Comment by DeniseColbert** [comment]
The paragraph right at the bottom is there, and looks good, but I can't see a link at the top:

[Uploading... image.png ]

**Comment by PatReynolds** [comment]
@PatReynolds to check/action

**Comment by AlOneill** [comment]
@PatReynolds The link 'at the top of the page' has been added to the "On this page" sub-menu, which does not make sense as you are taken to a different page!

**Comment by PatReynolds** [comment]
Have placed it as a block - is this better?

**Comment by AlOneill** [comment]
@PatReynolds Yes the block is better, but I've recently come to the conclusion that the `banner` class is awkward for screen-reader users — because the whole block is a link, it is not easy to find in a list of links. (I'll raise a system-wide issue to alter all instances of that construction.)

With your say-so, I'll re-factor the block (on your DRAFT), keeping the look pretty much the same. OK?

**Comment by PatReynolds** [comment]
@AlOneill to refactor the blocks on the the draft page (and elsewhere).

**Comment by AlOneill** [comment]
The call-out boxes that used the `banner` class (on Pat's DRAFT) have now been re-factored.

I have also changed all references (on that page) to the 'Transcriptions' page to 'Records'.

**Comment by DeniseColbert** [comment]
Pat to check link at top of page

**Comment by PatReynolds** [comment]
Not sure what the 'link at top of page' is - the link to "find out what the database contains" (left highest link) and to "exploring the records" (right highest link) both work fine.

However, there is still no link to the FAQs (the purpose of this story).   Is it better to release this updated edition, and then add the link, or add the link before release?  @AlOneill and @DeniseColbert do you have any thoughts?

**Comment by DeniseColbert** [comment]
The link to FAQs needs to be at the top of this page but it had been added to the bottom of the side-menu. This became the block, which is a nice bonus but we really do need the link in prime position.

**Comment by PatReynolds** [comment]
Pat  to move FAQ in the Menu from bottom to top

**Comment by PatReynolds** [comment]
Done.

I hope.

**Comment by PatReynolds** [comment]
@AlOneill to do a final check

**Comment by AlOneill** [comment]
Final checks done, a few tweaks made and "Help DRAFT" promoted to "Help". Updated page is sync-ready.
