### ISSUE TITLE
Add how to send a message under Communicate

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2336]
There is confusion about how to send messages to other members via the Communicate action and it is not intuitive so we should add explicit instructions in the Help as follows:

1. Click 'Communicate'
2. Click 'Create Communication'
3. Type your message
4. Click 'Save Communication'
5. Click 'Show' against the message
6. Click 'Send Communication' (and 'OK in the pop-up box)
7. Use the drop-down menu to select the role of the person you are sending to
8. Click 'Select Role'
9. Use the drop-down menu to select the actual person you are sending to
10. Click 'Send Communication'

E0  U6 S7 C8: P21

I would suggest the 'Send Communication' at step 6 would be better labeled as 'Select Recipient'

**Comment by SteveBiggs** [comment]
Added @AlOneill to update the Help.

**Comment by AlOneill** [comment]
Am proposing to add the instructions to "Info for transcribers" with a note at the top of "Info for coordinators". But I've not tested that I can communicate in this way when logged in as a transcriber.

I think that the list of possible roles for the recipient needs revising — executive_director [sic], for example, is no longer relevant whereas @DeniseColbert 's current role (which I cannot recall) is missing.

I also note that it is not possible to send a message to a transcriber using this system.

I agree with @SteveBiggs that the label for the button at step 6 is not the clearest

**Comment by AlOneill** [comment]
I also note that Rich Pomfret is still listed for some role that I cannot now remember (the role name was a surprise).

**Comment by AlOneill** [comment]
Have added instructions to [DRAFT Info for transcribers](https://test3.freereg.org.uk/cms/draft-information-for-transcribers#communicate) and will ad notes and links described on draft page once review is passed.

**Comment by SteveBiggs** [comment]
Looks good in test3.

**Comment by AlOneill** [comment]
@SteveBiggs thanks. I'll make the remaining edits (link from Coord Actions and note on Info for Coords) in the next few days. Then I'll make (DRAFT) Info for transcribers sync ready and post a comment here.

**Comment by AlOneill** [comment]
@SteveBiggs 
The revised [Information for transcribers](https://test3.freereg.org.uk/cms/information-for-transcribers) page is now sync-ready and the links and notes on the coordinator pages are in place. Ready for deployment.

**Comment by DeniseColbert** [comment]
@Vino-S to contact lemon re Refinery sync failing

**Comment by Vino-S** [comment]
Lemon fixed the refinery issue and Refinery sync ran successfully

**Comment by DeniseColbert** [comment]
Done, closing
