### ISSUE TITLE
Odd place in Jersey

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2353]
Two places in Jersey - one appears to be an abbreviation of St Helier ![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/709b4f43-aaf4-4216-9a7f-d8cd002a68eb)

**Comment by PatReynolds** [comment]
@PatReynolds to ask @SteveBiggs about this.

**Comment by edickens** [comment]
SHL in Jersey has a batch against it uploaded in 2012.  But I can't download it to have a look at it.  I suspect it should have been St Helier but did not match on the conversion from FR1.  Shall I relocate it?

The Place does have a grid reference so has been set up as an actual place.  It has a different grid reference to St Helier and is Brentwood, Essex.  The St Helier grid reference is correct.

**Comment by PatReynolds** [comment]
Grid Reference or lat and long?  

A quick check of Huelin and Cabot as surnames confirms that this is Jersey.  
![image](https://user-images.githubusercontent.com/6338822/100343786-bd940280-2fd7-11eb-96a6-09f435ee0a1e.png)
suggests that they are all baptisms from the same church - St Helier Church (aka Town Church) https://www.jerseydeanery.je/st-helier

**Comment by SteveBiggs** [comment]
I'm afraid I cannot help with this.

**Comment by Sherlock21** [comment]
Here is the file concerned.



seems to me the 4 files in St Helier proper are similarly without a church name.

I thing the solution is for the CC to get all 5 files and correct their content.
then get Kirk to erase the two ‘Place names ‘ in Jersey.

then add the proper Placename of St Helier
and the church of whatever it really is - or use "Parish Church" if its not named

and reload the 5 files.


then will not respond to me trying Relocate nor Change Church Name 

eric B

On 27 Nov 2020, at 17:23, Stephen Biggs <notifications@github.com> wrote:


I'm afraid I cannot help with this.

**Comment by Captainkirkdawson** [comment]
@edickens 
The place Shi has no apparent files associated with it.
There are however 4661 search records associated with it
It appears they were from a file  capn-bob.CHISHZBA4.CSV.
Date of processing is not recorded however the were created with the software search record version "2016-10-31T00:00:00+00:00"
The earliest attic version has
+INFO,capn-bob@pegleg2.demon.co.uk,password,SEQUENCED,BAPTISMS
#,CCC,Robert Wilkins,JSY,CHISHZBA4.CSV,19-Oct-2009
#,CREDIT,Mike Fry,iafrica.com
#,17-Jan-2012,LDS,
JSY,SHL,,,10 Oct 1862,01 Jan 1863,Helena,,Amice,Emily,PAYN,BISSON,,Merchant,
JSY,SHL,,,31 Dec 1862,02 Jan 1863,Peter Clement,,Frederick,Rachel,HOTTON,LE RAY,,Storekeeper,Mort. Jan Enterre? Private Baptism
JSY,SHL,,,21 Dec 1862,04 Jan 1863,William Henry,,William Henry,Ellen Jane,PRESTON,FORBES,,Presser,
JSY,SHL,,,11 Dec 1862,04 Jan 1863,Anne Selina,,Sydney Mansell,Eliza Goswell,WAVELL,COWLEY,,Cabinet Maker,
JSY,SHL,,,_2 Nov 1862,04 Jan 1863,Henry William,,James,Sarah Mary,WATTS,HACKING,,Waiter,
JSY,SHL,,,26 Nov 1862,04 Jan 1863,Clara Bell,,,Jane,,LE BRUN,,,illeg.
JSY,SHL,,,31 Oct 1862,04 Jan 1863,Francis,,John,Martha,GODFREY,MINTERN,,Lamplighter,
JSY,SHL,,,26 Nov 1862,04 Jan 1863,Louisa Rose Susan,,Fredrick Joseph,Susan,BAILLEY,VAUTIER,,Mariner,
JSY,SHL,,,01 Sep 1860,04 Jan 1863,William Henry,,Fredrick Joseph,Susan,BAILLEY,VAUTIER,,Mariner,b. Charles Parish Plymouth
JSY,SHL,,,28 Nov 1862,04 Jan 1863,Isabella,,Francis,Harriet,LE BRETON,TALL,,Plasterer,Twin of Jane
JSY,SHL,,,28 Nov 1862,04 Jan 1863,Jane,,Francis,Harriet,LE BRETON,TALL,,Plasterer,Twin of Isabella
JSY,SHL,,,03 Jul 1862,04 Jan 1863,Caroline Elizabeth,,,Caroline,,MYNAHON,,,illeg.
JSY,SHL,,,15 Dec 1862,04 Jan 1863,Emily,,,Catherine,,CASHEL,,,illeg.
A more recent version in the attic had
+INFO,capn-bob@pegleg2.com,PASSWORD,SEQUENCED,BAPTISMS,Windows-1252
#,CCC,Robert Wilkins,Hampshire,CHISHZBA4.csv,19-Oct-2009
#,CREDIT,Mike Fry,iafrica.com
**#,28-Nov-2020,LDS,**
+LDS
JSY,Shl,Blank  ,"",10 Oct 1862,01 Jan 1863,Helena,"",Amice,Emily,PAYN,BISSON,"",Merchant,"","",""
JSY,Shl,Blank  ,"",31 Dec 1862,02 Jan 1863,Peter Clement,"",Frederick,Rachel,HOTTON,LE RAY,"",Storekeeper,Mort. Jan Enterre? Private Baptism,"",""
JSY,Shl,Blank  ,"",21 Dec 1862,04 Jan 1863,William Henry,"",William Henry,Ellen Jane,PRESTON,FORBES,"",Presser,"","",""
JSY,Shl,Blank  ,"",11 Dec 1862,04 Jan 1863,Anne Selina,"",Sydney Mansell,Eliza Goswell,WAVELL,COWLEY,"",Cabinet Maker,"","",""
JSY,Shl,Blank  ,"",_2 Nov 1862,04 Jan 1863,Henry William,"",James,Sarah Mary,WATTS,HACKING,"",Waiter,"","",""
JSY,Shl,Blank  ,"",26 Nov 1862,04 Jan 1863,Clara Bell,"","",Jane,"",LE BRUN,"","",illeg.,"",""
JSY,Shl,Blank  ,"",31 Oct 1862,04 Jan 1863,Francis,"",John,Martha,GODFREY,MINTERN,"",Lamplighter,"","",""
JSY,Shl,Blank  ,"",26 Nov 1862,04 Jan 1863,Louisa Rose Susan,"",Fredrick Joseph,Susan,BAILLEY,VAUTIER,"",Mariner,"","",""
JSY,Shl,Blank  ,"",01 Sep 1860,04 Jan 1863,William Henry,"",Fredrick Joseph,Susan,BAILLEY,VAUTIER,"",Mariner,b. Charles Parish Plymouth,"",""
JSY,Shl,Blank  ,"",28 Nov 1862,04 Jan 1863,Isabella,"",Francis,Harriet,LE BRETON,TALL,"",Plasterer,Twin of Jane,"",""
JSY,Shl,Blank  ,"",28 Nov 1862,04 Jan 1863,Jane,"",Francis,Harriet,LE BRETON,TALL,"",Plasterer,Twin of Isabella,"",""
JSY,Shl,Blank  ,"",03 Jul 1862,04 Jan 1863,Caroline Elizabeth,"","",Caroline,"",MYNAHON,"","",illeg.,"",""
JSY,Shl,Blank  ,"",15 Dec 1862,04 Jan 1863,Emily,"","",Catherine,"",CASHEL,"","",illeg.,"",""
JSY,Shl,Blank  ,"",08 Dec 1862,07 Jan 1863,Ellen Ramsey,"","",Ellen,"",GOULD,"","",illeg.,"",""
JSY,Shl,Blank  ,"",05 Dec 1862,08 Jan 1863,John Sohier,"",Tom Charles,Jane,LE GROS,SOHIER,"",Marchand,"","",""

Both had 4661 records

**Comment by edickens** [comment]
I have changed and moved this file to St Helier and deleted the Place Shl, which I think was intended to be St Helier.  The Lat/Long for this was in Brentwood, not in Jersey.
It is gone now.

**Comment by Captainkirkdawson** [comment]
Unfortunately all the bad search records are there as orphans. Likely by an incorrect deletion of a file.

**Comment by edickens** [comment]
I downloaded the one file against this place.  Split it as it was over 4K entries.  Uploaded it into St Helier.  Waited for that to process.  Deleted the file in SHL when looking at the batches in the register.  Waited for that to go.  Deleted the Register.  Deleted the Church,  Deleted the Place.
So I'm not sure which process did not clear the Search entries.

**Comment by Captainkirkdawson** [comment]
I have checked again and can no longer find the orphans so your clean up is complete.
Well done
