### ISSUE TITLE
Linking the website with the transcribers mail group

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#2354]
We are having a problem with someone on the trascribers' mail group who I cannot identify.  They must have been invited at some time, but their UserID is no longer on the website or the email address does not match.  They have not put their name on the Google Group.

Also, when someone leaves the website, we have not means of removing them from the transcirbers mail group.  I'm going to have a purge of the list, but it would be much better if the transcibers forum was linked to the UserIDs.  Something for the Roadmap.

**Comment by richpomfret** [comment]
To investigate - how might we do this?

**Comment by PatReynolds** [comment]
@PatReynolds to add to Roadmap for discussion

**Comment by DeniseColbert** [comment]
Added to Roadmap - closing
