### ISSUE TITLE
Improve the "Chapeau"  of the Message notification email

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2366]
Now the message is displayed the chapeau

**Comment by DeniseColbert** [comment]
@SteveBiggs could you supply the text for this?

**Comment by PatReynolds** [comment]
E0 U3 S8 C7: P18

**Comment by SteveBiggs** [comment]
I suggest:
==================
Dear Colleague:

<name>, <role> with FreeREG has requested we send you a message on the following subject: <subject>.
The message content is provided at the bottom of this email.
Please DO NOT REPLY to this email.
If you need to reply to the message, you are requested to log into the Members website freereg.org.uk 
(if not already logged in) to view the message there
On the initial landing page after the log in; select the "messages" link at top left and on the list of messages select the "Show" button for specific message identification xxxxxxxxx.
You can reply to the originator of the message by selecting the "Reply" button at the top of the message being displayed.
The following is the message content 
<message content>

The FreeREG Team

**Comment by DeniseColbert** [comment]
Ready for testing on Test3 - Eric to test if this hasn't already been tested.

**Comment by SteveBiggs** [comment]
Tested and good to go.

**Comment by Captainkirkdawson** [comment]
Just a couple of minor formatting suggestions
![message](https://user-images.githubusercontent.com/2874694/107055487-95badb00-678e-11eb-9be9-e75039d90ceb.png)

**Comment by Vino-S** [comment]
Implemented the changes.
