### ISSUE TITLE
Never see a cookie consent statement 

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2396]
No browser shows the CC for Kirk. Edge, Opera, Chrome. Possibly shown only in EU countries.

Do we need to?
Do we want to?

**Comment by DeniseColbert** [comment]
@PatReynolds to look into this

**Comment by DeniseColbert** [comment]
@PatReynolds is looking into alternatives to MM

**Comment by PatReynolds** [comment]
@Captainkirkdawson has put back in the old cookie consent which will serve outside of the EU/UK/California

**Comment by Vino-S** [comment]
To show original Cookie Consent in countries other than the EU and California, we might have to read the User's IP Address to fetch information about the country. We also need to obtain consent from Users to access their IP. I believe it's not best practice to access the User's IP address unless it's absolutely necessary.

**Comment by Vino-S** [comment]
Updated code in test3 FreeCEN.

**Comment by Captainkirkdawson** [comment]
@Vino-S works as expected; well done.

**Comment by Vino-S** [comment]
Thanks, Kirk.

**Comment by Vino-S** [comment]
Custom Cookie Consent does not seem to work with the MM advert script.
The MM adverts do not respond to Custom Cookie Consent status.

One possible solution:
We remove MM advert from non GDPR countries and display our own google advert, which will respond to our Cookie Consent.

Any other suggestions will also be useful.

**Comment by PatReynolds** [comment]
@PatReynolds to talk to MM

**Comment by PatReynolds** [comment]
Emailed John @ MM 7 July 2021

**Comment by PatReynolds** [comment]
Claim they can see it in the Philippines - have asked for screenshot.

**Comment by Captainkirkdawson** [comment]
MM may say that for Freebmd but I have never seen one
