### ISSUE TITLE
Upgrade Rails framework

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#240]

**Comment by juliancheal** [comment]
Started working on this in this branch https://github.com/FreeUKGen/MyopicVicar/tree/update_rails

Firstly I've just added a Gemnasium badge, which tells us what's outdated. Obviously Rails is, but at least we will know what security issues we currently have.

I've updated a few ups from Rails 3.x to Rails 4.x So happy to take this on.

**Comment by juliancheal** [comment]
Updated Rails to version 3.2.21 (the lat of the 3.x version) on this branch https://github.com/FreeUKGen/MyopicVicar/tree/update_rails

Nothing seems broken. I would suggest others checkout this branch make sure it all seems good, then we update the Master branch to this version.

NB. Upgrading to Rails 4.x is no as simple as changing the Rails version in the Gemfile. There are quite a lot of other changes that would need to be made. However I've done this a few times now, so it's not impossible :D
