### ISSUE TITLE
Improve presentation of Gap information for transcribers and coords

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/MyopicVicar#2409]
Much of the information is currently presented as a PDF document. We should present it as HTML (where it is easier to fix the typos!).

**Comment by AlOneill** [comment]
I've run into a problem — I cannot extract the images from the PDF — none of my usual strategies are working.

@Captainkirkdawson do you have copies of the images that you could send to me?

Failing that, is anyone able to unpick the PDF and extract the images?

**Comment by AlOneill** [comment]
What is the proper casing of GAP? — Gap, gap or GAP. The casing in the PDF text and in the accompanying screen-shots of app screens is not consistent — all three forms are used.

**Comment by edickens** [comment]
My understanding of English grammar is that Gap is the correct casing.  The reason is that it is not the initials for anything else, which would mean all capitals, and it needs emphasis as it is the key to the document, so can start with a capital letter.  Eric

**Comment by AlOneill** [comment]
@edickens I cannot fault your logic! I will take it that 'GAP' is being used for (some kind of) emphasis and deal with it appropriately.

**Comment by AlOneill** [comment]
@Captainkirkdawson if sending the images is not an option, perhaps you could upload the file to Google Drive? I notice that 'The Embargo System' is there as a .docx and I think that is what I used to create the HTML for that page.

(Don't want to be a pest, but I have the chance to do this now and am trying to seize the moment.)

**Comment by AlOneill** [comment]
@Captainkirkdawson I thought a bit more creatively and found an online tool that extracts images from a (small) PDF file — it has done a great job! Apologies for wasting your time.

**Comment by edickens** [comment]
What I do is to bring the pdf file to the screem and zoom in on the image if needed.  I then use the Windows Snip tool and save that image.  This does not give very high definition, but for inserting into Help, or email, it is sufficient.  Large images are not needed in Help pages.

**Comment by AlOneill** [comment]
@edickens the images on this page have text that should be readable and they need to include enough context from the relevant display (including breadcrumbs) so that a volunteer can know that they are viewing the correct screen. So, the images do need to be large as well as of good quality. (Ideally they should be taken from a narrower screen than full-width, but those are the images we have, at least for now.)

**Comment by edickens** [comment]
Alison.  Do you need new versions of all 14 figures?  When I look at the document, no images show, so I am not sure what should be there.  It would be easier if I could see what is there then I can make some new versions of the same image.

**Comment by AlOneill** [comment]
@edickens a fresh set of images would be great, especially if you can save them as PNG. However, I've hit a problem with Refinery which appears to have changed (in the last month or two?) the way it handles image uploads which could mean that we will need a different strategy. So, yes please, but not just yet.

**Comment by AlOneill** [comment]
@edickens I've placed all the images on the draft version of [The Gap system](https://test3.freereg.org.uk/cms/information-for-transcribers/draft-the-gap-system). The bulk of the page is a single column so that we can see the content of the images more clearly — the layout will be refined once the new images are in place.

Please see the draft of [Making images and using them in Refinery](https://test3.freereg.org.uk/cms/draft-making-images-and-using-them-in-refinery), especially the first two parts, for details of what is required of an image. Anything that is not clear, please let me know — you will be the first person to use that page!

I suggest you do just a couple of images to start with and send them to me by email. Do not worry about annotations — they can be added later — but if you do make any, please also send an unannotated copy. Many thanks.

**Comment by AlOneill** [comment]
Offer to replace images has effectively been withdrawn. Will use original images.

**Comment by PatReynolds** [comment]
Suggested text for the UnitT project definition document
"UniTT permits the transcriber to indicate that there is a gap in the original they are transcribing (for examke an obviously missing page, or one or more records that cannot be transcribed due to damage)."
The document will also need to specify what data needs to be captured (will this be a different process to actual transcription???).
We spoke in scrum about the difference between this type of Gap and the type which is simply a result of people not liking the incumbant / church warden and gettng married elsewhere (or a some other reason why b/m/d/ while following one another on a page are further appart in time than is usual for this register?

**Comment by edickens** [comment]
I can add more reasons without program changes.  This is the present list...
![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/5a0b3b71-07c3-4eed-b57c-1b5fbfc5ff89)

**Comment by SteveBiggs** [comment]
"No entries for these years" covers the case of people choosing to go
elsewhere in those years. In general, we don't know for certain why - maybe
there just weren't many people getting baptised/married/dying because it
was a small parish or maybe they didn't like the Vicar but it doesn't
really matter. The fact remains there were no entries for those years.

Steve

Stephen Biggs
FreeREG Chairman

**Comment by PatReynolds** [comment]
Hi @edickens  I am not sure what data the current process captures - other than "there is a gap of X type" - to be useful (e.g. for finding more detail than is in FreeBMD without buying a certificate) to know the precise dates that records are missing for.

**Comment by edickens** [comment]
There is just Place, Church, Register Type, year range and reason.
The ideal result ought to be to warn the researcher when they choose a set of parameters which span a Gap.  At present, if they do not get a result when they expect one, they need to look at "Records" and look at what we have transcribed, or not as the case may be.

**Comment by PatReynolds** [comment]
Issue #2501 covers enhancing the text presented to a researcher when they have not found a result.

**Comment by PatReynolds** [comment]
For discussion at next documentation meeting

**Comment by PatReynolds** [comment]
Remaining actions: 
"There are two ways of navigating to the header menu {??}. The first is via ‘Review Batches by Filename’ from your Syndicate Actions." (second paragraph of *Syndicate Coordinator actions* - needs the query resolving.

**Comment by AlOneill** [comment]
[DRAFT The Gap system](https://test3.freereg.org.uk/cms/information-for-transcribers/draft-the-gap-system) updated.

Next task: make a DRAFT copy of "Information for transcribers" and make the changes to 'Help contents by page' and the section menu.

**Comment by AlOneill** [comment]
Three pages updated:
* https://test3.freereg.org.uk/cms/information-for-transcribers/draft-the-gap-system
* https://test3.freereg.org.uk/cms/draft-information-for-transcribers
* https://test3.freereg.org.uk/cms/information-for-transcribers/draft-file-and-batch-actions

Once these updates are checked and approved, there are a dozen or so pages that will need their submenus updating — these extra steps are needed because 'The Gap system' is a completely new page (replacing a PDF).

**Comment by PatReynolds** [comment]
@edickens to review

**Comment by edickens** [comment]
Re: First link above.  Do not say "Ask Eric D" but "Ask System Administrator".  I will not be around for ever!
As a general point, it iis Years that are entered not Dates.  But we all understand that.
A thought - To prompt a transcriber to enter a Gap reason.  When a file is uploaded a warning should be given if there are gaps of more than one year and no Gap reason against the Register Type.

**Comment by edickens** [comment]
Re: Third lnik above.  The links are wrong, but the wording about Gaps is fine.

**Comment by AlOneill** [comment]
All three pages promoted to live (so all the links should now work).

Next task: update sub-menus on other pages in Transcriber Help.

**Comment by AlOneill** [comment]
All the updated pages are now sync-ready.
