### ISSUE TITLE
Check the SNDmanager email is working correctly

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2420]
Eric to list the general sources they come from - are there any that _are_ important?

E1 U1 S7 C6: P15

**Comment by edickens** [comment]
I get SNDManager emails.

**Comment by DeniseColbert** [comment]
@Vino-S to incorporate this into the bigger task across CEN & REG

**Comment by Sandra-AW** [comment]
This could be closed - the UserID is no longer in use

**Comment by jayto581** [comment]
@Vino-S 
- SNDmanager is only used if there is no active syndicate or county coordinator with a valid email address
- If we remove the userid SNDmanger from the user database,  vino will get any email referenced to SNDmanager

**Comment by DeniseColbert** [comment]
@Sandra-AW will change the details on this userid to hers

**Comment by Sandra-AW** [comment]
I have changed the userid to my details and made it active (it was inactive). I can deactivate itagain if not needed. Otherwise. this can now be closed
