### ISSUE TITLE
GTM on FreeREG broken

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2435]
David Houseman reports the It looks like GTM on FreeREG2 stopped sending data around Feb 25 2021. Page views appear to be working (I assume due to a page tag which is outside of GTM). I'm not able to load any of the events that I've created. I'm wondering if this coincided with a release around that date. Can you look into this Kirk?

**Comment by Captainkirkdawson** [comment]
Vino

David has reported that the Google analytics on REG are no longer working as of late February

Looking at the commits I see that the GTM was removed on February 23rd. .

Is there any reason why it cannot be readded?

**Comment by Captainkirkdawson** [comment]
Vino reported
It's strange, MM was going to handle GA and GTM of FreeREG. 
I will raise the issue and also contact MM about the same.

**Comment by Captainkirkdawson** [comment]
I was unaware that MM had any interest or involvement with Google analytics. We had invested significantly through David to develop and produced analytic reports

**Comment by PatReynolds** [comment]
Assigned to @PatReynolds to investigate

**Comment by Captainkirkdawson** [comment]
@PatReynolds I thought that @Vino-S had worked with MM to fix

**Comment by PatReynolds** [comment]
Hi @Captainkirkdawson - fixed,  just needs testing. @dhousman are you able to test, please?

**Comment by PatReynolds** [comment]
@DeniseColbert to give @Vino-S access to the analytics account.

**Comment by Vino-S** [comment]
Analytics: up and running
