### ISSUE TITLE
FreeREG Analytics

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/MyopicVicar#2437]
@dhousman has reported that the REG Google analytics is no longer working from late February.

**Comment by Vino-S** [comment]
Sent mail to MM: 25/May/2021

**Comment by Captainkirkdawson** [comment]
This is same story as 2435 GTM on FreeREG Broken

**Comment by Vino-S** [comment]
Thanks, Kirk. 
Duplicate. Closing it
