### ISSUE TITLE
Place name searches are using the county indexes rather than  the place indexes

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2444]

**Comment by Captainkirkdawson** [comment]
Selection code updated and deployed to test3

**Comment by Sherlock21** [comment]
I tried a test in T3 for search on a surname SANDERCOCK across England as in image 1.
it ran OK and returned 259 images - most in Cornwall as expected plus a few in Jersey & 1 in Devon. Fine.
But look at image 2: the county for this record is missing.
is that the same snag as you found, Kirk? of a different one.
eric

<img width="1490" alt="Screenshot 2021-06-06 at 14 22 47" src="https://user-images.githubusercontent.com/9368704/120926334-51a3fc80-c6d4-11eb-8496-ebebd21ea806.png">
<img width="1043" alt="Screenshot 2021-06-06 at 14 22 14" src="https://user-images.githubusercontent.com/9368704/120926340-55378380-c6d4-11eb-87cd-ea482389f0f9.png">
