### ISSUE TITLE
Wildcard on surname with a forename does not work.

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2445]
I do not know if this is a new problem but I find that the addition of a forename in a wildcard card search produces no matches.
![cranniss.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/8d2c2708-d62f-4a0e-8cec-1124ef327815)
![mary cranniss.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/3c84fcef-a64f-4741-9a1f-b0f4c73fb13f)
![wildcard help.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/0b9268fc-d5ed-4e76-9098-af6b018f4a19)

**Comment by PatReynolds** [comment]
Search ![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/20453dd6-b96c-450b-a1d0-6aae7ac1b610)

Arthur Eames, Baptism Redbourn, Herts 1870-1990 finds a record, with Arthur Ea* it doesn't.

**Comment by Captainkirkdawson** [comment]
Issue found and fixed on test3
![cranniss.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/66d55ef4-b8af-4cd9-b6e0-508ee798eaa6)

**Comment by Captainkirkdawson** [comment]
Deployed to production
