### ISSUE TITLE
T3 testing

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#2446]
<img width="1572" alt="Screenshot 2021-06-06 at 14 46 57" src="https://user-images.githubusercontent.com/9368704/120927171-d3495980-c6d7-11eb-957b-a617b314a45a.png">

looking at My Batches, there are many of my files that carry the strange "Reg" comment: file does not appear to belong to Register.

**Comment by Sherlock21** [comment]
Further testing of a couple of contents of file WRYSEDTSTBU series suggests to be these are not my files - so the issue is really: why do they get listed under My Batches?

**Comment by Sherlock21** [comment]
I am just wondering:
As the fie name suggests the file is a TEST file ( from the TST in the file name), has it been removed but is leaving remnants that cause a partial appearance in this test SEARCH?

**Comment by Captainkirkdawson** [comment]
@Sherlock21 The message is a new one that indicates that the file in question is no longer correctly linked. Somehow or other the file during some form of processing has become detached. How or why I do not know; perhaps in a gateway timeout. In the past it would have shown the register name from the file. Now it looks it up. Hence we now know this file is damaged.
There are occasions when this will be seen in production where it is clearly more important.
