### ISSUE TITLE
Help page — improve source order and visual alignment

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/MyopicVicar#2453]
The "Want to know more about Soundex?" box is not in the best place — it would be better a bit further down in the sidebar, visually opposite the "Soundex" heading as well as immediately after that section in the source order.

This would entail simplifying some of the markup, and would have the added bonus of making the layout more difficult to break for much of the page, which seems like a Good Thing.

The changes will be easy to do in a proper text editor.

--------------------------------- 

I would also like to move the "If you still have questions" box, with its link to our FAQ page, to the foot of the sidebar. It seems wrong to offer that link so early on in the page — a screen-reader user hears that and a mobile phone user sees it immediately after the lead (opening) paragraph, i.e. before the page content has even got going.

Perhaps the text of "If you still have questions" should be modified to explain how or why the FAQ might be more appropriate or helpful?? Then discuss placement??

**Comment by PatReynolds** [comment]
That sounds excellent, @AlOneill.  

I agree 'if you still have questions' box should be tied to the bottom.  

For text, how about replacing the words "Frequently Asked Questions" with "detailed explanations of the less-used and more specialised features of FreeBMD"???

**Comment by AlOneill** [comment]
@PatReynolds TY. Not really feeling your suggested re-wording. Will think on.

[Draft Help]("https://test3.freereg.org.uk/cms/help-draft") page created. Soundex box and 'If you still have questions' box moved. Also simplified layout and replaced invalid use of `<q>` element with actual curly quotes.

Am now wondering where the Cookie notice notice and 'Supported browsers' notice should be placed, in the source order and visually.

**Comment by PatReynolds** [comment]
@PatReynolds suggested putting these at the bottom of the page.

**Comment by AlOneill** [comment]
Cookie notice notice and Supported browsers notice moved into their own section at the foot of the page, together with the FAQ notice.

Ready for Review.

**Comment by PatReynolds** [comment]
@PatReynolds to review

**Comment by PatReynolds** [comment]
Thanks, @AlOneill that is fine.

I spotted other things .... 

 -[ ] Stray ">>" at the end of this link: "Association of British Counties (link opens in a new tab)"
 - [ ] Maybe change "Also available is a link to the list of Unique Names for the Church records." to "Also available is a link to the list of Unique Names for that church" (to mirror what is said about register records????
 - [ ]  Wondering whether Soundex might be better immediately following Unique Names, as is gives good examples of why Unique names is so important.

**Comment by AlOneill** [comment]
The double chevrons were not exactly 'stray' — they were the result of trying to find a (naive) solution to how to warn a user that they will be taken to another site. A very old attempt. Class now removed.

I'll think about Unique Names some more. The whole idea needs a better explanation. Soundex and wildcards also go together. Will think on.

**Comment by PatReynolds** [comment]
Thanks, @AlOneill I will put this back into in progress

**Comment by AlOneill** [comment]
Perhaps this is just me, but the idea of "Unique" names as we are using it seems like a bizarre use of the word unique. The dictionary says that unique means, "being the only one of its kind; unlike anything else". We are using it to describe a listing of all the names (and spellings of that name) that occur at least once in a Place, Church, or Register.

What would be a better term to use here? It would have to fit on a button, so would "All name variations" or "All names used" work? (It has to fit on a button.)

**Comment by PatReynolds** [comment]
"Name variations"? "Names used in this Parish" "Names used in this Register"??   I have asked Twitter ....

**Comment by AlOneill** [comment]
Would "Names used here" be obscure? It would have the merit of being the same term everywhere (easier to set up), but would lose the clarity gained by being more specific.

I'll be very interested to see what the Twitter and Facebook users suggest.

**Comment by PatReynolds** [comment]
Twitter suggests "Index of names" or "Complete list of names" - List is better than Index, to my mind because it isn't an index (you can't click on "Jane" and see all the Janes in the register, and there is no other way, other than running a search for Jane to find them.

**Comment by PatReynolds** [comment]
I agree - looks good!
