### ISSUE TITLE
Ask a Question Syndicate

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#2476]
Is this syndicate really necessary now that we have Contact Us and these messages get answered.  We have just had someone register in order to ask a question when perhaps the Contact Us would be better.  However, if this is the standard in the other projects then we can leave it.  If is is not needed, I can get rid of it.
Or is the Contact Us not very visible.  It is small text.  But it is the norm now for there to be a Contact Us in the footer so people should find it.

**Comment by SteveBiggs** [comment]
My vote is to remove it.

**Comment by PatReynolds** [comment]
@edickens to remove this syndicate, as no longer needed

**Comment by edickens** [comment]
I have set to Inactive and moved to Waiting for deletion all four UserIDs in this syndicate.  I have also set the Syndicate to Not recruiting so it should not appear when someone registers.  There is no Syndicate Delete but that is not needed.
So this is finished and can be closed.
