### ISSUE TITLE
Issues with Citations

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2501]
Yesterday citations were working fine.

Today on my home pc (slightly older version of Chrome?) select 'generate citations'  is there, but when the Wikitree option is clicked, the page redisplays, but not with the citation (or the option to choose citation.

On my work laptop (slightly newer version of Chrome?) the 'generate citations' option does not appear.

![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/0bb88774-731e-457f-82db-e975feb15b94)

**Comment by Irene-ene** [comment]
@PatReynolds to check if this happens again

**Comment by PatReynolds** [comment]
No longer happening.
