### ISSUE TITLE
Implement No Results Found page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2504]
Text is at https://docs.google.com/document/d/1n58RWUVyqGe1pBf6YC7KAFkAdKE90m4hFJ60vBkWmZs/edit#heading=h.qh3iybvrhawt

**Comment by SteveBiggs** [comment]
New text looks fine to me.

**Comment by edickens** [comment]
No.  The text refers to "Transcripton pages".  This is now the "Records" buttton which they can find at the top of the screen.  Text needs correction.
But the rest is much better.

**Comment by PatReynolds** [comment]
Eric, the new text is on the right, and mentions "the Records section", not "Transcription pages" .

The idea of a navigation hint to the section is good.  (we should use the same wording whenever we direct people to the navigation bar - I'm not sure where else we might do that at the moment).

**Comment by edickens** [comment]
My mistake.  I wasn't looking at Test2.

**Comment by Captainkirkdawson** [comment]
Deployed to test3
