### ISSUE TITLE
A question mark is a valid character for the sex field in baptisms but the transcriber help does not include it

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2510]
Transcriber Help for the baptism field of 'sex' needs updating to include a '?' since this is what is provided on the drop-down list when doing online editing.

**Comment by PatReynolds** [comment]
@PatReynolds to look at in documentation meeting.

**Comment by AlOneill** [comment]
@SteveBiggs Are we saying a ? by itself is valid, or a word with a ? appended?

The latter looks to match the current info on UCF, but not the former. I know of no other field that accepts a ? by itself — but I could easily be wrong.

"Sometimes you will be able to read all of the characters but remain uncertain of the word. In this case type a ? at the end of the word, e.g. RACHARD? However, the most frequent use of the ? is with transcripts that have been donated to us and then converted for entry into FreeREG."

**Comment by SteveBiggs** [comment]
@AlOneill a ? by itself is valid:

![image](https://user-images.githubusercontent.com/25303607/152353272-e6926d2f-84c9-4270-af5d-0aee2135e662.png)

**Comment by AlOneill** [comment]
@SteveBiggs thanks. Now to establish how it can be used.

The current guidance says:
'A single character from f, F, m, or M; or "-" (a hyphen) if found in a transcript'

I suggest that this is edited to say:
'A single character from f, F, m, or M; or **if found in a transcript**, "-" (a hyphen) or "?" (a question mark)'

Does this work for you? There does not appear to be any other reason for using a only a question mark in this field.

**Comment by AlOneill** [comment]
@SteveBiggs  To use a ? to stand for unreadable (rather than a literal transcription of a transcript entry) would be a departure from our usual practice of using an \* (asterisk), yes? Seems wrong. 'M?' or 'F?' would be in line with the UCF instructions as I understand them, but not a ? by itself.

If there is no entry, the instructions for entering data say to leave blank.

I wonder … has a ? always been in the drop-down? If not, when and why was it added?

**Comment by AlOneill** [comment]
I've noticed some confusion over who exactly should be entered as a witness to a marriage and have created a new issue — #2541.

It would be good to clear that up at the same time, if possible.

**Comment by SteveBiggs** [comment]
@AlOneill AFAIK, an asterisk, M? and F? are all not accepted by the sex field. I believe that even if a hyphen is put in the transcription file, it gets converted to a ? when the file is uploaded because only m, M, f, F, ? or blank are allowable.

Your correct that if there is no entry, it should be left blank, but if there is something there but it's unreadable, strictly we should put a UCF entry and the only one allowable in the sex field is a ?

The ? has been in the drop-down menu for as long as I can remember (but at my age, that's not very long!)

**Comment by AlOneill** [comment]
@SteveBiggs thanks. This is now my suggestion:

![baptism-h-requirements.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/ccfdc304-c5f9-4916-9ac8-b617e7694b2b)

**Comment by SteveBiggs** [comment]
Looks good to me.

**Comment by AlOneill** [comment]
@SteveBiggs thanks.

I've now had a look at the person_sex field in Extended baptisms. The current field instructions are:

![person_sex-extended-bap.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/e96f1e7d-fd7e-4917-b93c-0aaeac34b6fa) 

The instructions are different from standard entry. I cannot say whether they were edited for Extended baptisms or if the directions regarding hyphens were not added (either in error or on purpose). Are you able to check the contents of the person_sex drop-down to determine whether or not a ? is valid here too?

**Comment by SteveBiggs** [comment]
@AlOneill it has exactly the same constraints so should have the same help text.

**Comment by SteveBiggs** [comment]
Looks good.
