### ISSUE TITLE
Donate request on search/detailed results should appear directly below the table

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2511]
The ad seems to be interrupting the table and the donate request:

![image](https://user-images.githubusercontent.com/19173257/142629793-b86d73e6-f718-4e97-ba96-95bfa78ce3ed.png)

E4 U3 S6 C?

**Comment by Vino-S** [comment]
Thanks @AlOneill for reminding me.
I have updated the CSS. Ready for testing in test3.
Apologies for delay.

**Comment by PatReynolds** [comment]
Tested and ready for deployment.

**Comment by AlOneill** [comment]
@Vino-S @PatReynolds I see the donate button but with legacy colours — the new version should be teal.

**Comment by AlOneill** [comment]
@Vino-S @PatReynolds I'm now seeing the icon with the revised teal colours, so all is well!
