### ISSUE TITLE
Site Statistics - CSV download facility

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2513]
Yearly download would be ideal.

**Comment by PatReynolds** [comment]
E3 U6 S7 C6: P21

**Comment by Captainkirkdawson** [comment]
Code added to test3 for evaluation.
Go to site statistics on REG test3
![download selection.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/32743e4c-b33c-4dd4-bcee-657900778879)
Select the![download.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/33411188-0295-4775-9428-1e4d952b5d2b) show download button which asks you to select the date range then select download.
Confirm you want to proceed. File downloads  as csv

**Comment by PatReynolds** [comment]
Download works finek, but as in your snip, the tool is not recording users or records uploaded.

![image](https://user-images.githubusercontent.com/6338822/145551335-8433085a-f81a-4208-a2a0-bfd80a7b67e3.png)

**Comment by SteveBiggs** [comment]
@PatReynolds I assume that will be because no one is searching or uploading to test3.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs is correct there is little activity on test3 but by loading into excel and filtering we can see a day when there was an upload and search
![Screenshot 2021-12-10 085511](https://user-images.githubusercontent.com/2874694/145603063-b29c2201-9ba9-4d03-bbb0-1692c52c6f7b.png)
