### ISSUE TITLE
Entering only a month and year (with no day) results in the system assuming the day is the start of the month

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2514]
In the case of there being a birth date of say, 5 Jun 1853 and a baptism date just stating Jun 1853 (no day given), the system reports an error that the baptism is before the birth so it must be assuming a day at the start of the month. If not stated, it should not assume any specific day, but could be any day in the month.

**Comment by PatReynolds** [comment]
Decided that the effort in making the system accept this situation is great, and implimenting it would probably cause other problems, therefore the solution applied here: record date of birth, put only the year into the baptism date, and put the date of baptism 'as is' full transcription into the notes.

**Comment by SteveBiggs** [comment]
I've sent an explaining email to the transcriber.

**Comment by AlOneill** [comment]
@SteveBiggs Do we want to update the Help, with the fix for a similar error message? There are a number of possible real situations so it seems sensible to describe the fix as a response to the error message. Or perhaps we do not want to go there at all, because the circumstances occur only rarely? (I hope that makes sense!)

**Comment by SteveBiggs** [comment]
@AlOneill perhaps update the UCF section to say that when no day is included in a date (just the month and year), the day defaults to the 1st of the month.

**Comment by AlOneill** [comment]
@SteveBiggs Good thinking. Have updated "Entering data …" and "Flexible CSV".

**Comment by PatReynolds** [comment]
@AlOneill is this now in live or still on test3 (needing checking?)

**Comment by AlOneill** [comment]
@PatReynolds this is now on live. Closing.
