### ISSUE TITLE
Typo in "Too many search results" text — census years!

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/MyopicVicar#2522]
Where there are too many search results, the 2nd para starts with:

"You can also limit the number of **census years** that are searched." [bold text mine mine].

Should it be "range of years"?

**Comment by Captainkirkdawson** [comment]
@AlOneill Fixed
![toomany.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/5439c030-4029-4a17-9c24-8e7c066f46dd)

**Comment by AlOneill** [comment]
Thank you @Captainkirkdawson. I had forgotten that a date range could be counter-productive.

Fix confirmed, so closing.
