### ISSUE TITLE
Consider adding a 'tips for transcribers' section to help

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2540]
For resources, etc. found by transcribers - esp shared by transcribers in a group.

**Comment by Captainkirkdawson** [comment]
Is this in the General help or the Transcriber help?

**Comment by PatReynolds** [comment]
In the Transcriber help.

**Comment by edickens** [comment]
Request for tips sent to the Transcribers Group

**Comment by DeniseColbert** [comment]
Tips placed in a GDoc: https://docs.google.com/document/d/11vtn5ZExQKx8dO6Ged8fCK2JLXY5ggiBVjkxfbq9kBk/edit?usp=sharing

**Comment by PatReynolds** [comment]
Will need a general section for things which don't fit into an existing section

**Comment by PatReynolds** [comment]
Perhaps we could look at using the "quotes" design used on Your Reviews for some of the tips to break up the page and capture the chatty style of some of the contributions?

**Comment by AlOneill** [comment]
Maybe. Ideally, would need to know the author of each tip.

**Comment by AlOneill** [comment]
I propose to add a section entitled 'Tips from fellow transcribers' to 'Information for transcribers'. It will have:

* the full text of tips that do not fit anywhere else 
* links to sections of existing pages that already have the suggested tip or that already have related tips and information — any new tips will be added to those sections

@DeniseColbert Before I begin, are there any more tips now waiting to be added to the document on GoogleDocs?

**Comment by DeniseColbert** [comment]
@AlOneill no more tips have come in, please go ahead.

**Comment by PatReynolds** [comment]
@DeniseColbert  @SteveBiggs  and @edickens  to take a look.

**Comment by edickens** [comment]
Fine by me.  Thanks, Eric

**Comment by AlOneill** [comment]
@DeniseColbert @SteveBiggs @edickens 
Thanks for looking, Eric. However, both issues on [DRAFT Info for transcribers](https://test3.freereg.org.uk/cms/information-for-transcribers/draft-information-for-transcribers) remain unanswered. Can any of you help to resolve them?

**Comment by SteveBiggs** [comment]
I believe that auto-correct for hyphenated first names is done in FreeREG processing but @Vino-S will have to confirm that.

I don't consider the clergy database to be of any use for FreeREG transcribing but is probably of personal interest to some transcribers.

**Comment by AlOneill** [comment]
Thank you @SteveBiggs that is my instinct. However, I'll wait for confirmation before updating the Help.

**Comment by AlOneill** [comment]
@Vino-S, can you confirm our impression that FreeREG processing converts a forename such as "Mary-Ann" (with a hyphen) to "Mary-ann"? Thanks.

**Comment by DeniseColbert** [comment]
@Vino-S see Alison's comment above

**Comment by AlOneill** [comment]
Info for transcribers and appropriate sub-pages are now sync-ready.

**Comment by DeniseColbert** [comment]
@AlOneill is eveything ok with the page now it's been deployed?

**Comment by AlOneill** [comment]
@DeniseColbert A quick look through the three updated pages — Info for transcribers, Latin words to recognise and Dealing with uncertainty — suggests all is as expected. So if you are happy with the outcome, this story can be closed.

**Comment by DeniseColbert** [comment]
OK, closing
