### ISSUE TITLE
Resolve inconsistencies re entry of name of officiating minister (and others) for a marriage

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/MyopicVicar#2541]
Entering data from registers, General guidance, Witnesses  (which is not present in Flexible CSV, General guidance), is not clear in its intent and is seemingly at odds with guidance for the Notes fields (standard and Flexible CSV).

The new-ish guidance under Witnesses is:
![general-guidance-witnesses.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/ce216c26-8b24-4042-b5fc-fbcf1f64db2d)

I am not sure what the fundamental message of this paragraph is (I did not add it).

In the guidance for the **Notes field** (standard and Flexible CSV) we have:
![notes-guidance.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/1fbfc7a5-941a-4e53-8dc9-ab7aea7cc778)

Do we want transcribers to include the name of the officiating minister as a Witness? (I believe that this has been discouraged in the past.)
What about the names of 'local Gentry' and similar probably-not-relatives?

**Comment by SteveBiggs** [comment]
We want all witnesses listed in the register entry recorded in the Witness field(s) no matter who they are.

The guidance about not including the officiating minister is when he/she is simply listed as the minister, not when they are a witness.

**Comment by AlOneill** [comment]
So, the Notes guidance can remain unchanged.

I do not think that "the Vicar" is allowed to be a Witness to a marriage in their own church — at least under current C of E rules. Being a relative is not required for a Witness — so what exactly are we trying to say? 

My first draft of a replacement for the Witnesses section (on the standard entering data page) is:
"We record everything that is in the register, including the names of everyone described as a witness. If you are transcribing Baptisms that include witnesses, then please use a spreadsheet with Flexible CSV which has fields for the names of up to eight witnesses to a baptism. Similarly, Flexible CSV has fields for up to eight witnesses to a marriage rather than the standard two."

I have ignored the final sentence, pending a clearer expression of the original point.

**Comment by SteveBiggs** [comment]
I don't know whether the Vicar can be a witness and I didn't write that help section, but your help new text looks fine to me.

**Comment by AlOneill** [comment]
[Entering data from registers](https://test3.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers) and [Flexible CSV format](https://test3.freereg.org.uk/cms/information-for-transcribers/flexible-csv-format) updated with appropriate text re witnesses.

Pages are sync-ready.

**Comment by SteveBiggs** [comment]
Looks good.
