### ISSUE TITLE
Investigate why STSBURMI.csv stalls the processor

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2544]

**Comment by SteveBiggs** [comment]
The original file as uploaded contained 764 records. After the file stalled, the file @Captainkirkdawson sent me to check had only 173 records. The last one of those 173 appears to have caused the processor to stall and the rest of the records were then 'lost'. The cause appears to have been that a UCF date of death was written as 'Jun 18_'. When I added a second underscore 'Jun 18__', the file processed correctly.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs correct analysis. Fixed

**Comment by SteveBiggs** [comment]
Thanks @Captainkirkdawson
