### ISSUE TITLE
Contact Us - Thank you

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2551]
Now the 'Your reviews' page is complete, we need to connect it to the user journey.

- [ ] Remove the 'Thank you' option from the drop-down menu in the contact form
- [x] Add text to the top of the 'Contact Us' form TBD by the Documentation team
- [x] Add the box with the 'Your reviews' link on the About page, to the FAQs page (same place)

**Comment by DeniseColbert** [comment]
Suggested text: would you like to thank the volunteers who have made FreeREG possible? Please [leave us a review]. [link to Your reviews page]

To be placed here:

![image](https://user-images.githubusercontent.com/19173257/156577105-7c8b824e-3628-4d01-9f53-b8139dbd54d9.png)

**Comment by DeniseColbert** [comment]
@AlOneill does this text seem ok?

**Comment by AlOneill** [comment]
Looks reasonable, as long as the first word is "Would" rather than "would" :-)

**Comment by DeniseColbert** [comment]
Fixed, thanks :)

**Comment by DeniseColbert** [comment]
Hi @Vino-S could you (or one of the tech volunteers you're working with) implement please?

**Comment by DeniseColbert** [comment]
@AlOneill will add the sentence from Contact form re. leaving a review in an island/islet at top of FAQ page.

**Comment by AlOneill** [comment]
Done — [Frequently asked questions (researchers)](https://test3.freereg.org.uk/cms/help/frequently-asked-questions-researchers) now has a link to "Your reviews" at the top of the page.

It is sync-ready.

**Comment by DeniseColbert** [comment]
@Vino-S to close after running another sync
