### ISSUE TITLE
Transcriber Statistics

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/MyopicVicar#2556]
- Added stats for unallocated Image groups.
- Added feature to get stats of transcriber registrations every 3,12, 36 and 60 months.
- Added feature to get stats of active transcribers for 3,12, 36 and 60 months.

**Comment by Vino-S** [comment]
Ready for testing in test3. But code needs to be deployed live for actual testing

**Comment by edickens** [comment]
Hi Vino,
Thanks.
The image group statistic doesn't really come under UserIDs.  It is a general Site Statistic.
I like the idea of Variable Statistics.  I assume that this means that the statistic is only calculated on request and not every time this screen is opened.  The Image Group could be the same.  Show as zero until Update is requested when the calculation is made.
This can go live.
Eric

**Comment by DeniseColbert** [comment]
I can't see where to test this in Test3; maybe I don't have the Action button?

**Comment by DeniseColbert** [comment]
I now have access (thanks Kirk:) however, the variable stats don't appear to work for me:

https://user-images.githubusercontent.com/19173257/156556535-a3b1e8bb-da3d-44a9-92fa-eeea91444153.mp4

**Comment by edickens** [comment]
As said a few days ago, this is ready to go live.  Please do this.  TY  Eric

**Comment by Vino-S** [comment]
Deployed to production
