### ISSUE TITLE
County additions report

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2566]
On FreeCEN, we have a feature that enables us to download a CSV of additions to the database by county. The Comms Team are now able to tweet (tagging County Records Offices and Archives etc.) and it would be good to do the same for FreeREG. Could this code be implemented on FreeREG?

https://www.freecen.org.uk/freecen2_site_statistics?locale=en

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/a8ec34b5-999f-4054-bf45-f6ded0b0eac5)

**Comment by PatReynolds** [comment]
@PatReynolds to ask @Vino-S how difficult to re-purpose FreeCEN code for FreeREG

**Comment by PatReynolds** [comment]
@DeniseColbert to send a copy of the FreeCEN spreadsheet

**Comment by DeniseColbert** [comment]
@Vino-S to implement

**Comment by DeniseColbert** [comment]
Coords and above

**Comment by DeniseColbert** [comment]
Looks good on test 3 but I'll test properly when deployed

**Comment by DeniseColbert** [comment]
@Vino-S I tagged you in a comment on the report for July that shows zero records added for all counties/events:

![image](https://github.com/FreeUKGen/MyopicVicar/assets/19173257/4c376cb4-742c-4f7e-8df8-9937de31711a)

**Comment by Vino-S** [comment]
@DeniseColbert to test in production after couple of days

**Comment by DeniseColbert** [comment]
Working from 6th Nov

**Comment by DeniseColbert** [comment]
Done: closing
