### ISSUE TITLE
Protect server from upload of malicious files attached to a problem report

### ISSUE THREAD

**Issue by graphiclunarkid** [FreeUKGen/MyopicVicar#257]
As a systems administrator I want the types of files that can be uploaded to the server via a problem report to be restricted so that the threat posed by malicious files is mitigated

ACCEPTANCE CRITERIA

- I can upload an image file (GIF, JPEG or PNG)
- I can upload a CSV file
- I cannot upload any other type of file

Consider during implementation:

- set noexec flag on file system used to store these files
- check directory and file permissions

**Comment by Captainkirkdawson** [comment]
Have put in checks so that only image extensions can be loaded

**Comment by juliancheal** [comment]
Have we considered storing the files on something like S3/Rackspace Cloud files?

It's cheap, and this way we're not storing data on servers that might get reinstalled/crash/etc.

**Comment by Captainkirkdawson** [comment]
Have also added check on csv file upload
