### ISSUE TITLE
Problems with "Support our Free UK Genealogy volunteers" overlay

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/MyopicVicar#2585]
Issues discovered so far — there could be more. Please add any that you find.

The links, 'Remind me later' and 'Close' cannot be activated with the enter key.

The page underneath the overlay is still active — the links and form inputs can be reached by keyboard, even if they cannot be seen.

**Comment by PatReynolds** [comment]
@DeniseColbert to test: keyboard only users should (at least) be able to close the pop-up)

**Comment by DeniseColbert** [comment]
Fixed- closing
