### ISSUE TITLE
Possible location error

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2597]
Looking at #1473 on Find My Past (to check there was no baptism date in a record, only a birth date, I note that FMP has the church as St Margaret's (Norwich, Norfolk). I.e. https://www.genuki.org.uk/big/eng/NFK/norwich/StMargaretsChapel  

We have it as St Mary Baptist

**Comment by SteveBiggs** [comment]
I'll pass this to the Norfolk coord to check.

**Comment by SteveBiggs** [comment]
I sent this to Julie Harold, Norfolk on 11th Aug. No response yet so will chase her.

**Comment by SteveBiggs** [comment]
Julie has confirmed that St Mary is the correct church.
