### ISSUE TITLE
Sidebars below My Heritage ad is too far down the page

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2603]
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/692a4042-1927-49f3-b87a-3ebb246a0e13)

https://www.freereg.org.uk/cms/about

**Comment by DeniseColbert** [comment]
@Vino-S we think the ad should be the bottom-most of all sidebar blocks?

**Comment by AlOneill** [comment]
@DeniseColbert @Vino-S 
I'm pretty sure that I was asked to place "More about FreeREG" and the content below it at the bottom of the sidebar. So nothing has moved or been moved by the Ad.

**Comment by DeniseColbert** [comment]
@PatReynoldsFUG is this the way we wanted it?

**Comment by DeniseColbert** [comment]
Scrum thinks this should be further up the page.

**Comment by AlOneill** [comment]
Sorry, Scrum, but "further up the page" is rather imprecise — I do not know how to interpret it. There are two things to consider here: the visual placement and its position in the source order which determines when a mobile user or a screen reader user will see or hear it. After what? Before what? Thank you!

**Comment by DeniseColbert** [comment]
Sorry Alison; directly below the My Heritage ad, visually. In the source order, I think it should come after the text in the body or after the sidebar links, whichever is best for keyboard-only users.

**Comment by AlOneill** [comment]
For sighted keyboard-only users there needs to be a correlation between what a user sees (at all screen widths) and the tabbing order (i.e. the source order).  A screen reader user has ways of making sense of the page other than by hearing it in strict source order — only a raw beginner would attempt to take in the whole page in source order. It sounds as if you want the page put back to how it started. Fair enough. That is what I'll do. I'll post here when it is done — the current page has to be unravelled, as it were.

**Comment by AlOneill** [comment]
The sidebar content below the My Heritage ad has been moved as per the Scrum's request of 5 days ago. In other words it has been **optimised for sighted keyboard-only users rather than for screen reader users**. This seems the best solution for the reasons given 4 days ago.

It is placed as best as I can do for the current page contents but will need review if and when the content of either column changes including changes to the height of the My Heritage advert.

**Comment by DeniseColbert** [comment]
Thanks @AlOneill  ready to go live now

**Comment by DeniseColbert** [comment]
I think this is deployed, reopen if not
