### ISSUE TITLE
Limitation in age at death in burial entry when over 100 years old

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2605]
This has come up before but I can't remember the outcome. Up to age 99, you can enter 99y or 99y6m, etc. but from 100 onwards, FreeREG only accepts numbers. E.g. 100y fails as does 100y6m, etc. Some transcribers make a habit of always including the 'y' (although they don't need to) so wonder why 100y fails.

**Comment by suffolkroots** [comment]
Another--- "person_age"=>"103y6m", 

This is not an error and should not need correcting.

**Comment by suffolkroots** [comment]
It surely should be important for the integrity of our data, that any record which is correct should be searchable?

eg  "person_age"=>"103y6m",

This is correct and should be searchable.

**Comment by SteveBiggs** [comment]
@suffolkroots Age is not a searchable field. This issue is about making it possible to enter 103y6m when transcribing an entry.

**Comment by suffolkroots** [comment]
@SteveBiggs this record was not searchable as the age was marked as an error. In order to make it searchable I amended the age and added a note. As the age was not wrong in the first place, this should not be necessary.

**Comment by SteveBiggs** [comment]
Ali, I'm agreeing with you. The error prevented the entry from being processed into the database so would not be there to be found in a search. That's why I raised this story and when it's fixed, FreeREG will accept age records above 100 in the same format as those below 100.

**Comment by DeniseColbert** [comment]
@Vino-S needs to do some more tests to identify the scale of this issue

**Comment by SteveBiggs** [comment]
Tested and working in test3

**Comment by AlOneill** [comment]
We also need to check that the documentation is correct for recording the age at death in: "Entering data from registers" and the flexible (extended) burial fields.

**Comment by Vino-S** [comment]
Code deployed to production

**Comment by DeniseColbert** [comment]
Done: closing
