### ISSUE TITLE
Destroy Contact is now Archive Contact - Help Update

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2610]
The Help needs updating on page: https://www.freereg.org.uk/cms/information-for-coordinators/coordinator-actions

'Destroy' should now read 'Archive':

![image.png](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/b794edab-7c34-42d6-90f2-d044fa889408)

**Comment by AlOneill** [comment]
@SteveBiggs 
This page has not been updated in a loooong time and I can see that it is in need of ARIA attributes and maybe some other enhancements — will do thorough checks off-line as well as changing that single word (!)

Is there anything else that could do with a spruce up here?

**Comment by SteveBiggs** [comment]
I'll take a look.

**Comment by AlOneill** [comment]
@SteveBiggs 
Technical editing complete — changes listed at top of page. 
Page returned to REG t3 as [DRAFT Coordinator actions](https://test3.freereg.org.uk/cms/information-for-coordinators/draft-coordinator-actions)

**Comment by SteveBiggs** [comment]
@AlOneill A few more changes are needed:

1. In this paragraph:
![image](https://user-images.githubusercontent.com/25303607/198902836-b5ae6a14-077c-4d8c-b290-5ce20891e980.png)
Please replace 'SH' with 'Show'

2. Replace this wording:
![image](https://user-images.githubusercontent.com/25303607/198902895-bb74f498-9e8a-4920-bb91-6384f744684e.png)
with:
"Next reply to the researcher using the Create Reply button within the Contact, so that the Data Managers know that you are dealing with the problem. Explain to the researcher what you have done and why.

The final step is to use the Archive button to move the Contact from the Active list to the Archive list. This is important as it allows the System Administrators to know that the issue has been dealt with."

**Comment by AlOneill** [comment]
@SteveBiggs 
Thanks. Done.

**Comment by SteveBiggs** [comment]
Looks good, thx.

**Comment by DeniseColbert** [comment]
@AlOneill could you make this sync-ready and move into Ready for User Testing with the Ready label?
