### ISSUE TITLE
Spouse data missing from results

### ISSUE THREAD

**Issue by PatReynoldsFUG** [FreeUKGen/MyopicVicar#2614]
I tried a search for Emma BALL, Northamptonshire, Kettering (no other restrictions) and got some results.  Grooms names are missing from resultsl.

**Comment by SteveBiggs** [comment]
I made the same search and it returned just one result which did have a Groom listed:
![image](https://user-images.githubusercontent.com/25303607/202467291-b78e21fb-4024-49ea-a292-d1022022a653.png)

**Comment by SteveBiggs** [comment]
I made another search without specifying a record type which is exactly what Pat did and returned the same result:
![image.png](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/417b1814-ed74-408c-8f74-5664080a662b)

I suggest this can be closed.
