### ISSUE TITLE
Redirect Genealogical question Contacts to Ali Hill

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2615]
Ali is taking over dealing with Genealogical question Contacts from Eric so they need to be sent to her email address which is ali.hill.wry@gmail.com

**Comment by DeniseColbert** [comment]
Genealogy Coordinator role to be assigned as secondary role for Ali Hill and Genealogical questions from Contact Us to go to this role

**Comment by SteveBiggs** [comment]
I believe this has been completed. @Vino-S to confirm.

**Comment by DeniseColbert** [comment]
Done closing
