### ISSUE TITLE
Add Transcriber Statistics action to Commscoord actions

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2616]
So that Sandra as Commscoord can create the monthly coordinator's newsletters she needs access to the Transcriber Statistics action button under the Display UserIDs action that she already has.

**Comment by DeniseColbert** [comment]
@Vino-S to make live so Sandra can test

**Comment by DeniseColbert** [comment]
@CommsCoord to test on live website (Can you see Transcriber Staistics in Your Actions?)

**Comment by DeniseColbert** [comment]
@SteveBiggs to test in Sandra's absence

**Comment by SteveBiggs** [comment]
The action is still not there. I logged in as commscoord, selected 'Display Userids' and only see this: 
![image](https://user-images.githubusercontent.com/25303607/225591241-09352c5c-4aa4-4b48-ac79-9869b26f299c.png)
She needs the 'Transcriber Statistics' action as well.

**Comment by DeniseColbert** [comment]
Deployed to live

**Comment by SteveBiggs** [comment]
The Transcriber Statistics button is now present on live BUT it doesn't do anything - it just returns the same screen.

**Comment by Vino-S** [comment]
Thanks for testing @SteveBiggs, 
I have made some changes and deployed the code again.
Could you try again and let me know, please.

**Comment by SteveBiggs** [comment]
Looks good now, thanks Vino.
