### ISSUE TITLE
Although Genealogical Contacts go to Ali's email as Genealogical Coord, she cannot see them in her Contacts on the website.

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2625]

**Comment by DeniseColbert** [comment]
@Vino-S to add contacts display to secondary roles

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by DeniseColbert** [comment]
@SteveBiggs this is ready for testing in Test 3 if you/Ali can test it?

**Comment by SteveBiggs** [comment]
Cannot get into test3 - get red error message.

**Comment by SteveBiggs** [comment]
Have sent a test genealogical question in test3. Awaiting confirmation that Ali sees it in her Contacts list.

**Comment by SteveBiggs** [comment]
Ali does not see the test GQ contact I raised on test3 nor did she get an email telling her about it. I raised it on 4th July, number is 268388241 which I DO see in my list as Sys_Admin.

**Comment by DeniseColbert** [comment]
@Vino-S to investigate

**Comment by DeniseColbert** [comment]
Vino fixed it so Ali can get messages sent to Genealogy Coordinator via test3, but @SteveBiggs can test on live or test3 to see if this now works as expected.

**Comment by SteveBiggs** [comment]
I raised a test genealogical question some weeks ago on test3 and had no reply from Ali so assume she got nothing. I will try again on the live website.

**Comment by SteveBiggs** [comment]
Ali has confirmed that she now gets both an email and the contact appears in her list so this can be closed.

**Comment by Vino-S** [comment]
Thanks Steve
