### ISSUE TITLE
Add the 'Keep until I say so' button to the list level of Contacts actions.

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2631]
This is to allow the Commscoord and Exec to quickly check which Contacts have been set to Keep by the CC.

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by DeniseColbert** [comment]
ready to test on Test 3 @SteveBiggs

**Comment by SteveBiggs** [comment]
The 'Keep until I say so'/'Remove Keep Designation' button is still not at the Contacts list level. It needs to be at this level against each individual Contact:

![image](https://github.com/FreeUKGen/MyopicVicar/assets/25303607/fcd95a75-30dc-4257-92c2-04563ece1a92)

**Comment by Vino-S** [comment]
Hi @SteveBiggs , I have updated test3 again. Could you test again, please.

**Comment by SteveBiggs** [comment]
Looks good now thanks, Vino.

**Comment by DeniseColbert** [comment]
Done, closing
