### ISSUE TITLE
Entering links to other websites and vice versa

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#2656]
From transcriber Ian Slater

As you may know I spend time weekly in the Peterborough Local Studies transcibing the burial records of Broadway and Eastfield cemeteries. I met a gentleman there today, Julian Dowse, who takes headstone photographs for the FindAGrave website and this this shows the grave co-ordinates. He has asked if it is possible to link the FreeReg records that I transcribe to the burial records for that website. 

Obviously I transcribe thousands more records than the number of headstones that exist in Broadway and Eastfield.
However I believe that each FreeReg record has a unique url which could possibly be linked to a FindAGrave burial record. I realise that FindAGrave is owned by Ancestry.com but would FreeReg permit the use of a burial to a record featured on that website?

This would give a researcher the facility to find a burial with co-ordinates and have additional text provided by FreeReg.

**Comment by DeniseColbert** [comment]
We would be happy for FreeREG links to be added to Find A Grave records (if any required permissions are sought and upheld on the FAG site).

Ian doesn't seem to be asking for FreeREG to place links to FAG, but that would need much more thought and discussion.

**Comment by SteveBiggs** [comment]
I assume that Eric will respond to Ian with this reply?

**Comment by SteveBiggs** [comment]
Sounds good, thanks.

**Comment by CommsCoord** [comment]
Done
