### ISSUE TITLE
Results not found without Soundex

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2658]
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/16d651f9-7a31-42ea-9687-81f295058ccd)

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/91c1add6-2aaa-4a24-b684-f927cb024281)

The name is exact so should appear, regardless of Soundex?

**Comment by SteveBiggs** [comment]
Looks good now.
