### ISSUE TITLE
Check Embargo is automatic for certain dates and later (recent events)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2672]
Does the rake task do this? Or is is human-dependent?

**Comment by CommsCoord** [comment]
The embargo does work but the coordinator does need to implement it themselves. I applied the embargo on a few baptisms files that had entries post-1924 and set the embargo at 100 years and it worked perfectly.

**Comment by DeniseColbert** [comment]
@CommsCoord we think this is how it's expected to work so we can close it?
