### ISSUE TITLE
Colour of two headings in footer illegible

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/MyopicVicar#2679]
The colour of the  headings "Useful links" and "Statistics" has become light grey  instead of white. As a result, they are virtually illegible. Colour looks fine on BMD and CEN.

**Comment by DeniseColbert** [comment]
@Vino-S to take a look (test 3 only it seems)

**Comment by AlOneill** [comment]
@Vino-S @DeniseColbert 
Also on production

**Comment by AlOneill** [comment]
@Vino-S @DeniseColbert 
Correction: now looking OK on production

**Comment by DeniseColbert** [comment]
@Vino-S  has fixed: closing
