### ISSUE TITLE
Specification for different register types

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2682]
Monumental Inscriptions (MI)
Marriage Bonds (MB)
Marriage Banns (MN)

@CommsCoord will call out to Coordinators to canvas different, locality specific info to take into account, and begin drafting spec.

**Comment by CommsCoord** [comment]
Message sent tonight to everyone to whom I would send the Coordinator newsletter ou to, but I also included transcribers as they are 'on-the-ground' working with these types of registers and I do feel their input could be invaluable to a project like this.

**Comment by CommsCoord** [comment]
Have had about 112 responses, mostly from transcribers. Michael Clarke has asked if this topic could be added as a discussion area in the Transcribers group. I have no idea how to access the group (I am not a member) so I might need to join the group and then access the area in question if it can be made.

**Comment by Vino-S** [comment]
Sandra to provide the feedback document.

**Comment by CommsCoord** [comment]
[Register ideas.xlsx](https://github.com/FreeUKGen/MyopicVicar/files/13440877/Register.ideas.xlsx)

This is what I have tallied so far. Another two responses have come in this morning which have not been added.

**Comment by DeniseColbert** [comment]
@DeniseColbert to create a Google Sheet from Sandra's file and place it in a subfolder for this issue on the drive

**Comment by SteveBiggs** [comment]
[Register.ideas.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWxoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0cefbadb978845411a397e900e73c34f10f3f865/Register.ideas.xlsx)

I have added some suggested banns fields in red.

**Comment by DeniseColbert** [comment]
Central file now on drive, please use this version: https://docs.google.com/spreadsheets/d/1uLMxG8yJRBhrCfrF4na9JutMNfpmaDI9/edit?usp=sharing&ouid=102304861870410029965&rtpof=true&sd=true

**Comment by DeniseColbert** [comment]
Handled by ComETT so closing
