### ISSUE TITLE
Search finds only father's or own surname

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2691]
Raised by Barrie Robinson WAR Coordinator:

One of my transcribers raised this in relation to baptisms, and I found a second instance. 1. Richard the son of Robert ALLSUP and Martha HEWITT (1825): a search for Richard ALLSUP finds him, a search for Richard HEWITT does not. 2. Mary PRICE and adult the wife of Lewis PRICE and daughter of Daniel and Mary BROOKS. I have entered this baptism on two rows, the fist as the daughter of Daniel and Mary, the second as the wife of Lewis PRICE, entering Lewis PRICE in the spaces where the father normally appears. I have appended a note explaining the situation in full to both. If as I have now done, I enter PRICE as her personal surname (in Flexible CSV) then a search for Mary PRICE finds both entries, but a search for Mary BROOKS finds neither. We feel that as a researcher may be searching under either surname in either case, the searches should find both instances. I would not have thought tis difficult to program. Hopefully I have explained this sufficiently clearly.

**Comment by Vino-S** [comment]
Hi @SteveBiggs 
Implemented similar solution as #1477
Also for testing in test2
Baptism Record: 
[https://test2.freereg.org.uk/search_records/6583c17abd30f2fed87ea633/robert-allsup-robert-hewitt-baptism-warwickshire-ashted-1825-07-03?locale=en](url)
Record Screenshot
<img width="1009" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXQ5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed90877aa09db522319e1a1b822390220845aa6e/image.png" alt="image.png" />
The Record details:
Forename: Robert
Father Surname: ALLSUP
Mother Surname: HEWITT
The record is now searchable as Robert ALLSUP and Robert HEWITT
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkY5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8012a5684d184b019833f26fcd5e97779e6868bf/image.png" alt="image.png" />

**Comment by SteveBiggs** [comment]
A search for Robert HEWITT did NOT return the record. Robert ALLSUP did.

**Comment by Vino-S** [comment]
Thanks Steve for testing
I searched for Robert HEWITT on **TEST2**. I got the following result. 
<img width="1876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODU5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d2a53d5572207a973a54c185b31ddbf84090400/image.png" alt="image.png" />

**Comment by DeniseColbert** [comment]
Ready to be deployed

**Comment by Vino-S** [comment]
deployed

**Comment by DeniseColbert** [comment]
Keeping open to monitor

**Comment by DeniseColbert** [comment]
@CommsCoord could you ask Barrie if he's aware that this has been fixed? Similar to #1477

**Comment by CommsCoord** [comment]
Barrie said he was not aware. He did not seem bothered by it now as it was some time ago, but he would try to contact the person who had queried this originally to see if they had any further problem.  Could this be closed for now and opened again if there is an ongoing issue?

**Comment by DeniseColbert** [comment]
Closing
