### ISSUE TITLE
Syndicate Coords should be able to move their inactive transcribers to the To be Destroyed syndicate

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2698]
This action needs to be added to SCs actions.

**Comment by Vino-S** [comment]
REady for testing in test3
Following roles can  move their inactive transcribers to the To be Destroyed syndicate:
Sys Admin
Executive Director
Syndicate Coordinator
I have removed this ability for members of Technical syndicate

**Comment by DeniseColbert** [comment]
Vino to check as Steve couldn't see the action in test 3 manage syndicate list.

(and place the exact path to the action in here)

**Comment by Vino-S** [comment]
Hi @SteveBiggs ,
I have updated the code. The action 'Move to inactive syndicate' should now be available to syndicate_coordinators
Below is the path
Your Actions >> Manage Syndicate >>Choose your Syndicate >>  Review All Members >> Then click on the **SH** action for one of the users 
You should then have the **'Move to inactive Syndicate'**
Attached a screenshot for reference:

<img width="1534" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlhkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2ce9dfe38b73f18782ef002ce7c1f4b5b84b67f/image.png" alt="image.png" />

**Comment by SteveBiggs** [comment]
Tested on test3 and all good now, thanks Vino.

**Comment by Vino-S** [comment]
Deployed

**Comment by DeniseColbert** [comment]
Done, closing
