### ISSUE TITLE
Useful cut-and-paste format(Is this still relevant?)

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#27]
Julie writes (about the result list):

Not easy to cut and paste into any other useful format - would take a long time to work through a lot of entries.

**Comment by PatReynolds** [comment]
Anna added:
I always copy results to paste into my genealogy program and the new format is definitely not as good for that purpose. Now I must edit the text to make it more compact and straightforward. For example, there are uneeded extra spaces between delineators (eg Place, Church name, Date, Age, etc) and the resulting details. There are also uneeded extra words. For instance, why must it say: “Burial person forename, Burial person surname, Burial person abode, Register entry number” etc. This is just silly, harder to read, and a waste of space (& ink if one is printing the results for filing):
County    Somerset
Place    Radstock
Church name    St Nicholas
Register type    PR
Register entry number    24
Burial date    20 Oct 1848
Person age    4d
Burial person forename    Margaret
Burial person surname    EDGELL
Burial person abode    Radstock

**Comment by Captainkirkdawson** [comment]
I disagree with the comments wrt names. There are possibilities for multiple forenames and surnames of all events. It is necessary to distinguish them. 

i Guess we could look at the spaces.

**Comment by Captainkirkdawson** [comment]
Address as part of #809 flexble_csv
