### ISSUE TITLE
Direct replies to System Emails (Freeregservant) currently go to Eric Dickens email - this must be stopped.

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2701]
System emails e.g. telling transcribers the status of their uploads need to have a clear statement saying "DON NOT REPLY to its email. It is not monitored" or similar and stop copying Eric on replies.

Perhaps add a message saying if you need further assistance please contact your SC or use this email address - CommsCoord address?

**Comment by DeniseColbert** [comment]
Lemon is implementing a do-not-reply email address which will bounce if transcribers reply. Captured in #1515

**Comment by SteveBiggs** [comment]
I thought we already had an issue for this somewhere!

**Comment by edickens** [comment]
Also freereg-processing.  These emails are generated when someone uploads a file and are for information only to the transcriber and SC...
<img width="581" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1o5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c951dc8f75ed694a49105cb084b3889c80e12456/Capture.JPG" alt="Capture.JPG" />
They should be from no-reply@freereg.org.uk

**Comment by DeniseColbert** [comment]
Done, closing
