### ISSUE TITLE
Move transcribers group to FreeUKGEN

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2714]
Can export all members and direct add to new group

Sandra would communicate to volunteers beforehand in preparation

For discussion: Should Jo directly add all new transcribers as policy? They can always opt-out if they wish.

**Comment by CommsCoord** [comment]
Jo has said that she would be happy to directly add people to the group.  It would be much easier to add directly when the transcriber is being moved to their new syndicate and let the transcriber opt-out or change how they get their communications from the group. 

Eric mentioned we need to change the wording on the password reset/first registration email.

**Comment by DeniseColbert** [comment]
Registration email text needs to be changed from "you will be invited to the transcribers' mailgroup" to "you will be added to the transcribers' mailgroup..."

**Comment by CommsCoord** [comment]
To make things easier on Jo's end, she was going to tell the transcriber they would be added to the group as part of the reassignment to another syndicate from Training. Perhaps on the registration email, this does not even need to be mentioned, as the first step is to get them into training. 

However, on the volunteer page of the website, Eric brought up a good point about the wording of the mailgroup, and perhaps the circled line could be changed to read ' You will have access to a friendly support group' or something similar (thank you Eric for the image)
![image](https://github.com/FreeUKGen/MyopicVicar/assets/20557838/5972e4d6-20f2-469a-80d3-d569a5ad6c0c)

**Comment by DeniseColbert** [comment]
Done, closing
