### ISSUE TITLE
Proposed update to FR Coordinator Help Page: Responding to Contacts

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/MyopicVicar#2716]
Propose updating the Responding to Contacts section of Coordinator Actions on Help pages.

https://docs.google.com/document/d/1sjcSkvOm0_c9LB4pmqixHs2-H-gRCbW2/edit

**Comment by DeniseColbert** [comment]
@AlOneill could you take a look at this please?

**Comment by AlOneill** [comment]
I presume I need access to the document linked above: have made a request.

**Comment by AlOneill** [comment]
@CommsCoord 
OK, I now have access — thank you.

To clarify, am I to update the webpage from the Google doc or review the Google doc?

**Comment by CommsCoord** [comment]
@AlOneill 
Please review it, the more eyes on it the better.
If the contents of the doc meet your approval, can it be placed on the webpage?

**Comment by AlOneill** [comment]
@CommsCoord @DeniseColbert 
I have reviewed this but need some input on the question of whether or not all lists should be capitalised and punctuated in the same way. Should we distinguish between lists of shorter 'bullet points' and those of longer items of more than one sentence? See the document for more context.

**Comment by AlOneill** [comment]
@DeniseColbert @Sandra-AW 
The document appears ready, so I will update the page unless I hear to the contrary. It will not be done in a hurry.

**Comment by DeniseColbert** [comment]
Thanks @AlOneill !

**Comment by AlOneill** [comment]
The updated [Draft coordinator actions, Responding to contacts](https://test3.freereg.org.uk/cms/information-for-coordinators/coordinator-actions/draft-coordinator-actions#contacts) is now on t3. Please see also the notes at the top of the page.

Nowadays I find it difficult to focus on Google Docs, so some issues only properly came to my attention once in the calm waters of HTML. My suggestions are:
1. there are a number of sentences and clauses written in the **passive voice** — consider re-writing such in the more easily understood, more friendly, **active voice**
2. the word 'contact' is used for both the message and the person who has sent the message which could be confusing and which is certainly a little awkward, especially as the casing of contact or Contact is not consistent — so, I suggest that instead we refer consistently to the person as a **'researcher'** (as used in the opening paragraph of the section, for example) and the message as a **'Contact'**
3. replace some or all of the instances of 'click' with **'select'** which is less device- and ability-dependent and hence a more inclusive term

**Comment by AlOneill** [comment]
Draft section updated with Suggestions and moved to [Draft Coordinator Actions](https://test3.freereg.org.uk/cms/information-for-coordinators/draft-coordinator-actions#contacts)

If there are no further suggestions or corrections noted here, I will publish on t3.

**Comment by AlOneill** [comment]
Updated [Coordinator actions](https://test3.freereg.org.uk/cms/information-for-coordinators/coordinator-actions) published on t3. It is sync-ready.

**Comment by DeniseColbert** [comment]
Thanks @AlOneill

**Comment by Vino-S** [comment]
Deployed
