### ISSUE TITLE
Communicate with the member when converted to github issue and when issue is closed

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/MyopicVicar#2736]

**Comment by Sandra-AW** [comment]
Is this the link you wanted me to use to test? It leads to a login page and won't let me go any further. Please forgive me if got this wrong...

https://app.zenhub.com/workspaces/comett-6108532be73e7b0011bbdd81/board

**Comment by Sandra-AW** [comment]
Sorry for the forgetfulness on my part. Is this in relation to feedback coming though on Live?

**Comment by DeniseColbert** [comment]
Sandra to send a test feedback and convert to GH issue. If email with story info received, can be delpoyed

**Comment by Sandra-AW** [comment]
Feedback created in test3 - automatic response email received 
Reply to feedback created in test3 - created the response, sent, and email received
Convery to issue - created Github story 531, however, automatic email response was not received

**Comment by DeniseColbert** [comment]
@Vino-S to check if this is on live and let Sandra know to test there

**Comment by DeniseColbert** [comment]
@Sandra-AW could you test this on live?

**Comment by stsccfr** [comment]
This is working for me.  I created a test case from FreeREG and first got the usual email from freereg.org.uk acknowledging my report and assigning a tracking number.  Then when the case was turned into a GitHub issue I got the following email, which includes both the original FreeREG issue number and a link new GitHub issue:

```
Dear STSCC

You had submitted some feedback to reference [307209284](https://www.freereg.org.uk/feedbacks/66f43244b18f7cad9f29b415) to us with the title Test report for GitHub #2736 at 15:52 on 2024-09-25

This email is to notify you that we have created an github issue and you can monitor the progess here: [link to github issue](https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/1544)
```

**Comment by DeniseColbert** [comment]
@Vino-S to check if email upon closing is implemented

**Comment by Sandra-AW** [comment]
I had the same on a test issue I created so as Dale said we are good to go on it and close this. Thank you Vino and everyone who made this happen.

**Comment by DeniseColbert** [comment]
Deployed: closing
