### ISSUE TITLE
Image server access role

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/MyopicVicar#2741]
Create role for image server access

**Comment by Vino-S** [comment]
Ready for testing in test3
Denise and Sandra are provided Image server Coord secondary role in test3

**Comment by DeniseColbert** [comment]
Sandra to take a look

**Comment by suffolkroots** [comment]
Hi Vino, as the person who will need this access, please may I also have Image server Coord secondary role in test3 so that I can have a look?
Thanks
Ali Hill

**Comment by Vino-S** [comment]
Hi Ali,
Assigned you the Image server coord secondary role

**Comment by Sandra-AW** [comment]
All appears to be in working order in test3. Can be deployed to live. Need to let Coords know Ali's role and they will need to create register/group for Ali to upload images to (this comment to remind me to send out notification when we are ready to get this onto LIve

**Comment by suffolkroots** [comment]
Sandra---
Please will you make it clear that I will only be uploading images for those CCs that do not wish to do it themselves, for whatever reason. I do not wish to tread on anyones toes.

**Comment by Sandra-AW** [comment]
> Sandra--- Please will you make it clear that I will only be uploading images for those CCs that do not wish to do it themselves, for whatever reason. I do not wish to tread on anyones toes.

Yes - that will happen when things move to live

**Comment by suffolkroots** [comment]
Denise---yes I have tested it and it is working as expected.

**Comment by DeniseColbert** [comment]
@Vino-S to allocate Image Server Coord and Data Manager (Eric Booker's role) to Ali's UserID as secondary role.

**Comment by suffolkroots** [comment]
Hi Vino

Thanks for assigning me as Image coordinator.

However, I can't access the images.

When I click on image-server-coord, it takes me here:

![image](https://github.com/user-attachments/assets/abcf9c53-d58c-4811-8f34-be2b533662cd)

 I click on Image Server it takes me back to here:

![image](https://github.com/user-attachments/assets/eeb6c589-759f-43f5-b51e-72ea112bd04e)

TIA
Ali

**Comment by Vino-S** [comment]
Hi Ali,
I have updated the code. Could you try again, please?

**Comment by suffolkroots** [comment]
All OK now thanks Vino

**Comment by DeniseColbert** [comment]
Done, closing
