### ISSUE TITLE
Training System needed so the work of trainees does not go into the live database(Still needed?)

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#290]
We will need a system to train new transribers

**Comment by Captainkirkdawson** [comment]
Is this still needed in the light of the upload that just checks for errors?

**Comment by edickens** [comment]
Yes, because we have a standard set of images for new trainees to do
    which should not go into the live database. We can then easily check
    that they have done it correctly.
    
    On 23/08/2015 22:16, Kirk Dawson wrote:
    
    
      Is this still needed in the light of the upload that just
        checks for errors?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
I think it would be wise to not start straight intp Production..

use Test3 system?

**Comment by Captainkirkdawson** [comment]
I fail to see the benefit of the proposed training system. As noted they
can be easily checked using the upload option to just check for errors. All
the records are available on line they just have no search records hence
are not searchable.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
EricB - I would like a system where work from a transcriber in the
    "Training" syndicate does not go into production.
    We want to get new volunteers to get set up in the way that they
    will eventually transcribe, so best in FR2.  But this is not needed
    until a later version.
    E
    
    On 23/08/2015 22:48, Sherlock21 wrote:
    
    
      I think it would be wise to not start straight intp
        Production..
      use Test3 system?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by edickens** [comment]
In which case, if they are in the Training Syndicate, should the other 
Actions be blocked?  But I think that they should use all the Actions so 
that they know what to do.  E

**Comment by Sherlock21** [comment]
EricD

I know that Kirk is dead against this, but...


I remembering my last 'real' industry job, where we had to train a couple of hundred staff on my site, in the new ways of Maintenance and statutory records management on a new computer package that we were introducing.

the Training there comprised: a totally separate system of:-
 pre- loaded part records,
 a collection of training ID's with the various
 permissions according to the job title,

A Training Manager's team who loaded the various part- records, to teach the different jobs, and to create the scenarios needed. 

lecture room based teaching of the groups of trainees
Then  assess the results of the Trainee's efforts.

Only when they got proficient did they get the OK to move into the Production environment.

Now that was much bigger set up than FreeReg - but the principle is the same.

I think this Training thing is actually a bit late in the day!
In FR2, for whom (now) is this Training setup going to be used? 
 these new  CC's and SC's?
replacements for us & Kirk?

Transcribers?
or whom?

We will eventually have Transcribers who will  range from Scared stiff - to dying to dabble and fiddle about and see how far they can get, and play "What if i do this"

So I think its essential to have an area where they get all the correct software for their job,  but limited past records to make it a bit realistic to add uploads to,
Then practice their new role.

What's the scope of your expectations for these Trainees?

**Comment by Captainkirkdawson** [comment]
No you get me totally wrong.

I have no objection to a training syndicate. It makes a great deal of sense. EricD can set that up whenever he wants. It requires no input from the development team.

What EricD was asking for was for this syndicate to be treated differently from other syndicates. It was here that you start to see my concerns starting to appear. Currently all syndicates are treated the same way and it is a slippery slope when you start to say treat this one differently from another. 

His request was that uploads to the syndicate not be included in the search database. But what if other syndicates also have people who they are training or developing?
We have already implemented a general option on the upload that says just check the records, don't add them to the search database. Its available to every syndicate and transcriber. So why not use this for people in training? That is my point

**Comment by edickens** [comment]
While away I've had another thought.
    Could the upload screen just not give someone who is a member of the
    Training Syndicate the Action to enter into the database.  This will
    let them upload and Validate and do everything else.
    But when their Syndicate is changed from Training to their final SC,
    then they will need to delete these files, although they will still
    just be against their UserID and will not have updated the database.
    To take your other point about people not in the Training Syndicate
    being trained by other SCs, we could use the "Role in FreeREG" which
    has "Training" as an option instead of them belonging to the
    Training Syndicate.
    E
    

    On 24/08/2015 18:59, Kirk Dawson wrote:
    
    
      No you get me totally wrong.
      I have no objection to a training syndicate. It makes a great
        deal of sense. EricD can set that up whenever he wants. It
        requires no input from the development team.
      What EricD was asking for was for this syndicate to be treated
        differently from other syndicates. It was here that you start to
        see my concerns starting to appear. Currently all syndicates are
        treated the same way and it is a slippery slope when you start
        to say treat this one differently from another. 
      His request was that uploads to the syndicate not be included
        in the search database. But what if other syndicates also have
        people who they are training or developing?
        We have already implemented a general option on the upload that
        says just check the records, don't add them to the search
        database. Its available to every syndicate and transcriber. So
        why not use this for people in training? That is my point
      —
        Reply to this email directly or view
          it on GitHub.
