### ISSUE TITLE
Need to have register /church Merge

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#31]
The current church code changes church names and propagates to Freereg!_csv_files.  It will not work correctly when there are multiple churches in a place and one attempts to rename to one of the exiting church names. In reality we need a merge rather than a name change. i.e. we need to merge the registers of two churches under one name and eliminate the other church name.

**Comment by Sherlock21** [comment]
Is this the same ( or related to) the task of correcting a mis-spelled church name in one batch, to match it with an existing correct name?
Like me cleaning up a batch of St Mary, when the correct name is St Mary the Virgin?

In which case we really do need a plan as I had not noticed there being an issue when I have done this in the past. - or is it one of those things which worked correctly once, but more recently does not?

**Comment by Captainkirkdawson** [comment]
No it was fixed a long time ago (mid summer) but the issue was not closed
