### ISSUE TITLE
Attach CSV files to problem reports

### ISSUE THREAD

**Issue by graphiclunarkid** [FreeUKGen/MyopicVicar#312]
As a member of the executive submitting a problem report I want to attach a file in Comma Separated Values format so that I can document file-upload or parsing problems.

ACCEPTANCE CRITERIA
- I can create a problem report. The system allows me to attach a single file in CSV format.
- I can submit the report. The CSV file is uploaded and stored by the system.
- The CSV file is associated with the report.
- I can add no other file type except CSV and those that were already supported.
- I can only add a single file per problem report.

This feature follows on from story #221
Dependent on #1293

**Comment by Captainkirkdawson** [comment]
See 313; do not see any value
