### ISSUE TITLE
Add multiple files to a problem report

### ISSUE THREAD

**Issue by graphiclunarkid** [FreeUKGen/MyopicVicar#313]
As a member of the executive reporting a problem I want to add multiple files so that I can include all relevant documentation.

ACCEPTANCE CRITERIA
- I can create a problem report. The system allows me to attach up to five files.
- I can submit the report. The system uploads and stores all five files.
- All five files are associated with the problem report.
- I cannot attach unsupported file types.

This story follows on from #221

**Comment by Captainkirkdawson** [comment]
Do we need more than a single screen shot???????

**Comment by Sherlock21** [comment]
Not all problems are solved by adding a screen shot. sometimes I wished to add a supplementary package of the input csv file for example - to show what original data we were discussing. Still valid I suggest.
same point in 312.

EricB

**Comment by Captainkirkdawson** [comment]
We have now been running without this feature for 3 years, The developers have no specific need for the information so believe it should be closed or considered for version 2
