### ISSUE TITLE
Trapped emails are being held by Google as Spam

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#315]
I check my gmail spam filter and find that Trapped emails and also Register emails for setting password are being trapped as Spam.  Does anyone else check their spam filters for this and what is it in the message that triggers Spam?

**Comment by Captainkirkdawson** [comment]
Not sure what we can do about what spam filters do with our emails other than have the senders email address added to your white list or contact list

**Comment by edickens** [comment]
I check my Google Spam filter and these "Trapped" emails are not caught 
in my Google spam filter.
EricD

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
Sorry do not understand the comment

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
