### ISSUE TITLE
Clean up search query collection

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#316]
As a technician I want old search queries to be scrubbed from the list of historical queries so that the list doesn't grow unmanagebly large over time.

ACCEPTANCE CRITERIA

- The list of search queries is capped to X records

OR

- Search queries are removed from the list after X days

**Comment by Captainkirkdawson** [comment]
If we move to a temp search_queries collection is this still required???

**Comment by benwbrum** [comment]
I think it is, yes.
