### ISSUE TITLE
Filter out searches which are too recent

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#318]
Although it is contentious, it has been said that we should not display BA less than 100 years, MA 75 years, BU 5 years.  So if someone requests within this range, then we do not allow it.

**Comment by edickens** [comment]
We did not discuss this at the last Scrum.  I think it should be included in Version 1.1 and definitely before the search goes live.
If it is included, the help documents and help icons will need updating.

**Comment by edickens** [comment]
This has become more important because we are being donated transcriptions up to 1980.  We want to keep them on file for the future as the opportunity to get them may not present itself again.
I think this is a very quick and easy amendment to make to the search function.  Something will need to go in the Advice for Researchers that this filtering takes place.

**Comment by DarrenWright** [comment]
Eric D suggests that we add an end date to the search itself rather than processing the search results.

**Comment by benwbrum** [comment]
I'm moving Julian's decision-making code into the search record creation code.
