### ISSUE TITLE
Back up entries and search-records collections

### ISSUE THREAD

**Issue by graphiclunarkid** [FreeUKGen/MyopicVicar#319]
As a tecnician I want the entries and search-records collections to be backed up so that I can restore them in the event of a disaster

ACCEPTANCE CRITERIA

- I can restore the entries collection from a backup. No more than 24 hours of data are lost.
- I can restore the search-records collection from a backup. No more than 24 hours of data are lost.

**Comment by Captainkirkdawson** [comment]
With 3 servers there are 3 copies. It is not necessary to back up these collections
