### ISSUE TITLE
Full Place name list for Researchers

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#333]
We have the Data Available Page, but not a full list of places, even though this information is available on our database.

**Comment by Captainkirkdawson** [comment]
Currently it is a full list of places, If there is no data then there are no records indicated.

**Comment by Captainkirkdawson** [comment]
It is now displaying only those data for which we have data. Which was the original specification.
Data for places for which we have data available for transcription will be part of the RAP
