### ISSUE TITLE
Add all to DAP places

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#345]
EricD has said; It would be nice to be able to select all places for a county

**Comment by Captainkirkdawson** [comment]
All discussion has been about the Search and not the original story which was aimed at the Database Contents.
Given the nature of the DAP or Database Contents I am unconvinced of the need for an All in the selection box. All Its going to do is take you to page where you have to scroll down all of the Places. This is what people objected to in the first place and why we introduced the selection.
WRT Search a blank means all.

**Comment by juliancheal** [comment]
Unless I was missing something obvious it seemed more difficult than I realised to add an "All" into the search results. So if we're happy with blank meaning all, then I'll leave it at that.

**Comment by Captainkirkdawson** [comment]
Julian; Lets talk about on Wednesday.  Since the listing of places is generated by a chained jquery script I can imagine adding all would not be trivial. You may want to look at 93 in the meantime as it is perhaps related. Might be a good idea to review our drop downs for consistency. I know I have not been consistent

**Comment by edickens** [comment]
My view on all the different lists
      which have a blank at the top is that it "not positive".  Why
      would blank mean "All"?  And a blank which is not relevant and
      does nothing would be even worse.  There should always be
      something to select.
      E
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 02/02/2015 17:17, Julian Cheal wrote:
    
    
      Unless I was missing something obvious it seemed more difficult
        than I realised to add an "All" into the search results. So if
        we're happy with blank meaning all, then I'll leave it at that.
      —
        Reply to this email directly or view
          it on GitHub.
