### ISSUE TITLE
Research data present flag setting and updating

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#350]
We introduced the data present flag solely as a means of determining whether the Place should be included in the Place selection table. 
There is evidence that when registers/churches and places are relocated this flag may/may not always be set correctly after the relocation.
If the flag is still used/needed then the process for updating the flag needs to be reviewed.

**Comment by Sherlock21** [comment]
If it's no longer used by you, then i am not too bothered about you taking it off and cleaning up.

**Comment by edickens** [comment]
Can it be recreated when we finally
      bring across the files and replace the ones on FR2?  I think it
      will be necessary to know which places have data so that lists can
      be shortened to active places only.
      EricD
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 01/01/2015 16:36, Kirk Dawson wrote:
    
    
      We introduced the data present flag solely as a means of
        determining whether the Place should be included in the Place
        selection table. 
        There is evidence that when registers/churches and places are
        relocated this flag may/may not always be set correctly after
        the relocation.
        If the flag is still used/needed then the process for updating
        the flag needs to be reviewed.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by PatReynolds** [comment]
I'm not sure what the purpose of the flag is - could someone explain?  Cheers, Pat

**Comment by Captainkirkdawson** [comment]
We use the flag to determine if the place should be displayed in the selection drop down box and therefore included in the search

**Comment by PatReynolds** [comment]
Thanks! Got this now.   Cheers, Pat

**Comment by Captainkirkdawson** [comment]
Code cleaned up as part of 421
