### ISSUE TITLE
Use data range for batch validation

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#352]
A data range has been added to the register collection. The fields need to be filled by coordinators.
Once present they should be used of validation of batch entries

**Comment by edickens** [comment]
Hi Kirk,
      I assume that if no dates are entered then no validation takes
      place.  Also, when batches are validated, it is just a caution,
      not rejection, because sometimes dates are in the register which
      are outside the dates on the cover of the register.  Data entry
      validation will be something different.
      EricD
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 01/01/2015 23:11, Kirk Dawson wrote:
    
    
      A data range has been added to the register collection. The
        fields need to be filled by coordinators.
        Once present they should be used of validation of batch entries
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Correct no range no validation
FR2 has no caution. It either passes or it does not
As currently conceived any year below the minimum year for the register will be rejected as an error. Similarly if the date is beyond the maximum year for the register it will be rejected as an error

**Comment by Captainkirkdawson** [comment]
Eric Dickens said
I think 352 needs to be NO for now.  I say this because the date fields that are set up now are against Register Type.  So for "Parish Register" it will need to be from when the Church first opened and then be open ended if the Church is still operational. If the Register Type is say Phillimores, then we know the range of years, but sometimes there are the odd late entry that applies outside this range.  So a "Caution" would be needed, but I don't think you have that facility.  Hence my saying NO for now.  Also, all the years have yet to be entered, so the date check will be little used for now.
