### ISSUE TITLE
Make surname optional in search

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#358]
Consensus that search should permit a search by forename only but that either forename or surname MUST be present.

**Comment by DarrenWright** [comment]
This seems quite reasonable. I assume the search limit is likely to stop it having disastrous implications on database capacity.

**Comment by Captainkirkdawson** [comment]
Will likely have to "fine-tune search limit as it does cause a server
implication. had never expected this to be an option

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
