### ISSUE TITLE
Add an All Counties search option

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#360]
A select All Counties option should be permitted. To avoid issues with search loading this should only be permitted when there is a narrow band of years. 20 years?

**Comment by Captainkirkdawson** [comment]
Implemented

**Comment by benwbrum** [comment]
We need to make "All" explicit as an option on the counties input control.

**Comment by PatReynolds** [comment]
'All' as explicit is 118, so will close this.
