### ISSUE TITLE
Print save option

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#366]
Currently there is no easy way of saving the results of a search. It has been suggested we implement a print or save option that the user can action to store or print the results on their computer

**Comment by Sherlock21** [comment]
I would go for user option to do either Print or Save. That removes the hassle of saving user's data for them.
Could/ should we make the Save as a csv file so thew can table it?
Could/ Should we give that download in that Genealogy transferable GEDCOM format, so they can drop records into their own family records software?

**Comment by edickens** [comment]
Not csv.  I would say a jpg, rather
      like a screen print.  This can be added to a family tree program
      as evidence.
      GEDCOM is a good idea but am not sure how you can use it to
      actually add an entry to your family tree.  I don't think it will
      be used that often.
      EricD
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 06/01/2015 16:59, Sherlock21 wrote:
    
    
      I would go for user option to do either Print or Save. That
        removes the hassle of saving user's data for them.
        Could/ should we make the Save as a csv file so thew can table
        it?
        Could/ Should we give that download in that Genealogy
        transferable GEDCOM format, so they can drop records into their
        own family records software?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
I would like a csv file to be downloaded please. One can do far more with the data in it, than in a jpg file. And the data starts live in text, just displaying it to make a picture on the user's screen doesn't make it easier to get it from there as a picture does it?
So give the user a choice of file type in that case please.

**Comment by DarrenWright** [comment]
Saving as a CSV file is the more logical way to do it but I think there are license issues given the agreement we currently have with transcribers (though that shouldn't prevent us working towards this).

**Comment by edickens** [comment]
My understand is that this would be a
      one record csv file of the detailed result of the search, which
      the researcher would want to put into their family tree or their
      spreadsheet or database.
      EricD
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 08/01/2015 12:55, DarrenWright wrote:
    
    
      Saving as a CSV file is the more logical way to do it but I
        think there are license issues given the agreement we currently
        have with transcribers (though that shouldn't prevent us working
        towards this).
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Interestingly I thought it was a print/save of the index of search results
as well the search detail result

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
But why would someone want the index of
      results?  They are more likely to want to save the search criteria
      that they entered so that they can repeat the search.  We were
      thinking of offering this when we get to the stage of researchers
      registering and then having extra facilities.  One would be to
      bring up a list of their recent searches so that they can repeat
      them.
      E
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 08/01/2015 14:21, Kirk Dawson wrote:
    
    Interestingly I thought it was a print/save of the
      index of search results
      
      as well the search detail result
      
      
      Kirk Dawson
      
      Fairmont Hot Springs, B.C.
      
      V0B 1L1
      
      
      On Thu, Jan 8, 2015 at 6:01 AM, Eric Dickens
      <notifications@github.com>
      
      wrote:
      
      
      >
      
      >
      
      >
      
      >
      
      >
      
      > My understand is that this would be a
      
      > one record csv file of the detailed result of the search,
      which
      
      > the researcher would want to put into their family tree or
      their
      
      > spreadsheet or database.
      
      > EricD
      
      > _____________________________________
      
      > Eric J Dickens
      
      > FreeREG Chairman
      
      >
      
      > On 08/01/2015 12:55, DarrenWright wrote:
      
      >
      
      >
      
      > Saving as a CSV file is the more logical way to do it but I
      
      > think there are license issues given the agreement we
      currently
      
      > have with transcribers (though that shouldn't prevent us
      working
      
      > towards this).
      
      > —
      
      > Reply to this email directly or view
      
      > it on GitHub.
      
      >
      
      > —
      
      > Reply to this email directly or view it on GitHub
      
      >
<https://github.com/FreeUKGen/MyopicVicar/issues/366#issuecomment-69176039>
      > .
      
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by edickens** [comment]
I'm getting more comments on this.  I think it should be moved up the priority.  For example...
The original FreeReg is easy to use and printed images are perfectly adequate.

I’ve tried to right click for printing but I got two pages of gobbled gook and I’ve tried to copy and paste the image into WORD but it is far too wide to copy onto either portrait or landscape. Looks like lots of mucking around to fix. How about a print button on your pages?

Thanks

Robyn Taylor

**Comment by Sherlock21** [comment]
There are 2 main elements of data that one gets, as a result of a Search.
The first being the table of 1-line person names, with the view details link at the RH end.
the second is the larger page of data one gets as "Details"

I think both should be downloadable either by just doing a Screen print [MD+P]
Or by downloading it as a csv file.

see also another # identical issues, and my same comment. They are the same problem and common solution.

**Comment by benlaurie** [comment]
On 29 April 2015 at 09:22, Sherlock21 <notifications@github.com> wrote:

> There are 2 main elements of data that one gets, as a result of a Search.
> The first being the table of 1-line person names, with the view details
> link at the RH end.
> the second is the larger page of data one gets as "Details"
>
> I think both should be downloadable either by just doing a Screen print
> [MD+P]
>

What is "MD"?

**Comment by edickens** [comment]
I would not go for the CSV file.  I appreciate that this is useful for 
loading into a spreadsheet to keep the results of your searching, but it 
will only be useful to a few.
The problem identified by my recent contact is that the screen print is 
too large and does not fit on to paper properly, not even in landscape.  
So the idea of a print icon which creates a printer friendly version 
seems a good idea to me.
E

**Comment by benlaurie** [comment]
The problem appears to be that some/all of the CSS is set to "screen only" - not sure why.

Presumably allowing the CSS to also be used for print would be a first step towards sanity.

**Comment by Sherlock21** [comment]
Sorry, Ben, It started off as CMD when i typed it. will go back and edit the item now.
Eric B

**Comment by benlaurie** [comment]
BTW, I went through the CSS and HTML as an experiment and changed "screen" and "only screen" (or was it "screen only") to "all".

Printing then yields something much like the page. Needs work, I'd say, but definitely improved.

**Comment by Sherlock21** [comment]
I don't see that providing Print will be a breach of the Agreement with Transcribers so far as the overall movement of data is concerned.
After all, the researcher can get a camera and photograph the page of data. It will only work if the data does not "spill over more than one screen's worth of course but even that's not insurmountable.

Is this lack of being able to print off what one has got on the screen a feature by design intent (ie did we mean to make it non printable) or has it just come that was as a result of these styling activities?
Is this the reason why the "Google Website Friendly" test fails?

**Comment by Sherlock21** [comment]
Refer also to #210 for printing off results that one has on the screen.

**Comment by edickens** [comment]
From a researcher to reg-exec...
Hi
 
Many thanks for your FreeReg service.
 
I wonder if it might make your service more user friendly it you could add a button to your individual record pages that provides a shortened web address [like Tiny URL?] & adds it into your clipboard ready for pasting.
 
Your addresses are very long and I've pasted a few to an html page, but the page's code is now hard to work with as my page code is now mostly meaningless Freereg code.
 
I guess there's a possibility of it creating a small income, if you use say googles's https://goo.gl/?
 
If you like the idea and have not already worked on it, I'd be happy to mock-up a page
 
Looking at your ULR below, I assume you aready use far shorter addresses. Might a button offer that instead?
 
Regards Geoff Soper, Redhill, Surrey
 
http://www.freereg.org.uk/cgi/SearchResults.pl?RecordType=Marriages&RecordID=2832526&v=MTQzMTA4NzI5MDpmNWFkYjM5ODExODVhNjA0NDE5NzY0MDliN2RkM2U1YzEyY2M3YmY1
becomes
http://goo.gl/Uy4JLr
or
http://tinyurl.com/o7wzky
 
or perhaps a button could create a line in some inhouse database of 'short links to freereg addresses', like www.freereg.org/07wzy? [6 digits allow for 2,500M links?]

**Comment by Sherlock21** [comment]
Won't such a link be obsolete after the next update of that data source?

At this stage, I would have thought we need to address other more important things about the total FR2 program suite, than get side tracked like this?

EricB

**Comment by edickens** [comment]
Hi EricB,
My understanding is that in FR2 the link will not change, unless someone 
replaces that actual file/batch.
This is important because we are having real researchers sending in 
transcription errors and we can't do anything about it.  While we deal 
with "customers" I think we need to make sure it works.
E

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
The researcher was commenting about FR1 not FR2.

In general the FR2 urls are shorter

The search record id is not permanent in either FR1 or FR2 so keeping that
is not a great idea.

This one would not be high on my agenda

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
EricD
But Does not an update effectively create a new record item and there fore a new id?

EricB
