### ISSUE TITLE
Search does not pick up wife of Thomas MORGAN

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#368]
When searching for the burial of a Mary MORGAN, no record is found even though Mary MORGAN is there. Record does not have a Mary MORGAN entered but Mary wife of Thomas MORGAN

**Comment by benwbrum** [comment]
@Captainkirkdawson,  do we know which original file contained the problematic records?  Even a county and date would help me get the data to test.

**Comment by Captainkirkdawson** [comment]
Search for Ann Morris buried 8 May 1720 in Devon Parish of Landcross. No result returned. Actual entry is line 63 in File DEVLANBU Entry not found presumably because the parish register contained no surname, but wife of Morgan Morris. There must be hundreds of entries like this in the database, and many minors often entered as son of, or dau. of, with no surname, the only clue that these may be minors. These entries are similar to baptism entries and the search engine needs to search Relative's Surname if no surname is present. 

The file is (You must be logged in to access it.

http://test2.freereg.org.uk/freereg1_csv_files/5463b079e9379010fcf86950

The record is 

http://test2.freereg.org.uk/freereg1_csv_entries/5463b079e9379010fcf86a0b

**Comment by benwbrum** [comment]
That's perfect, Kirk -- thanks!
