### ISSUE TITLE
Refinery Login should match rest of site

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#371]
Any time a user is redirected to the refinery login screen, it's quite jarring, as they lose their menu buttons and the styling looks like a totally different site.

**Comment by juliancheal** [comment]
Oh, I didn't see you had put your name against this. Have you started working on it? As I've got a branch with this working.

**Comment by benwbrum** [comment]
Sweet!  That makes my day.

**Comment by juliancheal** [comment]
So it currently looks like this:
![new_login](https://cloud.githubusercontent.com/assets/63991/5844607/f5f720a2-a1bd-11e4-9f84-4214a56f7317.jpg)
As you can see it needs styling, but what do we think?

**Comment by benwbrum** [comment]
Much better than the current set-up.  Thanks!
