### ISSUE TITLE
F2 works with local RW db and replicated RO db

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#380]
After long discussions with Kirk and Lemon, we've settled on a plan in which each app server will have access to a read-only replicant of F2 data, as well as a local read-write database in which to store the search_query record used within a user session.  We need to implement this and test it.

**Comment by juliancheal** [comment]
Where is this discussion?

**Comment by benwbrum** [comment]
All on email.  I'm happy to forward it or meet with you on it next week.

Ben

**Comment by benwbrum** [comment]
To summarize, the production deployments for the older FreeUKGen sites scale by spinning up new app servers and database servers 1:1, then putting them behind a load balancer.  The app servers connect to a read-only, replicated database, which supports searching.

F2 is different in that each search performed writes a record to the search_queries collection, which is used to hang persistent information off of allowing the user to page through individual records, drive the search logic, and other functions.

If each search server must access a read-write DB, the scalability model used elsewhere won't work.  However, if we make the search_queries collection--which is the only one searchers need to write to--use a local database, then we can support that model.  This means that instead of the development model (one app server-one R/W MySQL DB (Refinery)-one R/W Mongo DB (F2 data)), we'd instead have a distributable model (N app servers, each with one R/O MySQL DB (Refinery), one R/O Mongo DB  (F2 data), and one, non-replicated R/W Mongo DB)

**Comment by Captainkirkdawson** [comment]
Just to clarify. That's the problem with trying to summarize! In paragraph 1. The replicated databases on the older sites are never updated. They are replaced by a new one each month.

In paragraph 3. We would be using the standard Mongodb cluster replication for everything except the local search_query R/W DB. In the cluster there would be a primary and secondaries. 
The primary would respond to all writes that go to the replicated database. Saved search queries would be directed to this database when we implement that function for researchers. 
All admin functions would be directed to the primary. It is planned that this will be done by the load balancer directing all login requests to the primary the implementation of this aspect is a separate story 381. 
The  MySQL DB (Refinery) database is not highly volatile and is only used for login verification and static page delivery. It is planned to keep the replica sets updated by a regular cron process. Story 382
