### ISSUE TITLE
MySQL replica updating

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#383]

**Comment by Captainkirkdawson** [comment]
Need to write a rake tasks to select and dump  changed files as well as reload.

**Comment by edickens** [comment]
Kirk,
      Are you going to do anything about "Red flag" Churches which may
      not be needed after you have dumped changed files?  The files may
      have been corrected in FR1, which is why the "Red flag" Church is
      no longer needed.  Could you delete any "Red Flag" Church which
      has no batches after the dump?
      All changed (as compared with New) files should have the same
      UserID and Filename.  So I assume that you will replace these
      files.  But can you do anything with files which have changed
      UserID and/or Filename?  It probably will not matter if you are
      going to do a full rebuild at some time.
      EricD
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 27/01/2015 03:00, Kirk Dawson wrote:
    
    
      Need to write a rake tasks to select and dump changed files as
        well as reload.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
This comment has no relevance to the MySQL replica updating. Only MySQL tables are user fro user login and static html scripts.

**Comment by Captainkirkdawson** [comment]
Assuming that all Member logins go to the primary then all MySQL changes will always be on the primary. The only aspect of the MySQL tables used by the secondaries are the static refinery pages/images. There is no significant impact on the researcher if these are out of date.  The secondaries need to be updated in case they need to take over as primary. Would a regular rsync of the primary to the secondaries achieve this goal. Or would it be easier to run an hourly cron process to do  a selective backup  of the primary pages/images and restore those on the secondaries.?
