### ISSUE TITLE
DocumentNotFound in SearchQueriesController

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#386]
Searching on the test server yields the following error:

 Mongoid::Errors::DocumentNotFound in SearchQueriesController#show

Problem:
  Document(s) not found for class SearchQuery with id(s) 54c1129ae9379046a4000001.
Summary:
  When calling SearchQuery.find with an id or array of ids, each parameter must match a document in the database or this error will be raised. The search was for the id(s): 54c1129ae9379046a4000001 ... (1 total) and the following ids were not found: 54c1129ae9379046a4000001.
Resolution:
  Search for an id that is in the database or set the Mongoid.raise_not_found_error configuration option to false, which will cause a nil to be returned instead of raising this error when searching for a single id, or only the matched documents when searching for multiples.

Rails.root: /home/apache/hosts/freereg2/MyopicVicar
Application Trace | Framework Trace | Full Trace

app/controllers/search_queries_controller.rb:126:in `show'

**Comment by Captainkirkdawson** [comment]
This was not a code bug but caused by a damaged database.
