### ISSUE TITLE
Integrate new header

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#389]
Josh writes:
Hi Ben

I have completed a new header for the free reg project, as well as made the default container a bit wider.

You can see the changes in the following commits:

    https://github.com/FreeUKGen/Free-Reg-Frontend/commit/b861a5931cc8e242f6f185a8c8b2fa548d8086f7
    https://github.com/FreeUKGen/Free-Reg-Frontend/commit/482e6882b3f68acd0c7d01c86fc6e0a3c51dc03b
    https://github.com/FreeUKGen/Free-Reg-Frontend/commit/759133e7ce3377cc5bd41f0a3dfa1fed9f48863a

But essentially you will need to copy over all of the following folders:

    https://github.com/FreeUKGen/Free-Reg-Frontend/tree/master/styles/css
    https://github.com/FreeUKGen/Free-Reg-Frontend/tree/master/images

And replace the entirety of your .site__header__nav with the following lines:

https://github.com/FreeUKGen/Free-Reg-Frontend/blob/master/index.html#L64-L86

Hopefully that makes some sense to you, let me know if it doesn't!

**Comment by juliancheal** [comment]
FYI. I've been doing some research (for a personal project) into using external stylesheets/JS in a Rails project. And it involves putting the files in /vendor/assets. We should also be able to run bower and keep the files in sync via git submodules.

**Comment by juliancheal** [comment]
Gah, computers are infuriating!

So I got bower to install all the styles etc, from https://github.com/FreeUKGen/Free-Reg-Frontend and everything was looking nice, no more copy&paste...

...Except it currently looks like this.
![screen shot 2015-01-23 at 15 03 26](https://cloud.githubusercontent.com/assets/63991/5876717/6b9bf310-a311-11e4-9d7b-4bc53ed8d450.jpg)
I can't for the life of me work out if it's the new style updates or my nifty new style importing system.

So quick revert. I'll just import the new styles asap as outlined above. Then if that works push that for now. if doing that looks like my screenshot, then we have a problem.

**Comment by juliancheal** [comment]
FYI ignore me! It works! I just needed to RTFM notably this bit, "And replace the entirety of your .site__header__nav with the following lines:
https://github.com/FreeUKGen/Free-Reg-Frontend/blob/master/index.html#L64-L86"

**Comment by Captainkirkdawson** [comment]
But we cannot do a straight  paste of their code as the current navigation
bar varied the actual links depending on the nature and role of the person.
So that logic needs to be retained in the new navigation bar.
K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by juliancheal** [comment]
I've created a pull request, which is the version using Bower. https://github.com/FreeUKGen/MyopicVicar/pull/393

However, in the interest of science, I'm still creating a branch and pulling in these changes manually, just to compare.

Also yes Kirk, by copy & paste, I meant copy the bits that we needed and keep our nice coded navigation all coded.

**Comment by juliancheal** [comment]
It's me again. I've created a new branch https://github.com/FreeUKGen/MyopicVicar/tree/new_header_copy_pasta which is where I just copied the files as instructed in the email above.

It looks exactly like my pull request #393 which imports all the style assets using bower.

So take your pick:
* Keep the current styles all copy & pasted (ie. change nothing)
* Use bower to import styles and keep in sync

**Comment by Captainkirkdawson** [comment]
In my dotage I have become paranoid; like to make sure we have communicated completely. Hope you don't mind.
To date we have done the copy and paste as it was KISS. However we had always wanted to do the bower import, just never had the time. In your mind are there any performance downsides to having production use Bower?
Will have a look at both after breakfast.

**Comment by Captainkirkdawson** [comment]
Have pulled the copy and paste into my sever.
One observation. The social links are not in the navigation bar. I believe it was Darren's intention that they be there certainly for researchers.
There is another issue that I will raise in an email that relates to the style itself not your implementation.

**Comment by juliancheal** [comment]
Nope don't mind at all. But whoops you're right, I did forget the social links.

**Comment by Captainkirkdawson** [comment]
Have added the social links
