### ISSUE TITLE
Provide guidance on the search results (was: consider more fields in Search results?)

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#394]
A suggestion from a Coordinator now that we have a wider screen

**Comment by edickens** [comment]
- The Register type is not needed in the first list of results
- Display Parents first names in the first list as this is key to identifying a record
- Display age in Baptism and Burial, again key to identifying the correct record

**Comment by Captainkirkdawson** [comment]
Please clarify if you are talking about the Search Results or the Database Contents. The title says one but the content seems to imply the other.
Nor do I feel we should be responding to single coordinator observations. None of these matters were raised when we asked for a systematic review by the 12 members of the test group,

**Comment by edickens** [comment]
Hi Kirk,
      
      I will revisit my email about the contents.
      
      I don't respond to a single request, but some are replying to me
      personally off list.  I will also only pass on ideas which I think
      are useful and I will mark them as "Enhancements" which means that
      they are for future versions.  I have had other emails where it is
      obvious that the person has not got used to the facilities, such
      as not knowing that the reports can be sorted.  I just reply to
      these, sometimes copying Bernie so that the documentation can
      address these questions.
      
      Regards,
      
      Eric
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 28/01/2015 05:01, Kirk Dawson wrote:
    
    
      Please clarify if you are talking about the Search Results or
        the Database Contents. The title says one but the content seems
        to imply the other.
        Nor do I feel we should be responding to single coordinator
        observations. None of these matters were raised when we asked
        for a systematic review by the 12 members of the test group,
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by edickens** [comment]
Advice please.  I am getting requests
      such as "Does the search do x or y?".  If I don't know the answer,
      how should I log this request?  I have been thinking that we may
      need to ask Ben to check the help documents and ensure that the
      description of the Search is complete.
      
      Also, if I get what I think is a useful request which is sent to
      just me, should I put it out to all CCs to see what they think?
      
      E
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 28/01/2015 14:07, Eric Dickens-gmail wrote:
    
    
      
      Hi Kirk,
        
        I will revisit my email about the contents.
        
        I don't respond to a single request, but some are replying to me
        personally off list.  I will also only pass on ideas which I
        think are useful and I will mark them as "Enhancements" which
        means that they are for future versions.  I have had other
        emails where it is obvious that the person has not got used to
        the facilities, such as not knowing that the reports can be
        sorted.  I just reply to these, sometimes copying Bernie so that
        the documentation can address these questions.
        
        Regards,
        
        Eric
        _____________________________________
Eric J Dickens
FreeREG Chairman
        On 28/01/2015 05:01, Kirk Dawson wrote:
      
      
        Please clarify if you are talking about the Search Results or
          the Database Contents. The title says one but the content
          seems to imply the other.
          Nor do I feel we should be responding to single coordinator
          observations. None of these matters were raised when we asked
          for a systematic review by the 12 members of the test group,
        —
          Reply to this email directly or view

            it on GitHub.

**Comment by Captainkirkdawson** [comment]
My opinion. We need to keep all feedback away from the developers unless they are bugs. Inputs need to be consolidated and then prioritized,  The testing session had good points and bad points. We got 50+ comments which I consolidated into a report and that resulted in just 12 stories. All of which were implemented. The bad point was that we had 50+ items that went into feedback and therefore into the tracking system.
I suggest you have people use the comment process if you want a process point.
http://freereg2.freereg.org.uk/contacts/new
Its available through the About Us link.
The comments will go to you and be logged in the system BUT NOT into our management systems.
You can also see them on_line

**Comment by benwbrum** [comment]
I'm emailing Eric to set up a way to describe the search engine to him.

**Comment by Sherlock21** [comment]
I am in favour of a summary of either a public version of: "What the Search Engine does" in so far as the user needs to know what to put where, to find the likely results but no detailed enough for them to go build their own!
OR for the use of the Managers, a detailed version of the same - so we can take the load off the code writers as you say but actually be able to answer meaningful questions.

After all, does the public get a definition of how the Search engine works in Ancestry of FMP? No.

**Comment by PatReynolds** [comment]
Added to task list for intern: create mock-ups of potential changes to search results display (PC), and conduct formative user evaluation

**Comment by PatReynolds** [comment]
Added field for testing/consideration: link to repository

**Comment by Captainkirkdawson** [comment]
Could you please expand on this requirement, as written I cannot understand what is being requested

**Comment by Sherlock21** [comment]
Things have possibly moved on since my comment started life. I can't see anything relating which is not still needed.

**Comment by edickens** [comment]
I see this as V1.7 - researcher enhancements Phase 2.  We can define then..  But Pat needs to say if she has an urgent need.  E

**Comment by PatReynolds** [comment]
I am going to move the items relating to the original subject to a new story.  Remaining comments are about providing guidance on the search results, which I think is closed, and management of feedback, which I think is covered elsewhere.   Please raise new issue or clarify here if other action is needed.

**Comment by Gingerygamer** [comment]
Survey of users created on moving from (large to small) to (small to large) search radius.

**Comment by Gingerygamer** [comment]
Nevermind, wrong task.

**Comment by Captainkirkdawson** [comment]
Example.
In F1 the initial search results showed the origin of the surname.  In F2 search results show the deceased person with a surname, whether it be their surname or a relative's surname. Researchers may accept this as the defining result, as only on checking the detail will it be clear whether the surname entered is that of the deceased, or that of a relative, or both. It surely should not be assumed that the surname of the deceased is that of the relative? It usually is, but we should not make assumptions. Perhaps the help info could make this clear.

**Comment by Captainkirkdawson** [comment]
The search results provide a minimal sets of fields. All fields are shown in the detail.
Question is the minimal set too small? What should be added IF ANY.  All is NOT a viable answer.

**Comment by edickens** [comment]
FR1 says which field it has found.
    
     
    
    This can be found in FR in the Detail, but not easy when looking for
    someone in a long list.
    
    E
    
    

    On 17/06/2016 14:43, Kirk Dawson wrote:
    
    
      Example.
        In F1 the initial search results showed the origin of the
        surname. In F2 search results show the deceased person with a
        surname, whether it be their surname or a relative's surname.
        Researchers may accept this as the defining result, as only on
        checking the detail will it be clear whether the surname entered
        is that of the deceased, or that of a relative, or both. It
        surely should not be assumed that the surname of the deceased is
        that of the relative? It usually is, but we should not make
        assumptions. Perhaps the help info could make this clear.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by edickens** [comment]
As FR1?  E
    
    On 17/06/2016 14:47, Kirk Dawson wrote:
    
    
      The search results provide a minimal sets of fields. All fields
        are shown in the detail.
        Question is the minimal set too small? What should be added IF
        ANY. All is NOT a viable answer.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by Captainkirkdawson** [comment]
Remember this story is currently being evaluated for input from our community by our intern

**Comment by PatReynolds** [comment]
There is a lot of confusion between this story (Provide guidance on the search results) and #802  (consider more fields in Search results).  Meghan will work on #802 if she has time after completing other tasks here and on FreeCEN.



I have copied comments and actions for here to #802 (more fields) or a new story, #838 (guidance on search results).

Please add to those issue threads if I have got anything into the wrong place, or missed any points.
