### ISSUE TITLE
Remove reference to fiche reader in registration

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#395]
As nobody uses a fiche reader now, this is not needed, but keep the field

**Comment by edickens** [comment]
I have received a suggestion that having the field in the registration, with the default as True, might put off a new transcriber who would think that they have to have a fiche reader.
So keep the field, remove it from the registration form, but save it as default False.  The SC can then amend this should they find out that the transcriber does have a fiche reader.

**Comment by Captainkirkdawson** [comment]
Done as part of rewrite and reformat
