### ISSUE TITLE
Password reset on test2 encounters filesystem permission 

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#398]
*Summary*
Some of the directories under /raid-test/freereg2/users are owned by user kirkdawson instead of webserv.  When a user with an ID whose files are not owned by webserv attempts to update their password (and presumably any other user field), the update fails with an access error.  Fixing this ownership fixes the errors.

*Procedure*

*1* Request a password reset as one of the following users:
```
BobH
CLange
Chris
Hollyb
IanM
KBishop
amtarr
avrils
bat069
bommel
bonanzajellydog
brecha
british_kiwi
chrisr
d_wright
daphnewar
eggs
francisdodd
frontend_dev_transcriber
gdabnor
juliancheal
kirkdawson
lemon
norlian
petermcg
ponders64
referee65
robinsonv
rwmercer
sherlock22
sherlockthegreat
sue
suji
transcriber1
```
*2* Watch the log files for the password reset token
*3* Click the token link and change the password

*Error*

The following error results:
```
 Errno::EACCES in Refinery::PasswordsController#update

Permission denied - (/raid-test/freereg2/users/benwbrum/.uDetails, /raid-test/freereg2/users/benwbrum/.uDetails.1422548569)

Rails.root: /home/apache/hosts/freereg2/MyopicVicar
Application Trace | Framework Trace | Full Trace

app/models/userid_detail.rb:148:in `rename'
app/models/userid_detail.rb:148:in `save_to_attic'
app/models/userid_detail.rb:71:in `write_userid_file'
app/decorators/models/refinery/user_decorator.rb:37:in `save_password_and_send_notification'
```

*Work around*
I was able to get around this by logging into test2 and doing this:
```bash
 sudo chown webserv benwbrum
 sudo chown webserv benwbrum/.**
```

**Comment by Captainkirkdawson** [comment]
Problem is created when mongod-development is run as a user instance rather than as a service.
