### ISSUE TITLE
Handle double-barrelled surnames

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#40]
Previous discussions have talked about stopwords for "de la", and other particles when transforming complex surnames, but at minimum we need to deal with the surnames themselves.  Andy writes:

    A search on LLEWELLYN gives no results but a search on LLEWELLYN-LLEWELLYN finds the record:
     
    Rupert Eryron Douglas Tudor LLEWELLYN-LLEWELLYN (Baptizee) 	William Tudor LLEWELLYN-LLEWELLYN (Father)
    Alice Gertrude LLEWELLYN-LLEWELLYN (Mother) 	Baptism 	21 Sep 1892 	SOM

**Comment by Sherlock21** [comment]
Sean
What is this the duplicate of please?
so we can see when its been fixed and tested?

ericb

**Comment by dougkdev** [comment]
duplicate of #219
