### ISSUE TITLE
Update to Ruby 2

### ISSUE THREAD

**Issue by juliancheal** [FreeUKGen/MyopicVicar#400]
Updated Refinarycms, Refinarycms-authentication gems from 2.1.1 to 2.1.5, and dragonfly to 1.0.7.
To fix http://osvdb.org/show/osvdb/110439

**Comment by Captainkirkdawson** [comment]
Unfortunately this will not install.

babosa 1.0.2 which appears to be part of this requires ruby 2.0.0 or greater.

**Comment by juliancheal** [comment]
Oh no, what version of Ruby are we running on the server?

**Comment by Captainkirkdawson** [comment]
1.9.3

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by juliancheal** [comment]
This really shouldn't have happened if Refinary was following SemVer, as it was just a bug fix. Changing to a breaking version of babosa is very annoying.

I'll just check what version we can run, while still fixing this security issue.

**Comment by Captainkirkdawson** [comment]
Can I suggest you remove the commit until you find a solution; would not want it pulled into the servers by accident.
