### ISSUE TITLE
Redesign Batch Update Process

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#401]
The current batch update process is a simple batch delete/process new/ batch add new,

This was adopted since the average batch size was under 1000 and that the time taken to determine if a record should be updated was approximately the same as would be taken in simply replacing it.

Recent experience with incremental updates to the data base has shown that there are many batches that exceed the average size by an order of magnitude. There are many batches of over 20,000 records that are being updated on a regular basis. The largest seen to date is 30,668 records. 

Because of the number of indexes we use to optimize the search performance, the update of such a batch leads not only to the deletion and reinsertion of 61,000 entry/search records but the deletion and insertion of 2,000,000 index entries. A process that takes well over an hour of wall clock time doing disk i/o.

A redesign to update only those records that are changing is required. Perhaps we need to keep a digest of the actual record with the record and compare the incoming record with that and only process those that are changed. This will significantly reduce the disk traffic.

**Comment by Captainkirkdawson** [comment]
Have now found one batch with over 48,000 records.

**Comment by edickens** [comment]
Kirk,
      
      Would it help if I tell CCs never to update these large files but
      start new ones?
      
      E
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 02/02/2015 17:01, Kirk Dawson wrote:
    
    
      Have now found one batch with over 48,000 records.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Absolutely!
Why they are is beyond me. Our recommendation always used to be 2000.
Uploading 48000 is insane IMHO.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
defending the big file creators, since I have some up to 10,000 records, If one gets a copy of someone else's transcription with permission to put up onto FreeReg, then I see logic in keeping it all in one file.
And in F1, it did not create the problems we have here in FR2, did it? Don't the present issues only arise form the way we have created to updating process? - which the ordinary transcriber and most of the CC's are in total ignorance of anyway.

What about the situation of one of the big files being updated to correct an error that gets found? it would be kept as the same file and just reloaded. with all the timing issues that bother you now.

So, why not carve up big files into the 2000 max records that you request, now, as a once off job. Save everyone all the hassle in future when all have forgotten this debate?

**Comment by edickens** [comment]
Hi EricB,
      I don't think it matters too much if someone does the occasional
      correction and upload of a large file.  The problem is worse if
      someone is working on it and uploading at the end of each
      day/session.  This will create a 10,000 record update every time
      and all but the last few will be the same.
      EricD
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 03/02/2015 13:04, Sherlock21 wrote:
    
    
      defending the big file creators, since I have some up to 10,000
        records, If one gets a copy of someone else's transcription with
        permission to put up onto FreeReg, then I see logic in keeping
        it all in one file.
        And in F1, it did not create the problems we have here in FR2,
        did it? Don't the present issues only arise form the way we have
        created to updating process? - which the ordinary transcriber
        and most of the CC's are in total ignorance of anyway.
      What about the situation of one of the big files being updated
        to correct an error that gets found? it would be kept as the
        same file and just reloaded. with all the timing issues that
        bother you now.
      So, why not carve up big files into the 2000 max records that
        you request, now, as a once off job. Save everyone all the
        hassle in future when all have forgotten this debate?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Duplicates 288
