### ISSUE TITLE
CSV File Download - Line Endings

### ISSUE THREAD

**Issue by EmJayFry** [FreeUKGen/MyopicVicar#402]
csvfiles_controller#download

File downloads to PC but without the Windows line-endings of CRLF. Unix LF endings are used.

**Comment by Captainkirkdawson** [comment]
The down loader does no processing of the file just passes it to the browser

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by EmJayFry** [comment]
On 2015/02/04 02:54 AM, Kirk Dawson wrote:

> The down loader does no processing of the file just passes it to the browser

I have since explored the possibility of any ramifications and discovered that 
despite the downloaded files not having the conventional, Windows line-ending of 
CR+LF, WinREG is quite happy to read the files. Of course, when WinREG re-saves 
a file, the LF line-endings are replaced with CR+LF.

Forget the issue :-)

-- 
Regards,
Mike Fry (Jhb)

**Comment by Captainkirkdawson** [comment]
And when they get saved by the server they get stripped again. The fun of
different platforms.


Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
