### ISSUE TITLE
Case sensitive userids

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#404]
Unfortunately we again have case sensitive issues between Fr1 and FR2 due to the earlier code written for creating userids.

**Comment by edickens** [comment]
Is this because we didn't delete the
      unused ones and their files in FR2?  In FR1 files were moved and
      the duplicate UserID deleted.  I have been checking that no new
      duplicates have been created in FR1.
      E
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 04/02/2015 03:49, Kirk Dawson wrote:
    
    
      Unfortunately we again have case sensitive issues between Fr1
        and FR2 due to the earlier code written for creating userids.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
No it was when FR2 was downcasing Userids that you created.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Case sensitive userids and files deleted in consultation with EricD
