### ISSUE TITLE
Access to old syndicates

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#405]
As a result of the creation of the new syndicates. There syndicate coordinators have no access to the files created under the old syndicates

**Comment by edickens** [comment]
So do I need to check all UserIDs to
      see that they belong to a valid Syndicate?
      I thought that all single county syndicates should be OK, and I
      have done some spot checks, and merged multi-county, such as Mary
      Korna's Cambs, Beds and Hunts will require correction.  But
      looking at the UserIDs, these merged syndicates look to be OK.
      So does your conversion program need to refer to the UserID to
      find the Syndicate?  Or is something else wrong?
      Just let me know what you want me to do.
      E
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 04/02/2015 03:52, Kirk Dawson wrote:
    
    
      As a result of the creation of the new syndicates. There
        syndicate coordinators have no access to the files created under
        the old syndicates
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Do nothing until asked. The conversion process is unaware of the changes
made to syndicate structures. It was flagged at the time but got lost in
the mass of change requests. reflagging so it does not get lost again. I am
out of time to do anything. Does not affect  FR2.1.1

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
No longer relevant
