### ISSUE TITLE
Need for an incremental delete to compliment the incremental update

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#406]

**Comment by edickens** [comment]
What happens if a file is deleted in
      FR1?  We have found a duplicate and one of the versions will get
      deleted.
      E
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 04/02/2015 03:53, Kirk Dawson wrote:
    
    
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
When a file in FR1 has been deleted eg coordinator has moved it then it no
longer exists in FR1. For consistency it needs removing from FR2. Currently
we add and modify we do not delete

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Have you deleted all files before the
      present update?  If not, there could be a few still hanging
      around.  Not really a problem, but just something to look out for.
      E
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 04/02/2015 14:19, Kirk Dawson wrote:
    
    When a file in FR1 has been deleted eg coordinator has
      moved it then it no
      longer exists in FR1. For consistency it needs removing from FR2.
      Currently
      we add and modify we do not delete
      
      Kirk Dawson
      Fairmont Hot Springs, B.C.
      V0B 1L1
      
      On Wed, Feb 4, 2015 at 5:44 AM, Eric Dickens
      <notifications@github.com>
      wrote:
      
      >
      >
      >
      >
      >
      > What happens if a file is deleted in
      > FR1? We have found a duplicate and one of the versions will
      get
      > deleted.
      > E
      > _____________________________________
      > Eric J Dickens
      > FreeREG Chairman
      > On 04/02/2015 03:53, Kirk Dawson wrote:
      >
      >
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
<https://github.com/FreeUKGen/MyopicVicar/issues/406#issuecomment-72848382>
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Developed and tested once
