### ISSUE TITLE
Define "Launch" F2 Version 1

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#412]
What's involved here?

**Comment by benwbrum** [comment]
Ben says: Rebuild from CSV using new files and changes to search engine algorithm

Kirk says: Get the system deployed on a multi-server production environment

**Comment by edickens** [comment]
We said that "Launch" is when we let
      the search go to the general public and put a comment in the FR1
      header to tell people about FR2.
      
      So opening to Transcribers is not "Launch".
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 04/02/2015 16:19, Ben W. Brumfield wrote:
    
    
      Ben says: Rebuild from CSV using new files and changes to
        search engine algorithm
      Kirk says: Get the system deployed on a multi-server production
        environment
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Agreed that is my preferred definition.

The a multi-server production environment is a necessary step. Once there
launch can be very shortly there after.

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by DarrenWright** [comment]
Agreed
