### ISSUE TITLE
Activate the banner advertisement

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#414]

**Comment by edickens** [comment]
In FR1 we entered <!-#exec cgl="/cgl/banner.pl"-> into each page.
I appreciate that this is a Perl program, but it will integrate FR2 with the existing income and should perhaps be used until the other projects are closed down.

**Comment by juliancheal** [comment]
Would be good to see what's in banner.pl is this available anywhere? As just entering that won't work.
