### ISSUE TITLE
Prepare for FreeBMD2

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#418]
I have been asked why we do not have the same search options as FreeBMD, and we will need these when FR2 is modified for FB2.

**Comment by edickens** [comment]
You can see all the options at http://www.freebmd.org.uk/cgi/search.pl and the one that I was asked for in FR2 is the Spouses First name.

**Comment by Captainkirkdawson** [comment]
I have no idea what this means or what is required. Proposer needs to state an explicit requirement
