### ISSUE TITLE
UCF search support

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#42]
Eric B writes:
BenB

Another thing that is not picked up...

Actual record says:
Marriages 30 apr 1715 Norfolk.
James Che*rin + Mary Ricks.

Where in the protocol the * stands for 1 or more chars. are not readable

If I search for a surname say CHEERIN within the year of 1715 and tick fuzzy, it is not included. als though the following list is returned:-

**Comment by benwbrum** [comment]
The second exampe, `John [_othergill]` is actually incorrect UCF.

**Comment by benwbrum** [comment]
UCF handling for forenames with square-bracket notation (but no wildcards) is complete.  I'd appreciate @Sherlock21 or @edickens having a look over the cases I'm testing:
```
Test case # 0: William should match queries for William
Test case # 1: [M_]ary should match queries for Mary
Test case # 2: Mar[gy] should match queries for Mary
Test case # 2: Mar[gy] should match queries for Marg
Test case # 3: [A_][n_][n_] should match queries for Ann
Test case # 4: [T_][h_][o_][m_][a_][s_] should match queries for Thomas
Test case # 5: Eli[sz]abeth should match queries for Elisabeth
Test case # 5: Eli[sz]abeth should match queries for Elizabeth
Test case # 8: eli[z_]abeth should match queries for Elizabeth
Test case # 11: [john] should match queries for John
```

Note that test case 11 is not valid UCF.  I'm trying to handle common-but-invalid UCF correctly in the software rather than to stand on principle.

**Comment by Sherlock21** [comment]
Your list of options for what is returned in each example does fit with what i would expect - i.e. I cannot think of any other sensible options for [M_]ary than Mary and so on down the set except for item 3.
Where [A_][n_][n_] means any three letter name of course - so could Ben or Tom or Jan or Pat and many others not satisfy this one?

**Comment by Sherlock21** [comment]
And that means you are on a hiding to nothing!! 

So should we veto that type of usage? and say: "only 2 UCF sets in any one name" in order to get it done in your Search Processing?
