### ISSUE TITLE
Populate search date from extrapolated postion in record

### ISSUE THREAD

**Issue by juliancheal** [FreeUKGen/MyopicVicar#424]
Where there is no year date or only a partial year date. We can extrapolate a guestimate of the date from it's position in the register.

**Comment by Sherlock21** [comment]
is there any background to this matter please?
are you referring to the Parish Register transcriptions data? or to some software data stamp  elements?
Seems a bit iffy to me as far as the integrity of the data is concerned

**Comment by Captainkirkdawson** [comment]
Only if there is a record number in the register

**Comment by Captainkirkdawson** [comment]
I really do not believe this is feasible except for records post 1837 when they are from a numbered register

**Comment by edickens** [comment]
I agree with Kirk.  But should we have a new field which is "Assumed 
Year" to differentiate it from TWYS dates?  If so, then in due course 
CCs could enter this information just for those entries which have no 
date at all.  In most cases it is possible to get to the nearest 10 
years, which is better than nothing.

EricD

_____________________________________
Eric J Dickens
FreeREG Chairman
