### ISSUE TITLE
Informing researchers when there is a server outage

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#437]

**Comment by edickens** [comment]
Can we create a single screen to say "The website is being upgraded and is not available.  We apologise for the loss of service.  It may be a day or more before we are back, so please be patient.  The website will return to this website address."

**Comment by Captainkirkdawson** [comment]
Tough to do when there is no server

**Comment by Captainkirkdawson** [comment]
Do not believe this to be a real requirement when we are running with 3 servers
