### ISSUE TITLE
What is a Register

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#439]
There is a difference of opinion as to what constitutes a "Register"

**Comment by edickens** [comment]
We need to be clear on what is a Register since that will determine how work is allocated to transcribers and signed off as Completed.
My view is that it is the same as a Register Book which the church has used.  The early ones contained a mixture of BA, MA and BU and so are known as General Registers.  More recently churches kept three pre-printed books running for BA, MA and BU.
If a register is very large, or it is a transcription where the break by register is not known, then we should break the data into sensible chunks and call these separate registers.  Or should these registers be broken into Batches.  At present a Batch represents a transcribers work of up to 2,000 entries,  so this is not really the best way to break up a large register.  So I suggest that some flexibility of definition is needed depending on the source.
EricD

**Comment by Captainkirkdawson** [comment]
As currently implemented a register is a register type. ie. a register is one of the accepted register types. All uploaded batches are part of a register (type).
As part of the RAP a register could have many books and a book can have many chapters and a chapter can have many sections and a section many images.

**Comment by benwbrum** [comment]
I'd like to get clear on what the goals of this definition are.  From discussions during last week's meeting, it seems like we're talking about a few different things:

1) What is a register?  
2) How will work be allocated to volunteers by coordinators?
3) How do we connect the images in the image server to the application, so that volunteers can see the registers which are available for them to work on.

I'm starting by focusing on 3, which I gather is the biggest technical issue.

**Comment by edickens** [comment]
Ben,
    
    The situation at present in FreeREG is that we do not have a
    "Register Record" grouping of entries.  We have a "Register Type"
    which has the name "Register" quite often.  This has the facility
    for a range of years.  It is designed for example to say that there
    exists within a Church within a Place a Register, say the "Parish
    Register" which we are transcribing.  The start year will in most
    cases be the year when the Church was dedicated and the end year
    will be empty if the Church is still there.  BUT, and this is the
    problem, the Church's actual Parish Register is very likely to be
    held in a number of books.  Each book is known as a Register. 
    Perhaps we should call them "Register Books" and to differentiate
    them from "Register Type".
    
    Then we come to breaking the "Register Book" into smaller sections
    for allocation to Transcribers.  Each book can contain thousands of
    entries.  The books are on the image server as pages, which can be
    just two or hundreds of entries.  We allocate a series of images to
    the transcriber.  They then create batches which need to be
    associated with the "Register Book" which needs to be associated
    with the "Register Type".
    
    I don't want to go through the process of introducing another layer
    of record grouping, so we need to discuss if the Batch Name could be
    the link.  For example, the present image names are something like
    "SSX-Albourne-BA-1813-1900-226-1-2-1_00077.jpg" where SSX is the
    County, Albourne is the Place, BA says that it is a Register of
    Baptisms (BA, MA and BU are usually different books as they are in
    different pre-printed formats), 1813-1900 are the years coved by
    this "Register Book", 1-2-1 is usually the microfilm number where a
    Register Books is more than 80 pages, 00077 is the image sequence
    number, often the Page Number within the Register Book.
    
    But I am not saying how this wants to be programmed and we need to
    consider the other projects.  FreeBMD has Year Quarters with pages,
    and FreeCEN has Place books, I think broken into Districts.
    
    So your 3) is not much use until we know what entry on the
    Place/Church/Register Type will hold the link to the group of
    images.  Individual entries could link to a Page of a Register
    Book.  I think linking to an entry within a page/image will be very
    difficult, especially with the old handwritten books.
    
    I hope that is not too confusing, but I do suggest that before you
    do anything we agree on how the database, including the images, will
    be structured.
    
    Regards
    
    Eric
    
    
    On 21/07/2016 13:15, Ben W. Brumfield
      wrote:
    
    
      I'd like to get clear on what the goals of this definition are.
        From discussions during last week's meeting, it seems like we're
        talking about a few different things:
      1) What is a register?
        
        2) How will work be allocated to volunteers by coordinators?
        3) How do we connect the images in the image server to the
        application, so that volunteers can see the registers which are
        available for them to work on.
      I'm starting by focusing on 3, which I gather is the biggest
        technical issue.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by Sherlock21** [comment]
All the conversation so far is centred on Work being ALLOCATED by CC's.

But don't forget that there are lots of other contributors who have their own sources, and will contribute their own Transcription files.

Are your suggesting they won't be able to do that in future?

**Comment by edickens** [comment]
Not at all.  All the existing uploads will stay.  The main problem
    will be that the RAP may not show what is in progress for those not
    using the image server, where we know what has been allocated and
    hence what is in progress.  So, just thinking aloud at present, we
    will need some means for the SC to indicate that a "Register" is
    being worked on and so if we get images from elsewhere we do not
    duplicate work, or spend time trying to obtain these images. 
    Ideally we need to know what everyone has access to (hence is
    "available") and so what will eventually be transcribed.  We can
    then tell where the gaps are and can try to get those images.
    
    E
    
      On 22/07/2016 08:07, Sherlock21 wrote:
    
    
      All the conversation so far is centred on Work being ALLOCATED
        by SC's.
      But don't forget that there are lots of other contributors who
        have their own sources, and will contribute their own
        Transcription files.
      Are your suggesting they won't be able to do that in future?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by Captainkirkdawson** [comment]
Please review #68
