### ISSUE TITLE
Wordiing of confirmation email to SCs

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#446]
The wording of the final registration email to SCs is a bit abrupt.

**Comment by edickens** [comment]
Now that FR2 sends the final registration email to SCs, Jo (LAN) has commented that the final sentence is a bit abrupt, and I do agree with her.
The present wording is e.g. 
"Dear Joanne;
The registrant Cheryl Harding at freereg.edickens+charding@gmail.com has confirmed their email address and registered a password with FreeREG using an userid of charding.
They are now your responsibility
The FreeREG Team"

Jo suggests it should be softer, so I think that the final paragraph should be "'They are now a member of your syndicate."

**Comment by Captainkirkdawson** [comment]
I believe this to have been fixed

**Comment by edickens** [comment]
Yes
