### ISSUE TITLE
Film/Image numbers not showing

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#447]
After a search the detail record does not show the Film/Image number

**Comment by Captainkirkdawson** [comment]
Could you please provide a search and result we can use for testing this?

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
William Skynner, bap 1821 Kent, Chatham
    
    But it is recent and does not come up in FR1.
    
    
    
    E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 14/04/2015 03:40, Kirk Dawson wrote:
    
    Could you please provide a search and result we can
      use for testing this?
      
      Kirk Dawson
      Fairmont Hot Springs, B.C.
      V0B 1L1

**Comment by Sherlock21** [comment]
Kirk & Ben
You can use this file: its one of my transcriptions.

 ericb/WRYDEWBA9.csv 
The records are in FR2.
a copy is attached . county = WRY. place = Dewsbury if you need to do a search
If you need a FR2 search, pick a record from this file, and do a Search - then you have all you need

**Comment by PatReynolds** [comment]
@edickens is this still a live issue?

**Comment by edickens** [comment]
I think this needs to be reviewed after V1.5.  The system may change.  And we may be able to have a routine to show images to researchers if we have permission.

**Comment by PatReynolds** [comment]
Ty.  1.6 seems the right place for it.

**Comment by SteveBiggs** [comment]
I agree to leave for 1.6, but whether or not we can show images, this information should be shown in the search detail so that the researcher knows where to look up the original fiche.
