### ISSUE TITLE
Make Registration response a hyper link

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#448]
After first entry of details for registration a message is sent to the SC.  A hyper link for the reply would be useful.

**Comment by edickens** [comment]
Kirk,
After today's exchange about a hyper link on the MOTD can you do it here as in this example...
 Dear Paula;
Welcome.
To register as a transcriber for FreeREG with a userid of paty. You need to follow the link below or paste a copy into your browser address window to set your password to something only you know.
http://freereg2.freereg.org.uk/refinery/users/password/edit?initial=true&reset_password_token=uWWBSgLyNdWsse9xBzkB

At present we have to copy and paste.
E

**Comment by Captainkirkdawson** [comment]
I believe this to have been fixed
