### ISSUE TITLE
Merge county changes in to master

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#456]
We need OptGroup for country and alphabetical within them

**Comment by edickens** [comment]
Do this after FreeREG1 has closed down.  It is important the FR2
    works like FR1.  The mistake I made over the year filter!
    E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 16/04/2015 16:22, Ben W. Brumfield
      wrote:
    
    
      We need OptGroup for country and alphabetical within them
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
This is ready to deploy
