### ISSUE TITLE
Reduce overnight updating

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#460]
Reduce the processing by omitting any file with errors

**Comment by edickens** [comment]
Cathy has made a good suggestion.  If the transcriber forces an error then the file is marked by FR1 as "with errors".  If FR2 then skips those marked with errors, they will not need to be processed.  The transcriber will remove the error when they have finished and so the file gets just one update.
And that is the principle that I have proposed (can't remember the story number now but will be V1.3) where I suggest that when we get to loading directly into FR2 a transcriber has to set a flag in the Batch or Register Records to say "all OK" and only then is the file processed.  Until then it is just saved for security.  This will save a lot of processing when transcribers upload directly as you could get 300 people uploading files each one up to three times a day as they save their work.  So the "all OK" marker would avoid any indexing - just do validation - until the final release of the work.
E

**Comment by edickens** [comment]
There has been a lot of debate amongst transcribers about this and I now have a new - and simple - proposal.
Most, say 90%, of the traffic is just backing up and the files are not ready and have not been checked, so should not be used to update the database.  So files should not update the database every time they are amended.  If the file has been amended and it has been two weeks since FR2 was last updated with the file, then an update takes place, otherwise the file is ignored.  This should just be a simple date check in the existing system.
This process will also be needed when we get to the stage of uploading directly into FR2.  At that time transcribers may upload a file a number of times every day so the whole system would grind to a halt.  By ignoring the file for two weeks, amended files would only have the indexes created once a fortnight.
In the final version of uploading directly into FR2, there could be a marker saying "Complete" and only then would the database indexes be updated.
If validation could be done daily that would be a bonus and allow for errors to be corrected in a timely fashion.
E

**Comment by Captainkirkdawson** [comment]
Guess I feel more like  DaveM everyday with being provided to address
issues.
Makes  no sense to me. We are supposed  to be getting  away from a file
based system to a record  based one.

**Comment by edickens** [comment]
I agree with you Kirk.  Online data entry record by record is the 
ultimate goal.  But even then transcribers will work in batches (or 
Registers) since they need to go back and check their work or fill in 
gaps where the writing was difficult to read.
I was just tying to find a quick and easy stop gap for the updating 
problem, which will get worse when people upload direct into FR2 before 
online data entry is ready.
E

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by benlaurie** [comment]
On 18 April 2015 at 13:09, Eric Dickens <notifications@github.com> wrote:

> I agree with you Kirk. Online data entry record by record is the
> ultimate goal. But even then transcribers will work in batches (or
> Registers) since they need to go back and check their work or fill in
> gaps where the writing was difficult to read.
> I was just tying to find a quick and easy stop gap for the updating
> problem, which will get worse when people upload direct into FR2 before
> online data entry is ready.
>

What is "the updating problem"?

**Comment by edickens** [comment]
It takes around two hours of flat out processing just to do the
    files that have been uploaded in one day.  That is because the whole
    file is processed when perhaps 10% or less of the records may have
    changed.
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 18/04/2015 14:28, Ben Laurie wrote:
    
    On 18 April 2015 at 13:09, Eric Dickens
      <notifications@github.com> wrote:
      
      > I agree with you Kirk. Online data entry record by record is
      the
      > ultimate goal. But even then transcribers will work in
      batches (or
      > Registers) since they need to go back and check their work or
      fill in
      > gaps where the writing was difficult to read.
      > I was just tying to find a quick and easy stop gap for the
      updating
      > problem, which will get worse when people upload direct into
      FR2 before
      > online data entry is ready.
      >
      
      What is "the updating problem"?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by edickens** [comment]
I agree that we do not need to do anything until Kirk's record based update system is deployed.  This will be the same system that will be needed when transcribers load directly into FreeREG2.
If it is possible, and to work towards the final system,  can some basic validation be put in?  In particular to not process (but report) any record where the UserID does not match an Active UserID in FR2, and any Placename which does not match a valid Placename.  Church names are a bit more difficult at present, but validation will be needed eventually.  However, when we open to Coordinators we can then insist that they set up  the Church name before transcribing starts and then we can validate against it.
E

**Comment by Captainkirkdawson** [comment]
Eric

We only process records uploaded by a folder that is valid userid in FR2.

Place validation should wait until Coordinators have had a chance to
complete their clean up.

Church should wait until they have had time to enter names/and or correct
them.

We really don't what people complaining well it was there in FR1 why is it
not in FR2

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Thanks Kirk.
I've not seen a message for a folder with a file that has a UserID not 
in FR2 so I must be updating them properly.
I think the places are fairly clean now, but a good idea to wait until 
CCs have had a final check.
Churches are a long way off.
I just wanted to record the need for these validations since it cropped 
up in exchanges I have had.
E

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
You would likely see them first as having a folder but no userid in FR2

Lets give them 2-3 weeks after they get access.

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Yes, I do, but I also get an error report for UserIDs who have not 
completed registration and when I delete them from FR1 they stay in the 
daily update error list.  I think this is because they are still there 
until the next FR1 update.  I'm waiting to see what happens after the 
next update.
As for validating Places and Churches, I think we need to wait at least 
3 weeks after warning them that the validation is coming in.
E

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
This story is part of 288.
