### ISSUE TITLE
Store viewed record numbers in database

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#461]
Presently we store the viewed record number in the session cookie. Researchers have been viewing too many records for the session cookie to store and causing a system fault. A temp fix to limit the number of viewed records has been implemented. A better long term solution is to store the viewed record number in the database collection for search queries.

**Comment by Captainkirkdawson** [comment]
The viewed flag is stored in the search result collection rather than as a session field. This will enable all viewed flags to be stored as we limited the session to 10 entries so as to avoid a cookie overflow. It also enables us to access that information when we start to store a researcher search and its results. In the longer term this information could be stored against a researchers interests.

**Comment by benwbrum** [comment]
This is very interesting. Did you store a single document per user with that already have records? Or do we have a record per viewing? I can imagine either one working.

**Comment by Captainkirkdawson** [comment]
At this point each viewed search_record.id is stored in a new viewed_records array field in a search result (previously just held the search_record ids) which is an embedded document in the search query collection. Thus once we allow a researcher to save and retrieve searches we will also retrieve the records they have viewed. The next step would be to populate a new collection for a user with retrieved and viewed records. That would require us to think about what to do with te contents of that collection when a search record is changed or deleted. Going down that road would of course make rebuilds problematic.
