### ISSUE TITLE
Index selection

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#465]
If at any point we want to retire my home-grown rule-based optimizer and figure out what Mongo's cost-based optimiser is doing wrong, this is probably the thing to investigate:

http://docs.mongodb.org/manual/reference/method/db.collection.getPlanCache/

Note: a "query shape" appears to be MongoDB's phrase for what Oracle would call the query's abstract syntax tree.

**Comment by Captainkirkdawson** [comment]
This is a new comment on an old story that needs urgent attention.
When using the wired tiger with the new search date indexes we continue to see over 70 long running searches a day.
It appears that most have a record type specified in the search. But we only have a record_type index for searches without a county. All of the long running searches have had a county specified and hence those searches will have to do a document lookup

**Comment by AlexAvlonitis** [comment]
Hi @Captainkirkdawson when you have some time, could you please let me know how you identify long searches from the logs, do you enable mongo query profiler or you have another location that you gather logs and reports? I will need to identify a specific query to try and replicate the issue and see what's not being indexed or whatever the issue is.

**Comment by Captainkirkdawson** [comment]
Alex. 
We keep information on search performance in a server specific mongodb collection search_query. See the specific model search_query.rb for what we collect. The index used in in the collection
The indexes for search_record are shown in search_record.rb
We provide access to the primary server collection through the Search Performance Action available to you on login.
![search](https://cloud.githubusercontent.com/assets/2874694/21081192/a58e0f82-bf7e-11e6-857d-e4e3acab7588.JPG)

It produces a report for the current day sorted by longest running

![search1](https://cloud.githubusercontent.com/assets/2874694/21081199/ce32c928-bf7e-11e6-8f7c-a3a601c6e75f.JPG)

You can access the report directly for each server without logging in by keying the address of the specific server with the report http://www14.freereg.org.uk/search_queries/report? 
![search2](https://cloud.githubusercontent.com/assets/2874694/21081246/8796d6c0-bf7f-11e6-9c89-f91bc2c182f1.JPG)
Note www13 is colobus,www14 is drill, www15 is howler www16 is brazza and www17 is saki

**Comment by Captainkirkdawson** [comment]
Index usage on colobus for the first 11 days of December is
 "county_fn_ln_sd"	6340
 "county_fn_ln_ssd"	2841
 "county_fnsdx"	0
 "county_fnsdx_ssd"	0
 "county_ln_sd"	2528
 "county_ln_ssd"	1004
 "county_lnsdx_fnsdx_sd"	4220
 "county_lnsdx_fnsdx_ssd"	1420
 "ln_rt_fn_sd"	1215
 "ln_rt_fn_ssd"	432
 "lnsdx_rt_fnsdx_sd"	361
 "lnsdx_rt_fnsdx_ssd"	120
 "place_fnsdx_lnsdx"	2046
 "place_fnsdx_lnsdx_ssd"	853
 "place_ln"	7266
 "place_ln_ssd"	1040
 "place_ln_fn"	2814
 "place_ln_fn_ssd"	1193
 "place_lnsdx"	1607
 "place_lnsdx_ssd"	704
Total	38004

**Comment by Captainkirkdawson** [comment]
Clearly we can drop "county_fnsdx"	 and "county_fnsdx_ssd"	as they are not used

**Comment by Captainkirkdawson** [comment]
Rather than separate indexes for sd and ssd could these not be combined?
eg "county_fn_ln_sd_ssd

**Comment by Captainkirkdawson** [comment]
The majority of searches include a record type but we have only 2 basic indexes that incorporate the record type

**Comment by AlexAvlonitis** [comment]
https://github.com/FreeUKGen/MyopicVicar/commit/0e2e9abe54283fd8c8e039508f142af3294d7527
Create a separate branch "Indexes".
I removed the 2 not used indexes as you noted.
Combined the sd with ssd into one, although i'm not sure about it, as to why it was separate before (to create smaller indexed collections, instead of 1? or better targeting? )
For every sd and ssd i created an record type index as well 'rt'.

**Comment by Captainkirkdawson** [comment]
Consideration of deployment of this may be a little premature. More discussion and evaluation is required before going much further
We currently provide mongodb with a hint as to which index to use so the code that computes that hint needs adjustment to use any changed indexes. We use a hint as mongodb was initially not very good at determining which indexes to use and used the same one of all searches.
Indexes need to be deployed on a server by server basis and each index creation takes several hours so we need to be sure that we have the correct set of indexes before proceeding. BenB has also wondered if his hinting is still needed. Lets talk about at the next scrum

**Comment by Captainkirkdawson** [comment]
Proposing to evaluate a reduced number of search_record indexes; 12 instead of 18.
Adding a record_type_params to make use of the rt indexes for all as well as specific rts.
Modifying the hint algorithm to provide greater sensitivity between indexes.
Evaluating on test3. 
"ln_county_rt_sd_ssd" => ["search_names.last_name", "chapman_code","record_type", "search_date", "secondary_search_date"],
    "ln_fn_county_rt_sd_ssd" => ["search_names.last_name", "search_names.first_name","chapman_code","record_type", "search_date", "secondary_search_date"],
    "lnsdx_county_rt_sd_ssd" => ["search_soundex.last_name","chapman_code","record_type", "search_date", "secondary_search_date"],
    "lnsdx_fnsdx_county_rt_sd_ssd" => ["search_soundex.last_name", "search_soundex.first_name","chapman_code","record_type", "search_date", "secondary_search_date"],
    "ln_place_rt_sd_ssd" => ["search_names.last_name", "place_id","record_type", "search_date", "secondary_search_date"],
    "ln_fn_place_rt_sd_ssd" => ["search_names.last_name", "search_names.first_name","place_id","record_type", "search_date", "secondary_search_date"],
    "lnsdx_place_rt_sd_ssd" => ["search_soundex.last_name", "place_id","record_type", "search_date", "secondary_search_date"],
    "lnsdx_fnsdx_place_rt_sd_ssd" => ["search_soundex.last_name", "search_soundex.first_name","place_id","record_type", "search_date", "secondary_search_date"],
    "fn_county_rt_sd_ssd" => ["search_names.first_name", "chapman_code","record_type", "search_date", "secondary_search_date"],
    "fnsdx_county_rt_sd_ssd" => ["search_soundex.last_name", "chapman_code","record_type", "search_date", "secondary_search_date"],
    "fn_place_rt_sd_ssd" => ["search_names.first_name", "place_id","record_type", "search_date", "secondary_search_date"],
    "fnsdx_place_rt_sd_ssd" => ["search_soundex.last_name", "place_id","record_type", "search_date", "secondary_search_date"]

**Comment by Captainkirkdawson** [comment]
Deployed to test3 for evaluation

**Comment by Captainkirkdawson** [comment]
Thank you for your tests EricB. 

The longest search was 2 seconds for a nearby (which is to be expected).

Most were under 500 msec.

A better test would be one of the secondary servers where we can see the impact of application contention.

The 250 results is an arbitrary limit selected 18 months ago. The limit controls the amount of time a browser will spend in downloading and constructing the page it is going to display on your computer. It really does not affect the server. Given that most people are now on broadband we can likely consider increasing the limit 

BenB. Can you outline the ucf search process for me so I can integrate it with the new structure? it is many months since I looked at the code.

**Comment by Captainkirkdawson** [comment]
The indexes for search_record consume 17.4GB. 
Their average size is 1.2GB. 
The largest is 2.6GB for ln_fn_place_sd_ssd
The next is 2.1GB for ln_fn_county_sd_ssd
The index for ln_county_rt_sd_ssd, likely the most frequently usable index is 781MB

**Comment by edickens** [comment]
That is huge for 37M records.  What will FreeBMD and FreeCEN take? 
Although I know that they don't have as many indexes.

E

**Comment by Captainkirkdawson** [comment]
You cannot do a simple extrapolation. It all depends on the search options, how they are used, how the index is constructed etc etc. 
CEN has 31M search records. Very similar to REG. It has 13 indexes cf our new 14. They consume 3.5GB and have an average of 275MB. In general they only have 4 fields in an index whereas we have 6 fields

**Comment by Captainkirkdawson** [comment]
Report from EricB
result of partial dates.
The search return the right record if:-
the Baptism full date is in the seletion range
AND if its in the forms: *1833	or	* Sep 1833	or	just 1833.

Also, if there is no Baptism date then the Birth date (if present) is used instead if that is in the Select range.
AND also if its in the forms: *1833	or	* Sep 1833	or	just 1833.

IF there are both Birth and Baptism dates present, only the Baptism date is used to determine if the record is in range of the date range specified.

And in all cases, the speed of the search and results presentation is noticably faster.
So:  looks like a complete success doesn’t it.
testing done between 19:00 and 19:40 GMT on  19 Dec 2016.

**Comment by Captainkirkdawson** [comment]
Will deploy to brazza when FreeBMD build completed later this week

**Comment by Captainkirkdawson** [comment]
brazza had 10 searches at 100+ seconds on Dec 28

**Comment by Captainkirkdawson** [comment]
On 29 Dec I added the new indexes to brazza and eliminated the old ones, I activated the new indexes on the brazza server only.  Although all diagnostics showed that brazza only had the new indexes all attempts to access brazza through mongoid on brazza refused to access those indexes. Hence it appears that we cannot evaluate the performance of the new indexes on brazza.

**Comment by Captainkirkdawson** [comment]
Deployed the 12 new indexes to all production servers

**Comment by Captainkirkdawson** [comment]
Need to remove old indexes and index code

**Comment by Captainkirkdawson** [comment]
Surplus indexes removed. There are now 15.

**Comment by Captainkirkdawson** [comment]
Comparison of before and after performance
Before
![newrelic](https://cloud.githubusercontent.com/assets/2874694/21664055/5fee3c3c-d2a1-11e6-9da7-45e983238f02.JPG)
After
![new_indexes](https://cloud.githubusercontent.com/assets/2874694/21664063/72d8fe22-d2a1-11e6-8669-886ebb4e70f2.JPG)

**Comment by Captainkirkdawson** [comment]
There has also been a 10 fold reduction in the number of searches that reach the time out max of 100s from 20 per server to 2

**Comment by Captainkirkdawson** [comment]
Reduction of number of indexes has reduced impact of update_csv_processor

**Comment by Captainkirkdawson** [comment]
Code clean up to complete transition has been applied to test3 prior to deployment
