### ISSUE TITLE
Review Mongo 3 for deployment

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#466]

**Comment by sean-wood** [comment]
Is the update to Mungo DB still required

**Comment by benwbrum** [comment]
We are running a version of Mongo from 2013 or early 2014.  Since then, MongoDB has released a version 3 which should now be stable, and will likely be retiring support for the version of Mongo we're running.

So yes, it is still required as a maintenance task in the next year, though deploying FreeCEN2 and improving FreeREG2 shouldn't depend on it.

**Comment by sean-wood** [comment]
Great thanks for the quick response

**Comment by Captainkirkdawson** [comment]
We are actually running 2.6.7 on the production servers. This was released on January 2015. The last release of this version was 2.6.11 in August 2015. The latest current stable release is 3.0.6 also dated August 2015. Version 3 incorporates a new storage engine.

Of perhaps greater concern, which likely should be a separate story, is our ODM to Mongodb  which is Mongoid. We are currently using version 3.1.6 which was released on December 2013. There was a release 3.1.7 in May 2015 which had very few changes. There was a new version 4 released June 2014 which we never evaluated. It is backwards incompatible with version 3. There is a new version 5 in release candidate status. This new version will replace the internal driver Moped with the new official ruby driver for Mongodb. There will be a significant number of incompatibilities with the version

**Comment by benwbrum** [comment]
In addition to the issues Kirk raises, an upgrade of our Ruby on Rails framework will also be needed.  We investigated this in #391 and determined that it was non-trivial, important, but not urgent yet.  Rails 4.2 was released several months ago, marking the last release of Rails 5.  The next Rails upgrade will be to 5.0, at which point support for Rails 3 (which we're running) will be dropped.

**Comment by Captainkirkdawson** [comment]
This needs evaluation prior to 1.7

**Comment by Captainkirkdawson** [comment]
Requires move to mongoid 5 as a prerequisite

**Comment by Captainkirkdawson** [comment]
Once Mongoid  5 is operational.  We need to deploy Mongodb 3.2  on a development machine. and develop an implementation plan which will be first run on test3,

**Comment by Captainkirkdawson** [comment]
I think I was premature in statement about mongoid5 being a prerequisite. Have installed 3.012 on my development machine and it appears to be functional.

**Comment by Captainkirkdawson** [comment]
Mongodb 3.2 will require a new driver. 3.0 does not. 3.0.12 was released on 9 May 2016. So will restrict my current evaluation to that version.

**Comment by Captainkirkdawson** [comment]
The developers of have informed me that Mongoid 3 and 4. only officially support MongoDB up to 2.6

**Comment by Captainkirkdawson** [comment]
Installed Mongodb 3.0.12 without issue on my development machine.  Discussing with Lemon its installation on the test server.

**Comment by Captainkirkdawson** [comment]
Have installed Mongodb 3.2.7 on my development machine

**Comment by Captainkirkdawson** [comment]
Mongodb 3.2 installed on test3
