### ISSUE TITLE
Display number of searches (yesterday) in footer

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#470]

**Comment by benwbrum** [comment]
Also, display number of records:

"Yesterday 23456 searches were performed on 23452367 records.

**Comment by edickens** [comment]
When I said number of records, I was referring to the size of the
    database.  FR1 shows how many BA, MA and BU we have.  If we can say
    that "Yesterday we added nnn more entries", even better.
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 30/04/2015 15:14, Ben W. Brumfield
      wrote:
    
    
      Also, display number of records:
      "Yesterday 23456 searches were performed on 23452367 records.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by edickens** [comment]
The total records added last night shows as zero, but the update report says that a lot of records were processed.  Something seems to be wrong.   Or was the total negative?  This can happen if some duplicate files are deleted.
E

**Comment by benwbrum** [comment]
Apparently we didn't calculate stats after the update correctly. I've kicked it off my hand, so the footer is right

**Comment by Captainkirkdawson** [comment]
My mistake; had missed that the actual rake task was running as webserv and
not freereg2. Has been fixed

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
