### ISSUE TITLE
Coordinator names in the DAP

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#477]
It has been pointed out to me that the coordinator name for DBY is wrong

**Comment by edickens** [comment]
At present the header information from the FR1 PPP had been copied across to FR2 and is in the Refinery.  It is used in the heading of the DAP.  But the entry for DBY is wrong because the CC has changed.
So I suggest that I remove all reference to the CC and to anything that is date or time dependent. from the County headings.
But should the CC's name (not email and not a link) be put automatically in the header?  It is there in the FR1 PPP.
Some CCs also put in the FR1 PPP the number of records on the database for their county.  This information is not calculated in FR2, but I do use it in my Newsletter.  Not urgent, but something that will be needed and it is in FR1.
E

**Comment by Sherlock21** [comment]
I am inclined to ask the CC's whether or not they want their name in the Placename header in FR2.
Then go by the majority, and apply to all - so you would have to tell then that if anyone says NO, then its no all round as it will be automated.

**Comment by edickens** [comment]
Hi EricB,
A good point.  Perhaps we should adopt what is in FR1.  That is we show 
the CC name in the PPP header, so it should be in the DAP header.
Some CCs have a link to their email address behind their name, but I 
would suggest not in FR2.  This is because there is in FR2 the "Report a 
problem" option which finds the correct email address, and this is not 
in FR1.
If we agree with this, then I need the name put in automatically so that 
it gets updated when a CC changes.
E

**Comment by Sherlock21** [comment]
OK. That seems reasonable, and should not upset anyone.

**Comment by Captainkirkdawson** [comment]
Implemented
