### ISSUE TITLE
UserID update report problem

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#478]
The FR2  fromFR1 update is showing UserIDs that don't exist

**Comment by edickens** [comment]
This report is created daily..
There are 2035 userids and 2021 userid files
Checking they all exist
BHills85 not in the database
Bev-Sanders not in the database
FredF not in the database
Hopkin not in the database
Sarah27 not in the database
Sibrwd not in the database
boneinjalon not in the database
dharma05 not in the database
But none exist is both FR1 and FR2.  Where does this information come from?
E

**Comment by Captainkirkdawson** [comment]
Have all been eliminated
