### ISSUE TITLE
Add access to search statistics

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#480]

**Comment by Captainkirkdawson** [comment]
Search statistics are currently only accessible by entering the url in the browser

**Comment by PatReynolds** [comment]
What version should be ascribed to this?

**Comment by PatReynolds** [comment]
What version should be ascribed to this?

**Comment by Captainkirkdawson** [comment]
changed to 1,4

**Comment by Captainkirkdawson** [comment]
Long since done
