### ISSUE TITLE
Co-ordinators Tables

### ISSUE THREAD

**Issue by DarrenWright** [FreeUKGen/MyopicVicar#484]
The tables in the co-ordinator pages still use the basic Refinery styling.

**Comment by DarrenWright** [comment]
The tables in the co-ordinator ages still use the basic Refinery styling.   There's not particular impetus to use the standard table  from the CSS (though that would be consistent) but the Refinery Styling was the issue we got the most complaints about last time we let co-ordinators into the site. 

E.g http://freereg2.freereg.org.uk/manage_syndicates/selection?option=Review%20Active%20Members

**Comment by Captainkirkdawson** [comment]
As stated to EricD if all pages are to be restyled then I will need about 4
weeks to so do and test them all.


Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by DarrenWright** [comment]
That's fine. There's no real rush to get it done. There's no particular rush to get this release out.

**Comment by Captainkirkdawson** [comment]
Sorry, I thought there was a great of urgency to get coordinators with access to the system which is the intent of this release.

**Comment by DarrenWright** [comment]
I don't think so. There's a great enthusiasm but there isn't a pressing need.

**Comment by edickens** [comment]
Yes, it is urgent.  I'm doing a lot of fire fighting and the longer
    we delay the more work there is for Coordinators as each day there
    are more place, church and register details to sort out.
    
    It does not affect Researchers, but the "peasant are revolting" and
    the sooner we can get them involved the better.
    
    The styling of tables is cosmetic, although it will save a lot of
    scrolling and time, but we have to find out if there are any
    technical problems.  There is no point in reformatting the tables
    only to find we then need to make changes to them.
    
    Please, let the CCs in this week.
    
    Eric
    _____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by DarrenWright** [comment]
Hi,

Nothing has changed. The data is subject to the same changes as it has been
throughout the three years of this process.

Waiting four weeks to get it right is not unreasonable.

Cosmetic is important.  It's the single biggest issue that has generated
emails.

I've not noticed anyone on the co-ordinators list mentioning an urgent need
to get involved but I'm more than happy to explain why.

We shouldn't cut corners because it will only store up problems for the
future. As we've seen on numerous occasions.

Thanks

--
Darren Wright
Executive Director
Free UK Genealogy

**Comment by Sherlock21** [comment]
I am thinking that there is a high degree of Hacked Offness amongst CC's due to going nowhere.

EB

**Comment by DarrenWright** [comment]
On 11 May 2015 at 19:28, Sherlock21 <notifications@github.com> wrote:

> I am thinking that there is a high degree of Hacked Offness amongst CC's
> due to going nowhere.
>
>
>
We launched a site to the general public a few weeks ago. That's hardly
going nowhere.

**Comment by edickens** [comment]
It's your call but I am formally saying that I not at all happy.

Are you prepared to take on some of the work that I am doing to hold the 
fort?  I am very happy to forward every message I get to you. For 
example, every new UserID has to be set up in FR2 on the same day that 
they register, otherwise if they upload a file it will be reject by the 
overnight update.  You then have to record that this file has not been 
taken across and make sure that when the UserID is set up in FR2 that 
the file is uploaded again into FR1 to force it to be accepted by the 
update.

All the questions I deal with involve about an hour every day to handle 
all the problems.  I want CCs to deal with these.

E

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by Sherlock21** [comment]
As far as CC's being allowed access to get to do their routine tasks is concerned, I and they, do see it as Going Nowhere. 

As I have said before, its all back to front.

**Comment by DarrenWright** [comment]
Talked to Julian about this and he will talk  to Kirk about implementing it.
