### ISSUE TITLE
Back Button (Breadcrumbs)

### ISSUE THREAD

**Issue by DarrenWright** [FreeUKGen/MyopicVicar#485]
Throughout the co-ordinator pages there is no way to navigate back to the previous screen.

Is it possible to implement a breadcrumb?

**Comment by Captainkirkdawson** [comment]
There is. It is the Browser back button.

**Comment by DarrenWright** [comment]
It seems a bit counter intuitive. 

Elsewhere on the site we've told people not to use the back button so we're building in an inconsistent approach.

**Comment by Captainkirkdawson** [comment]
Interesting; to me it is very intuitive.
Not sure where we are telling people not to.
We did have a Back Button on every page. It was taken out because it sometimes gave inconsistent results compared to the browser back

**Comment by benwbrum** [comment]
Kirk's breadcrumb prototype looks like exactly the thing!
