### ISSUE TITLE
Add brazza server to mongodb cluster

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#486]

**Comment by edickens** [comment]
I appreciate that setting up servers is a good idea while the
    process is still fresh in your minds, but we still have a huge
    amount of programming to do.
    There are still a lot of emails flying around for me to allocate
    images on the image server and SCs having to keep records of work
    available, in progress and completed.  I want to get out of the day
    to day running of FreeREG.
    E

**Comment by Captainkirkdawson** [comment]
Completed
