### ISSUE TITLE
DAP-Previously Viewed

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#49]
EricB suggests adding previously viewed

**Comment by Captainkirkdawson** [comment]
Given current structure this is meaningless

**Comment by Sherlock21** [comment]
This feature WAS there until recently. Now today its not there.

Why delete it if it was wanted, and worked OK?
The feature is used by FindMyPast, and is one of their most user friendly features - which was the reason behind  my original request for it.

When selectively trawling through a search list of returned records, its essential to know which one has looked up the detail of, and which one has not. Else one spends no end of time revisiting the ones already reviewed. especially if there are several pages, ons one skips about following a particular first name.

I wish to request it is reinstated please.

**Comment by edickens** [comment]
We have it in FR1 as the "Number" in
      the list changes colour.  But it is not saved.  Just the current
      search shows.
      EricD
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 02/01/2015 15:41, Sherlock21 wrote:
    
    
      This feature WAS there until recently. Now today its not there.
      Why delete it if it was wanted, and worked OK?
        The feature is used by FindMyPast, and is one of their most user
        friendly features - which was the reason behind my original
        request for it.
      When selectively trawling through a search list of returned
        records, its essential to know which one has looked up the
        detail of, and which one has not. Else one spends no end of time
        revisiting the ones already reviewed. especially if there are
        several pages, ons one skips about following a particular first
        name.
      I wish to request it is reinstated please. 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
The capability was never implemented for the DAP. With the new way of entering the DAP it is meaningless. There is nothing to re-introduce. I should know I wrote the code.
The capability IS there for the search results which is what you are talking about. It has NOT been removed.
Like FR1 it is only effective for the CURRENT search. There is no memory from search to search.

**Comment by Sherlock21** [comment]
Are we all discussing the same topic?

This topic I thought was about the text "Viewed" which appears on each record, at the  RH end underneath "details", when one had looked up the details. 

Nothing to do with DAP in my request - but the issue I refer to  3 items up, is to do with the disappearance of VIEWED off the Search results record list, when one looks up a detail. Is that not what you have zapped now? If not,I will have to raise that one as an issue.

**Comment by Sherlock21** [comment]
I accept its my mis-undersatnding of topics. Sorry. New fault issue raised for what I am on about.
