### ISSUE TITLE
Standardisation of Church Denominatoin

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#490]
When CCs are tidying things up they can put in the Church Denomination

**Comment by edickens** [comment]
It would be ideal to have a pick list to standardise this for technical researchers.  But new denominations will come along so a manager amendment facility is needed.
How about this to start...
Church of England, Anglican, Baptist, Independent, Congregational, Methodist, Roman Catholic, Jewish, Quaker, Presbyterian, Unitarian, Moslem, Community Cemetery, Unknown, Latter Day Saints, Christadelphian, Evanjelical, Jehovah's witness, Christian Centre, Moravian, Zion, Salvation Army, Amani Centre, Gospel Centre, Free Church, Christian Bretheren, Buddhist Centre, Mission, Swedenborgian, First Church of Christ Scientist, Greek Ortodox, Russian Ortodox, Epsicopal, Welseyan, Calvanastic Methodist.

**Comment by Captainkirkdawson** [comment]
This is identical to 376 which had been agreed as due for 1.5

**Comment by edickens** [comment]
I thought it was there but could not find it.  I was looking through 
incoming.  1.5 is fine, although CCs will have to go through the 
Churches for a second time.
