### ISSUE TITLE
Format of search record detail display and its print/csv format

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#491]
Feedback that came into FreeREG1

**Comment by edickens** [comment]
Dear Sir/Madam,

 

I have had the pleasure of using your site for some years (Freereg). Unfortunately Freereg 2 has been designed by someone who does not understand the process of usage.

 

1)The objective is to glean information. This requires transferring the information for use with other software.

2)The information on Freereg 2 as presented  now requires an additional 3 operations to do that.

3)In Freereg 1 the number changes (in the left hand column) colour having selected it so that there is a visual clue as to where you are with the transfers. Nothing in freereg2.

4)The B & M & D are now mixed up which is not a friendly way to transfer the data.( with the extra processes)

5) While the typeface and size may be OK for the partial sited it could be smaller.

 

I assume the objective is to phase out Freereg. Unless the above problems are addressed it will be a retrograde step.  ( as usual with several site “upgrades” .)

 

Conclusion: Freereg2 OK for Children!

 

Regards,

 

S.Wyatt

**Comment by edickens** [comment]
I have also noticed that rather than provide a table with all fields including blanks where applicable, the report now only shows fields that contain data. This means that if you try to export a record fields will not be in the same order. I use an excel method that reads records into a “family tree” style mapping. This cannot now be used, because the fields do not appear in a consistent order. To me, the upgrade is a backward step I’m afraid.
Matthew
01603 706831
[Looks as if we could do with a "Copy as CSV" so that people can paste into spreadsheets. - E]

**Comment by Sherlock21** [comment]
Providing a csv file style of export would still have the missing fields issue, unless you take the extract before you drop the empty fields to form the display.
I would be happy to revert to the full set of fields, with them empty if no data. That may be the easier way to resolve this issue. And I do tend to have sympathy with this writer.

**Comment by Captainkirkdawson** [comment]
Include as part of  #809 flexible_csv

**Comment by Captainkirkdawson** [comment]
Propose to add  a json output as well; perhaps we provide the option to include all fields or  only those that have actual values. That gives a total of 6 options. printable, CSV, JSON each with a full or actual values.

**Comment by Captainkirkdawson** [comment]
Code integrated into flexible_csv branch.  Decided to just provide 3 options. All fields in the entries are to be included. Includied nil value fields as this means individual outputs are of identical format regardless of content.

**Comment by Captainkirkdawson** [comment]
on test2

**Comment by PatReynolds** [comment]
Good idea!

**Comment by Captainkirkdawson** [comment]
Deployed to production
