### ISSUE TITLE
Update is not recognising deleted UserIDs

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#493]
The overnight update is showing UserIDs as "Not in Database" when deleted in FR1 and FR2

**Comment by edickens** [comment]
When a UserID has been Deleted in FR1 and Destroyed in FR2, the update still thinks that it is in FR1 by reporting "Not in Database".  This report, once generated, shows up at every overnight update from then on.

**Comment by Captainkirkdawson** [comment]
No longer relevant
