### ISSUE TITLE
Releasing FR2 to CCs

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#496]
Concerns have been expressed that CCs will do more than  we want them to do

**Comment by edickens** [comment]
To avoid CCs doing more than we want them to do,  is it possible to lock out SCs while opening to CCs?  But, most are both CC and SC and use the same UserID.
So if it is not possible to lock out just SC functions, should I change all SCs to my UserID so that they then do not have SC access?  This is not difficult to do and easy to reset when needed.
E

**Comment by Sherlock21** [comment]
I agree with ED. It will be necessary to spell out in reasonable detail, what they should deal with, and by which means - eg like dealing with records which have Non Approved Place Names or Church Names; correcting Researcher- notified transcription errors.

**Comment by Captainkirkdawson** [comment]
Cannot lock out SC functions without some effort which I would rather no do
there is no easy solution.

Most of the SC functions are the same as CC functions just applied to a
different slice.  There are some that are unique that deal with the
Syndicate membership.

I personally believe we should treat them as responsible adults until
proven otherwise.


Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Agreed.  But, when the time comes, I will stress to them that we
    trust them.
    
    E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 01/06/2015 15:43, Kirk Dawson wrote:
    
    Cannot lock out SC functions without some effort which
      I would rather no do
      there is no easy solution.
      
      Most of the SC functions are the same as CC functions just applied
      to a
      different slice. There are some that are unique that deal with the
      Syndicate membership.
      
      I personally believe we should treat them as responsible adults
      until
      proven otherwise.
      
      
      Kirk Dawson
      Fairmont Hot Springs, B.C.
      V0B 1L1
      
      On Mon, Jun 1, 2015 at 1:54 AM, Sherlock21
      <notifications@github.com> wrote:
      
      > I agree with ED. It will be necessary to spell out in
      reasonable detail,
      > what they should deal with, and by which means - eg like
      dealing with
      > records which have Non Approved Place Names or Church Names;
      correcting
      > Researcher- notified transcription errors.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
<https://github.com/FreeUKGen/MyopicVicar/issues/496#issuecomment-107344955>
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.
