### ISSUE TITLE
Change sequence of Contact recipients

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#500]
At present Kirk is set to answer all Contacts - Change to reg-web

**Comment by edickens** [comment]
I get the reg-web emails so am happy to be the first to answer Contact messages.  I will forward or copy as necessary.  I do this already for FR1.
E

**Comment by Captainkirkdawson** [comment]
Have changed the message to say that you will take the lead. Will deploy tonight
