### ISSUE TITLE
Registrant selecting Syndicate

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#501]
Registrants don't seem to be selecting the correct Syndicate

**Comment by edickens** [comment]
We have had two transcribers who I think registered in FR2 themselves.  I say "think" because when I came to add them they were already there and I did not get any registration emails.
Both selected "Ayrshire-Mick Claxton" as their Syndicate.  My guess this was by default.
So should registration be made so that the Syndicate field is empty and a positive selection has to be made and they get a warning if they have not selected a Syndicate.  In this way "Ayrshire" is not the default.

**Comment by Captainkirkdawson** [comment]
There is no way that could happen. A user MUST select a syndicate

**Comment by edickens** [comment]
I will keep an eye in it, but the two people who have registered in FR2 
have selected AGY, the first in the list, I suspect by not bothering to 
look for anything different.  So the AGY SC could have to deal with 
unwanted registrations.  I would prefer the default to be "Researcher".

**Comment by Captainkirkdawson** [comment]
The first on the list is now Researcher
