### ISSUE TITLE
Remove automatic capitalisation from overnight update

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#503]
I think this story has been before but closed.  However, there are now problems.  See my comment

**Comment by edickens** [comment]
We are having a lot of problems correcting Unapproved Place Names, because the overnight update keeps changing the capitalisation to the Unapproved version when the FR1 file has the Approved version.  I don't know how many files are uploaded with the Unapproved version which is changed to Approved, but it should not happen after all the work we have put in to get CCs to tell their transcribers what to enter.
However, I understand why Kirk did not want to remove this feature as he thought it would let in a lot of wrong files and so create more Unapproved Places.  But I now think that will not happen because the Unapproved were all created, and rightly so, when we brought across the whole database.  So any old file that is uploaded will already have had the associated Unapproved place created   All that is coming across now are new transcriptions and corrections.  We have spent three years getting CCs to tell their transcribers to use the correct name, and that seems to have worked.  Also, CCs can now access the MPN and EricB can get the right Place as the Approved.  So I would like the automatic capitalisation removed for Places, not Churches.
I also think we should seriously consider the next step, which is to validate Places against the Approved MPN and not process, but report, any failures.  This will definitely stop any more Unapproved places being entered.  Validation should not be done for Churches  - yet.
The automatic capitalisation of Places is causing us more work than it saves now.
E

**Comment by Captainkirkdawson** [comment]
If we do this you need to be aware that a batch that was previously
processed may not be processed in the future.i.e. one that had been
corrected by the punctuation and capitalization code.

If we proceed in this way we should implement the rejection rather than the
acceptance of an unapproved place name.

As i a first step it would be possible to do the comparison on a case
insensitive basis



Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Understood and agreed.  Exactly what we want.  We need to identify 
batches being capitalised and get them corrected, otherwise the 
mis-spellings will continue.  You can rejected against an Unapproved 
place as well if you wish.
E

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
The selection of the Place is now 2 stage. Stage1 perfect match. Stage 2 lower case match ignoring -.' The Unapproved is still set for non matches and a message produced for the update log.
