### ISSUE TITLE
Sometimes current refinery user status is lost

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#505]

**Comment by Captainkirkdawson** [comment]
Maybe it is the password reset that eliminates the current_refinery_user status that would explain a great deal.

**Comment by edickens** [comment]
Yes.  But it should not do it as soon as the "Request a new password" is 
issued.  It is possible that the person will not reset the password but 
remember their original.  So the password should just be overwritten 
when the new one is entered.
E

**Comment by Captainkirkdawson** [comment]
The person who asks for the password reset is changed to not a current refinery user. Think my solution will be to log the person out after the request. Safest move and I know not how to better access the code

**Comment by Captainkirkdawson** [comment]
Have now forced a relogin after password reset. SC may complain but!

**Comment by edickens** [comment]
This will ensure that they have remembered their new password.  This is 
the usual procedure.
E

**Comment by Captainkirkdawson** [comment]
But it does mean that if you or SC sends out the reset for a userid then you or the SC will have to login again!!!!

**Comment by edickens** [comment]
Not a problem.  It is very rare, but does happen.  E
