### ISSUE TITLE
2500 failed Google and other Search engine search accesses a day

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#512]
We are getting at least 2500 accesses a day from the Google and other bots that appear to be "manufacturing" the search query and providing invalid parameter. These are creating a application crash/recovery each time. While the impact may be minimal it is not really a good solution!

**Comment by edickens** [comment]
Do you think that this might also happen in FR1?  It seems odd that the 
level of searches is so steady after a day one fall and then no more.  
But today, after FR1 search failed for most of the morning, I did get 
about five emails from people reporting the problem who were still using 
FR1.  I told them to use FR2 and one came back saying what a great 
improvement.  Can't they read the MOTD!
E

**Comment by Captainkirkdawson** [comment]
Absolutely

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
At least half of the failed searches  are from Mediapartners-Google web crawler which is "analyze them to decide what ads to show visitors to your site."

**Comment by Captainkirkdawson** [comment]
On July 4 there were nearly 4000 such failures. They are from "ad engines"

**Comment by edickens** [comment]
I think this is the same problem in FR1...
    
    
    This is not statistically possible.  Perhaps no real person is
    searching in FR1?
    E

**Comment by benwbrum** [comment]
This should be incorporated into #517
