### ISSUE TITLE
Add  type of registration to SC message

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#513]
The message that a SC gets says that someone has registered in their syndicate but not which syndicate.

**Comment by edickens** [comment]
If the message says which syndicate that they have selected, then the SC will know if it is to transcribe or something else.  Some people are SCs of more than one syndicate so it is useful to know which they have selected.

**Comment by Captainkirkdawson** [comment]
I am sorry but I thought you had merged all syndicates for a SC into one so
the situation you refer to does not exist

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Yes.  But I have had comments that the SC did not realise that it was a 
new volunteer.  There are some that are SC of more than one because of 
Rest of England and Training.  But in general it is one person for one 
syndicate.
I really wanted to know if the volunteer was applying to be a learner, 
an experienced transcriber, or wants to be a Coordinator. At present 
they email the SC and ask for more information before registering.  This 
is not something that the volunteer selects, but it is left to the SC to 
amend their profile after registering.
Today's registrations have come out of the blue to the SC.  Hence the 
surprise and wondering what to do.
Perhaps it is just learning and it is way ahead of where we are.
E

**Comment by Captainkirkdawson** [comment]
On Thu, Jun 25, 2015 at 4:08 PM, Eric Dickens <notifications@github.com>
wrote:

> Yes. But I have had comments that the SC did not realise that it was a
> new volunteer. There are some that are SC of more than one because of
> Rest of England and Training. But in general it is one person for one
> syndicate.
>

*So we are doing this for one person?*


> I really wanted to know if the volunteer was applying to be a learner,
> an experienced transcriber, or wants to be a Coordinator. At present
> they email the SC and ask for more information before registering. This
> is not something that the volunteer selects, but it is left to the SC to
> amend their profile after registering.
>

*Who knows their expertise; it is not available information*


> Today's registrations have come out of the blue to the SC. Hence the
> surprise and wondering what to do.
>


*But what is the difference between this and FR1 where they get emails out
of the blue. *

> Perhaps it is just learning and it is way ahead of where we are.
>


*Likely the case; but this is where you should have a volunteer coordinator
helping you out. *

> E
>
> *Personally I think you do not have enough people helping you, nor do I
have enough helping me. *

**Comment by edickens** [comment]
Yes, close this.  It is part of the learning curve.
E
