### ISSUE TITLE
Management of UserIDs

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#514]
If a volunteer does not complete registration we get left with a half registered UserID.  We need to be able to identify these.

**Comment by edickens** [comment]
When someone registers they get sent an email asking them to set their Password.  If they do not do this with 24 hours the request is no longer valid.  A SC can resend the request, so the UserID needs to remain.  But some may never register and so, like FR1, we can get lots of half completed UserID registrations.
The UserID profile needs to show which have not completed registration.
Also, a report listing uncompleted registrations, available to SC and above, would be very useful.
E

**Comment by edickens** [comment]
When a volunteer registers they are sent an email asking them to set their password.  But if they do not do this within 24 hours, then the request is no longer valid.  A SC can resend the request, so the UserID needs to remain on the database.
However, as in FR1, we will get left with quite a few half completed registrations.
So the fact that the registration is not complete needs to show on the UserID profile, and a report listing these would be very useful to SCs and above.
E

**Comment by Captainkirkdawson** [comment]
Failure to complete registration to be displayed on profile.
Action to display uncompleted registrations is available to SC and system administrator

**Comment by edickens** [comment]
Originally we decided that if someone did not complete registration
    within 24 hours that we would remove the Profile so that we don't
    get cluttered up with uncompleted registrations.
    Suggest an alternative...
    When the server deletes an uncompleted registration after 24 hours
    an email is sent to the CC with the basic information.  They can
    then decide if they want to contact the person to help them
    register, or just let it go if it is someone mucking about.  E
    
      On 15/10/2016 04:29, Kirk Dawson wrote:
    
    
      Failure to complete registration to be displayed on profile.
        Action to display uncompleted registrations is available to SC
        and system administrator
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #514: Failure to complete registration to be displayed on profile.\nAction to display uncompleted registrations is available to SC and system administrator"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/514#issuecomment-253959730"}}}

**Comment by Captainkirkdawson** [comment]
I was not aware of any agreement to delete an incomplete registration. Have never written any code to so do. Acting within the 24 hr window would be most inappropriate. It could happen for many reasons. 
I far prefer to have human beings make such decisions given that they can access the information.
We could link this to #109 with a different colour

**Comment by edickens** [comment]
Are you sure that code to delete incomplete registrations is not
    there?  It is just that there have been times when people have not
    got it done and I have said that since 24 hours had gone then they
    needed to start again and that they could use the same UserID and it
    seemed to work.
    
    But if we are not taking them out after 24 hours, then a report for
    the SC is needed so that they can tidy them up.  BUT, they
    cannot delete UserIDs at present.  They have to email me.  So we
    need to give them that Action, perhaps just for incomplete
    registrations.  E
    
      On 15/10/2016 17:33, Kirk Dawson wrote:
    
    
      I was not aware of any agreement to delete an incomplete
        registration. Have never written any code to so do. Acting
        within the 24 hr window would be most inappropriate. It could
        happen for many reasons. 
        I far prefer to have human beings make such decisions given that
        they can access the information.
        We could link this to #109
        with a different colour
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #514: I was not aware of any agreement to delete an incomplete registration. Have never written any code to so do. Acting within the 24 hr window would be most inappropriate. It could happen for many reasons. \r\nI far prefer to have human beings make such decisions given that they can access the information.\r\nWe could link this to #109 with a different colour"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/514#issuecomment-253994950"}}}

**Comment by Captainkirkdawson** [comment]
On hold pending common gateway

**Comment by SteveBiggs** [comment]
This is OBE by #1146.

**Comment by Captainkirkdawson** [comment]
Guess I have been out of the UK for too long but what does OBE mean in this
context?

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by SteveBiggs** [comment]
Overcome By Events :-)

Steve


Stephen Biggs
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
😊

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by SteveBiggs** [comment]
This can be closed as it's covered by #1146.
