### ISSUE TITLE
Figure out SEO

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#517]
Currently Google claims that robots.txt bans FreeREG2 from appearing in searches, but we're getting loads of hits from crawlers (see #512).  We need to figure out what's up.

**Comment by Captainkirkdawson** [comment]
Current robots

User-agent: *
Allow: /about
Allow: /donate
Allow: /help
Allow: /search_queries/new
Allow: /freereg_contents
Disallow: /

**Comment by Sherlock21** [comment]
I tried a Google search just now.

if i type Freereg2, google suggests I use Freereg 2. and that gives me a whole set of replies ( links)
If I insist that I want Freereg2, it does function and supply a different list ( attached.
So seems to give something either way

**Comment by Sherlock21** [comment]
I can't see where my attachement has gone to!

**Comment by Captainkirkdawson** [comment]
There was no attachment.

Best way with GitHub is to paste the image
See the instruction below on github
Attach images by dragging & dropping or selecting them.

**Comment by Sherlock21** [comment]
I did try the Drag n drop method of attaching my jpg file. but nothing appeared in the text box.

SO I tried the Attach an Image option - and again i saw no sign of anything being attached

hence - so that you had something to look at, I did the email option .

**Comment by Captainkirkdawson** [comment]
Made some changes to the robots and the meta tags (We had nothing in them). FreeREG2 now appears in a Google search for FreeREG2.
 It does not appear in a search for FreeREG.
Your server FreeREG2 site appears as the number 2. Likely we should remove.
Likely Ben can make some additional improvements

**Comment by Sherlock21** [comment]
This is what I get immediately

**Comment by Captainkirkdawson** [comment]
Sorry but what did you get?
