### ISSUE TITLE
RAP Method of recording Repository, Church, recording associated permissions, and storing permission - jpg and hard copy

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#518]

**Comment by PatReynolds** [comment]
Thoughts on what milestone to give this welcome.  It is needed for the implementation of  Open Data and for good governance (e.g. avoiding lawsuits).

**Comment by Captainkirkdawson** [comment]
Since I have no idea of the time-scale for those events I am not in a position to comment

**Comment by edickens** [comment]
I suggest adding to the Roadmap for V1.5 - E
    
    On 17/09/2015 23:04, Kirk Dawson wrote:
    
    
      Since I have no idea of the time-scale for those events I am
        not in a position to comment
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by PatReynolds** [comment]
Dalry Cemetery, Edinburgh- incoming as a transcribed set - could act as example.

**Comment by PatReynolds** [comment]
Seems to entails the creation of unique Register Book to hold repository/owner permissions, Repository, etc.

**Comment by Captainkirkdawson** [comment]
Dependant on 439

**Comment by PatReynolds** [comment]
EricB notes: This needs to be done when the images are uploaded to the images server. But it must also be possible to do this at register book level because sometimes the images are not on the images server, for example when the transcriber takes their laptop to the Records Office or Church and transcribes from the original. E

**Comment by Captainkirkdawson** [comment]
I do not believe this to be the story for defining the data model that links image to the register through subsidiary collections as discussed in our meeting on what is a register

**Comment by benwbrum** [comment]
Kirk, is the data model definition story this one?  https://github.com/FreeUKGen/MyopicVicar/issues/68

Regardless, I'm working from the gdoc and will likely be in touch on and off today.

**Comment by Captainkirkdawson** [comment]
Yes there is good material there; also see #951 where Eric and I have been chatting about aspects of it
I am around working on colobus

**Comment by PatReynolds** [comment]
See also /525
