### ISSUE TITLE
Overnight update files "Not changed"

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#519]
The test for "Not updated" is seldom used and causes extra work

**Comment by edickens** [comment]
The report that a file has not been changed in the overnight update has appeared very infrequently this last week.  I think it is not needed.
There are two advantages in removing this test.  It will reduce processing, but better still, files will not have to be amended with a Space to force an update.  The need to upload an unchanged file occurs when there is an error in the FR2 Place Names List, and when that has been corrected, all that is needed is for the file to be uploaded again and then, because of the last uploaded date change, it will be processed.  Now it has to be edited as well.
I think any extra processing will be out-weighted by the ease of forcing an update.
E

**Comment by Captainkirkdawson** [comment]
This proposal would cause difficulties in the restart of a failed update
