### ISSUE TITLE
Write New WinFREEREG

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#521]

**Comment by AlOneill** [comment]
If the name WinFREEREG is not set in stone:

The name FR, as used in our logo is (now) capitalised as FreeReg. I suggest it would therefore make sense to use WINFreeReg as the name of the app.

WinFreeReg does not quite do it as it does not distinguish between the two components in the name.

WINFreeReg also has the advantage of being more readable than WinFREEREG, especially when trying to read back something you have typed -- there are just too many consecutive uprights to decipher comfortably.
