### ISSUE TITLE
Review Roadmap

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#523]

**Comment by Captainkirkdawson** [comment]
Need to reformat last paragraph

**Comment by PatReynolds** [comment]
What are the 'data changes' mentioned in the first paragraph?

**Comment by Captainkirkdawson** [comment]
Making changes to the actual meta data contained by the database. eg Who are the coordinators, who are the transcribers, what is a persons role in FreeReg. What are the Register Types. What are the religious institution denominations. What are the locations of the places etc
