### ISSUE TITLE
Document contact system

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#526]
The list of contact reports is getting huge and we do not know if they have been actioned.

**Comment by edickens** [comment]
I have to admit that I probably have not been using the system properly, but it is too easy to do that.
I get emails when there is a Contact for me.  I either answer it by "Reply" or forward it to the person involved.  In both cases the Contact report remains in the list and there is no indication as to whether I have answered it or the person to whom I have forwarded it has received and actioned it.
I don't know the solution to the problem, but I suspect that a lot of messages are going unanswered, but I have no way of checking.
E

**Comment by Sherlock21** [comment]
I must admit that i just react to emails Only. and use "Reply" . only newly initiated messages from me do i just write out - obviously
So I could well manage without this feature.

**Comment by Captainkirkdawson** [comment]
This is yet another example of the need for a documented "procedure" for the management of contacts.
Any person when they have "resolved" the contact have to delete it. The system has no way of knowing when a human being completed whatever was required.
You need someone who "manages" the process and looks after outstanding contacts.

**Comment by PatReynolds** [comment]
Eric D, do you think this is something that Eric the recent volunteer could take on?

**Comment by edickens** [comment]
I would have thought it needed programming if it is integrated into FR2.
I run two mail groups, one for transcriber and one for Coordinators.  I 
invite every new registrant to join and most do. There are now 349.  
They can manage their own emails and how they want to receive them.
E

**Comment by Captainkirkdawson** [comment]
What is needed  is a documentation of the process for the management of the Contact Collection. How it works and what people are to do with it.
Pat I agree fully that a person who does document is exactly what we need.
