### ISSUE TITLE
Cookie choice - quick fix

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#527]
By a date (tbc - possibly 1st September 2015) we have to have cookie choice on our website, or our Google income stream will stop (it's around 90% of our funding).

There are some options here https://www.cookiechoices.org/

I've only looked at the Cookie Consent Kit, which is a quite basic option (consent/don't consent).

I can tweak the EU model text, if told what cookies we use, and which categories they are in.  As in this example: http://www.kwik-fit.com/cookies.asp

**Comment by Captainkirkdawson** [comment]
We use the following cookies on FR2. 

freereg2_session. Set for all users. Sole use is to direct the user to the same server for searches. Required for revising searches. If disabled results from searches will be inconsistent. Exists only for the session.

_Myopicvicar. Set for all users.  General usage is only to store control information for the search results. For members it is used to personalize their functions and ensure correct navigation. Life time is 2 hrs to enable users to resume activities after navigating away from the website.

Administrator. Only set for members.Ensures that member operations are directed to the master server. Lifetime is session.

_ga and _gat and related cookies from Google analytics

If you provide appropriate text we will add as more information
