### ISSUE TITLE
Scroll bar - IE browser issue (Anna)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#530]
When I need to use the scroll bar, I can’t use an IE browser – I must use Chrome or it doesn’t work!

**Comment by Captainkirkdawson** [comment]
This may be an issue with old versions of IE; it is not an issue with modern supported versions.
I do not believe this to be a bug that needs fixing

**Comment by PatReynolds** [comment]
Originator of the issue did not respond with version number.  I have let her know it is fixed, and said she can contact me if still having difficulties.
