### ISSUE TITLE
History feature issue in Chrome (Anna)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#531]
When I want to retrace my steps (in Chrome) by using the History feature, it just brings up a blank FreeREG page rather than actual previous results (in the old version one could view previous results in browser history, which was very helpful.)

**Comment by Captainkirkdawson** [comment]
We have implemented a title by page so that the history can be correctly viewed by going to the requested page. Previously all pages had the same history title
