### ISSUE TITLE
Add Batch Complete message for Transcriber to send to SC

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#532]
Add the means for the transcriber to say that they have finished their work and hence trigger an email to the SC

**Comment by Captainkirkdawson** [comment]
What is wrong with them simply emailing their SC?

**Comment by edickens** [comment]
They don't do it and it will be needed for the RAP report to move it
    out of "In progress" and take it off the report and for the images
    to be unallocated.  E
    
    On 12/09/2015 03:18, Kirk Dawson wrote:
    
    
      What is wrong with them simply emailing their SC?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
If they don't do it why would they do it in FR2?

We can send cc to SC on any process but would that "overload" them?

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
The problem now is that transcribers do not always tell the SC that they 
have finished.  The SC has to keep checking their work.
Having a system for the transcriber to automatically notify the SC that 
they have finished will save the transcriber time and save the SC having 
to check.  They will use this email to update their records of who is 
doing what.
We will need this information for updating the RAP report.
The trigger should be a button which the transcriber uses against a 
batch to say "This batch is done, sight checked and error free".
E

**Comment by Captainkirkdawson** [comment]
I cannot see why they would click an option and not send an email. If they don't do one why would they do the other. There is nothing automatic about it if it relies on a human action.
The only automatic solution is to send an email to the SC with every processing of an upload

**Comment by edickens** [comment]
OK, forget it.  Close this topic.  We can revisit this when we get
    to the RAP and allocation of images.  E
    
    On 12/09/2015 16:31, Kirk Dawson wrote:
    
    
      I cannot see why they would click an option and not send an
        email. If they don't do one why would they do the other. There
        is nothing automatic about it if it relies on a human action.
        The only automatic solution is to send an email to the SC with
        every processing of an upload 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Why do you reject my solution. It is fully automatic?

**Comment by edickens** [comment]
I must have misunderstood.  I didn't think it was automatic.  You
    said that the transcriber had to send an email.  E
    
    On 12/09/2015 16:40, Kirk Dawson wrote:
    
    
      Why do you reject my solution. It is fully automatic?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
It is simple to add a cc to the SC of the message to the transcriber when a file is processed after an upload.
Fully automatic. SC knows what the transcriber is up to. 

I was not rejecting your requirement. Just your solution.

**Comment by edickens** [comment]
The problem with that is that it is not telling the SC that the file
    has been checked and is error free.  Processing could be just the
    start.  And if they do it a few times and use Replace before they
    are finished then it could tell the SC that they have finished
    before they are ready.  I would also like something, which we don't
    have now, where the transcriber has to do something positive and
    acknowledge that they have finished and checked and are satisfied
    with what they have done.  There will then be just one email per
    completed batch.  And that is when it will be moved off the RAP
    report after having been In Progress, the images returned to the
    pool, and when the SC can do a sight check, allocate some more
    images and perhaps upgrade the transcriber's ability.  So it will
    trigger the move to the next lot of work, which is not at the upload
    point.  In fact a transcriber might hang on to a batch and its
    images until they are into the next lot if the images are part of
    the same register book and they need to find more entries to solve a
    readability problem with the last lot.
    The SC should know what the transcriber is up to through the RAP
    report.  It will show what is In Progress and could show if the
    batch has had its first upload and if it is error free or not.
    Thoughts?  E
    
    On 12/09/2015 16:47, Kirk Dawson wrote:
    
    
      It is simple to add a cc to the SC of the message to the
        transcriber when a file is processed after an upload.
        Fully automatic. SC knows what the transcriber is up to. 
      I was not rejecting your requirement. Just your solution.
      —
        Reply to this email directly or view

          it on GitHub.

**Comment by edickens** [comment]
SC are complaining that they get an email each time a file is uploaded.  They really only need to know when the transcriber has finished what they are doing and wants more work.

**Comment by Captainkirkdawson** [comment]
Is it a consensus view of coordinators that upload notifications are stopped? Many have asked for addition to subject line to assist them which have been addressed. Also there have been complaints when messages did not arrive?
We cannot add that to an upload message as the upload may have errors.
We could add  a button  on the batches page that sends a message to the SC that I have finished. However I really do not see advantage over transcriber sending an email!

**Comment by edickens** [comment]
I don't see any messages of this type because I do not have any
    transcribers.  But I have had a positive feedback about the SC
    getting some indication that the batch is complete.  I agree that we
    should not stop upload notifications going to the SC.
    If the file has errors, then it is not complete, so being unable to
    add Completed to the message in this case is not a problem.
    Your last paragraph is a useful idea, but rather than a message to
    the SC, just add to the subject "Completed", and the file would need
    to be error free.
    I have ideas to use this in the RAP report, so it would also be
    helpful if the "Completed" information is held against the batch. 
    It could trigger the removal of this batch from the "In progress",
    perhaps after the SC has sight checked and "Signed it off".
    E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 17/10/2016 22:22, Kirk Dawson wrote:
    
    
      Is it a consensus view of coordinators that upload
        notifications are stopped? Many have asked for addition to
        subject line to assist them which have been addressed. Also
        there have been complaints when messages did not arrive?
        We cannot add that to an upload message as the upload may have
        errors.
        We could add a button on the batches page that sends a message
        to the SC that I have finished. However I really do not see
        advantage over transcriber sending an email!
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #532: Is it a consensus view of coordinators that upload notifications are stopped? Many have asked for addition to subject line to assist them which have been addressed. Also there have been complaints when messages did not arrive?\nWe cannot add that to an upload message as the upload may have errors.\nWe could add  a button  on the batches page that sends a message to the SC that I have finished. However I really do not see advantage over transcriber sending an email!"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/532#issuecomment-254338162"}}}

**Comment by edickens** [comment]
Does this need Project manager approval to be added to the functions in V1.5.  Also, if approved, should it go in the Roadmap so that SCs know what has been agreed to be included?  E

**Comment by PatReynolds** [comment]
I've discussed this with a number of Coordinators and had very positive
support.

At present the SC gets an email each time the transcriber uploads a
file. But they may not have finished what has been assigned to them.
They are just uploading for validation or to make what they have done
available to researchers. SCs tend to ignore these emails. What they
want to know is when the assigned images are complete so that they can
check the work and assign more work. So a button as part of the
uploading for the transcriber to say "Finished and sight checked" will
trigger the email to the SC. Other emails are not needed. It is then
time to remove this assigned work from the RAP (they were "In progress"
until then). Or perhaps they stay on the RAP as "Being checked by SC"
until the SC signs it off as OK. The batch to have a Coordinators Lock
applied so that no more changes are made by the transcriber, because the
transcriber has no more need to work on this batch. These changes in
status to be done by just clicking buttons. At present it involves the
SC updating spreadsheets on their computer in many different formats.
It could be so much easier and quicker. E

**Comment by PatReynolds** [comment]
Tied-in with the allocation process. Consider this 'finetuning'.

**Comment by edickens** [comment]
I think an essential part as it triggers the removal from the RAP.
This will then also be accurate.  Anything that is done manually, such as the spreadsheet that the SC keeps, is open to error.  This is why I think we have allocation of images going back years which may have been completed.  And we cannot get any management reports.

**Comment by SteveBiggs** [comment]
This has been implemented as part of the image management work Kirk and Bev have done on test2.
