### ISSUE TITLE
Change to Roadmap to reflect Online Transcription project

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#533]
Because Online Transcription is now being handled as a stand-alone project, the FR2 roadmap now needs to include it at Version 1.6, if FreeREG is chosen as the pilot, and as V1.8 if FreeREG is not chosen as the pilot.  I am drawing up criteria for choice of pilot.

**Comment by edickens** [comment]
Pat,
    I'm not sure what is planned in detail, but we have since the
    beginning wanted an online data entry system.  The present
    WinFreeREG that Mike is working on is an option for transcribers and
    is the basis of what can be online data entry.  The difference will
    be that, rather than holding the program on their computer, when we
    go online, the coding will be integrated into web browsers and
    transcriptions will be held on the server and not on the
    transcribers computer.  The main thing is that the way it will work,
    as far as validation and appearance, will be the same.  So the bulk
    of the coding to integrate with FR2 will have been done and tested.
    E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 12/08/2015 10:21, PatReynolds wrote:
    
    
      Because Online Transcription is now being handled as a
        stand-alone project, the FR2 roadmap now needs to include it at
        Version 1.6, if FreeREG is chosen as the pilot, and as V1.8 if
        FreeREG is not chosen as the pilot. I am drawing up criteria for
        choice of pilot. 
      —
        Reply to this email directly or view
          it on GitHub.
