### ISSUE TITLE
Move a batch to a different UserID

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#534]
If a SC uploads a batch for someone else, they need to assign it to that UserID - How?

**Comment by edickens** [comment]
For example.  We are donated a transcription.  The SC or CC does the conversion, then needs to put it on the server in a UserID associated with the donor.  In FR1 we upload to the CC's UserID to check it out, then move it to the final UserID.  The same applies if the CC uploads on behalf of a transcriber.

**Comment by Captainkirkdawson** [comment]
In the upload. They select where to have it assigned. It is already programmed

**Comment by edickens** [comment]
TY.  No problem.  E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 12/08/2015 14:41, Kirk Dawson wrote:
    
    
      In the upload. They select where to have it assigned. It is
        already programmed
      —
        Reply to this email directly or view
          it on GitHub.
