### ISSUE TITLE
Fr2 and FR1 members area is not accessable

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#536]
Since 5pm today the members area is not accessible.

**Comment by edickens** [comment]
It is not just me.  Mick has reported it to me.  I emailed the project team a few hours ago.  I have not had any feedback.

**Comment by Captainkirkdawson** [comment]
Yes the master server is absent without leave.

Awaiting lemon to wake up and make solution.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Applies also to member part of BMD

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Problem was a server crash
