### ISSUE TITLE
Transcribers' sign-up process

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#537]
Map and implement processes for signing up new transcribers.

**Comment by edickens** [comment]
How's this for starters...
- Select "Volunteer to transcribe" from the home page footer
- Volunteer enters all details, including select a Syndicate.  If in doubt select "Any".  Do not select "Researcher"
- Submit
- The SC receives an email giving details.
- An email will be sent to the address that the Volunteer has entered.  Select the link and enter a password.  Submit,  Registration is complete.
- The SC receives an email saying that registration is complete.
- The SC must then email the volunteer to find their level of expertise.  The UserID record is amended accordingly by the SC.
- If the volunteer needs training, their Syndicate should be amended to Training and a note entered as to which Syndicate they should go back to after training.  The Training SC takes control and does the training (until we have a training package).
- If no training is needed, the volunteer enters the Allocation of work system, V1.6.  For now it is all offline.

**Comment by Captainkirkdawson** [comment]
See also 268

**Comment by PatReynolds** [comment]
If they select 'any', can we allocate them to the top-of-the-priortity list of counties needing transcribers (i.e. one from those counties we are trying to push 'over the edge' to the point where people find it useful, and sign up as transcribers for it of their own free will?

**Comment by edickens** [comment]
We don't have a priority system.  It will rely on the person who is SC 
for "Any".

**Comment by Captainkirkdawson** [comment]
This is the current system. In light of 268 what if any thing is required?
