### ISSUE TITLE
info.png on search form is not cached

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#542]
While researching #442, we discovered that the browser isn't caching the info.png icon that shows up on the form fields.

Rough transcript of findings to date

@dougkdev /app/assets/images/info.png
@benwbrum: So it should be using the asset pipeline.
Moreover, the asset pipeline doesn't explain anything about why the browser isn't caching the same file.

@dougkdev: if i am reading my browser info correctly, the response header for info.png includes a "cache-Control
no-cache"

@captainkirk: great catch

@benwbrum: cf http://api.rubyonrails.org/classes/ActionController/ConditionalGet.html#method-i-expires_now

Hm.  We're not using the image_tag helper to include info.png, and we are specifying "app/images": see <img alt="Information" height="16" src="/assets/images/info.png"> at https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/search_queries/_form.html.erb#L21

**Comment by dougkdev** [comment]
I switched direct references to the info.png image to image_tag references
so info.png will be handled by the asset pipeline.  I will do the same in
the freecen_parsing branch-specifc files.

On Fri, Aug 28, 2015 at 12:35 PM, Ben W. Brumfield <notifications@github.com
