### ISSUE TITLE
Documentation for uploading files

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#544]
Draft skeleton of the documentation needed to launch V1.3

**Comment by Captainkirkdawson** [comment]
To me this should be the #1 priority for Alison. It is likely the most important component affecting the largest audience (aside from the researcher help)

**Comment by edickens** [comment]
Background
Transcribers and Coordinators can upload files into FR2.  The first stage is to upload the file from your computer to the server.  Once there it is held for future processing.  You could just leave it there as backup.  Then you can Verify the file.  It will be validated against County and Place (and eventually Church and Register Type) as well as all the usual validation of the fields.  If you wish, you can process the file (that is add it to the live database) and create the batches that will appear in your UserID.  Or you can correct any errors and replace the file.  Then only when error free do you process it.  If you do process it when it has errors, then just the correct records will be added to the database.
Coordinators have the option to upload files into any UserID in their Syndicate.

How to
- Log in
- Select Batches
- Select Upload new file
- Enter details
- Choose Verify, or Process.  There are three ways to process depending on the size of the file.  Overnight is recommended.
- Your list of Files will now show Orange if there is a file that has been uploaded but is not in the database.  Select RP (Reprocess) to get it put in the database.
- If the error was a Place name, which has now been fixed and the file does not need to be changed, then use Reprocess.

Note.  Once you start uploading directly into FR2 you should not use FR1 again.

And that is all there is to it.

[Screen prints need adding to the final document.]
