### ISSUE TITLE
Email address rejected

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#546]
Have entered this Report like this because Convert to an issue does not work.

**Comment by edickens** [comment]
Dear Eric;

We have received correspondence on a Website Problem that was directed us from Michael Walsby at michael@walsby.eu.

Copies went to all registered system administrators: (Kirk,John,Eric,Ben,)

It is suggested that Eric Dickens takes the lead in responding.

You may review the contact on line if you are logged into the system.

Contact

Time: 09:03 on 2015-08-17

Screenshot: No screenshot attached.

Body:I tried to send a message but was told my e-mail address is invalid ! Why ?

The FreeREG Team

**Comment by edickens** [comment]
I've now had another email to say that report #357 has been created.
I have replied.
E

**Comment by Captainkirkdawson** [comment]
Why do you think this is a bug ????

The contact would not have come in with an invalid email address

PS what did you reply.

PPS All contacts that come in as Website Problems are automatically included in Github. You do not have to create another one

**Comment by edickens** [comment]
I see now that I sent it to re-web so he has not had an answer.  I
    was going to say...
    
    Hi Michael,
     
     No idea why.  I will report the problem.
     
     Thanks
     
     Eric
    
    The author types in their email address, in this case
    michael@walsby.eu and so it is not used in a message.  I think he is
    saying that this is validated and seen as invalid and so he put in a
    Contact.
    
    I can try sending him an email.
    
    E
    
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 17/08/2015 18:37, Kirk Dawson wrote:
    
    
      Why do you think this is a bug ????
      The contact would not have come in with an invalid email
        address
      PS what did you reply.
      PPS All contacts that come in as Website Problems are
        automatically included in Github. You do not have to create
        another one
      —
        Reply to this email directly or view

          it on GitHub.

**Comment by Captainkirkdawson** [comment]
There is no way we can ever do anything with the limited amount of
information provided. He needs to provide the email address he had a
problem with. Clearly the one you are going to respond to was accepted. A
blank email will be rejected!

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
