### ISSUE TITLE
Check and ensure that FreeREG is accesible

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#548]
Use a Cookie to save different options for screen colours and contrast

**Comment by edickens** [comment]
Since FR2 launched we have had a number of comments about the screen colours, rather than the screen layout.  I certainly find the lack of contrast tiring and we have had someone with cataracts say that it is very difficult for them.
So could we have three options, Low, medium and high contrast.  Anyone who registers could select from these and each would point to a different css (style sheet) and their choice would be recorded in a cookie.
E

**Comment by PatReynolds** [comment]
Possibly an accessibility issuse rather than simple design issues

**Comment by AlOneill** [comment]
As I understand it, there are so many possible different issues with eyesight that we cannot hope to help everyone. Do people with specific problems use their own browser sylesheets to override browser/site stylesheets?

For those with dyslexia ("word blindness"), a change in background colour (away from white) can stop the text jumping about on the screen, but the choice of colour is an individual thing, best set by the user.

As a simple first step, we can ensure that browser zoom does not break our pages.

Secondly, is our highlighting combo (white on teal), a good choice?

**Comment by edickens** [comment]
I think we need to look at just three options.  The soft version
    that we have now.  A medium contrast for those working a long time
    on the website, and a high contrast for those with failing sight.
    
    But there is also the question of Scrolling.  The very big font and
    white space causes a lot of scrolling and it is difficult/impossible
    to see the whole result of a search or even the contents of one
    record at one time.  A compact version for CCs and SCs who are
    working with the reports would be much appreciated.  Today I had
    someone look at the new Database Contents and did not realise that
    the place names were there as the first one is off the bottom of the
    screen.
    
    Eric
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 09/10/2015 17:09, AlOneill wrote:
    
    
      As I understand it, there are so many possible different issues
        with eyesight that we cannot hope to help everyone. Do people
        with specific problems use their own browser sylesheets to
        override browser/site stylesheets?
      For those with dyslexia ("word blindness"), a change in
        background colour (away from white) can stop the text jumping
        about on the screen, but the choice of colour is an individual
        thing, best set by the user.
      As a simple first step, we can ensure that browser zoom does
        not break our pages.
      Secondly, is our highlighting combo (white on teal), a good
        choice?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by AlOneill** [comment]
We need to be careful about terms here. According to http://webaim.org/resources/contrastchecker/, most of our content is high contrast, that is #444 (dark grey) on #fff (white). 

Which bits are "soft" contrast for you Eric?

**Comment by edickens** [comment]
Hi Alison,
    
    The home page for example...
    
    
    
    or, perhaps because of the contrast to the buttons...
    
    
    
    Regards Eric
    
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 09/10/2015 20:18, AlOneill wrote:
    
    
      We need to be careful about terms here. According to http://webaim.org/resources/contrastchecker/,
        most of our content is high contrast, that is #444
        (dark grey) on #fff (white). 
      Which bits are "soft" contrast for you Eric?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by PatReynolds** [comment]
Can anyone recollect what the next step is - Helena had quotations from the Shaw Trust and Digital Accessibilty Centre

**Comment by PatReynolds** [comment]
Date now confirmed 2nd August - Pat and Denise in person, all welcome via hangout pm.
