### ISSUE TITLE
Warn users that they must use recent web browsers

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#550]

**Comment by edickens** [comment]
We get reports from people saying that things don't work.  Many are because they are using old web browsers.  We need to say somewhere that we have checked the website for it to work with the latest versions, but that some functions will not work with older web browsers.  In FR1 it was screen resolution!

**Comment by Captainkirkdawson** [comment]
Where should this appear?

**Comment by Sherlock21** [comment]
A suitable set of words appears at the top of Github pages when i try to Edit a comment there.  - becauseI use Safari and OSX 10.6.8 - which it does not like. [And i will not update to OSX Yosemite or later as i don't like many of their features. Also some of my applications would need to be updated which would cost me.- all to no benefit except to match Github's expectations. No signs yet of FreeReg being left out in the cold but it would get the same response.

**Comment by AlOneill** [comment]
Have placed a notice on Help page:
http://www.freereg.org.uk/help#browsers

Suggest you give this as link when replying to contacts.
