### ISSUE TITLE
info popups positioned partially off screen on smaller displays

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/MyopicVicar#558]
This issue is briefly mentioned in the discussion of #444 but is really a separate thing.  A quick fix for this is to simply change the tooltip class to the opposite side (from left to right on the fields at the left and right to left for the fields on the right) so they always pop up towards the middle of the form instead of toward the outside where they might go off screen. (in the appropriate erb files)

**Comment by Captainkirkdawson** [comment]
Their positioning was optimized for a large display. We have never optimized for a small screen.

**Comment by dougkdev** [comment]
In app/views/search_queries/_form.html.erb, I switched the popup positions
from left to right on the left edge of the search form and right to left on
the right edge.

On Fri, Aug 28, 2015 at 12:35 PM, Ben W. Brumfield <notifications@github.com
