### ISSUE TITLE
Trainees can only check files

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#559]
A trainee should not be able to load into the database

**Comment by Captainkirkdawson** [comment]
A trainee is not given any option except Verify

**Comment by edickens** [comment]
Good idea.  I have amended my draft instructions for uploading
    accordingly.  E
    

    On 03/09/2015 03:18, Kirk Dawson wrote:
    
    
      A trainee is not given any option except Verify
      —
        Reply to this email directly or view
          it on GitHub.
