### ISSUE TITLE
Logging in of Inactive UserID fails

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#560]
When Logging in and I am Inactive, the link is wrong

**Comment by Captainkirkdawson** [comment]
Please explain.

What link?

**Comment by Captainkirkdawson** [comment]
I have edickens and it is marked as Inactive.  When I try to log in with it I get...
![aibigeji](https://cloud.githubusercontent.com/assets/2874694/9562915/cb789a88-4e36-11e5-8cb8-60522bd828af.png)



Browser Back says "Signed out successfully".

Reloading test3 is asking me to Logout but I don't know who I'm logged in as.

**Comment by Captainkirkdawson** [comment]
Fixed.
Now need to find nice way of informing user why
