### ISSUE TITLE
New Register Types

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#561]
To standardise the coding and to match the help pages, new entries are needed

**Comment by edickens** [comment]
New Register types which should be accepted in validation.
OR "Other Register" for original register sources not covered by other codes.  Comment to go in the header.
PT "Phillimores Transcript" equivalent to PH "Phillimores"
DT "Dwelly's Transcript" equivalent to DW "Dwelly's"
OT "Other Transcript" for all other transcribed sources
MI "Memorial Inscription" for transcriptions made from gravestones
UK "Unknown" for transcriptions donated from an unknown source

Existing register types to be retained.
PR "Parish Register original"
AT "Archdeacons Transcript"
BT "Bishops Transcript"
EX "Extract"
Blank "Unspecified"

Existing codes (PH, DW) should be retained as there are transcriptions that have them, but validation of new transcriptions, such as in WinFreereg, should only use the new and retained lists.

[I have give this V1.6 but the FR2 Help pages may included the new codes.]

**Comment by Captainkirkdawson** [comment]
See also 614

**Comment by Captainkirkdawson** [comment]
In looking at this I see you have redefined EX from "Extract of a register" to "Extract".

Was this deliberate? If so is  "Extract" well enough defined by common usage to be interpreted by a researcher??

We cannot have identical key/value pairs as proposed for DT and DW

**Comment by Captainkirkdawson** [comment]
I further note that you have dropped the ' from Archdeacon's Bishop's and Phillimore's  while retaining it in Dwelly's.

Clearly we need to be consistent are hopefully correct .

Work on hold until clarified.

**Comment by edickens** [comment]
Hi Kirk,
EX "Extract of a register" or even "Extract from a register" is fine.  This was not a deliberate change.
If you look at the first comment here we are retaining AT and BT.  The ones in the last paragraph are not to the standard we are suggesting, which is a T  on the end to indicate Transcript.  But there are a lot of existing entries which is why we suggest that these are retained, unless you can convert them.  We can insist that the new list is used from when you go live with this.  WinReg will only accept the new set, which is what has been the problem.  Thanks E

**Comment by Sherlock21** [comment]
I take the view that we should only introduce change to past used codes, if that change improves the grammar or logic of the total. AT for Archdeacon's Transcript ( and the other 2) have been used for decades, and are well known. so should not be lightly changed.
Extracts by definition are someones copy of an original - so the legend and the code should identify " an extract from what. Indeed AT's and BT's are themselves Extracts from the Original Registers in that they are not complete - being bi- annual  events often.

This is probably our last chance of creating a composite, structured, set of codes to say what the source of our transcription is.

**Comment by edickens** [comment]
Hi Kirk,
I did the sixth comment yesterday.  What else do you need to know?  But I'm not sure if EricB's Comment needs clarifying.  I don't think he is saying that old codes should not be changed, but that the type of code should not be changed.  That is to say we must retain Archdeacon's Transcripts as a source.  But we can change the coding we use, because we are trying to rationalise by having all Transcription Register Types to end in the letter T.  So PH becomes PT for Phillimores.  However, I understand that you cannot have the same code PH and PT working for the same source.   So we either have to amend all the past PH entries to PT, or we have two entries for Phillimores which have slightly different descriptions, but mean the same.  It will mean that if someone is analysing our database they will have to use both PH and PT to get all the Phillimores.
It is very likely that we will need to add extra codes and register types to this list, so are the codes and descriptions set in a common table?  If not, then I can be a lot of coding to change it to work from a table.  E

**Comment by Captainkirkdawson** [comment]
waiting decision on my question which is repeated here

I further note that you have dropped the ' from Archdeacon's Bishop's and Phillimore's while retaining it in Dwelly's.

Clearly we need to be consistent are hopefully correct .

Work on hold until clarified.

It is a common table so changes are relatively easy until you start wanting equivalences. 

info buttons are hard coded so we should avoid changing definitions unless they are essential and you have proposed 4 definition changes to existing types as well as new ones

**Comment by edickens** [comment]
I understand now.  I thought you were saying that we were dropping the 
coding of AT.  I have no strong views on how you describe the different 
sources.  EricB and I were just standardising the two character code.

No I don't want equivalence.  There is no problem having PH and PT. We 
want to drop PH from future transcriptions.

The Info buttons need to show just the new set of codes.  Or would it be 
better to say in the Info button that the codes are defined in the 
Help?  Then it is easier to add to if needed.  I can't do a screen print 
of the Registers Info Button, but you have a long description there.  
Perhaps a description such as "A Church can have multiple registers 
depending on the source from which we transcribe. See Help for a full 
description."

E

**Comment by Captainkirkdawson** [comment]
You realize that this change is going to make work for coordinators who will have to rename all their TR register types to OT just as soon as they get one in the new  format otherwise they will have separate register types. Similarly for all PH and DW

**Comment by edickens** [comment]
I see what you are getting at.    Perhaps we should wait until we
    get full Place/Church/Register matching then when someone uploads
    data they match against what has been set up.  Eventually I'd like
    this all to be set up by the CC and then transcribers just put their
    work against it.  They will not need codes at all then.  You already
    have the "Create Register" action, so they can do it ready for the
    transcriptions.  So all we need to do now is to get WinReg, Help and
    Validation to agree.  E
    
    On 14/11/2015 21:28, Kirk Dawson wrote:
    
    
      You realize that this change is going to make work for
        coordinators who will have to rename all their TR register types
        to OT just as soon as they get one in the new format otherwise
        they will have separate register types. Similarly for all PH and
        DW
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
It would really be nice to think these things through before coding is
started!

I am just in the process of deploying to test3.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Yes, it is a lesson to be learnt.  EricB and I put our suggestions in 
the Story for ideas.  We suggested that OR be used for "Other Registers" 
rather than specifying each type, such as Public Cemetery Records.  But 
does everyone think that this is sufficient, or should we add more 
different sources?  We think that the list in this story is sufficient.  E

_____________________________________

**Comment by Sherlock21** [comment]
My objective was to end up with a short list of codes which had logical structure.
for those codes which change, i would have hoped that a little batch update script would have bee the way forward - to change any of the existing data to fit the new codes.
is that totally unrealistic? 
In my last industrial job, i had that quite a lot when we changed the records software system.
If it is, then we can never achieve the objective  can we? - since CC's will not do it by hand.

**Comment by edickens** [comment]
The problem is that if we do that, and the transcriber then uploads
    the file again before we have validation against Register Types, we
    will end up with two Register Types for the same Church.  A point
    made by Kirk.  So it is a timing problem now.  E
    
    On 15/11/2015 11:56, Sherlock21 wrote:
    
    
      My objective was to end up with a short list of codes which had
        logical structure.
        for those codes which change, i would have hoped that a little
        batch update script would have bee the way forward - to change
        any of the existing data to fit the new codes.
        is that totally unrealistic? 
        In my last industrial job, i had that quite a lot when we
        changed the records software system.
        If it is, then we can never achieve the objective can we? -
        since CC's will not do it by hand.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
So what's the solution?
If CC's do the changes by hand, then the is still the issue of being out of step with the transcriber's copy. and/or the locked file confuses the Transcriber when they try to upload - but that applies to everything that gets locked.

But do nothing is just as unsatisfactory to me.
If one asks the question: "why are we doing this?"  the answer must be to give the researcher knowledge of our source, which is a guide to " how many sequential hands has this transcription passed through", so as to give  measure of confidence in what they see.

Surely that's still our aim is it not?

**Comment by Captainkirkdawson** [comment]
A wonderful example of an unclear moving target. 
There has never been any request as part of this story or any other story to do a update of one register type to another. 
To change TR to OT is likely to affect several million search records and affect system performance for quite a time while it happens. For what benefit?  
The same for the change to other existing register types.
Changing TR to OT provides the researcher with no additional information. They are just as likely to be confused over the change. 
Additions make sense. But what is the rationale for simply changing codes?

**Comment by Sherlock21** [comment]
I agree with the last points.
But when this item started life, it was expected that there would be some discussion/ dialogue/.
With hindsight,  there only ever seems to be a slack handful of contributors. So perhaps that was the first oversight. 

if a feature is worth having, then in my book its worth having structured and right - or save the effort of having it at all.

**Comment by Captainkirkdawson** [comment]
OK. Have you tested it???

Do we change spec??

**Comment by edickens** [comment]
I think EricB is the best to do this as he knows where to find
    relevant entries.  Also, I am not sure exactly what I am looking
    for.  Are you expecting files to be uploaded to check that the new
    Register types are accepted?  E
    
    On 15/11/2015 22:15, Kirk Dawson wrote:
    
    
      OK. Have you tested it???
      Do we change spec??
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Deployed was the code that implemented this story

New codes accepted
OR "Other Register" for original register sources not covered by other codes. 
PT "Phillimores Transcript" equivalent to PH "Phillimores"
DT "Dwelly's Transcript" equivalent to DW "Dwelly's"
OT "Other Transcript" equivalent to TR "Transcription"
MI "Memorial Inscription" for transcriptions made from gravestones
UK "Unknown" for transcriptions donated from an unknown source

Existing register types to be retained and still processed.
PR "Parish Register original"
AT "Archdeacons Transcript"
BT "Bishops Transcript"
EX "Extract"
Blank "Unspecified"

Existing codes (PH, DW, TR) are accepted but are changed internally to PT, DT and OT respectively, if downloaded they would use the new codes

info explanations amended

On line changes in relocate of file or register only permit the approved set of codes ie (PH, DW, TR)  are not offered. So CCs and DM can change existing files/registers

All aspects need checking.

Not included is any code to do a database reset for the (PH, DW, TR) codes. Extent of problem is currently unknown

**Comment by edickens** [comment]
I tried a Relocate of a PH file and selected Phillimores.  So it was really relocating to the same references.  But it still shows in the list of files as PH not PT.  Not really a problem as I expect the Register is recorded as PH.  E
![capture](https://cloud.githubusercontent.com/assets/8876165/11176507/9dd3f0a4-8c35-11e5-8670-ddaa22410e52.JPG)

**Comment by Sherlock21** [comment]
I have been out most of the day. - i will create a set of files of each of the new codes and the existing ones that get changed.

OR Kirk - can i not put the different rows all into one file [for the Same County/ Place name  Church Name] for ease?


It will be based on real data of my own.
and use T3?.
E

**Comment by Captainkirkdawson** [comment]
It can all be in one file

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
My file was uploaded OK, and i chose: Process Later [as opposed to process now] but no action overnight.
\

does T3 not run to process automatically overnight?
so i will do it again  and "process now" Tuesday Morning UK.

Ericb

**Comment by Sherlock21** [comment]
Here is the file

and here's a copy of the Place name ALVERTHORPE which is the place I put this little file to.
We got some success - file was not rejected
and the AT; BT; Unspecified; Extract of a Register; MI; PR work

BUt the codes: PT, DW; OT; did not completely as I have 4 alpha-numeric string church names - much like those that some people got when trying to change names of relocate.


Over to you Kirk.

I will not fiddle with this during the day.

**Comment by Captainkirkdawson** [comment]
t3 has no automated schedule

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Placed on hold due to other priorities

**Comment by Captainkirkdawson** [comment]
Register Type	Number
Space	20197673
PR	7607232
TR	3966972
AT	820942
BT	773188
PH	364556
EX	128577
DW	45415
Blank	5391
Total entries	33990748
Total records	33990455
Total files	44598
Total registers	12607
