### ISSUE TITLE
Problems creating a Church

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#563]
Feedback from STS Coordinator

**Comment by edickens** [comment]
Michael Clarke wrote...
Great care needs to be exercised when using the "Creating New Church" functionality. What you see is not necessarily what you get! During my managing of STS, the number of times that I created a new church in the wrong place is unimaginable. Somehow, behind the scenes, the place name invisibly changes and the new church is created in the wrong place. You then have to go back to that place to destroy the newly created church and try to create it in the correct place. I use two open tabs in Firefox to process the "old" church and to process the "new" church. The two sessions may be getting confused.

Maybe you need to warn coords that there is a current problem in this piece of functionality and also get the problem corrected. Unfortunately, I cannot describe how I got the problem.

ED  Replies - We need a check  that FR2 should not be open twice.  I suspect it is the Cookies getting confused.

**Comment by Sherlock21** [comment]
On the original issue from Michael Clarke, it is often essential to have 2 windows open at the same time when one is moving stuff about, or changing elements of the naming. To put code in to prevent that would not be helpful.

It just needs care especially when picking the new Place name or the church name from a drop down list - I  agree with Michael, the list font is a bit small to drop the cursor on the right name.

**Comment by edickens** [comment]
This seems to be procedure,  not coding.  Suggest that it is closed because nothing can be done to help the situation.

**Comment by Sherlock21** [comment]
I suggest this one should be closed out, and nothing changed in the Process.
i don't have any problems like that described. - neither then nor now.

IF you think it necessary to do something, then make the window that contains the drop down list from which to pick, a bit taller so that it shows 6 or 7 names, rather than the 4 or 5.

The method of scroll down is too coarse for those who work on old fashioned PC's and half the alphabet flash part with great speed.

**Comment by Captainkirkdawson** [comment]
The speed of scroll is controlled by your own computer settings it is not controlled by the app

**Comment by Sherlock21** [comment]
If I use the Mouse Trackiing speed adjustment to slow this down, then its useless for absolutely everything else - is far too slow.
Sad thing is it did not used to me like this!

So just display another couple of lines within the drop down box please?

**Comment by edickens** [comment]
I have sympathy for this.  There are some boxes with enough entries 
showing, such as selecting from the list of UserIDs which is many 
thousand, and this works fine.  What I do is get somewhere near with the 
slider then hover the mouse over the list and use the wheel. But if you 
are using a laptop with touch pad, then you may have problems.  E

**Comment by Captainkirkdawson** [comment]
E#risB Could you raise a specific story for which "box" you believe needs additional vertical space. There are so many I would not know where to start

As for this story it remains a non story; similarly for the scrolling speed issue
