### ISSUE TITLE
Confirmation of transcriber registration

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#565]
It seems that just the SC gets confirmation of a transcriber registration

**Comment by edickens** [comment]
May I have a copy of the confirmation of the registration of a transcriber as I need to invite them to join the transcribers' mailgroup.  Not essential while they are still registering in FR1 as I get copies of those.  E

**Comment by Captainkirkdawson** [comment]
Is there not a way to automate such a routine action rather than you having to so do

**Comment by edickens** [comment]
Yes, when we get to setting up mailgroups within FR2.  I think it is
    in the milestones somewhere in the distant future.
    E
    
    On 02/09/2015 18:44, Kirk Dawson wrote:
    
    
      Is there not a way to automate such a routine action rather
        than you having to so do
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Added
