### ISSUE TITLE
Change the UserID of a Batch/File

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#566]
There is a need to organise Batches/Files under the UserID who created the transcription, even if they did not upload it

**Comment by edickens** [comment]
At present, to change the UserID associated with a Batch/File in FR2, I believe that the only way is to download the  file, delete the file on the server, upload the file again into the new UserID.  This could take a lot of processing.
Will the "Replace a file" be a better system or do we need a "Relocate"?
I hope I have understood the problem correctly.  E

**Comment by Captainkirkdawson** [comment]
But we deliberately did not add a movement between userids so as to avoid all of the issues you had with that in FR1. Coordinators can see and access all files relevant to them. They can upload and replacement into the userid.
What is the requirement that leads to this request?

**Comment by edickens** [comment]
Hi Kirk,
    Some CCs who uploaded on behalf of transcribers kept all the files
    in one UserID.  We want to put them into UserIDs for each
    transcriber because the Database Contents is not crediting the
    correct transcriber, because it selects the UserID.  But it is just
    a correction exercise so we can work around it.  That is download,
    delete and upload, or do it in FR1 while we can.
    Doreen just asked if there was a way to change the UserID, and there
    isn't.  But perhaps it is not needed.  E
    

    On 04/09/2015 18:38, Kirk Dawson wrote:
    
    
      But we deliberately did not add a movement between userids so
        as to avoid all of the issues you had with that in FR1.
        Coordinators can see and access all files relevant to them. They
        can upload and replacement into the userid.
        What is the requirement that leads to this request?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
It likely is less of an impact to add the move function as it only has to change owners and pointers and not delete/create records

**Comment by edickens** [comment]
So should Sean approve it to be added.  E
    

    On 04/09/2015 20:20, Kirk Dawson wrote:
    
    
      It likely is less of an impact to add the move function as it
        only has to change owners and pointers and not delete/create
        records
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Same as 574

**Comment by sean-wood** [comment]
I am happy for this to go forward
