### ISSUE TITLE
Delete FR1 deleted files from FR2

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#567]
We were originally running a full reconciliation between FR1 and FR2.  It was dropped when the PhysicAL files collection was implemented.
As has been pointed out we still need to delete FR2 file from FR1 that have been deleted in FR1

**Comment by sean-wood** [comment]
Is this a priority , i.e disk space etc.

**Comment by Captainkirkdawson** [comment]
This is potentially a database content duplication issue.
If a file in FR1 is moved to a new userid then while files only came into FR2 from FR1 we could delete the files associated with the old user by comparing the two file sets.
With the introduction of uploading into FR2 this comparison and deletion is no longer valid. Hence there can be the same data in the database for 2 userids. There is no concern over disk space, The concern is for duplicate records in a search result for a researcher. He might assume this was double keying when it was not.

**Comment by Captainkirkdawson** [comment]
In thinking about the issue. It is possible to detect the deletion in FR1 and to process a deletion in FR of a similar file for that userid whose date of creation is before the date at which we opened FR up to on-line uploads

**Comment by edickens** [comment]
But this will all go away if we move to FR.  Let's get transcribers
    off FR1.  E
    
    On 12/10/2015 20:34, Kirk Dawson wrote:
    
    
      In thinking about the issue. It is possible to detect the
        deletion in FR1 and to process a deletion in FR of a similar
        file for that userid whose date of creation is before the date
        at which we opened FR up to on-line uploads
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
That seems a far better idea, EricD, than writing & testing some more code - especially when other fixes are needed at the moment.

**Comment by edickens** [comment]
I'm ready to go to release to Transcribers and then, if there are no
    major problems, Pat suggests we give them a month then we stop
    uploading to FR1 and the overnight FR1 to FR update.  E
    
    On 13/10/2015 08:29, Sherlock21 wrote:
    
    
      That seems a far better idea, EricD, than writing & testing
        some more code - especially when other fixes are needed at the
        moment.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
What do you propose to do to delete the duplicate files that Anna and others have created?

**Comment by edickens** [comment]
We will have to identify them and then delete them ourselves.  The
    facilities are there to do it.  I have been keeping an eye on the
    Physical Files report but think that it will be cleaner to sort it
    all out after we have left FR1 and do not have a moving target to
    aim at.  E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 13/10/2015 14:57, Kirk Dawson wrote:
    
    
      What do you propose to do to delete the duplicate files that
        Anna and others have created?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
In which case this can be closed as no programming is required

**Comment by edickens** [comment]
But we have to remember to do it.  E
    
    On 13/10/2015 15:21, Kirk Dawson wrote:
    
    
      In which case this can be closed as no programming is required
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
But that's why we have the non product issues tracking system. You were using it for a while

**Comment by edickens** [comment]
Yes.  But it never got discussed in the Scrum or as part of project
    management.  E
    
    On 13/10/2015 15:28, Kirk Dawson wrote:
    
    
      But that's why we have the non product issues tracking system.
        You were using it for a while
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
But that is easily fixed by having Sean cover it,

The waffle board can display those items by the click of a button. Go up to
the top left and where it says freegen/myopicvicar click and select the non
product items.

Its where these actions should go.



Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by sean-wood** [comment]
Hi Both

I will cover this in future scrum meetings, thanks for letting me know where they are.


Regards

Sean Wood
Technical Project Manager
E: sean.wood@freeukgen.org.uk<mailto:sean.wood@freeukgen.org.uk>
M: +44 (0) 7771 824 315
W: http://www.freeukgenealogy.org.uk/

**Comment by sean-wood** [comment]
Hi Both

Do I need to be invited to those other waffle boards as I cannot see them

Kind Regards


Sean Wood
Director and Principal Consultant
Sands View I.T. Consulting Ltd.

E: swood@sandsviewitconsulting.co.uk<mailto:swood@sandsviewitconsulting.co.uk>
T: +44 (0) 7771 824 315
W: www.sandsviewitconsulting.co.uk<http://www.sandsviewitconsulting.co.uk/>

From: Sean Wood [mailto:swood@sandsviewitconsulting.co.uk]
Sent: 13 October 2015 15:46
To: FreeUKGen/MyopicVicar <reply@reply.github.com>; FreeUKGen/MyopicVicar <MyopicVicar@noreply.github.com>
Cc: sean-wood <sean.wood@freeukgen.org.uk>
Subject: RE: [MyopicVicar] Delete FR1 deleted files from FR2 (#567)

Hi Both

I will cover this in future scrum meetings, thanks for letting me know where they are.


Regards

Sean Wood
Technical Project Manager
E: sean.wood@freeukgen.org.uk<mailto:sean.wood@freeukgen.org.uk>
M: +44 (0) 7771 824 315
W: http://www.freeukgenealogy.org.uk/

**Comment by Sherlock21** [comment]
But, Sean, its an ever increasing number of files / batches. spread over an expanding list of Places.
 And will continue thus, so long as we are running both present arrangements in parallel. - I had a call for help on this topic, Just this lunchtime, from another person.
The only solution in by book is to stop working direct into FR2 until we close F1. We have had this dual system for long enough now to get a handle on the fact that it creates more work that it relieves,  it seems daft to carry on - especially if the "Backstop" is for EricD to remember what needs going back over to fix eventually.

**Comment by Captainkirkdawson** [comment]
No; you likely need to configure your waffle settings.

Go to left column; select the screw for project settings; second from top.

select project sources if not already selected

Click the green Gihub under add source

The list of repositories opens.

Select the freeregnonproductissues and it will add those issues as a
separate selectable item on the top menu from then on.

You can do the same for freecen as well if you have not already got it on
your waffle

PS myopicvicar and product issues have been "integrated" into one waffle
display

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
EricB

That is TOTALLY the wrong solution. People should ONLY be doing userid
moves on FR. It DOES NOT create duplicates.

*It is moves on FR1 that cause the duplicates.*

You and EricD are the only people who can do userid moves on FR

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Kirk
Is this wholly true?  If the files is moved in FR but not in FR1, then 
the overnight update will find a UserID(Old):Filename in FR1 with no 
matching equivalent in FR and so create it as if it is a new file.  
There are then two versions in FR.  Which is why I suggest EricB and I 
do not use this facility until the overnight updates have stopped.
E

**Comment by Captainkirkdawson** [comment]
It is 100% true!
FR1 files are ONLY processed into FR if the file in FR1 has changed from my copy of FR1
There was an issue initially with the change userid on FR in that I deleted the file from my copy of FR1. This was a mistake as the nightly sync added it back and reprocessed that. This was fixed as soon as it was brought to my attention in 463.
The problem is solely with moving files in FR1.
So if you are telling people to do it there and you are not doing it for them as we agreed you should be doing then you are just making the job harder for yourselves.

**Comment by Sherlock21** [comment]
K

And we (EricD & me) have stopped doing userID moves. ever since I wrote the Snag report a few days ago.


But those who are doing uploading direct into FR2 seem to be having the troubles so they need their process sorting out. And whatever they are doing, is what I suggest to stop doing.


Ericb

**Comment by Captainkirkdawson** [comment]
But that snag was fixed 2 days ago.

Since I have no idea what they are doing and no one has told me what they are doing that is causing a problem I cannot assist.

Only DM and SA have access to the change userid function.

So if they are causing problems using some other way I need to know.

**Comment by edickens** [comment]
I'm not sure that they are causing problems any more.  E
    
    On 13/10/2015 18:38, Kirk Dawson wrote:
    
    
      But that snag was fixed 2 days ago.
      Since I have no idea what they are doing and no one has told me
        what they are doing that is causing a problem I cannot assist.
      Only DM and SA have access to the change userid function.
      So if they are causing problems using some other way I need to
        know.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
This Item is about mixing up file changes in F1 and F2.
the topic has gone off rails by linking it in recent posts to the question of Changing UserIDs. What I wrote above, was on the subject of getting people getting multiple copies of a Batch in F2.

**Comment by Captainkirkdawson** [comment]
To the best of my knowledge the only way that a person can get multiple copies of a batch in FR is by moving them between userids in FR1 and that should be stopped. Stop changing in FR1.
