### ISSUE TITLE
Instructions to coordinators on how to us FR2 to give credit

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#577]
I think it is clear that people continue to think in only FR1 terms where you only did things by changing a file on their computer either in the data or in the header.
It is time that they moved away from that with FR2. There is no need to download and upload files in many situations. All they have to do is use the functions available to them in FR2 to edit records and headers and to add information to the Place, Church, and Register documents. These changes are reflected immediately and in many cases will propagate into the Database Contents pages and thereby assist researchers and give transcribers and contributors their due credit.
For example if you have a file where the transcriber missed their name (or misspelt it), then go to the edit headers function for that batch and input their name, That name will now appear in the Database Contents display where the researcher looks at the register contents. If you want to give recognition to someone else for their work on the file add their name to credit field of the header.
If you want to recognise the contribution of someone or some organization to the Register itself. Go to the Edit Register function and add whatever it is into the credit field. While you are at it you might want to add some notes about the Register, its source, its status( finished, in progress, need assistance), the official start and end date of the register, even a comment on copyright. Perhaps for those that are being worked on a note on quality would help.

**Comment by edickens** [comment]
What I am going to suggest here is very radical and could be V1.8
    Online data entry.  (It wouldn't be me if I didn't do things like
    this!)
    The reason for everyone thinking in FR1 terms is that they are
    concerned that any changes made in FR2 could be undone by uploading
    an old version of their transcription.  We have introduced locks,
    but they still rely on people doing things correctly.
    So ----  WinFreeREG will only work with FR2.  So it could create
    files (batches) on the transcribers computer which can only be
    uploaded through it.  The format of these files could be totally
    different.  They do not need headers, nor the County/Place/Church
    against each record.  What is needed, is the CC to set up the
    County/Place/Church/Register Type/Comments/Copyright/Image
    references/Batch information and any other source information.  The
    transcriber will have no control over this.  The Batch is assigned
    to a Transcriber, who can only work with batches assigned to them. 
    WinFreeREG accesses this information and the transcriber creates
    Register Entries to go against the information already on the
    server.  The transcriber can have a file on their computer as their
    property.  But the only things that they can change are the register
    entries.  This is virtually online data entry, except that the
    transcriber has the software on their computer and records are not
    uploaded one by one.
    You may want to bring this forward in the schedule, but I think we
    need to live with what we have and do this in V1.8.  We have to
    first get transcribers uploading into FR2.  We should not be
    concerned about the extra facilities in FR2 before we have the
    basics done and dusted.  E
    Sean - Perhaps this is a new Story, but I have entered it here to
    link it with Kirk's comments below.
    
    On 18/09/2015 00:50, Kirk Dawson wrote:
    
    
      I think it is clear that people continue to think in only FR1
        terms where you only did things by changing a file on their
        computer either in the data or in the header.
        It is time that they moved away from that with FR2. There is no
        need to download and upload files in many situations. All they
        have to do is use the functions available to them in FR2 to edit
        records and headers and to add information to the Place, Church,
        and Register documents. These changes are reflected immediately
        and in many cases will propagate into the Database Contents
        pages and thereby assist researchers and give transcribers and
        contributors their due credit.
        For example if you have a file where the transcriber missed
        their name (or misspelt it), then go to the edit headers
        function for that batch and input their name, That name will now
        appear in the Database Contents display where the researcher
        looks at the register contents. If you want to give recognition
        to someone else for their work on the file add their name to
        credit field of the header.
        If you want to recognise the contribution of someone or some
        organization to the Register itself. Go to the Edit Register
        function and add whatever it is into the credit field. While you
        are at it you might want to add some notes about the Register,
        its source, its status( finished, in progress, need assistance),
        the official start and end date of the register, even a comment
        on copyright. Perhaps for those that are being worked on a note
        on quality would help.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
As you say Eric what you are talking about is a totally different story! It is in our Roadmap as a future unscheduled milestone.
We have many more pressing issue such as what I wrote in the story

**Comment by AlOneill** [comment]
Have added 2 sections to the Coordinator actions page: Editing batch headers, Editing Register and Place information.
Content based on last 2 paras of Kirk's first post.

The lead para does ask coords to only use actions described for them, so maybe that has put a few off.

**Comment by Captainkirkdawson** [comment]
Thanks Alison. Could we just add (Giving credit) to the Editing batch header title as that is really the emphasis. Otherwise its a little sterile

Also we should remove that actions described here point.

**Comment by AlOneill** [comment]
Thanks. Done and done.

I rather fudged the instructions for how to edit headers:

"
If you become aware that any of the Header fields for a Batch are empty or misspelt, for example, then select Edit Headers for that Batch and simply type the additions or corrections.
"

Is there an Edit Headers button? Or should it be:
select ED for that Batch, then Headers and simply ...

or something else? (i have no batches and can see only as far as an empty Batches report list with ED included in the actions column.)

Alison
