### ISSUE TITLE
Orphan Search Records

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#579]
Hi Admin,

I have noticed on several occasions duplicates appearing in the FreeREG2 results (see first screen shot). Click on one and it takes you to the information, but click on the other and you get an error (see second screen shot).
![screen shot 2015-09-24 at 6 49 59 am](https://cloud.githubusercontent.com/assets/2874694/10089265/db93f766-62de-11e5-9883-e755947e74f5.png)

**Comment by Captainkirkdawson** [comment]
Investigation to_date
System dies with following error
ActionView::Template::Error (undefined method `record_type' for nil:NilClass):
    16:           <% if @entry && @annotations && @annotations.length %>
    17:           <h2>Offline Transcriptions</h2>
    18:           <% end %>
    19:           <h3><%= RecordType::display_name(@entry.freereg1_csv_file.record_type)   %> entry</h3>
    20:           <h4> For information about this place follow the link to <%= link_to(@search_record.place.place_name, show_place_path(@search_record.place)) %></h4>
    21:           <h5> If you believe there to be an error in this transcription then please <%= link_to "report", report_error_contact_path(@search_record, :query => @search_query) %> it to our data manager.</h5>
    22:         </td>
  app/views/search_records/show.html.erb:19:in `_app_views_search_records_show_html_erb__1176738097524222506_17340614220'

**Comment by Captainkirkdawson** [comment]
The search record is actually there and it is not a duplicate. They are 2 separate transcriptions
freereg2:PRIMARY> db.search_records.find({_id: ObjectId("55f241b7f493fd7f4907b5a5")})
{ "_id" : ObjectId("55f241b7f493fd7f4907b5a5"), "transcript_dates" : [ "14 Nov 1774" ], "search_dates" : [ "1774-11-14" ], "location_names" : [ "Wragby (St Michael)", " [Transcript]" ], "search_soundex" : [ { "first_name" : "M630", "last_name" : "F655", "type" : "p" }, { "first_name" : "J500", "last_name" : "R216", "type" : "p" } ], "record_type" : "ma", "chapman_code" : "WRY", "file_line_number" : 1132, "line_id" : "padWRY.WRYWRAMA.CSV.1132", "transcript_names" : [ { "role" : "b", "type" : "primary", "first_name" : "Martha", "last_name" : "FREEMAN" }, { "role" : "g", "type" : "primary", "first_name" : "John", "last_name" : "RUSHFORTH" } ], "freereg1_csv_entry_id" : ObjectId("55f241b7f493fd7f4907b5a2"), "place_id" : ObjectId("53cd4998eca9ebee4f00b7a8"), "search_names" : [ { "_id" : ObjectId("55f241b7f493fd7f4907b5a6"), "first_name" : "martha", "last_name" : "freeman", "origin" : "transcript", "type" : "p" }, { "_id" : ObjectId("55f241b7f493fd7f4907b5a7"), "first_name" : "john", "last_name" : "rushforth", "origin" : "transcript", "type" : "p" } ] }
freereg2:PRIMARY> db.search_records.find({_id: ObjectId("5510cd84e93790ccb6bb92e9")})
{ "_id" : ObjectId("5510cd84e93790ccb6bb92e9"), "transcript_dates" : [ "14 Nov 1774" ], "search_dates" : [ "1774-11-14" ], "location_names" : [ "Wragby (St Michael)", "[Transcript]" ], "search_soundex" : [ { "first_name" : "M630", "last_name" : "F655", "type" : "p" }, { "first_name" : "J500", "last_name" : "R216", "type" : "p" } ], "record_type" : "ma", "chapman_code" : "WRY", "file_line_number" : 1132, "line_id" : "wrypipdin.WRYWRAMA.CSV.1132", "transcript_names" : [ { "role" : "b", "type" : "primary", "first_name" : "Martha", "last_name" : "FREEMAN" }, { "role" : "g", "type" : "primary", "first_name" : "John", "last_name" : "RUSHFORTH" } ], "freereg1_csv_entry_id" : ObjectId("5463bea2e937904abb3f7e65"), "place_id" : ObjectId("53cd4998eca9ebee4f00b7a8"), "search_names" : [ { "_id" : ObjectId("5510cd84e93790ccb6bb92ea"), "first_name" : "martha", "last_name" : "freeman", "origin" : "transcript", "type" : "p" }, { "_id" : ObjectId("5510cd84e93790ccb6bb92eb"), "first_name" : "john", "last_name" : "rushforth", "origin" : "transcript", "type" : "p" } ] }
freereg

**Comment by Captainkirkdawson** [comment]
both entries are there.
freereg2:PRIMARY> db.freereg1_csv_entries.find({_id: ObjectId("55f241b7f493fd7f4907b5a2")})
{ "_id" : ObjectId("55f241b7f493fd7f4907b5a2"), "error_flag" : "false", "line_id" : "padWRY.WRYWRAMA.CSV.1132", "file_line_number" : 1132, "register_entry_number" : null, "marriage_date" : "14 Nov 1774", "year" : "1774", "groom_forename" : "John", "groom_surname" : "RUSHFORTH", "groom_age" : null, "groom_parish" : null, "groom_condition" : null, "groom_occupation" : null, "groom_abode" : null, "bride_forename" : "Martha", "bride_surname" : "FREEMAN", "bride_age" : null, "bride_parish" : null, "bride_condition" : null, "bride_occupation" : null, "bride_abode" : null, "groom_father_forename" : null, "groom_father_surname" : null, "groom_father_occupation" : null, "bride_father_forename" : null, "bride_father_surname" : null, "bride_father_occupation" : null, "witness1_forename" : "Hariot", "witness1_surname" : "TANNER", "witness2_forename" : "Charles", "witness2_surname" : "HALL", "notes" : "By William Brown", "county" : "WRY", "place" : "Wragby", "church_name" : "St Michael", "register_type" : "TR", "record_type" : "ma", "freereg1_csv_file_id" : ObjectId("55f241a4f493fd7f4907a2ce"), "record_digest" : "jmDc4iZ6Rhe22DTkoIHYbg==", "u_at" : ISODate("2015-09-11T02:51:35.002Z"), "c_at" : ISODate("2015-09-11T02:51:35.002Z"), "multiple_witnesses" : [ { "_id" : ObjectId("55f241b7f493fd7f4907b5a3"), "witness_forename" : "Hariot", "witness_surname" : "TANNER" }, { "_id" : ObjectId("55f241b7f493fd7f4907b5a4"), "witness_forename" : "Charles", "witness_surname" : "HALL" } ] }
freereg2:PRIMARY> db.freereg1_csv_entries.find({_id: ObjectId("5463bea2e937904abb3f7e65")})
{ "_id" : ObjectId("5463bea2e937904abb3f7e65"), "error_flag" : "false", "line_id" : "wrypipdin.WRYWRAMA.CSV.1132", "file_line_number" : 1132, "register_entry_number" : null, "marriage_date" : "14 Nov 1774", "year" : "1774", "groom_forename" : "John", "groom_surname" : "RUSHFORTH", "groom_age" : null, "groom_parish" : null, "groom_condition" : null, "groom_occupation" : null, "groom_abode" : null, "bride_forename" : "Martha", "bride_surname" : "FREEMAN", "bride_age" : null, "bride_parish" : null, "bride_condition" : null, "bride_occupation" : null, "bride_abode" : null, "groom_father_forename" : null, "groom_father_surname" : null, "groom_father_occupation" : null, "bride_father_forename" : null, "bride_father_surname" : null, "bride_father_occupation" : null, "witness1_forename" : "Hariot", "witness1_surname" : "TANNER", "witness2_forename" : "Charles", "witness2_surname" : "HALL", "notes" : "By William Brown", "county" : "WRY", "place" : "Wragby", "church_name" : "St Michael", "register_type" : "TR", "record_type" : "ma", "freereg1_csv_file_id" : ObjectId("5463bea0e937904abb3f7123"), "u_at" : ISODate("2015-05-28T20:13:14.933Z"), "c_at" : ISODate("2014-11-12T20:10:10.941Z"), "multiple_witnesses" : [ { "_id" : ObjectId("55f16268f493fd8f0e32745b"), "witness_forename" : "Hariot", "witness_surname" : "TANNER" }, { "_id" : ObjectId("55f16268f493fd8f0e32745c"), "witness_forename" : "Charles", "witness_surname" : "HALL" } ], "record_digest" : "jmDc4iZ6Rhe22DTkoIHYbg==" }
Both have a record type field

**Comment by Captainkirkdawson** [comment]
OK The entries for wrypipdin.WRYWRAMA.CSV are orphans in that the file they belong to no longer exists. Hence when we look up the file/register chain for the present register type (we do that because we use the information from the highest level which is the most up to date) it is not found.
Question was wrpipdin recently deleted and did the delete callback chain which we use to delete the children entries/search_records fail????

**Comment by Captainkirkdawson** [comment]
We can paper over the issue by using the record_type from the record but that is not the solution

**Comment by Captainkirkdawson** [comment]
When integrating the Physical Files collection I deleted the logical delete. My error.
Have implemented a paper over and a warning message in the log so that we may delete the records affected as they are identified

**Comment by benwbrum** [comment]
Should we write a script to identify orphan records and queue them for
deletion?

Ben

**Comment by Captainkirkdawson** [comment]
We would have to check each of 35 million entries and see if their file existed. Likely would be faster and better in the long run

**Comment by benwbrum** [comment]
That's what I feared.  So we'd need to think pretty hard about it.

Don't have the brain capacity tonight, I'm afraid.

**Comment by Captainkirkdawson** [comment]
Me neither having tracked it down and got a paper fix in place

**Comment by Sherlock21** [comment]
does the Attic  collection not help here?
I had a look in Test3, and there are is no place called WRAGBY in WRY.

But this was a search of Yorkshire wher you sum ERY + NRY+WRY. Any significance there?

Look at the index of batches.

there are 2 files of same user name & file name. BUT one is PR and other is TR

Any clues in this guys??

**Comment by Sherlock21** [comment]
KIRK & BEN


guys:
have a look at my post on #579 - may be the clue you need.

Ericb

**Comment by edickens** [comment]
Hi EricB.
    I'm just home again as trying to sort out my hundreds of emails.  It
    is difficult to answer your question without spending time looking
    up the original Contact (if I can find it) and I don't know if the
    sender has had an answer.  E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 25/09/2015 14:15, Sherlock21 wrote:
    
    
      does the Attic collection not help here?
        I had a look in Test3, and there are is no place called WRAGBY
        in WRY.
      But this was a search of Yorkshire wher you sum ERY + NRY+WRY.
        Any significance there?
      Look at the index of batches.
      there are 2 files of same user name & file name. BUT one is
        PR and other is TR
      Any clues in this guys??
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
EricB

I suggest you ignore this one. 

My input was a  collection of hints to Kirk &Ben who seemed to be struggling with this weird occurrence.  - but they seem to have abandoned the topic.

EB

**Comment by Captainkirkdawson** [comment]
Gentlemen the issue was determined 4 days ago when I commented
When integrating the Physical Files collection I deleted the logical delete. My error.
We have a paper over in place so people no longer get the error page and we log an error message of the event. There is a task that is run against the log that detects the event and deleted the orphan entries. Will take a few days to clean up but expect it may be faster than checking every entry.

**Comment by Captainkirkdawson** [comment]
Located 423 orphan files!!!!

**Comment by Captainkirkdawson** [comment]
All 423 orphans removed. Running a check to see if there are any others.

**Comment by benwbrum** [comment]
Hooray!

**Comment by Captainkirkdawson** [comment]
I am deeply worried. Ran a further check and in one week we have accumulated a further 328 orphans

**Comment by Captainkirkdawson** [comment]
Nor can I believe we are deleting that number of files in a week!

**Comment by Captainkirkdawson** [comment]
Looks like I may have been using delete rather than destroy and therefore not running the callback to destroy the entries.

**Comment by benwbrum** [comment]
That's actually really reassuring.  (To me, at least.)

**Comment by Captainkirkdawson** [comment]
Not so much to me. I have always been concerned about putting program logic into call backs exactly for this reason.

**Comment by Captainkirkdawson** [comment]
Yep. The user delete of a batch uses a delete not a destroy. Checking all other situations of use of delete

**Comment by Captainkirkdawson** [comment]
We have accumulated a further 38 orphans in the past 4 days

**Comment by Sherlock21** [comment]
I noticed too that the stats on the foot of the Search form, show a  reduction of 82,533 records last night. AND there were something like 65,000 reduction the night before.
Are these reductions also to do with the same issue?

**Comment by Captainkirkdawson** [comment]
Yes

**Comment by edickens** [comment]
There have been some Filemoves in FR1.  I will try and check to see
    if they were matched with the move back.  E
    
    On 18/10/2015 16:32, Kirk Dawson wrote:
    
    
      We have accumulated a further 38 orphans in the past 4 days
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by edickens** [comment]
Kirk,
    Is this one of the new Orphans?  This is the FR1 message at 09:49
    17/10/2015 but I cannot find a move back to hawkinssm - E
    Hi,

The user Susan Hawkins (hawkinssm) has been modified!
The following file(s) were moved from hawkinssm to Cjvk:
	KENBROMA1.CSV
Reassigned KENBROMA1.CSV to Cjvk in database
Moved /home/apache/hosts/freereg/users/hawkinssm/KENBROMA1.CSV to /home/apache/hosts/freereg/users/Cjvk/KENBROMA1.CSV
Completed reassignment of file KENBROMA1.CSV from hawkinssm to Cjvk
	The Machine inside FreeREG
    
    _
On 18/10/2015 16:32, Kirk Dawson wrote:

    
      We have accumulated a further 38 orphans in the past 4 days
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Have no idea; the identification process just gives the missing file oblect and since that no longer exists it is not readily available

**Comment by edickens** [comment]
I will try to stop all filemoves.  We had trouble in FR1 with it a
    few years back.
    
    E
    
    On 18/10/2015 17:30, Kirk Dawson wrote:
    
    
      Yes
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Awaiting final test of #602 will then run a detection and deletion next week

**Comment by Captainkirkdawson** [comment]
test under 603 ran fine; will await rake running over weekend then pick up the rest

**Comment by Captainkirkdawson** [comment]
Running task to identify remaining orphans

**Comment by Captainkirkdawson** [comment]
50 orphans; now running a clearance

**Comment by benwbrum** [comment]
Wow.  That's really encouraging.

**Comment by Captainkirkdawson** [comment]
Orphans cleared overnight.
There is now a nightly rake task that clears out deleted files.
Will add a weekly task to see if more are appearing for an as yet unknown reason, Also will document all rake tasks
