### ISSUE TITLE
Data Problem Policy

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#583]
We need to establish and then document a clear policy on what we accept to do with records that people say are in error.

**Comment by Sherlock21** [comment]
These should be limited to our Transcription errors only. Helpful as commenters may think they are, telling of GRO certificates etc which they have, which show different details to those in out record, they are only a prompt that we hay have made a transcription error. And we should not alter the Transcription to match the email concerned Unless the Transcriber (or the CC) reviews our source and agrees that we are wrong.

**Comment by edickens** [comment]
We have always either,,,
    - Rechecked our transcription and amended if necessary
    - Kept our transcription and added another entry with the
    alternative and a comment in the notes.  But I wouldn't want these
    to be a different Register Type.
    E
    
    On 27/09/2015 14:13, Sherlock21 wrote:
    
    
      These should be limited to our Transcription errors only.
        Helpful as commenters may think they are, telling of GRO
        certificates etc which they have, which show different details
        to those in out record, they are only a prompt that we hay have
        made a transcription error. And we should not alter the
        Transcription to match the email concerned Unless the
        Transcriber (or the CC) reviews our source and agrees that we
        are wrong. 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
We have placed following in the report a data problem.

We are sorry that you feel the transcription may be in error. Please tell us why you believe we have misinterpreted the original record. We will adjust the record if, upon review of the original, we agree with your interpretation. 
Please be aware we do not adjust transcriptions based upon sources of information other than the original register.

**Comment by edickens** [comment]
Hi Kirk,
    I think that is a good idea.  If we have been doing say BT or PH
    then our transcription could be different.  If they have found the
    original parish register which shows that our source, not us, was
    wrong.  We then do not change our entry, but we put in another cross
    referenced entry, based on evidence which they must show us. 
    However, no need to say this here, but perhaps Alison might like to
    put something in Help.
    E
    
    On 06/11/2015 05:20, Kirk Dawson wrote:
    
    
      We have placed following in the report a data problem.
      We are sorry that you feel the transcription may be in error.
        Please tell us why you believe we have misinterpreted the
        original record. We will adjust the record if, upon review of
        the original, we agree with your interpretation. 
        Please be aware we do not adjust transcriptions based upon
        sources of information other than the original register.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
I concur with Kirk's note.
I am also very cautious about adding extra entries just to put the informant's alternative data "in somewhere".

**Comment by Sherlock21** [comment]
I also agree with EricD's points about writing up in the CC's Help/ Instructions exactly what the policy is, and how to implement - and not - all reported errors/changes.
Which begs the question: are Cc's "Help Instructions"  secure from public access?

**Comment by AlOneill** [comment]
No, they are not. Any page in the documentation could, in principle, be accessed by anyone who manages to type the correct URL. The Info for Transcribers/Coordinators folders are **not** password-protected.

However, I don't think we want to say anything that *needs* protecting from public gaze. Anything we put in the Info for T/C folders will be an expansion on the notice that the public see anyway, when Reporting a data problem.

**Comment by Captainkirkdawson** [comment]
I agree with Alison; there is nothing in those pages that we should be ashamed of being seen by anyone. Any member of the public can become a transcriber.
So I really don't see Eric's concern
