### ISSUE TITLE
Show Waffle to CCs?

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#590]
CCs are concerned that their requests are being forgotten

**Comment by edickens** [comment]
I get a lot of emails saying "Why don't we" and "What happened to my request".  So can we put in a Button for CCs to link to the Roadmap and perhaps to this Waffle.  They can then see, but not amend, what is going on.  In particular they will see the future planned versions and know when their ideas could be incorporated.  I appreciate that this may in the first instance provoke more questions, but we need to keep CCs informed and involved.
I would even go further and say that any registered person, researchers included, should be able to see the Roadmap.
This will mean keeping the Roadmap up-to-date.

**Comment by Captainkirkdawson** [comment]
Done on roadmap but not convinced about waffle

**Comment by edickens** [comment]
Hi Kirk.  Agreed to not showing Waffle.  How do they access it?  I
    can see it in System Documentation, but what will a CC or SC see?  I
    need to email them.  E
    
    On 11/10/2015 00:55, Kirk Dawson wrote:
    
    
      Done on roadmap but not convinced about waffle
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
The Roadmap is there as a direct button on their actions. CC and SC. You
still access via the system documents

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
