### ISSUE TITLE
Make title field searchable

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#592]
Titles and ranks are currently being recorded in Occupation (by some, where present) and notes (by others).  Creating a searchable field would improve this situation

**Comment by Captainkirkdawson** [comment]
Fields are being added as part of #809

**Comment by Captainkirkdawson** [comment]
@SteveBiggs can you check we have this in the list of new fields in #809. If so we can close this story

**Comment by SteveBiggs** [comment]
Yes we have titles in all of BA, MA and BU, but they're not currently proposed to be searchable fields.

**Comment by Captainkirkdawson** [comment]
Decision was that we not make the field searchable
