### ISSUE TITLE
Scope needs for data sharing

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#593]
We have a number of potential partnerships in the pipeline which will involve sharing some of our data.  Some want one-off (usually research) others may want to receive updates periodically or harvest periodically).  Needs discussion of user needs, what we are prepared to do, and what is needed to do it.

**Comment by edickens** [comment]
Pat - My immediate reaction is that we need to sort out the
    Transcriber Agreement first.  Historically they are very protective
    of their work, but would be happy to let it be used for these
    purposes under safeguards, or as extracts.
    What I think these people need is a Report Generator.  They can then
    extract the bits that they want in the form that they want.  It is
    in the Roadmap.  So we are getting ahead of ourselves again.  E
    
    On 11/10/2015 07:14, PatReynolds wrote:
    
    
      We have a number of potential partnerships in the pipeline
        which will involve sharing some of our data. Some want one-off
        (usually research) others may want to receive updates
        periodically or harvest periodically). Needs discussion of user
        needs, what we are prepared to do, and what is needed to do it.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
If the suggestion is to give unrestricted access, by way of a user driven report generator then we have absolutely no control of the amount of data going out NOR the uses to which it may legally or illegally find its way.

Who are these groups anyway?
 & what do they want to do with the access?.
As it stands at present, I would not be in favour.

And remembering a previous decision by the Exec, when I suggested that we could sell statistical data that WE extracted, that was pointed out to be completely against the Charity Position so could not be done.
So obviously these proposals as all on a FREE of INCOME (to us) basis?
