### ISSUE TITLE
Setting up new UserIDs on the Image Server

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#595]
FR1 automatically sets up new UserIDs, so an interim solution is needed

**Comment by edickens** [comment]
At present, when a new UserID is created in FR1 a new folder is created on the Image Server.  I don't know how this is done, but it will be necessary to do something for when we stop using FR1 shortly.
Each UserID folder on the Image Server can be accessed by using getscan.pl and that  lets the transcriber only see their folder and only with their password.
I don't mind creating the new folders when we have moved to FR, but I don't know how the access permission works nor what information getscan.pl needs.
Advice is a all that is needed now until we integrated the image server completely.
E

**Comment by Captainkirkdawson** [comment]
Ask Barrie directly, we have no knowledge of the image server

**Comment by Captainkirkdawson** [comment]
We have implemented a new task that creates the REG_users list that is used to update the image servers with our users.
We have confirmed that this works correctly.
We have asked Lemon for advise and assistance on the sync task we need to add to the nightly update and to eliminate the FR1 syncing task

**Comment by Captainkirkdawson** [comment]
Caompleted
