### ISSUE TITLE
Improve visibility of notes

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#597]
Researchers are not scrolling down to the notes field - how can we help them see this information?  Put notes at the top?  Put a warning message at the top telling them to scroll all the way down?

**Comment by Sherlock21** [comment]
Our Advertising strip and our on header stuff take up 50% of my screen (vertically). so if you move the notes to a position further up, what do you propose to move to the bottom?
Far better to reduce all the wasted space.
And not counting the advertising space, if the white space were to be reduced by 30%, there would be room for 5 more rows of data which would make better use.

**Comment by Captainkirkdawson** [comment]
They have been put at the top
