### ISSUE TITLE
Tablet: How to treat

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#600]
Do we treat a tablet as a desktop or mobile devise as far as search results are concerned?

**Comment by PatReynolds** [comment]
I am wondering if desktop users generally would like the option of using the mobile view?  On Tristan, I found google.com/gwt/n a way of getting at mobile versions (to save bandwidth).  I've liked some sites mobile versions better than their standard ones (look better / work better when I've enlarged the font significantly for use on my laptop without my big screen).
So perhaps one of our accessiblity choices would be 'mobile / desktop view'?

**Comment by PatReynolds** [comment]
Issue has drifted, so now #702
