### ISSUE TITLE
Delete batch to delete all batches?

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#601]
What to do with a file with multiple batches when user deletes a single batch. 
Delete all batches and the file?
Delete just the batch and leave the file with the other batches only?
Only an issue when there are multiple batches in a file!

**Comment by Sherlock21** [comment]
I would be inclined to ask back to the user: This is a multi-batch file. Do you want to delete ALL batches or just this one?

I have no idea how many multi-batch files there are so it may be a big issue or not.

**Comment by edickens** [comment]
There are not many, at least not if you exclude typing errors. 
    WinReg does not allow multi-batch files.
    The main ones are Circuit records where the register covers a large
    number of places of baptism.
    
    On 16/10/2015 09:16, Sherlock21 wrote:
    
    
      I would be inclined to ask back to the user: This is a
        multi-batch file. Do you want to delete ALL batches or just this
        one?
      I have no idea how many multi-batch files there are so it may
        be a big issue or not.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Good suggestion Eric: will use that approach when this story hits big time
