### ISSUE TITLE
What is Active in a UserID?

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#602]
We have an Active marker but how should it be used?

**Comment by edickens** [comment]
An interesting situation has arisen today.  There are quite a few UserIDs with files, but the transcriber is no longer working.  The SC has taken control of these and is editing the files if necessary.  So the Transcriber (UserID) is not Active, but it should still be possible to access the files.  In FR1 we have "Disable" which stops the transcriber from accessing the server, but the SC can access the UserID.
Is "Active" the same or do we need something to differentiate between the different situations?  E

**Comment by Captainkirkdawson** [comment]
Active in FR is the same as disable in FR1. It just stops the transcriber from logging in.SC and CC can still access the associated batches and they do not need to move them around!
