### ISSUE TITLE
Serious Performance issue on File delete

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#603]
For those watching issue 579 they will know that we were having an issue with orphan entries and records.
This was traced to a mistake in the code. A delete was NOT destroying entries and search records because the delete does not initiate the call back that is needed for their destruction.
The solution is trivial. The recovery painful and the long term implications significant. Why?
The act of deleting records causes a significant performance impact. The destruction of a file of 100 brings the servers to their knees for several seconds. This is because the deletion and index adjustments is propagated in real time to all servers and they place read/write locks locks on the complete database until the writes are completed.
Ben and I have been aware of issues around the propagation of updates to the servers for some time. For most aspects it is not a noticeable issue. In areas where it was we used a throttling of the change creation to spread the slave writes over a longer time. For example in the orphan clean up there is a delay of 1.5 seconds imposed between subsequent deletions. This has little performance impact. 0.3 seconds has some impact but it was felt that since this was a one off clean up it could be tolerated. 
.
Now comes the kicker. As noted earlier orphans were created by a file deletion. This has been corrected HOWEVER what do you think will happen when a coordinator/transcriber deletes a file. The destruction of the entries and search_records no matter how small in number will bring all servers to a stop while they are brought into sync. Imagine a coordinator deleting a 40,000 record file. I suspect we would be non responsive for hours. Hence the correction has been reversed while exploring options.
Clearly one could throttle the on-line file delete. But no coordinator is going to wait 30 minutes while a 2000 record file is deleted. Perhaps we spin the file delete as a rake task with the appropriate throttling. 
Final note the number of file deletions has absolutely exploded in the past month. Almost all of them are not required. There looks to have been 300 in the past week alone. They are being done as people change "ownership" of files on FR1 rather than doing it on FR where no file deletions or additions would be required.
Perhaps there other far better solutions and an urgent solution is required. In the interim I am reverting to the deletion that creates the orphans until we have a solution.

**Comment by Captainkirkdawson** [comment]
Perhaps we spin the file delete as a rake task with the appropriate throttling.  

Should read

Perhaps we run the file delete as a rake task in the nightly update with the appropriate throttling.

**Comment by benwbrum** [comment]
I am in favor of moving long-running tasks to a background task to be run via forking a rake call. 
I'm dismayed that deleting and adjusting indexes for 40K records of our 30M is such a long-running task.  (I'm not questioning Kirk's observations here -- rather I'm just frustrated that the version of MongoDB we run doesn't do this more painlessly.)

In addition to Kirk's proposed technical fix #1 (pushing file deletion into the background) and social fix #2 (discouraging unnecessary file deletions), I'd like to propose a few additional options for consideration:
3) Spend some time researching MongoDB replication, deletion and B-tree rebalancing to figure out if we're doing something wrong.
4) Upgrade to the latest version of MongoDB, which has had one major release and probably a few minor releases after the version we're running.  (Note that this would require time from the developers to test compatibility and performance -- especially for replicated deletes)
5) Postpone the problem by making record deletion actually flip an "i_am_deleted_dont_look_at_me" bit on the freereg1_csv_file, freereg1_csv_entry, and search_record collections, then modify the search engine, admin tools, and DAP to filter those deleted entries out.  We could then set up a long-running sweeper task on a cron job to delete the "deleted" records pokily enough that we don't get MongoDB all stirred up.  (If this sounds like I'm proposing we implement our own garbage collection, I can't disagree.)

I do think that #1 is a must-do, and #2 sounds appealing (though I don't know how to make it happen).  I don't feel like any of 3-5 are magic solutions, but Kirk asked for other options, so I thought I'd oblige.

**Comment by edickens** [comment]
I don't disagree with all of this,but it is taking us away from
    releasing V1.3.  Coordinators and myself are waiting to move off FR1
    and running both systems is causing a lot of these problems.  The
    databases are getting out of step and becoming difficult to
    control.  I think that deleting these Orphans can wait, now that we
    know the cause which has been fixed.
    I think we need to look at why we are deleting.  It was very rare to
    delete in FR1.  The only time was when a transcriber was in
    training.
    In FR the reason I think is moving Batches between Churches as we
    tidy up the past.  Perhaps just the index to the Church could be
    changed?  We should not be using the Destroy action, but the
    Relocate.
    But please, let's get off FR1 first.  E
    
    On 16/10/2015 01:48, Ben W. Brumfield
      wrote:
    
    
      I am in favor of moving long-running tasks to a background task
        to be run via forking a rake call. 
        I'm dismayed that deleting and adjusting indexes for 40K records
        of our 30M is such a long-running task. (I'm not questioning
        Kirk's observations here -- rather I'm just frustrated that the
        version of MongoDB we run doesn't do this more painlessly.)
      In addition to Kirk's proposed technical fix #1 (pushing file deletion
        into the background) and social fix #2 (discouraging
        unnecessary file deletions), I'd like to propose a few
        additional options for consideration:
        3) Spend some time researching MongoDB replication, deletion and
        B-tree rebalancing to figure out if we're doing something wrong.
        4) Upgrade to the latest version of MongoDB, which has had one
        major release and probably a few minor releases after the
        version we're running. (Note that this would require time from
        the developers to test compatibility and performance --
        especially for replicated deletes)
        5) Postpone the problem by making record deletion actually flip
        an "i_am_deleted_dont_look_at_me" bit on the freereg1_csv_file,
        freereg1_csv_entry, and search_record collections, then modify
        the search engine, admin tools, and DAP to filter those deleted
        entries out. We could then set up a long-running sweeper task on
        a cron job to delete the "deleted" records pokily enough that we
        don't get MongoDB all stirred up. (If this sounds like I'm
        proposing we implement our own garbage collection, I can't
        disagree.)
      I do think that #1 is a must-do, and #2 sounds appealing
        (though I don't know how to make it happen). I don't feel like
        any of 3-5 are magic solutions, but Kirk asked for other
        options, so I thought I'd oblige.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
Interestingly ( and before I read BenB's comment above) I had been running through my mind the idea of Don't Destroy records then! Just shunt them off into a false home - as-it-were, where they are not accessible in searches. but could be dealt with at a mass event in the future. 
Something like what Ben suggests but better put, in (5).

**Comment by Sherlock21** [comment]
To respond to EricD's comment above about deleting files to tidy up church names is the only way to do some of them - and i say this from having been on the  job of doing it .
The automatic Case changing feature in F2 is causing much of that workload - Problem issue #466 I think. - if that issue were dealt with, then changing church names would not be so necessary.

**Comment by Captainkirkdawson** [comment]
EricD wrote:  "I think that deleting these Orphans can wait, now that we know the cause which has been fixed."
Unfortunately while we know the cause it has NOT been fixed. The whole point of this story is that a fix cannot be implemented until we have decided how to do it.
Every batch delete done will cause a new set of orphans.

**Comment by Captainkirkdawson** [comment]
Responding to both EricD and EricB on what FR actions require a batch delete be performed.
The answer is "none" they are all done in place. All relocations, name changes and owner changes are implemented in place with just changes to pointers.
If there are situations that do lead to the need for a batch delete please raise in another story.
The only currently known situations are 1) the same file existing in different userids coming from FR1 and 2) the batch is no longer required.

**Comment by Captainkirkdawson** [comment]
Doug wrote: What version of mongdb is running on production?  The version on vervet is 2.6.7, which has database-level locking.  It looks like newer versions support document-level locking, which may significantly improve the performance of writes to update the indexes (or may not-- hard to tell for a specific use-case without actually trying).

**Comment by Captainkirkdawson** [comment]
We are running the same version in both development and production  2.6.7,.

**Comment by Captainkirkdawson** [comment]
Doug wrote:
Additional reading indicates that document-level locking requires use of a new storage engine called WiredTiger, but I would recommend against that since it looks like WiredTiger is not very mature yet.  Version 3 does support collection-level locking with the standard MMAPv1 storage engine, which still may improve the performance quite a bit.  But like Ben said, that would require compatibility testing, etc., and there is no guarantee the performance increase would be sufficient to do the clean-up in real-time.  That being the case, my opinion is that it is probably better to go ahead with one of your other suggested solutions for now (ignoring orphans in the search / cleaning up orphans as part of the nightly cron taks).

**Comment by Captainkirkdawson** [comment]
The major change in Mongo 3 was the introduction of a new storage engine which is theif future; it is still not a stable storage engine from what I see and we would have to think carefully about adopting it. Although    it appears that different slaves can operate with different engines. Our use of Mongo is quite straightforward so most of the apparent incompatibilities do not affect us; its the unknown that bite.

**Comment by Captainkirkdawson** [comment]
Doug wrote:Looks like our opinion about the new storage engine is the same.

**Comment by Captainkirkdawson** [comment]
Yes we seem to be on the same wavelength wrt WiredTiger.

Collection locking is unlikely to be helpful since we are deleting search records and that is what the searches are hitting.

**Comment by Captainkirkdawson** [comment]
Rake task written, tested. Tested on t3, applied to colobus and 1 file of my own has been deleted. Will see if rake task runs as expected as part of production suite.
