### ISSUE TITLE
Identify what issues are stopping Coordinators using FR as their prime work base.

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#604]

**Comment by edickens** [comment]
Their transcribers are still on FR1 so they have to use a mixture of
    systems.
    

    On 16/10/2015 16:26, Kirk Dawson wrote:
    
    
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
EricD wrote in #603 that Coordinators and myself are waiting to move off FR1  and running both systems is causing a lot of these problems. Hence this story. What is stopping them?
Transcribers will continue to upload into FR1 for some time even when they are able to access FR. It is unrealistic to expect that transcribers will flip overnight especially as they will not have the WinREG gateway to assist them on day 1 and they will therefore have to change their method of operation. As a result coordinators and managers will have to be prepared to use both for sometime.
Even now most coordinators appear to be predominantly focussing their activities on FR1. Using FR to identify problems with their data and then fixing the issues in FR1. Why? What is stopping them from making the transition and doing it all on FR?

**Comment by edickens** [comment]
I think CCs will focus their activities on FR1 while their
    transcribers are also there.
    Yes, it will take time to move people over, but we need to start. 
    They look in FR for the results of their work, so I think that they
    will switch as soon as they can.  At least the more computer savvy
    people will.
    
    On 16/10/2015 16:40, Kirk Dawson wrote:
    
    
      EricD wrote in #603 that Coordinators and myself are waiting to
        move off FR1 and running both systems is causing a lot of these
        problems. Hence this story. What is stopping them?
        Transcribers will continue to upload into FR1 for some time even
        when they are able to access FR. It is unrealistic to expect
        that transcribers will flip overnight especially as they will
        not have the WinREG gateway to assist them on day 1 and they
        will therefore have to change their method of operation. As a
        result coordinators and managers will have to be prepared to use
        both for sometime.
        Even now most coordinators appear to be predominantly focussing
        their activities on FR1. Using FR to identify problems with
        their data and then fixing the issues in FR1. Why? What is
        stopping them from making the transition and doing it all on FR?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
I see the issue as a case of 2 groups:
the modern, computer savvy set like to play with new things, so they will be waiting to get started with FR.
The older generation, in the main, are content with what they are used to. So will stick with F1 as long as possible.

**Comment by Captainkirkdawson** [comment]
Closed
