### ISSUE TITLE
Improve email distribution of Comments and Feedback

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#605]
It is not possible to see who else has received the emails.

**Comment by edickens** [comment]
Can the email address also show who has received copies.  This should work if the email address is of the format e.g for SOM
mailto:somersetcoord@aol.co.uk?cc=reg-web@freereg.org.uk
Thanks E

**Comment by Captainkirkdawson** [comment]
Please Please Please can we get away from the use of the old BMD alias
system. It has no meaning within the FR. People are identified according to
their role in FR and emailed accordingly. In your example why send emails
to Ben Laurie ???

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
I only chose that because that is where they are going now.... 
    
    and it is through this that they reach me.  I can't see where I can
    change it.
    
    The "Contact Us" has...
    
    
    Each of these should perhaps go to a particular Syndicate.  I could
    set up a Syndicate for each of these headings and then the person
    involved can easily be changed if necessary.
    
    Who do you suggest they go to?  E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 17/10/2015 15:46, Kirk Dawson wrote:
    
    Please Please Please can we get away from the use of
      the old BMD alias
      system. It has no meaning within the FR. People are identified
      according to
      their role in FR and emailed accordingly. In your example why send
      emails
      to Ben Laurie ???
      
      Kirk Dawson
      Fairmont Hot Springs, B.C.
      V0B 1L1

**Comment by Sherlock21** [comment]
Its fine, complaining vigerously like this, but I for one have never seen your apparent rules written out anywhere, nor a list of such " FR Posts" & the associated people names.

**Comment by Captainkirkdawson** [comment]
They do not go to reg-web@freereg.org.uk unless the alias system is reprocessing the assigned email address. 
The email that you receive will come from reg-web@freereg.org.uk as the sender. That is not the same as FR sending it to that email address.

**Comment by Captainkirkdawson** [comment]
EricB You see the roles every time you look at a userid; Its a drop down list.
 ["researcher","trainee",'pending', ,transcriber','syndicate_coordinator','county_coordinator','country_coordinator',
    'volunteer_coordinator','data_manager', 'technical','system_administrator']
In any email you receive as a DM the other DMs are identified in the email. Similarly for other roles..

**Comment by edickens** [comment]
Correct.  But where does FR send it?
    
    On 17/10/2015 16:21, Kirk Dawson wrote:
    
    
      They do not go to reg-web@freereg.org.uk
        unless the alias system is reprocessing the assigned email
        address. 
        The email that you receive will come from reg-web@freereg.org.uk
        as the sender. That is not the same as FR sending it to that
        email address. 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Since you specifically asked for the copy it is sent for REGManager and not
the System administrators as the rest of us have no need. The original goes
to the SC.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
That is fine, but the email address of REGManager is
    freereg.edickens+REG@gmail.com not reg-web@freereg.org.uk
    E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 17/10/2015 18:14, Kirk Dawson wrote:
    
    Since you specifically asked for the copy it is sent
      for REGManager and not
      the System administrators as the rest of us have no need. The
      original goes
      to the SC.
      
      Kirk Dawson
      Fairmont Hot Springs, B.C.
      V0B 1L1
      
      On Sat, Oct 17, 2015 at 10:42 AM, Eric Dickens
      <notifications@github.com>
      wrote:
      
      >
      >
      >
      >
      >
      > Correct. But where does FR send it?
      >
      > On 17/10/2015 16:21, Kirk Dawson wrote:
      >
      >
      > They do not go to reg-web@freereg.org.uk
      > unless the alias system is reprocessing the assigned email
      > address.
      > The email that you receive will come from
      reg-web@freereg.org.uk
      > as the sender. That is not the same as FR sending it to that
      > email address.
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
<https://github.com/FreeUKGen/MyopicVicar/issues/605#issuecomment-148932684>
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
Thanks for the reply telling me the link between UserID & roll.\
I was not aware, because I don't oft look up userid's.

**Comment by PatReynolds** [comment]
Eric B. I can't see the connection between your last comment and this issue - could you raise it separately?

**Comment by Sherlock21** [comment]
OK. new topic created on 644.

**Comment by Captainkirkdawson** [comment]
Dependant on 626

**Comment by Captainkirkdawson** [comment]
Using the freereg-contacts@freereg.org.uk address have revised the code so that copies of the original email are sent to the appropriate person.  This has been done for contacts; volunteers ; questions; thank you and Website problems.
Will do data manager and feedbacks based on any experience with these first ones.
Have also implemented a log of ALL emails sent so that we can better track future "complaints".

**Comment by Captainkirkdawson** [comment]
Add something unique to subject line

**Comment by Captainkirkdawson** [comment]
Will also attempt to address Pats communication paper.

**Comment by Captainkirkdawson** [comment]
Deployed to test3. Addressed #335 and #539 at same time.
