### ISSUE TITLE
Let transcribers know when images are available

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#606]
Just as researchers will be able to ask for an email when a place has records changed, transcribers would like to know when images become available for a place

**Comment by edickens** [comment]
I think that there is a request for registered researchers to enter a request to be informed of changes to a Place, so perhaps this should be added to that story.
Transcribers have interests in particular places, which is what motivates them to transcribe, so it will be beneficial if they can leave a request to be informed when images become available for that place.  This is the same system as researchers requests but for images.  E

**Comment by sean-wood** [comment]
need further stories for image server

**Comment by Captainkirkdawson** [comment]
This has been incorporated as part of the image server software
