### ISSUE TITLE
Performance Problems with Database Contents

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#607]
It appears that the new scrollable database contents display is having a significant performance impact on the servers. Servers have been out for minutes at a time today. We may have to withdraw until there is a better solution

**Comment by Captainkirkdawson** [comment]
An alphabet selection code is ready; need to access where to place the cutoff

**Comment by Captainkirkdawson** [comment]
This will be an interim fix until we can do the calculations on a nightly basis and just read the results from the database.

**Comment by sean-wood** [comment]
OK Kirk,
Thank you for looking into this so quickly

**Comment by Captainkirkdawson** [comment]
Will implement alphabet selection of counties with >500,000 records.

A badge of honour!!!!!!!!

["CAM","CON","DUR","ESS","GLA","KEN","LAN","LIN","MDX","NBL","NFK","NTH","NTT","SOM","SRY","STS","WRY"]

**Comment by Captainkirkdawson** [comment]
Deployed
