### ISSUE TITLE
Multiple Place Selection

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#609]
We say none or 1 place; but multiple places selected does work. The About info in wrong in this case!!

**Comment by AlOneill** [comment]
Zounds! It does. Search criteria only lists one place, *but*...

**Comment by Captainkirkdawson** [comment]
Nor does the revise revise those selected; just the last of those selected!

**Comment by dougkdev** [comment]
Disabled multiple selection for place as discussed in today's scrum.
(Multiple place selection is superseded by "nearby places" option during
the search). On test3, not yet live on production.
