### ISSUE TITLE
Rewrite/Dry the csv processor

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#610]
The current csv file processor was my first code and written 3 years ago. It has grown and been augmented to the point where maintenance is about to become an issue. Originally it served to just one purpose now it serves 3 different purpose. 1) the original process from FR1 2) batch processing from FR add on_line processing of FR uploads. The first requirement is dropping. The third will increase and change.
It would be a good idea for me to clean the code into a better structure so that others can maintain in the future.

**Comment by Captainkirkdawson** [comment]
I have commenced work on this because the current code is unmaintainable

**Comment by Captainkirkdawson** [comment]
This rewrite is also required to support the introduction of new fields into a CSV files.

**Comment by Captainkirkdawson** [comment]
Have run tests of 150 files using files from Kyran, Ali, EricB, myself and Julie. In addition EricB ran a number of independent tests. Made a few minor tweaks. Have asked EricD to review.

**Comment by benwbrum** [comment]
I should have benchmark numbers in the next 24 hours.
