### ISSUE TITLE
Register types mismatch the Help

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#614]

**Comment by edickens** [comment]
Hello Eric

Further to my email about the register types in the FR help screens and whether they were active or not, you told me that I could use them.

Below is an extract of the beginning of a file that was submitted to FR and disappeared up its own what not.

+INFO,genghis17@comcast.net,PASSWORD,SEQUENCED,BURIALS,,3.02.21
#,CCC,Dale Braden,Staffordshire,STSTILBU40.CSV,14-Feb-2014
#,CREDIT,Dale Braden,genghis17@comcast.net
#,20-Oct-2015,,
STS,Tipton,Alexandra Road Cemetery OR,40000,26 Feb 1971,Jason Lee,,,,,EVANS,3d,"66 Bilston Road, Gospel Oak, West Bromwich",
STS,Tipton,Alexandra Road Cemetery OR,40001,03 Mar 1971,William Frank,,,,,NUTTING,62,"15 Thelma Road, Tipton",
STS,Tipton,Alexandra Road Cemetery OR,40002,04 Mar 1971,John,,,,,GARRETT,55,"6 Coronation Road, Tipton",

You will se that I was trying to use "OR" for Other Register. No email was received to say success or failure AND the file did not appear in the church at all.

I have already had one transcriber asking if she should put the Register Types as in the help screen into all her files.

Something should be done about this. (a) create a kludge that temporarily allows these new codes but does nothing else or (b) get the correct process working or (c) remove the offending register types from the help screen.


Kind Regards

Michael Clarke

FreeREG Staffordshire Coordinator

**Comment by Captainkirkdawson** [comment]
Please tell me why this is a bug?
We have never implemented the new codes.

**Comment by edickens** [comment]
Because I thought it had been implemented, the Help said so.  In
    which case it could have been a bug.  Is it difficult to do?  If it
    is, then the documentation needs changing, or showing which types
    are to come in which version.  E
    
    On 23/10/2015 01:34, Kirk Dawson wrote:
    
    
      Please tell me why this is a bug?
        We have never implemented the new codes.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Can I point to the story #561 on the implementation which you raised and the milestone assigned of 1,6

**Comment by AlOneill** [comment]
What would you like me to do? The new Register types are listed in a couple of places at present: Entering data from registers (simple list) and Record type (with explanations).

If this is my mistake, then what  detailshould be on the Register type page? Or should page link be removed from menus?

**Comment by Captainkirkdawson** [comment]
This is not a system bug. The change has yet to reach the action list.

I believe that the document should reflect what the system currently does.

{"Parish Register" => "PR", "Transcript" => 'TR', "Archdeacon's Transcripts" => "AT", "Bishop's Transcripts" => "BT",  
	"Phillimore's Transcripts" => "PH",  "Dwelly's Transcripts" => "DW", "Extract of a Register" => "EX", 
	"Memorial Inscription" => "MI"}
