### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#615]
Are our users Profiles Encrypted?

**Comment by edickens** [comment]
The fact that TalkTalk has been compromised makes me ask, and perhaps should be in our documentation, whether the Profiles are encrypted?  Peoples names and email addresses are there and could be hacked and generate Spam.
We should also have a section in the documentation on how to reset your password, because many may be doing it today.

**Comment by Sherlock21** [comment]
I agree with you and your concerns - not so much about the PR Data, but the personal stuff.
I go so far as to say this is quite urgent.

**Comment by PatReynolds** [comment]
Sean, can you comment on the urgency of this?  EricD please start another story with the request for documentation on how to reset your password, if not elsewhere / done

**Comment by Captainkirkdawson** [comment]
Passwords are encrypted. nothing else is. None of the projects uses https for user communication.

**Comment by sean-wood** [comment]
what information do we keep in our databases, user name / password ?

**Comment by edickens** [comment]
Lots more that is sensitive.  In particular email address, telephone
    number, home location and sometimes people enter a home address.
    
    On 03/12/2015 10:59, sean-wood wrote:
    
    
      what information do we keep in our databases, user name /
        password ?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by sean-wood** [comment]
Thank you

Kind Regards


Sean Wood
Director and Principal Consultant
Sands View I.T. Consulting Ltd.

E: swood@sandsviewitconsulting.co.uk<mailto:swood@sandsviewitconsulting.co.uk>
T: +44 (0) 7771 824 315
W: www.sandsviewitconsulting.co.uk<http://www.sandsviewitconsulting.co.uk/>

**Comment by sean-wood** [comment]
Hi Eric

Within the provisions of the data protection act the following data is classed as sensitive

Sensitive personal data.E+W+S+N.I.
In this Act “sensitive personal data” means personal data consisting of information as to—
(a)the racial or ethnic origin of the data subject,
(b)his political opinions,
(c)his religious beliefs or other beliefs of a similar nature,
(d)whether he is a member of a trade union (within the meaning of the M1<http://www.legislation.gov.uk/ukpga/1998/29/section/2#commentary-c18184281>Trade Union and Labour Relations (Consolidation) Act 1992),
(e)his physical or mental health or condition,
(f)his sexual life,
(g)the commission or alleged commission by him of any offence, or
(h)any proceedings for any offence committed or alleged to have been committed by him, the disposal of such proceedings or the sentence of any court in such proceedings.

I am looking further at what requirements we need to put in place with the data we hold

Kind Regards


Sean Wood
Director and Principal Consultant
Sands View I.T. Consulting Ltd.

E: swood@sandsviewitconsulting.co.uk<mailto:swood@sandsviewitconsulting.co.uk>
T: +44 (0) 7771 824 315
W: www.sandsviewitconsulting.co.uk<http://www.sandsviewitconsulting.co.uk/>

**Comment by edickens** [comment]
From the days when I had to deal with the data protection act, there is 
also the requirement not to hold any personal opinions, such as "This 
person is a trouble maker".  But you can say "This person has caused 
problems by trying to corrupt the database".  And you have to back this 
up with evidence.

The only field where this could apply is the note "Reason for making 
Inactive".  We need to be careful.

The User can see all these fields, except for when they are Inactive as 
they cannot log in, so there is no hidden information to them. Only the 
person themselves and Syndicate Coordinators and above can access the 
UserID details.

Regards,

Eric

**Comment by PatReynolds** [comment]
As to what data we store: this is now explained in our Privacy Notice which I put up yesterday: http://www.freeukgenealogy.org.uk/about/constitution-and-policies/

**Comment by Captainkirkdawson** [comment]
Is this why we are now getting system exception crashes as people try to access  some privacy policy on FR?
AbstractController::ActionNotFound: The action 'show' could not be found for AssetsController

{
  "action" => "show",
  "controller" => "assets",
  "format" => "html",
  "id" => "privacy"
}

**Comment by Captainkirkdawson** [comment]
Is this still an active backlog item that requires development effort?

**Comment by sean-wood** [comment]
Having reviewed the policy, I believe we do not need to do anything else
