### ISSUE TITLE
Database contents suggestions

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#616]
From a researcher

**Comment by edickens** [comment]
Hello,

 

I am a fan of the new freereg site, especially the search for nearby places that has proved very fruitful for me.

 

However, I think you have regressed in the coverage section.

 

On the old site you can clearly see which parishes are covered and which are not. The new site only lists the covered parishes.

 

On the old site you get a breakdown for years covered for each of baptisms, marriages and burials. Gaps in data are also listed. The new site just lists a start an end date which to be frank are not believable.

 

EG Lowestoft in Suffolk lists a start date of 1561 and an end date of 2007 on the new site. This is clearly not true and does not match at all closely to the old site seen below-

 

Lowestoft
	

St Margaret
	

1561-1900
	

1561-1628 1813-1832
	

1561-1786
	

Martyn Pearson
Heather Lawn
	

1561-1610
	

 
	

 
	

1561-1609 1846-1868
	

 
	

Martyn Pearson
Heather Lawn

 

As you can see, you used to be able to see what years the registers cover, the years that had been transcribed and the years that were being worked on.

 

All of this is crucial for family research to limit mistakes.

 

Moreover, the contributors are no longer available for contributions for individual parishes. I think their hard work should continue to be attributed.

 

I do not know how easy it would be to return this section back to its former glory (I am a sql developer so I can estimate that the data requirements for this are actually very low) but I suggest you look at it as it’s clearly a case of loss of data.

 

Kind regards,

 

Sean Robertshaw.

**Comment by Captainkirkdawson** [comment]
I am sorry but where is the suggestion?

The only thing missing is the gap information.

All of the other information that he wants is already there if he looks at it. Another case of not reading the documentation and looking.

**Comment by PatReynolds** [comment]
Would the notes field of "Information about the Register itself" be the place where gaps should be recorded?

**Comment by edickens** [comment]
No.  It needs to be at Batch level so that we can show it in the
    Decade analysis.  Also, Church registers have lots of gaps, such as
    when the Church was being repaired for just a few years.
    
    Please do not confuse Register with Register Type.  A Register Type,
    such as PR, can have many Register Books.  There are usually more
    recently separate ones for BA, MA and BU.  Some cover 100s of years,
    some where the Church is busy just a few.  And some of these books
    get "borrowed" and not returned, or are lost in fire or water or
    mice damage.
    
    I suggest that the CC creates a Batch with the years involved and an
    indication that it covers missing records.  But that is all for
    future versions.
    
    E
    
    
    
    On 17/11/2015 11:45, PatReynolds wrote:
    
    
      Would the notes field of "Information about the Register
        itself" be the place where gaps should be recorded?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Likely GAPs should appear at multiple levels.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
This will be addressed as part of the GAP
