### ISSUE TITLE
Style of the Cookie request

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#617]
The large black box is threatening

**Comment by edickens** [comment]
I've had a suggestion that the large black box with the request to accept cookies is very aggressive.   Some have to accept  this regularly if they have a cleanup program.  It is thought to be a Virus or Trojan or something.

**Comment by edickens** [comment]
While I was away tried to access FR from my iPod Touch so that I could help with the Contact Problem.  But the Cookie acceptance was so large and it did not scroll and the button is off the screen.  Nothing I could do would get past it.  Photo of my iPod attached.  You can just see part of the button at the bottom of the screen.  E

![p1000817](https://cloud.githubusercontent.com/assets/8876165/21545207/8c852ba8-cdcd-11e6-833b-7963a9091213.JPG)

**Comment by AlOneill** [comment]
See my comments on #923 for suggestions on how to edit the JavaScript on application.html.erb

**Comment by Captainkirkdawson** [comment]
Duplicate of 887
