### ISSUE TITLE
Statitics for counties with alphabetic

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#618]
The statistics don't show until a letter of the alphabet has been selected.

**Comment by edickens** [comment]
The statistics apply to the whole county, so can be shown when the county is first selected and the alphabet selection comes up.  They do not need to be shown again.  It will free up space on the place listing and will not give the impression that they apply to that letter of the alphabet.

**Comment by Captainkirkdawson** [comment]
Is this still relevant?

**Comment by edickens** [comment]
Nobody has commented to me about it since then.
