### ISSUE TITLE
Refactor Update process

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#619]
The update runs both a FR1 ingest and a FR ingest,
Same software is used just different controls.
It could be made clearer which is which.
Is it worth it?

**Comment by edickens** [comment]
Evening Kirk (Dull damp and getting dark here!).
    My reason for asking is that if there is a problem I need to tell
    the SC which system to look at.  I was hoping that one of the
    headings or the general format might give me a clue.  Is one always
    run before the other?  E
    
    On 24/10/2015 15:10, Kirk Dawson wrote:
    
    
      The update runs both a FR1 ingest and a FR ingest,
        Same software is used just different controls.
        It could be made clearer which is which.
        Is it worth it?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Is there any requirement. There is now only a single update process

**Comment by edickens** [comment]
No need to change.  Everyone seems to know how to use it.  E
    

    On 13/04/2016 04:05, Kirk Dawson wrote:
    
    
      Is there any requirement. There is now only a single update
        process
      —
        You are receiving this because you commented.
        Reply to this email directly or view
          it on GitHub
