### ISSUE TITLE
Bounced emails

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#620]
I am getting a steady trickle of bounced emails.

**Comment by edickens** [comment]
What should I do with these emails?  They go to reg-web@freereg.org.uk.  I have been returning them to the SC for checking, but is this part of the problem of  ISPs  not accepting FR?  Who would like a copy of them?  Will someone compose an email to send to transcribers?  How do we solve this problem?  There is an email for each file uploaded.  E

**Comment by edickens** [comment]
The plot thickens!  A bounced uploaded report has been sent to the email address in the file header, but this is not the latest email address for the transcriber nor the same as in their Profile.   Which should we use?  I suggest that we should adopt a standard that the email address in the profile is the correct one and this is used all the times.   BUT, it raises the question of what to do when a SC uploads on behalf of a transcriber and uploads into their account.  So perhaps the email address to be used should be that of the person who has logged in?  E

**Comment by Sherlock21** [comment]
I completely agree. the email in the users Profile is the right one. That is the one the user should keep up to date and any other uses should draw off that one as needed.  - so that there are not dozens of copies & subsets about the place most out of date.

An email address in the file header should be just an indication of who created the file or who uploaded it.

PERHAPS its time to redefine the header fields and change email address into userID or some other non- email look alike string.

**Comment by Captainkirkdawson** [comment]
What makes you think the header email address is used?

FR makes no use of the header email address other than to retain it and display it as the email address that was in the header.

An email is sent to the email address of the userid of the file owner but only when they have asked for the file to be processed as soon as possible.

Perhaps it is time to use a different email address for our sender?

**Comment by edickens** [comment]
It is too complicated to get the evidence which is way down my pile
    of emails. But if I remember correctly, the email address in the
    Profile is correct but the email address in the message was
    different and bounced.  But I have received loads of messages
    generated from different sources.
    
    I will keep the evidence when it happens again.
    
    Since all the reg-web emails only come to me, then perhaps it is
    time, at least for a while, to use a different system so that the
    traffic can be monitored so that the system can be improved. 
    Suggestions please Pat.
    
    E
    
    On 25/10/2015 15:14, Kirk Dawson wrote:
    
    
      What makes you think the header email address is used?
      FR makes no use of the header email address other than to
        retain it and display it as the email address that was in the
        header.
      An email is sent to the email address of the userid of the file
        owner but only when they have asked for the file to be processed
        as soon as possible.
      Perhaps it is time to use a different email address for our
        sender?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Exploring the use of additional senders

**Comment by Captainkirkdawson** [comment]
With the change in senders there are few bounced emails. Those from uploads are being sent to coordinators for action
