### ISSUE TITLE
Replace report wording not correct?

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#623]
When someone uploads instead of replacing, the report wording is contradictory.

**Comment by edickens** [comment]
Should this messages have a "NOT" in it? This looks as if it has been processed so why would one then need to replace?  E

Error Message: The upload with file name WRYHAWBA3.CSV was unsuccessful because {:file_name=>["File already exists and has been processed. You need to replace the existing file"]}

**Comment by Captainkirkdawson** [comment]
Do not agree. Perhaps a change in tense

It says  "The upload with file name WRYHAWBA3.CSV was unsuccessful"

The reason   "File already exists and has been processed"

It tells you what to do " You need to replace the existing file"

**Comment by edickens** [comment]
It sounds to me that the file has been processed and entered into
    the database.
    
    I suggest we use "rejected" instead of "processed".
    
    I understand what you mean by the fact that the file has been worked
    on and so processed, but I read it that it had completed processing.
    
    E
    
    On 27/10/2015 15:14, Kirk Dawson wrote:
    
    
      Do not agree. Perhaps a change in tense
      It says "The upload with file name WRYHAWBA3.CSV was
        unsuccessful"
      The reason "File already exists and has been processed"
      It tells you what to do " You need to replace the existing
        file"
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Clearly the wording is confusing you. This is the upload. It did not upload. Why because the file already existed. The user needs to use the replace option not the upload.
