### ISSUE TITLE
Password change notification different from other updates

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#625]
Currently the same message is sent on both a password reset and the initial password set. This is because we use the former to achieve the latter. Coordinators are complaining that they are getting too many reset messages

**Comment by Captainkirkdawson** [comment]
Have added code that so that notification will only be sent when the reset is within 5 days of the userid creation; people have just one day to action this first step so this should work

**Comment by edickens** [comment]
That should do.  Will this be mentioned in the Help?
    
    Is any notification sent if someone changes Syndicate?  E
    
    On 16/11/2015 01:01, Kirk Dawson wrote:
    
    
      Have added code that so that notification will only be sent
        when the reset is within 5 days of the userid creation; people
        have just one day to action this first step so this should work
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
wrt "Is any notification sent if someone changes Syndicate?  E"

why would it? this is simply a password reset!
