### ISSUE TITLE
Use multiple sending addresses

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#626]
We currently use reg-web@freereg.org.uk to distribute emails from FR. This address has existed for 20 years and now has a "history" with ISPs. Also all returned mails and anyone who replies go to its alias. EricD and BenL.
It is suggested we modernize our addresses with more current aliases.
eg
freereg-registration@freeukgen.org.uk with returns to ?; 
freereg-processing@freeukgen.org.uk with returns to SAs and ?
freereg-contacts@freeukgen.org.uk with returns to ?
freereg-feedback@freeukgen.org.uk with returns to SAs and ?
freereg-genera@freeukgen.org.ukl with returns to ?
Possibly others and other suggestions

**Comment by PatReynolds** [comment]
I am not sure what the addresses would be used for, and hence who they should return to.

**Comment by Captainkirkdawson** [comment]
They will be used by the system when it sends a message to a user. 
eg when dealing with registration matter the server will send messages from freereg-registration@freeukgen.org.uk
When sending out emails on the results of their processing of files the sever will send messages from freereg-registration@freeukgen.org.uk
Similarly when responding to contact and feedbacks we will use the proposed email addresses as the sender.
In terms of return ie if a user responds to the message or it gets bounced who needs to deal with it.

Processing. I do; Registration matters? volunteer coordinator?? contacts our contacts coordinator?

**Comment by Captainkirkdawson** [comment]
This issue is on the critical path to all matters dealing with emails and email distribution and no work can start on them until we make a decision on how we are going to proceed with our sending addresses and our internal roles systems. It would be a big mistake to continue with the current practice of sending all emails from reg-web so I will not proceed by default.

To be clear. When FR sends a message TO someone it must display a FROM sender. This is a requirement of all email systems. ISPs use this information to return undelivered messages. They also use it to determine its "habits" and  black lists identified  spammers (including those that exhibit the characteristics of spamming). Mail needs the from-sender to enable people to reply and stop further mail or to respond the the actual mail. We currently use reg-web@freereg.org.uk as our FROM. It has been around for 20 years and has a history being used by spammers and others so is often blocked by ISPs.

The FreeUKGEN has a mail system where responses to FROM go to.

These are maintained in a system accessed solely by those with access to the cvs repository. Primarily Lemon/ Barrie/BenL and DaveM

reg-exec: EricJDickens, MarkJames, JohnPingram, DaveMayall, MickClaxton
reg-data: EricJDickens, MickClaxton, EricBooker
reg-volunteer: EricJDickens, DoreenOlds
reg-register: EricJDickens
reg-england: JohnPingram, DoreenOlds, EricJDickens
reg-wales: JohnPingram, EricJDickens, SandraJones,  SheilaJames 
reg-scotland: JohnPingram, EricJDickens
reg-web: BenLaurie, EricJDickens
reg-webmaster: BenLaurie, EricJDickens, support
reg-corrections: RobertWilkins, MickClaxton
reg-finance: EricJDickens, CamillavonMassenbach
reg-fichecopies: KevinHowell3, MickClaxton
reg-lists: JohnPingram, EricJDickens
reg-winreg: MikeFry, EricJDickens
reg-image: EricJDickens

I had suggested 
freereg-registration@freeukgen.org.uk with returns to ?; 
freereg-processing@freeukgen.org.uk with returns to SAs and ?
freereg-contacts@freeukgen.org.uk with returns to ?
freereg-feedback@freeukgen.org.uk with returns to SAs and ?
freereg-genera@freeukgen.org.ukl with returns to ?

But  received little guidance so perhaps we could use 

reg-volunteer for registration matters 
reg-corrections for the data error contact messages

we would still need  something for contacts and processing messages.

perhaps  we could have Lemon add
processing@freereg.org.uk with returns to EricJDickens
contacts@freereg.org.uk with returns to Daimian if he is working out? Lemon would have to add

FR uses the person_role to decide who should receive copies of mail that is sent. ie. the TO for copies. It does not use the aliases as it has no access to them.

.

**Comment by edickens** [comment]
I await Pat's decision on this and perhaps Barrie needs to be
    involved.
    All the reg-x@freereg.org.uk get Spam and filtered out from when
    they were embedded unprotected in FR1.  So I suggest you use new
    ones and protect them.  We should not then get Spam and not be
    blocked.
    E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 13/11/2015 19:22, Kirk Dawson wrote:
    
    
      This issue is on the critical path to all matters dealing with
        emails and email distribution and no work can start on them
        until we make a decision on how we are going to proceed with our
        sending addresses and our internal roles systems. It would be a
        big mistake to continue with the current practice of sending all
        emails from reg-web so I will not proceed by default.
      To be clear. When FR sends a message TO someone it must display
        a FROM sender. This is a requirement of all email systems. ISPs
        use this information to return undelivered messages. They also
        use it to determine its "habits" and black lists identified
        spammers (including those that exhibit the characteristics of
        spamming). Mail needs the from-sender to enable people to reply
        and stop further mail or to respond the the actual mail. We
        currently use reg-web@freereg.org.uk
        as our FROM. It has been around for 20 years and has a history
        being used by spammers and others so is often blocked by ISPs.
      The FreeUKGEN has a mail system where responses to FROM go to.
      These are maintained in a system accessed solely by those with
        access to the cvs repository. Primarily Lemon/ Barrie/BenL and
        DaveM
      reg-exec: EricJDickens, MarkJames, JohnPingram, DaveMayall,
        MickClaxton
        reg-data: EricJDickens, MickClaxton, EricBooker
        reg-volunteer: EricJDickens, DoreenOlds
        reg-register: EricJDickens
        reg-england: JohnPingram, DoreenOlds, EricJDickens
        reg-wales: JohnPingram, EricJDickens, SandraJones, SheilaJames 
        reg-scotland: JohnPingram, EricJDickens
        reg-web: BenLaurie, EricJDickens
        reg-webmaster: BenLaurie, EricJDickens, support
        reg-corrections: RobertWilkins, MickClaxton
        reg-finance: EricJDickens, CamillavonMassenbach
        reg-fichecopies: KevinHowell3, MickClaxton
        reg-lists: JohnPingram, EricJDickens
        reg-winreg: MikeFry, EricJDickens
        reg-image: EricJDickens
      I had suggested 
        freereg-registration@freeukgen.org.uk
        with returns to ?; 
        freereg-processing@freeukgen.org.uk
        with returns to SAs and ?
        freereg-contacts@freeukgen.org.uk
        with returns to ?
        freereg-feedback@freeukgen.org.uk
        with returns to SAs and ?
        freereg-genera@freeukgen.org.ukl
        with returns to ?
      But received little guidance so perhaps we could use 
      reg-volunteer for registration matters 
        reg-corrections for the data error contact messages
      we would still need something for contacts and processing
        messages.
      perhaps we could have Lemon add
        processing@freereg.org.uk
        with returns to EricJDickens
        contacts@freereg.org.uk
        with returns to Daimian if he is working out? Lemon would have
        to add
      FR uses the person_role to decide who should receive copies of
        mail that is sent. ie. the TO for copies. It does not use the
        aliases as it has no access to them.
      .
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by PatReynolds** [comment]
I am not sure what I am being asked to decide.
@freeukgen.org.uk vs @freereg.org.uk?  I'd stick with the latter, if the address is not so compromised that anything@freereg.org.uk is going to be treated as spam.

What comes before the @?
Kirk's suggestions all sound fine.

I would like to see processing@ and contacts@ follow the same format as the others - i.e. reg-contacts@, reg-processing@

freereg-registration@freeukgen.org.uk with returns to reg-register
freereg-processing@freeukgen.org.uk with returns to reg-processing
freereg-contacts@freeukgen.org.uk with returns to reg-contacts
freereg-feedback@freeukgen.org.uk with returns to SAs and reg-contacts
freereg-genera@freeukgen.org.ukl with returns to SAs and reg-contacts

(last one should be freereg-general, I think)

Hope that helps, but if you are thinking 'aahhgghh, no, Pat has completely misunderstood what type of emails get sent from freereg-contacts' or similar, you will have to give me more information about the type of emails, and who needs to know that they have failed if I'm to guess where they go.

**Comment by Captainkirkdawson** [comment]
Thank you Pat. The first paragraph is what I really needed. We will use @freereg.org.uk.

**Comment by edickens** [comment]
I think the @freereg.org.uk that got compromised and attract Spam
    are those on the FR1 website.  Those are ..
    
    reg-web@
    reg-exec@
    reg-corrections@
    reg-volunteer@
    reg-england@
    reg-wales@
    reg-scotland@
    
    In fact pretty well all of the old ones.  So if you choose some new
    ones, protect them by scrambling them, then they should be fine.
    
    E
    
    
    On 16/11/2015 14:27, PatReynolds wrote:
    
    
      I am not sure what I am being asked to decide.
        @freeukgen.org.uk vs @freereg.org.uk? I'd stick with the latter,
        if the address is not so compromised that anything@freereg.org.uk
        is going to be treated as spam.
      What comes before the @?
        Kirk's suggestions all sound fine.
      I would like to see processing@ and contacts@ follow the same
        format as the others - i.e. reg-contacts@, reg-processing@
      freereg-registration@freeukgen.org.uk
        with returns to reg-register
        freereg-processing@freeukgen.org.uk
        with returns to reg-processing
        freereg-contacts@freeukgen.org.uk
        with returns to reg-contacts
        freereg-feedback@freeukgen.org.uk
        with returns to SAs and reg-contacts
        freereg-genera@freeukgen.org.ukl
        with returns to SAs and reg-contacts
      (last one should be freereg-general, I think)
      Hope that helps, but if you are thinking 'aahhgghh, no, Pat has
        completely misunderstood what type of emails get sent from
        freereg-contacts' or similar, you will have to give me more
        information about the type of emails, and who needs to know that
        they have failed if I'm to guess where they go.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Don"t understand your comment about scrambling them. FR has no email
address on any of its webpage.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
In which case no problem if those who skim the websites cannot find the 
ones you use to send the emails.  E

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by AlOneill** [comment]
Er, there are a couple -- my fault. They are obfuscated to a degree, but could be made to point to Contact form, together with appropriate subject/recipient. Will check details...

**Comment by Captainkirkdawson** [comment]
That's why we use the contact form submission processes so that we never
publish an email address. So we should always point to it.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
I used this in FR1 http://www.albionresearch.com/misc/obfuscator.php
    but not the JavaScript version which I think you could use now.  E
    
    On 16/11/2015 15:33, AlOneill wrote:
    
    
      Er, there are a couple -- my fault. They are obfuscated to a
        degree, but could be made to point to Contact form, together
        with appropriate subject/recipient. Will check details...
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by AlOneill** [comment]
All fixed to point to Contact form. Only obfuscated address now is for Damien -- can Damien be contacted via Contact form yet?

**Comment by Captainkirkdawson** [comment]
No I have been waiting and waiting for someone to tell me if he is to be
the sole recipient of Contacts see #576

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
I suggest not.  I am happy to get a copy provided that this is shown
    in the headings.
    
    My reason is that sometimes the messages are technical, or they
    could be because they have not had a reply from Damien in which case
    I will reply and copy Damien.  It takes me no time to scan read the
    message and then delete it.  Doing a reply when I have to look
    things up on the website is what takes the time.
    
    And don't forget my request for a sequence number in the Subject
    line in the way that the github "Report a problem" messages do. 
    Otherwise I just have hundreds of messages with the same subject
    line.
    
    E
    _____________________________________

    On 16/11/2015 16:14, Kirk Dawson wrote:
    
    No I have been waiting and waiting for someone to tell
      me if he is to be
      the sole recipient of Contacts see #576
      
      Kirk Dawson
      Fairmont Hot Springs, B.C.
      V0B 1L1

**Comment by AlOneill** [comment]
@edickens Cannot use raw JS on a Refinery page.

**Comment by Captainkirkdawson** [comment]
Lemon has established the new aliases for us. Next step is to put them to us
