### ISSUE TITLE
System exceptions

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#627]
We are getting  a number of system exceptions each day caused by coordinators making a change (say a delete) then hitting the back button and reselection the thing they just changed.
The back button does not refresh the page hence the system crashes because the thing they changed is gone!
This is why we introduced the breadcrumbs!!! so that they got a fresh copy.
With some effort we can try to catch these errors so they are not exceptions.
But if only they used the breadcrumbs or refreshed after a browser back

**Comment by edickens** [comment]
Could this also apply to Transcribers?  For example if they Edit an
    entry.  I ask because it is a bit easier to get Coordinators to take
    care until we fix it, but there are too many transcribers.
    Also, very few will see this message, it is not distributed to
    Coordinators or Transcribers, if you want them to know that you want
    them to use the Breadcrumbs.  E
    On 28/10/2015 22:04, Kirk Dawson wrote:

    
      We are getting a number of system exceptions each day caused by
        coordinators making a change (say a delete) then hitting the
        back button and reselection the thing they just changed.
        The back button does not refresh the page hence the system
        crashes because the thing they changed is gone!
        This is why we introduced the breadcrumbs!!! so that they got a
        fresh copy.
        With some effort we can try to catch these errors so they are
        not exceptions.
        But if only they used the breadcrumbs or refreshed after a
        browser back
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
It is much less likely that they will cause a system exception. The latter only occurs if a document number gets changed or deleted. This happens when a batch/record is deleted; when it is relocated somewhere else, when it is merged into another register/church or place. It does not happen if you edit a record. What happens then is if you do browser back you will see the old record and then I expect people to complain that the edit does not work!
I am sorry but after the past 3 days of comments about how bad the system is and that "nothing would be better" than what we have now there is NO way I will start any dialogue with them on ANY subject.
I do not see this being fixed any time soon; it is not a system bug

**Comment by Sherlock21** [comment]
Breadcrumbs instead of Browser Back Button is the problem - if i may be so bold -.
The word Breadcrumbs is only in my vocabulary as the bits one leaves on the breakfast table. and nothing to do with a location on a web page.
If the place to click, in order to find & use FR Breadcrumbs, showed up as a link in the usual way when one runs the mouse over it, then it might ring a bell with the users. 

Speaking from my personal experience, we have had years of getting into the habit of Browser Back Button to get from B to A,  maybe a little note on screens where one needs to use the Breadcrumbs method would be a great reminder & help stop these crashes?

**Comment by edickens** [comment]
Can a note in Bold be put in the "Known problems" Members logged in
    page to say that Breadcrumbs (and explain what they are as it is not
    a word that most use) and not the back button must be used for the
    website to work,otherwise it will cause problems?  This is stated in
    the Cookies acceptance banner, but needs to be repeated.  E
    
    On 29/10/2015 08:50, Sherlock21 wrote:
    
    
      Breadcrumbs instead of Browser Back Button is the problem - if
        i may be so bold -.
        The word Breadcrumbs is only in my vocabulary as the bits one
        leaves on the breakfast table. and nothing to do with a location
        on a web page.
        If the place to click, in order to find & use FR
        Breadcrumbs, showed up as a link in the usual way when one runs
        the mouse over it, then it might ring a bell with the users. 
      Speaking from my personal experience, we have had years of
        getting into the habit of Browser Back Button to get from B to
        A, maybe a little note on screens where one needs to use the
        Breadcrumbs method would be a great reminder & help stop
        these crashes?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by sean-wood** [comment]
I agree that there is a problem with users using the browser back button on lots of different websites instead of the breadcrumb menu option.

I also think that an explanation needs to be added, I will create a ticket on the waffle for this.


Kind Regards


Sean Wood
Director and Principal Consultant
Sands View I.T. Consulting Ltd.

E: swood@sandsviewitconsulting.co.uk<mailto:swood@sandsviewitconsulting.co.uk>
T: +44 (0) 7771 824 315
W: www.sandsviewitconsulting.co.uk<http://www.sandsviewitconsulting.co.uk/>

**Comment by sean-wood** [comment]
Would it be worth  disabling the back button with a coded solution. I appreciate this is not easy particularly on the older browsers

**Comment by edickens** [comment]
But isn't this a large amount of programming as it will be needed on
    all pages?  We need to get everything working first so that we can
    get a real feel for how the website works.  E
    
    On 29/10/2015 10:02, sean-wood wrote:
    
    
      Would it be worth disabling the back button with a coded
        solution. I appreciate this is not easy particularly on the
        older browsers
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
I had an idea: just colour the Breadcombs in a different  colour to all the other green headers and labels so it stands out. - say Blue but same font size as at present. 
Minimum effort I hope.

Then the note on the front page need only be short, and refer to the coloured breadcrumbs and everyone is in step.
And don't inhibit the Browser Back button - as the user may need to use it for other purposes.
