### ISSUE TITLE
Performance Issue with search

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#635]
Observed massive spike in response time on colobus at 15:44 today 2 Nov
![performance of fr](https://cloud.githubusercontent.com/assets/2874694/10889219/d6b4e948-814d-11e5-884a-4fb896be1f18.JPG)
This was noticeable to the user community with refusals to accept new connections.
Explored the logs and found that the same search had been entered 4 times. 15:44:02 15:44:58 and twice at 15:49:01.

The search was quite complex
Parameters: {"utf8"=>"✓", "authenticity_token"=>"Gd57wkbarWSBq6LdVgUQFpEl/0UOgEhbUfcb8MPtHAg=", "search_query"=>{"last_name"=>"davies", "first_name"=>"", "start_year"=>"1780", "end_year"=>"1820"
"chapman_codes"=>["", "SOM"], "place_ids"=>["53cd497feca9ebee4f008bb6"], "record_type"=>"ba", "inclusive"=>"false", "search_nearby_places"=>"true", "fuzzy"=>"true", "region"=>""}, "button"=>""}

I cannot see that these searches ever completed

At similar times the following search was executed 7 times
Parameters: {"utf8"=>"✓", "authenticity_token"=>"rTeg/t9QjsOWPnYgnztb0dIU/g+SGaKNv944NAIpsWA=", "search_query"=>{"last_name"=>"clark", "first_name"=>"", "start_year"=>"1720", "end_year"=>"1735", "chapman_codes"=>["", "NFK"], "record_type"=>"ma", "inclusive"=>"false", "search_nearby_places"=>"false", "fuzzy"=>"true", "region"=>""}, "button"=>""}

One of these took 1338054ms to complete!!!!!!!!

It may be time to consider prioritizing some of our stories that were aimed at limiting this type of action.

**Comment by edickens** [comment]
From my experience today in doing a search when we were busy, I can see 
the person hitting the Search Button again before the search has 
finished.  If they don't look at their browser's "Waiting" icon they 
could try again.  I think a more positive "Processing" icon might stop 
this, or we need to see if a search is from the same person and report 
that "We are already working for you - do you want to cancel this 
search?"  E

**Comment by Captainkirkdawson** [comment]
We have a number of stories to address various aspects of this issue; they like so many others, are just sitting there. We really don't need new ideas we need to do some of the things we know we need to do

**Comment by edickens** [comment]
Hi Kirk.
I agree that we don't need new ideas, but these will come to light as 
people use the website.  So is anyone collecting them for future 
versions or are we going to have to go through the process of asking for 
ideas some time in the future?  E

**Comment by Captainkirkdawson** [comment]
We have 2 specific stories

#495 #182

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Another example today
![f2a](https://cloud.githubusercontent.com/assets/2874694/10921086/d9ffe09c-8230-11e5-8b8d-6ed440b426b4.JPG)

The worst search times for today. The numbers 1
![f2b](https://cloud.githubusercontent.com/assets/2874694/10921101/efa8a1e0-8230-11e5-9b31-16db2decc220.JPG)

**Comment by Sherlock21** [comment]
I am sure that I have been guilty of starting off some long searchers. and once realising it, I would have dearly liked to have a CANCEL SEARCH. so i could properly stop it, so i could write the search again.

Would this be a solution to introduce now? - at least stop those like me trying to be helpful.

Analysing the elements of these long long searchers, what's the worst 4 offenders?
Trying to cover too many user specified Counties to make ones 3 max?
Or too many individual Place Names instead of take the whole county, then pick one place at a time? - ie dont allow more than 1 Place name to be selected except under Whole County?
Or year range?

I think we should attempt to stop these long running queries at least until the Servers can do a better job.

**Comment by AlOneill** [comment]
@Sherlock21 Try Esc -- depends on browser

**Comment by Captainkirkdawson** [comment]
But the point I am making is that once started a search will run until it
finishes; all you are doing is breaking the connection; the search will
continue to run on the server. There is no cancel search period in the
current set up.

So while I think it appropriate to have a connection time out and provide
the user with a message, we must either make the search very efficient or
NOT start it at all.


Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by AlOneill** [comment]
Ah -- I get it. I've contributed to horribly long searches too -- especially whilst testing the wildcard option on test3. Am not competent to comment on the options you give... but agree that something is needed fairly soon.

**Comment by Captainkirkdawson** [comment]
Have added the search index to the search queries collection and report to see if we can see any patterns

**Comment by Captainkirkdawson** [comment]
Experimenting with the following search 
![search1](https://cloud.githubusercontent.com/assets/2874694/11198497/3e8ac13e-8c82-11e5-86e6-5f295fadb8eb.JPG)
On test3 with no competition it took 495 seconds.

Looking at the analysis report it would seem that it does not put any bounds on the years.
![search2](https://cloud.githubusercontent.com/assets/2874694/11198530/8a55f9da-8c82-11e5-9129-b1353781bc42.JPG)

**Comment by Captainkirkdawson** [comment]
A similar search but one that puts a name in the forename field (Lincolnshire to make sure it was not using cached information) was extremely fast
![search3](https://cloud.githubusercontent.com/assets/2874694/11198644/a0c4fc9c-8c83-11e5-85fa-0be6f6547041.JPG)
but is still puts no bounds on the date

**Comment by Captainkirkdawson** [comment]
Again going to Somerset and selecting a specific place is fast
![search4](https://cloud.githubusercontent.com/assets/2874694/11198716/6b1ee7c8-8c84-11e5-8203-f4f6c404de6b.JPG)

**Comment by Captainkirkdawson** [comment]
Remove the year limit and the search completes in 2 sec but one maxes out on the limit of results

**Comment by benwbrum** [comment]
I believe that--at minimum--we should investigate wildcard search
performance for 1.4.  (And by "investigate", I mean "Ben chases down the
perfomance stats from the queries already executed on test3 by the rest of
the team", not more work for all of you.)

**Comment by Captainkirkdawson** [comment]
These are not wildcard; that introduces another variable!!

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
Indeed,Kirk, I totally see where you are at.

but my point is: if we need to make changes, for the very reasons that you state, can't we be accommodating of the issue i made - which is the allow the user to terminate before the end?

EB

**Comment by edickens** [comment]
How about every second testing to see if Esc or Back has been used and 
if it has stop processing? E

**Comment by Sherlock21** [comment]
I would suggest the POSITIVE approach and provide a button on the search form: 'ABANDON SEARCH"
Much better than leaving the user to guess "What on earth do I do to get out of here?"

**Comment by edickens** [comment]
And that would presuppose that we have a box saying "Search in
    progress" and that has the Abandon button.  E
    
    On 17/11/2015 11:06, Sherlock21 wrote:
    
    
      I would suggest the POSITIVE approach and provide a button on
        the search form: 'ABANDON SEARCH"
        Much better than leaving the user to guess "What on earth do I
        do to get out of here?"
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
Indeed. a good extra feature instead of leaving the user wondering where its got to.
EB

**Comment by Captainkirkdawson** [comment]
Sometimes you guys really take the biscuit!!, How many time do I have to say that with the current drivers we use THERE IS NO STOPPING a search. IT RUNS TO COMPLETION. Stop trying to propose solutions until we get much better handle on where issues really exist and what we can do about them,

**Comment by Captainkirkdawson** [comment]
Rebuilding  indexes on test3 to make sure we have a good base

**Comment by benwbrum** [comment]
Thanks, @Captainkirkdawson.  You mentioned on the call yesterday that a different MongoDB/Ruby driver has the ability to kill off long-running queries.  Is that the mongo ruby driver, or something different?

**Comment by Captainkirkdawson** [comment]
Ben please read my long post on this thread about the issue posted 3 days
ago it provides all the background you need

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by benwbrum** [comment]
@Captainkirkdawson , I've read your write-up, and as usual you've explored essentially everything.  The only alternative I can come up with is to write a cron job on each server which wakes up every minute, queries mongo directly for long-running queries on the search_records collection and kills them off.  Do you think that's worth exploring?

**Comment by Sherlock21** [comment]
the question which occurs to me: what does everyone else do ?

Ericb

**Comment by benwbrum** [comment]
I suspect that everyone else upgrades their system/drivers/database more
frequently than we do.  We've got a story for server upgrades, but it's on
the back burner.

Ben

**Comment by Captainkirkdawson** [comment]
Personally I would invest in ensuring efficient searching. Although a small investment in looking at the kill option is likely worth it providing we are sure that it is a clean kill.
