### ISSUE TITLE
Add UserID and name to Uploaded report

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#639]
Particularly for an SC who has uploaded a file, it is useful to confirm where it has gone.

**Comment by edickens** [comment]
In the attached message, there is no way to know who or which UserID was used.  E


![capture](https://cloud.githubusercontent.com/assets/8876165/11014182/a79903ea-8523-11e5-8459-bea50f1e7755.JPG)

**Comment by Captainkirkdawson** [comment]
But its your file!!!!!!. It went to you as the owner. Copies to you as SC or CC have Copy in the subject line.
