### ISSUE TITLE
Display of Places in a county by a coordinator times out when there are a large number of Places

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#640]
[See this exception on Errbit] [production][freereg1_csv_files#index] 
Caused by attempting to list too many files when system busy

**Comment by Captainkirkdawson** [comment]
SOM has 4325 files and NFK 7939 files. Attempting to list all of these in one display causes indigestion. A by product of the move away from paging

**Comment by Sherlock21** [comment]
Well.....given that the object is to increase our transcription coverage, more Counties will go the same way won't they.
So for my twopennyworth, I would be quite happy to return to Paging.

**Comment by Captainkirkdawson** [comment]
Contacted the 3 main coordinators involved. They are open to change.
Suggested.
Starting to look at a couple of options that build on what I have done with the Transcriptions pages (Was Database Contents) it was deployed overnight.

What I could do is put an alphabetic selection on the Place names; 

File names are a little tougher as the county code means that they would all fall in the same bin. Could do an alphabetic group selection on the 4th character. But likely a paging in blocks of 750 would likely be as easy and as logical.

For date of load (Oldest/youngest) the middle is likely of no interest; so just providing the first 750 are likely all that are needed.

For userid we could do the alphabetic group selection.

Comments

Work on hold until plan developed

**Comment by edickens** [comment]
750 should do.
A minor point.  When doing the Alpha range box, can it be big enough so 
that no scrolling is needed, and also, since one or the other has to be 
selected, action the request as soon as clicking the choice rather than 
than having to press a Select button.
E

**Comment by Captainkirkdawson** [comment]
Coordinators involved are supportive of the proposed solutions

**Comment by Captainkirkdawson** [comment]
Phase 1 that deals with display of places has been developed and is under test. It uses a dynamic alphabetic selection based on the number of records in the county. Will look at also deploying this for the Transcribers function if it proves effective. Would likely help to have a rake task added to the nightly update that computes the records for a county and we use that rather than real time counting.

**Comment by Captainkirkdawson** [comment]
Phase 2 uses a 500 entry pagination  with internal scrolling on file displays. Most counties/syndicates will not notice a difference but those counties/syndicates with thousands of files will notice improved load times and there will be less impact on the researcher. The 500 page is set in Freereg_option_constants
