### ISSUE TITLE
Transcriber does not know why they cannot log in

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#643]
I get quite a few requests from SCs who have been asked by transcribers why they cannot log in.

**Comment by edickens** [comment]
When someone cannot log in, (rather like when I tried when Inactive) the transcriber does not know why they cannot log in.  They just get sent back to the home page.  They need a reason and advice on what to do, even it if is to refer to a particular Help page.  E

**Comment by Captainkirkdawson** [comment]
Why raise this again. We agreed to address it 505.

The only reason that they cannot login and end up back at the search page
is they are inactive.

Password and userid issue end up back at the login page with a message.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
I tried to filter on "login" and "log in" and did not get #505, so
    thought it had not been entered.  The problem was because a
    transcriber complained that they could not log in and they are
    Active.  So thought it was a wrong UserID or Password.  I have
    checked now and they do get a message, although it is the same
    colour and font as the text and could have been missed.  I missed it
    at first.
    
    Please close.  E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 09/11/2015 20:14, Kirk Dawson wrote:
    
    Why raise this again. We agreed to address it 505.
      
      The only reason that they cannot login and end up back at the
      search page
      is they are inactive.
      
      Password and userid issue end up back at the login page with a
      message.
      
      Kirk Dawson
      Fairmont Hot Springs, B.C.
      V0B 1L1
      
      On Mon, Nov 9, 2015 at 12:49 PM, Eric Dickens
      <notifications@github.com>
      wrote:
      
      > When someone cannot log in, (rather like when I tried when
      Inactive) the
      > transcriber does not know why they cannot log in. They just
      get sent back
      > to the home page. They need a reason and advice on what to
      do, even it if
      > is to refer to a particular Help page. E
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
<https://github.com/FreeUKGen/MyopicVicar/issues/643#issuecomment-155171140>
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.
