### ISSUE TITLE
Find the email address of a CC / SC or any UserID

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#644]
I need a facility to find an email address from any of these start points please:-
1) drill down on a UserID anywhere.
2) find the CC and SC - from knowing the County - say at the head of an All Places and Active Places list.
3) from knowing the Person't name.
4) from a list of FreeReg Post Names
so if I want to email a particular CC or SC, or Tranacriber then i can get to their email

**Comment by edickens** [comment]
These are SC actions.  Do you want these for yourself or is it a
    request for all CCs?
    
    The Database Contents gives the CC name, but deliberately does not
    give their email address to the world, to save Spam.
    
    But 4) is a good idea.  Or we could put the link to the CC or SC
    behind their name in the Database Contents, ONLY is you are logged
    in and are not a Researcher.
    
    Story needed.
    
    E
    
    On 12/11/2015 09:38, Sherlock21 wrote:
    
    
      I need a facility to find an email address from any of these
        start points please:-
        1) drill down on a UserID anywhere.
        2) find the CC and SC - from knowing the County - say at the
        head of an All Places and Active Places list.
        3) from knowing the Person't name.
        4) from a list of FreeReg Post Names
        so if I want to email a particular CC or SC, or Tranacriber then
        i can get to their email
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
To clarify: These were just for me as DM. So i can contact quickly, anyone I likely need to go to direct.

And the "Story" was supposed to be the first posting above, as usual.

**Comment by edickens** [comment]
Kirk can give you, as DM, some of the other options which have been
    programmed.
    
    Cheers E
    
    On 12/11/2015 10:14, Sherlock21 wrote:
    
    
      To clarify: These were just for me as DM. So i can contact
        quickly, anyone I likely need to go to direct.
      And the "Story" was supposed to be the first posting above, as
        usual.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
You already have it. Its called the Access Profile action

**Comment by Sherlock21** [comment]
thanks K

I had tried that before, but picking UserID as the start, it only gave me a very few to select from - like a few dozen.

I have worked it out now though: I/t takes ages to load the full list!and there was no clue as to the fact that this was still loading up.

Now I know that, fine. i Can live with it.

delete the job number please.

EB

**Comment by PatReynolds** [comment]
Thanks, all.  Closing this now.
