### ISSUE TITLE
Process files even if they are unchanged 1.3

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#646]

**Comment by edickens** [comment]
The overnight update sometimes does not process a file because it says it has not changed.  But the person who uploaded it would have done it for a reason.  Kirk's original reason was fine as it saved processing, but now the need has gone away and yet the re-upload could be needed, for example if the Place name has been changed then the file needs uploading again without amendment, but the present system will not accept it.  There are not many of these, but when they occur then the change is not made and I think data is being lost until the file is actually amend, and this may never happen.

**Comment by Captainkirkdawson** [comment]
Needs 610

**Comment by Captainkirkdawson** [comment]
Impact of doing this is minimal

**Comment by Captainkirkdawson** [comment]
IMplemented
