### ISSUE TITLE
Is there a way to avoid overnight updating? 1.3

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#647]
Overnight updating means that the transcriber does not know of errors until they get an email.

**Comment by edickens** [comment]
I would like all files to be processed immediately and there to be no overnight update.  There would then be no need to wait for the email to see if there are errors.  This will save a heavy load on the processor while updating by spreading the work over the day.  Or the entry into the database can be done overnight, because it is the indexing that takes the time, but a validation can be done immediately.  There is then no need for emails and the transcriber will not have continued making the same mistake, especially if it is a Place or Church name.

**Comment by Captainkirkdawson** [comment]
Dependent on 610

**Comment by PatReynolds** [comment]
#610 is 'Reviewing active members - not members of syndicate (MaryKay)' - was there another #610 now done?

**Comment by Captainkirkdawson** [comment]
There are 2 numbering schemes. 1 for features and 1 for issues.
Unfortunately we overlap.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
IMO it would be a mistake to add additional load to servers during prime time searches. Even if one initiated a processing immediately it could take an hour or more before it has finished processing so a report that it has finished is still likely needed. This should be reviewed in 6 months.
