### ISSUE TITLE
Batch complete marker

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#648]

**Comment by edickens** [comment]
I would like a "Batch complete" button on the Upload so that in the long term the RAP knows when a batch is still being worked on and the SC knows if the upload is just a backup or if it is complete and been sight checked.  This is an extra field in the Batch header.
This should be used for lots of other purposes as well as just informing the SC.  The batch should be locked to the transcriber so that they don't overwrite it.  This information is useful to a researcher when the range of years may look as if all the records are there when in fact entries are still being added.  This will also indicate when it is time to remove the batch from the RAP as it is no longer "In Progress".
If it can done now it will avoid having to go back and mark batches as complete when the RAP comes into use.

**Comment by edickens** [comment]
Has this been implemented?  Is that why it has been closed?  Or do
    you see it part of V1.5?  E
    
    On 13/04/2016 05:29, Kirk Dawson wrote:
    
    
      Closed #648.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by Captainkirkdawson** [comment]
Its a duplicate

**Comment by Captainkirkdawson** [comment]
See 532
