### ISSUE TITLE
Plan for batch validation 1.5

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#649]
There are a number of things coming up in V1.5 which might need a lot of discussion, now is a time to do this.

**Comment by edickens** [comment]
- Validation of batches
The batch record should be set up by the CC.  The transcriber then must load into this and accept the criteria
The batch record should have the range of years and entries must match these.
- Batch names
The batch name does not have to be a FR1 format name.  We have already had a file uploaded with a different name.   We can choose file names such as ​SSX-Arundel-8-1-1-3-GR-1742-1752 which gives a lot more information about the contents; matches the image server; and lets the transcriber look down their list of batches much better.

**Comment by Sherlock21** [comment]
I am in favour of us all using the same file and batch numbering style - rather than having everyone invent their own.
At an individual level, people will want the system they can remember and handle.
BUT for those who work across the whole patch, and spend a lot of time reading batch numbers, 2000 different numbering systems is the last thing that is helpful.

**Comment by edickens** [comment]
I think this depends on the structure being developed.  This will determine if facts need to be set up before transcriptions/images can be uploaded to the database.
For example we now have to have County/Place/Church set up otherwise work is rejected.  Do we need CCs to set up other fixed information before Images are uploaded?  And  then should transcriptions match these facts in order to ensure that we do not have lots of batches that later have to be reassigned.
To be approved for inclusion in the specification for V1.5 by Project Manager?

**Comment by richpomfret** [comment]
Happy to move this into 1.5. However, I would like to review this in our next pre-sprint (or perhaps our new roadmap meeting) and assess the priority.
