### ISSUE TITLE
Coordinators seeing tthe transcribers Help

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#653]
The Help is presented depending on the Role.

**Comment by edickens** [comment]
Coordinators are often asked to solve a problem and need to point the sender to where to look in the Help.  But a Coordinator cannot see the Transcribers section of the Help, or at least not easily.  If the selection under Help at the top Action level can have selections for Transcribers Actions, in the same way as it says Coordinators Actions, then they can tell the sender where to look.  This needs to go down all levels depending on the Role of the UserID.  E

**Comment by AlOneill** [comment]
To clarify: are you asking for a full Information for Transcribers section *sub-menu*, as well as the Information for Coords section sub-menu?

Or are you suggesting that Help in the *main navigation banner* has a drop-down choice for Coords of: Info for Coords; Info for Transcribers; and Researcher Help?

Or... ?

**Comment by edickens** [comment]
Hi Alison.  Coordinators have asked to see the Transcribers Help
    exactly as the transcriber sees it. This is so that they can answer
    questions.  E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 20/11/2015 18:35, AlOneill wrote:
    
    
      To clarify: are you asking for a full Information for
        Transcribers section sub-menu, as well as the
        Information for Coords section sub-menu?
      Or are you suggesting that Help in the main navigation
          banner has a drop-down choice for Coords of: Info for
        Coords; Info for Transcribers; and Researcher Help?
      Or... ?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by AlOneill** [comment]
They can already do this, using the link in the first para on Info for Coords.

I will add a little bit of text with the link so that they realise that Info for Transcribers = Transcriber Help.
