### ISSUE TITLE
Files reported as error free when they are not

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#660]

**Comment by Captainkirkdawson** [comment]
What is this please? How can we investigate such a story?

**Comment by edickens** [comment]
github would not let me add a comment so I have sent an email with
    the facts to the project team.  E
    
    On 18/11/2015 15:45, Kirk Dawson wrote:
    
    
      What is this please? How can we investigate such a story?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Sorry I no longer read the Google groups. Told you that  after the last confrontation with the coordinators.Too much distraction

**Comment by edickens** [comment]
Today I have had two people report that their file has not arrived in FR although they have had emails saying that it was processed.  This is one of them and this is the entry in the overnight update...

Now today I have had a data report saying the file NBLNEWBA has been uploaded but is not in my transcribers
Userid, so where is it?????????

cornwall	NBLNEWBA.CSVThe county code ï»¿+INFO is invalid and rejected or you have a blank record line  at line 0
cornwall	NBLNEWBA.CSVHeader_Error,First line of file does not start with +INFO it has # at line 1
cornwall	NBLNEWBA.CSVHeader_Error,I did not know enough about your data format to extract transciber information at header line 2 at line 2
cornwall	NBLNEWBA.CSVHeader_Error,I did not know enough about your data format to extract notes Information at header line 4 at line 4
cornwall	NBLNEWBA.CSV	processed  0 data lines for location NBL, Newcastle upon Tyne, All Saints,  , ;  0 unchanged and 0 removed.  4 header errors and 4 data errors

This is the message from the server...

From: freereg_processing <freereg_processing@freereg.org.uk>
To: harold <harold@reece-pinchin.co.uk>
CC: Doreenolds <Doreenolds@aol.com>; susanmarr58 <susanmarr58@yahoo.co.nz>
Sent: Wed, 18 Nov 2015 5:54
Subject: cornwall/NBLNEWBA.CSV was processed by FreeREG at 2015-11-18 05:54:22 +0000

Harold,
The file submitted for processing has been completed. We processed 7623 records and there were 0 data errors and 0 header errors. If there were any errors you will need to review the on-line information for this file to see the details.
The FreeREG Team

At tonight's Scrum I would like to recommend that Kirk rewrites the Upload as a matter of urgency, but we need to discus how it will work first.  Transcribers are getting worried.

**Comment by Sherlock21** [comment]
Eric

Who is the userid for this one.? 
ericb

**Comment by edickens** [comment]
The SC is Doreen (ENG) but the CC EricW (NBL) and the UserID cornwall.  E

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
The file has already been replaced today so any significant investigation is impossible.

**Comment by edickens** [comment]
But how because there has not been an update since last night.  The
    report I showed was from this morning's update.  E
    
    On 18/11/2015 17:03, Kirk Dawson wrote:
    
    
      The file has already been replaced today so any significant
        investigation is impossible.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
The user has already uploaded a replacement file and its waiting for
tonight's processing slot so how can I possibly investigate what happened
with a file that no longer exists.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Ah! well.  Will try again when one crops up.  E

_____________________________________

**Comment by Captainkirkdawson** [comment]
Except it took 30 minutes to delete nearly 8000 records!

There are already nearly 100 files waiting for processing tonight with this
one first in the queue! Suspect it could be long night.

Most of the uploads look like people changing register types. What a waste
of time and resources. Suspect this will go on for months

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
We can stop it and get the CC to use Relocate.  But it is part of the 
debate on whether you want to do the rewrite of the update soon.  I did 
say recently that I think that there could be 30,000 files that need 
changing.  E

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
Just noticed that this was processed the previous night as well and died with the same error

**Comment by edickens** [comment]
Yes.  But the problem is that it was reported as uploaded error free
    to the transcriber so they added more.  I send my reports to the CC
    and they have to pass them on.  E
    
    On 18/11/2015 17:49, Kirk Dawson wrote:
    
    
      Just noticed that this was processed the previous night as well
        and died with the same error
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
They will need to show me such a message.

The message sent to a user has the following form

The file submitted for processing has been completed. We processed <%=
@records%> records and there were <%= @errors%> data errors and <%=
@headers%> header errors. If there were any errors you will need to review
the on-line information for this file to see the details.</p>

The log shows the following information
cornwall NBLNEWBA.CSV processed  0 data lines for location NBL, Newcastle
upon Tyne, All Saints,  , ; 0 unchanged and 0 removed.  4 header errors and
4 data errors

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
cornwall NBLNEWBA.CSV processed  0 data lines for location NBL, Newcastle
upon Tyne, All Saints,  , ; 0 unchanged and 0 removed.  4 header errors and
4 data errors

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Here is the report..
    
    From: freereg_processing
      <freereg_processing@freereg.org.uk>
      To: harold <harold@reece-pinchin.co.uk>
      CC: Doreenolds <Doreenolds@aol.com>; susanmarr58
      <susanmarr58@yahoo.co.nz>
      Sent: Wed, 18 Nov 2015 5:54
      Subject: cornwall/NBLNEWBA.CSV was processed by FreeREG at
      2015-11-18 05:54:22 +0000
      
      
        
          Harold,
          The file submitted for processing has been completed. We
            processed 7623 records and there were 0 data errors and 0
            header errors. If there were any errors you will need to
            review the on-line information for this file to see the
            details.
           The FreeREG Team
        
      
    
    
    
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 18/11/2015 18:31, Kirk Dawson wrote:
    
    cornwall NBLNEWBA.CSV processed 0 data lines for
      location NBL, Newcastle
      upon Tyne, All Saints, , ; 0 unchanged and 0 removed. 4 header
      errors and
      4 data errors
      
      Kirk Dawson
      Fairmont Hot Springs, B.C.
      V0B 1L1
