### ISSUE TITLE
Overnight processing performance

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#661]
Kirk may not have seen this message that I did for discussion

**Comment by edickens** [comment]
> Hello everyone,
>
> I'm doing this as an email instead of a Story as it will be a long email and I don't want it to go further until I have clarified my thinking.
>
> The overnight update is taking huge amounts of processing and we have not really got going yet.  So why is this the case?
>
> To analyse Sunday 15 November..
>
> The footer of the home pages said on Tuesday 17th that 14,312 records had been added in the 24 hours to midnight Monday 16th.  So this would include the Sunday night update and any files uploaded immediately on Monday 16th.  Assuming that the latter is small, then 95,914 records were selected for processing, 20,676 Unchanged, 44,982 were changes to Place/Church/Register type, 97,603 were created.  That makes a total of 140,896 records were processed at 336ms = 789 minutes.
>
> So what is going on...
>
> - Many register types are being changed from "Unspecified" to PR.
>
> - Many files being uploaded are just having extra records added, but all are processed.
>
> - No files were unchanged, one had a bad character, three did not exist, which means that they had been uploaded twice and so had already been processed.
>
> Recommendations...
>
> - Changing Register Type is better done using Relocate, but this is only open to Coordinators.  Suggest we offer Transcribers the Relocate.  Or we tell Transcribers to just sent a list to their CC for them to use Relocate.  But remember that every time a Church has had its Register Type corrected, the "Unspecified" is left as an entry with no batches.  The CC has to delete this, or we need to have a tidy up process that runs from time to time.  This will be for "Unspecified" only.  These register types should not be created any more.
>
    I agree that using "Relocate" is the slick way of changing Register type. BUT
Having seen the problems that some CC's have got involved in, I am reluctant to support this option as a means of reducing server work.
If CC's did the Relocate, they could do the tidy up at the same time.


> - There could be as many as 30,000 "Unspecified" Register Type batches.  Do these really need changing?  Why not just correct the Register Type when working on a batch.
>
    I think the presence in the Search report of Unspecified looks as though our records are less than good. I know we had nothing to put in there, but a purge on this would put out a better image
 
> - Kirk wants to rewrite the validation and upload, and this will be a good time to take a fresh look at the process in the light of experience.
>
> - The files being added to normally have records added at the end. So the new upload and existing files should be compared from the start and identical entries ignored.  Once a change if found, process from there, rather than process everything.  This could leave only about 10% that needs processing.
>
> - Indexing seems to be what takes all the time.  So introduce a "Batch Complete" marker, and until that is received do not index and enter the file/batch into the database, but just validate as soon as it is uploaded and hold it for further uploading.  These files will be "In progress" until the "Batch Complete" is triggered.  "Batch Complete" will not be accepted if the file has errors.  This will drastically reduce the overnight processing.  In FR1 files were only entered into the live database at the end of every four weeks, so this is not a step backwards.
>     
    Would that mean these records were not included in a search before the Batch compete flag is set, then? that would remove all of them until someone went through by hand would it not?
> - If this system works, then perhaps indexing of "Batch Complete" can take place immediately and not left for overnight processing. This will encourage transcribers to use smaller batches as their work will not go live until "Batch Complete" is entered.
>
> - Some may want to say "Batch Complete" before it is complete so as to see their work in the live database, and then add more to the file.  This should be accepted, but it needs to be a separate process.  A transcriber needs to say "Replacing a temporary file" or "Replacing a previous Batch Complete".
>
    These add-ons are a bit hard for me to get my head round! so I would guess it will confuse most transcribers who upload their own.

> - This will also get over the complaints that the transcriber does not get to know of the errors until after the processing and they get an email.
>
> - We will be able to do immediate error reports.  We will not need any Overnight Processing.  This can only come in once we are off FR1.
>
    As I keep saying: a brave decision would be to shut F1 now, and at least remove that set of restraints.

> Thoughts?
>
> Eric

**Comment by Captainkirkdawson** [comment]
No I stopped reading the discussion because of notes such as this one. 

Yes the overnight processing has exploded; as have the ASAP requests. 
Looking at tonight there are 113 files scheduled to be processed. Suspect it will be 10AM GMT before the update finishes. There were about 20 ASAPs

It is clear that 75% of those and those of the past few nights are being processed ONLY because of change in location such as register. Validation as proposed as the priority action will NOT address the load imposed by these files. These files call for the deletion and recreation of all their entries.
Processing is slow because deletion of entries/search records has been deliberately slowed because of the impact of mass deletions has been shown to cause significant server impact as all servers are brought to the same state. While the overnight processing is overnight for the UK it is not for other parts of the world and we should not, I suggest, provide those people with a poor level of service.

The statement "Many files being uploaded are just having extra records added, but all are processed" is misleading; while we of course process all records we do not recreate the actual entries and search records if they already exist for that location. Only "new" ones are fully processed and indexed.

The only solution to the major load impact is to provide a register type change option for transcribers..  

As for the rest of it which clearly is way and beyond the simple reintroduction of a validation option I leave it to others to think about and implement.  I have to say that I have no interest whatsoever in undertaking it. So it is clearly the time for management to find another person to take on the full time support of FR. I have taken it as far as I can.

**Comment by edickens** [comment]
Understood Kirk.
I'm concerned that if we give "Relocate" to transcribers so that they 
can change the "Register Type" that they will not also do "Download" or 
correct the version on their computer.  As a result they could upload 
and recreate the "Unspecified".  And if they do amend the version on 
their computer, and do it correctly, when they upload that file next, 
will it match the version of their file on the server?  If it doesn't 
then we could end up processing the change of Register Type, which is 
what we are trying to avoid.
As for Validate.  Assuming we can find someone to support FR and 
reinstate it, can it check Church and Register Type without the 
capitalisation changes, so that transcribers know that their version 
does not match and they can put that right.  When they do ask for it to 
be processed then the capitalisation changes can be made if they have 
not made a change.  E

**Comment by Sherlock21** [comment]
BUT please bear in mind my testing report for#561. which indicates some snags and the test was suspended pending fixing the cause(s)

SO if you are telling Transcribers to :either send files to their  CC to use the REname App, or propose giving all transcriber this APP, then they must be told they are restricted on what Register codes they can use.

**Comment by Captainkirkdawson** [comment]
EricD.
The issue you raise is identical if done by transcriber or coordinator. In my mind they are more likely to download the file if they do it themselves than if some other person does it for them in the background. 
Similar response to  EricB it would have been done within the present framework of Register Types.
Will not pursue given your combined preference for the status quo.

**Comment by benwbrum** [comment]
This is something Kirk and I need to talk about when we do the updater/processor transfer-of-information in January

**Comment by Captainkirkdawson** [comment]
The overnight processor was changed 3 weeks ago to permit the change of register type at the file level without having to reprocess the records.
This issue is closed
