### ISSUE TITLE
Re-Introduce Validation

### ISSUE THREAD

**Issue by sean-wood** [FreeUKGen/MyopicVicar#662]

**Comment by sean-wood** [comment]
Check with mike the term used

**Comment by Captainkirkdawson** [comment]
I am sorry Eric that question makes no sense. Validation is a process action not an upload/replace action.
The more I think about this the more I believe this suggestion imposes an old FR1 type of processing onto a modern infrastructure. If one goes this way there is no real move towards record/entry processing it is back to the old file processing system.  It does nothing to address the issue that it was proposed to address in

**Comment by edickens** [comment]
So what is Validation?  One would not want to validate one entry.  A transcriber will want to know if their work will be rejected or not.  And that may be a new batch or an amendment to an existing batch.
But is validation really needed?  With WinFREEREG validation is done at data entry.  No errors can (should) exist.  It is only those who use a spreadsheet or have converted a donated transcription who might have errors, and they could put that through WinFREEREG to upload.
