### ISSUE TITLE
Update donation page to include Giftaid

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#665]
We are signing up for Giftaid (reclaiming tax paid by UK donors).  This has been implemented on FreeCEN2, and needs implementing on FreeREG1 and FreeREG.

**Comment by Captainkirkdawson** [comment]
Do not understand the actual requirement.

**Comment by PatReynolds** [comment]
Doug has the code which serves the correct paypal button, depending on whether or not the giftaid declaration is signed (ticked), and I have the PayPal code for FreeREG-with-giftaid and FreeREG-without giftaid.

**Comment by dougkdev** [comment]
Pat,
I will update this if you send me the two FreeReg paypal codes.  Thanks.
