### ISSUE TITLE
Remove BOM from input file

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#666]
Some files are coming in with a BOM that is being interpreted as a character and causing the failure to detect +INFO at the start of a file

**Comment by Sherlock21** [comment]
What on earth is a BOM !!

**Comment by benwbrum** [comment]
I have the same question.

**Comment by Captainkirkdawson** [comment]
https://en.wikipedia.org/wiki/Byte_order_mark

Appears as ï»¿ at start of a file

**Comment by benlaurie** [comment]
Hang on ... if you are simply removing the BOM, it means you are not processing the file correctly.

You should be feeding it through something that understands unicode rather than hoping it will all work out OK.

BTW, what is our position on unicode (my view: we should support it).

**Comment by archerbarrie** [comment]
For what it is worth, FreeBMD recognises the UTF8 BOM (and only that BOM), removes it and interprets the file as Unicode (using the CharSet library routine). Alternatively, there is a field in the <a href='http://www.freebmd.org.uk/Format.shtml#charset'>first line of the file</a> that can be set to Unicode. However, the FreeBMD character set is limited to ISO8859-01.

**Comment by dougkdev** [comment]
The .csv header for FreeReg has a field in which the transcriber enters the
character encoding of the file. If none is specified, Windows-1252 is
assumed unless the file starts with a unicode BOM, in which case unicode is
assumed (UTF-8, UTF-16LE, or UTF-16BE, depending on which BOM starts the
file).  If the transcriber specifies an encoding in the header field, that
takes precedence over assumptions based on BOM or lack thereof.

The .csv file gets read assuming the selected encoding and the data gets
transcoded to UTF-8 for internal use. If any character sequences are
invalid in the selected encoding or cannot be properly transcoded to UTF-8,
the user is notified that either the character encoding field is wrong and
needs to be corrected, or there are invalid characters that need to be
removed from the file.

One concern I have is that if people are creating their .csv using one
encoding and then adding the header in a text editor that assumes UTF-8 and
adds the BOM without properly transcoding the existing characters to UTF-8,
we may be ending up with hybrid files (BOM at the beginning of a .csv that
really has characters encoded in Window-1252, for example).  If so, we may
need to go back to explicitly ignoring the BOM on all files.

**Comment by Sherlock21** [comment]
I  do all my own transcribing work on an iMac so my files are UTF-8.
BUT sometimes in the process of assisting  Transcribers or Cc's resolve a data problem, i end up downloading their files and perhaps editing a bit of one. If I then upload these files, does the fact that I just open the file on my iMac, and save it again, change the whole of the text in it to UCF-8? [ assuming it was a Windows file originally? ]
OR do we have a bit of both?
Do I need to change the header field as you imply?

**Comment by edickens** [comment]
I suggest we do not waste too much effort on this.  The problem does
    not happen very often.
    
    Before long we will have WinFREEREG which will do the uploading of
    files into FR.  I'm not sure how it will work, but it should be
    independent of the operating system.  Hopefully it can be set up
    without having to install software on the transcriber's computer. 
    This is the first step towards online data entry, being integration
    with the upload processing.  E
    
    On 12/01/2016 10:50, Sherlock21 wrote:
    
      I do all my own transcribing work on an iMac so my files are
        UTF-8.
        BUT sometimes in the process of assisting Transcribers or Cc's
        resolve a data problem, i end up downloading their files and
        perhaps editing a bit of one. If I then upload these files, does
        the fact that I just open the file on my iMac, and save it
        again, change the whole of the text in it to UCF-8? [ assuming
        it was a Windows file originally? ]
        OR do we have a bit of both?
        Do I need to change the header field as you imply?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Sorry EricD but it is essential work for multiple reasons. We will always get files from a variety of sources and it is essential that we ingest them correctly and without barfing the processor. In addition we must process Mac files correctly.

**Comment by Captainkirkdawson** [comment]
EricB. I believe that Doug has added UCF-8 as a valid character set as part of his work. You should be using that as a character set in the header for your files.

Alison: we need to add the UCF-8 option to our documentation, This should be used I gather for "modern" versions of the Mac OS

**Comment by Sherlock21** [comment]
Thank you.
I will check that it does happen.

**Comment by Captainkirkdawson** [comment]
Hang on EricB has yet to be deployed to production

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by AlOneill** [comment]
OK, but what counts as a "modern" Mac OS? All OS **X** (Snow Leopard+)? Or does it also depend on the spreadsheet/text editor used. 

FWIW, my spreadsheet (OpenOffice) says it saves as utf-8. I do not use a text editor any more. I upload files with "macintosh" as the encoding...

**Comment by Captainkirkdawson** [comment]
I wish I knew!

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Doug. I believe that most of our transcribers really understand nothing about characters sets and what their computers are doing. I also believe that transcribers and coordinators are moving files around between themselves using a variety of platforms with little (no?) regard for character sets and without changing headers. We have transcribers working with old versions of Windows and old versions of text editors and old versions of Excel. We also have an increasing number are using modern PCs and Macs with modern applications. Hence they are likely producing hybrid files. 
However since we have not permitted UCF-8 as a character set until this change. They have come in with a non UCF header. We previously just stripped the BOM if it was there and since we strongly discouraged "special characters" we have not really encountered any difficulties. I suspect in the future we will getting a mixture in the future. Time will tell if this change will work for all situations.
This issue of old platforms and applications was the reason for downloading files in Windows 1252

**Comment by Sherlock21** [comment]
I would be inclined to the view: if its OS X 10 or greater its 'modern' Up to and including 9 was always called Classsic.

**Comment by Sherlock21** [comment]
Kirk: i think that Transcribers would not know what you were talking about let alone know how to control the matter!
So better to try and accommodate everything, And give them a list of characters NOT to be used - if that's still necessary.

**Comment by dougkdev** [comment]
Thank you for your feedback.  Since we cannot count on the character set
field of the .csv header being accurate (due to users not knowing what to
put or due to files being edited and saved in a different encoding
after-the-fact), if there is a UTF-8 BOM we read as unicode regardless of
what is specified in the header field.  If we find invalid characters, then
we default back to whatever is specified.

If there is no BOM, we use what is specified in the header field.

If there is no BOM and nothing specified, we default to Windows-1252 (like
before), unless we see characters that are not defined in Windows-1252 and
all characters are valid in UTF-8.  If that is the case, we default to
UTF-8.

We currently support UTF-8 but not UTF-16 which is less common.

Whichever encoding ends up being used, we replace invalid / undefined
characters (if any) with the unicode undefined character symbol.  Since we
rarely see special characters anyway, this isn't likely to happen much.

**Comment by Captainkirkdawson** [comment]
Ran a number of tests OK. So have deployed to production

**Comment by Captainkirkdawson** [comment]
Processed the 17 files for 14 Jan OK. We now need to update documentation on UTF-8 as the preferred option for OS X applications, Open Office users need to specify this option on save. Most Windows apps including Excel still use CP 1252 in Europe (CP1250 in USA) although some modern non MS products can output a UTF-8 formatted CSV file.

**Comment by AlOneill** [comment]
Thanks Kirk. [File headers page](http://www.freereg.org.uk/information-for-transcribers/file-headers) updated as per.

**Comment by Captainkirkdawson** [comment]
Doug, We had 3 files with ignoring Windows-1252 specified in col 5 of .csv header because UTF-8 Byte Order Mark (BOM) was found in the file. Processed OK

**Comment by dougkdev** [comment]
Good to know.  Thanks.

**Comment by dougkdev** [comment]
Are we OK to mark this as done?

**Comment by Captainkirkdawson** [comment]
Absolutely; its in use 50 times a day
