### ISSUE TITLE
Updating FR from FR1?

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#672]
Is it still necessary to do the overnight update?

**Comment by edickens** [comment]
There have been a few night's recently when I have not received a FR from FR1 update.  I assume this is because there are no files to process.  (A nil return would be more useful.)  In which case has the time time come to stop updating FR from FR1.  There are not many more UserIDs that are active.  I can email transcribers to say that we will stop this update, and then I will disable all the remaining UserIDs, except CCs so that they can look up information.  E

**Comment by Captainkirkdawson** [comment]
We can go to weekly updates from FR1 if you wish

**Comment by edickens** [comment]
I have not seen a FR1 to FR update for a few days.  Have there been
    any files to process?
    
    I would go for weekly updates now.  Which day?  I will tell
    everyone.
    
    E
    
    On 28/11/2015 00:10, Kirk Dawson wrote:
    
    
      We can go to weekly updates from FR1 if you wish
      —
        Reply to this email directly or view
          it on GitHub.
