### ISSUE TITLE
Checking the FR overnight update

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#673]
Now that the "Processed" reports are working correctly, is it necessary for me to check the overnight update report and send emails to the Coordinator to tell them to get the problem fixed?

**Comment by edickens** [comment]
I have been looking through the over night processing reports and finding files that have been Rejected for processing, for say a bad character, a wrong format header, illegal quotations, and other such errors.  I do not take action on Data Errors.
But as this is the FR update, then the transcriber will already have this information.   I had assumed not for the FR1 to FR update because that is not integrated into the "List batches" report.
But I do need confirmation that the transcribers are getting reports for rejections.  On 23rd we had:-
SUG	STSSTFMA.csv *We were unable to process the file possibly due to an invalid structure or character. Please consult the System Administrator*
which I assume is a message sent to the Transcriber.
So do I still need to take action on these reports?  E

**Comment by benlaurie** [comment]
On Fri, 27 Nov 2015 at 08:00 Eric Dickens <notifications@github.com> wrote:

> I have been looking through the over night processing reports and finding
> files that have been Rejected for processing, for say a bad character, a
> wrong format header, illegal quotations, and other such errors. I do not
> take action on Data Errors.
> But as this is the FR update, then the transcriber will already have this
> information. I had assumed not for the FR1 to FR update because that is not
> integrated into the "List batches" report.
> But I do need confirmation that the transcribers are getting reports for
> rejections. On 23rd we had:-
> SUG STSSTFMA.csv *We were unable to process the file possibly due to an
> invalid structure or character. Please consult the System Administrator*
>

That is not a very helpful error!

**Comment by edickens** [comment]
Ben - There is a lot more information.  I just entered the messages
    that has possibly gone to the transcriber.  E
    

    On 27/11/2015 08:33, Ben Laurie wrote:
    
    On Fri, 27 Nov 2015 at 08:00 Eric Dickens
      <notifications@github.com> wrote:
      
      > I have been looking through the over night processing reports
      and finding
      > files that have been Rejected for processing, for say a bad
      character, a
      > wrong format header, illegal quotations, and other such
      errors. I do not
      > take action on Data Errors.
      > But as this is the FR update, then the transcriber will
      already have this
      > information. I had assumed not for the FR1 to FR update
      because that is not
      > integrated into the "List batches" report.
      > But I do need confirmation that the transcribers are getting
      reports for
      > rejections. On 23rd we had:-
      > SUG STSSTFMA.csv *We were unable to process the file possibly
      due to an
      > invalid structure or character. Please consult the System
      Administrator*
      >
      
      That is not a very helpful error!
      
      >
      > which I assume is a message sent to the Transcriber.
      > So do I still need to take action on these reports? E
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
<https://github.com/FreeUKGen/MyopicVicar/issues/673#issuecomment-160061965>
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
#<Mail::Message:17421866260, Multipart: false, Headers: <Date: Mon, 23 Nov 2015 05:57:19 +0000>, <From: freereg-processing@freereg.org.uk>, <To: derek.farmer1@ntlworld.com>, <Cc: freereg2.sts.coordinator@gmail.com>, <Message-ID: <5652aabfedb95_16e7e4012c5bf0572a1@colobus.freebmd.org.uk.mail>>, <Subject: SUG/STSSTFMA.csv failed to be processed by FreeREG at 2015-11-23 05:57:19 +0000>, <Mime-Version: 1.0>, <Content-Type: text/html>, <Content-Transfer-Encoding: 7bit>>

**Comment by Captainkirkdawson** [comment]
Mail was sent to both user and coordinator
<Mail::Message:17421866260, Multipart: false, Headers: <Date: Mon, 23 Nov 2015 05:57:19 +0000>, <From: freereg-processing@freereg.org.uk>, <To: derek.farmer1@ntlworld.com>, <Cc: freereg2.sts.coordinator@gmail.com>, <Message-ID: <5652aabfedb95_16e7e4012c5bf0572a1@colobus.freebmd.org.uk.mail>>, <Subject: SUG/STSSTFMA.csv failed to be processed by FreeREG at 2015-11-23 05:57:19 +0000>, <Mime-Version: 1.0>, <Content-Type: text/html>, <Content-Transfer-Encoding: 7bit>>

**Comment by edickens** [comment]
In which case I will not check the FR overnight update, other than to 
look to see what is going on.  There are some peculiarities with a lot 
of files being uploaded for the same place with no changes and they are 
not a place/church change.
