### ISSUE TITLE
Specify the Roles and what they do.

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#677]
A recent problem has been because the coordinator was expecting certain Actions but their role did not provide them.

**Comment by edickens** [comment]
Roles are Researcher; Trainee; Pending; Transcriber; Syndicate Coordinator; County Coordinator; Country Coordinator; Volunteer Coordinator; Data Manager; Technical; System Administrator, Contacts Coordinator.  It is not the case that a higher level has all the Actions of a lower level.
The reason for asking for this to go in the Coordinators Help is so that they know what their Role lets them do.  The problem that Sandra has just had is that alycymru is set up as Country Coordinator but also assigned as Wales SC.  So she did not understand why she could not list all the Wales batches under the SC Action.  Country Coordinator is not higher than Syndicate Coordinator.  Problem now solved.
I remember Kirk did this definition some time ago, but it needs updating and recording.  E

**Comment by Captainkirkdawson** [comment]
There is no reason why she should not access the Wales Syndicate if she is the syndicate manager for Wales. 
Not sure she has a powerful enough computer to deal with the thousands of files that are associated with that syndicate. 
She is best advised to work with specific subsets using either looking at the files for a specific user or a county.

**Comment by AlOneill** [comment]
The details of how  coordinators should respond to a "Data Problem" were updated before the break to reflect the recent changes.

A fuller account of Roles/Actions and Communications is on the (draft) [Behind the scenes](http://www.freereg.org.uk/information-for-coordinators/behind-the-scenes) page.

Although most of the Roles are self-explanatory, a few could do with an explicit description: Pending, Genealogy Coord, Engagement Coord, Volunteer Coord (plus any other Role known to puzzle people). 

Comments or suggestions?

**Comment by Captainkirkdawson** [comment]
Looks good to me.
