### ISSUE TITLE
Reset password emails are not reaching the transcriber

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#678]
Reports received of someone requesting "Forgotten password" and not getting the email.

**Comment by edickens** [comment]
bigpond ISP does not seem to let the email through.  I thought we created some new freereg.org.uk email address and hid these so that would not be found for Spam and so get through the ISPs.  Does Request new password use this?  E

**Comment by Captainkirkdawson** [comment]
bidpond does allow our remains through. We have sent some 15 notifications to users at bigpond.
We are using new sending addresses but they all use @freereg.org.uk as decided some time ago. There have been only 2 rejections in a total of 1000 emails sent in the past 10 days.
The password reset message is sent by refinerycms and uses a no-reply@freereg.org.uk which perhaps bigpond is not accepting.

**Comment by edickens** [comment]
Is this the same message/email address as sent from the "Send
    password change request" in the Show Profile?  These seem to get
    through.  E
    
    On 28/11/2015 17:24, Kirk Dawson wrote:
    
    
      bidpond does allow our remains through. We have sent some 15
        notifications to users at bigpond.
        We are using new sending addresses but they all use
        @freereg.org.uk as decided some time ago. There have been only 2
        rejections in a total of 1000 emails sent in the past 10 days.
        The password reset message is sent by refinerycms and uses a no-reply@freereg.org.uk
        which perhaps bigpond is not accepting.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
The system sent message from refinery is different from the one sent from
the application

**Comment by Captainkirkdawson** [comment]
To have the refinery email use a different sending address we would have to investigate how to override the refinery mailer.

**Comment by edickens** [comment]
No need to.  E
    
    On 28/11/2015 18:45, Kirk Dawson wrote:
    
    
      To have the refinery email use a different sending address we
        would have to investigate how to override the refinery mailer.
      —
        Reply to this email directly or view
          it on GitHub.
