### ISSUE TITLE
Defining stories for Records Available Pages (the RAP)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#68]
The Coordinators Control Report.  To start - the RAP (Records Available Pages) which is their main control document.

**Comment by Captainkirkdawson** [comment]
From 73
VOT Very Old,fragment, torn, fire damage    expert

VNC Very Old Needs Care,readable    Medium/expert

FBC Faded but clear Medium

ONC Old Needs Care  Medium

OBO Old but Organised,layed out like a register Medium

NOF Nice Order but Faint,layed out like a register  Medium

MIX Mixed, faded/clear/good/bad writing Medium

OSD OK, but some difficulty starters

VGC Very Good Clear, New transcribers   starters

GDC Good and Clear, for new transcribers, next level    starters

TRG Typed registers, but  have been typed   requested because of eye site etc

TBT Typed BT's

**Comment by Captainkirkdawson** [comment]
From 211

The field is called "Status of Transcriptions". I suggest that this should be a pick list as follows:-

No data available (Default)
Images Available
Allocated (UserID needed?) (Or perhaps enter the UserID instead)
Transcription complete

**Comment by edickens** [comment]
At what level will this information be recorded?  A transcription could be just a Batch, but we would not want the RAP at this level, except perhaps for transcriptions in progress.
Your Register level is for the whole life of the Church so is perhaps too long.
We will need to record register books that have gone missing and so can never be transcribed.  Which brings us to the question of how do we record missing entries.
I think we need resolve these questions before we get into coding the work.

**Comment by edickens** [comment]
I have been thinking a lot about this and have gone back to basics.

What is the purpose of the RAP?  I would like it to show the status of parish registers from their source to being live on the database, at which time the information transfers to the DAP.

So these are the stages:-
Register are/are not in existence and have not been transcribed.  Check needed against DAP.
Register books are/are not in existence
Images are/are not in existence
We have permission to transcribe the images
Images are on the image server or are accessible from somewhere else
Images/batches/register books have been allocated.
Batches have been uploaded against this allocation (means that the transcriber has started)
Batch has been signed off as complete by transcriber
All the images for this allocation have been transcribed and signed off as complete by transcriber.  New allocation needed.

SC then checks these batches and signs them off and they are removed from this report.

I have not been thinking of how the whole uploading of images and allocation will work, just the sequence.  Perhaps we do need to decide how we are going to process the images before we do the RAP?  Also, we need to decide what to do about missing Registers and unreadable pages.  This is to save the CC looking for registers or missing years which can never be transcribed.

E

**Comment by Captainkirkdawson** [comment]
Eric B commented


My first comment is that there is a danger of confusion and mis-understanding possible here from the Word Batch as Kirk has insisted in the past is his word for file as we used to call the bundles of records Transcribed and uploaded together. with names like NFKREPBA1.csv Preferred quantity being 2000 single line records.
Here the word has become used as the contents of a Register Book.

Elsewhere. it was the quantity of records given to a Transcriber to work through.

**Comment by Captainkirkdawson** [comment]
EricD commented.
Before we think about introducing another set of functions, and I understand the need that Kirk has expressed here, I think we need to debate the use of Batches. At present the Register is "Register Type" such as "Parish Register". With this name it could cover the documents from 1530 to the present day. There are date range and quality fields against the Register Record. But, the quality will vary over the years and the Registers are a set of books, each usually covering about 50 years. Images of these books are usually grouped into sets that match the books. So my thoughts are that we need some more Batch functions. In the Register functions we need "Create Batch". The Batch name needs to be capable of being created. We will need to show a link to the images and to identify their Quality. But that is as far as my thinking can go because I cannot see how we can easily match the FR1 files to these Batch records. But then perhaps we do not need to. When transcribers load into FR2 they can select the Batch that they are working on. I hope this does not muddy the waters, but I think it is time to plan ahead so that we don't do another set of structure changes.

**Comment by PatReynolds** [comment]
Feature for RAP: Perhaps registered transcribers could log a request so that when material becomes available they are the first to know.

**Comment by Captainkirkdawson** [comment]
First Draft
The current data model for Freereg2 supports searches of Events(1) that occurred for person somewhere in the UK. It was built as a database of Transcriptions(2) of these events. These transcriptions are organized into Physical File(3) by the transcriber with each file containing a set of transcriptions for a single type of event; these are produced either off-line or on-line. A physical file is processed into Batches(3) of events for the same register/church/place. A batch belongs to a Register(5). Each register belongs to a Church (6) and a church can have many registers. A church is located in a specific Place (7) 


(1) Event: an occurrence of a baptism (birth), marriage or burial (death) for a person that usually specified a date
(2) Transcription. A TWYS digital version of the original event
(3) Physical File. A set of unprocessed original transcriptions of events in a CSV data interchange format. A file only has one event type. The size of the set is from a few hundred to 2 thousand.
(4) Batch. A group of processed transcription for the same register/church/place. There can be 1 or more batches in a physical file
(5) Register. The original document that contained events. Its description include a name, alternate name and type as well as other information.
(6) Church. A religious institution or entity that has created Register(s) of Events
(7) Place. A physical location in the UK. The names and their locations are defined by the Association of British Counties (http://www.gazetteer.org.uk/)

To met a researchers' need to know if we have actually transcribed events that might contain events that are of interest to them. We provide the  (Data Availability Pages) DAP. From those pages the researcher can get the number of transcribed events by type and decade for every Place/Church/Register for which we have data as well as by whom. A similar system provides county coordinators with the ability to determine what has been transcribed and when.

The researcher also has a need to know if we have and/or are transcribing other events and the date range of those events for Places and Churches of interest to them. This is currently not supported but has been termed the (Register or Record Availability Pages) RAP. In addition the researcher needs to know if there are gaps in a register for whatever reason that might be the reason that they were unable to find an event in the records. This has been termed the GAP

RAP Requirements.

Researcher needs to find out R1) what registers are currently available to FR and not being transcribed and for which Place and Church; R2) the date range of events for each of those register; R3) what registers are currently being transcribed and for which Place and Church; R4) the date range of events for each of those register.
Transcriber needs to find out R1) and R2) above; they also need to know R5) the complexity or skill requirement to transcribe specific data ranges; and R6) who to approach to get part of the register assigned to them for transcription.
Coordinator needs to find out/set R1),R2), R3), R4) and R5) above. In addition they need to set ownership and any copyright/licensing information for the register. They MAY need/wish to create subsets of a register.

GAP Requirements.
(We need to define what a GAP is)
Researcher need to know G1) the range of dates for which events in a register may not exist, for what reason and for which Place and Church.
Transcriber needs to be able to record the G1)  
Coordinator needs to be able to record the G1)

**Comment by edickens** [comment]
My personal comments:-
- First paragraph.  Batches s/b (4).
- (3) can be as small as one, which happens when say a Burial is entered 
in a Baptism register book.
- (4) A Batch can be a whole register book or part thereof, and is often 
the pages contained on one microfiche.
- (5) We call this Register Type, because it defines the source of the 
transcription.  Most Churches have many Register Books.  Very often the 
BA, MA and BU are in separate books.  This line should not refer to a 
document.  Source may have been a better description, but we are used to 
this now.
- (6) Is not necessarily religious.  We have the burial records for 
Manchester's public cemetery.
- (7) Not to be confused with Parish.  There is an Alternative Place 
Name which can be used in a search.
- The DAP can be found from "Transcriptions" on the homepage.
- RAP transcribers.  When a transcriber finds something that they would 
like to work on, they should have an easy means (at present they send an 
email) to ask to be allocate that register book or part thereof, and 
perhaps this should be a predefined Batch, with the years involved for 
validation.
- RAP Transcriber.  On completion of the work allocated to them, the 
transcriber should have an easy way to say that they are finished, 
thereby changing the status of work allocated from "In progress" to 
"Completed".  The Coordinator should be told of this.  Uploading part 
complete transcriptions does not need to be reported.
- RAP Coordinators.  The syndicate coordinator needs to be able to 
allocate register books, or part thereof, to a transcriber so that the 
status changes from "Waiting to be transcribed" to "In progress".
- GAP.  A Gap is a period of one year or more, but can be defined as a 
range of years.
- GAP.  On completion of a set of allocated work, the server should 
check for gaps of more than one year.  This to appear in the GAP report 
for investigation to see if it is a missed transcription or some other 
reason.  If the data is never going to be available, this gap to be 
marked as such.  The transcriber should do this as they go along, but it 
can be missed.  This needs to be done retrospectively because a batch 
can get deleted and not replaced, thereby creating a Gap.

But otherwise the principles stated here are absolutely correct.

Thanks,

Eric

**Comment by benwbrum** [comment]
I really worry about the terminology of "Event", and would consider revising as follows:

The current data model for Freereg2 supports searches of Entries (1) that record Events(2) that occurred for Person(3) somewhere in the UK. It was built as a database of Transcriptions(4) of these Entries. These transcriptions are organized into Physical Files(5) by the transcriber with each file containing a set of transcriptions for a single type of event; these are produced either off-line or on-line. A physical file is processed into Batches(6) of Entries for the same register/church/place. A batch belongs to a Register(7). Each register belongs to a Church (8) and a church can have many registers. A church is located in a specific Place (9)

(1) Entry: A portion of a physical document recording an Event.  Multiple entries may attest to the same event, as when original parish registers were transcribed contemporaneously for bishops or archdeacons, or when parish registers or contemporary transcripts were published later in Phillimore editions.
(2) Event: an occurrence of a baptism (birth), marriage or burial (death) for a Person that usually specified a date
(3) Person: an actual person who was buried, baptized, or wed.
(4) Transcription. A TWYS digital version of the original event
(5) Physical File. A set of unprocessed original transcriptions of events in a CSV data interchange format. A file only has one event type. The size of the set is from a few hundred to 2 thousand.
(6) Batch. A group of processed transcription for the same register/church/place. There can be 1 or more batches in a physical file
(7) Register. The original document that contained events. Its description include a name, alternate name and type as well as other information. As part of the RAP a register could have many books and a book can have many chapters and a chapter can have many sections and a section many images.
(8) Church. A religious institution or entity that has created Register(s) of Events
(9) Place. A physical location in the UK. The names and their locations are defined by the Association of British Counties (http://www.gazetteer.org.uk/)

The reason I'm so pedantic here is that family tree software usually tries to track Persons and Events, ideally linking to documents (Entries) supporting the genealogist's conclusions.  We, on the other hand, are a record database that attempts to represent the documents which have survived, but does not attempt to make assertions about historical reality.

I'm still not quite satisfied with this, as I feel like we need to incorporate some understanding of the images we have and how they relate.  (I also need to review and comment on the rest of the draft.)

**Comment by Sherlock21** [comment]
In Kirk's above summary called FIRST DRAFT,
I agree with the definitions.

But we are missing one definition: Register Type.
Here, what we really mean is: the source document which the Transcriber used to produce this Transcription.

IT may well have been the Original Register ( but not very likely)
More likely a fiche or digital scan of the above.
But if its a pre existing Transcription of some sort - then that's hardly a Register Type in my view.

I think we should tidy up this misnomer at this point, and replace the Register Type with Image Source.
Its easy to get mixed up with Register with Register Type. - especially the 'outsiders'

**Comment by Sherlock21** [comment]
I like BenB;'s approach above which wasn't there when I started writing my copy immediately prior to this. I like Ben's approach.
But I disagree with point  (4). A record is not strictly a TWYS of the Original Event. its a TWYS of our source of a record of an original event.

- My reason: if our Source is a document which is itself is a Transcription, then its already at least one step away from the original recording of the Event. - may be by 100 years, if its one of the early 1900's Publications, or even more, if modern.

And, BenB may like to consider where  my suggested "Register Type" field label fits into his view please?

**Comment by PatReynolds** [comment]
Between 'Transcription' and 'Event' we need 'X'.  X might be 'Register' or 'Source', although both may be used for other purposes, making them unsuitable.
There is an Original Event.  The event is recorded in one or more Xes (e.g. the Parish Register, a local newspaper, the local Registry Office record).  Each of these may be subject to further copying (e.g. Bishop's Transcript, the Local Rag's Book of the Year, the GRO record), producing further X-like databases or documents.  The 'Register Type'  describes the form of the X, and the notes on the type help the researcher understand how many steps away from the Original Event the X is, and how reliable the X is as a consequence of that, and other factors.  It also helps the researcher understand why we present multiple transcriptions which relate to a single Original Event.
The recent Policy Group discussion conclusion that our role is not to act in loco genealogist (and tie together the many transcriptions which may all describe Original Events where a single unique individual took part).  I think this is similar - it is not our role to tie together the records of what appear to be a single Original Event.

**Comment by PatReynolds** [comment]
For (9), I'd suggest:

We have developed for FreeREG (thanks to the exhaustive work of EricB) a nested list of places.  This is based upon, but not identically replicating any other listing.  The list of places, at its lowest level, is a geographical point.  
This is not (necessarily) as the same geographical point as those who recorded the Original Event understood the place to be (which was almost certainly an area rather than a point, for example), nor yet the same spelling or form of names in the place they used, or would even recognise - it is an approximation to standardised forms, used for returning searches.

**Comment by Captainkirkdawson** [comment]
A revised draft incorporating all comments has been placed into a shared google doc

**Comment by sean-wood** [comment]
stories 948 to 961 have been raised from the notes.
