### ISSUE TITLE
Problem when SC uploading into transcribers UserID

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#680]
When a CC uploads into a transcribers UserID an unexpected confirmation email is sent to the transcriber.

**Comment by edickens** [comment]
These last few days we have had transcribers reporting files being uploaded into their UserID which they know nothing about.  This has usually been done by their SC.
The facility to upload directly into another UserID by the SC is a very useful feature.  But it is intended either for those transcribers who do not wish to upload themselves or for making changes to work done by transcribers who are no longer active.
So my suggestion is that it should only be possible for the SC to upload into an "Active = No" UserID.  This is because the SC is acting on behalf of the transcriber who should not now have any connection with the database. 
The confirmation email for the upload should go to the SC who uploaded it, or the SC should have changed the email address in the Inactive UserID to one that will reach them.  Confirmation emails should never go to the named Inactive transcriber.
If a SC wishes to upload a file into an Active UserID,  the correct method is to email the file to that transcriber and get them to upload it.  In this way the transcriber knows what is going on and will have a compatible copy on their computer.  E

**Comment by Captainkirkdawson** [comment]
If an enhancement for SC why is this not a 1.5 milestone?
A confirmation email does not go to an inactive transcriber.
I agree with your last paragraph but that is a procedure issue not a software matter..

**Comment by edickens** [comment]
I only put it as V1.3 because it was a problem that has cropped up now.  
As an Enhancement because it was something that we had not thought of 
and programmed.
Should we add to "Living with FR" a paragraph about uploading into a 
transcriber's UserID?  E

**Comment by Captainkirkdawson** [comment]
Is there any development task associated with this

**Comment by edickens** [comment]
See the first comment, which is my suggested solution from a year
    ago.
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 25/10/2016 16:08, Kirk Dawson wrote:
    
    
      Assigned #680
        to @edickens.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Assigned #680 to @edickens."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/680#event-835618229"}}}

**Comment by Captainkirkdawson** [comment]
So you wish to limit SC/CCs uploads to userids that are inactive?

**Comment by edickens** [comment]
No.  I said "So my suggestion is that it should only be possible for the SC to upload into an "Active = No" UserID. "  What I meant is that an Inactive transcriber cannot upload into their UserID (they should not be able to log in) but a SC/CC can upload into an Inactive UserID, as well as into Active UserIDs.
However, the problem is (was?) that when they upload into an Inactive UserID the confirmation email goes to the Inactive Transcriber.   It should, like all upload reports, go to the person who did the upload, who is the person who logged in to do the upload.  E

**Comment by Captainkirkdawson** [comment]
No action required. System already performs as requested.
