### ISSUE TITLE
Error processing report does not attach file

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#681]
The reason for the upload failure is wrong.

**Comment by edickens** [comment]
A transcriber has reported this...
    ozfor/NTHHLMBA1.CSV failed to be processed by FreeREG at 2015-12-06 08:39:17 +0000:

           The file submitted failed to process. The reason:
              #<File:0x0000081aa7cb10>
            If you do not understand the reason please ask your coordinator for assistance.

    ozfor/NTHHLMBA1.CSV failed to be processed by FreeREG at 2015-12-06 08:39:16 +0000         The file submitted failed to process. The reason: ozfor NTHHLMBA1.CSV has not changed since last processing If you do not understand the reason please ask your coordinator for assistance. 

They are querying the "Reason".  But looking at the timing, I'm wondering if they have used ASAP but tried upload again before the upload processing was complete.  E

**Comment by Captainkirkdawson** [comment]
Do not see why this is classified as a bug.

File has not changed since it was last processed on Oct 31 

System did what was designed to do.

**Comment by edickens** [comment]
Not that message Kirk.  This message description ...
    
    The file submitted failed to process. The reason: 
                  #<File:0x0000081aa7cb10> 
    
    On 06/12/2015 15:29, Kirk Dawson wrote:
    
      Do not see why this is classified as a bug.
      File has not changed since it was last processed on Oct 31 
      System did what was designed to do.
      —
        Reply to this email directly or view
          it on GitHub.
