### ISSUE TITLE
Valid new registrations?

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#682]
New registrations not accepting the invitation to join the transcribers group

**Comment by edickens** [comment]
These last ten days there has been about 20 new registrations who have completed the process.  The latest one today has an email address ending .ch which I think is China, but the name is not Chinese.  She has registered for Kent.  These could all be genuine.  My concern is that not accepting the invitation to join the transcribers mailgroup is unusual.
So my question is - what should we advise the SC to do with these new volunteers and is our security good enough?  It is possible to register without reference to anyone and then once in is it then possible to hack the website?  Should we have another stage in the registration process whereby the SC has to accept the registration which would then open up those Actions which allow uploading and editing?   E

**Comment by PatReynolds** [comment]
.ch is Switzerland.  

Sean is looking at all aspects of security across our efforts at the moment, so I'll badge this for him to lead on.  I've said it's urgent, but may well move to less urgent / a developer once actions if any are identified.

**Comment by Captainkirkdawson** [comment]
Fail to see this as a valid sprint backlog item; I have no idea what work is required

**Comment by edickens** [comment]
Some programming may be needed, depending on what Sean comes up with.
Can you confirm that if someone does not set a password within a day, then the UserID is destroy.

**Comment by Captainkirkdawson** [comment]
No I cannot confirm that because it is NOT destroyed. It remains there so that the reset can be sent in the event that it was a simple delay

**Comment by edickens** [comment]
No problem.  But we need to know - in the SC list of UserIDs - those
    who have not completed registration by setting a password.  E
    
    On 14/03/2016 13:45, Kirk Dawson wrote:
    
    
      No I cannot confirm that because it is NOT destroyed. It
        remains there so that the reset can be sent in the event that it
        was a simple delay
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Is there anything that needs doing on this. I believe not

**Comment by edickens** [comment]
Pat's views needed as it involves our relationship with transcribers and if we integrate a discussion group for them.  Also if we are going to retain details of those who never transcribe.  E

**Comment by PatReynolds** [comment]
Still waiting for Sean's opinion on the level of security threat, if any.  Have badged again as Sean.

**Comment by sean-wood** [comment]
working through this
1. level of access a transcriber has
2. is there an onboarding process ( Transcribers communicate with their SC before starting working)
3. How often are User IDs / passwords reset

**Comment by edickens** [comment]
On 13/07/2016 15:14, sean-wood wrote:
    
      working through this
        1. level of access a transcriber has
      
    
    Not much.  Just their own work and no means of changing any fixed
    information.
    
      
        2. is there an onboarding process ( Transcribers communicate
        with their SC before starting working)
      
    
    Yes.  The SC is informed of the registration, with their email
    address, so they then contact them to determine level of
    experience/skill and then work is allocated.
    
      
        3. How often are User IDs / passwords reset.
    
    Passwords are not reset that often.  Usually when someone returns
    after an absence or they have changed computer.
    
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
