### ISSUE TITLE
Labels and milestone choices missing from issues arriving via 'management'

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#683]
Low-numbered issues, arriving by 'management' e.g. #11, #20 cannot have milestones applied, and only a limited range of labels are available (e.g. no 'documentation')

**Comment by Captainkirkdawson** [comment]
The management repository has no labels or milestones established for it

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by benwbrum** [comment]
What we need to do is to co into github (not waffle) and add labels to the
repository's issues. If those labels match the other milestones, so much
the better!

**Comment by benwbrum** [comment]
This should be completed.  @PatReynolds can you take a look?

**Comment by PatReynolds** [comment]
I still am not offered miilestones to select.  This affects issue #20 and #21.

**Comment by benwbrum** [comment]
Thanks, Pat -- this is mystifying!

**Comment by benwbrum** [comment]
I see the problem -- I added the milestones to the `Systemwide` repository, not the management one.

**Comment by benwbrum** [comment]
Try again -- I believe that I've added the milestones to the correct spot
now.

**Comment by PatReynolds** [comment]
Works fine now! Thank you!
