### ISSUE TITLE
Using the new Reporting system

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#685]

**Comment by edickens** [comment]
I have just used the new Reporting system, I hope in the way it is intended.  I used the link on the website and sent in #30099999.  This was sent to Kirk, John Pingram and Myself.  So I actioned it.  But as I wanted to convert this to a Github Issue, I had to log in to FreeREG and use the link the against the Report to created the Story.  I then deleted the Report on the Website since it had then been actioned, as I believe is the required process.
But on Github it only show the issue name as "30099999 issue (Eric)" which makes it difficult to identify when looking at the Waffle.  So I have added the description to the Title.  I suggest that the Summary which has been submitted by the sender should go in the Title. 
Otherwise the system works but it takes a lot of going into and out of websites.  E

**Comment by Captainkirkdawson** [comment]
The title of a feedback is supposed to go into the Github subject line as well as the reference number and submitter. (It will not when coming from a contact as there is no subject just the type of issue)
Only one login to the website is needed unless you wish to add comments to the issue before conversion to issue

**Comment by PatReynolds** [comment]
Shall I close this, or is it a documentation issue?

**Comment by edickens** [comment]
Yes, close.  E
