### ISSUE TITLE
File crashed the overnight update

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#686]

**Comment by edickens** [comment]
This comment, but the update did recover and complete...
BarbJSTS	STSWODBA50.CSV line 542 crashed the processor
undefined method `length' for nil:NilClass
["/home/apache/hosts/freereg2/production/lib/freereg_validations.rb:298:in `year_extract'", "

**Comment by Captainkirkdawson** [comment]
Fixed will deploy 16 Dec
