### ISSUE TITLE
Improvement to the Contact sytem for "Data Problem"

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#689]
Provide better information in the message

**Comment by edickens** [comment]
We have had a number of messages like this...
 Data Problem:
NOT AN ERROR JUST AN ADDITION, 2ND WITNESS IS DANIEL WALDEN. WHO WAS SARAH KINGS' STEP--FATHER.
But which entry is it?   We get a clue fro m the CC that it has been sent to, if you know who is CC of where.  So either the sender should have to enter some fields with Place/Church/Date or the website should enter the Search criteria selected.
As it stands now, the CC has to email the sender for more details.  E

**Comment by Captainkirkdawson** [comment]
Not true. All they (or you) have to do is go to the Contacts collection and look up the relevant reference to see all of the information they need including a link to the specific record. See below.

We cannot include the specific record information in the email as a number of people did not want their userid to be public.
![contact](https://cloud.githubusercontent.com/assets/2874694/11918636/76cb9d8c-a6f6-11e5-9723-86d8c7f9ba41.JPG)

**Comment by edickens** [comment]
TY
    The problem that caused me to write this is #30475547 where they
    have selected the wrong message type.
    I assume that the record information is only saved when "Data
    problem" is selected.  E
    
    On 20/12/2015 15:52, Kirk Dawson wrote:
    
    
      Not true. All they (or you) have to do is go to the Contacts
        collection and look up the relevant reference to see all of the
        information they need including a link to the specific record.
        See below.
      We cannot include the specific record information in the email
        as a number of people did not want their userid to be public.
        
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
There is no selection involved in a Data Problem. It always comes in as a Data Problem.
It comes only by selecting the report an error link from the search result detail page.
The subject is "Thank you for reporting a problem with our data"
A copy always goes to the CC with additional info copies to the DMs (and us until we are satisfied that the process is working)
The detail in the Contacts Collection always has the record identification and a link

In the Contact form there is a Data Question in the list of subjects. The subject in the email is always
"Thank you for your data question" Copies only go to the DMs (and us until we are satisfied that the process is working)

So Question is a question and there is no information on a record unless the researcher includes it in their question
And Problem is a problem report for a specific record displayed from a search and the collection has a direct link to the record

The one you refer to is a Problem. So no selection was involved.

**Comment by AlOneill** [comment]
Would it help people to get their heads around this if Data Problem was Transcription Problem? Or another term that does not use the word "Data"?

**Comment by Captainkirkdawson** [comment]
This only affects 6 people, DMs and SAs they are the only ones who get both data questions and data problems. It does not affect the researcher. It does not affect the coordinators who only have to deal with data problems

**Comment by edickens** [comment]
Not for me.  Now that I know who gets what, and I am getting used to
    it, I can identify the different sources of the messages.  E
    
    On 20/12/2015 23:02, AlOneill wrote:
    
    
      Would it help people to get their heads around this if Data
        Problem was Transcription Problem? Or another term that does not
        use the word "Data"?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
I think you may have a point, Ali. after all , data covers a wide area. and as far as I am concerned it would help if it were divided into " County & Place Names" issues, and "Transcription" issues, AND somehow, suggestions that the Register transcription is wrong because the informant has a copy of the Marriage Cert, or it's their gg uncle must be prevented getting through.

**Comment by Captainkirkdawson** [comment]
System appears to be functioning with no complaints
