### ISSUE TITLE
Broadcast emails

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#691]
Timeframe: needed to implement Transcriber Agreement
‘to’ email addresses must be anonymous
Very restricted group able to use this feature
Personalisation (e.g. ‘Dear FIRSTNAME,’) is a nice-to-have
Recipients must be selected as ‘all’ or by characteristics, to include
* Role (e.g. transcriber, county co-ordinator)
* County (nb multiple county possible)
* Transcriber agreement status
* Code of Conduct status
* Activity status (e.g. active, on a break, no longer active)

Recipients must NOT be able to unsubscribe themselves from this feature, but can opt-out of all but the most essential communications) 
Access to groups of recipients must be restricted – e.g. County Coordinator can broadcast to their county, but not to others’ counties.

**Comment by edickens** [comment]
We need to differentiate between County and Syndicate.  These are
    two different groups and will address different topics.
    Coordinators must know when to use this instead of setting up a
    Forum on a particular topic.  Alternatively we could allow an "Opt
    Out", but this can be over-ridden by the Coordinator or Management
    in the case of something really important.  In other words, we need
    to differentiate between discussion and directives.  Perhaps
    Broadcast emails are only use for directives  E
    
    On 23/12/2015 13:34, PatReynolds wrote:
    
    
      Timeframe: needed to implement Transcriber Agreement
        ‘to’ email addresses must be anonymous
        Very restricted group able to use this feature
        Personalisation (eg ‘Dear FIRSTNAME,’) is a nice-to-have
        Recipients must be selected as ‘all’ or by characteristics, to
        include
      
        Role (eg transcriber, county co-ordinator)
        County (nb multiple county possible)
        Transcriber agreement status
        Code of Conduct status
        Activity status (eg active, on a break, no longer active)
      
      Recipients must NOT be able to unsubscribe themselves from this
        feature, but can opt-out of all but the most essential
        communications) 
        Access to groups of recipients must be restricted – eg County
        Coordinator can broadcast to their county, but not to others’
        counties
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by dougkdev** [comment]
I confused this story with #735 when I requested that this story be
assigned to me. I think this one is still "needs review."
