### ISSUE TITLE
Newsletter distribution

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#692]
Similar to broadcast emails (issue #691), but with opt-out allowed. Already exists - decision on future needed.

**Comment by edickens** [comment]
The present system is a Google Group.  People are invited to join
    when they register as a transcriber.  Most do accept the invitation.
    So an opt out is a good idea, but needs to be made clear at
    registration that this does not opt them out of Management emails.
    Will we have Researchers' Newsletters when they are able to
    register?  E
    On 23/12/2015 13:37, PatReynolds wrote:

    
      Similar to broadcast emails (issue #691),
        but with opt-out allowed Already exists - decision on future
        needed
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Do noi understand requirement,
A new letter can be attached to the message system. 
Do you need a do not communicate flag in the profile?

**Comment by edickens** [comment]
A SC wants to sent a newsletter to just their transcribers, not to
    all transcribers.  This is to tell them of data that they have, to
    tell them about being on holiday, and to unite their team.  So a
    selection by Syndicate is needed n the message system.  E
    
      On 15/10/2016 04:33, Kirk Dawson wrote:
    
    
      Do noi understand requirement,
        A new letter can be attached to the message system. 
        Do you need a do not communicate flag in the profile?
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #692: Do noi understand requirement,\nA new letter can be attached to the message system. \nDo you need a do not communicate flag in the profile?"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/692#issuecomment-253959888"}}}

**Comment by Captainkirkdawson** [comment]
As a result of this story.
A coordinator can use the Message System to  communicate to their syndicate members,
A transcriber can opt out of receiving general information
A coordinator can select to send messages to opted out members

**Comment by edickens** [comment]
That is what is needed.  E
    
      On 15/10/2016 15:01, Kirk Dawson wrote:
    
    
      As a result of this story.
        A coordinator can use the Message System to communicate to their
        syndicate members,
        A transcriber can opt out of receiving general information
        A coordinator can select to send messages to opted out members
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #692: As a result of this story.\r\nA coordinator can use the Message System to  communicate to their syndicate members,\r\nA transcriber can opt out of receiving general information\r\nA coordinator can select to send messages to opted out members"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/692#issuecomment-253986097"}}}

**Comment by Captainkirkdawson** [comment]
This send messages action still needs to perform this check even with a common gateway

**Comment by PatReynolds** [comment]
#995 refers

**Comment by PatReynolds** [comment]
Needs to be opt-out, I thought - that's how it differes.

**Comment by Captainkirkdawson** [comment]
The subject is Newsletter  Distribution, What needs to be done???????? Current system seems to work.
