### ISSUE TITLE
Check and update contact emails/contact forms enhancements for 1.5, 1.6 and 1.7

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#694]
See Specification for FreeREG email/contacts/forums/groups.

Need to agree approach for different email/contact forms and write stories for 1.4, 1.5 and 1.6.

**Comment by Captainkirkdawson** [comment]
Is there anything more that needs doing on this at this time. We made the email and contacts changes sometime ago.

We still do not have a forum process for coordinators but that is not part of 1.4

**Comment by edickens** [comment]
I think now that Sandra is dealing with these (although I am doing
    it now as she has a family bereavement) we should let this run for a
    while until it settles down,.  Before long we can remove many of the
    CCs.
    
    Eric
    
    On 29/04/2016 01:52, Kirk Dawson wrote:
    
    
      Is there anything more that needs doing on this at this time.
        We made the email and contacts changes sometime ago.
      We still do not have a forum process for coordinators but that
        is not part of 1.4
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly or view
          it on GitHub

**Comment by PatReynolds** [comment]
Forums for Registered Researchers now 1.7 rather than 1.4.

**Comment by edickens** [comment]
Pat - Can this be closed?

**Comment by PatReynolds** [comment]
No  - this is the defining task for Communications.  I think we need a separate meeting to go through the Specification for FreeREG email/contacts/forums/groups, check it is still what we want, and write the individual stories if they are not already on the board.  Much of the 'needs info' is because the info is in the Specification or needs to be developed with reference to the specification.

**Comment by Captainkirkdawson** [comment]
Very interesting comment. I was under the impression we had implemented a comment system that met the communications requirements in that specification document which had been used in its development or had other stories that addressed the remaining requirement

**Comment by PatReynolds** [comment]
I'll action this - just to do the double check that all the stories are on there.

**Comment by PatReynolds** [comment]
Share revised document on trac, once done.
