### ISSUE TITLE
Dudley, WOR records appear under a Search of Staffordshire

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#695]
This started life as user report 31251299. When a search for a surname Allwright in STS, ( nothing else in the spec) there are 47 results. MANY show Dudley St Thomas as the place/ church. But Dudley is in WOR. It has been since I think September 2015. And Dudley WOR is where the navigation takes the user if slicking on "details".The search results include data from  St Thomas church ( which is in Dudley/WOR).
 There is a Dudley Port in STS if that's a clue to you?
The file involved is STSSTABA1.CSV which I think was the "lost one" of recent fame, which I loaded into WOR. To get the full picture you need to run yourself a search and just look at the results.

**Comment by PatReynolds** [comment]
Just to note (in case it helps) that the baptism of James Allwright (1813) in Dudley St Thomas _does_ come up if you search in WOR.

**Comment by Sherlock21** [comment]
I checked other records - eg Hannah Price bu. Jan 1813 in Oldbury / WOR. but search on STS for Price with year range 1812 to1815, and this WOR record is in the results.

Oldbury was also previously in STS, but relocated to /WOR.
this record is file: jonny.STSOLDBU.csv.1

**Comment by Sherlock21** [comment]
I have tried a similar relocated Place name - Dob cross was in LAN, relocated to WRY.
here one file went by RELOCATE By me,
Other I think went by Reload by Ali hill.

if its any value

**Comment by Captainkirkdawson** [comment]
I am sorry Eric but I am unsure what you are trying to tell me with these
last 2 posts.

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
Instead of just giving you the first - out of the blue- problem report, i was thinking around the topic. ie trying to to add more useful facts for you. Namely listing all the records i have found that give rise to this situation in post 1, all once were in a batch that was in STS originally, and had been relocated to another county.
but i also recognise that this may lead you down a path that is the wrong path.  
But equally, you yourself will know that STS batches have had a chequered history.
So you can ignore these if you want, and just consider posts 1 and 2 of mine.

**Comment by Captainkirkdawson** [comment]
With respect to Pat's comment. I cannot find that baptism in WOR it is only retrieved by a search in STS. It originated in a file that had a place name Dudley (Staffs) as the place name that was changed to Dudley and relocated to WOR. But it appears that the Chapman code in the search record was not changed. More to follow.

**Comment by Captainkirkdawson** [comment]
Have confirmed that the county relocation did not update the chapman code in the search record. Have written a rake task to assess size of issue. The rake task also includes an option to fix once the size of the issue is determined.

**Comment by Captainkirkdawson** [comment]
Have determined extent of issue. There are 174874 records in STS search records that should be in WOR. There are also 9323  in BRE that should be in RAD and 6802 in NFK that should be in SFK.
Of less concern is that there 45436 records with the misspelt Dwellies instead of Dwelly's and approximately 300,000 records with a variety of register or church name inconsistencies. None of these affect the performance of the search.
I propose to correct these over the next week but giving priority to the incorrect chapman codes.
I do not believe that we are creating these issues with the current software but will confirm that before starting the correction.

**Comment by Sherlock21** [comment]
Wow!
I knew there were a lot of STS place names that had to change County, but did not expect it to amount to so many records. I would welcome you doing it with a bit of nifty coding please!

as to the 300,000 other ends. - are they listable by county from and to, for us to work through when you have finished? seems a pity to miss the chance if you have all that's needed there?

**Comment by Captainkirkdawson** [comment]
Leave it to me.

**Comment by Captainkirkdawson** [comment]
All corrections have been made.
