### ISSUE TITLE
Mobile view for desktop users

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#702]
I am wondering if desktop users generally would like the option of using the mobile view? On Tristan, I found google.com/gwt/n a way of getting at mobile versions (to save bandwidth). I've liked some sites mobile versions better than their standard ones (look better / work better when I've enlarged the font significantly for use on my laptop without my big screen).
So perhaps one of our accessibility choices would be 'mobile / desktop view'?

**Comment by Sherlock21** [comment]
on the face of it, I am not interested. So i would not wast the time doing this whilst there are bigger issues to fix. But thats without trying it out - so could you share the method and let us try before making a commitment?

**Comment by Captainkirkdawson** [comment]
Unless there is a real strong case for this iI suggest we drop; it has not been mentioned by the research community

**Comment by PatReynolds** [comment]
Agreed.
