### ISSUE TITLE
Navigation of Place Names table fails if its a alph grouped county

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#703]
In a County where Place Names are divided into groups like A - L; M - P; AND Q - Z, If CC or DN select List Active Places and picks A-L group, from Active Places  then retracks and picks say M - P group, it reverts to All Places rather than Active Places. same for each other subset.

**Comment by Sherlock21** [comment]
It would help users if the Breadcrumbs used the names: ALL PLACES or ACTIVE PLACES instead of just Places as at present.

**Comment by Captainkirkdawson** [comment]
Fixed breadcrumb

**Comment by Sherlock21** [comment]
TY

**Comment by Sherlock21** [comment]
I am afraid there is a snag with this solution K.
Pick your County
then the range.
select Active Places and scroll down a bit.
Select any place name then one of its church registers.

NOW navigate backwards on the breadcrumbs. The first one ("breadscrum) you get to that you lets you select it, takes your right back to having to reselect  either All places of Active places and start again.
Similar if one just selects All Places.

**Comment by Captainkirkdawson** [comment]
Very different issue.
