### ISSUE TITLE
Clarify abbreviations on Contacts page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#704]
E.g. put text at top SH = show, etc., or mouse-over?  The abbreviations are documented in Help, but not everyone reads help (Eric D has chain of emails)

**Comment by Captainkirkdawson** [comment]
Why?

These pages are only used by coordinators or managers who have those on all
their pages.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Is this still required?

**Comment by PatReynolds** [comment]
I'm probably the only one who needs it, so I'll close.
