### ISSUE TITLE
Validation at uploading of a file

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#705]
Please add validation of a file ( new or Replacement) and reject any where County and/or Placename/ and/or Church is present but no person data is. - these will be errors by spreadsheet users -

**Comment by edickens** [comment]
But accept if there is a year and no person.  This indicates missing
    entries and there could be something in the notes.
    
    I do agree to reject if there is just County and/or Place and/or
    Church ONLY as those with spreadsheets tend to fill lots of rows
    with this before transcribing then not delete them.
    
    E
    
    On 07/01/2016 15:06, Sherlock21 wrote:
    
    
      Please add validation of a file ( new or Replacement) and
        reject any where County and/or Placename/ and/or Church is
        present but no person data is. - these will be errors by
        spreadsheet users -
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
Ahh: you mean so that you can use these rows for identifying where there are no records so that the ( planned)  coverage works effectively if necessary?
Yes your reference to spreadsheet user's methodology is the likely cause of this - but it was not the reason for the mess in the file which gave rise to me raising this request.
