### ISSUE TITLE
Sever FR from FR1

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#706]
Currently FR is updated nightly from files that have been changed in FR1. 
This was the means by which FR was updated until transcribers were moved to FR uploading. 
There are no longer transcribers with access to FR1 upload. Hence it is time to stop the nightly update from FR1. 
Files in FR1 that might be needed in FR for some unknown reason in the future can still be accessed in FR1 by the coordinator/managers and loaded manually into FR.
There will just be no automatic system.

**Comment by edickens** [comment]
Kirk.  Please let EricB and me know when this is done.  We don't think it is a good idea to work on the Unprocessed Files until this is done.  TY  E

**Comment by Captainkirkdawson** [comment]
This is complete.
