### ISSUE TITLE
Processing task running on a slave

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#707]
This is a valid error as we do not expect to run this task on a slave. 
Issue is why is it trying to run on the slave??????????

[See this exception on Errbit]

(

**Comment by Captainkirkdawson** [comment]
I wonder if this could be caused by the administration cookie timing out at the time of submission for processing. 
Perhaps we need to have a test in the task to ensure it is running on the master server

**Comment by richpomfret** [comment]
To assign to Chee when he starts.

**Comment by AlexAvlonitis** [comment]
hello,
As i don't know much about the servers yet, i was thinking what if we run an if condition in the task, to run only if host == 'master_host_name'  to make sure it won't run on other servers.

**Comment by Captainkirkdawson** [comment]
That is the solution strategy. Mongoid has a function that provides the information. We are running mongoid 5 but the documentation on version3/4 is better
https://docs.mongodb.com/ruby-driver/master/mongoid/#ruby-mongoid-tutorial

**Comment by AlexAvlonitis** [comment]
Has the rake build:freereg_update been changed to build_ssl:freereg_update?
build_ssl.rake is the only place i can find :freereg_update task.
Line 434 -  i'm suggesting something like this to ensure it only runs on the server we want.
``` ruby
    host_name = `hostname`.strip
    if host_name == 'colobus.freebmd.org.uk'
      FreeregCsvUpdateProcessor.process(args.range,args.type,args.delta)
    else
      puts "It can only run on master server"
    end
```

**Comment by Captainkirkdawson** [comment]
Like a number of things they are not what they may appear.

The upload of a csv file either processes immediately or sets a flag to
process overnight

https://github.com/FreeUKGen/MyopicVicar/blob/master/app/controllers/csvfiles_controller.rb#L58-L68

The nightly update script undertakes a number of tasks one of them
processes those uploads waiting to be processed.

https://github.com/FreeUKGen/MyopicVicar/blob/master/lib/tasks/scripts/update_freereg2_production.sh#L1-L62

The explicit rake task is

sudo -u webserv bundle exec rake RAILS_ENV=production
build:freereg_new_update[create_search_records,waiting,no_force,a-9] --trace

so it is the task  build:freereg_new_update which initiates
new_freereg_csv_update_processor.rb

I suggest it is done in the code freereg_new_update_processor that needs to
check for master server.


https://github.com/FreeUKGen/MyopicVicar/blob/master/lib/new_freereg_csv_update_processor.rb

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by AlexAvlonitis** [comment]
https://github.com/FreeUKGen/MyopicVicar/blob/master/lib/new_freereg_csv_update_processor.rb#L61-L63
How about? 
``` ruby

    server_name = `hostname`.strip
    force, create_search_records = NewFreeregCsvUpdateProcessor.convert_to_bolean(create_search_records,force)
    @project =  NewFreeregCsvUpdateProcessor.new(Rails.application.config.datafiles,create_search_records,type,force,range,Time.new)
    @project.write_log_file("Started csv file processor project. #{@project.inspect} using website #{Rails.application.config.website}. <br>")

    unless server_name == 'colobus.freebmd.org.uk'
      @project.write_log_file("proccessing terminated, #{server_name} is not the master server")
      return
    end
```

**Comment by AlexAvlonitis** [comment]
https://github.com/FreeUKGen/MyopicVicar/pull/1025

**Comment by Captainkirkdawson** [comment]
see response to 1025

**Comment by AlexAvlonitis** [comment]
Please see: https://github.com/FreeUKGen/MyopicVicar/commit/d2c69a7756f08745cfd0e9e5fc3e7abb334c38c2

**Comment by Captainkirkdawson** [comment]
That would likely work however we do need to run the same code on test3 and our own development software. So rather than a positive test that is a primary why not go for a negative test. ie. error out if secondary preferred is detected. That then would work likely work in all environments. You might have other approaches.

**Comment by AlexAvlonitis** [comment]
Valid point https://github.com/FreeUKGen/MyopicVicar/commit/dd1357f4053eeac912ce88989bace87e462d20fd
It will only trigger if the node is secondary. if it's anything else or nil (dev environment) it will run
