### ISSUE TITLE
Navigation of Place Names table in alph grouped Counties  dont permit moving from one place yo another within a band.

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#708]
please follow this flow path:-
Pick your County
then the range.
select Active Places and scroll down a bit.
Select any place name then one of its church registers.

NOW try to navigate backwards on the breadcrumbs, as if you now wish to go to the placename next in the list. 

The first one ("breadscrum) you get to that you lets you select it, takes your right back to having to reselect either All places of Active places and start again.
Similar if one just selects All Places.

For those of us who did not want these selection bands as a means of skipping down the alphabet, it was much better all in one long scrollable list. - even if the bands do get to work as planned.

**Comment by Captainkirkdawson** [comment]
Navigation fixed.

Cannot revert to full scrollable lists because of server impact when 1000s of files are involved
