### ISSUE TITLE
Files with no entries/records

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#713]
When cleaning up the search records and entries I encountered the following files that had no entries/records. Could the Erics please review and determine if these files need to be reloaded and processed. This is separate from #723
barryross	STSNOEBA49.CSV	has 	0	 No entries
carolem132	SOMNFIBU.CSV	has 	0	 No entries
daddydingle	SSXBIGBU.CSV	has 	0	 No entries
dmoore	STSLIFBU50.CSV	has 	0	 No entries
dmoore	STSLIFBU51.CSV	has 	0	 No entries
Joynsonj	STSWLMBU50.CSV	has 	0	 No entries
Joynsonj	STSWLMBU51.CSV	has 	0	 No entries
Joynsonj	STSWLMBU53.csv	has 	0	 No entries
StephenAndrews63	NBLCAMBA.csv	has 	0	 No entries
ValC52	SRYBUCBA5.CSV	has 	0	 No entries
ValC52	SRYBUCBA6.CSV	has 	0	 No entries
ValC52	SRYBUCBA7.CSV	has 	0	 No entries
WalesViv	CGNABZBU.csv	has 	0	 No entries
MTokely	NFKNMOBU1.CSV	has 	2667	 No search record

**Comment by Sherlock21** [comment]
K

OK I am working through this list.

BUT one snag:
Stephen Andrews63 NBLCAMBA.csv is NOT an empty file.
it is there in Cambois in NBL if you look at Active Places. it contains 4413 records, and is dated 11 dec 2011.

it also matches the list files by userID.

So I fear something adrift with this. I will do no more on it.
*******
The last record in your email is also an odd one as it  actually says it has 2667 records but in fact has 3814 records last uploaded 19 may 2015 in FR.
So again I thing something is adrift.

so i will not do that one either until I have your comment.
***********


And these 3 files by ValC52 all have data in them   dated 1 Feb 1815.
so i will not do that one either until I have your comment.
 **********
Generally, EricD does not see any reason to remove Empty files > But i disagree with him. I see it your way .

ericB

**Comment by Captainkirkdawson** [comment]
It is essential that these files get addressed. The processor does not create files when there are no records. The situation has been caused by a system malfunction of some form over the past 9 months. I have no idea what or how except that it is likely when the file processor has crashed or been stopped when in the middle of doing something.
Allow me to assure you they are empty files no matter what the file information may say. On your first example display the records. There are none. The same for the 3 ValC52. All of the files that are in that list have no records.
On the last one that has no search records. It displays 2667 entries but none of them will be found in a search. The search records were not created.

These files need to be processed or removed.

The safest solution is to have the transcriber replace the file that is in the system.
If they cannot then we can:
If they exist in the physical files they can be reprocessed.
If they they are not in Physical Files then the most recent attic version can be downloaded and used. 
Maybe the coordinator has a copy. if we do not.
If we cannot get a file with records in there then the empty one needs to be deleted.
Regardless the CC likely needs to be aware

**Comment by edickens** [comment]
Kirk,
    EricB and I are not sure that Delete is working properly - another
    topic - so taking your last but one sentence, would it be better to
    just replace with a file that we create with just one valid record
    so as to create a file with records, and then delete that?  E
    
    On 15/01/2016 18:02, Kirk Dawson wrote:
    
    
      It is essential that these files get addressed. The processor
        does not create files when there are no records. The situation
        has been caused by a system malfunction of some form over the
        past 9 months. I have no idea what or how except that it is
        likely when the file processor has crashed or been stopped when
        in the middle of doing something.
        Allow me to assure you they are empty files no matter what the
        file information may say. On your first example display the
        records. There are none. The same for the 3 ValC52. All of the
        files that are in that list have no records.
        On the last one that has no search records. It displays 2667
        entries but none of them will be found in a search. The search
        records were not created.
      These files need to be processed or removed.
      The safest solution is to have the transcriber replace the file
        that is in the system.
        If they cannot then we can:
        If they exist in the physical files they can be reprocessed.
        If they they are not in Physical Files then the most recent
        attic version can be downloaded and used. 
        Maybe the coordinator has a copy. if we do not.
        If we cannot get a file with records in there then the empty one
        needs to be deleted.
        Regardless the CC likely needs to be aware
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Not aware of any issues with delete but would never be surprised at anything.
Not sure how what you suggest helps but be my guest

**Comment by Sherlock21** [comment]
OK.

I was going to do the job be deleting all 14 file names, then loading as if new, if it did not exist before this empty one.  But i will now get a copy from the CC of what should have been in that file, and do a reload myself So i can see what happens along the way - rather than ask the CC to do it.  I dont get much control that way round. It will be tomorrow before we see results.

**Comment by Sherlock21** [comment]
Kirk & ericD


OK,i have just reloaded the Transcriber's file copy of the daddydingle one for SSX.

complete success - tested by using SEARCH for a know entry in that file.

so off we go ( tomorrow) when i get the other copy files or resort to download.

thanks all.
eb

**Comment by Captainkirkdawson** [comment]
What is current status of this?

**Comment by Sherlock21** [comment]
Not at all sure where this one has got to.

I have not done any testing of a solution - ie reject files that have empty row(s) of data.
so may be still needed.

**Comment by Captainkirkdawson** [comment]
Code was added to the processor to avoid creating records when there were insufficient fields
