### ISSUE TITLE
Burial records does not create family member if the relative surname is blank.

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#714]
This burial entry { "_id" : ObjectId("546384a7e9379027821218f5"), "error_flag" : "false", "line_id" : "Hazel.NFKWYMBU3.CSV.1694", "file_line_number" : 1694, "register_entry_number" : null, "burial_date" : "14 Jun 1789", "year" : "1789", "burial_person_forename" : "Jeremiah", "relationship" : "son", "male_relative_forename" : "William", "female_relative_forename" : null, "relative_surname" : "CULPITT", "burial_person_surname" : "CULPITT", "person_age" : null, "burial_person_abode" : null, "notes" : null, "county" : "NFK", "place" : "Wymondham", "church_name" : "Virgin Mary and St Thomas a Becket", "register_type" : " ", "record_type" : "bu", "freereg1_csv_file_id" : ObjectId("546384a5e93790278212051d"), "u_at" : ISODate("2015-05-19T18:13:30.423Z"), "c_at" : ISODate("2014-11-12T16:02:47.554Z"), "multiple_witnesses" : [ { "_id" : ObjectId("546384a7e9379027821218f6"), "witness_forename" : null, "witness_surname" : null }, { "_id" : ObjectId("546384a7e9379027821218f7"), "witness_forename" : null, "witness_surname" : null } ], "record_digest" : "fL9SFYZCDv/Ikz0G04n5ng==" } 
correctly creates a search record with a family member
[ { "first_name" : "J650", "last_name" : "C413", "type" : "p" }, { "first_name" : "W450", "last_name" : "C413", "type" : "f" } ], "record_type" : "bu", "chapman_code" : "NFK", "father_first_name" : "William", "file_line_number" : 1694, "line_id" : "Hazel.NFKWYMBU3.CSV.1694", "transcript_names" : [ { "role" : "bu", "type" : "primary", "first_name" : "Jeremiah", "last_name" : "CULPITT" }, { "role" : "mr", "type" : "other", "first_name" : "William", "last_name" : "CULPITT" } ], "freereg1_csv_entry_id" : ObjectId("546384a7e9379027821218f5"), "place_id" : ObjectId("53cd4971eca9ebee4f00734e"), "search_names" : [ { "_id" : ObjectId("551083fbe93790f8ad53d8b0"), "first_name" : "jeremiah", "last_name" : "culpitt", "origin" : "transcript", "type" : "p" }, { "_id" : ObjectId("551083fbe93790f8ad53d8b1"), "first_name" : "william", "last_name" : "culpitt", "origin" : "transcript", "type" : "f" } ] }
freereg2:PRIMARY> db.freereg1_csv_entries.find({_id: ObjectId(""546384a7e9379027821218f5")})
However when the relatives surname is blank as in the following entry
{ "_id" : ObjectId("54639aa4e9379010fc87630a"), "error_flag" : "false", "line_id" : "brilyn.NFKWYMBU.CSV.176", "file_line_number" : 176, "register_entry_number" : null, "burial_date" : "30 Apr 1781", "year" : "1781", "burial_person_forename" : "Elizabeth", "relationship" : "wife", "male_relative_forename" : "Philip", "female_relative_forename" : null, "relative_surname" : null, "burial_person_surname" : "CRANNESS", "person_age" : null, "burial_person_abode" : null, "notes" : null, "county" : "NFK", "place" : "Wymondham", "church_name" : "Virgin Mary and St Thomas a Becket", "register_type" : "AT", "record_type" : "bu", "freereg1_csv_file_id" : ObjectId("54639aa3e9379010fc8760fc"), "u_at" : ISODate("2015-05-28T02:04:19.541Z"), "c_at" : ISODate("2014-11-12T17:36:36.108Z"), "multiple_witnesses" : [ { "_id" : ObjectId("54639aa4e9379010fc87630b"), "witness_forename" : null, "witness_surname" : null }, { "_id" : ObjectId("54639aa4e9379010fc87630c"), "witness_forename" : null, "witness_surname" : null } ], "record_digest" : "+x9jL4fbbdCiXy5I3Kq0XQ==" } 
it does not create a family member component of the search record
{ "_id" : ObjectId("5510b20fe937900271aa9e7e"), "transcript_dates" : [ "30 Apr 1781" ], "search_dates" : [ "1781-04-30" ], "location_names" : [ "Wymondham (Virgin Mary and St Thomas a Becket)", "[Archdeacon's Transcripts]" ], "search_soundex" : [ { "first_name" : "E421", "last_name" : "C652", "type" : "p" } ], "record_type" : "bu", "chapman_code" : "NFK", "father_first_name" : "Philip", "file_line_number" : 176, "line_id" : "brilyn.NFKWYMBU.CSV.176", "transcript_names" : [ { "role" : "bu", "type" : "primary", "first_name" : "Elizabeth", "last_name" : "CRANNESS" } ], "freereg1_csv_entry_id" : ObjectId("54639aa4e9379010fc87630a"), "place_id" : ObjectId("53cd4971eca9ebee4f00734e"), "search_names" : [ { "_id" : ObjectId("5510b20fe937900271aa9e7f"), "first_name" : "elizabeth", "last_name" : "cranness", "origin" : "transcript", "type" : "p" } ] }
In addition it has translated the relationship from a wife to a parent ie a father_first_name of "Philip"

**Comment by dougkdev** [comment]
As I started looking through the code to see what is causing this, it looks
like I'll be meddling with parts of the code that Ben will be looking at
for #706 and #731, and likely will be making more significant changes to in
#711.  As such, Ben and I should at least coordinate our efforts and it
might even make sense for him to pick this up instead of me since it is
somewhat related to those other 3 stories.

**Comment by benwbrum** [comment]
Agreed.  I'll take this one.
