### ISSUE TITLE
a Search for a record that has the event date of * * 1764 goes on for ever

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#715]
To check that an overnight processing job had been successful,i did a search for one record.
NFK/ Norwich/ Burial. Eliz Youngs/ bu * * 1764.
the search kept going for over 10 minutes then i ditched it. Is this caused by the date format?
Because doing another search for record that has a proper date in full format ddmmyyyy worked normally fast.

**Comment by Captainkirkdawson** [comment]
Unable to duplicate. A search for Eliz Youns in Norwich produces 21 results very quickly and results include the record with the  * * 1764. A search for Eliz Youngs in 1764 produces the required record. All searched extremely fast,

**Comment by Sherlock21** [comment]
K

Surname  was/ should have been YOUNGS.

I got Julie Harold to do it later on in the  and it ran OK.

So I too did  OK.

Must have been the time of day.

I did a Search run this morning somewhere before 9:30, and that too was very slow. Is overnight stuff still running at that time perhaps?
My computer was not doing anything else.

Lets not worry about it - too much else at the moment.
E

**Comment by Captainkirkdawson** [comment]
Yes I did use YOUNGS mistyped in response. 

The original comment says you searched for a record with * * 1764. How would you do that? 

There were no response issues at 09:30 GMT today. Any individual search can run long (if it is a complex search or producing large numbers of results) without creating a general response issue. 
The overnight work usually finished by 05:00 GMT.

**Comment by Sherlock21** [comment]
Yesterday's search was for one person as in box 1. for the data range I put something tight - like from 1760 to 1765 ish. and the Exact names and location.
This mornings search was for 1 person  ( surname/ County/ Place/and an exact year). I dont remember what - it did not start off as a test!

I only mentioned it now because it was roughly the same time of day as yesterday's and as you could not find a snag with the spec in box 1 above, I wondered on different lines - like busy machines at the time. quantity in the result today: about 20 max.

**Comment by Sherlock21** [comment]
PS if your question means how did I search for a date * * 1764, well I didn't.

I picked the last record from the file I had, and that had a date Baptism * * 1764 with a person with full names as I said in the initial box.
