### ISSUE TITLE
Entries per screen has changed - Change back please

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#717]

**Comment by edickens** [comment]
Last night someone changed the number of entries per screen on some reports, noticeably listing of batches.  What EricB and I were working on which was 3 screens has now become 25.  This is impossible to work with.  Please undo the change that was made.  E

**Comment by Sherlock21** [comment]
I am at a Complete standstill meanwhile. So ASAP please

**Comment by Captainkirkdawson** [comment]
Sorry about that.  Committed my test constants
