### ISSUE TITLE
Handling of other data from registers

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#718]
Do we want to transcribe / serve additional data transcribed from a register (e.g. note on harvest, purchase of font, etc.)?

**Comment by benwbrum** [comment]
Should that go in a note, or do we need a separate, register note?

**Comment by Captainkirkdawson** [comment]
There is nothing to stop the transcriber entering any such information in the notes field for the entry.
Similarly the coordinator can enter such information in the Register notes

**Comment by PatReynolds** [comment]
Notes about the church, register, or parish, etc. should be noted against the register, notes about the individual mentioned in the record should go in the record.

This is what already happens.  If done in Flexible CSV, the notes come up in the correct places. eg. note about place, church, or comment about someone in the record.
