### ISSUE TITLE
Files Not Processed snag

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#719]
There is an issue with this application. -I suspect some wrong files are being listed.
take UserID - Jean. file = GLSBABU1.csv. waiting since 09 May 2015 in FR. and I cannot download these files at all to see content.

BUT looking in the county/ Placename church : GLS/ Badgeworth/ Holy Trinity. there are a full matching collection of active files of more recent dates ( 4 nov 2015).
SO where to go? why are these in the Not Approved list? Do  just delete the version in the Not Processed list - what about the possibility of that action deleting the one that's in the Place name/ church listing.

**Comment by edickens** [comment]
Interesting.  Because this is an invalid filename.  Only two
    characters for the place code.
    
    These are her FR1 files, which most seem to be the wrong format, but
    have been accepted...
    
    
    
    And GLSBADBU1.csv is not  there.
    
    The header has even more errors...
    
    
    
    
    E
    
    On 29/01/2016 11:07, Sherlock21 wrote:
    
    
      There is an issue with this application. -I suspect some wrong
        files are being listed.
        take UserID - Jean. file = GLSBABU1.csv. waiting since 09 May
        2015 in FR. and I cannot download these files at all to see
        content.
      BUT looking in the county/ Placename church : GLS/ Badgeworth/
        Holy Trinity. there are a full matching collection of active
        files of more recent dates ( 4 nov 2015).
        SO where to go? why are these in the Not Approved list? Do just
        delete the version in the Not Processed list - what about the
        possibility of that action deleting the one that's in the Place
        name/ church listing.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
so would you be suggesting these in my list were an early version with the error in the fie name. that were abandoned and replaces with new files of normal format names into F1?

so i  can zap these GLSBABU1 etc files? And worry no more!

**Comment by edickens** [comment]
I wouldn't go as far as that.  But if a record is checked in each
    version, and they agree, then the Unprocessed could be zapped.  Or
    can we check the number of records in each version, and if they are
    the same then you could assume that they were the same.
    
    Alternatively, process them and produced duplicate records, which
    can be deleted later if found to be duplicates.  It is better to
    have duplicates than missing records.  E
    
    On 29/01/2016 12:00, Sherlock21 wrote:
    
    
      so would you be suggesting these in my list were an early
        version with the error in the fie name. that were abandoned and
        replaces with new files of normal format names into F1?
      so i can zap these GLSBABU1 etc files? And worry no more!
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
ON further digging, I suspect there is either a bigger issue, or a second, but related, issue.
The file WRYNECK/WRYSWCBA6.csv was uploaded in Dec 2015. It was correct.
Then these past day or two, there was another version of the same data, also by wryneck, was seen to be in the Not Processed listing, with a data of 6 Feb 2016 ( I think from memory) which was sitting there un processed, reading the content, it seemed the same DATA except the header details slightly different

I deleted the one in thr Nor Processed table, using the DELETE BUTTON ON THE TABLE.

But then on checking the place/ church/ files, there was no file wryneck/WRYSWCBA6.csv. in the church.
and there was now non in the refreshed Not Processed listing either.
Yet the view of the file in Not Processed showed clearly different files existed.
I have a copy of each. please tell me to whom I should send.??



I Deleted this one from the

**Comment by Captainkirkdawson** [comment]
The delete button in the physical files collection is a HARD delete. It deletes all copies in FR (both the base set used by FR and the copy from FR1.) It deletes all batches in FR as well as all entries and search records. The only remaining trace of the file is a copy in the attic for the userid
