### ISSUE TITLE
New report to list batch for easy scanning for errors

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#720]

**Comment by edickens** [comment]
When a SC gets a completed Batch, they need to sight scan it for obvious errors.  A report is needed to look like a Notepad view of the CSV file, including headers.

**Comment by Captainkirkdawson** [comment]
Is this the same as #730 View Batches in CSV format?

**Comment by edickens** [comment]
I think Yes.  E
    
      On 17/10/2016 22:33, Kirk Dawson wrote:
    
    
      Is this the same as #730
        View Batches in CSV format?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #720: Is this the same as #730 View Batches in CSV format?"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/720#issuecomment-254340918"}}}
