### ISSUE TITLE
Enable marking / non-use of  do-not-contact and bounced emails

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#723]

**Comment by PatReynolds** [comment]
Not sure if this means what I think it does - i.e. that bounced emails should lead to a volunteer / registered researcher being marked as 'uncontactable' (and not sent further emails.  Would also allow us to have an 'unsubscribe' function for non-active folk that could then be manually set to 'active' if they want to get emails again.

**Comment by PatReynolds** [comment]
Yes, having spoken with Eric, this is URGENT as is needed to ensure that we meet people's requests not to email them again (needed by end August 2016).

**Comment by Captainkirkdawson** [comment]
This requires human intervention. 

Whom ever monitors the email bounces needs to take action. 

There is NO link from the email system back into the app. I am totally unsure how one would ever construct such a system. At some point we need people to take action and control the system.

**Comment by PatReynolds** [comment]
Yes, a human will have to mark the email as 'deceased' or 'do not contact', etc.  This story is about making the system so that the human can make the marks.  Ideally, via CSV upload in the first place, as there is a rather a long list.

**Comment by CommsCoord** [comment]
I am happy to help with that if needed. Sandra
