### ISSUE TITLE
Improve Donate request

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#724]

**Comment by edickens** [comment]
We only have "Donate" on the home page.  Why not on the Search Results Details?  We should say "Have you found what you are looking for?  If so we could have saved you the cost of obtaining a copy of the register entry.  Would you like to make a small donation to keep our free service going?"  E

**Comment by PatReynolds** [comment]
Completed?

**Comment by SteveBiggs** [comment]
Yes it's done.
