### ISSUE TITLE
Add Printer Friendly to results list

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#725]

**Comment by edickens** [comment]
We have a Printer Friendly option for the detail but we have been asked to also have it for the Results found list.  This would be a page at a time, say 50 lines so as to be one sheet of paper.  The reason is that people like to print it out and tick off the entries as they check whether they are the right ones or not.

**Comment by PatReynolds** [comment]
1.4 or 1.7?

**Comment by edickens** [comment]
1.4.  We keep getting complaints.  E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 25/02/2016 14:56, PatReynolds wrote:
    
    
      1.4 or 1.7?
      —
        Reply to this email directly or view
          it on GitHub.
