### ISSUE TITLE
Close FR1 to all but the Search

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#726]

**Comment by edickens** [comment]
I am getting returning transcribers trying to log in to the old website and find their account disabled.  All Help, Login and Register pages should be removed, or just have a text to say to use the new website.  These are all html pages which I can edit, but I will then need BenL to do an update of these pages, but not the database.  However I don't want to do anything as drastic as this without approval.  E

**Comment by Sherlock21** [comment]
Does this conflict with the methodology of dealing with the 1140 records which did not get processed properly? this needs links back to F1 to get file contents from the userID ?file name.

**Comment by edickens** [comment]
Forgot that.  We'll have to keep FR1 logging in open to
    Coordinators.
    
    E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 10/02/2016 17:32, Sherlock21 wrote:
    
    
      Does this conflict with the methodology of dealing with the
        1140 records which did not get processed properly? this needs
        links back to F1 to get file contents from the userID ?file
        name.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by PatReynolds** [comment]
Should I close this?

**Comment by edickens** [comment]
Not done yet.  E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 25/02/2016 14:56, PatReynolds wrote:
    
    
      Should I close this?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by edickens** [comment]
Please can we do this sooner.  Someone has tried, and will succeed, to register into FR1.  All that is needed is to amend some of the FR1 pages and delete a few Perl programs.  I can amend the html pages and BenL needs to copy them to the place on the server after I have uploaded them.  E

**Comment by edickens** [comment]
He has now uploaded a file to FR1, so we have more of a mess to sort out.  E

**Comment by Sherlock21** [comment]
PAT - NO, its not this Github Topic that you should close - its F1. Yes: F1.

Who is saying NO? there is nothing on this ticket that records any objections .

Where's the Management here?

**Comment by Captainkirkdawson** [comment]
The FR  development team has no knowledge or experience of amending and updating FR1. The only person who does this is BenL.

**Comment by edickens** [comment]
And I can do all the html pages.  BenL and I did the monthly
    updating of the Parish Progress Pages.  E
    
      On 07/09/2016 14:16, Kirk Dawson wrote:
    
    
      The FR development team has no knowledge or experience of
        amending and updating FR1. The only person who does this is
        BenL.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #726: The FR  development team has no knowledge or experience of amending and updating FR1. The only person who does this is BenL."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/726#issuecomment-245276848"}}}
