### ISSUE TITLE
File naming standard in FR

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#727]
When starting a new file a three letter code is generated using the first three letters of the County name  followed by the Placename,  which is now not changeable

In the past CC's  have been asked to change this when doing non-conformist records or places with common starting initials

What is the new FR standard for file names
given the differing views of Replicate exactly what we had in F1, or adopt a method of including the date range of the data, or have a free for all with no structure?

**Comment by edickens** [comment]
There is not the same need in FR as there was in FR1 for standard
    filenames.  The important fields are the County, Place, Church in
    each entry.  WinReg forces a standardisation.
    But when we get to V1.5, I am proposing that Batches are used to
    manage the entries, and in this case the Batch name (not to be
    confused with the filename) will have much more meaning.  But we are
    not there yet.  E
    
    On 10/02/2016 17:30, Sherlock21 wrote:
    
    
      When starting a new file a three letter code is generated using
        the first three letters of the County name followed by the
        Placename, which is now not changeable
      In the past CC's have been asked to change this when doing
        non-conformist records or places with common starting initials
      What is the new FR standard for file names
        given the differing views of Replicate exactly what we had in
        F1, or adopt a method of including the date range of the data,
        or have a free for all with no structure?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
But my issue was raised to fit TODAY as this is where we currently are, and people are confused with what they should do today. CC Eric Wealleans raised this very question with me just yesterday.

**Comment by edickens** [comment]
In which case we do what we have always done...
    The file name must consist of: [three letter Chapman code for the
    county][a three letter placename code assigned by the person
    uploading the file][BA|BU|MA][part number, if any].CSV.
    The Coordinator to decide on the three letter placename code for
    consistency and it is usually the first three letters of the place
    name.
    The website has been amended so that when you look at the list of
    batches for a UserID or Church/Register type, the year range within
    each batch is shown, so this does not need to go in the filename.  E
    
      On 11/02/2016 11:13, Sherlock21 wrote:
    
    
    
      But my issue was raised to fit TODAY as this is where we
        currently are, and people are confused with what they should do
        today. CC Eric Wealleans raised this very question with me just
        yesterday.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
EricD

Fine with me.

But would you be good enough to issue the para you just added below, as a circular to ALL CCs & SC's.

thanks
EricB

**Comment by Captainkirkdawson** [comment]
There is no development work here

**Comment by edickens** [comment]
Have moved this to V1.5 for when we have decided how to process batches.  This may or may not be relevant.  E
