### ISSUE TITLE
View Batches in CSV format

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#730]

**Comment by edickens** [comment]
SC and CC and above ONLY, to have a new report which will list a Batch in csv format.  The reason is that it is necessary to check what a transcriber is doing and this is a good way to sight check how many UCF, or what is being put in the notes, very quickly.  The entries should be one per row and 100 rows per page.  The Batch header should also be shown at the beginning.
Another reason for this is that not all fields are shown at the same time at present.
E

**Comment by edickens** [comment]
With Edit button against each line to go to the Edit screen, then return to the same place.  Ali (WRY)

**Comment by Captainkirkdawson** [comment]
There is a download of a file in csv format. Coordinators and transcribers can list and edit entries., What is proposed in terms of linking from csv file to editing of specific records or fields is not viable
