### ISSUE TITLE
Active places report does not return to the place being looked at.

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#731]
Priority 17 or 11 ( 0	1	8/2	8)

**Comment by edickens** [comment]
The Active Places report used to return to the place being looked at so that the search can be continued from that place.   This used to work, but does not now that Ranges have been introduced.  Doreen

**Comment by dougkdev** [comment]
From the description, I am not sure what the desired functionality is that
is no longer working.  If I click on manage counties, then "active places"
I can select a range of letters, then it shows a list of the active places
in that letter range for that county.  This is the Active Places report you
are talking about, right?  Now I'm not sure what you mean by returning to
the place being looked at / continuing the search.  Can you describe the
steps you mean?  (I am not familiar with how it used to work).  Thanks.

**Comment by edickens** [comment]
The principle of all reports is that when you ask to Show the details, after that, when you use the Breadcrumb, you will return to where you were working.  In this case, for a county with hundreds of Active places,  you may be on page 3 of the report when you ask to see the details of that place, but now, when you go back, you go back to page 1, not back to the place you were looking at on page 3.  E

**Comment by Captainkirkdawson** [comment]
Need to store place_id and return to that one

**Comment by Captainkirkdawson** [comment]
Is this current version or version 2?

**Comment by richpomfret** [comment]
Closing.
