### ISSUE TITLE
Date of birth giving wrong impression of year range

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#732]

**Comment by edickens** [comment]
Now that Year of Birth has been introduced into the year range, it gives the wrong impression.  Someone can get baptised when they are 70,  so their birth year would be way outside the year range of the register.  Birth year should not be used for the Register year range.  This will become  even more important when we validate years included in the register.  Doreen

**Comment by edickens** [comment]
I'm not sure, but the year of birth is also used to determine the year range calculated for the batch and Church.  This might only be used when the BA year is not entered, but for someone who was baptised when older, this gives a wrong indication of the years in the register.  The year of birth should never be used for calculating the range of years.  However, we do have some registers of births.  I know that this should be FreeBMD, but these are pre-1837 and contain more than just the index.  So we transcribe them.  They will have year of birth only.  So how will the year range of the register be calculated?  Should they be a different Register Type and processed accordingly.

**Comment by Sherlock21** [comment]
1) we must transcribe the value of course/
2) And I think it would me a mistake to not to not include it in calculating the date range of the batch even if it does give a wrong impression because of a gap that is apparently introduced. 
3) Other gaps in the data will exist particularly if the source is a Transcription itself - like in some recent ones where the Transcription source covered 1701 to 1780 then 1850 t0 1910, all in the one document, thus giving the impression of 1701 - 1910. but it we do not include Births in calculating the range, then the thousands of files which undoubtedly have "correct" data will not get considered. And that would be more wrong in my opinion.

**Comment by edickens** [comment]
But the problem is that if the BA register range is 1850-1910 and
    someone is 60 when they are baptised, the BA is entered in this
    register year range, but the birth year could be 1790, giving the
    impression that this batch covers 1790 to 1910.
    What is needed, and I will come to it in V1.5, is a batch header to
    be created by the CC before transcribing starts.  This information
    to be taken from the actual document.  New fields are needed.  E
    
    On 17/02/2016 11:03, Sherlock21 wrote:
    
    
      1) we must transcribe the value of course/
        2) And I think it would me a mistake to not to not include it in
        calculating the date range of the batch even if it does give a
        wrong impression because of a gap that is apparently introduced.
        
        3) Other gaps in the data will exist particularly if the source
        is a Transcription itself - like in some recent ones where the
        Transcription source covered 1701 to 1780 then 1850 t0 1910, all
        in the one document, thus giving the impression of 1701 - 1910.
        but it we do not include Births in calculating the range, then
        the thousands of files which undoubtedly have "correct" data
        will not get considered. And that would be more wrong in my
        opinion.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
But in that case, the CC can only put in the dates on the Register image cover sheet or whatever, which will in effect omit all the actual records within the batch  and if its Baptisms in the Register concerned,  then even thought there is a field for birth date, if its used, you can;t include these dates in calculating the Register data range. - So why not just omit using the filed however its been sourced/  computed/ recorded or whatever  and stick to the range being: the Main event date of the REgister concerned?

 so no Baptism dates will be included in this Range value ( in the case of our Registers).

**Comment by edickens** [comment]
EricB - Do you mean BA dates in your last paragraph.  Surely Birth
    Dates.
    
    There are times when the entries in the register are outside the
    range of dates shown on the cover of the register book.  This is
    when some previous entries have been omitted.  These have to be
    accepted, but are they really indicative of the range of years
    covered by that register book?  E
    
    On 17/02/2016 13:26, Sherlock21 wrote:
    
      But in that case, the CC can only put in the dates on the
        Register image cover sheet or whatever, which will in effect
        omit all the actual records within the batch and if its Baptisms
        in the Register concerned, then even thought there is a field
        for birth date, if its used, you can;t include these dates in
        calculating the Register data range. - So why not just omit
        using the filed however its been sourced/ computed/ recorded or
        whatever and stick to the range being: the Main event date of
        the REgister concerned?
      so no Baptism dates will be included in this Range value ( in
        the case of our Registers). 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
Oh dear !
Yes, i did mean Date of Birth, as written in the Baptisms Register.
Very sorry for any confustion!

**Comment by Captainkirkdawson** [comment]
But if we use date of baptism only then we will appear to have files with no records and no range when they only have dates of birth. That was why we added the date of birth into the range calculation.
Seems we cause problems both ways!!! Personally I prefer it the way it is

**Comment by Sherlock21** [comment]
My preference is also to leave as is. - I wrote t previous "solution" as the debate seemed to want a bit of both worlds"

**Comment by Captainkirkdawson** [comment]
For information. Why are new fields needed??
The register information already includes the ability for coordinators to record the max and min dates of a register. To my knowledge no one has used it.

**Comment by edickens** [comment]
It is date range in Batches that they need to look for gaps that
    have not been transcribed.  But that is V1.5 RAP or GAP reports. 
    The date range in Register Type is very wide.
    
    E
    
    On 29/04/2016 14:46, Kirk Dawson wrote:
    
    
      For information. Why are new fields needed??
        The register information already includes the ability for
        coordinators to record the max and min dates of a register. To
        my knowledge no one has used it.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by Captainkirkdawson** [comment]
In other words this can be closed.
