### ISSUE TITLE
CC and SC to have Files Waiting to be Processed

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#734]

**Comment by edickens** [comment]
I'm not sure if this is a long term need.  Everything should be processed within 24 hours.  But we have asked CCs to look into the huge list of unprocessed files and this will make it easier to sort out this problem as we need CC and SC cooperation.  Ali (WRY)

**Comment by Sherlock21** [comment]
It may well be a long term need, as the list of such files grows day by day! - which I did not expect to be the case.

**Comment by edickens** [comment]
We need to find out why this list is growing.  It should not.  E
    
    On 11/02/2016 11:00, Sherlock21 wrote:
    
    
      It may well be a long term need, as the list of such files
        grows day by day! - which I did not expect to be the case. 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
Exactly!


I will raise a new topic for this in github issues.

and please note additional comment in #719


I shall STOP all NotApproved work as of now.

eb

**Comment by Sherlock21** [comment]
this is now on NEW topic #738

eb

**Comment by edickens** [comment]
The need for Coordinators to see this report is not the same as fixing why the Unprocessed report is growing.
Also, I understand that SCs can see the Unprocessed report but not CCs.  Although often these are the same people, there is a difference when a UserID works for a different syndicate then the SC cannot see their files.  So this report should say to let CCs have the same access as SCs.

**Comment by edickens** [comment]
Correction to above.  SCs have waiting to be processed but not Unprocessed.  CCs have neither.  Both should have the Waiting and Unprocessed reports.  E

**Comment by Captainkirkdawson** [comment]
Will look at the CC having access to waiting. Since most CCs are SCs and SCs already have access to the waiting list it does not appear to be high priority.
WRT to Unprocessed files; this could be made available to CCs;  and perhaps SCs. However it is important to remember that Coordinators have not been exposed to the physical file concept as implemented in FR which is similar to the old FR1 file concept; except there are 2 file repositories. On FR we have moved to a record based system and coordinators actually work with "processed" record collections which we called batches; many of them still think in terms of the old unprocessed files.  Hence I see significant likelihood for long term confusion developing by making it available.

**Comment by Sherlock21** [comment]
i am inclined to agree with Kirk's view. But I put this in because some CC's - like STS and WRY asked me for it.

**Comment by edickens** [comment]
Like EricB, I agree with Kirk.  I'm also concerned that the
    "unprocessed report" will cause confusion.  Nothing should be
    "Unprocessed" after the overnight update.  And if we can get the
    update to process larger files, then the overnight update may not be
    needed.  I'd like to know why the "Unprocessed" report is needed. 
    Is it because transcribers are not getting their confirmation email,
    which I know happens because of wrong email addresses and spam
    filters?
    
    The reason for the SC to see these reports is that, although all?
    are both SC and CC, the transcribers work for a number of different
    counties and may not be a member of their syndicate when the CC
    needs to know what is going on.
    
    Unfortunately for now we will always think of files because that is
    what WinReg and Excel create and data is uploaded as set of records
    which are files within Windows.  This will only change when we use
    full online data entry.
    
    Eric
    
    
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 13/03/2016 22:57, Kirk Dawson wrote:
    
    
      Will look at the CC having access to waiting. Since most CCs
        are SCs and SCs already have access to the waiting list it does
        not appear to be high priority.
        WRT to Unprocessed files; this could be made available to CCs;
        and perhaps SCs. However it is important to remember that
        Coordinators have not been exposed to the physical file concept
        as implemented in FR which is similar to the old FR1 file
        concept; except there are 2 file repositories. On FR we have
        moved to a record based system and coordinators actually work
        with "processed" record collections which we called batches;
        many of them still think in terms of the old unprocessed files.
        Hence I see significant likelihood for long term confusion
        developing by making it available.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
EricD

Initially, it was that Kirk found that some files had been left behind over the months - for reasons  said to  include: when the system crashed it did not pick up all the leftovers?

EB

**Comment by edickens** [comment]
Yes, and the reason why the CC wants this report is so that they can 
sort it into a logical sequence for checking, which is likely to be 
Place/Church so that they can see if it has actually been processed.  E
