### ISSUE TITLE
Advise researchers that they must provide or state evidence of an error

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#735]

**Comment by edickens** [comment]
When a researcher reports an error they need to be advised that they must say why they think that there is an error.  Preferably with a screen print, otherwise state where they have found what they think is the correct entry,  or state their reason, such as it is their family.  E

**Comment by PatReynolds** [comment]
I think this runs against the current help statement, which says they can
ONLY request corrections which are errors in transcription.  We do not
correct earlier transcribers (eg Bishops transcripts) or the errors of the
writer of the original text.

I think we already have a story about researchers ability to write notes,
which seems like the natural home for such corrections.

**Comment by edickens** [comment]
Yes.  We must not change the transcription if it is correct.  We can add 
an extra record with the alternative suggestion.  However, we do find 
that the suggestion is sometimes that they have found the wrong person.  
So we need to be sure that we are putting in a correct alternative.  
That is why the researcher needs to provide evidence, rather than just 
saying what they think the name should be, without saying why they think 
that.
Even when we get to letting researchers leave comments, these will need 
to be moderated.  Also, these notes will not create a searchable entry, 
unless we have a system for the CC to be able to convert it to an entry.  E

**Comment by PatReynolds** [comment]
We don't take odd/partial register transcriptions so creating new entries
from information provided about a single event seems to go against this.

In the long term this will be resolved by discussions about data linking,
standards, etc which the Trustees began discussing two weeks ago.

Best wishes,

Pat
