### ISSUE TITLE
SC to be able to delele UserIDs

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#737]

**Comment by edickens** [comment]
At present an SC has to email the System Administrator to be able to delete a UserID.  This was sensible at the start as they could delete anyone.  But now it would be useful if they can delete a UserID, but only if it is in their Syndicate and if there are no Batches associated with that UserID.  An "Are you sure" is needed too.  Make sure that there are no other implications.
The reason for deleting is that we get a high percentage of people who register, but then realise that there is more to transcribing than they thought and never do anything.  They just clutter up the system.   Steve

**Comment by PatReynolds** [comment]
As user ids are key to transcriber identification for open data, they
should only be deleted in the cases where someone has not transcribed
anything. I would have thought this was a small number - so added to the
auto tidy-up, or done by someone in the management team on occasion or on
request?

Best wishes,

Pat

**Comment by edickens** [comment]
Pat - It is not a small number.  25% would not be impossible.  There are 
over 2,000 UserIDs on file and yet only about 300 are transcribing at 
present.  Quite a few register because they think they can then get 
access to more detailed information, or they fancy transcribing and then 
they realise that they need a few basic computer skills, so never do 
anything.  E

**Comment by PatReynolds** [comment]
Can the ids with no associated records which are more than a set period old
not be deleted automatically?

Otherwise, we will need to ensure that a coord can only delete an I'd with
no associated records.

Best wishes

Pat

**Comment by Sherlock21** [comment]
I would have thought that if a record exists, however old it is, then the ID of the transcriber also needs to exist with it.
 For as long as the record exists.

EB

**Comment by edickens** [comment]
IDs can always only be deleted now when they have no records.  E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 13/02/2016 16:45, PatReynolds wrote:
    
    Can the ids with no associated records which are more
      than a set period old
      not be deleted automatically?
      
      Otherwise, we will need to ensure that a coord can only delete an
      I'd with
      no associated records.
      
      Best wishes
      
      Pat
      On 12 Feb 2016 14:47, "Eric Dickens"
      <notifications@github.com> wrote:
      
      > Pat - It is not a small number. 25% would not be impossible.
      There are
      > over 2,000 UserIDs on file and yet only about 300 are
      transcribing at
      > present. Quite a few register because they think they can
      then get
      > access to more detailed information, or they fancy
      transcribing and then
      > they realise that they need a few basic computer skills, so
      never do
      > anything. E
      >
      > On 12/02/2016 08:17, PatReynolds wrote:
      > > As user ids are key to transcriber identification for
      open data, they
      > > should only be deleted in the cases where someone has
      not transcribed
      > > anything. I would have thought this was a small number -
      so added to the
      > > auto tidy-up, or done by someone in the management team
      on occasion or on
      > > request?
      > >
      > > Best wishes,
      > >
      > > Pat
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
<https://github.com/FreeUKGen/MyopicVicar/issues/737#issuecomment-183245489>
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Ability provided but will only be carried out if the userid has not uploaded files

**Comment by edickens** [comment]
Good idea.  That was our concern.
    
    E
    
      On 20/06/2016 23:36, Kirk Dawson wrote:
    
    
      Ability provided but will only be carried out if the userid has
        not uploaded files
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
