### ISSUE TITLE
The Not Approved listing is continuously growing.

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#738]
there are daily additions of new files to this list.
Sometimes, the new addition has nothing to do with the ones deleted, sometimes it does seem to "recycle" and show a previously done one.

**Comment by Sherlock21** [comment]
Some of these files are recorded on here as"  loaded onto FR as far back as in 2005 - which is before FR was created isn't it?

**Comment by edickens** [comment]
No,  FR1 started in 1998.  But most files have been modified at some
    time since then.  E
    
    On 11/02/2016 19:39, Sherlock21 wrote:
    
    
      Some of these files are recorded on here as" loaded onto FR as
        far back as in 2005 - which is before FR was created isn't it?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
I am referring to FR as the new FreeReg - what we called FR2 once upon a time, and not mixed up with F1.

**Comment by dougkdev** [comment]
Eric, which list is this story referring to as the "Not Approved" list?  Is this the "files not processed" list under the "physical files" action?  Thanks.

**Comment by Sherlock21** [comment]
Doug..

Log on as DM.
Pick Physical files.

then in the  LH column, the first item.
see screen print attaches.

It was written by Kirk, just before he went on hols. to clean out a pile of rubbish that had accumulated for unknown reasons.

I expected it to get worked down to zero - but despite the numbers I resolved it seemed to keep the same size even when one allowed for those genuine files uploaded and awaiting processing that following night.
eric b

**Comment by Captainkirkdawson** [comment]
Could I request  some specific information on where and why it is thought that the list is growing?

**Comment by Sherlock21** [comment]
Kirk
you asked for an example: well the first on the list now is: 29thgirb / DORCHEMA.csv. this file was  in Place name DOR / CHEDDINGTON  I downloaded this file, so aas to correct the place name and change the file name too.
Then I corrected the place name ( using change Place name) and then  uploaded the file with its new name ( as A new file) in the ID of the Transcriber 29thgirb.
On screen message  indicated change name OK, then file uploaded OK and processed now ( only 50 or so rows). 

So why is this old one here now? It was not on this list when I downloaded a copy and then deleted it>

AND where is the new file now? Not in the corrected place name (DOR / Chedington)?

ALSO, when /i suspended the task of reloading these files there were 3 pages in the list. Now there are 4 pages.

**Comment by Captainkirkdawson** [comment]
How did you delete it?

**Comment by Sherlock21** [comment]
I would imagine that i/ used the "Destroy Place" button when I have removed the batch.
but as I was not keeping detailed notes, i can't be totally sure. - But how else could it have been deleted.?
As to where is the file i uploaded? could it be that I did not actually do that - since there are only 3 files for this User and none i the DORCHJMA one?

Can audit of my actions over the last Saturday &Sunday throw any light on this aspect perhaps?

**Comment by Captainkirkdawson** [comment]
There are 3 possible locations. The one you note, the Remove a Batch used by Coordinators and the other is in the Physical Files display. They operate in different manners, This has led me to consider there may be a logic issue that does indeed lead to this issue. More research needed.

**Comment by Sherlock21** [comment]
K

your question set me thinking too.

I dont remember ever testing this "destroy" path i referred to :( ie coming from the Place name and its batches.) as different tot he method coming from the Spreadsheet like display of all batches in various listings, where the action buttons are just 2 letters.

So is that what you are also wondering?

E

**Comment by Captainkirkdawson** [comment]
Possibly.

**Comment by Captainkirkdawson** [comment]
WRT DORCHJMA.csv
#<Mail::Message:17402735420, Multipart: false, Headers: <Date: Sat, 12 Mar 2016 16:55:57 +0000>, <From: freereg-processing@freereg.org.uk>, <To: colin@woolston34.plus.com>, <Cc: capn-bob@pegleg2.com>, <Message-ID: <56e44a1d7b285_da4e4012c5bf05728@colobus.freebmd.org.uk.mail>>, <Subject: 29thgirb/DORCHJMA.csv failed to be processed by FreeReg at 2016-03-12 16:55:57 +0000>, <Mime-Version: 1.0>, <Content-Type: text/html>, <Content-Transfer-Encoding: 7bit>>
Started a build at 2016-03-12 16:55:56 +0000with options of add with true search_records, a base directory at /raid/freereg2/users, a change directory at /raid/freereg2/freereg1/users and a file 29thgirb/DORCHJMA.csv and a delta change that was run at 12/03/2016 16:55
1	 files selected for processing
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 4
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 5
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 6
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 7
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 8
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 9
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 10
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 11
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 12
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 13
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 14
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 15
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 16
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 17
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 18
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 19
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 20
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 21
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 22
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 23
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 24
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 25
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 26
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 27
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 28
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 29
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 30
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 31
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 32
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 33
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 34
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 35
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 36
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 37
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 38
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 39
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 40
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 41
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 42
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 43
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 44
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 45
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 46
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 47
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 48
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 49
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 50
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 51
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 52
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 53
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 54
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 55
29thgirb	DORCHJMA.csvThe Place Cheddington is unapproved and rejected at line 56

**Comment by Captainkirkdawson** [comment]
There are 2 Chedington place names
{ "_id" : ObjectId("53cbf5d3eca9eb03a6002b9c"), "chapman_code" : "DOR", "country" : "England", "county" : "Dorset", "disabled" : "false", "genuki_url" : "http://www.genuki.org.uk/cgi-bin/gazplace?GR=ST480060,PLACE=CHEDINGTON,CCC=DOR", "grid_reference" : "ST4805", "latitude" : "50.842176", "location" : [ -2.7399101, 50.842176 ], "longitude" : "-2.7399101", "master_place_lat" : "50.842176", "master_place_lon" : "-2.7399101", "modified_place_name" : "chedington", "original_chapman_code" : null, "original_country" : null, "original_county" : null, "original_grid_reference" : null, "original_latitude" : null, "original_longitude" : null, "original_place_name" : null, "original_source" : null, "other_reason_for_change" : null, "place_name" : "Chedington", "reason_for_change" : null, "source" : "Gazetteer", "u_at" : ISODate("2014-07-26T13:31:02.417Z") }
{ "_id" : ObjectId("53cd4999eca9ebee4f00ba02"), "chapman_code" : "DOR", "country" : "England", "county" : "Dorset", "data_present" : false, "disabled" : "false", "genuki_url" : "http://www.genuki.org.uk/cgi-bin/gazplace?GR=ST488054,PLACE=CHEDDINGTON,CCC=DOR", "grid_reference" : "ST488054", "last_amended" : "15 Dec 2009", "latitude" : "50.845844", "location" : [ -2.728605, 50.845844 ], "longitude" : "-2.728605", "master_place_lat" : "51.84784", "master_place_lon" : "-0.66429", "modified_place_name" : "chedington", "original_chapman_code" : "DOR", "original_country" : null, "original_county" : "Dorset", "original_grid_reference" : null, "original_latitude" : "51.84784", "original_longitude" : "-0.66429", "original_place_name" : "Cheddington", "original_source" : "GeoNames", "other_reason_for_change" : null, "place_name" : "Chedington", "reason_for_change" : null, "source" : "GeoNames", "u_at" : ISODate("2016-03-12T16:49:27.053Z"), "alternate" : "", "place_notes" : "" }

**Comment by Sherlock21** [comment]
The Cheddington with 2 D's was an upload by me to get rid of zero data rows in the original loaded file.

But it would seem it did not  run in time before I then changed the place name from the "2 x D" into 1 x D, and the file name as well.

Maybe I should have only dome one bit each day
It will be better when the uploader gets the  on screen report I think than I would have the full picture.

I have a file I can upload into the right place if its easier for you - just zap these.

**Comment by Captainkirkdawson** [comment]
The duplication of chedingtons have been removed. Please reload your file

**Comment by Captainkirkdawson** [comment]
The growth was caused by not deleting the entry in the Physical Files collection on a delete of a batch. Problem fixed.
Need to clean up the Physical Files collections

**Comment by Sherlock21** [comment]
Correct file now uploaded OK. contents checked too.  

COMPLETE
