### ISSUE TITLE
Clean up program

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#740]

**Comment by edickens** [comment]
I suggest that we have a clean up program to be run once a month to do certain operations.  The first lot that I can think of are:-
- Destroy Register Types with no Batches.  It is likely that the batches have been moved to a different register type.
- Destroy Contact and Feedback reports which have had replies, but no more replies have been added in the last six months.
- Destroy Unapproved places with no Batches.  The batch will have been corrected.
- Destroy Churches with no Register Types, after destroying Register Types with no batches.  These most likely be spelling errors that have been corrected.

**Comment by Sherlock21** [comment]
I am not so sure about destroying churches with no batches. In some big cities where its useful to properly designate the church names in a common style, I had though have entering these 'ready'
eg London, York, Birmingham, Bath & Bristol . Though London is possibly fully populated now with at least one batch per listed Church.

**Comment by AlOneill** [comment]
Also, if we are going to be encouraging Coords to set up Church/Reg Type *before* transcription is begun, there there could be quite a lag before transcriber uploads, especially if latter is following the 'Best practice' guidelines.

**Comment by edickens** [comment]
Agreed.  Perhaps it should just be "Unspecified" Register Types with
    no Batches that we delete.  Also, any Church with no Register Types,
    because one should be set up when the Church is set up as that
    specifies the year range of the registers.  But perhaps that is a
    step too far at this stage.  E
    
    On 11/02/2016 18:46, AlOneill wrote:
    
    
      Also, if we are going to be encouraging Coords to set up
        Church/Reg Type before transcription is begun, there
        there could be quite a lag before transcriber uploads,
        especially if latter is following the 'Best practice'
        guidelines.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
WRT Churches and Register Types; destruction of these should always be a human decision.  Destruction of feedback/contact automatically requires a change to the system to monitor replies

**Comment by edickens** [comment]
Yes, they perhaps should be  a human action, but the CC needs to know where to look.  It is unrealistic to expect them to look through every Place/Church to find these records.  And there could be other things that need tidying up.
Suggest we look at this again after RAP/GAP/Image Allocation are done. E
