### ISSUE TITLE
Duplicate search results

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#742]

**Comment by edickens** [comment]
The following shows what is happening.  (I can't insert the example images so please ask for the full email from EricB if you want to see them.)

I have done a check on 2 random selected records in MDX/ Westminster / St Margaret church.

1) groom name Gilbert WESTE, (m 1629)
and one gets 3 records. see below.



the first comes from file:  Ishelton. MDX.MDXWSMMA.csv.1
second from		-ditto- MA2.1
third from		-ditto- MA.csv.1	




Then I did the same search using FEMALE person - exactly same result.

repeated this with a different person ( same church) - exactly same results both ways.


I also tried it with  a year that was not split 	-exactly same result







SO there is a snag in our Search Tool.

I looked up details of one of the records and there is not duplication

The person details dont muddle the situation by others in the record sharing the same name(s)
 


PLEASE can you put this into a BUG report for me - I have to go out now.

many thnaks
ericb

**Comment by Sherlock21** [comment]
I tried search on NFK/ SALLE/ and also on NFK/ Hackford(Eynesford) for a marriage and both cases came back correctly, with only the one record.
These 2 searches were on my own data files - which I know have not been changed or relocated etc since upload - is this significant?

**Comment by Sherlock21** [comment]
Note I made a reading error int he UserID's in the file names above.
CORRECT userID's + file names are here
lasheltonMDX.MDXWSMMA.CSV
and the other is
lshelton.MDXWSMMA.CSV

the first uid begins with Iacsh

whilst the second without the "a"

They look like 2 versions of the same person Lynda Shelton from NFK syndicate

The search shows a record for the marriage of William Watts on 1 jan 1628/9 in each of these 2 files
  
AND when I browse the file lashertonMDX/MDXWSMMA.csv, the first data row is for William Watts, as the search shows.

 I cannot find the file MDXWSMMA in for the userID lshelton anywhere. So how where does the search tool get it? 
NOR can I find the file under  Allfiles.

**Comment by dougkdev** [comment]
This marriage occurs in the search results 3 times:
lshelton.MDXWSMMA.CSV.40
lasheltonMDX.MDXWSMMA.CSV.40
lasheltonMDX.MDXWSMMA2.CSV.40

The same user has two user accounts: lshelton and lasheltonMDX (one starts with "ls", the other with "la").

There are three files with this marriage in it:
1) lshelton has MDXWSMMA.CSV  I can see the batch when I list the batches for user lshelton (Your Actions, Manage Userids, Select Specific Userid, lshelton, List Batches).  The list is long, so you may need to hit control-f to search for the filename in the page (command-f if you are on a mac).  This marriage record is in the batch on line 40 (Show the batch, then browse the records in the batch to confirm that the marriage is on line 40). I can also see the file in the list of physical files for the userid lshelton (Your Actions, Physical Files, Files for Specific Userid, lshelton / All).

2) lasheltonMDX also has a file named MDXWSMMA.CSV  I can see the batch when I do: Your Actions, Manage Userids, Select Specific Userid, lasheltonMDX, List Batches.  Show the batch, then browse the records in the batch to confirm that the marriage is on line 40.  I can also see the file in the list of physical files for userid lasheltonMDX (Your Actions, Physical Files, Files for Specific Userid, lasheltonMDX / All).

3) lasheltonMDX has a file named MDXWSMMA2.CSV  I can see the batch in the list of batches for lasheltonMDX. I can also confirm the marriage is on line 40.  I can also see the file in the list of physical files for userid lasheltonMDX.

In this case, the search results seem to reflect exactly what is in the data.  This does not appear to be a bug unless I misunderstood the problem that was reported.

**Comment by benwbrum** [comment]
I agree with Doug's assessment.  If three files contain the same record,
the record should appear in the search results three times.
