### ISSUE TITLE
Search form does not  populate the places for NFK

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#743]

**Comment by Sherlock21** [comment]
When selecting the County = NFK, the table for Place names does not populate. - Select any other County and it does populate correctly and speedily.
Nevertheless, if one fills in the rest of the search and submits, and a positive result is received, THEN returns to do a Revise Search, the Place names table is populated.

**Comment by dougkdev** [comment]
The ajax response to the request for places in NFK was returning two copies of the information.  Instead of "{all the data here}" the response was "{all the data here}{all the data again}".  Several places in NFK had "last changed" dates within the last couple of days, so there may be some strange issue where things aren't updating properly when changes are made, or the recent changes may have nothing to do with the issue that arose.
At Ben's suggestion, I ran the refresh_places_cache rake task and NFK is now populating.  If this issue arises again, refreshing the places cache (only takes a few minutes to run) seems to have fixed the issue, but a deeper investigation into why the problem arose in the first place is probably in order at some point.

**Comment by edickens** [comment]
Doug,
    
    Would it help if we find out what changes were being made to those
    NFK places?  Only EricB should be able to make changes to the Places
    list.  If so, please supply a couple of place names.
    
    EricD
    
    On 22/02/2016 21:46, dougkdev wrote:
    
    
      The ajax response to the request for places in NFK was
        returning two copies of the information. Instead of "{all the
        data here}" the response was "{all the data here}{all the data
        again}". Several places in NFK had "last changed" dates within
        the last couple of days, so there may be some strange issue
        where things aren't updating properly when changes are made, or
        the recent changes may have nothing to do with the issue that
        arose.
        At Ben's suggestion, I ran the refresh_places_cache rake task
        and NFK is now populating. If this issue arises again,
        refreshing the places cache (only takes a few minutes to run)
        seems to have fixed the issue, but a deeper investigation into
        why the problem arose in the first place is probably in order at
        some point.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
I have not made any changes to Place names in NFK for a while now.
- The only changes I remember doing are in SOM and GLS in the last couple of days.

**Comment by dougkdev** [comment]
It may not have anything to do with actually changing place names. I'm not positive what the "last changed" date means (in the Active Places list).  It may just be the last time records were added or updated in that place? 
Here are a few that have 21 Feb 2016 as their date:
Great Plumstead, St. Mary (Transcript)
Great Yarmouth, St Nicholas (Archdeacon's Trans. and Parish Reg.)
Shereford, St Nicholas (Archdeacon's Trans. and Transcript)
Sheringham (Parish Reg. and Trans.)
also several other places starting with "S".

**Comment by dougkdev** [comment]
Before you spend too much time looking at the changes, I'll take a peek at the code to see when that date gets updated.

**Comment by dougkdev** [comment]
The info bubble for that column says "The most recent date when at least one record in the register was amended, added or deleted."

**Comment by Sherlock21** [comment]
I can confirm that these listed Place names have NOT been changed ( by me, as DM) this month. - eb

**Comment by Sherlock21** [comment]
Perhaps then, Doug, the label is not quite right - as it suggests the actual Place name change rather than some of the data doesn't it.

**Comment by edickens** [comment]
Great Yarmouth, St Nicholas was update in last nights update.
    vk3dwu	NFKGYAMA1.CSV	processed  2431 data lines for location NFK, Great Yarmouth, St Nicholas, PR, ma;  0 unchanged and 0 removed.  0 header errors and 0 data errors
vk3dwu	NFKGYABU6.CSV	processed  2402 data lines for location NFK, Great Yarmouth, St Nicholas, PR, bu;  0 unchanged and 0 removed.  0 header errors and 0 data errors
vk3dwu	NFKGYABU5.CSV	processed  1201 data lines for location NFK, Great Yarmouth, St Nicholas, PR, bu;  0 unchanged and 0 removed.  0 header errors and 0 data errors
vk3dwu	NFKGYABU1.CSV	processed  2382 data lines for location NFK, Great Yarmouth, St Nicholas, PR, bu;  2382 unchanged and 0 removed.  0 header errors and 0 data errors
    This same transcriber also uploladed Great Yarmouth on 21st.  The
    first report of the problem that I can find is 15:34 on 21st
    #35998447.
    
    E
    

    On 22/02/2016 22:06, dougkdev wrote:
    
    
      It may not have anything to do with actually changing place
        names. I'm not positive what the "last changed" date means (in
        the Active Places list). It may just be the last time records
        were added or updated in that place? 
        Here are a few that have 21 Feb 2016 as their date:
        Great Plumstead, St. Mary (Transcript)
        Great Yarmouth, St Nicholas (Archdeacon's Trans. and Parish
        Reg.)
        Shereford, St Nicholas (Archdeacon's Trans. and Transcript)
        Sheringham (Parish Reg. and Trans.)
        also several other places starting with "S".
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by PatReynolds** [comment]
Norfolk populates properly for me (chrome).

**Comment by Sherlock21** [comment]
NFK populates for me again now.
Thanks, All.

Yes you can close it for me Pat
