### ISSUE TITLE
PlaceNames list display gone wrong after changing a placename

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#745]
Having deleted a batch, then the church name,
I changed a Place name from GLS/ Boxwell & Leighterton to just Boxwell, I noticed that the display on All Places,  now has an extra half line of empty space between Boxwell and the next place, Bradley.
Logging out and back in does not shift this space NOR does empty Caches, NOR does reset Safari.

This only happened after I have changed the place name.

**Comment by Captainkirkdawson** [comment]
Reason is that there are 2 places named Boxwell
freereg2:PRIMARY>  db.places.find({place_name: "Boxwell"})
{ "_id" : ObjectId("53cbf5deeca9eb03a6003f25"), "chapman_code" : "GLS", "country" : "England", "county" : "Gloucestershire", "disabled" : "false", "genuki_url" : "http://www.genuki.org.uk/cgi-bin/gazplace?GR=ST810920,PLACE=BOXWELL,CCC=GLS", "grid_reference" : "ST8192", "latitude" : "51.626491", "location" : [ -2.2758743, 51.626491 ], "longitude" : "-2.2758743", "master_place_lat" : "51.626491", "master_place_lon" : "-2.2758743", "modified_place_name" : "boxwell", "original_chapman_code" : null, "original_country" : null, "original_county" : null, "original_grid_reference" : null, "original_latitude" : null, "original_longitude" : null, "original_place_name" : null, "original_source" : null, "other_reason_for_change" : null, "place_name" : "Boxwell", "reason_for_change" : null, "source" : "Gazetteer", "u_at" : ISODate("2014-07-26T13:31:05.084Z") }
{ "_id" : ObjectId("53cd4998eca9ebee4f00b89c"), "chapman_code" : "GLS", "country" : null, "county" : "Gloucestershire", "data_present" : false, "disabled" : "false", "genuki_url" : "http://www.genuki.org.uk/cgi-bin/gazplace?GR=ST829910,PLACE=BOXWELL%20AND%20LEIGHTERTON,CCC=GLS", "grid_reference" : "ST829910", "last_amended" : "23 Apr 2011", "latitude" : "51.617562", "location" : [ -2.248378, 51.617562 ], "longitude" : "-2.248378", "master_place_lat" : "51.617562", "master_place_lon" : "-2.248378", "modified_place_name" : "boxwell", "original_chapman_code" : "GLS", "original_country" : null, "original_county" : "Gloucestershire", "original_grid_reference" : "ST829910", "original_latitude" : "51.617562", "original_longitude" : "-2.248378", "original_place_name" : "Boxwell and Leighterton", "original_source" : "Genuki", "other_reason_for_change" : null, "place_name" : "Boxwell", "reason_for_change" : null, "source" : "Genuki", "u_at" : ISODate("2016-02-25T19:24:16.327Z"), "alternate" : "" }

**Comment by Sherlock21** [comment]
The One with GR 810920 as the Genuki url link is the right one.

is this why I see a half height empty row in the Application too? 
I think there may be a fourth one form a few months back somewhere in the github issues list from me too.

**Comment by Captainkirkdawson** [comment]
Specific issue cleaned up.
Need to write check to avoid renaming to existing place
