### ISSUE TITLE
Do not Download Files that include batch with error records

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#750]
Priority 17 (0	3	6	8)

Download omits error records, so if this file overwrites the transcribers version these records are lost.

**Comment by edickens** [comment]
Either the Download should be refused until the errors are corrected (although there could be hundreds if is a placename, or the error records should be downloaded as they are with the error for correction in WinReg.

**Comment by Captainkirkdawson** [comment]
Placename errors never get to be loaded.
Cannot include error records they do not exist in the database.
Only solution is to refuse to download a file that has a batch  with errors

**Comment by edickens** [comment]
Understood why not possible.  But is there a way to view the
    original file in CSV format?  E
    
      On 17/10/2016 00:40, Kirk Dawson wrote:
    
    
      Placename errors never get to be loaded.
        Cannot include error records they do not exist in the database.
        Only solution is to refuse to download a file that has a batch
        with errors
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #750: Placename errors never get to be loaded.\nCannot include error records they do not exist in the database.\nOnly solution is to refuse to download a file that has a batch  with errors"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/750#issuecomment-254085458"}}}

**Comment by Captainkirkdawson** [comment]
As a result:
Files will not download if a batch contains an error.
A message explaining that Batch with errors needs correcting before file can be downloaded

**Comment by Captainkirkdawson** [comment]
CSV format story already exists #730

**Comment by Captainkirkdawson** [comment]
Fix applied to test3

**Comment by richpomfret** [comment]
@edickens to take a look/test.

**Comment by edickens** [comment]
The error report is in Blue not Red.  And I suggest that you add "so the file cannot be downloaded".
I corrected the error and then the download did work, although there is no message to say that it was complete.
Coding works.

**Comment by Captainkirkdawson** [comment]
Have changed message. Colour coding messages is a much larger issue. Separate story in system wide

**Comment by edickens** [comment]
My reason for commenting on the colour is that elsewhere we have blue/green as confirmation that all is OK, but Red if the action was not successful.  E
