### ISSUE TITLE
21 Contact teams - re Plan B for urgent communications As defined by #694

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#753]
Rootsweb, which is still used by FreeCEN and FreeBMD for some forums, has gone down and this has made me think about resilience in the communications system we are designing.  It needs to contain a way of getting emails out to 'all' and the top-level of opt-outable communications.

E2 U6 S8 C3: P21

**Comment by Captainkirkdawson** [comment]
What do you want done

**Comment by edickens** [comment]
We have this in FreeREG.  Is this for the other projects?

**Comment by Captainkirkdawson** [comment]
What is Plan B? Is there a story that needs work in FR and if so what?

**Comment by PatReynolds** [comment]
We could have a back-up of the emails and their qualifiers (e.g. active, deceased, bouncing, etc.) on Sendgrid.  But this may be superceded by the idea of a single Gateway, so on hold.

**Comment by PatReynolds** [comment]
Current issue suggests that back-up on Sendgrid isn't the (whole) solution, as a block on us as the sender causes widespread faillure.  I suggest we look at what others do for their Plan B.  For example,  https://twitter.com/ispstatusuk  Our users wouldn't need a twitter account, as we could route this onto our websites, and we could have another website on a free platform which was just to present the twitter feed from @freukgenStatus (or whatever it gets called).

**Comment by PatReynolds** [comment]
If we have a back-up spreadsheet somewhere of emails and qualifiers, we can use this to email out in an emergency.

**Comment by edickens** [comment]
Who will keep it up-to-date?
If really essential, then a file (spreadsheet format or for Outlook?) of names and email addresses needs to be sent every night to a separate computer.

**Comment by PatReynolds** [comment]
Regular back-up needed - @lemon-ukgen is this already done?

**Comment by lemon-ukgen** [comment]
A regular backup of *what*?

Of Sendgrid lists? No, we don't back those up. We could, although that protects us against Sendgrid itself failing, not against our (in)ability to send email to addresses that are on those lists. I expect we can dump out list membership via their API.

Using Twitter for out-of-band status updates is very common and is low friction.

Spreadsheet? What's a 'qualifier' in this context?

**Comment by Captainkirkdawson** [comment]
No idea what is expected of this story. Propose to close

**Comment by PatReynolds** [comment]
Link to operating/communicating "Plan B" put on Slack #general 19/12/2018

**Comment by Captainkirkdawson** [comment]
@PatReynolds I am sorry to say this needs a GREAT deal more work to be useful. It does not work as written. Moved back to backlog

**Comment by PatReynolds** [comment]
Slack is now functioning as PlanB, so closing.
