### ISSUE TITLE
A Duplicate Place name in Search table

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#754]
This morningI changed the Place Name of ESSEX / Laindon cum Basildon, to Laingdon. It had one church - St Nicholas and Holy Cross+ 3 batches with it. All changed correctly on screen. Later in the day, Julie Harrold uploaded 3 files for the church of St Nicholas - which correctly generated the Church name of St Nicholas + its new files.
There is no duplication of contents, but I just did a Search to check there was not -
SO search for ESS/ Laindon / Thomas Munt bap 1654..
BUT having set the Search County = ESS, the drop down box for Place, contains 2 x Laindon Place names. investigation shows one does not have any data behind it and my search crashes each time, the other does have data and search appears to work.
But where does the duff place name come in from?

**Comment by Captainkirkdawson** [comment]
There are two place locations for Laindon.
freereg2:PRIMARY> db.places.find({place_name: "Laindon"})
{ "_id" : ObjectId("53cd4998eca9ebee4f00b7e3"), "chapman_code" : "ESS", "country" : "England", "county" : "Essex", "data_present" : true, "disabled" : "false", "genuki_url" : "http://www.genuki.org.uk/cgi-bin/gazplace?GR=TQ670890,PLACE=LAINDON%20BASILDON,CCC=ESS", "grid_reference" : "TQ670890", "last_amended" : "19 Dec 2013", "latitude" : "51.57513", "location" : [ 0.408558, 51.57513 ], "longitude" : "0.408558", "master_place_lat" : "51.57513", "master_place_lon" : "0.408558", "modified_place_name" : "laindon", "original_chapman_code" : "ESS", "original_country" : null, "original_county" : "Essex", "original_grid_reference" : "TQ670890", "original_latitude" : "51.57513", "original_longitude" : "0.408558", "original_place_name" : "Laindon cum Basildon", "original_source" : "Genuki", "other_reason_for_change" : "", "place_name" : "Laindon", "reason_for_change" : "", "source" : "Genuki", "u_at" : ISODate("2016-03-06T16:28:02.930Z"), "alternate" : "", "place_notes" : "Laindon parish originally contained Basildon (Holy Cross) as a chapel.  Basildon has separate registers from 1777.", "alternateplacenames" : [ { "_id" : ObjectId("5652ed66f493fd9d080001d0"), "alternate_name" : "" } ] }
{ "_id" : ObjectId("53cbf5d8eca9eb03a6003511"), "chapman_code" : "ESS", "country" : "England", "county" : "Essex", "disabled" : "false", "genuki_url" : "http://www.genuki.org.uk/cgi-bin/gazplace?GR=TQ675889,PLACE=LAINDON,CCC=ESS", "grid_reference" : "TQ675889", "latitude" : "51.574084", "location" : [ 0.415719, 51.574084 ], "longitude" : "0.415719", "master_place_lat" : "51.57513", "master_place_lon" : "0.40855798", "modified_place_name" : "laindon", "original_chapman_code" : "ESS", "original_country" : "England", "original_county" : "Essex", "original_grid_reference" : "TQ6789", "original_latitude" : "51.57513", "original_longitude" : "0.40855798", "original_place_name" : "Laindon", "original_source" : "Gazetteer", "other_reason_for_change" : "", "place_name" : "Laindon", "reason_for_change" : "", "source" : "Gazetteer", "u_at" : ISODate("2016-03-06T09:40:42.561Z"), "alternate" : "", "data_present" : true, "place_notes" : "Laindon parish originally contained Basildon (Holy Cross) as a chapel\r\n", "alternateplacenames" : [ { "_id" : ObjectId("56dac61ef493fdd89e00053d"), "alternate_name" : "Laynden" } ], "last_amended" : "10 Oct 2010" }
Let me know which is supposed to be the correct one and I will merge them

**Comment by Sherlock21** [comment]
The first one of the two should be made the current one. It was just edited by me in very recent days.  as indicated in the opening statement.

**Comment by Captainkirkdawson** [comment]
What puzzles me is why there is a duplication; there are others in 738 and 745.  We cannot create a duplicate. But we will get a duplicate if there is a name change to a place if one with the same name already exists!

**Comment by Sherlock21** [comment]
Could you put in a Process Stop and  add an on screen message to say so, in this case, instead of making the change?

**Comment by Captainkirkdawson** [comment]
Check has been added.

Laindons have been merged
