### ISSUE TITLE
rebuild database for 1.4 features

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#756]
In order to pick up new emendations, witness search, wildcard support, and issues like #706 and #711 we need to create a database-rebuild script to re-generate search records.

The apply_emendations script is the only example of us doing this before.

**Comment by Captainkirkdawson** [comment]
Have added a search record digest so as to be able to detect changes on update and hence only save those records that change. Have added a software version field so that we know the version of code used to create the search record. There will be no need to try to change records processed with the same software version.
Have written a rake task that updates search records based on these concepts. Have run a volume test on test3 (650,000 records). Based on this timing it will take a minimum of 4,5 days to update the production severs.
Have asked Ben and Doug to review the code and results of that volume test.
Need to have all code that affects search_records deployed to master before running.

**Comment by benwbrum** [comment]
Excellent.  I'm reviewing this now.

Opinions on this (initial) test plan?

1. Update local master
2. Build a (small) database from scratch
3. Merge master into wildcard
4. Checkout wildcard
5. Run the update search record task


Before we merge wildcard into master, we need a new step:
4a. Test that new software searches against old records still work

We also need to hide the new wildcard features in the UI before merging
them.

**Comment by Captainkirkdawson** [comment]
Ben not sure of the benefit of building a new database on test3.  Could we not 1) update master on T3; 2) merge wldcard into master on t3; 3) Run the update search record task on t3. test the searches on t3. 4)Disable any search features we do not want to use until database ready 5) Deploy to master 6) run the update task on production 7)activate search capabilities

**Comment by benwbrum** [comment]
Yes, you're right.

Am running through plan on my dev box now.

Ben

**Comment by Captainkirkdawson** [comment]
Ran into an issue that Mongoid was not inserting the embedded documents into the search record but a different one!!!!!

**Comment by Captainkirkdawson** [comment]
Have finally beaten Mongoid into submission. As we have known for some years embedded documents have always been problematic with early versions of mongoid and mongodb. (One of the reason we really must devote time to a system version upgrade.)
While the documentation outlines a number of ways of  deleting embedded documents and adding new documents only one of those ways will work with an existing parent. Specifically on an existing parent one can only delete an embedded document with something of the form search_record.search_names.where(value).delete_all as all other forms delete the search record! To add a new embedded document to an existing parent search_record.search_names.new(value) all other forms such as create and push  put the document in the wrong search record.
The new code has been deployed as part of search record and is used both by our update search records rake task,  by the new processor and by the on-line update. This means that we no longer delete and recreate search records when a field changes but rather update the existing record. This should improve performance during updates. Although only time will tell.
Plan to move code to test3 and run volume tests.

**Comment by Captainkirkdawson** [comment]
Have started update of search records on production. Appears that 25% of burial records require updating.. Significant performance impact when running with a sleep of .04 sec. Now running with a sleep of .5 which means a much longer run time.

**Comment by Captainkirkdawson** [comment]
At this rate it will take 17 days to do the burials

**Comment by Captainkirkdawson** [comment]
BU rebuild on test3 is now complete. MA rebuild on test3 is under way.

**Comment by Captainkirkdawson** [comment]
Ma rebuild on test3 now complete. 45% of all records were updated. Ba has commenced

**Comment by Captainkirkdawson** [comment]
Profiling of the updates indicates that the search record is having to be moved on disk because we are increasing the document size through the addition of new search names in the embedded search name collection. This is causing a rewrite of all index entries for that record.

**Comment by benwbrum** [comment]
I can think of two reasons for this:

1) the name array has gotten longer due to inclusion of witnesses
2) the name array has gotten wider due to the gender flag

**Comment by Captainkirkdawson** [comment]
Have suspended the ba update on production at 50% complete as this is freebmd rebuild week. Will resume when their update finishes.

**Comment by Captainkirkdawson** [comment]
The test3 rebuild is complete. Have recommenced the rebuild on production as L is not using the maintenance week.

**Comment by Captainkirkdawson** [comment]
The burial search record rebuild  on the production servers is complete. The marriage update has commeneced

**Comment by Captainkirkdawson** [comment]
Marriage records are requiring a 50% recreate. This is causing more impact on system performance. Have slowed processing rate by increasing sleep to .5s from .4 s

**Comment by Captainkirkdawson** [comment]
Marriage rebuild has been paused for FreeBMD rebuild

**Comment by Captainkirkdawson** [comment]
Have restarted the marriage search record update

**Comment by Captainkirkdawson** [comment]
10% of searches are limiting on colobus with only 2% limiting on slaves

**Comment by Captainkirkdawson** [comment]
Paused again during FreeBMD build. 60% complete on Ma

**Comment by Captainkirkdawson** [comment]
Restarted emendation on ma again

**Comment by Captainkirkdawson** [comment]
Stopped ma emendations due to performance impacts

**Comment by Captainkirkdawson** [comment]
Integrated as part of #936
