### ISSUE TITLE
No forename entered in the register.  What should we do?

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#757]

**Comment by edickens** [comment]
The situation does arise where no firstname may be entered.   We need to TWYS.  So how does the search handle this?
And that raises the question of what happens when the first few characters of either the lastname or firstname are unreadable and so are UCF?  I suggest that blank names (Including the word Blank) and first letters UCF should come up when no names are entered, or we need a box on the search screen (advanced search?) to tick to ask for just unreadable entries.  We do have entries where the lastname is just a Star.

**Comment by Sherlock21** [comment]
Upon reflection I think " LEFT BLANK" is better grammar for key text fields.

And for Date fields, then that wont do.
The Transcriber can actually see that the record concerned is usually in a set of records in a data sequence on the page - as Kirk points out this is a key fact that the researcher never gets to see  - so a year date of the previous date in the Register sequence should usefully be used WITH A NOTE to explain " No Date recorded but Register Record is sequenced  with this record immediately following  one with the Year Date shown here"
this will do for all Baptism, Marriage or Burial key dates. Any other dates should be left blank as we do at present.

**Comment by Captainkirkdawson** [comment]
See also #745

**Comment by Captainkirkdawson** [comment]
Propose to close in favour of #745
