### ISSUE TITLE
Add field to show that a batch has been independently checked

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#758]

**Comment by edickens** [comment]
Especially the older registers need checking by a second transcriber.  This field will indicate, to both the SC and Researcher, that the batch has been checked and may not need doing again.  At present we sometimes fully transcribe twice so that we get duplicate entries and leave it to the researcher to decide which is correct.  But checking is better because now we get two entries that are exactly the same and so frustrating for the researcher to check and find no difference.

**Comment by Captainkirkdawson** [comment]
Implemented as part of the IS system
