### ISSUE TITLE
System for assigning Syndicates to transcribers

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#760]

**Comment by edickens** [comment]
I've made this a story because some program changes may be needed and also the Registration and SC Help pages be updated.
When someone registers and selects "Transcribe anywhere" then Jo gets them as she is also SC for Training.  But these people may not need training, and if they do, then they should have selected training.  So someone else should pick up anyone who registers for "Anywhere" and discuss with them where they would like to transcribe.  Having done that, the new registrant needs to be moved to that syndicate.  But who should do this?  The Volunteer-Coordinator?  Do they have the authority to change syndicate?  Do we have someone to do this, because the post is vacant.  I am not keen to take it on, even on a temporary basis.
The reason for a program change is that the Syndicate "Anywhere" may need to be handled differently as the person should not do anything until someone has contacted them and moved them to another syndicate.  E

**Comment by sean-wood** [comment]
dependant on 68
