### ISSUE TITLE
Allow messages to be sent to inactive users based on reason

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/MyopicVicar#761]
#739 added a pick-list of standardized reasons for a user being marked as inactive.
Eric would like to be able to message inactive users that are inactive for reasons to be picked from the standardized list.  For example, users who are temporarily taking a break, but not deceased.

**Comment by Captainkirkdawson** [comment]
Have been working on this and have it implementable. The issue that I see is that few inactive userids incorporate the standardized list

**Comment by Captainkirkdawson** [comment]
Also added active as default and the ability to set the sent from
