### ISSUE TITLE
I can't change a particular Place name to something similar as told: it already Exists.

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#762]
I have a Place name ( NFK / Wiggenhall St Germans) with the terminal "s" which i wish to change by removing the terminal "s".
There are others in this family like  NFK Wiggenhall St Mary; and Wiggenhall St Mary the Virgin; and Wiggenhall St Peter etc.  

There was also a Place name NFK / Wiggenhall that I deleted yesterday as that version was not needed.

Please fix ASAP.

**Comment by edickens** [comment]
Wiggenhall St Germans has an "s" on the end.  But Wiggenhall St Mary
    does not.  These are places near me that I used to go through until
    the bypass was built.
    
    On 29/03/2016 08:56, Sherlock21 wrote:
    
    
      I have a Place name ( NFK / Wiggenhall St Germans) with the
        terminal "s" which i wish to change by removing the terminal
        "s".
        There are others in this family like NFK Wiggenhall St Mary; and
        Wiggenhall St Mary the Virgin; and Wiggenhall St Peter etc. 
      There was also a Place name NFK / Wiggenhall that I deleted
        yesterday as that version was not needed.
      Please fix ASAP.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly or view
          it on GitHub

**Comment by Sherlock21** [comment]
Hi, Eric D

Thanks for that comment. - But it was Julie who asked me to correct the place name for her - so presuming she was right, I was just doing it!

May be I should check back with her, in view of your comment.

But the snag still needs fixing as we have found it out.

thanks,
eric B

**Comment by Sherlock21** [comment]
Phillimore has the place without the terminal "s" so that's where we need to be. And I suspect there is a bug in the job where there is a multiple word place name?

**Comment by Captainkirkdawson** [comment]
Name fixed

**Comment by Captainkirkdawson** [comment]
Unfortunately given the way I fixed it the search records have not been updated. Will require a specific script to fix
Reason for the issue in first place is that there is a disabled place of that name

**Comment by Captainkirkdawson** [comment]
Records corrected
