### ISSUE TITLE
New volunteer can easily identify counties with opportunities

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#764]
Prospective volunteers should be able to see
a) which counties have a 'volunteer drive' (most badly need volunteers to get them over the 'hump' of being less/more useful
b) which counties have images awaiting transcription
c) which counties do not have images, unless the transcriber pays for them
d) which counties do not at the moment have images

**Comment by edickens** [comment]
a) Is in the "Volunteer" screen bottom left.  But perhaps needs
    improving to show urgency.
    b) to d) Will be in the RAP report V1.5.
    
    E
    
    On 31/03/2016 16:21, PatReynolds wrote:
    
    
      Prospective volunteers should be able to see
        a) which counties have a 'volunteer drive' (most badly need
        volunteers to get them over the 'hump' of being less/more useful
        b) which counties have images awaiting transcription
        c) which counties do not have images, unless the transcriber
        pays for them
        d) which counties do not at the moment have images
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly or view
          it on GitHub

**Comment by Captainkirkdawson** [comment]
Implemented as part of IS system
