### ISSUE TITLE
Indexing with arrays

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#765]
Long running search; not the different formatting of the 2 dates

2016-04-03T15:31:24.494+0100 [conn1132131] query myopic_vicar_production_20150223.search_records query: { $query: { chapman_code: { $in: [ "NFK" ] }, search_dates: { $elemMatch: { $gt: "1933", $lt: "1971-01-01" } }, search_names: { $elemMatch: { type: "p", first_name: "ann", last_name: "reeve" } } }, $hint: "county_fn_ln_sd" } planSummary: IXSCAN { chapman_code: 1, search_names.first_name: 1, search_names.last_name: 1, search_date: 1 } ntoreturn:250 ntoskip:0 nscanned:1303 nscannedObjects:1303 keyUpdates:0 numYields:841 locks(micros) r:2138678 nreturned:2 reslen:2313 29873ms

**Comment by Captainkirkdawson** [comment]
I believe there to be an issue with the use of gte or lte in string searches that bypasses the indexes

**Comment by benwbrum** [comment]
Maybe, but search_date is the fourth term in the index it's using, so I'd
be surprised if that matters.  Wonder what happens if we run the query
without a date?

**Comment by Captainkirkdawson** [comment]
I think that the access to search performance shows this issue much better. There there is only one index. Mind you it is a date that is being used

**Comment by Captainkirkdawson** [comment]
Research shows that bounded searches are problematic

**Comment by Captainkirkdawson** [comment]
Changed the search queries bounded search into an equal on a day where day is a new field computed from c_at. Performance is orders of magnitude better

**Comment by Captainkirkdawson** [comment]
Why do we use a full date field i the search record when the search query bound is only a year. This provides a fine granularity on search date that is not used. Does this cause a performance issue?

**Comment by Captainkirkdawson** [comment]
Have located 2 issues. 1) It appears we may be violating an index limitation by trying to index 2 arrays which is not permitted 2) we do not have an index on chapman_fn_sd which means forename only searches with a date limitation will run slowly

**Comment by Captainkirkdawson** [comment]
WRT point 2. Have implemented a requirement that forename searches are for a place(s)

**Comment by Captainkirkdawson** [comment]
Very interesting since implementing a place requirement on a forename only search the  overall system response  has improved dramatically.

**Comment by Captainkirkdawson** [comment]
This issue is only caused by having 2 date entries for baptisms; births and baptisms.
If we only used baptism dates then we would not need an array for search dates

**Comment by benwbrum** [comment]
I've transformed the underlying code substantially, but would like a code review before we merge and deploy: https://github.com/FreeUKGen/MyopicVicar/pull/939

**Comment by Captainkirkdawson** [comment]
Have reviewed this excellent code. Mode the following comments.

I believe the proposed code will achieve our objective.
However it is not totally clear to me how we would actually implement the code operationally.
This code will create the new search_date field for new and updated records. It will allow the update search records rake task to update the database to add the new field.
If activated the search will now use the search_date field and as a second step use the secondary_search_date field (This implies that there will only be one additional date). But it will currently only perform a non indexed search. Hence the search code must not ever be activated until 1) all search records are updated and 2) new indexes created. Those indexes are not yet defined in this code.
Do we create the new indexes while creating the records or after they are all created?
Since this likely will require the update of 35 million search records the time required in the current system will be extremely long.  

I propose to pull into my development server and run some tests. Based on that I would do the same on test3.
However given the performance issues associated with the implementation of this code I would first like to evaluate the wired tiger storage  engine on test3 first see #942

**Comment by Captainkirkdawson** [comment]
Ben made the following comment off line on implementation.

1) Run a rebuild to copy the contents of search_dates[] into search_date and (where necessary) secondary_search_date (during this time the current search algorithm will continue to run.)

2) Build new indexes using search_date 

3) Switch to the new search algorithm, which queries against search_date and secondary_search_date, leaving the old search_dates[] field in place (will require a new code deploy)

4) Drop indexes on search_dates[] (will require a new code deploy)

5) Prune search_dates (will require a new code deploy) off of existing records

**Comment by benwbrum** [comment]
I completely agree that wired tiger might be advisable to deploy before
this or any other rebuilds.

Kirk, I'd like to chat with you about how this works with
search_record_version, as well -- the strange thing about this was the
inapplicability of the record digest.

Let me add some additional search indexes in a format that allows them to
be operationlized.  (Once I figure out how to do that) before we declare
this story 'done'.
