### ISSUE TITLE
Provide email link to relevant CC and SC for Manager Profile people, from the top of the All Places and Active Places screen

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#766]
At present, to email a CC, one has to leave the page one is on - say Active Places for a County, navigate over to Manage Syndicates and pick the right one, then find the name of the relevant SC. Then go to: list members of that SC, and find the person. then copy off their email address.
then navigate to the place one was working in County and Place name, to get to be able to see in FR,  what to write the email about on ones email window.

I am not asking you to build email capability into FR Places, but at the top of the Page, a link to the County CC or SC email address,  which fires up an email page as a separate window ( from the users' email app on their computer).

**Comment by edickens** [comment]
This link to the CCs email address only to be available to register transcriber and above.  Not registered researchers.  Also, only to show to these people in "Transcriptions".

**Comment by Sherlock21** [comment]
I agree with Eric D about access also to some Transcribers only. - but surely not all transcribers get to all SC & CC email addresses - how about only those they are working for? either by being in that SC / CC group, or have files / batches in the person's County?

**Comment by edickens** [comment]
I do get quite a few requests from transcribers to work for another
    syndicate/county.  So if they are people registered with us, then I
    think they should be able to email anyone.  E
    
    On 08/04/2016 10:46, Sherlock21 wrote:
    
    
      I agree with Eric D about access also to some Transcribers
        only. - but surely not all transcribers get to all SC & CC
        email addresses - how about only those they are working for?
        either by being in that SC / CC group, or have files / batches
        in the person's County?
      —
        You are receiving this because you commented.
        Reply to this email directly or view
          it on GitHub

**Comment by Captainkirkdawson** [comment]
Of limited benefit to a few people

**Comment by Sherlock21** [comment]
It may well be so. But non the less its the difference between me doing an email to the CC and sorting n issue, or not bothering and leaving it.l

**Comment by edickens** [comment]
But if not, it means that everyone has to keep their own record of
    who is currently CC or SC.  I have today just looked up WES to be
    sure.  I have extra Actions to see the list of all CCs and SCs which
    makes it easy for me, but it is not the same for other
    coordinators.  E
    
    On 13/04/2016 05:40, Kirk Dawson wrote:
    
    
      Of limited benefit to a few people
      —
        You are receiving this because you commented.
        Reply to this email directly or view
          it on GitHub
