### ISSUE TITLE
Migration of images from AWS to Hertsner servers

### ISSUE THREAD

**Issue by sean-wood** [FreeUKGen/MyopicVicar#767]
currently FreeReg images are stored on Amazon servers and not the existing servers we use for other projects.
This ticket is for the investigation and implementation of decommissioning the Amazon servers

**Comment by edickens** [comment]
Will this make a difference to getscan.pl and BitKinex links? 
    Important because FreeREG has lots of transcribers accessing images
    and I have to do quite a few allocations every day.  E
    
    On 08/04/2016 15:41, sean-wood wrote:
    
    
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly or view
          it on GitHub

**Comment by sean-wood** [comment]
Hi Eric

I have forwarded your question to Ben B who will be investigating and doing the work

Sean

**Comment by benwbrum** [comment]
I'm only just now able to log into the image servers, so I'll be exploring this shortly.

**Comment by benwbrum** [comment]
I've been pulling the almost 400K FreeCEN entries onto the image servers.  At the moment we're nearly done with the first hundred thousand.
