### ISSUE TITLE
Update GiftAid text

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#769]
Update to match Free UK gen

**Comment by Captainkirkdawson** [comment]
Could we have a little more specificity  please

**Comment by Captainkirkdawson** [comment]
I do not know where GiftAid text is located on FR

**Comment by edickens** [comment]
Pat.  Why assigned to me?  Unless this is FR1, I cannot do it.  Eric
    
      On 21/10/2016 15:19, PatReynolds wrote:
    
    
      Assigned #769
        to @edickens.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Assigned #769 to @edickens."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/769#event-832094211"}}}

**Comment by PatReynolds** [comment]
No longer needed since donations now all on free uk gen website, so closing
