### ISSUE TITLE
Reject Invalid Register Type on upload

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#771]
During the rewrite of the upload process check that a Register Type has been entered in the batch.

**Comment by edickens** [comment]
I'm not suggesting that the upload has to match  what is on the server, just that a Register Type has been entered, even if it is OR or even UK (Unknown).   If no code is entered we get "Unspecified" created which later on has to be corrected and removed.  E

**Comment by Captainkirkdawson** [comment]
Are we really ready to make a register type mandatory and why does it benefit the technician?

**Comment by edickens** [comment]
There is no reason now not to enter it.  We have UK for Unknown. 
    The list of codes is in the Help pages.  If it is not entered, then
    "Unspecified" is created and someone has to sort it out later with
    all the associated moving of batches.  There are many Churches with
    the entries split over more than one Register Type.  I'm not saying
    that it has to be set up in advance like the Church, just that one
    has to be entered.  E
    
    On 30/04/2016 01:21, Kirk Dawson wrote:
    
    
      Are we really ready to make a register type mandatory and why
        does it benefit the technician?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by Sherlock21** [comment]
the Register type give a degree of confidence to the researcher - as they get told: our record comes straight from an Original Register at one end of the scale, to a copy off something that has been round the houses and re types out - with the chance of more typo errors being introduced.
Having been given this information, the user can take it or leave it. If we don't tell them then they surely have less confidence in our data source.

**Comment by Captainkirkdawson** [comment]
I agree with what you say EricB but the question was "Are we ready to make the field a mandatory field with rejection if absent".

We do validate. We currently set Unspecified if invalid.

**Comment by edickens** [comment]
I would say yes we should make it mandatory, but not just yet!  Let
    the Church validation settle.  E
    
    On 30/04/2016 15:59, Kirk Dawson wrote:
    
    
      I agree with what you say EricB but the question was "Are we
        ready to make the field a mandatory field with rejection if
        absent".
      We do validate. We currently set Unspecified if invalid. 
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by Captainkirkdawson** [comment]
In that case it is deferred to 1.5

**Comment by Sherlock21** [comment]
I will go along with the Majority.

given the difficulty I have seen that some people have getting the church names right, it might be some while!!

eb

**Comment by edickens** [comment]
What information is needed?  If the Register Type is not one of the standard codes reject the Entry.  If none are entered then I suggest still use "Unspecified".  But if they have tried to enter one and got it wrong, it is best rejected.

**Comment by Captainkirkdawson** [comment]
But that is the current practice It has to be a valid register type if not it is rejected, If blank then is Unspecified.

**Comment by edickens** [comment]
When I started this story I suggested that something needs to be entered, not just left blank.  There is no excuse to leave it blank.  That just creates work in the future.  But I will leave it to the SC to make sure that the transcriber enters a register type.
This can be closed.  Very old story.
