### ISSUE TITLE
FR1 being returned when www.freereg.org.uk entered

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#773]
While trying to do some work on FR on a new-to-me computer, typing www.freereg.org.uk into the address bar took me to FR1. So did the link from www.freeukgen.org.uk.  The only way in is to go the FR1 and follow the link.  Computer is old, XP, out of date ie. We don't support out of date, but I am wondering how prevalent this is, and whether it means we need to make some changes to the FR1 homepage to reflect the fact that people may arrive unexpectedly.

**Comment by Captainkirkdawson** [comment]
I am unable to duplicate this report. www.freereg.org.uk goes to the new version for me. So does the link from freeukgen

**Comment by PatReynolds** [comment]
I am going to have access to the computer in question at the weekend and will screenshot / document what happens.
