### ISSUE TITLE
IT is Possible for 2 files to co-exist, by same userID and with same file name.

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#774]

**Comment by Sherlock21** [comment]
refer please to DEVON / Countisbury and files by JHarold  both named DEVCOUMA.
-email with screen print sent to Kirk.

Content differs between them. And its not a case of one should have replaced the other as year ranges are complementary.

**Comment by Sherlock21** [comment]
I fully agree that we should not have files that had multiple Place names or church names in them because that only gives rise to multiple batches in FR.
The best relationship between file and Batch is 1:1.

But that’s not where we are. because things came across from F1 in the manner that multiple batches were created.

I have tried an experiment / test in T3 to see what happens.

use WRY / AAATestplace and AAATestplace 2 and AAATestplace3. with church names St Paul, St Paul2 and St Paul3.
[ i did them like this so they all come together in a listing for east of seeing - but in historical use, they would have been different places scattered about -SO NOT OBVIOUS to spot.

having used a little file of 16 records, I put some against each Place name & Church name. it works fine, was expected.

then playing the part of another person coming along time later, like a CC might, to clean up come  church name or Reg type, and choosing  to download the batch for one of these ( was one views it in the Application,) one does not know whether the batch you see containing 3 or 4 records, is the total of the FILE or what.

so assume its the All for this file name, and edit the downloaded batch to set the data right. and RELOAD. from the option in the Batches application.

the new Reload works OK. BUT it deleted all the individual rows of data that were in the original file, but which are scattered about the database. And we do that unknowingly - so valuable records will get deleted in this situation.

NOW. you might argue i should  investigate all possibilities of this happening  but  its a bit too vague a thing surely.

 
SO for starters : How many FILES are current in FR, that have given rise to more than a 1:1 batch? this will give a measure of what we (I) are worrying about.

What do we do about it? Not all CC’s will be as savvy as Me I am sure, so I raise the question: Do we have an issue?  Do we need to worry? Do we need a slightly different safeguard against inadvertently deleting data?

**Comment by Captainkirkdawson** [comment]
Let me be absolutely clear. It is NOT possible for there to be more than one file of the same full name (name plus extensions) in a userid. It just cannot happen. The operating system will not permit it to happen let alone our code. So I intend to close this issue and raise the issue of multiple batches in a single file which is what is a legitimate topic for discussion.

**Comment by Sherlock21** [comment]
I AGREE TO CLOSE THIS NOW. - Resolved
