### ISSUE TITLE
Contacts Coordinator Actions

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#775]

**Comment by edickens** [comment]
Please add the following to the Actions for the Role of Contacts_Coordinator.

All UserID actions, except no need to Edit UserID, but to be able to access and Edit batches.

Manage Counties so as to look up place and church details.

County Coordinators so as to be able to find out who is the current CC.

Syndicate Coordinators so as to find out who is the current SC and if they are recruiting.

No edit facilities, other then batch entries, are needed, although if it is difficult to exclude this it doesn't matter as Sandra knows what she is doing.

**Comment by edickens** [comment]
Please add the Contacts_Coordinator to all Contact messages as a CC: but not the first one.  Sandra can then see what is going on, but also deal with messages addressed to me while I am away.  ED

**Comment by Captainkirkdawson** [comment]
Sorry Eric I do not understand
"All UserID actions, except no need to Edit UserID, but to be able to access and Edit batches."  
There is no edit batches action in userid management.

I propose we give the CC Access to Userid Profiles which is what DM and other coordinators have. (No creation or editing)

Similarly will provide an access to coordinator information

**Comment by edickens** [comment]
That will be fine.  It is difficult for me to know what Actions
    others have because I get everything.  E
    
    On 28/04/2016 21:41, Kirk Dawson wrote:
    
    
      Sorry Eric I do not understand
        "All UserID actions, except no need to Edit UserID, but to be
        able to access and Edit batches."
        
        There is no edit batches action in userid management.
      I propose we give the CC Access to Userid Profiles which is
        what DM and other coordinators have. (No creation or editing)
      Similarly will provide an access to coordinator information
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by Captainkirkdawson** [comment]
Done. Will deploy tonight
