### ISSUE TITLE
Access to Help Pages

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#776]

**Comment by edickens** [comment]
I needed to look up some information (capital letters) in the Help pages, but if I have logged in as System  Administrator, I do not have access to Transcriber help pages.  I do have another UserID set up as a Transcriber so could access it that way.
But I suggest that all higher level roles should have access to all lower level Help pages.  A higher level person can still be a transcriber.
E

**Comment by AlOneill** [comment]
This is the current (and for a few months ) situation: 
* there is a link to *Information for Transcribers* at the top of the *Information for Coordinators* page 
* as I understand things, the *Help* button on the main menu will take all logged-in Coords-and-above to *Information for Coordinators*

What needs to change?

**Comment by edickens** [comment]
Hi Alison,
    
    When I am logged in, no matter which route I use I always get just..
    
    
    
    Regards,
    
    Eric
    
    
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 26/04/2016 21:45, AlOneill wrote:
    
    
      This is the current (and for a few months ) situation: 
      
        there is a link to Information for Transcribers at
          the top of the Information for Coordinators page 
        as I understand things, the Help button on the
          main menu will take all logged-in Coords-and-above to Information
            for Coordinators
        
      
      What needs to change?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by Sherlock21** [comment]
When I log in as DM and before I pick under ACTIONS in a column on the RH side, I have, in the very top Actions green bar, one called HELP.

this goes to Actions for Coordinators.
in the first line of text under the header, is a link to Actions for Transcribers - together these seem OK for me.

eric B

**Comment by edickens** [comment]
Thanks EricB.
    
    I didn't think of looking at Coordinators Actions for Transcribers. 
    I also find that the colour "Teal" does not stand out well in the
    text for me so I missed it.
    
    Regards,
    
    EricD
    
    On 29/04/2016 10:22, Sherlock21 wrote:
    
    
      When I log in as DM and before I pick under ACTIONS in a column
        on the RH side, I have, in the very top Actions green bar, one
        called HELP.
      this goes to Actions for Coordinators.
        in the first line of text under the header, is a link to Actions
        for Transcribers - together these seem OK for me.
      eric B
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by Sherlock21** [comment]
Well, I know where you are coming from…

I just went for a nosey hunt about, after reading what you said about “ not being catered for"

So i clicked all the links I could find, to see where they went!  And next time I really need something, I will of course have forgotten where they re..

Should perhaps be all in a list together - so one can see ALL of what one has - either all the lot, or only the solitary Users list.
And as the Profiles are hierarchical, some will add onto the top, as one moves up the tree as it were.
 
E B

**Comment by Captainkirkdawson** [comment]
Access is there
