### ISSUE TITLE
Multiple Batches in a Single File

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#777]
EricB has legitimately raised the issue of multiple batches in a single file the the confusion that this can cause.

EricB stated
I fully agree that we should not have files that had multiple Place names or church names in them because that only gives rise to multiple batches in FR.
The best relationship between file and Batch is 1:1.

But that’s not where we are. because things came across from F1 in the manner that multiple batches were created.

I have tried an experiment / test in T3 to see what happens.

use WRY / AAATestplace and AAATestplace 2 and AAATestplace3. with church names St Paul, St Paul2 and St Paul3.
[ i did them like this so they all come together in a listing for east of seeing - but in historical use, they would have been different places scattered about -SO NOT OBVIOUS to spot.

having used a little file of 16 records, I put some against each Place name & Church name. it works fine, was expected.

then playing the part of another person coming along time later, like a CC might, to clean up come church name or Reg type, and choosing to download the batch for one of these ( was one views it in the Application,) one does not know whether the batch you see containing 3 or 4 records, is the total of the FILE or what.

so assume its the All for this file name, and edit the downloaded batch to set the data right. and RELOAD. from the option in the Batches application.

the new Reload works OK. BUT it deleted all the individual rows of data that were in the original file, but which are scattered about the database. And we do that unknowingly - so valuable records will get deleted in this situation.

NOW. you might argue i should investigate all possibilities of this happening but its a bit too vague a thing surely.

SO for starters : How many FILES are current in FR, that have given rise to more than a 1:1 batch? this will give a measure of what we (I) are worrying about.

What do we do about it? Not all CC’s will be as savvy as Me I am sure, so I raise the question: Do we have an issue? Do we need to worry? Do we need a slightly different safeguard against inadvertently deleting data?_

**Comment by edickens** [comment]
I think that the first step is to identify when this problem occurs,
    and when it is valid and not just a typing error.
    
    This is a Place in ELN...
    
    
    
    I have not checked, but I suspect that the official moves around all
    these "Churches", and has a single register book.  Even if this is
    not the case here, the principle applies.  However, don't get it out
    of proportion.  The number of times different "Churches" are in one
    Register book is very small.  In some cases (and I cannot find it
    now) the official did Baptisms in homes, so the "Church" changed for
    almost every entry.  But this should be "Abode" and the "Church"
    would be a "Circuit".  The problem comes with trying to put a map
    reference when the events take place over wide area.
    
    So the question now is how do we process these?  I would like to see
    the "Church" field the same throughout the file and so create just
    one batch.  So should the "Church" be something like "Innerwick
    Circuit" and the location of the entry be in another field, or even
    the note?.  Or does the transcriber have to create loads of
    different batches?  WinReg does not allow different Churches in one
    Place, so we do need a ruling on this.
    
    And this does remind me that we should show the Denomination on the
    list of Places/Churches.  In the above example, the denomination is
    shown in the Church dedication, which is not correct.  E

**Comment by Captainkirkdawson** [comment]
EricB

You are correct to be concerned about multiple batches in a file. There are hundreds in Scotland as that was how the original Scottish coordinator insisted on setting up church names. There are relatively few in England and Wales. They usually appear as a typing mistake when using a non winreg entry process (Winreg will not permit it to happen because of the way it it set up).

However let me be clear a download of a batch WILL include all of the batches for a file if there are multiple batches. This decision was taken to avoid the issues you identify.

The help materials for Coordinators contains a significant amount of information on how to manage the situation including correction of and merging batches.

I cannot comment in detail about the situation with DEVCOUMA.CSV in  DEVON / Countisbury by JHarold as changes have been made. 

The original file contained 2 batches. One for a church named Countisbury St John with 46 records and a second named  Countisbury Cum Lynmouth with 84 records. That is how the original church names were created. 

It would appear that both church names have been changed to St John. I do not know if that is correct. If so they should now be merged into one batch

**Comment by Sherlock21** [comment]
the names Kirk shows above are the Parish name [ Countisbury cum Lynmouth] and a corruption of it [ Countisbury St John] in the latter case the place name + the Church name. - often it was written in F1 in this manner, and comes across into Fr as the Church name - but here in FR, we have the Place name in its own field as well, so the result reads stupidly.
These files were for the church of St John, which is in Countisbury. - hence my renaming and merging task.
