### ISSUE TITLE
Inactive transcribers

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#780]

**Comment by edickens** [comment]
I am getting a steady stream of messages such as this..

Eric,
I stopped doing any freereg some years ago, so don't need to know any of this!  You must be using an old address list.
Michèle Gross

But why are they telling me know when there have been a number of messages and so they would have told us before?  Suggestions as to how to deal with this?

And should freereg-contacts@freereg.org.uk now go to Contacts_coordinator?

E

**Comment by PatReynolds** [comment]
Is Michele incorrectly marked as active?  Or is this an objection to being consulted about Open Data - what 'messages such as this' is she talking about?

**Comment by edickens** [comment]
This was six months ago.  Transcribers are now marked as "Inactive" if necessary.
Suggest that it is Closed.
The"Messages such as this" is in my comment from "Eric" to Gross".
