### ISSUE TITLE
File upload rejecting Church

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#784]

**Comment by edickens** [comment]
Newcastle upon Tyne BT rejections on Tuesday 3rd.

I have a copy of the file from the transcriber and Chris entered:-

NBL,Newcastle Upon Tyne,St Andrew Bt,,

This has two problems.  It should be "Newcastle upon Tyne" and "BT".

I have asked him to change both of these in just this one file NBLNWABU1.CSV and upload it again.

My  guess is that the Place after Kirk's capitalisation routine is matching the Place on the server, because the report shows NBL, Newcastle upon Tyne, St Andrew, BT, bu but is then not accepting the file because the Church as entered in the file does not match.

**Comment by Sherlock21** [comment]
Surely this is not a BUG.

its a matter of the Transcriber not getting the spelling right isn't it - rather than fudging the soft are to convert a wrong file?

**Comment by edickens** [comment]
Chris has amended this file and it is in the waiting to be processed queue.  This should be accepted now, unless it is a different problem.  E

**Comment by edickens** [comment]
After changing "Upon" to "upon" and "Bt" to "BT", the file has been accepted.  E
