### ISSUE TITLE
No Screen Message when FR is down

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#785]
When FR was down this past weekend, I did not receive any system message saying so when I tried to log on. Got the Cookies tick box OK, then the Logon Ui/d and pw. - just to be told by a system message: You have got your ID + Password wrong!

**Comment by Captainkirkdawson** [comment]
FR was never down last week, It was shut to member login for maintenance purposes. A message to that effect was provided on attempted login.
However due  to a bug, now since fixed, the message was only seen the first time a login was attempted and all subsequent attempts got a different message
