### ISSUE TITLE
Processed date rather than Uploaded date

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#791]
Priority 13 (0	3	2	8)
Our initial implementation provides coordinators with lists by uploaded date. We can and do process files without an upload. Should the list be by processed date rather than uploaded?

**Comment by Sherlock21** [comment]
Yes, i think with hindsight, that would be a better reference.

**Comment by richpomfret** [comment]
Has this been completed/deployed?

**Comment by SteveBiggs** [comment]
Yes deployed, although there is a typo in processed:

![image](https://user-images.githubusercontent.com/25303607/45450288-a9ea7300-b6cf-11e8-910d-367ca5538b58.png)
