### ISSUE TITLE
Spelling error in record details display

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#794]

**Comment by edickens** [comment]
![capture](https://cloud.githubusercontent.com/assets/8876165/15071262/21cad020-1382-11e6-8f57-d83fa54d7045.JPG)
The Grooms Father in the display of an MA record is incorrect.  See attached.

From Ali.

**Comment by Captainkirkdawson** [comment]
Only one question . Why is this assigned a milestone of 1.3. We are currently working on 1.4. Is it urgent enough to assign to 1.4 meaning that it must be done before we get on with 1.5?

**Comment by edickens** [comment]
I don't really understand the naming system.  I would have also had
    something like "When convenient", "Operational".  The latter meaning
    that it is something that needs assessing now, but is not part of
    the development process.  To me version numbers are jobs that need
    doing as part of the future development.  V1.3 and V1.4 are now
    history as they are operational.  I cannot also remember if
    something was done in V1.3 or V1.4 to know which to assign.
    
    This one could be V2!
    
    E
    
    On 06/05/2016 14:56, Kirk Dawson wrote:
    
    
      Only one question . Why is this assigned a milestone of 1.3. We
        are currently working on 1.4. Is it urgent enough to assign to
        1.4 meaning that it must be done before we get on with 1.5?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by Captainkirkdawson** [comment]
Fixed
