### ISSUE TITLE
Auto-conversion of Church Names during Data File Upload

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#795]
There was an issue very recently from a WORCESTERSHIRE file uploaded for Upton upon Severn.

The church name was in the database as SS Peter & Paul. The file was rejected even though the church name in the file exactly matched the church name in the database.

You objected to the use of SS, and also " &".

I agree with you that SS should not have been used, and  should have been written as: St Peter & St Paul.

But I disagree with your automatic conversion of " & “ into “ and “. This is not correct. The Church of England Find a church site shows this to be the right name as in the screen print here. ( attached to the email to Kirk &Eric D)

I have experimented with a test file of my own, and confirm that there is conversion going on in the upload process, which undermines the TWYS rule, and causes unnecessary confusion amongst the Transcriber, the CC, and Me.

With more control now applied to the creation of Church Names, that should be the arbiter now.

Please therefore remove the code which does this “ & “ conversion.

Are there any other auto - conversions in church name please?

Eric Booker - Data Manager

**Comment by edickens** [comment]
I agree with EricB that the time has come to remove all conversion 
routines and just do a lower-case match.

We have now got everyone to understand the need for an exact match and 
last night there was not one miss-match.

There has been a problem where an extra space had been entered in the 
Church dedication, and this - quite rightly - caused a rejection.  So 
the conversion routine is correcting some problems and not others, which 
can cause more confusion than help.  An all or nothing approach will 
ensure accuracy.

The conversion routine has been very useful until now, but I think the 
time has come to stop using it.

E

**Comment by Sherlock21** [comment]
Exactly As Eric D says: "Conversion" was a helpful step along the way. But now everyone is getting used to doing things pedantically correct to match the Master.

**Comment by Captainkirkdawson** [comment]
I am sorry but it was EricD who requested the "conversion" used previously in church name processing because we were rejecting far too many church names

**Comment by edickens** [comment]
True.  But I did not have enough information to show that there was
    a lot of conversion needed to match the Server's Church name.  I now
    think that this conversion is not needed, just a lower-case match.
    
    We have insisted on an exact match, and by being firm transcribers
    have now got the message.  It is not difficult for them to do.
    
    The original reason was also because a transcription was creating a
    Church name if there was no match.  This is no longer the case.
    
    E
    
    On 08/05/2016 16:18, Kirk Dawson wrote:
    
    
      I am sorry but it was EricD who requested the "conversion" used
        previously in church name processing because we were rejecting
        far too many church names
      —
        You are receiving this because you commented.
        Reply to this email directly or view
          it on GitHub

**Comment by edickens** [comment]
There are now more occasions where auto conversion is creating duplicate Churches.
In the overnuoight file load of 16 May this file was uploaded...
******************************************************************* <br>
Started on the file NTTWORBU1.CSV for KarenTurner at 2016-05-16 01:54:23 +0100. <p>
Code set 
Checking for undefined with 
There are 1 locations and 15511 existing records corresponding to the new file. <p>
Updating the current batch for NTT, Worksop, Our Lady And St Cuthbert (Priory), Parish Register. <br>
15511 records were processed of which 16 were updated/added and 0 had data errors. <p>
There were 13 entries in the original file that did not exist in the new one and hence were deleted. <br>
Created  15511 entries at an average time of 4ms per record at 2016-05-16 01:55:35 +0100. <br>
******************************************************************* <br>
The flies matched but there are now two Church names, see attached.
![capture](https://cloud.githubusercontent.com/assets/8876165/15282351/a27aa5f0-1b3a-11e6-9b1b-091af09279b8.JPG)
The overnight file upload should never create a Church and the auto conversion should be turned off.  This is just creating more correction work.  E

**Comment by edickens** [comment]
More on  this one.
On 15th this was processed...
******************************************************************* <br>
Started on the file ESSTOLBU.CSV for pjd at 2016-05-15 01:37:05 +0100. <p>
Code set 
Checking for undefined with 
There are 0 locations and 125 existing records corresponding to the new file. <p>
Removing batch ESS, Tolleshunt D'Arcy, St Nicholas, PR, bu for pjd ESSTOLBU.CSV. <br>
There were 125 entries in the original file that did not exist in the new one and hence were deleted. <br>
Created  0 entries at an average time of ms per record at 2016-05-15 01:37:30 +0100. <br>
******************************************************************* <br>
The place did not match, although the message here and to the transcriber does not say so.  The place name shown here is correct and matches the server.  So why was it rejected.  The transcriber says:-
I have checked the place-name and I had omitted to capitalise the A in Tolleshunt D'Arcy. I have now amended the file and uploaded it with no errors.
But a lowercase match should have accepted the file and used the server version.  Unless the capitalisation is doing something?  E

**Comment by Captainkirkdawson** [comment]
Is this issue still relevant and required. System seems to be working satisfactorily

**Comment by edickens** [comment]
Hi Kirk,
    
    Probably not needed, but it helps if an old file is edited and
    uploaded and it had something that was auto-corrected in the past. 
    If you remove the correcting, then it will get rejected and have to
    have every record amended.
    
    E
    
      On 07/10/2016 18:06, Kirk Dawson wrote:
    
    
      Is this issue still relevant and required. System seems to be
        working satisfactorily
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #795: Is this issue still relevant and required. System seems to be working satisfactorily"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/795#issuecomment-252307219"}}}

**Comment by Sherlock21** [comment]
I would say this is now redundant.
Except for one or two people who get it wrong, the message has got home OK.

As it was one of my original stories,  I say: Kill this one, and
Work on something that's more essential.
