### ISSUE TITLE
Allow CCs to amend Church names

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#796]

**Comment by edickens** [comment]
Now that we have tight validation of Church names, Ali (WRY) has requested that County Coordinators have the Action to Edit a Church name. 
There are many spelling errors that have cropped up over the years and this method of correction is easier than downloading, creating a new Church, uploading and deleting.
I appreciate that the reason we did not give them this Action is because it can take a lot of processing, so needs to be used carefully.  But perhaps a warning when the CC does this might be beneficial.  E

**Comment by Captainkirkdawson** [comment]
Action is currently restricted to data managers and system administrators with no restriction on numbers of records.
Action is restricted as changing the church name in ten or hundreds of thousands of records will bring the servers to their knees.
Limits would have to be imposed similar to those placed on register changes prior to implementation

**Comment by Sherlock21** [comment]
I agreed that not everyone will be best fitted to get this option.

So, Can it be subjective and with a limit to number of records? - BUT NOT  a blanket reduction for MGR & DM.
Is there no facility to add little bundles of privileges to ones profile or has it to be all or nothing, and only with thin the groupings of Transcriber/ Researcher/ SC / CC / DM/ MGR/ etc

**Comment by edickens** [comment]
I could make Ali DM just while she tidies up her Church names.  E
    
    On 08/05/2016 17:39, Sherlock21 wrote:
    
    
      I agreed that not everyone will be best fitted to get this
        option.
      So, Can it be subjective and with a limit to number of records?
        - BUT NOT a blanket reduction for MGR & DM.
        Is there no facility to add little bundles of privileges to ones
        profile or has it to be all or nothing, and only with thin the
        groupings of Transcriber/ Researcher/ SC / CC / DM/ MGR/ etc
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by Sherlock21** [comment]
That would be better than having no solution to offer wouldn't it.

And in T3 she has had some testing involvement with DM thing for me from time to time.
If you set the limits of course I don’t see a potential risk, do you?

Eric

**Comment by Captainkirkdawson** [comment]
It is by responsibility not by people. It will take a complete redesign and
rewrite of the userid role to allow selectivity.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Any performance issues resulting would be your responsibility. There is
currently no limit on the number of records that could be changed.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
Hi,Eric D

thanks for discussing this topic - but as i see its harder than /i would have suspected - so I withdraw the request for Ali.

I can cope.

EB

**Comment by edickens** [comment]
Have heard from Ali, who understands the problems of the system, so this 
topic can be closed.  ED
