### ISSUE TITLE
Overnight file upload processing follow-up procedure

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#797]

**Comment by edickens** [comment]
The File Upload Processing of 8 May has prompted me to ask if we need to define the procedure that should be taken for those files with Errors, i in particular the files which are rejected.  There were some genuine rejections that I had not seen before and I need to be  sure that the transcriber has been informed of the problem.
I have been emailing their Coordinator to inform them, but this is not something that I, or anyone else, should need to do in the long term.  There will be times when I am not available to do this.
I don't know if the File Upload Processing can send an email to the Transcriber and Coordinator should the file be totally rejected.  The Transcriber could check the next day to confirm, or may realise that they do did not get a confirmation email for a successful upload, but this is not foolproof.  There are some rejections which are serious and need sorting out, so I think something more positive needs to be done.
Thoughts?  E

**Comment by Sherlock21** [comment]
Yes, up to now I have been reading it, and just doing the actions that would naturally come my way - then telling the CC.

But this is hardly a system I agree.
I would like stay on the list for what we presently receive but i agree there could be scope for a bit of automation.

**Comment by Captainkirkdawson** [comment]
What automation do you suggest?.

Each transcriber and their coordinator already receive an email with a report on the results of each file that has processed either as ASAP or in the overnight update.

That report contains all of the information that you see for the file (except a few messages about character set etc which are there for my use).  So they already should know to take action and also what that action so be. To be clear they get a message even if all records are rejected such as a place or church name rejection.

**Comment by edickens** [comment]
This can be closed.
    _____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by edickens** [comment]
I've had a comment about the report "Please consult the System Administrator. <br>
Illegal quoting in line 1148." where the transcriber does not get the whole message.  It does say that they should contact the SA, which is fine.  But it does not say how to contact the SA.  Perhaps enter a link.  Or include it as CC: for this type of message.  E
