### ISSUE TITLE
Quality control markers on batches

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#804]

**Comment by edickens** [comment]
This is likely to be  needed by CEN and BMD.

When a batch is uploaded the Transcriber needs to indicate; if they have sight checked the Batch; if they have had problems and would like it checked by someone else; if the source is of bad quality and this batch should be revisited if  better images become available; if they have not finished the batch and have yet to check it; if the batch is complete; if they are the checker and have checked the batch.
But this needs debate between the three projects as to how it will work.
EricD
I have put this in as V1.5 because it fits in with changes needed when integrating the image server and for the RAP progress report.

**Comment by edickens** [comment]
There may be another story that covers this, but FreeBMD has a very good report on those batches which have a lot of UCF.  These are batches that need to be revisited and checked by someone else, or we need to try to get a better copy of the image.  So this is automatically highlighting those batches which need investigation.
Yes, there is marker against the image group, and perhaps this needs to be set, by the transcriber or if there is a lot of UCF, when someone uploads a batch created from that Image Group.

**Comment by Captainkirkdawson** [comment]
Story #748 is the UCF report ite version 2.
