### ISSUE TITLE
Unable to edit a 2 part Place name in some cases.

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#806]
See NFK/ Wiggenhall. There are several places with this first word:Wiggenhall St Germans, Wiggenhall St Mary Magdalene, Wiggenhall St Mary the Virgin, and  Wiggenhall St Peter.
I am needing to delete the terminal "s' from St Germans. but each time i use: change Place Name, I get the reply: can't do. that Place name already exists. - well the first word of the name clearly does, but not the full string.

Possible a bug?

**Comment by Sherlock21** [comment]
I tried the same thing in T3 -on the same Place Name. It does not happen there!

So is there a "hidden' place name of the one i need to change this into?

In original version of creating the MPN, if a place name started life in the main list, then it was disabled, it disappeared from view - as one would expect.

Then at a later time, if it was necessary to Create the same place again for some reason, a system message  said:
" Place already exists - you cannot create this one' .

BUT when returning to the start again, and view the full list of place names, the one I was told  I could not create, was actually there in the All Places list again.

do we have some of that anomaly here - except that the magic reincarnation is not there this time?

**Comment by Captainkirkdawson** [comment]
See 762 and fixed
