### ISSUE TITLE
Undefined method `places_json' for nil:NilClass for search query new

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#816]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/562a65f7e93790333a00002f/problems/57498c6ee93790aad6000015)

**Comment by benwbrum** [comment]
Rebuild the places cache should fix this

**Comment by Captainkirkdawson** [comment]
This happens on a regular basis. We need to catch and initiate rebuild automatically rather than seeing the error in the errbit and manually rebuilding

**Comment by Captainkirkdawson** [comment]
Observed a similar issue on my development work . It appears to occur with a nil record in the original cache. Implemented a nil test in my  development branch. Will look at deploying unless Doug has made progress

**Comment by Captainkirkdawson** [comment]
Fixed
