### ISSUE TITLE
Errno::ENOENT: No such file or directory  update_freereg_messages1464424184,log

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#817]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/57495704e93790aad6000012)

**Comment by Captainkirkdawson** [comment]
We create a log file for the system managers on each ASAP file being processed. On successful completion the file is deleted. The naming system does not have enough granularity using the current time stamp, as a result multiple files of the same name are being created and deletion becomes problematic.
Two solutions 1) Do not create a managers log if the managers do not need a report of the processing 2) create a common managers log and place all log information from processing in that one.
What do managers want? Do they want the results of ASAP processing. Currently each user and coordinator get a processing report.

**Comment by Sherlock21** [comment]
I would go for NO automatic log to Managers, unless the person concerned doing the upload is themselves a manager. So I would guess the uploader getting a copy would not be overridden by the Manages NOT getting one.

**Comment by Captainkirkdawson** [comment]
Have increased granularity of log name
