### ISSUE TITLE
Performance degradation with 2.1.4.4

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#818]
The deployment of the new wildcard code has degraded performance,

**Comment by Captainkirkdawson** [comment]
The attached report shows before and after,
The new code was deployed at 17;00 PST. The spikes at 18:00 to 20:00 are while the overnight processing takes place. What is noticeable is that the period leading up to the deployment and since are quite different.

![performance](https://cloud.githubusercontent.com/assets/2874694/15627999/5b75b24a-24b2-11e6-934b-e441445c6f43.JPG)

**Comment by Captainkirkdawson** [comment]
I have confirmed that the overnight processing was especially demanding. 66,000 records were added but more significantly was the deletion of 55,500 records. This finished at 21:45 PST

The load of ASAP processing has been light with a number from 01:00 to 02:00 PST. and only 1 other at 06:00 so file processing was not responsible for the additional response time. Something seems to be different in the search performance

**Comment by Sherlock21** [comment]
I have not been using that feature in the last 48 hours so not mine!

And i only did 3 Process now jobs, at 20:00 hers Friday night GMT.
All the rest of my reprocessing went into the Overnight bundle.

**Comment by Captainkirkdawson** [comment]
Some ucf preliminary code was active. Ben disabled

**Comment by benwbrum** [comment]
On a positive note, although the un-tested UCF code slowed down searches,
it did not bring them down altogether.  Let's call that the bright side of
deploying (and running) untested code!
