### ISSUE TITLE
standard email on file upload failed to arrive

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#827]
The standard email to transcriber failed to arrive when I uploaded WRYSEDMA1.csv today at 17:15hrs BST.

The file upload as a replacement was successful as proven by a user-search for one of the data rows.
This email system had been working OK for me yesterday.  ericb

**Comment by Sherlock21** [comment]
Ignore this one please - it turned up at 18:15

**Comment by Captainkirkdawson** [comment]
#<Mail::Message:17240935460, Multipart: false, Headers: <Date: Thu, 02 Jun 2016 17:22:25 +0100>, <From: freereg-processing@freereg.org.uk>, <To: ericbooker8@gmail.com>, <Cc: ali.hill.wry@gmail.com>, <Message-ID: <57505d419b916_42924012c5bf06989@colobus.freebmd.org.uk.mail>>, <Subject: ericb/WRYSEDMA1.csv was processed by FreeReg at 2016-06-02 17:22:25 +0100>, <Mime-Version: 1.0>, <Content-Type: text/html>, <Content-Transfer-Encoding: 7bit>>
