### ISSUE TITLE
Reject a file beng uploaded with a wrong Place/Church in the first record

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#828]

**Comment by edickens** [comment]
Now a file with a wrong Place/Church is rejected, but not until the full validation, and for overnight processing, not until that process.
But because very few files have multiple Place?Church names, then by validating the first record, only for the Place/Church, then the transcriber will know immediately that they need to correct the problem and resubmit, rather than having to wait perhaps until the next day.
Full validation of Place/Church still needs to be done when the file is processed in case there are errors elsewhere in the file.  Checking just the first records will find 90% of the errors and will save processing time.  E

**Comment by Sherlock21** [comment]
Thank you.

eb

**Comment by Captainkirkdawson** [comment]
Since there is no real overnight processing there is no longer any benefit to this suggestion.
