### ISSUE TITLE
Review Update to mongoid 5

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#830]
We are currently using mongoid 3.1.7. The current version is 5.1 and the latter is required to move to mongo 3.0 and above.

**Comment by Captainkirkdawson** [comment]
Commence a new branch  mongoid5. Install on development machine and development implementation plan

**Comment by Captainkirkdawson** [comment]
Mongoid 5 requires ActiveModel >4 which requires rails 4. Refinery CMS 2.1.1 requires ActiveModel <4.0 Looks like we are in for a major update.

**Comment by Captainkirkdawson** [comment]
Have updated my development server with Rails 4.2.6 and all its components at their latest versions. Have updated to Refinery CMS 3.0.3. Have  converted to the Ruby 2.2 driver for Mongodb 3 instead of moped. Have updated to Mongoid 5. Using Mongodb 3.0. Have moved refinery away from the root so that it does not try to interpret all page requests. 
After many fights I now have a working system that functions correctly both for searches and most member functions.
Have applied a search time limit which is supported by the Ruby Driver for Mongodb.  It works as expected and have implemented code to rescue after timeout with appropriate messages to user. Have implemented the time limit as  a rails configuration setting.

**Comment by dougkdev** [comment]
#466 indicated staying with MongoDB 3.0 instead of 3.2 because 3.2 requires
the new driver, whereas 3.0 does not.  If you already moved to the new
driver instead of moped, is it still advantageous to stay on Mongodb 3.0
instead of 3.2 due to other incompatibilities?

**Comment by Captainkirkdawson** [comment]
You raise a very good question Doug. Since we bit the bullet using the ruby driver version 2.2.5 this does support Mongodb 3.2. Mongodb 3.2 is pushing their new storage engine Wired Tiger but it still supports our current storage engine  MMAPv1. Interestingly it appears that a replicated server complex can have servers with both engines. Bottom line is that I think we should look at Mongodb 3.2 when I have finished the changes to the app for everything else. 

There is a further question and that is do we also update ruby? Our severs are 2.1.6; I am at 2.1.7. Perhaps we should go to 2.2.5. Need to check with Lemon what is available for our servers. I cannot go beyond that yet!!

**Comment by Captainkirkdawson** [comment]
Have committed to mongoid5 branch. Needs to be checkout on test3

**Comment by Captainkirkdawson** [comment]
Updated application running on test3
