### ISSUE TITLE
Processing message for registers

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/MyopicVicar#831]
When batches have been uploaded and processing is not yet finished, it was suggested that a message on the register contents page / other applicable places would be useful to indicate that processing is still in progress.  See #821 for the discussion.

**Comment by edickens** [comment]
Perhaps on the List Batches screen, all Buttons should be disabled
    so that no Show or Edit is possible.  The word "Processing" could
    appear in place of the buttons.  E
    
      On 08/06/2016 09:33, dougkdev wrote:
    
    
      When batches have been uploaded and processing is not yet
        finished, it was suggested that a message on the register
        contents page / other applicable places would be useful to
        indicate that processing is still in progress. See #821
        for the discussion.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by edickens** [comment]
Th enew Image Assignment System has a "Batch Complete" indicator.  The RAP report should show all the information needed.  I don't think this is needed now.
