### ISSUE TITLE
Test of wildcard features

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#834]
Are there any wild card issues with current implementation?

**Comment by Sherlock21** [comment]
I tested it with BenB some time back. It was fine then.

**Comment by Captainkirkdawson** [comment]
Ttanscriber reports:
The help link in the Email goes to webpage which has: Some examples •sm*th finds: Smith, Smyth, Smithe, and Smythe; also Smithers, Smethurst, etc. •davi*s finds: Davis and Davies; also Davids, Davidson, Davison, etc. •cr*f finds: Crawford, Crawfoord, Crawfurd and Craufurd; also Cranford, etc. •pen*c finds: Penicuik, Penicuk, Pennicook, Pennicooke, Pennicuk, Pennicuke, Pennycook, and Penycook; also Pendrick, Pendreitch, etc. This is abnormal for a wildcard search where you would expect eg sm*th to find Smith and Smyth and Smeeth but not Smithe, Smythe, Smithers, Smethurst etc as well. To get the latter ones you would need sm* (or sm*th* if that is allowed). It is no surprise you warn you could get a lot of results. I *think* your new wildcard search is also different from the wildcard search on FreeBMD which means it is confusing to people who use both websites, especially as they are part of the same family. Finally, the tooltip on Surname still says you can't do wildcard searches.

**Comment by Captainkirkdawson** [comment]
EricB said. When I did some tests for BenB, the spec was this:

TRANSCRIBER uses UCF in the data.

RESEARCHER uses a * in the query and gets all the exact spellings, AND the variations generated by the UCF containing names. I did not include looking for names with ? at the end. ( because i did not remember we did that! )
[There must be a minimum of 2 letters before the wild card. and there must be a Place name too if the wild card is in the surname.]

**Comment by Captainkirkdawson** [comment]
EricB said.
Is a ? in a search considered to be a wild Card?
I had worked on the basis that Wild card was *

Perhaps we should spell it clearly - even if its just for the tester.

**Comment by Captainkirkdawson** [comment]
EricD said

I tried Wildcard in Google and got this... https://docs.marklogic.com/guide/search-dev/wildcard I had in my mind that ? is for one character.  But I suggest we use Star only.  We need to say that.

**Comment by Captainkirkdawson** [comment]
As currently implemented. Both * and ? function in the same way. They say accept an and all characters in any name after the position of the wildcard. All characters preceding the wildcard must match the provided characters. ? is not a single character wildcard

**Comment by Captainkirkdawson** [comment]
I may have misspoken! They do not operate as single character wildcards when inside a word ut still function as multiple character matches with leading and trailing matches required

**Comment by edickens** [comment]
Agreed, Star only.  E
    
      On 20/06/2016 01:07, Kirk Dawson wrote:
    
    
      EricD said
      I tried Wildcard in Google and got this... https://docs.marklogic.com/guide/search-dev/wildcard
        I had in my mind that ? is for one character. But I suggest we
        use Star only. We need to say that.
      —
        You are receiving this because you were assigned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
