### ISSUE TITLE
Handling of more than 2 witness names in marriages

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#836]
The  old F1 rules for Marriage records where there  are more than 2 witnesses,  was to create multiple records, each containing 2 of the total number of  Witnesses. Then the search facility will extract all the multiples, so as to cover the total number.
Whilst testing the revised code, and using a common name for the Bride & Groom with multiple Witnesses, the result is most confusing to read. - Even thought the  partners in the multi-witness records are positioned next to each other, one John Brown marrying Mary Smith   looks exactly like every other one in the search results list. One has to select each, and scroll down to the very bottom of the details listing to ring the file number reference to see whether these are for the same marriage or for a different marriage. 
Im my testing I found it most confusing. Even though I knew I was dealing with Multiple witnesses.

FAR BETTER if we implemented  multiple fields  to accommodate multiple Witnesses in one record. then there would be only one result row for these just like there are for all the other records.

The F1 solution was a fudge at the time. We should not be perpetuating it into FR in my view especially as there is a simple solution now available.

**Comment by edickens** [comment]
Agreed.  But the question asked at this week's conference call was
    whether we try to do some code to rectify the "fudge" done in FR1. 
    I said that I did not think that there were enough records, or
    relevance as it is only witnesses, to spend that amount of effort.
    
    However, we should, as soon as the coding allows, enter just one
    record for as many witnesses as there are, for exactly the reasons
    you state here.  But it will need the new WinFREEREG and the new
    file upload format to do this.  E
    
    On 17/06/2016 09:06, Sherlock21 wrote:
    
    
      The old F1 rules for Marriage records where there are more than
        2 witnesses, was to create multiple records, each containing 2
        of the total number of Witnesses. Then the search facility will
        extract all the multiples, so as to cover the total number.
        Whilst testing the revised code, and using a common name for the
        Bride & Groom with multiple Witnesses, the result is most
        confusing to read. - Even thought the partners in the
        multi-witness records are positioned next to each other, one
        John Brown marrying Mary Smith looks exactly like every other
        one in the search results list. One has to select each, and
        scroll down to the very bottom of the details listing to ring
        the file number reference to see whether these are for the same
        marriage or for a different marriage. 
        Im my testing I found it most confusing. Even though I knew I
        was dealing with Multiple witnesses.
      FAR BETTER if we implemented multiple fields to accommodate
        multiple Witnesses in one record. then there would be only one
        result row for these just like there are for all the other
        records.
      The F1 solution was a fudge at the time. We should not be
        perpetuating it into FR in my view especially as there is a
        simple solution now available.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by Captainkirkdawson** [comment]
This will be implemented in #814.

In meantime we need to document a practise for FR.

 I suggest we recommend that additional witnesses are now placed either in notes or as duplicate records with changed witnesses. That when batch is "finished" The transcriber/coordinator go on line and edit those witnesses into additional witnesses on a single record and delete them from the note or delete duplicate record. 

Do we also suggest that coordinators may if they wish clean up their existing marriage records on line

**Comment by edickens** [comment]
My only concern is that if they spend time online creating a single
    record (which is what is needed) and they then download the batch
    because there has been a change elsewhere, the server will recreate
    the multiple records that the transcriber or coordinator has just
    merged.
    
    Should we wait until we have the new upload file format?  Then the
    transcriber will be able to create one record.
    
    E
    
      On 18/06/2016 15:40, Kirk Dawson wrote:
    
    
      This will be implemented in #814.
      In meantime we need to document a practise for FR.
      I suggest we recommend that additional witnesses are now placed
        either in notes or as duplicate records with changed witnesses.
        That when batch is "finished" The transcriber/coordinator go on
        line and edit those witnesses into additional witnesses on a
        single record and delete them from the note or delete duplicate
        record. 
      Do we also suggest that coordinators may if they wish clean up
        their existing marriage records on line
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by Captainkirkdawson** [comment]
It will be a year before we have the new format.

You are correct the "work" will be undone if the batch is downloaded which is one of the reasons I had proposed the combine software in #811 

Regardless we need advise on the Help as to what they should do. We are currently silent

**Comment by edickens** [comment]
OK.  Suggest that we recommend uploading the first record with two
    witnesses, then when the batch is complete, editing online to add
    the other witnesses.  BUT also lock the file.  The Transcriber can
    do this.  The header can also have a comment to say that the file is
    locked as it contains records with more than two witnesses.  It
    should then not be downloaded.
    
    There is no point delaying the creation of single records with more
    than two witnesses, otherwise we are just creating more work for the
    future.
    
    E
    
      On 18/06/2016 17:00, Kirk Dawson wrote:
    
    
      It will be a year before we have the new format.
      You are correct the "work" will be undone if the batch is
        downloaded which is one of the reasons I had proposed the
        combine software in #811
      
      Regardless we need advise on the Help as to what they should
        do. We are currently silent
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by Sherlock21** [comment]
Aback fit clean up as you suggest would at least make them readily useable.
Any chance of a list based on notes comments please to help CC's find them?

**Comment by Captainkirkdawson** [comment]
EricB #811 was rejected at the last scrum.  Perhaps you wish to write a new story for a listing capability. Would be straight  forward.
EricD do you wish to work with Alison to update the Help.

**Comment by edickens** [comment]
Alison - Do contact me over this.  E
    
    On 18/06/2016 18:00, Kirk Dawson wrote:
    
    
      EricB #811
        was rejected at the last scrum. Perhaps you wish to write a new
        story for a listing capability. Would be straight forward.
        EricD do you wish to work with Alison to update the Help.
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by Sherlock21** [comment]
See #837 for the task to provide a listing facility.
