### ISSUE TITLE
Provide a listing facility which to identify all Marriage records which have  Witnesses in the Notes field

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#837]
Provide a service to generate a listing in a downloadable csv file, and sorted by County / Placename/ File owner/ filename/ record row number / Notes field text.
To identify records which contain Other Witness names in the Notes field. - suggest clue could be: contains the any of the words: wit; witness; witnesses. OR where multiple entries have been created to comply with  F1 rules.
Suggest we need discuss how it will function: i.e. run by each CC for themselves. AND by Managers to see the scope of the task we are asking of everyone? and by DM to see how its progressing.

**Comment by Captainkirkdawson** [comment]
This is not a simple request. To process the notes field for content requires some sophistic software to extract names from an unformatted field. Perhaps a first start would be to provide a file with the contents of all records containing something in the notes field and get someone to look at them

**Comment by Sherlock21** [comment]
If its worth doing anything, then surely the first option is to provide more fields in the Marriage Record form?
Then Transcribers can usefully put all Witness names in the right place, and also work through such a list as suggested above, to relocate those already existing.
Working off a list to do "corrections" would be very useful - instead of having to trawl through every Marriage file by hand looking for what's not there in the first place. 
a facility to get ones listing re run ( to check they had all been picked up for example) would be useful.

**Comment by Sherlock21** [comment]
Perhaps a first step would be to COUNT how many Marriage records do have Extra witness names in the Notes?
Then we/you can manage by fact, rather than just a guess.
Even if its a simple as count per County/ Placename where the text WIT or WITNESS appears in the Notes field?

**Comment by edickens** [comment]
#809 needs to be done and then WinFreeREG needs to be modified.
    
    If I understand it correctly, you can now enter more than two
    witnesses if you edit a record online, but if you download the
    batch, these extra witnesses will be lost.  So we have to get the
    means to enter multiple witnesses before we start to find the
    records that need editing.  E
    
      On 17/10/2016 08:35, Sherlock21 wrote:
    
    
      If its worth doing anything, then surely the first option is to
        provide more fields in the Marriage Record form?
        Then Transcribers can usefully put all Witness names in the
        right place, and also work through such a list as suggested
        above, to relocate those already existing.
        Working off a list to do "corrections" would be very useful -
        instead of having to trawl through every Marriage file by hand
        looking for what's not there in the first place. 
        a facility to get ones listing re run ( to check they had all
        been picked up for example) would be useful.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Sherlock21 in #837: If its worth doing anything, then surely the first option is to provide more fields in the Marriage Record form?\r\nThen Transcribers can usefully put all Witness names in the right place, and also work through such a list as suggested above, to relocate those already existing.\r\nWorking off a list to do \"corrections\" would be very useful - instead of having to trawl through every Marriage file by hand looking for what's not there in the first place. \r\na facility to get ones listing re run ( to check they had all been picked up for example) would be useful."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/837#issuecomment-254133491"}}}

**Comment by Captainkirkdawson** [comment]
EricB. Why are we reopening things that have already been addressed or are pending?
We undertook an epic to address multiple witnesses. Many of the stories generated have been implemented. The ability to input on-line as many witnesses as required exists. The ability to display them exists. The ability to search for them will exist when #969 rebuild gets done. A download does NOT loose the multiple witnesses. Duplicate records are created in the download for as many pairs as exist.. There are unimplemented stories that await #809 Flexible CSV format input. Stories that complete the epic namely 812 813 and 814 await action on 809. In fact 812 address the requirement to extract witnesses from Notes.

**Comment by Sherlock21** [comment]
I was not the one reopening anything.

I was just replying to a email of today by Eric D on the subject ( 2 items up from here) where he had not got it completely correct) re Losing the data.

**Comment by Captainkirkdawson** [comment]
EricB
This is your story and request all be it a few months old. 
Do you still need this in light of what has been or is waiting to be done on multiple witnesses?

**Comment by Sherlock21** [comment]
Kill this one if you are going with #969 instead now.
