### ISSUE TITLE
Provide guidance on the search results

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#838]
Eric 28 Jan: Advice please.  I am getting requests
      such as "Does the search do x or y?".  If I don't know the answer,
      how should I log this request?  I have been thinking that we may
      need to ask Ben to check the help documents and ensure that the
      description of the Search is complete.

```
  Also, if I get what I think is a useful request which is sent to
  just me, should I put it out to all CCs to see what they think?
```

Sherlock21 28 Jan: I am in favour of a summary of either a public version of: "What the Search Engine does" in so far as the user needs to know what to put where, to find the likely results but no detailed enough for them to go build their own!
OR for the use of the Managers, a detailed version of the same - so we can take the load off the code writers as you say but actually be able to answer meaningful questions.

After all, does the public get a definition of how the Search engine works in Ancestry of FMP? No.

Kirk 17 June: Example.
In F1 the initial search results showed the origin of the surname. In F2 search results show the deceased person with a surname, whether it be their surname or a relative's surname. Researchers may accept this as the defining result, as only on checking the detail will it be clear whether the surname entered is that of the deceased, or that of a relative, or both. It surely should not be assumed that the surname of the deceased is that of the relative? It usually is, but we should not make assumptions. Perhaps the help info could make this clear.

Eric D 17 June: FR1 says which field it has found.

```
This can be found in FR in the Detail, but not easy when looking for
someone in a long list.
```

**Comment by Captainkirkdawson** [comment]
Is this still open or closed or?
