### ISSUE TITLE
Burton on Trent Location error?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#840]
A search 'and nearby places' with Burton on Trent locates in Kent (Burslem locates in Staffordshire, as expected).

**Comment by PatReynolds** [comment]
![burton](https://cloud.githubusercontent.com/assets/6338822/16305827/693ea368-3953-11e6-9612-10f19b426d0e.JPG)

**Comment by Sherlock21** [comment]
I checked on their Grid Refs and they are Correct.
Burton-upon-Trent (STS) is at SK242230
Deptford (Kent) is at TQ371774.

So Its not the database location values

**Comment by Sherlock21** [comment]
If I do the search reverse way round - i.e. look for baptisms in Deptford (KEN) then it works correctly.

I also did a Nearby search for Smith in Barton-under-Needwood (STS) which is not far from Burton-upon-Trent. this worked correctly - nearby found records form STS and DBY - which is right. Non from Kent.

**Comment by Captainkirkdawson** [comment]
The actual location coordinates for Burton-upon-Trent are incorrect. They are for the Tower of London. Hence the nearby results. The Grid reference is correct but we use the actual coordinates.
Have updated the Place.

**Comment by Captainkirkdawson** [comment]
Works OK now. Was not a bug
