### ISSUE TITLE
Wrong system generated email sent when an Active Transcriber is made inactive

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#841]

**Comment by Sherlock21** [comment]
This relates to system email to Michael Clare on 23 June 2016 when he was made Inactive my his SC (Rest of England). There was no change of CC or SC.

yet the email said: " Please make them welcome"

**Comment by Captainkirkdawson** [comment]
Fixed in mongoid5 branch awaiting deployment
