### ISSUE TITLE
Store files which get rejected on upload for some reason

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#849]

**Comment by Sherlock21** [comment]
As discussed in emails, just store in the Attic ALL files which get rejected on upload for any reason. 
Flag or mark if possible  for easy finding?
 Rather than the Transcriber's efforts go to waste. RegMgr & DM to be able to download in the usual way.
 The CC can then rescue them if possible rather that the effort get lost.

**Comment by edickens** [comment]
Good idea.
    
    Some don't also know that WinReg keeps a backup, so if a file is not
    saved, there is a backup, but I am not sure when the backup is made.
    
    However, a version in the Attic is a good idea.  The CC/SC needs to
    know that they can contact me to find out what the transcriber has
    been doing wrong.  This does not happen often, so is acceptable.
    
    E
    
    On 02/07/2016 17:33, Sherlock21 wrote:
    
      As discussed in emails, just store in the Attic ALL files which
        get rejected on upload for any reason. 
        Flag or mark if possible for easy finding?
        Rather than the Transcriber's efforts go to waste. RegMgr &
        DM to be able to download in the usual way.
        The CC can then rescue them if possible rather that the effort
        get lost.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by Sherlock21** [comment]
Kirk offered to put these into the Attic. 

To me its better than in winReg ‘cos i have no knowledge of that app ansi can see its going to be you and I who get asked to find them
i got the idea from Kirk that its not too big a deal to do this.
but he is busy with oyther things at the moment - 
on the other hand as you read in doreen's note to me - its costing us Transcribers right now.

its in the list as #849.

EB

**Comment by Captainkirkdawson** [comment]
Propose to close as it has been overtaken by events. There is no rejection on an upload. A file may be unprocessable. The file stays there until corrected and processed. The DM can get a list of unprocessed files and take action as appropriate
