### ISSUE TITLE
Cannot access UserID Jonny

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#851]

**Comment by edickens** [comment]
Server hangs then times out.  Using "Manage UserID"/"Select UserID".

Also, when I use the FR Report a Problem, after some time the screen reverts to Enter a new Comment, and the request does not seem to have been saved.

**Comment by Captainkirkdawson** [comment]
Unable to duplicate

**Comment by edickens** [comment]
Is OK now in FR and Test3.  But I think when you were updating the
    database and processing was slow, the Actions Manage UserID/Select
    by UserID had problems with a UserID which had a lot of files. 
    Jonny has about 3/4M records.  E
    
      On 06/07/2016 01:58, Kirk Dawson wrote:
    
    
      Unable to duplicate
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by Captainkirkdawson** [comment]
Its the number of files that is the determinant in response time since we do an on-line calculation of number of records. Likely we really do not need

**Comment by edickens** [comment]
Only really needed when the "Show batches" is selected, although it
    is one of the statistics shown.  But perhaps we should just say "No
    batches uploaded" or "Batches Uploaded" and then give the count when
    the "Show batches" is selected.  The information that the UserID has
    never uploaded any files is the most used information.
    
    However, there are not that many UserIDs with so many files and
    Jonny should not have that many.  He took a lot onto his UserID from
    inactive transcribers when he was CC.  They are not all his work.
    
    E
    
      On 06/07/2016 15:01, Kirk Dawson wrote:
    
    
      Its the number of files that is the determinant in response
        time since we do an on-line calculation of number of records.
        Likely we really do not need
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
