### ISSUE TITLE
Place 'donate' link at bottom of all search results'

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#852]

**Comment by sean-wood** [comment]
Pat to provide text for developers

**Comment by edickens** [comment]
Pat.  Why assigned to me?  Unless this is FR1, I cannot do it.  Eric
    
      On 21/10/2016 15:20, PatReynolds wrote:
    
    
      Assigned #852
        to @edickens.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Assigned #852 to @edickens."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/852#event-832094992"}}}

**Comment by israelriibeiro** [comment]
Hi, @PatReynolds . Could you provide me more information about this?

**Comment by PatReynolds** [comment]
1) the search pages should divert to a donations page.  This should be on individual project website, but using a link to the Giftaid form on www.freeukgenealogy http://www.freeukgenealogy.org.uk/admin/entries/pages/83-help-us-keep-history-free#anchor This would avoid the need for a new form.


2) the text to link to the project-specific donations page should be:Please donate to support [Project Name]’


3) the link to the page should be a ‘Donate’ icon - same for all projects -  which should include the word ‘Donate’. (currently sourcing icon issue #844).

**Comment by israelriibeiro** [comment]
@PatReynolds , how can i access this url? Where can i have to sign up  in order to see this?!

**Comment by PatReynolds** [comment]
Sorry, wrong url.  http://www.freeukgenealogy.org.uk/about/help-us-keep-history-free/#anchor

**Comment by israelriibeiro** [comment]
Hi, @PatReynolds . 

The is over here: [Issue_856](https://github.com/FreeUKGen/MyopicVicar/commit/5f4b92a435ae3bab6e1d2645debe3d3c1361f0e6)
Is this correct?

![test_link](https://cloud.githubusercontent.com/assets/4265692/20861113/f33170f0-b96e-11e6-8498-056219b91499.gif)

**Comment by PatReynolds** [comment]
Text revision suggested for search results page: 
If you have found FreeREG useful, please consider donating to support the work of this and other projects of Free UK Genealogy CIO.

**Comment by edickens** [comment]
I would have been a bit more "aggressive" because we are saving them a 
lot of money.  Halve a look at the GRO ordering 
http://www.gro.gov.uk/gro/content/certificates/default.asp which is now 
£45 per certificate if you want to view it online.  And the cheapest is 
£9.25 
http://www.gro.gov.uk/gro/content/certificates/most_customers_want_to_know.asp#OrderingCertificates 
and you may not even have ordered the correct certificate!

Eric J Dickens

**Comment by PatReynolds** [comment]
Agreed, Eric - added as an issue across all websites.

**Comment by DeniseColbert** [comment]
I've started a document with some ideas: https://docs.google.com/document/d/1xavXbF_rL7GNlx5tNlJobVIPFpmwz_7Dfwl4DMl4y68/edit#

**Comment by israelriibeiro** [comment]
@PatReynolds / @DeniseColbert , i got to chose the best sentence to add to the view? Or you already did?!

**Comment by PatReynolds** [comment]
@SteveBiggs to make a choice and inform @israelriibeiro

**Comment by SteveBiggs** [comment]
My suggested wording is:
While most other genealogy sites charge you to find and read records, FreeREG is dedicated to keeping our searches free.  A small donation towards our costs would really help us keep it that way.
