### ISSUE TITLE
Use responsive google ad units

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#853]
See https://support.google.com/adsense/answer/3213689?hl=en-GB I think this may enable us to serve adverts on tablets/mobiles.

**Comment by sean-wood** [comment]
This approach may need development
This example is taken from the google help page

For example, if you have a <div> with a width of 30% and you place our responsive ad code within the <div>, then depending on the width of the user's screen, we’ll automatically serve different ad sizes. If your page is viewed on a tablet with a width of 1024 px, we'll serve a 307 x 250 ad, and if it's viewed on a 21" desktop PC with a 1680 px width, we'll serve a 504 x 60 ad.

-----
need to understand how we serve ads at the moment

**Comment by Captainkirkdawson** [comment]
I believe this has been passed by other stories and developments and is no longer relevant
