### ISSUE TITLE
Mail not being distributed

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#878]

**Comment by edickens** [comment]
I have not had an overnight update report for two days now.  Did it run?  Were there just no files to be processed?  Is it a distribution problem?  There have been the usual number of records added to the database, so at least ASAP processing is working.  Please check.  E

**Comment by Sherlock21** [comment]
Same with me. my last one was the 21st July too.

**Comment by Captainkirkdawson** [comment]
FR is producing the emails. They are not being distributed, possibly this is a result of reaching our mail providers contracted limit

**Comment by edickens** [comment]
Emails did not get through again last night - early 24 July.   This is critical to the operation.   A transcriber does not know if their uploaded file has errors or not, nor if it was processed, without these emails.   Perhaps not strictly true as they can look at their list of batches, but it is unrealistic to ask them to keep doing this every hour or so.
If this cannot be fixed in the next few hours, I will put out a message because transcribers do not know what is happening and what they should do.

**Comment by Captainkirkdawson** [comment]
You need to put out a message. This in NOT FR

https://news.ycombinator.com/item?id=12142728

**Comment by lemon-ukgen** [comment]
Context: [thread on the tech list](http://lists.links.org/pipermail/freeukgen-tech/2016-July/002910.html) 

* we stopped sending using SendGrid Monday morning, we're sending ourselves again
* we know this generate its own problems, but way less than 100% deferal at SG
* I have been in touch with SG to get the backlog delivered (see attachment)
* looking at alternative providers now

<img width="1429" alt="screen shot 2016-07-26 at 17 35 00" src="https://cloud.githubusercontent.com/assets/16789923/17129590/5b77e910-5357-11e6-8ca2-ba548326efdc.png">
