### ISSUE TITLE
Add "Late Wife of" to Relationship code table in Burials

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#879]

**Comment by Sherlock21** [comment]
benefits are: (1) to reflect more correctly TWYS
and (2) to save having to type the correct words in the notes - and thus save errors where the Transcriber puts the only possible phrase: "Wife of" in the table, and forgets to add the correct title in the notes.

**Comment by Captainkirkdawson** [comment]
There is no relationship code table for burials in FR

The field is a TWYS field

**Comment by Sherlock21** [comment]
I raised  this one because when I tried to Edit one of these relationships online, my revision got rejected. - this was: to edit from WIFE OF to LATE WIFE OF
So I assumed that it was table backed, by a table to whichI did not have access. - hence I asked for this addition.

The change I was trying to do was from WIFE OF, to LATE WIFE OF
However, I later successfully uploaded a file with the required "LATE WIFE OF" as relationship which world fine.

So snag is in "On-Line Edit" - which was reported under Testing snags I think.

**Comment by Captainkirkdawson** [comment]
Unaware of any issues 
![relationship](https://cloud.githubusercontent.com/assets/2874694/17458319/67c267a6-5bca-11e6-9b86-d76fa2108a88.JPG)

**Comment by edickens** [comment]
This is to do with WinReg.  The transcriber can edit the table as held 
on their computer.  E

**Comment by Sherlock21** [comment]
OK, close this and move o please.
ericB.

**Comment by Sherlock21** [comment]
This is NOT to do with WinReg at all.
It is  to do with FR. And editing a Burial record online.

I will make a full test of the feature whem I have the time, and raise whatever is necessary as a Test Report.
