### ISSUE TITLE
Create Mac policy/roadmap

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#882]
Decide interim actions needed to support mac users until 'online' transcription is in place.

**Comment by Sherlock21** [comment]
Does this imply that there will be one way only  of creating files of transcribed data in the future?
If yes, please state the new policy now.

IF not, then why is it an issue? The method is to create a non- WinReg file as Windows, Linux and Mac users do now, surely?
Any issues about invalid character codes is common to ALL .

**Comment by Captainkirkdawson** [comment]
Propose to close as there is no real requirement.
