### ISSUE TITLE
Server uploaded a file for an Inactive UserID?

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#884]

**Comment by edickens** [comment]
For five nights in a row now this file has been submitted for processing:-
Started on the file Malcolm1.csv for maltum at 2016-08-08 07:25:07 +0100. <p>
csv slurp rescue Illegal quoting in line 2.
maltum	Malcolm1.csv *We were unable to process the file possibly due to an invalid structure or character. Please consult the System Administrator*. <br>
Illegal quoting in line 2.
I have had no reply to my emails from the transcriber, so I made this UserID inactive early on 7 August.   It is possible that he uploaded again before I did this, but the log needs checking.  I now think it is more likely that the server keeps trying to process this file.
This file is still in the "Waiting to be processed".   Should it have been removed from this?
What is happening?

**Comment by edickens** [comment]
The file (I have a copy but it is CSV and so not supported here) is not being deleted after overnight processing from the "Waiting to be processed" list and so gets processed again and again.  I thought it was the transcriber, but it is not.
So I have now deleted the file from the "Waiting to be processed" list and made their account "maltum" active again.

**Comment by Captainkirkdawson** [comment]
What is the identified bug?
The waiting to be processed flag is only removed on successful processing of the file. 
The file in question was not processed. 
Illegal quoting has to be addressed as stated in the message. Often a difficult one for a transcriber/coordinator with which  to deal.
The system did not permit an inactive user to upload as stated in the story. So there is no bug.

**Comment by edickens** [comment]
Hi Kirk,
    
    The problem was that the "transcriber" uploaded rubbish, which was
    not processed.  But then never corrected the file.  The file was
    called Malcolm1.csv, nothing like our format.  As a result it kept
    processing every night for five nights until I deleted it.
    
    At first I thought that the file had been processed after I had made
    the UserID Inactive. The transcriber never replied to my emails.  I
    thought  that they were uploading the file again and again to try to
    get it through.  If I had not deleted it, then it would still be
    being processed every night.
    
    So the question is?  Should the server remove the file from the
    "Waiting to be processed" if it has done an error report?
    
    E
    
    
    On 13/08/2016 16:41, Kirk Dawson wrote:
    
    
      What is the identified bug?
        The waiting to be processed flag is only removed on successful
        processing of the file. 
        The file in question was not processed. 
        Illegal quoting has to be addressed as stated in the message.
        Often a difficult one for a transcriber/coordinator with which
        to deal.
        The system did not permit an inactive user to upload as stated
        in the story. So there is no bug.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #884: What is the identified bug?\nThe waiting to be processed flag is only removed on successful processing of the file. \nThe file in question was not processed. \nIllegal quoting has to be addressed as stated in the message. Often a difficult one for a transcriber/coordinator with which  to deal.\nThe system did not permit an inactive user to upload as stated in the story. So there is no bug."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/884#issuecomment-239626978"}}}

**Comment by Sherlock21** [comment]
Eric D & Kirk


I seem to remember a few weeks back there was an issue where a Transcriber uploaded a large file which had either a place name or a church name error which prevented it being processed.

But the Uploader had lost the file so had nothing to correct. - but it was a large collection for us to loose.
As it appeared that these rejected files are “deleted" by the server - or so I thought- I asked Kirk if he could recover that file by any good fortune.

Reply was: Its not actually deleted form the server, just not accessible by us.
So Kirk agreed: its easy to have it saved somewhere  from which the CC and you & I can recover it/ download it and correct the data to reload.

I don’t remember the outcome. Nor if it actually got into the production server - but as it sounds like your situation, it might be the same topic.

Sorry for the vagueness - its gotten lost in recent events I am afraid - but maybe Kirk can confirm where we are if he did close this loop - and what arrangements do we have in being now?

Eric B

**Comment by Sherlock21** [comment]
Not sure what this is "ASSIGNED" to me. I can  do nothing to produce the code needed and have been criticised for telling the coders how to do their job!

I will test it out when the process has been devised by Kirk and the code written.

**Comment by Captainkirkdawson** [comment]
Currently I am doing nothing on this.

You and EricD were assigned to **specify what needed to be done**. 

If nothing we will close.

**Comment by edickens** [comment]
How can this happen as Inactive people cannot log in?
    
    E
    
      On 25/10/2016 17:02, Kirk Dawson wrote:
    
    
      Currently I am doing nothing on this.
      You and EricD were assigned to specify what needed to
          be done. 
      If nothing we will close.
      —
        You are receiving this because you were assigned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #884: Currently I am doing nothing on this.\r\n\r\nYou and EricD were assigned to **specify what needed to be done**. \r\n\r\nIf nothing we will close.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/884#issuecomment-256079525"}}}

**Comment by Captainkirkdawson** [comment]
But a SC/CC can and you have explicitly requested that they be limited to uploading to inactive userids #680

**Comment by edickens** [comment]
I meant that an inactive UserID can  only have files uploaded into it by a CC or SC.  A SC or CC can upload into any Active UserID as well.  BUT - It is important that the confirmation email is sent to the person who uploaded the file, not the email address in the files UserID (as well as the SC).  This should apply to all uploads.  It needs to be to the email address in the UserID of the person logged in.  An Inactive UserID does not want to get emails.  They should no longer be involved with FR.  If the file is loaded into an Active UserID by a SC/CC, then the CC/SC should have been in contact with the transcriber so no need for the confirmation email to go to the transcriber.  Perhaps a file loaded into someone else's UserID by a SC/CC should be locked with an SC lock.  In this way they will query with their SC if they need to work on this file.
Needs approval by Project Manager.

**Comment by Captainkirkdawson** [comment]
No record is kept as to who uploaded the file so there is no ability to do as suggested.

**Comment by edickens** [comment]
So I suggest that if the batch is being loaded into an Inactive UserID (no matter who uploads it) then the confirmation email is only sent to the SC and not to the UserID.
It might have been possible to do it for ASAP processing as the person is still logged in, but we cannot have two systems for ASAP and Overnight.

**Comment by Captainkirkdawson** [comment]
An email does not go to an inactive userid.

**Comment by edickens** [comment]
I've just read through this story and it has got into a muddle with different topics.  My guess now after all this time is that the UserID was changed to Inactive while the file was being processed.  Not worth doing any more on it.  Close it.
