### ISSUE TITLE
Refinery editor centers everything in preview

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#885]
The refinery editor displays all text as centred. 
We need to display page under development as it will be displayed when saved.

**Comment by AlOneill** [comment]
Digging using Firebug, it seems that that `text-align: center;` is coming from line 6 of  the wymiframe (no extension given) file. 

Then all other elements inherit. This is quoted for an individual element: `Inherited from body.page_part_body.visual_editor_iframe_body`

**Comment by benwbrum** [comment]
Thanks, Alison -- this is very helpful!

**Comment by benwbrum** [comment]
See comment in #895

**Comment by Captainkirkdawson** [comment]
Fixed

**Comment by Captainkirkdawson** [comment]
But only on my development machine!

**Comment by Captainkirkdawson** [comment]
I can only get this to work on my development machine that has rails loading the assets. What is likely the issue is the positioning of a css file in the asset pipeline. Beyond me!!!

**Comment by dougkdev** [comment]
I think the reason you are only able to get this to work in development is that
the file wymiframe.html.erb (which uses rails helpers to find the formatting.css) was put into the public directory.  Everything in public is served as a static file by apache in production. Nothing in that directory is processed by rails or the asset pipeline, so there should be no .erb in that directory, only completed, static assets, (which unfortunately also precludes referencing files with asset pipeline digests in their names).

**Comment by Captainkirkdawson** [comment]
Thats a good catch.

I was totally unsure where to put wymiframe.html. It does not seem logical to put it in public but where else should we put the damn thing. Having it in public without the erb does work for vervet though

**Comment by AlOneill** [comment]
Looking good -- many thanks!

**Comment by Captainkirkdawson** [comment]
Sorry it took us so long
