### ISSUE TITLE
New volunteer confirmation emails being lost?

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#901]

**Comment by edickens** [comment]
I have not received any new volunteer emails so that I can invite them to the transcribers mailgroup.  I know that some new UserIDs have been set up.  And are the SCs getting them?  E

**Comment by edickens** [comment]
I have not had a new volunteer email since 15/08/16, which is unusual.  Can anyone check if there have been any new registration since then, and if so, why have I not had the confirmation emails?  E

**Comment by lemon-ukgen** [comment]
Let me know an email address to search the logs for and I'll take a look.

**Comment by edickens** [comment]
Perhaps no new volunteers have registered.  I don't know of any.  It
    just seems unusual.  I have no means to check.  E
    
      On 29/08/2016 09:55, lemon wrote:
    
    
      Let me know an email address to search the logs for and I'll
        take a look.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lemon-ukgen in #901: Let me know an email address to search the logs for and I'll take a look."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/901#issuecomment-243069614"}}}

**Comment by edickens** [comment]
I have now had confirmation that emails from the registration of new transcribers are not getting to me at freereg.edickens@gmail.com.  For example the UserID sueann email sue@littonfields.co.uk registered on 26 August.  But there are others and none are getting to me.  E

**Comment by lemon-ukgen** [comment]
On 7/09/2016 05:33 AEST Eric Dickens wrote:
> I have now had confirmation that emails from the registration of new
> transcribers are not getting to me at freereg.edickens@gmail.com.
> For example the UserID sueann email sue@littonfields.co.uk registered
> on 26 August.  But there are others and none are getting to me.  E
>

I can see SendGrid delivering mails to that address. I can't tell what's 
in them, but I don't believe there's a deliverability issue between 
UKGEN and your Gmail account.


At UKGEN:

```
Sep  6 20:11:00 howler postfix/qmgr[43922]: AB53E2009E: 
from=<commscoord.freereg@gmail.com>, size=7698, nrcpt=2 (queue active)

Sep  6 20:11:01 howler postfix/smtp[16875]: AB53E2009E: 
to=<FreeReg.edickens@gmail.com>, 
orig_to=<freereg-contacts@freereg.org.uk>, 
relay=smtp.sendgrid.net[159.122.224.196]:587, delay=0.36, 
delays=0.09/0.04/0.17/0.06, dsn=2.0.0, status=sent (250 Ok: queued as 
5ws_hMBmSSy1U9G8yti56A)
```

At SendGrid:
```
Email
     freereg.edickens@gmail.com
Reason
     250 2.0.0 OK 1473189068 n2si248403ite.92 - gsmtp
SMTP-ID
     <CADv96+gmyWiGP3Nw=2DGiWekWOwOB7SHi=6=6nj04QQA0-8q0A@mail.gmail.com>
Processed String
     September 6, 2016 - 08:11:08 PM
MSGID
     5ws_hMBmSSy1U9G8yti56A.filter0447p1mdw1.17932.57CF14C441.1
```

**Comment by edickens** [comment]
They are going to the transcriber because  they complete registration.  
They are not in my gmail Spam, nor do I get them.  I did before the last 
software update.  E

**Comment by Captainkirkdawson** [comment]
Found a hidden issue. Fixed. You should see them tomorrow if there are registration completions

**Comment by edickens** [comment]
I am still not getting copies of these emails.  The SC does.  See UserIds Jennifer and brookwood40.  E

**Comment by edickens** [comment]
I have had a few emails from volunteers these last few days saying that they have not heard from anyone after registering.  So I am also wondering if the emails are going to the SCs?  But some SCs have told me that they did get the emails, so I am confused, except that I know that there is a problem.

**Comment by dougkdev** [comment]
Would you like me to run the query again right now instead of waiting until
Kirk is back?

**Comment by Captainkirkdawson** [comment]
There were no registrations between Sept 13 and Sept 18.
There have been no emails on registration completion since my change.

**Comment by Captainkirkdawson** [comment]
Since the change there have been 5 completions so emails are still not being generated

**Comment by Captainkirkdawson** [comment]
I had amended the wrong email. Sorry!!

**Comment by edickens** [comment]
I'll let you know when a new registration email gets through.  TY  E
    
    On 19/09/2016 21:25, Kirk Dawson wrote:
    
    
      I had amended the wrong email. Sorry!!
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #901: I had amended the wrong email. Sorry!!"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/901#issuecomment-248114651"}}}
