### ISSUE TITLE
Is it time to add extra fields?

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#902]

**Comment by edickens** [comment]
With the large amount time to add extra indexes, and a possible rebuild to be done, is this a good time to also add extra fields, even if we do not use them straight away?  There are about half a dozen that have been requested.  E

**Comment by Captainkirkdawson** [comment]
Only if those fields have to be used in an index

**Comment by edickens** [comment]
I think some do.  Can't remember them all, but in BA and BU a
    separate Surname for the person involved to identify it from the
    relative.  Also, not sure about Age in BA  which would be needed to
    calculate the approximate year of birth.  E
    
      On 25/08/2016 17:30, Kirk Dawson wrote:
    
    
      Only if those fields have to be used in an index
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #902: Only if those fields have to be used in an index"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/902#issuecomment-242452995"}}}

**Comment by Captainkirkdawson** [comment]
As written this is too broad to be addressed. Which fields for what collections. We have stories 633 and 655 already scheduled for 1.6 as they involve transcription input.
Any additional fields that are to be populated by transcribers cannot be dealt with until we have addressed the flexible CSV input.  So only additional fields that could be considered at this time would be generated fields of coordinator meta data fields. These are unlikely to need index creation

**Comment by edickens** [comment]
Understood.  But we could identify these fields, get them and the
    indexed set up, even if we cannot enter any data into them now.  At
    least they would be ready and a re-index would not be needed. 
    However, suggest closing this now.  E
    
      On 27/08/2016 00:09, Kirk Dawson wrote:
    
    
      As written this is too broad to be addressed. Which fields for
        what collections. We have stories 633 and 655 already scheduled
        for 1.6 as they involve transcription input.
        Any additional fields that are to be populated by transcribers
        cannot be dealt with until we have addressed the flexible CSV
        input. So only additional fields that could be considered at
        this time would be generated fields of coordinator meta data
        fields. These are unlikely to need index creation
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #902: As written this is too broad to be addressed. Which fields for what collections. We have stories 633 and 655 already scheduled for 1.6 as they involve transcription input.\nAny additional fields that are to be populated by transcribers cannot be dealt with until we have addressed the flexible CSV input.  So only additional fields that could be considered at this time would be generated fields of coordinator meta data fields. These are unlikely to need index creation"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/902#issuecomment-242873215"}}}

**Comment by Captainkirkdawson** [comment]
To do so would require coding in the fields and that takes time and testing and we would end up creating a meaningless index which would then have to be populated and updated.
