### ISSUE TITLE
Develop Plan for Responding to the Accessibility Report

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#903]
The Shaw Trust accessibility report is available at:
https://drive.google.com/file/d/0BwVHfubVQz16OW1idmpqWTdrbkU/view
As a result of this story we will have.
Individual stories that identify what  we propose to undertake (if anything) for each of the recommendations made by the Trust

**Comment by Captainkirkdawson** [comment]
Alison noted:
Hmm. Quite a long list! But only to be expected.

I can report that one small item -- STAS-F03: Empty Links -- was dealt with a couple of days ago.

**Comment by Captainkirkdawson** [comment]
EricD noted:
All very sensible, but the consultants who advised us on the website format should have seen these standards.  This is a huge amount of work to put right, but more importantly it will be a radical change for all of us who have just got used to using the website and finding our way around it.

I hope this does not delay the programming of the rest of Version 1 because we have a lot of essential features to add.

**Comment by Captainkirkdawson** [comment]
Pat Reynolds noted:
I agree with EricD that much 'should have been done right first time'.  My intuition, running my eyes down the 'to do' list is that what we have is a list of tasks which will need different skillsets to implement.  Some will be for developers, others for those who know how to use Registry. Some have simple 'this is broken, this is the fix' stories, others will need debate and consideration among the team.  

What I am wondering about (and feel free to suggest alternatives!) is getting all these stories onto the board, but using an alternative milestone sequence (perhaps A.1 for the highest priority, etc.  Marking each up with an indication of the type of skill needed, and its duration (with epics marked as such).  I suspect that quite a lot are calling for the kinds of skills that we have (potential) volunteers with - plus the Shaw Trust said they thought they might be able to help.

However, it is, I think, inevitable that this will mean that completion of FreeREG version 1.7 is later than it would have been if we had not had the report written.

**Comment by Captainkirkdawson** [comment]
EricD noted:
Yes, put it all into Stories under a new milestone.

But the Trustees need to decide if this is important enough to delay the project.  There is still so much basic work to do and FreeBMD and FreeCEN need to be completed.  What I suggest is that this report is digested into a new standard and that is use that in future.  When the projects are complete, or a module is being rewritten, then we can go back and reprogram what has been done.

We had a lot of debate as to whether the area behind login should be a different standard to that shown to researchers.  This is to do with the text colour, which is very tiring, and so little to view at a time on the screen making it necessary to scroll a lot.  Perhaps we can develop a standard for behind the login based on the Shaw Trust standard and then we can see how it works and get used to working to it.

I'm also concerned about the amount of time and cost we are spending on getting the present database to work.  We have set the time out longer and longer because the searches need so much processing power to work.  But what are we going to do when FreeREG is ten times the size, or when FreeBMD comes online with its 200M records?  We are struggling on 36M, and we have hardly started.

**Comment by Captainkirkdawson** [comment]
An interesting document. Interesting comments by Eric and Pat. Concerned that these comments are going to get lost.

My initial reaction was " Wow as  a developer I am totally unfamiliar with almost all of these requirements". No wonder we failed! Time to retire

My suggestion is that before we run off creating a whole set of specific stories before we have even had our discussion with Shaw next week that we define a single story that is Develop Plan for Responding to the Accessibility Report. Clearly an epic. So we can capture ideas and comments

**Comment by Captainkirkdawson** [comment]
Alison noted.
My take on the requirements is that they fall into 3 natural groups:

HTML (+ a little CSS) -- we have the skills to sort out the markup! focus is a state much like hover is, the tab order can be rationalised, skip links put in place, heading made hierarchical, &c. (Any missing knowledge is just a click away...)

RefineryCMS -- e.g. the <title> tags, which may be new territory (?) for the developers. Before the upgrade, Refinery 'Advanced Options' hinted that control over meta tags (including <title>) on a per page basis is entirely possible, just not set up. I have edited a page controller (?correct term), in a dummy Refinery site, so that a page's <h1> tag content is used to construct the title tag. This cannot be beyond the wit of our Talented Trio (although I do appreciate that our setup is not a simple one).

Colour scheme (contrasts) -- trickiest to put right, requiring agreement on a scheme and editing of vars.scss (the file that defines the colours we use and how we access them). There are tools for checking contrast, e.g. http://webaim.org/resources/contrastchecker/ which can help.

So, don't panic and don't even think of retiring (Kirk, or anyone else!) over this.

And I agree that the consultants who set this up in the first place should have been well aware of the issues surrounding accessibility and should have provided, for instance, a colour scheme that is useable / compliant and a way of specifying <title> tags. (Unless we told them not to bother!!)

And, yes, let's start with a single epic story and some proper analysis of the work to be done, &c, and only then formulate a plan of action with specific stories.

**Comment by Captainkirkdawson** [comment]
Pat noted  I have (temporarily) given this a 1.5 milestone as I think we have only a limited time for a re-submit (6 months). The work is likely to be suitable for the new html/css volunteers, so will not have a large impact on development schedules

**Comment by PatReynolds** [comment]
The feedback from users who still use (and prefer) FR1 suggests that we need to deal with the tricky issue (colour scheme) before we can close down FR1 completely.

**Comment by edickens** [comment]
I'm only suggesting that we close down everything, except
    searching.  We need to remove all email links and just refer people
    to the new website if they want help or to make comments.  The
    transcriber's help pages and image server access can still be there,
    but there will be no links from the homepage.  You will need to know
    the URLs to access them.  E
    
      On 07/09/2016 14:37, PatReynolds wrote:
    
    
      The feedback from users who still use (and prefer) FR1 suggests
        that we need to deal with the tricky issue (colour scheme)
        before we can close down FR1 completely.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@PatReynolds in #903: The feedback from users who still use (and prefer) FR1 suggests that we need to deal with the tricky issue (colour scheme) before we can close down FR1 completely."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/903#issuecomment-245282524"}}}

**Comment by Captainkirkdawson** [comment]
Individual stories written

**Comment by Captainkirkdawson** [comment]
In the scrum of 21 September it was agreed that Pat would review the priority of each individual recommendation. 

I subsequently argued that we should be looking at the public pages page by page and ensuring that each page met all accessibility issues. That it was better to address all aspects on a page at the same time. I believe that this was agreed although the scrum minutes do not reflect this.

I have added 2 stories that reflect this alternate approach.  #945 and #946.
