### ISSUE TITLE
Change batch owner crashes

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#904]

**Comment by edickens** [comment]
I don't use this often so did not check on Test3.  I did "Report a problem" on the UserID/List batches screen,  but it has not appeared in th messages, nor does it seem to have been sent to Sandra.  Hence it never got converted to an issue.  Hence this story.  I have a long list of batches to move for her.  E

**Comment by Captainkirkdawson** [comment]
Fixed
