### ISSUE TITLE
Process for More Info

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#908]
There are many stories that come in and require additional information.
I for one am not going to track down that information.
We need a process for getting that information

**Comment by Captainkirkdawson** [comment]
There are 27 stories that fall into that situation

**Comment by edickens** [comment]
Agreed.  When we define the system, we need to have a means for the
    reply to the Story to go to the originator.  Many stories are
    entered on behalf of a sender, or are "Convert to issue".  Comments
    against stories only go to the Waffle distribution.  E
    
    On 30/08/2016 15:35, Kirk Dawson wrote:
    
    
      There are many stories that come in and require additional
        information.
        I for one am not going to track down that information.
        We need a process for getting that information
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Follow up on More Info (#908)"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/908"}}}

**Comment by PatReynolds** [comment]
Would this be a task for the Comms Coord?  She could ask for clarification on what exactly is needed, off github/waffle, if not clear.

**Comment by Captainkirkdawson** [comment]
It could be but is the workload to much?

**Comment by richpomfret** [comment]
The process has now been outlined i.e. Sandra is now in charge of sourcing more info and updates the stories as appropriate for us to then prioritise in the backlog.
