### ISSUE TITLE
create /browserconfig.xml for use by IE/Edge pinned pages

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/MyopicVicar#910]
We get lots of failed GET requests for /browserconfig.xml which is used by the newer Microsoft browsers for "pinned" websites. We do not currently provide that file.

**Comment by Captainkirkdawson** [comment]
Have added instruction to meta that tells IE not to look for the file

**Comment by dougkdev** [comment]
Apparently some browser versions or devices look for the file despite the
meta instruction, so we were still getting lots of 404's for this file.  I
just added a minimal browserconfig.xml (without referencing any mstile
images) to the /public directory to prevent the lingering 404's in the
server log. The frontend assets repositories for both freecen and freebmd
have mstile png imagesand browserconfig.xml file, but for some reason those
images were never created for FreeReg? We can create some from the other
FreeReg icons and then add those to the browserconfig.xml.

**Comment by Captainkirkdawson** [comment]
Was implemented a long time ago
