### ISSUE TITLE
create new syndicate fails

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/MyopicVicar#911]
See this errbit report for details:
http://errbit.freeukgen.org.uk/apps/56296bbde93790333a000002/problems/57c70c73e9379035dc000018

**Comment by dougkdev** [comment]
problem was in the breadcrumbs.

**Comment by dougkdev** [comment]
Fix pushed to master and test3.

**Comment by edickens** [comment]
Doug - What syndicate are you creating?  Is it in FR?  E
    
      On 31/08/2016 18:42, dougkdev wrote:
    
    
      Fix pushed to master and test3.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dougkdev in #911: Fix pushed to master and test3."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/911#issuecomment-243842495"}}}

**Comment by dougkdev** [comment]
No, I needed to set up the Technical syndicate for FreeCen. But the error
was in code shared by both FreeReg and FreeCen.
