### ISSUE TITLE
Write up the difference between the two Locks

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#912]
There is the Transcriber Lock and the Syndicate Coordinator Lock of a file.  The Help does not explain how these work and the differences.

**Comment by edickens** [comment]
The situation has arisen where an SC wants to lock a batch to stop the transcriber from deleting it.  My understanding is that if the transcriber downloads the file, then the lock is removed and they could then delete it.  But are both locks removed?  Does relocating a batch to a new Place/Church set both locks?  A more detailed explanation needed in the Coordinator Help Pages.  E

**Comment by Captainkirkdawson** [comment]
See also #518

**Comment by AlOneill** [comment]
The current info, on 
http://www.freereg.org.uk/cms/information-for-transcribers/file-and-batch-actions
says:

**Batch and file locks**

"When a batch is locked, the whole file is locked. There are actually two locks: one for you and one for your coordinator. Yours will be set if you make an online edit; your coordinator's will be set if they make an online edit to your batch. You can remove your own lock by downloading a copy of the edited file: from any listing of your files, find the file and then click on DL.

"If your coordinator has set the lock, then they will remove it only when they are sure that you have downloaded a copy of the edited file."

How does it need to be changed?

**Comment by edickens** [comment]
Hi Alison,
    
    My only suggestion is that the last sentence should read "If your
    coordinator has set the lock, then they can remove it when the
    reason for the lock is no longer a problem.."
    
    I put it this way because there are other reasons for putting on a
    Coordinators lock, such as moving the batch to a different UserID,
    or moving it to a different Register Type, or the transcriber is not
    entering data correctly, or the transcriber is deleting batches.
    
    Regards,
    
    Eric.
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 06/09/2016 01:12, AlOneill wrote:
    
    
      The current info, on 
        http://www.freereg.org.uk/cms/information-for-transcribers/file-and-batch-actions
        says:
      Batch and file locks
      "When a batch is locked, the whole file is locked. There are
        actually two locks: one for you and one for your coordinator.
        Yours will be set if you make an online edit; your coordinator's
        will be set if they make an online edit to your batch. You can
        remove your own lock by downloading a copy of the edited file:
        from any listing of your files, find the file and then click on
        DL.
      "If your coordinator has set the lock, then they will remove it
        only when they are sure that you have downloaded a copy of the
        edited file."
      How does it need to be changed?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AlOneill in #912: The current info, on \nhttp://www.freereg.org.uk/cms/information-for-transcribers/file-and-batch-actions\nsays:\n\n**Batch and file locks**\n\n\"When a batch is locked, the whole file is locked. There are actually two locks: one for you and one for your coordinator. Yours will be set if you make an online edit; your coordinator's will be set if they make an online edit to your batch. You can remove your own lock by downloading a copy of the edited file: from any listing of your files, find the file and then click on DL.\n\n\"If your coordinator has set the lock, then they will remove it only when they are sure that you have downloaded a copy of the edited file.\"\n\nHow does it need to be changed?"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/912#issuecomment-244823872"}}}

**Comment by AlOneill** [comment]
Done.
