### ISSUE TITLE
Set the "Delete Records part 2" to run overnight as a routine in Test regions - as it does in Production

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#913]
When doing Testing, or when using this region for training or familiarisation, Search results records are cluttered with part deleted records

**Comment by Sherlock21** [comment]
This arises from  the fact the REMOVE a batch is a 2 stage job - some elements of the data disablement  happen straight away, and the rest are complete in a different routine. - In Production the second step is run automatically overnight. 
In the Test region, the Second part of the task is not run. So that in a search in the Test region, one gets records that fit the criteria, but have been "Part 1 Delete" but are still in the indexes,  [ in addition to any Genuine records that meet the criteria of course]

This is confusing at best, and most misleading to those who don't know the intricacies . And waste much time for the tester, in trying to sort out the wheat from the chaff, and hunting for files/ batches which are not accessible but are listed in the Search Results.

**Comment by Captainkirkdawson** [comment]
We are not set up to run scheduled tasks on the test server.
Have set the delete task to run

**Comment by Sherlock21** [comment]
OK, Kirk

thanks for doing it by hand.

EB
