### ISSUE TITLE
Reset password reports "Invalid token"

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#914]

**Comment by edickens** [comment]
The transcriber sandy has asked me for a password reset.  I used the proper button.  This is the email that was sent:-
> From: reg-web@freereg.org.uk
> Date: 3 September 2016 at 21:08:43 BST
> To: sandracooper44@icloud.com
> Subject: Reset password instructions
> Reply-To: reg-web@freereg.org.uk
>
> Hello sandy!
>
> You have either just registered and need to set your own password or just need to change your existing password. You can do this by clicking on the link below.
>
> Change my password
>
> Your password won't change until you follow the link above and create a new one.
>
> We hope you will enjoy or already are enjoying working with FreeREG. It is only through your work that researchers can find their ancestors on FreeREG.
>
> The FreeREG Team.

with the link:-
http://www.freereg.org.uk/cms/refinery/users/password/edit?reset_password_token=GzYBs25P5u_b1FUcwXE9

but she says that she gets the messages "Invalid token".

I cannot see anything wrong.

E

**Comment by Captainkirkdawson** [comment]
Remember the link is only good for 24hrs and can only be used once.

**Comment by Captainkirkdawson** [comment]
Cannot duplicate issue

**Comment by edickens** [comment]
They may have tried to use it twice.  It was within 24 hours.  Close
    this.  E
    
      On 05/09/2016 02:19, Kirk Dawson wrote:
    
    
      Remember the link is only good for 24hrs and can only be used
        once.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #914: Remember the link is only good for 24hrs and can only be used once."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/914#issuecomment-244640483"}}}
