### ISSUE TITLE
20 STAS-F15: Insufficient Colour Contrast AA

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#931]
Logos and styling

NB: these are **not** the final colours (AO)

 https://drive.google.com/file/d/0BzRDUeF70Mtpa1dqb1NmLTNtLVk/view?usp=sharing

Priority (10 4 10 4) 28

**Comment by Captainkirkdawson** [comment]
Alison noted
<p>Colour scheme (contrasts) -- trickiest to put right, requiring agreement on a scheme and editing of vars.scss (the file that defines the colours we use and how we access them). There are tools for checking contrast, e.g. <a href="http://webaim.org/resources/contrastchecker/">http://webaim.org/resources/contrastchecker/</a> which can help.

**Comment by Captainkirkdawson** [comment]
Essential for shut down of FR1

**Comment by edickens** [comment]
I'm only proposing now that we shut down all FR1 functions and
    links, except Searching.  So other than someone seeking Help, there
    will be no need for anyone using FR1 to access FR2.  E
    
      On 08/09/2016 04:07, Kirk Dawson wrote:
    
    
      Essential for shut down of FR1
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #931: Essential for shut down of FR1"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/931#issuecomment-245481431"}}}

**Comment by AlOneill** [comment]
The only colour in the current scheme that can be used for normal sized text (such as most links) is the 'magenta'. It is thus also the only background colour of the four brand colours that can be used with normal-sized white text in information boxes.

Navy/white can be used for info boxes, but 'navy' is not suitable as a link colour as it is not clearly distinguishable from the dark grey ordinary text. (Old-style browser-default link blue, 0000ff in RGB parlance, is both compliant and distinguishable, which is interesting ... )

**Comment by PatReynolds** [comment]
Pat to locate original documentation and send to Alison.

**Comment by PatReynolds** [comment]
Trustee decision: use normal convention for links (i.e. blue for unclicked, purple for clicked).  Other colours may be changed as we see fit in order to comply with accessibility requirements.

**Comment by PatReynolds** [comment]
See also conversation on Coordination board re. colour of FreeREG logo etc. post FreeCEN2 colour change #437

**Comment by DeniseColbert** [comment]
@AlOneill to add image to this story

**Comment by AlOneill** [comment]
Here are the proposed colours for the FreeREG logo and links.

:hover and :focus states for link to be styled along same lines as for FreeCEN (link text underlined and dark grey, plus background of very light version of same blue for :focus state).

![FreeCen__Icons_testing.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d69640ab53e3ab3d433467200aa4693cc7f33ab0487e021b4d44be445b0a17adac8022a2be3c77d8590befd16d5e77933d12faaa9e0dfd50e474d412dcfce9c85ecafa3c2ded8a8a4f371f071c8eff5935a99a5985.png)

**Comment by Sherlock21** [comment]
There is hardly any contrast between the blue and the existing middle colour on my screen - What was supposed to be wrong with the present colours - they are very different to me on colour and in contrast too. 
The wrong one out is the middle block, which overlaps the other 2 if anything is wrong.

If anything is wrong, the just remove the logo completely! and revert the text FreeReg to clearly different colours if you need to use colour at all.

**Comment by AlOneill** [comment]
@Sherlock21  Sorry, but I do not understand most of your first para. In short, the present brown is useless in anything but the logo: it does not have sufficient contrast against white or black to be used in text, &c, and thus represent FreeREG outside of the logo.

The edited colours look fine to me. Screens and eyesight vary from user to user: let's see what others think first. (Colours in *logos* are not required to be access-friendly.)

The set of 4 logos is part of the UKGen identity and so can't be left out on any of the sites.

**Comment by Sherlock21** [comment]
I will spell it out again for you:

The 3 colours in the logo just look a mess together. End
The blue in the name FreeReg does not go with the black in the name - there is insufficient contrast to make it distinctive, so it might as well just be all blue or all black.

**Comment by PatReynolds** [comment]
Personally (and I see differently out of my two eyes!) I think that It might be good to make the arrow point of the logo a bit brighter. Perhaps seeing all four logos together might be helpful (sorry, more wor).k

For accessibility, I don't think it matters if some viewers can't distinguish the blue of Free from the black of REG.  The important thing is, is the blue of the link distinctive?

**Comment by SteveBiggs** [comment]
As Alison says, screens and eyes vary so there will be different opinions.
The most important point is that the text (link) has a good contrast
against the white background and dark blue will work much better than the
existing brown (or light teal). Of course the dark blue will not work
against a black background, but I would suggest white text should always be
used against black.

As Pat says, it would be good to see the four (new) logos side by side.

Steve


Stephen Biggs
FreeREG Chairman

**Comment by AlOneill** [comment]
There is an inherent dilemma in choosing colours that work for a range of eyes/screens: it is impossible to find a colour that is AAA on white and yet still has acceptable contrast with the surrounding text, even if that text is made black, rather than our current dark grey. With testing by people, the link text being bold may be sufficient to earn AAA status.

The blue used here is AA on white (though close to AAA, with a contrast ratio of 6.87:1, whereas AAA requires 7.1:1 or better). I have changed the text (not the logo text) colour to black to obtain the best contrast — our current dark grey has only about half the contrast of black against the blue.

![freecen__icon_and_colour_testing](https://user-images.githubusercontent.com/14852554/32183012-04d20d6c-bd90-11e7-8f42-dbe94412e5da.png)

Other blues might be equally suitable — I will need to check out the numbers and compare with the other logos. However, there is *no colour* that would provide a *bigger* (calculated) contrast with black. Blues are good in that they are minimally changed by the most common forms of colour-blindness (red/green).

@PatReynolds I will experiment with the shade/tint of blue in the logo to see if that makes an appreciable difference. The colours in the 'arrow head' or 'apex block' (depending on how whether one sees the shape as flat or as 3 cubes at a jaunty angle) are a blend (can't think of the correct term just now) which I would be reluctant to tamper with until we are in agreement over the colours to be used in actual text. I hope that makes sense.

@Sherlock21 Is there enough difference for you between the blue and the black in the pure text part of the image, the sentences with links?

**Comment by AlOneill** [comment]
I've adjusted the tint of the blue cube so that the saturation value matches more closely that of the current brown, and the black upper face of the apex cube is allowed to pop.

Then I adjusted the purple and magenta to offer the best contrast possible with black text. Finally, I adjusted the other 2 logos so that the saturation values were in better balance.

![FreeCen__Icon_and_colour_testing.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d69640ab53cf95274218702608ac3e62baf72dac56720f084d52be011a001ea9aacd39aca43973df0f5ab8d8645b7cc63a43a9b8801fbf00b9758b4cd3a4a0980e91b6697abad2c51a7c0c0f0a88f85734a59942cb51f54de44456a316242e.png)

**Comment by SteveBiggs** [comment]
They look good to me Alison. Well done.

Steve


Stephen Biggs
FreeREG Chairman

**Comment by AlOneill** [comment]
Thanks, Steve. 

When I looked at the logos in alpha order, I realised that the CEN and BMD colours were too close to each other — re-working is now in progress!

**Comment by AlOneill** [comment]
Here is the re-working with better colour separation. Other details as above.

![FreeCen__Icon_and_colour_testing.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d69640ab53cf95274218702608ac3e62baf72dac56720f084d52be011a001ea9aacd39aca43973df0f5ab8d8645b7cc63a43a9b8801fbf00b9758b4cd3a4a0980e91b6697abad2c51a7c0c0f0a8bff5734a59942cc5ff64ce24e5dac14242e.png)

**Comment by AlOneill** [comment]
Thank you to all who have commented so far. Do continue to say what you think as we will likely be living with these colours for quite a while!

There is one more aspect to ponder: the colour of the **main menu** for each project.

In order to be consistent, I suggest that we use one of these schemes:

* Teal for all 3 projects, or
* Each project to use its accent colour (the colour of the word 'Free' in its logo)

A mixture of approaches — some Teal, others accent colour, runs the risk of appearing somewhat ad hoc, unplanned, or "make do".

**Comment by SteveBiggs** [comment]
I would suggest we use the accent colour. I assume this will be used for
all action buttons too?

btw, I like the way you've used more transparent versions of the accent
colour for the logo to deal with the contrast issue that EricB raised.

Steve

**Comment by AlOneill** [comment]
@SteveBiggs Yes, accent/link colour for the buttons. Potentially disorientating otherwise.

**Comment by Sherlock21** [comment]
Could you please do an example of applying the proposed Accent Colour to 
A) a page full of Action buttons 
B) a page with only one cation button in it 

-in Steve's question above.

This might well make a difference to my view.
following suggested pages have (multiple actions buttons - each file name is an action link)
and single action button is Submit.
![multiple actions buttones on a page](https://user-images.githubusercontent.com/9368704/32290769-f9687016-bf32-11e7-8d69-8a5b6c57ed9e.jpg)
![single action button](https://user-images.githubusercontent.com/9368704/32290785-06621042-bf33-11e7-9bca-2274edcc9b8e.jpg)

**Comment by PatReynolds** [comment]
FreeBMD seems to have changed significantly - snip of current colour:
![image](https://user-images.githubusercontent.com/6338822/32336738-01442734-bfe8-11e7-841d-955beecb7b2a.png)
I thought FreeBMD was the one suite of colours that was fine, AA-wise?

**Comment by AlOneill** [comment]
@Sherlock21 A single button, such as a Submit, will stand out just fine and should be more legible than it is now.

For your first example, all the teal on the page would be replaced by the blue of 'Free', except for the muted blue in the logo. If a whole bunch of buttons is just too much blue, then with links becoming more legible, perhaps it would be better to present a simple list of links: buttons do not stack particularly nicely, whatever the colour. There *are* other possibilities, but each would involve changes that would have to wait until the main accessibility changes are securely in place.

A demo page would take a while to set up as I can only work locally for now: it may have to wait until I have access to a development environment. In the meantime, a link and some buttons:

![FreeCen__Icon_and_colour_testing.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d69640ab53cf95274218702608ac3e62baf72dac56720f084d52be011a001ea9aacd39aca43973df0f5ab8d8645b7cc63a43a9b8801fbf00b9758b4cd3a4a0980e91b6697abad2c51a7c0c0f0a88f75734a59942ce5cf749e84451ac13242e.png)

**Comment by Sherlock21** [comment]
Ok, Ali, I accept that doing a 'real' mock up. but what you have done demonstrates the proposal well.

Not if this is what is proposed, I find this blue is TOO STRONG and dazzling. it is the Same with either of the 2 fonts.

I would not want this change
In fact I don't see why the need to change these sort of action button. After all they are only used by CC;s and MGRs so that is 50 users at best, and some, only by Steve & Myself.

Same applies to the bread crumbs.

I can ignore her logo colour, because its only seen by me at logon andI don't actually have to use it as an Action button.

SO please don't ripple thought these colour changes into the areas that are used by the Volunteers without getting 100 % support

**Comment by suffolkroots** [comment]
>Sherlock21 said--I would not want this change
In fact I don't see why the need to change these sort of action button. After all they are only used by CC;s and MGRs so that is 50 users at best, and some, only by Steve & Myself.

I agree---what CCs need is data, not activities with a paintbox. What use is a pretty site if transcribing grinds to a halt?

**Comment by AlOneill** [comment]
Pat & EricB — you are both right (doh!). I adjusted the colours by starting in the wrong place, then went in the wrong direction!! Working now on a better set of adjustments. BTW, breadcrumbs need not be blue on FR — (accessible) Teal may well be a better choice across all 3 sites.

@suffolkroots — the changes are not to make the sites "pretty", but to allow some people (including potential volunteers) to access the sites at all!  A volunteer who is *not* a transcriber may well have limited eyesight, whereas a potential transcriber may not be able to use a pointing device, for example. At some point, Researchers will be invited to be Members. However, your use of the phrase, "activities with a paintbox", appears to trivialise what we are doing here and as such I can't but take exception to it.

**Comment by suffolkroots** [comment]
AlOneill----having read the accessibility inspection report I am fully aware of the issues needing attention. However, CCs raised many of these issues through feedback re the first incarnation of FR. Had these been taken seriously at the time we might not be in this position now. On a personal level, as someone with slightly compromised vision I find the bright blue buttons dazzling and hurtful to my eyes.

**Comment by AlOneill** [comment]
@suffolkroots Thank you for expanding. I apologise for my rant — you and EricB are quite right about that bright blue: it is quite unsuitable: I don't know what I was thinking.

**Comment by AlOneill** [comment]
Proper colours restored. 

Are there any issues with the "Free" / link colours as proposed?

The colour for each topmost block in the logos is exactly the same as the background colour in the focus styling — however, visually there are marked differences. Do we want to lighten the focus colours to visually match the logos or darken the logo colours to visually match the focus styling? Or ...

![FreeCen__Icon_and_colour_testing.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46ce869f26a186a7b0d69640ab53cf95274218702608ac3e62baf72dac56720f084d52be011a001ea9aacd39aca43973df0f5ab8d8645b7cc63a43a9b8801fbf00b9758b4cd3a4a0980e91b6697abad2c51a7c0c0f0a88f85734a59942c059f643e94d5da411242e.png)

**Comment by Sherlock21** [comment]
Ali - what you propose in the last post above is fine by me. I have no greater problem with this than I do with what we have in Production today. And historically we have managed with very well.
I to do have eyesight problems ( as well as the typos!) but I manage with the present shade of teal for EVERY Acion button  that I need to use.
I for one would much prefer that you  actually just STOP at the "Free/ link part of the proposal and don't go further.
Indeed, I would be at the point of considering my position were you to run through the whole site  changing colours.

**Comment by AlOneill** [comment]
@Sherlock21 So, I will take that as a vote for **Teal main nav and (default) buttons** across all sites.

**Comment by SteveBiggs** [comment]
As I'm not sight impaired, it's hard for me to comment on what works best for people who are. I'm happy with the latest proposed colours and also with the nav bar and buttons remaining teal. The only thing I feel strongly about is that the current teal links are very hard to distinguish:

![image](https://user-images.githubusercontent.com/25303607/32414109-b972ce6a-c217-11e7-848d-84f5756141eb.png)
so replacing these with the bold blue is good.

(I've just noticed there is a typo - " ...use the this link .....")

**Comment by Sherlock21** [comment]
Which actual buttons / links are you referring to please, Steve?
- an example so I  understand before commenting further if you would.

**Comment by Sherlock21** [comment]
Ali -re your last post, I can't comment on the other sites, as I don't have access ( not any role) there except as a researcher.

**Comment by suffolkroots** [comment]
Not sure which links you mean Steve---there is a link in your post but it doesn't lead to an example----

**Comment by SteveBiggs** [comment]
Nav bar and button (teal):
![image](https://user-images.githubusercontent.com/25303607/32414845-1d1eaf88-c227-11e7-8736-61b0315b0826.png)

Text link (blue):
![image](https://user-images.githubusercontent.com/25303607/32414833-fbe80062-c226-11e7-9840-ebee59ba9680.png)

**Comment by SteveBiggs** [comment]
Not sure why the images are not showing in email, but If you view it on
GitHub
<https://github.com/FreeUKGen/MyopicVicar/issues/931#issuecomment-341970337>
you'll
see them

Steve


Stephen Biggs
FreeREG Chairman

**Comment by suffolkroots** [comment]
Thanks Steve. Not sure whether the text link you mention is needed anyway, as there is a very clear VOLUNTEER in the Navigation bar

**Comment by Sherlock21** [comment]
logging on to Github and this topic, then click on the "A link with FreeREG styling" 3 posts above from here, goes nowhere either for me.

**Comment by SteveBiggs** [comment]
Eric, it is just an image showing what inline text links would look like with this colour scheme. i.e. they would be blue and in bold type, so much more obvious than the current light teal of 8 posts above here.

We are debating what colour scheme to use for buttons and links.

**Comment by Sherlock21** [comment]
Thank you, Steve. 

Are you saying:  there was not a real example at the end of your link, showing what your are wanting to change form Teal, to blue & bold?

If it is ALL of what I included as my input to the debate ( under the time stamp: 4 days ago) then all I can say is that my comments there, all still stand. If that is what you area leo saying you favour changing, please say so.

IF I am on the wrong track, then please say my typical examples will all stay as TEAL across the FR application.

**Comment by SteveBiggs** [comment]
I am clearly not explaining this very well.

The image IS the example, i.e the text "FreeREG Styling" in bold blue is an example of what a link in text would look like. It's not a real clickable link, but shows the styling of what one would look like.

All buttons and the menu header bar would remain the current Teal colour (as the other image shows)

**Comment by Sherlock21** [comment]
Ahhhhhh.

So I get that now! Thank you.

**Comment by AlOneill** [comment]
Thank you all for your feedback and patience! Taking on board the comments re 'brightness', I'll tweak the palette to work as AA without resorting to black text — black on white would be more tiring to read (for most people) than dark grey on white.  (And maybe devise a more muted version as an alternative — no promises.)

So, please do *not* take the above colours as final in any sense.

**Comment by AlOneill** [comment]
The scrum 2 days ago decided to go with the following colour scheme for FreeREG:

![Composite__Icon_and_colour_testing.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46cb9b97338d90a09bec807c8d5eff9a164729771607ac277f90f117ab476815060119be5d4a1f06a3a3dc78e2a436628f5f5ebe8038567dc23511abea871fbd01ba21881a85b5ea9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec959f349e74d51ac173066f43b.png)

For those who work with button-heavy pages, this is how they will look *with the current markup*. Note that a little extra vertical space has been added between rows of buttons to prevent the "buttons crashing" effect, and make a page more comfortable to read than at present.

![Composite__Icon_and_colour_testing.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46cb9b97338d90a09bec807c8d5eff9a164729771607ac277f90f117ab476815060119be5d4a1f06a3a3dc78e2a436628f5f5ebe8038567dc23511abea871fbd01ba21881a85b5ea9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec959f349e7495ca7133f64f43b.png)

(Proper versions of all the updated logos will be available in due course for those who need them.)

**Comment by Sherlock21** [comment]
as one of the awkward ones on this topic, I must say: I am content with this. Thank you.

**Comment by suffolkroots** [comment]
Colour scheme looks fine Alison. Thanks

**Comment by AlOneill** [comment]
@Sherlock21 Glad this works for you! Remember that you are not looking at an actual page, but rather an *image* of a page: on a real page the bleeding effect may well disappear. Can we review the issue once you are able to test an actual page in a browser?

@suffolkroots Sound — you're welcome!

**Comment by SteveBiggs** [comment]
@AlOneill when do you expect it to be available to view on an actual page?

**Comment by Sherlock21** [comment]
Ok, review on T3 please?

**Comment by AlOneill** [comment]
@SteveBiggs @Sherlock21 I'm waiting to get set up on Cloud9. Then there are quite a few changes to make and test. Then a proper Developer will want to test it out, before everyone gets to take a peek on the development site. Might make it before Xmas, if all goes well, but don't hold your breath!

**Comment by AlOneill** [comment]
Of course I can let you *all* see the buttons on test3 (doh!) — plus a couple of variations to consider, especially if you find the current small buttons difficult to read. (Note that the buttons are all dummies, with no hover/focus state on the new ones.)

There is now a demo page at:
https://test3.freereg.org.uk/cms//sandbox-for-alison/

**Comment by Sherlock21** [comment]
Thank you  Alison

Option 1 font size will be OK. - there is no significant bleeding of the coulour intothe white

That way the same number of file names will be accommodated across the page ( so there will be no increase in the rows of file names in the header _ which in some place/ churches, its qute extensive already!

SO I am fine with just the colour change.

Thanks again,
Eric B

**Comment by AlOneill** [comment]
@Sherlock21 Thank you — noted.

If anyone else thinks they could have problems with reading our proposed small buttons, please take a look at the demo page (back 2 posts) and comment on your preferences. Thanks.

**Comment by PatReynolds** [comment]
I have updated priority to reflect dependency - needed by FreeBMD2 which has potential large economic result.

**Comment by Captainkirkdawson** [comment]
See systemwide #65

**Comment by PatReynolds** [comment]
@PatReynolds to add link to current document in the project description.

Deployment process (following asset pipeline changes) to be decided.

**Comment by PatReynolds** [comment]
Demo page no longer at https://test3.freereg.org.uk/cms//sandbox-for-alison/ (also tried https://test2.freereg.org.uk/cms//sandbox-for-alison/ and not there, either. @AlOneill is this still the demo page, and if so, where is it, please?

**Comment by AlOneill** [comment]
@PatReynolds Those pages were obliterated many moons ago in an early sync operation from live to test.

What would you like to be on them?

**Comment by PatReynolds** [comment]
Hi @AlOneill after writing that, I found the .png which I've put in the issue description above.  If this isn't the current (and I think final) change, could you update the description, please?

**Comment by AlOneill** [comment]
@PatReynolds No, those are **not** the final colours!! Not sure what you mean by "update the description" — I will look out the equivalent PNG file (on my computer) with the final colours, and then … ?

**Comment by AlOneill** [comment]
Have re-worked social media icons to play nicely on light (main menu) and dark (footer) backgrounds — previous edits were awkward and did not work well in footer.

**Comment by Captainkirkdawson** [comment]
@AlOneill @PatReynolds is there a  conclusion somewhere of the colour schemes that have been agreed?

**Comment by Captainkirkdawson** [comment]
Being dealt with as part of systemwide 71. At that point we should review this to see if all aspects have been addressed.
