### ISSUE TITLE
A file with LESS data rows and some rows starting with * in the Person Name get dropped in a Reload

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#937]
There was already a version of my file WRYSEDBU1.csv in Production.
I uploaded a revised file that had less data rows ( called: uploaded) and noticed  when doing an online Browse this Batch, there were some rows with just the County/ Place / Church populated.
So I downloaded the batch from the Server. ( file is called download - see last line of comment box ) and started to compare the two files.
Data rows 3 and 4 are missing in "download"
Data rows 9 and 10 are missing in "download"
Data row 16 is missing in "download'
- I gave up then because its too difficult!

then,
BUT at the end of the downloaded file when viewed as a spreadsheet, row numbers 1122 to 1143 show fields A,B and C but NO data! and the 2 rows after that ( 1144 and 1145)  show data that was at row 725 and 726 in the input file. - Now I know that it had been said previously that the Downloaded file will not be inthe same data order as the input file, but its impossibe to compare properly when they come out like this! 

The file called "upload" works fine in Test Region both as a first time upload, and also using it as a Reload.

I can't attach the 2 necessary csv files, so please email me and i will attach to your email

**Comment by Captainkirkdawson** [comment]
FR is a record not a file based system.
There is no order in the database hence a downloaded file may well have a different order than the original.
The reportedly missing records are there in the downloaded file just in a different position.
The file in question was replaced 9 times on the 9th of September and 7 times on the 10th of September. The "extra" blank records were first added on the 9th according to the attic.  Hence no issues are apparent
