### ISSUE TITLE
Transcriber's email address on batches is not in step with that on their profile.

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#938]

**Comment by edickens** [comment]
It might never be.  The batch is what is entered when they uploaded
    the batch and entered in the header.  The Profile is what they have
    entered when they registered and kept up-to-date.  It is best this
    way because if we lose contact with someone, we can take control of
    the UserID while still retaining the original email address in the
    headers.
    
    Any correspondence should go to the email address in the Profile as
    that should be the latest.  I will remind transcribers to keep this
    up-to-date in tomorrow's four weekly newsletter.  E
    
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Transcriber's email address on batches is not in step with that on their profile. (#938)"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/93
