### ISSUE TITLE
Adjust place_cache rebuild

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#941]
Currently `refresh_all` in `place_cache` that destroys all and then rebuilds
This has significant impact on performance when run
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/models/place_cache.rb#L1-L33
 We currently have a rake task
https://github.com/FreeUKGen/MyopicVicar/blob/master/lib/tasks/foo.rake#L203-L206 that inititiates the `refresh_all`
Requirement:
The `refresh_all` cycles through the counties destroying each in turn and then rebuilds. 
We need to add an option to select just one county to refresh

**Comment by israelriibeiro** [comment]
@Captainkirkdawson , did you mean this way?   [refresh_places_cache](https://github.com/FreeUKGen/MyopicVicar/blob/update_cache_by_county/lib/tasks/foo.rake#L203-L210)

It can be used to one county or more, like this:

rake foo:refresh_places_cache['NFK','HEF']  

Or, if want to update everything, you can do this:

rake foo:refresh_places_cache

**Comment by Captainkirkdawson** [comment]
Yes extactly
But in addition the refresh all cycles through the counties doing the specific county destruction when it is rebuilding  rather that all at once at the start

**Comment by israelriibeiro** [comment]
@Captainkirkdawson , does this issue need more adjustments?

**Comment by Captainkirkdawson** [comment]
The adjustment to the rake is fine but we need to adjust the refresh_all method do that .
If you look at the refresh_all code in place_cache
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/models/place_cache.rb#L1-L33
There is a use of destroy_all and then a rebuild. 
Requirement:
The refresh_all cycles through the counties d**estroying each in turn** and then rebuilds. 
We need to add an option to select just one county to refresh

**Comment by israelriibeiro** [comment]
@Captainkirkdawson , take a look at it, please: [refresh_all](https://github.com/FreeUKGen/MyopicVicar/blob/update_cache_by_county/app/models/place_cache.rb#L21-L30) .

**Comment by Captainkirkdawson** [comment]
Israel
Since self.refresh(county) deletes the cache for a county
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/models/place_cache.rb#L6-L19
Could we not simply remove the destroy all in
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/models/place_cache.rb#L21-L26

K

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by israelriibeiro** [comment]
Did that now: [refresh_all](https://github.com/FreeUKGen/MyopicVicar/blob/update_cache_by_county/app/models/place_cache.rb#L21-L30)

**Comment by Sherlock21** [comment]
Are you guys working in T3 or in Production please?

inT3 i have an issue with reloading a changed batch AND also a new batch.

both cases i get the email saying the processing is done correctly, but the batch does not appear in the Place/ Church -

2 fails out of 2 (differnt) tries

Eric B

**Comment by Captainkirkdawson** [comment]
Neither T3 or in Production for this story at this time


Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1
