### ISSUE TITLE
Mongodb Wired Tiger Storage Engine

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#942]
We currently use the current MMAPv1 storage engine of Mongodb that permits collection level concurrency control. This is an improvement on the database level concurrency control used until a month ago.
However Mongodb has introduced a new storage engine (Wired Tiger) that permits document level concurrency control that is stated to give a 7-10 times improvement in write performance.
This would have little benefit for actual searches BUT could be of significant benefit when we are updating the database at the same time as searching. Fir the past 3 months we have been  (and continue) to update the database with new emendations and witness support. We will; also soon be updating the database to support the new search date structure.
We should evaluate the benefit/cost implications of migrating to the new storage engine

**Comment by benwbrum** [comment]
I really, really like this idea.  It is depressing indeed to realize that
we'll need to wait on the upgrade we started more than a month ago to
finish before we can start the next upgrade, so solving write performance
would be wonderful.

**Comment by dougkdev** [comment]
I also like this idea.  We briefly discussed WiredTiger many months ago and
decided that it might still be a little immature and unstable at that time,
but it has become the default storage engine for current versions of
mongodb now, so probably fairly stable at this point.

**Comment by edickens** [comment]
I hope it won't delay V1.5.  E

**Comment by dougkdev** [comment]
A very beneficial side-effect of faster writes without locking the entire
collection is that it may reduce the amount of throttling required during
processing, because search performance should not degrade as much while
writes are happening.  Besides significantly speeding up the complete
database updates (like the one currently happening and the one that will
need to happen for the updated search date structure), this should also
speed up both nightly processing and "as soon as possible" processing.

**Comment by Captainkirkdawson** [comment]
From:
http://stackoverflow.com/questions/37985134/how-to-choose-from-mmapv1-wiredtiger-or-in-memory-storageengine-for-mongodb

MongoDB WiredTiger  provides more granular document-level concurrency control, delivering between 7x and 10x greater throughput for most write-intensive applications, while maintaining predictable low latency.

The MMAPv1 storage engine uses a process called “record allocation” to grab disk space for document storage. All records are contiguously located on disk, and when a document becomes larger than the allocated record, it must allocate a new record. New allocations require moving a document and updating all indexes that refer to the document, which takes more time than in-place updates and leads to storage fragmentation. Furthermore, MMAPv1 in it’s current iterations usually leads to high space utilization on your file system due to over-allocation of record space and it’s lack of support for compression. As mentioned previously, a storage engine’s locking scheme is one of the most important factors in overall database performance. MMAPv1 has collection-level locking – meaning only one insert, update or delete operation can use a collection at a time. This type of locking scheme creates a very common scenario in concurrent workloads, where update/delete/insert operations are always waiting for the operation(s) in front of them to complete. Furthermore, oftentimes those operations are flowing in more quickly than they can be completed in serial fashion by the storage engine. To put it in context, imagine a giant supermarket on Sunday afternoon that only has one checkout line open: plenty of customers, but low throughput!
Everyone has different requirements, but for most cases WiredTiger would be ideal choice the fact that it makes atomic operations on document level and not collection level has a great advantage, you simply can't beat that.

**Comment by Captainkirkdawson** [comment]
From
http://www.developer.com/db/tips-for-mongodb-wiredtiger-performance-tuning.html
The WiredTiger storage engine is designed for modern multicore architectures and is better able to leverage multiple cores than MMAPv1.
WiredTiger uses prefix compression to store Indexes—identical prefixes are stored only once. This results in smaller indexes and consequently results in lower RAM usage for indexes.
Working with WiredTiger Cache Size
The size of the cache is the single most important knob for WiredTiger. By default, MongoDB 3.x reserves 50% (60% in 3.2) of the available memory for its data cache. Although the default works for most applications, it is worthwhile to try tuning this number to achieve the best possible performance for your application. The size of the cache should be big enough to hold the working set of your application.
MongoDB also needs additional memory outside of this cache for aggregations, sorting, connection management, and the like, so it is important to make sure you leave MongoDB with enough memory to do its work. If not, there is a chance MongoDB can get killed by the OS Out of memory (OOM) killer.

The first step is to understand the usage of your cache with the default settings. Use the following command to get your cache usage statistics:

db.serverStatus().wiredTiger.cache

Controlling WiredTiger Read and Write Tickets
WiredTiger uses tickets to control the number of read/write operations simultaneously processed by the storage engine. The default value is 128 and works well for most cases. If the number of tickets falls to 0, all subsequent operations are queued, waiting for tickets. Long-running operations might cause the number of tickets available to decrease, reducing the concurrency of your system. For example, if your read tickets are decreasing, there is a good chance that there are a number of long running unindexed operations. If you would like to find out which operations are slow, there are third-party tools available. You can tune your tickets up/down depending on the needs of your system and determine the performance impact.

You can check the usage of your tickets by using the following command:

db.serverStatus().wiredTiger.concurrentTransactions

**Comment by Captainkirkdawson** [comment]
Upgrading to wired tiger is covered in
https://docs.mongodb.com/v3.0/release-notes/3.0-upgrade/
The process is different between standalone (test3) and replica (production)
In MongoDB 3.0, replica sets can have members with different storage engines. As such, you can update members to use the WiredTiger storage engine in a rolling manner. Before changing all the members to use WiredTiger, you may prefer to run with mixed storage engines for some period. However, performance can vary according to workload. To update all members of the replica set to use WiredTiger, update the secondary members first. Then step down the primary, and update the stepped-down member.

**Comment by Captainkirkdawson** [comment]
Have successfully upgraded my development server to wired tiger

**Comment by Captainkirkdawson** [comment]
Interesting. On my development server the database and its indexes are only 10% of the size of the MMAP version!!!!!!!!!!!!.

**Comment by benwbrum** [comment]
That's certainly encouraging!

**Comment by Captainkirkdawson** [comment]
Notes on the process for changing storage engine on standalone system arw at
http://www.freereg.org.uk/cms/system-documents/changing-storage-engines

**Comment by Captainkirkdawson** [comment]
Have confirmed that searches continue to perform nicely with a flat out running of the new search record update code.

**Comment by Captainkirkdawson** [comment]
brazza now running with wired_tiger. Database, including indexes, is 32GB cf 300GB.

Conversion took 7 hrs.

**Comment by Captainkirkdawson** [comment]
Will wait until FreeBMD rebuild, which starts Monday, completes before converting the other servers

**Comment by Captainkirkdawson** [comment]
Awaiting a review of the brazza configuration by Lemon before moving forward to other servers

**Comment by Captainkirkdawson** [comment]
Deploying to saki

**Comment by Captainkirkdawson** [comment]
Saki running on wired tiger; 5 hrs
Preparing Howler

**Comment by Captainkirkdawson** [comment]
Howler is complete.

**Comment by Captainkirkdawson** [comment]
Working on colobus

**Comment by Captainkirkdawson** [comment]
colobus is complete
