### ISSUE TITLE
24? Create Multi Application MyopicVicar

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#943]
As Doug has noted in #856 

We have never merged freecen_parsing back into master, but we fairly regularly merge master into freecen_parsing. While freecen_parsing is app-aware, master is not. All of the changes we are making to the assets now and also the recent changes that were made (for example 27 July when assets were moved around and reorganized) are being made in the directories things get copied into instead of where they are copied from (in the freecen_parsing branch, that is). If we set up master in a similar manner as the freecen_parsing branch, it would be much easier to keep things in sync between the projects and not clobber or lose changes when merging from branch to branch.

Merging back in would take time and effort from all three of us (Kirk, me, Ben), but it may be wise to do so at some point

**Comment by benwbrum** [comment]
There are three major phases:

* Merge master into freecen_parsing
* Merge freecen_parsing (+master) back into master
* Add modality support to FreeREG-specific parts of master

**Comment by Captainkirkdawson** [comment]
Phases 1 and 2 have been completed. 
Phase 1 master has been merged into freecen_parsing by @benwbrum , tested and bugs fixed by myself. Brought into step with the current master yet again. It is now running on test2 cen. Have recommended that the merged branch replace freecen_parsing in production and  become the base code for CEN Development. Master should be merged into the merged branch every 2 weeks, These 2 steps are essential  to avoid future divergence and having to do this all again. 
Phase 2 has been done into  a test branch there are no conflicts. However the merged code does not run the REG application correctly. It needs modularity added to make it respond correctly. Given  this is for a future release and its assignment to @benwbrum  I propose to stop here.

**Comment by AlOneill** [comment]
How will this affect the SCSS changes I'm making on Cloud9 in freecen_parsing? Some of the SCSS/CSS and associated ERB files are app-aware already, the remainder I will be making app-aware as soon as I can get my head around it.

**Comment by Captainkirkdawson** [comment]
In my mind you should switch to the master-into-parsing branch and make you changes there; however it really depends upon when that branch will be deployed. Regardless if you make your changes into a specific branch we can always pull that into subsequent code bases.
As for SCSS it is not clear to me that we have ever used the SCSS. When we set things up 4 years ago I think we just used the css

**Comment by Captainkirkdawson** [comment]
Following discussions with @benwbrum I will commence the back port.
Step 1 will be to move the application initialization back into master

**Comment by AlOneill** [comment]
@Captainkirkdawson Thanks. Am making changes to SCSS because it would be bonkers to edit the CSS: both variables (colours) and some style definitions (which colour combinations are allowed for islands, for example) needed either redefining or dropping altogether. This is done.

The exceptions are the CSS image files, the 3 that insert logos and similar images: these I am editing directly— actually 9 files, 3 for each project. This part is in progress.

**Comment by Captainkirkdawson** [comment]
Question is this version 2 milestone or earlier?

**Comment by benwbrum** [comment]
Still in progress.  Index set-ups need to be made bi-modal (see sub-stories).
