### ISSUE TITLE
WinFreeREG needs to only select Places with Churches

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#944]
If a batch is created for a Place with no Church already set up, it will get rejected.  So when downloading the list of Place names for a transcriber to choose, it needs to be just those Places which have Churches.

**Comment by EmJayFry** [comment]
Change doesn't so much affect WinFreeREG as  one of the server functions that it accesses in transreg_places_controller.rb. Request to server can stay the same bur the response needs to filter out those places that don't have at least one church set up or it.

**Comment by edickens** [comment]
Mike,
    
    Have had a night to think about it. I think it would be better if
    WinFreeREG were to put up a Warning, and stop further transcribing,
    if someone chooses a Place with no Church.  This is because someone
    may (and it happens regularly) have found some images to transcribe
    and made a start on it.  They should have told the CC beforehand to
    create the Church, but if they have not, then WinFreeREG should tell
    them to get the Church created before they can go any further.
    
    The complaint wasn't that you had downloaded all places, but that
    WinFreeREG allows the transcriber to create a file which is then
    rejected.
    
    Thanks,
    
    Eric
    
    On 21/09/2016 15:58, Mike wrote:
    
    
      Change doesn't so much affect WinFreeREG as one of the server
        functions that it accesses in transreg_places_controller.rb.
        Request to server can stay the same bur the response needs to
        filter out those places that don't have at least one church set
        up or it.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@EmJayFry in #944: Change doesn't so much affect WinFreeREG as  one of the server functions that it accesses in transreg_places_controller.rb. Request to server can stay the same bur the response needs to filter out those places that don't have at least one church set up or it."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/944#issuecomment-248638691"}}}

**Comment by EmJayFry** [comment]
On 22 Sep 2016 09:40, Eric Dickens wrote:

> The complaint wasn't that you had downloaded all places, but that
> WinFreeREG allows the transcriber to create a file which is then
> rejected.

Not any more! No Church - no start of file.

As for existing files, if it's a place with no church then the user will no 
longer be able to edit the File Header Details. They'll still be able to edit 
the data, but nothing to do with the header records.

-- 
Regards,
Mike Fry (Jhb)

**Comment by edickens** [comment]
Brilliant.  Should do nicely.
    
    E
    
    On 22/09/2016 12:33, Mike wrote:
    
    On 22 Sep 2016 09:40, Eric Dickens wrote:
      
      > The complaint wasn't that you had downloaded all places, but
      that
      > WinFreeREG allows the transcriber to create a file which is
      then
      > rejected.
      
      Not any more! No Church - no start of file.
      
      As for existing files, if it's a place with no church then the
      user will no 
      longer be able to edit the File Header Details. They'll still be
      able to edit 
      the data, but nothing to do with the header records.
      
      -- 
      Regards,
      Mike Fry (Jhb)
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@EmJayFry in #944: On 22 Sep 2016 09:40, Eric Dickens wrote:\n\n\u003e The complaint wasn't that you had downloaded all places, but that\n\u003e WinFreeREG allows the transcriber to create a file which is then\n\u003e rejected.\n\nNot any more! No Church - no start of file.\n\nAs for existing files, if it's a place with no church then the user will no \nlonger be able to edit the File Header Details. They'll still be able to edit \nthe data, but nothing to do with the header records.\n\n-- \nRegards,\nMike Fry (Jhb)\n"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/944#issuecomment-248878080"}}}

**Comment by EmJayFry** [comment]
So! What do we do with this story? Close it?

**Comment by edickens** [comment]
I'd say yes, but your change has not been tested.  E
    
      On 22/09/2016 13:26, Mike wrote:
    
    
      So! What do we do with this story? Close it?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@EmJayFry in #944: So! What do we do with this story? Close it?"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/944#issuecomment-248889182"}}}

**Comment by EmJayFry** [comment]
On 22 Sep 2016 14:53, Eric Dickens wrote:

> I'd say yes, but your change has not been tested.  E
>

Can't close it. I've found another wrinkle.

If the existing file is for a non-existent place, or a place that doesn't have a 
church, then the program behaves as I previously said: the user can't get to 
edit the file until the place/church conundrum is solved.

However, if the file is for a valid place/church combination, then the file can 
be edited and, it seems, can be reassigned to a place without a church. 
Impossible to assign it to a non-existent place since the place can only be 
selected from the list downloaded from FreeREG. But, an existent place with no 
church is a problem. Need to work out what to do.

-- 
Regards,
Mike Fry (Jhb)

**Comment by Captainkirkdawson** [comment]
Mike can you please confirm that you want transreg_places_controller.rb to only turn those Places that have one or more Churches defined?.

**Comment by EmJayFry** [comment]
On 22 Sep 2016 19:47, Kirk Dawson wrote:

> Mike can you please confirm that you want transreg_places_controller.rb to only
> turn those Places that have one or more Churches defined?.

Discussions with Eric (see the story) imply that it isn't necessary any more. 
Besides, I had already taken steps to

a) Prevent a new file being started if the place didn't have a church.
b) Prevent an existing file from being edited unless the place has a church.
c) Prevent an otherwise valid existing file from being changed to a place 
without a church.

So... No. I don't think we need that change.

-- 
Regards,
Mike Fry (Jhb)

**Comment by Captainkirkdawson** [comment]
TY; standing down
