### ISSUE TITLE
DAP -  review image of event if permitted

### ISSUE THREAD

**Issue by sean-wood** [FreeUKGen/MyopicVicar#948]

**Comment by edickens** [comment]
I think we should investigate if we can show researchers the images for 
checking purposes.  I would suggest that only those researchers (and 
others) who have registered and agreed to our T&C, which should include 
using the images for checking purposes, should have this facility.  It 
gives us an audit trail of who has looked at what.  E

**Comment by PatReynolds** [comment]
The getting of permissions is a separate story, but agree for this story: functionality should include allowing RegisteredResearchers to view, and could include audit trail of who has viewed the image.

**Comment by Sherlock21** [comment]
In my view, the DPA says: publish personal info only on a meed to know basis - and letting registered researchers see private emails addresses when the owner of that email address did not give their explicit agreement seems the wrong side of correct.

Eric B

**Comment by richpomfret** [comment]
Finetuning.

**Comment by Captainkirkdawson** [comment]
duplicate of #1279
