### ISSUE TITLE
RAP -  what registers are currently available and not being transcribed or being transcribed

### ISSUE THREAD

**Issue by sean-wood** [FreeUKGen/MyopicVicar#951]
See R1. https://docs.google.com/document/d/1LFHFFsjV-b44vWSR2amVWNs7JWtrVkSls_AjBi-7yNU/edit#

**Comment by edickens** [comment]
Not sure on this.  The transcriber needs to know.  But why the 
Researcher?  Researcher need the GAP report so that they know that they 
are not wasting their time.  E

**Comment by PatReynolds** [comment]
This is #11.  
Researchers need to know because they might volunteer to transcribe.

**Comment by Captainkirkdawson** [comment]
As part of the RAP a register could have many books and a book can have many chapters and a chapter can have many sections and a section many images. 
The skill level required to transcribe events is usually not at the register or book level but at a level below that. perhaps at the image level

**Comment by edickens** [comment]
Agreed. But it would be a batch of images grouped for one skill
    level.  Sometimes there are bad individual images due to damage to
    the book, but we can ignore that for skill level.
    
    I was hoping not to introduce any more levels, if at all possible. 
    So a Batch name could be WOR-Abberley-BA-1813-1857_Part 1.  This
    would be about 50 pages or 1000 entries.  I don't see any demand to
    put the whole register book back into one entry.  If the different
    parts are listed next to each other, that would do.  The year range
    here is the range of the register book, hence is in the batch name,
    but within the batch header would be the years covered by Part 1.
    
    Just a thought.  E
    
    On 06/10/2016 18:10, Kirk Dawson wrote:
    
      As part of the RAP a register could have many books and a book
        can have many chapters and a chapter can have many sections and
        a section many images. 
        The skill level required to transcribe events is usually not at
        the register or book level but at a level below that. perhaps at
        the image level
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #951: As part of the RAP a register could have many books and a book can have many chapters and a chapter can have many sections and a section many images. \nThe skill level required to transcribe events is usually not at the register or book level but at a level below that. perhaps at the image level"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/951#issuecomment-252027540"}}}

**Comment by Captainkirkdawson** [comment]
I currently have difficulty with seeing a batch in that light. A batch is a set of transcribed events. It certainly links to the images what were transcribed.
I had never thought of a batch as a set of un-transcribed events linked to images. It would need somewhat of a rethink of the the structure of the data model and changes to how WinFreeREG operates as well.  But it is certainly a change from what we discussed earlier and inconsistent with our current definitions. I would be worried to see batch names of the type suggested as these include fields of a batch in the name. That in itself is not a reason for its rejection.

**Comment by edickens** [comment]
Hi Kirk,
    
    I do agree.  I have difficulty getting my mind around the best way
    to bring it all together.  My problem is not so much with the
    Register Book and its parts, as the concept of a Batch.  This has
    arisen because of the files created in FR1 and not from the actual
    data.  If we were to get to online data entry, then the transcriber
    would just be adding entries to a Register Book, or part thereof.
    
    So what I have said as a Batch Name is really just descriptive text
    against a set of records.  The problem is how to define this set.
    
    E
    
      On 06/10/2016 19:27, Kirk Dawson wrote:
    
    
      I currently have difficulty with seeing a batch in that light.
        A batch is a set of transcribed events. It certainly links to
        the images what were transcribed.
        I had never thought of a batch as a set of un-transcribed events
        linked to images. It would need somewhat of a rethink of the the
        structure of the data model and changes to how WinFreeREG
        operates as well. But it is certainly a change from what we
        discussed earlier and inconsistent with our current definitions.
        I would be worried to see batch names of the type suggested as
        these include fields of a batch in the name. That in itself is
        not a reason for its rejection.
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #951: I currently have difficulty with seeing a batch in that light. A batch is a set of transcribed events. It certainly links to the images what were transcribed.\r\nI had never thought of a batch as a set of un-transcribed events linked to images. It would need somewhat of a rethink of the the structure of the data model and changes to how WinFreeREG operates as well.  But it is certainly a change from what we discussed earlier and inconsistent with our current definitions. I would be worried to see batch names of the type suggested as these include fields of a batch in the name. That in itself is not a reason for its rejection."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/951#issuecomment-252048387"}}}

**Comment by edickens** [comment]
When deciding what images we have that have not been transcribed, please ignore any Sets of images that are not BA, MA or BU.  There will be Sets for Banns and OD (Other Data) such as a description  of the Church, Vicars names and lists of families.  The OD Sets may not have a year range.  They are useful information, perhaps even to researchers, but they do not have any transcribable records.  E

**Comment by edickens** [comment]
Bev and Kirk,
When you start on this you may want to first of all list, selectable by county, those Places, Churches, Register Types (PCR) which do not have corresponding transcriptions.  This report will be longer than you think because the Image Server (IS) has a Register Type whereas many transcriptions do not and so are "Unspecified".  The County Coordinator (CC) will need to sort this out.  And to do that they will need to look at the RAP at the same time as the "Transcriptions", so will most likely want to print the RAP or download it as CSV, therefore an option to do this would be useful.
When planning how you are going to do this, and to avoid having to change what you do, the RAP will in due course need to compare the PCR on the IS to the Transcriptions by year range.  This is because there are many PCR where the easier images have been transcribed, but the older, Latin and poorer quality have not been done, even though we have the images.
Thanks  Eric

**Comment by edickens** [comment]
PS.  The RAP may take a lot of processing to produce, but it does not change very often.  Also, if it is available "As at yesterday" that will be fine.  So perhaps program it accordingly.

**Comment by Sherlock21** [comment]
In the case of  Management or a CC wanting a reasonably up to date overall view, then yes I agree with you about "yesterday's position' would be OK.

But if its a CC needing to check recent activities for example, they may well need a NOW for their own County, so they can allocate images now.  So would it not be practical to have two views: A single County view NOW, and a Global position Last Overnight?

**Comment by richpomfret** [comment]
For a later iteration.

**Comment by PatReynolds** [comment]
was #952, too.

**Comment by Captainkirkdawson** [comment]
Will focus in  on #953
