### ISSUE TITLE
RAP -  find out the date range of the events for each of those registers

### ISSUE THREAD

**Issue by sean-wood** [FreeUKGen/MyopicVicar#952]
See R2.
https://docs.google.com/document/d/1LFHFFsjV-b44vWSR2amVWNs7JWtrVkSls_AjBi-7yNU/edit#

**Comment by edickens** [comment]
This is a more complex issue.  We need the date range of each register 
book for validation.  It is also useful for when some dates are missing 
(see #799) and the search can show these records to the researcher if 
the register book range falls within the year range selected in the 
search.  E
