### ISSUE TITLE
RAP -  what registers are currently being transcribed and for which Place and Church.

### ISSUE THREAD

**Issue by sean-wood** [FreeUKGen/MyopicVicar#953]

**Comment by edickens** [comment]
Researcher?  Definitely the Coordinators and Transcribers to avoid 
duplication.  Also, for management, we need dates when entries were last 
uploaded to see if the transcriber has gone AWOL and the work needs to 
be given to someone else.  I know from my records that some transcribers 
have had work allocated to them for nearly two years. This creates a gap 
in the entries for a Church.  The Coordinators need to get as complete a 
set for a Church as soon as possible.  E

**Comment by Captainkirkdawson** [comment]
Bev is about to start work on the Researcher RAP 

The basic requirement that we stated in the overall RAP/DAP/GAP document was

Researcher needs to find out:
R1) what registers are currently available to FR and not being transcribed and for which Place and Church; 
R2) the date range of events for each of those register; 
R3) what registers are currently being transcribed and for which Place and Church; 
R4) the date range of events for each of those register.

These were initially storied in 951 and 953.

Would like to respond to this with respect to the Image Server where we can provide information based on the status information at the group level

I would like your thoughts on what we should be providing and to what level of detail.

My current plan would be to make the information available through the TRANSCRIPTIONS link on the main menu which display the DAP information

This link accesses and displays fields in the place, church and register collections that contain the information to be displayed using the freereg_content_controller. These fields are updated (actually recreated) nightly by the freereg_content rake task (Bev it is rake  freereg:calculate_freereg_content)

We would need to add specific fields in place, church and register to hold the new fields that we wish to display. We could add the RAP information to the current displays as a new block between the Information table on the place/church/register and before the number of transcriptions block. I would expect that this would simply be the date range of images currently being transcribed and  the date range of images  available for transcription. We could also add a button link to the contact_us system that says Volunteer to Transcribe.

**Comment by Captainkirkdawson** [comment]
Bev has coded a test piece on this at the register level. Not yet deployed anywhere but will discuss at the next scrum.
What is being proposed is outlined below.
![researcher.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fa9189268391aa87ecad01e81fe086264c22703d46f96925d6e62bbe4722585b574eab135d5f46fcf98828f3b63f26984019af80330b2b9b645bf9fa9015ad00b22a8a4a84bebe8b44c1ee3821ee8b9d02.JPG)

**Comment by edickens** [comment]
That is exactly how I see it.

**Comment by richpomfret** [comment]
Email should be tailored to syndicate coords.

**Comment by PatReynolds** [comment]
Should researchers be able to see RAP and GAP information on the same page?

**Comment by Captainkirkdawson** [comment]
Yes that was the plan

**Comment by PatReynolds** [comment]
Thanks, @Captainkirkdawson 

Suggestion: if we have images, but they are not being transcribed, suggest that the researcher volunteers.
Suggestion: if we do not have images, but they potentially exist, suggest that the researcher contact the Record Office or Church/other institution concerned and request that they let us have them.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  moving our email discussion to where it should be
I had originally proposed that the request to volunteer from a researcher on the RAP see example a view posts above would go to the SC. This will work fine for those images that are allocated to a syndicate. It does not work if the images are Unallocated.  I had suggested the CC.
You have suggested instead it go to the Volunteer coordinator. Technically this would work except we have no one identified with that role.
![volunteer_coordintor.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fe9b96368c97ac8afb8040ab52e2902048337c3b46ef696097ec22ba416f43554d4baf140b0e11f5f08d23a6b16e758a5e0bedd06e0a74c56b03b0aac04ee155e57dd205d0f4ae805ec2e83724e2898e4a381c001e88fc5d3db2d4.JPG)
You indicated we do have someone.

**Comment by SteveBiggs** [comment]
Yes Jo Summerfield, but because she is also a CC and SC, @Vino-S did some changes so that Jo gets the access to VC actions amc communications.

**Comment by Captainkirkdawson** [comment]
In which case what we were going to do is not going to work since whatever was done no longer uses the person_role definitions. 
Have no idea what was done and am reluctant to build customization upon customization as that will get us into real trouble when someone else takes over.
Hence I suggest we simply abandon any attempt to pass custom information along and simply add a volunteer button on the page

**Comment by PatReynolds** [comment]
Should go to the Volunteer Coordinator, as that is the route in for all other volunteers.

Could the problem be solved by the Volunteer Coordinator having a different email address (maybe even a standard one)?

**Comment by SteveBiggs** [comment]
@Vino-S created secondary roles sometime back and I thought she had consulted with Kirk, but perhaps not. Here is an excerpt from an email from Vino about it:

"I had updated the code yesterday. So as per our discussion:

Feedback => Steve
Website Problems => Steve
Genealogical => Eric
Enhancement => Steve
Thank-yous => Eric
General Comments => Eric
Volunteering questions => Jo 

In a order to avoid hard-coding. I had created a new field in UseridDetail model "secondary_role" which is an array so that a person can have multiple secondary roles. Following are the details
1. Eric's secondary_role: "genealogy_coordinator", "general_communication_coordinator", "publicity_coordinator"
2. Steve's secondary_role: "website_coordinator"
3. Jo' secondary_role: "volunteer_coordinator"

**Comment by Captainkirkdawson** [comment]
Thank you for pointing out the secondary_role. Yes we can use that.

It is unfortunate that when the secondary_role was introduced we did not at the same time introduce a display of that role and the ability to set it though the app. Will add a story for that.

**Comment by Captainkirkdawson** [comment]
@PatReynolds You said "Should go to the Volunteer Coordinator, as that is the route in for all other volunteers." I am afraid I do not understand. Do all volunteers now go to the volunteer coordinator?  Or just those with a question about transcribing?

**Comment by Captainkirkdawson** [comment]
Example of latest version http://www16.freereg.org.uk/freereg_contents/5811a440f493fdadb86b2296/show_register

**Comment by PatReynolds** [comment]
Looking good!  I'm assuming only a few lines of 'available/being transcribed is because more have to be added.

You were right about the volunteering pathway!

**Comment by edickens** [comment]
Is there a higher level?  My thoughts are that someone looking for work would not want to look at every place but start by looking at the county where it would say "There are some places with untranscribed images", then they would look at the list of places, again marking those with untranscribed images.  After that they would look at this RAP screen and choose what to transcribe.

**Comment by Sherlock21** [comment]
I agree with Eric D's point above. Overview per County, then drill down.

**Comment by Captainkirkdawson** [comment]
Was not aware this was for volunteer recruitment! The specification was to report on progress and availability in concert with what has been done

**Comment by edickens** [comment]
That is my understanding too.  It is for transcribers to volunteer to transcribe something else.  Perhaps we need different wording.

**Comment by Captainkirkdawson** [comment]
You have me totally lost. We are not saying the same thing at all.
This is nothing to do with transcribers. These are the researcher pages where they can see what work is underway and what may be remaining. It permits the researcher to volunteer BUT that is an add on

**Comment by edickens** [comment]
Understood.  In which case the "Volunteer" does not need to be against each Image Group but in the text with an explanation.  A link to the SC is need.

**Comment by Captainkirkdawson** [comment]
The yes is already a  link to either the SC or the VC depending on the status of the images. There is one on each line so we can determine which group they may be interested in

**Comment by edickens** [comment]
So the same could apply to a transcriber who fancied doing somewhere else in which they have an interest?

**Comment by SteveBiggs** [comment]
Eric, transcribers can look for and request available groups from other counties via the button under the Assignments action:
![image](https://user-images.githubusercontent.com/25303607/38049190-743a4364-32bf-11e8-9f64-5c6ef7059cff.png)

**Comment by PatReynolds** [comment]
Eric, I think some researchers will want to become a transcriber if they see a place they are interested in, and the ease of that first step (e.g. button in their field of view) is probably the best way of making sure they act on the impluse.  I'm not sure that capturing their name and email address is the most efficient way of moving them from impulse  to being a fully trained transcriber.  Maybe a simple link to the signup page? Maybe an intermediate page that explains that they need to sign up to the county, and then tell the coord that they are interested in the parish?
