### ISSUE TITLE
RAP - Review and evaluate the transcriptions

### ISSUE THREAD

**Issue by sean-wood** [FreeUKGen/MyopicVicar#958]

**Comment by edickens** [comment]
See #956  E

**Comment by richpomfret** [comment]
For @Captainkirkdawson to update the document.

**Comment by Captainkirkdawson** [comment]
I have totally forgotten what it was that I was going to write. Anyone can give me a hint????

**Comment by edickens** [comment]
This is to include routines in the Allocation system for the SC (or CC?) to review and evaluate the transcription before signing it off as done, or to mark it as needing to be checked, or to be done again.  It stays on the RAP until this is done  ED

**Comment by Captainkirkdawson** [comment]
This has been incorporated as part of the current image server software
