### ISSUE TITLE
Password working sometimes and not others

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#962]

**Comment by edickens** [comment]
I have had to help a number of people who say that their password did not work.  For example this one to the transcribers' group:-
Hi, I also have had this problem several times.  It seems that my password will be accepted some days but not others.  I have tried on numerous occasions to reset the password and got the same message you report.   (Invalid token.)  However the next day my original password will work or the reset will work.  I thought that I was possibly doing something wrong, but maybe there is a glitch. 
Christine  Harris

**Comment by Captainkirkdawson** [comment]
I am sorry but this type of issue statement is totally impossible to investigate. 
Specific example of who, where and when is required.

**Comment by edickens** [comment]
The transcribers group had at least three people who reported this
    problem.  But that seems to have stopped now.
    
    Could it have been while a rebuild was taking place?
    
    E
    
      On 28/09/2016 15:32, Kirk Dawson wrote:
    
    
      I am sorry but this type of issue statement is totally
        impossible to investigate. 
        Specific example of who, where and when is required.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #962: I am sorry but this type of issue statement is totally impossible to investigate. \nSpecific example of who, where and when is required."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/962#issuecomment-250184032"}}}

**Comment by Captainkirkdawson** [comment]
No point in speculating without information on who and when.

Propose no further action until an example is proided

**Comment by edickens** [comment]
These were all the emails.  BUT - I think people may get in a muddle
    when they try to use WinReg to log in which it cannot do.  There is
    also confusion with FR1, which I am trying to close down so that
    they cannot use the log in gateway that is there.  They also do not
    remember that they cannot use the "password token" more than once. 
    There have been no more messages on this subject since 23/09/2016.
    
    
    
    
    From Edwin Furnival:-
    
    Just to add.
    I also have had problems with my password. About a fortnight
      ago it wouldn't work, I tried several times. I tried changing it,
      the new one also wouldn't work. The next day the new one wouldn't
      work but the old one did and has done ever since. Weird!
    
    ----Original message----
    From : christineharris377@gmail.com
    Date : 23/09/2016 - 18:58 (GMTDT)
    To : freereg-transcribers@googlegroups.com
    Subject : Re: [Transcribers Group] logging in - invalid password
    token?
    
    Hi, I also have had this problem several times.  It
      seems that my password will be accepted some days but not others. 
      I have tried on numerous occasions to reset the password and got
      the same message you report.  However the next day my original
      password will work or the reset will work.  I thought that I was
      possibly doing something wrong, but maybe there is a glitch.  
    Christine
    
    On 23 Sep 2016 10:15 am, "June Spendlove" <june@sarco.co.uk> wrote:
    Help please!!
     
    Can anyone advise as to how I can log in to
      Freereg – I am asked for a password everywhere I try, as a new
      transcriber, to access help and I also notice I will need it when
      I upload a batch to FreeReg which I guess I do via the WinReg
      Server gateway. I have tried to reset the password numerous times
      but every time I get “Invalid password token” and I also get wrong
      password message when I try to access this group via the link on
      the emails, which takes me to Google groups. I have also followed
      the link which was sent me to change my password but again it
      keeps coming back with the invalid message.
     
    Any ideas what I am doing wrong?
     
    Thanks for reading.
     
    Regards
    June
     
    
    
    
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 29/09/2016 15:04, Kirk Dawson wrote:
    
    
      No point in speculating without information on who and when.
      Propose no further action until an example is proided
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #962: No point in speculating without information on who and when.\r\n\r\nPropose no further action until an example is proided"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/962#issuecomment-250475243"}}}

**Comment by Captainkirkdawson** [comment]
Not one of those reports tells me anything about their userid and the date and approximate time of the event without that minimum amount of information you detection is possible.
You may wish to tell transcriber to report the the issue if it happens again BUT they MUST report their userid and the day and time of the event.

**Comment by edickens** [comment]
Agreed.  I can get UserIDs for you from the names, but not the time
    of the event.  They need to use the "Contact Us" if they cannot log
    in and then that will be time marked.
    
    But I've heard no more since 23rd, so forget it.  Closed.
    
    E
    
      On 29/09/2016 16:20, Kirk Dawson wrote:
    
    
      Not one of those reports tells me anything about their userid
        and the date and approximate time of the event without that
        minimum amount of information you detection is possible.
        You may wish to tell transcriber to report the the issue if it
        happens again BUT they MUST report their userid and the day and
        time of the event.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #962: Not one of those reports tells me anything about their userid and the date and approximate time of the event without that minimum amount of information you detection is possible.\nYou may wish to tell transcriber to report the the issue if it happens again BUT they MUST report their userid and the day and time of the event."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/962#issuecomment-250498191"}}}
