### ISSUE TITLE
userid_details#create ActionController::InvalidAuthenticityToken

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#973]
[See this exception on Errbit]
https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/57fbabc0e937902c5f000000

**Comment by Captainkirkdawson** [comment]
There were 4 attempted registrations over 2 days (10/11 Oct)that failed due to this issue.
2 were from the same person. That person subsequently succeeded.
One did not follow through and an email followup has been requested of the coordinator.
The last person was our new Project Manager. He has subsequently successfully registered.
The only reason that I can see for these is a premature session timeout. 
Experience with Alison indicates that Refinery is using its own session timeout default which is 10 minutes. I have changed the default for refinery to 100 minutes.

**Comment by Captainkirkdawson** [comment]
Has not been observed since increasing refinery timeout from 10 to 100 minutes

**Comment by israelriibeiro** [comment]
Kirk, happend here too:

```
 curl -X POST -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-GB,en;q=0.5' -H 'Referer: http://localhost:3000/userid_details/transcriber_registration' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:49.0) Gecko/20100101 Firefox/49.0' http://localhost:3000/userid_details -d ''

Started POST "/userid_details" for ::1 at 2016-10-19 13:31:56 -0200
Processing by UseridDetailsController#create as HTML
Can't verify CSRF token authenticity
Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms)
** [Airbrake] Notice was not sent due to configuration:         
  Environment Monitored? false         
  API key set? true

ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):

```

**Comment by israelriibeiro** [comment]
@Captainkirkdawson , i did a research here. The only time that i could circumvent this situation is when i added this to controller:

```
skip_before_filter :verify_authenticity_token, only: [:create]
```

```
curl -X POST -H 'Accept-Language: en-GB,en;q=0.5' -H 'Referer: http://localhost:3000/userid_details/transcriber_registration'  http://localhost:3000/userid_details
<html><body>You are being <a href="http://localhost:3000/search_queries/new">redirected</a>.</body></html>%       

```

**Comment by Captainkirkdawson** [comment]
But that bypasses the whole purpose of forgery controls and on a create that seems most unwise
The user when starting the registration is given the token and is meant to give it back when taking the next action ie pressing create or send or whatever.

**Comment by israelriibeiro** [comment]
That's what i thought. How can i test this without using curl? I have to register userid_details#transcriber_registration and then do what?!

**Comment by Captainkirkdawson** [comment]
Israel
The process is as follows.
In the footer there is a link to "Become a transcriber" it takes you to the form
userid_details/transcriber_registration; the form is filled in and on selecting the Register Transcriber button we go to the 
https://github.com/FreeUKGen/MyopicVicar/blob/master/app/controllers/userid_details_controller.rb#L29-L44.
The system then sends a registration completion message.

**Comment by israelriibeiro** [comment]
Hi, @Captainkirkdawson . 
Using curl, which is not recommend, to test this, gave the problem. Look at what Jose Valim says here: 
[Jose Valim](https://github.com/plataformatec/devise/issues/779)
> If you have an web service, sign in should be done using HTTP Auth. If not, your option is to disable authenticity token on the session form, although not recommended.

With HTTP auth, everything goes ok. I think we should wait a little more in order to close this issue. If the problem doesn't show up again, your solution, Kirk, resolve the problem.

**Comment by Captainkirkdawson** [comment]
Agree we just monitor for the next while. TY for your input
