### ISSUE TITLE
Coordinator emergency contact As defined by #694

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#977]
We also have a slot for telephone number, but not many use this. The problem is, particularly with Coordinators, that if the email does not work we have completely lost contact. So rather than a telephone number, we need "Emergency contact information". This could be a telephone number, but it could be a relatives email address, or even a postal address. Just some means to contact them should we get no reply to an email.

**Comment by edickens** [comment]
This is not really #694 as it is in the Profile and not the Comment message system.  But I can see that it is all part of communication, although in this case with registered CC, SC and Transcribers and not Researchers.

**Comment by edickens** [comment]
Making someone's UserID Inactive has brought a response, but this is not a satisfactory way to "wake them up".  We created the field "Telephone number" as the emergency contact method.  I would like to call this something better and then get everyone, particularly Coordinators, to use it.  It does not need to be a telephone number, someone else's email, or a postal address would do.  It is a text field, so no programming is needed other than the field name, and a change to the Help.  E

**Comment by Captainkirkdawson** [comment]
What needs to be done? There are fields is it not a management issue not a system issue
