### ISSUE TITLE
Regular email verification

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#978]
Messages from the server bounce from time to time, but we do nothing about it. This is usually because the User has changed their ISP or put in a filter. As management we assume that they have got the message and do not know that it never got through. Messages getting through is most important for error messages when files are uploaded.
Either bouncing emails need to be sent to the SC so that they can take action, or as Pat suggests, say once a quarter, we email everyone and ask them to confirm that their email address is correct. If we get no reply within a week then their UserID should be disabled.

**Comment by Captainkirkdawson** [comment]
I am of the opinion that either the list manager or sender is the person responsible to taking what ever action is to be taken. If emails are sent through the freereg_contacts email address then you or Sandra must take action.
If I send the mail then I must act on bounces that come to me similarly for messages sent by others. When they receive  bounce they must act. 
Others may see automated system but I do not.

**Comment by edickens** [comment]
Agreed.  The next question is "What action should we take?".  If we
    do not have a back-up contact system, then how do we stop messages
    that will bounce being sent.  E  
    
      On 17/10/2016 22:05, Kirk Dawson wrote:
    
    
      I am of the opinion that either the list manager or sender is
        the person responsible to taking what ever action is to be
        taken. If emails are sent through the freereg_contacts email
        address then you or Sandra must take action.
        If I send the mail then I must act on bounces that come to me
        similarly for messages sent by others. When they receive bounce
        they must act. 
        Others may see automated system but I do not.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #978: I am of the opinion that either the list manager or sender is the person responsible to taking what ever action is to be taken. If emails are sent through the freereg_contacts email address then you or Sandra must take action.\nIf I send the mail then I must act on bounces that come to me similarly for messages sent by others. When they receive  bounce they must act. \nOthers may see automated system but I do not."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/978#issuecomment-254333935"}}}

**Comment by PatReynolds** [comment]
We need to have a way of marking invalid emails (I have a list from Sendgrid of the bouncers back in August, for example), so that they are not used in future.   If there is a way of uploading the list from Sendgrid to the system, without someone having to manually look up and mark each one, that would be ideal.

**Comment by Captainkirkdawson** [comment]
Requirement.

Add flag that email address is incorrect to userid collection
Add test to distribution selections so that emails are not sent to those people
Add to reset of email address on login if set
Write rake task to extract invalid email address from report
Get access to example of report
automate report extraction if possible

**Comment by edickens** [comment]
Good idea.  E
    
      On 18/10/2016 16:46, Kirk Dawson wrote:
    
    
      Requirement.
      Add flag that email address is incorrect to userid collection
        Add test to distribution selections so that emails are not sent
        to those people
        Add to reset of email address on login if set
        Write rake task to extract invalid email address from report
        Get access to example of report
        automate report extraction if possible
      
      
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #978: Requirement.\r\n\r\nAdd flag that email address is incorrect to userid collection\r\nAdd test to distribution selections so that emails are not sent to those people\r\nAdd to reset of email address on login if set\r\nWrite rake task to extract invalid email address from report\r\nGet access to example of report\r\nautomate report extraction if possible"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/978#issuecomment-254550193"}

**Comment by Captainkirkdawson** [comment]
Feature has been added. Confirmation days set at 120. Recent sign ups and new creations are not affected until after 120 days. All other people who log in need to confirm their email address as the default is set to false. 
989 will automated setting to false

**Comment by Captainkirkdawson** [comment]
Further development on hold pending common gateway

**Comment by Captainkirkdawson** [comment]
Implemented
