### ISSUE TITLE
Adds on mobile devices

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#979]
Currently it would seem that our adds which are banner adds are not displayed on mobile devices.

**Comment by Captainkirkdawson** [comment]
How does this relate to #820

**Comment by PatReynolds** [comment]
#820 may resolve

**Comment by richpomfret** [comment]
To explore use of Anchor/overlay ads.

**Comment by Captainkirkdawson** [comment]
Is this still relevant?

**Comment by smrr723** [comment]
See you've closed this @Captainkirkdawson but looked like a duplicate of #1455 anyway.

**Comment by Captainkirkdawson** [comment]
It was
