### ISSUE TITLE
WinFreeREG issues identified from usage

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#985]
Following wider usage, some improvements are needed

**Comment by edickens** [comment]
These are the issues reported to me by Steve Biggs

1. The Fiche and the Image information does not automatically insert itself from last record
2. Don't like that it doesn't enter Register increment automatically
3. Not having a working down arrow to open next line is a draw back
4. When a new line is opened, the first cell is not active, so you have to double-click with mouse, which is a pain.
5. The edit box is small making it difficult to see what you are entering - especially in the Notes
6. Don't like removal of colour backgrounds, the pink was always a reminder to save
7. Capital letters are only possible on the first word in Notes. For example a name will appear as thomas bowker if within a note
8. I am used to saving with Ctrl S every few records. Don't think that works with this program so have to click on the save icon.
9. As an older person with poor sight I would  prefer larger text if that was possible.
10. At the end of a file I always sort by date to make sure the date range is sensible and no obvious year typos.  Now however the date column sorts by day then month then year so not a lot of help to spot an error.
11. If you have made an error and not changed say 'Image Nr' over several entries, I would normally type in first cell correct number and CTL C and CTL V to change several cells at once, can't do in latest.

Same from Peter Rolison
1. Automatically backup existing file as editing begins, to provide a recovery position if required.
2. Add a "Save As" option that permits the current file to be saved somewhere different to where it was read from
3. Replicate dates from previous record to give a starting point for the new record

**Comment by Sherlock21** [comment]
one comment on your list if i may:

On 22 Oct 2016, at 10:37, Eric Dickens <notifications@github.com> wrote:

> These are the issues reported to me by Steve Biggs
> 
> The Fiche and the Image information does not automatically insert itself from last record
> Don't like that it doesn't enter Register increment automatically
	it may not always nbe correect ot increment next line automatically

what about the Register haveing several childen all on one baptism line in the Register?
what about the Scribe who could cont when going from one page to the next and missing a hundred out?
that about the practice of numbering starts again every fresh year? 
etc.
	
> Not having a working down arrow to open next line is a draw back
> When a new line is opened, the first cell is not active, so you have to double-click with mouse, which is a pain.
> The edit box is small making it difficult to see what you are entering - especially in the Notes
> Don't like removal of colour backgrounds, the pink was always a reminder to save
> Capital letters are only possible on the first word in Notes. For example a name will appear as thomas bowker if within a note
> I am used to saving with Ctrl S every few records. Don't think that works with this program so have to click on the save icon.
> As an older person with poor sight I would prefer larger text if that was possible.
> At the end of a file I always sort by date to make sure the date range is sensible and no obvious year typos. Now however the date column sorts by day then month then year so not a lot of help to spot an error.
	Why do this? the source register is often not in date order. Often, there are late additions, say a few weeks before tha last date done. So does this auto sort imply that one cannot enter a record with an earlier date than that just put in?

For back checking of a set of transcriptions  file from WinFreeReg needs to be exactly in the sequence of the original Register surely.
Eric B

**Comment by EmJayFry** [comment]
Current status (18 Nov 2016)
' DONE:  1. The Fiche and the Image information does not automatically insert itself from last record
' DONE:  2. Don't like that it doesn't enter Register increment automatically
' DONE:  3. Not having a working down arrow to open next line is a draw back
' TODO:  4. When a new line is opened, the first cell is not active, so you have to double-click with mouse, which is a pain.
' DONE:  5. The edit box is small making it difficult to see what you are entering - especially in the Notes
' DONE:  6. Don't like removal of colour backgrounds, the pink was always a reminder to save
' TODO:  7. Capital letters are only possible on the first word in Notes. For example a name will appear as thomas bowker if within a note
' DONE:  8. I am used to saving with Ctrl S every few records. Don't think that works with this program so have to click on the save icon.
' DONE:  9. As an older person with poor sight I would  prefer larger text if that was possible.
' DONE: 10. At the end of a file I always sort by date to make sure the date range is sensible and no obvious year typos.  Now however the date column sorts by day then month then year so not a lot of help to spot an error.
' TODO: 11. If you have made an error and not changed say 'Image Nr' over several entries, I would normally type in first cell correct number and CTL C and CTL V to change several cells at once, can't do in latest.
' TODO: 12. Automatically backup existing file as editing begins, to provide a recovery position if required.
' TODO: 13. Add a "Save As" option that permits the current file to be saved somewhere different to where it was read from
' DONE: 14. Replicate dates from previous record to give a starting point for the new record
