### ISSUE TITLE
Extra "Child of" options for burials

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#988]

**Comment by edickens** [comment]
From a transcriber
'Child of' - in the relationship column on the Burials sheets. Is it possible to introduce a further choice of 'child of'?  The reason for this is that in records that are written in Latin the relationship is frequently (mostly!) written as 'fil'; which could be an abbreviation for filius or filia. Of course 99.9% of the time the name will indicate which it is but I have been told that that is for the researcher, not me, to decide upon. Hence I have always stuck rigidly to the rule that an entry is only to be made in that column if the sex is specifically stated (as is also the case with baptisms). At present I enter nothing at all if it says 'fil' but this could lead to researchers sometimes not being certain on whether it is a child or a wife that is being recorded. I could, and sometimes do, record the fact in the notes column but it would be easier just to click.

**Comment by Sherlock21** [comment]
I do not see any issue with just typing in Child Of in these circumstances.

But if on WinReg, would it have to be in the WinReg tables? if so by whom?

**Comment by Sherlock21** [comment]
A related thought also just occurred to me as I transcribed such a 1674 burial.
the record says: A child of Thomas Cocks of the town buryed the 17 September.

SO the relationship field needs to take: A child of
And the surname should be entered as Cock. Not Cocks since the terminal s is not part of the name, but is the correct grammar ( for once!)

**Comment by Captainkirkdawson** [comment]
As noted in #1009 by @SteveBiggs 
You can add other options for the relationship in a burial via 'Settings'->'Lookup Tables'->'Burial Relationships' (I have used "cousin of")
FR supports this form of input

**Comment by benwbrum** [comment]
This appears to be adequately supported in WinREG
