### ISSUE TITLE
Bounced emails set invalid email address flag

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#989]
Write rake task to extract invalid email address from report
Get access to example of report
automate report extraction if possible

**Comment by Captainkirkdawson** [comment]
Require access to sendgrid bounce information

**Comment by Captainkirkdawson** [comment]
Need to implement sendgrid api

**Comment by Captainkirkdawson** [comment]
In mean time have activated forward bounces to sender

**Comment by AlexAvlonitis** [comment]
hello @Captainkirkdawson , could you please give me some more information about this task. Do we need a report for all failed attempts to emails (where the email is invalid)? Are we using sendgrid at the moment, or it's something that we want. if we use it, can i please have some information about the login details and if you currently use their API, to use the same keys to create the rake task.

**Comment by Captainkirkdawson** [comment]
Will have to wait till I get a better connection in 3 days in Chile. This place is impossible

**Comment by Captainkirkdawson** [comment]
We are currently using sendgrid to distribute our emails. It reports on bounced and other problems with emails. It keeps that information for 1 week.
Lemon set up the service and can give you access.
Idea was that we run a nightly review of the report and when there is a bounce we set the invalid email flag in the userid

**Comment by edickens** [comment]
But Mick Claxton LIN SC is being bounced at present.  To make an SC
    inactive would be bad.  But if the bounce is because the email
    address does not exist, rather than by SpamCop, then that is the
    time to make them Inactive.  E
    
    On 12/12/2016 21:48, Kirk Dawson wrote:
    
    
      We are currently using sendgrid to distribute our emails. It
        reports on bounced and other problems with emails. It keeps that
        information for 1 week.
        Lemon set up the service and can give you access.
        Idea was that we run a nightly review of the report and when
        there is a bounce we set the invalid email flag in the userid
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #989: We are currently using sendgrid to distribute our emails. It reports on bounced and other problems with emails. It keeps that information for 1 week.\nLemon set up the service and can give you access.\nIdea was that we run a nightly review of the report and when there is a bounce we set the invalid email flag in the userid"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/989#issuecomment-266563275"}}}

**Comment by edickens** [comment]
If this has been deployed to production it is not working.
On 20/04/2017 at 12:05 an email to <distar@home.3b.co.uk> UserID Dinahst was bounced by SpamCop.  But her Profile is still active and her registration completed.  She registered on 19 January 2014.

**Comment by Captainkirkdawson** [comment]
It is not in production. It is not even in test. It is in progress. It is likely several weeks from deployment,

As I said on todays scrum. We plan to produce an initial report on which Userid we would declare invalid for you and Steve to look at first before we start to do it also ask for a report to go to SCs that has to be developed.

**Comment by Captainkirkdawson** [comment]
System Administrators will have received the first test of a dry run of a bounced email system on test3.

The bounced emails are real but were checked against test3 userids so not an up to date collection.

The sytem will make the userid email address invalid with the stated reason. when enabled

The system will send the SC an email with the information when enabled

The log of all issues is being sent to system administrators
