### ISSUE TITLE
Do not send to invalid email addresses

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#990]

**Comment by Captainkirkdawson** [comment]
Add test to distribution selections so that emails are not sent to those people

**Comment by Captainkirkdawson** [comment]
Dependant on deployment of 989 and 978

**Comment by israelriibeiro** [comment]
I never test it, but we could use this: 

https://github.com/kamilc/email_verifier

It connects to the smtp server and check if the email exists. It's like doing this, i think:

https://www.webdigi.co.uk/blog/2009/how-to-check-if-an-email-address-exists-without-sending-an-email/

**Comment by Captainkirkdawson** [comment]
Israel's suggestion should be investigated as part of the common gateway

The send messages action still needs to perform this check even with a common gateway
