### ISSUE TITLE
FreeREG Update Processing Report

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#991]

**Comment by edickens** [comment]
For two days now I have not received this report.  Is there a problem?  E

**Comment by Sherlock21** [comment]
Now you mention it, nor have I.

ericb

**Comment by Captainkirkdawson** [comment]
The overnight process crashed on each of the past 3 nights. A problem file has been detected which should have been caught but was not. Investigating.

**Comment by Captainkirkdawson** [comment]
Problem caused by a file header with record_type  of BAPTIMS putting in trap; file deleted in interim

**Comment by Captainkirkdawson** [comment]
Trap existed but in trying to ensure that there were no other header errors we continued processing and barfed when getting default record field order. Need second trap
