### ISSUE TITLE
Inform Managers of nightly process failure

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#993]
Every night we run a cron task that does many things. Occasionally it fails to complete correctly.
Usually it is not noticed until someone starts complaining that their file was not processed or a report was not received.
There is a requirement for the cron task to send a message to system administrators that it has failed to complete correctly. This way action can be taken earlier

**Comment by edickens** [comment]
And also should there be no files to process, unless it already does, 
because I have not seen this situation yet.  However it will happen next 
week.

**Comment by richpomfret** [comment]
To assign to Chee once he starts with us.

**Comment by Captainkirkdawson** [comment]
Since there are no nightly updates in the  system this is irrelevant now

**Comment by richpomfret** [comment]
Not applicable. Shall close.
