### ISSUE TITLE
[refinery/county_pages/admin/county_pages#update] RuntimeError: Please override county_page_params with your desired parameter security.

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#994]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/580947c3e93790fde4000000)

**Comment by Captainkirkdawson** [comment]
Suggestion is that the county pages engine bundle should be updated

**Comment by Captainkirkdawson** [comment]
County pages need to be updated due to genuki link changes

**Comment by Captainkirkdawson** [comment]
In dicsussions with Ben on best long term solution

**Comment by Captainkirkdawson** [comment]
Fixed

**Comment by Captainkirkdawson** [comment]
@AlOneill please test

**Comment by AlOneill** [comment]
Have successfully edited the first 5 pages of County info on production.

**Comment by Captainkirkdawson** [comment]
Great

**Comment by Captainkirkdawson** [comment]
My Christmas present!!!!

**Comment by AlOneill** [comment]
GenUKI links on county pages updated as far as possible: 2 counties, Cornwall and East Lothian, have non-standard urls still because the GenUKI "standard" urls don't work for now.

Have added a note to my TODO list to check on these 2 links periodically ...

**Comment by Sherlock21** [comment]
Please advise me of what you refer to as "GenUKI Standard urls don't work for now" please.
with an example of one, if you don't mind please.

if its to do with the bit about Location navigation, then I ought to be in the loop.

if its not, then its a bit of an ambiguous phrase.
EB

**Comment by AlOneill** [comment]
@Sherlock21 
A "standard" GenUKI county  url  for Cornwall *would* be this:
http://www.genuki.org.uk/big/eng/CON/ 
but that does not work. Instead, the url for Cornwall is:
http://www.genuki.org.uk/big/eng/Cornwall 

Something similar applies to the url for East Lothian. I hope that answers your question.

**Comment by Sherlock21** [comment]
Thank you.
I had never noticed that link existed! too tiny in the pale green font.
