### ISSUE TITLE
Set a default process overnight on upload

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#995]
Users must currently select either Process ASAP or Overnight after uploading.
If they do not hit the process button the file will sit for ever.
Requirement is to set a default of process overnight which would be overridden if process asap is processed

**Comment by edickens** [comment]
Great idea.  Does this mean that they HAVE to process one way or
    another?
    
    Have just done an experiment.  I selected a file to Replace.  But
    having said Upload and got the screen to select "Overnight" I
    changed my mind and decided to selected "Your Actions".  The file is
    now in the Unprocessed and yet I never pressed the process button. 
    If you want to check it is :-
    
    
    
    So if they exit the screen without pressing "Process" then the file
    should be deleted from the "Unprocessed".
    
    OR, just do not upload the file until "Process" is selected.
    
    E
    
    On 28/10/2016 18:08, Kirk Dawson wrote:
    
      Users must currently select either Process ASAP or Overnight
        after uploading.
        If they do not hit the process button the file will sit for
        ever.
        Requirement is to set a default of process overnight which would
        be overridden if process asap is processed

**Comment by Captainkirkdawson** [comment]
Your experiment is what I would expect to happen. The processing is not scheduled UNLESS the process button is clicked. Selecting an option does not do it

**Comment by Sherlock21** [comment]
I had been out of contact yesterday - but trying to catch up now.

My view is: when someone UPLOADS a file, they intend it to get processed into the database - else they would not have uploaded it
there is a check already that its the same number if its a REPLACE, so that base is covered. 
and if its a new file then if its a mistake, these is only the one to be deleted with no harm done about over writing the earlier version.

SO its a clear cut decision: set the program to Process  overnight by Default ( unless the uploaded picks Process asap.)

If the Processor fails, what happens to all "today's " collection in these circumstances? even the ones that for abandoned in the failed process? These need picking up don't they.

**Comment by Sherlock21** [comment]
PS - but don't go processing all these 2000+ ones just jet - I will have a random check on a few as soon as i can.

**Comment by Captainkirkdawson** [comment]
This story is to simply stop  the bypassing of the processing step nothing to do with cleanup
I think what I will do is just eliminate the step. A user uploads. If they are trainee they are just checked. If it can be processed ASAP it will be otherwise it gets queued automatically

**Comment by Captainkirkdawson** [comment]
This story is to simply stop  the bypassing of the processing step nothing to do with cleanup
I think what I will do is just eliminate the step. A user uploads. If they are trainee they are just checked. If it can be processed ASAP it will be otherwise it gets queued automatically

**Comment by Sherlock21** [comment]
Does this amount then to
step 1) upload file
step 2) select Process asap if its offered
step 3) hit Confirm to process.

or step 1) upload.

IF its small enough then offer ASAP or overnight
then just goes as selected there with no further action by the uploader

IF its too big for ASAP then don't offer it and Put in Overnight processing list and uploaded dopes not see it again?

What does the email say back to the uploaded in each case?

PS I like the idea but I just need to understand the steps I am agreeing to!

**Comment by Captainkirkdawson** [comment]
Neither

Upload/replace

If file small enough goes to ASAP; if too big goes to Overnight. 
Message after upload tells you want is happening to file

Test it out now on test3

**Comment by edickens** [comment]
Not too happy with that.

I selected RL, found the file with Browse, hit "Replace" and it very 
quickly went back to the list of batches, with a message to say that the 
file is being processed.

I think I would like an "Are you sure?".  It is then that you can do the 
upload and start processing.

My file processed immediately and I have the email.  But if the file is 
set for overnight processing, will the message on the batches screen say 
that it is waiting for overnight processing?  With no selection you will 
not know what the server has selected.

It would be better still if the batch in the batch list could have a new 
colour to show that it is waiting for (overnight) processing. This 
should perhaps stop the person uploading again before the file had been 
processed.

But I do like the idea of not having to choose and confirm the type of 
processing.

E

**Comment by edickens** [comment]
PS.  I think the "Browse" screen should explain what will happen. That 
is to say that the server will select now or overnight depending on the 
file size.  And that "Replace" will also start the processing.  Perhaps 
"Replace" should say "Replace now".

You do have an "Are you sure" screen, which should be enough.

But perhaps this is just because it is a change that it surprised me how 
easy and quick it was.

E

**Comment by Sherlock21** [comment]
I go along with Eric D's suggestion to have the on screen progress message in BOLD RED. That's an added warning that things are different.

**Comment by Captainkirkdawson** [comment]
Mutter mutter mutter thought they would be happy to eliminate steps and simplify process mutter mutter mutter
On replace there is a confirmation of action requirement. 
Could add a comment on the actual upload/replace page that process now moves directly to submission. That could be in colour.
Do not agree that the information message should be in red that is for errors and this is not an error

**Comment by edickens** [comment]
Agreed Kirk.
    
    My original comment was really because it came as a surprise how
    quickly I returned to the list of batches.  EricB only wanted it in
    Red, because, like me, he did not see the confirmation at the top. 
    In fact, is this the correct place?  Most system responses such as
    "the update was successful" are just above the data box and not
    above the descriptions.
    
    I think a bit of an explanation on the upload/replace "browse" page
    would be a good idea.  Mainly for existing users who will be
    surprised - like us!
    
    E
    
    On 30/10/2016 14:40, Kirk Dawson wrote:
    
    
      Mutter mutter mutter thought they would be happy to eliminate
        steps and simplify process mutter mutter mutter
        On replace there is a confirmation of action requirement. 
        Could add a comment on the actual upload/replace page that
        process now moves directly to submission. That could be in
        colour.
        Do not agree that the information message should be in red that
        is for errors and this is not an error
      
      
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #995: Mutter mutter mutter thought they would be happy to eliminate steps and simplify process mutter mutter mutter\r\nOn replace there is a confirmation of action requirement. \r\nCould add a comment on the actual upload/replace page that process now moves directly to submission. That could be in colour.\r\nDo not agree that the information message should be in red that is for errors and this is not an error"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/995#issuecomment-257154879"}}}

**Comment by Captainkirkdawson** [comment]
Please review what is on test3 in the form of messaging

**Comment by richpomfret** [comment]
Will require a message to let users know.

**Comment by edickens** [comment]
I cannot put a notice out about this until I know that Spamcop is no 
longer black-listing us.  Otherwise I will get back 200 undelivered 
emails.  I cannot use the transcribers mailgroup because not everyone 
subscribes to this.

BUT this notice has to go out before the server comes back online to 
transcribers otherwise we will get loads of messages asking about what 
has happened.

I wait to hear when we are clear with Spamcop.

E
