### ISSUE TITLE
Check if a more recent file is to be overwritten

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#996]

**Comment by edickens** [comment]
Only if it is possible, introduce an "Are you sure" if the date of creation of a file about to be uploaded is older than the version on the server.  This also to apply to any "Replace" option.

**Comment by Captainkirkdawson** [comment]
How would one know?

**Comment by Sherlock21** [comment]
On a quick check, 
although the online page of “Files not Processed", says: 2180 files, when I download them there are only 501.

There are  120 of these which are dated between 8 September 2015 and 30 Dec 2015
and the remaining 381 are all this year (2016).
So where are the rest please? and what happened on 8th Sept 2015 to give this start date?

**Comment by edickens** [comment]
I'm not sure what dates you keep.
    
    But for a Replace (or Process in the Unprocessed files list) there
    must (may) be a file already in the system and if its uploaded date
    is more recent than the created date on the transcriber's computer
    from which the file is coming, then it should not overwrite the file
    on the server.
    
    For example, say I had an old file on my computer dated 15 January
    2016 and there is a file on the server which was uploaded 25 June
    2016, then my file should not be processed.  To get it processed I
    would need to check then amend the file on my computer to get
    today's date and then it would work.  This situation can happen if a
    SC has uploaded a file of the same name into a transcriber's
    UserID.  But perhaps it should then be locked?
    
    E
    _____________________________________
Eric J Dickens
FreeREG Chairman
    On 29/10/2016 00:15, Kirk Dawson wrote:
    
    
      How would one know?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #996: How would one know?"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/996#issuecomment-257050522"}}}

**Comment by Captainkirkdawson** [comment]
We had such a test in the processor in its initial version but it was eliminated.

**Comment by edickens** [comment]
This would be very useful to clear the "Unprocessed list".  E
    
      On 29/10/2016 15:46, Kirk Dawson wrote:
    
    
      We had such a test in the processor in its initial version but
        it was eliminated.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #996: We had such a test in the processor in its initial version but it was eliminated.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/996#issuecomment-257095493"}}}

**Comment by Captainkirkdawson** [comment]
2 different requests. 1) don't upload if older 2)don't process if older

**Comment by edickens** [comment]
Yes.  E
    
      On 29/10/2016 17:56, Kirk Dawson wrote:
    
    
      2 different requests. 1) don't upload if older 2)don't process
        if older
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #996: 2 different requests. 1) don't upload if older 2)don't process if older"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/996#issuecomment-257102653"}}}

**Comment by Captainkirkdawson** [comment]
For 1) I know of no way of accessing the creation/modification information on a file on the users computer. An uploaded/replaced file has the date we created it.  2) In light of 1) the replaced file will always be newer which is why we dropped the test in the processor.  The only situation where this could work is if we are reprocessing an existing  file that somehow got into the system that is older than the processed file.

**Comment by edickens** [comment]
Kirk,
    
    Suggest close this.  Not worth any programming effort.
    
    E
    
      On 29/10/2016 22:32, Kirk Dawson wrote:
    
    
      For 1) I know of no way of accessing the creation/modification
        information on a file on the users computer. An
        uploaded/replaced file has the date we created it. 2) In light
        of 1) the replaced file will always be newer which is why we
        dropped the test in the processor. The only situation where this
        could work is if we are reprocessing an existing file that
        somehow got into the system that is older than the processed
        file.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #996: For 1) I know of no way of accessing the creation/modification information on a file on the users computer. An uploaded/replaced file has the date we created it.  2) In light of 1) the replaced file will always be newer which is why we dropped the test in the processor.  The only situation where this could work is if we are reprocessing an existing  file that somehow got into the system that is older than the processed file."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/996#issuecomment-257117257"}}}
