### ISSUE TITLE
Transcribers not READING management messages

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#997]

**Comment by edickens** [comment]
I have heard that some transcribers say that they did not get the message about tomorrow's shutdown.
I have investigated, and they did, but they did not read it amongst the mass of emails that they get.
So, we need to make the Subject line more prominent if it is a serious issue.  Or we need to automatically start the Subject line with something that shows that it a message from the server and not just sent through the transcribers' mailgroup.

**Comment by edickens** [comment]
I'm not surprised now that many transcribers have not heard of the shutdown, because I'm getting dozens of bounced emails.  They would have tried to deliver for 24 hours and are now giving up.  Here are some of the reasons:-
Diagnostic-Code: 550 mail not accepted from blacklisted IP address, see: http://spamcop.net/bl.shtml [167.89.100.237] 
Diagnostic-Code: 550 "JunkMail rejected - o1.24nn.shared.sendgrid.net [167.89.100.237]:30010 is in an RBL, see Blocked - see http://www.spamcop.net/bl.shtml?167.89.100.237" 
Diagnostic-Code: 550  mx8.tb.ukmail.iss.as9143.net bizsmtp Connection rejected. Your IP 167.89.100.237 is in RBL. Please see https://www.spamcop.net/bl.shtml?167.89.100.237
I hope  that I'm not going to get all 1,500 back.  E

**Comment by richpomfret** [comment]
Will be fixed as part of another task.
