### ISSUE TITLE
Where do unprocessed physical file entries come from?

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#998]
When a batch is removed by a manager for a userid the physical file information for the userid is not amended. 
Requirement is to delete the entry in physical files for the userid
Also need to clean up the collection

**Comment by edickens** [comment]
This could account for many of the files.  Particularly STS.  E

**Comment by Captainkirkdawson** [comment]
Speculation was unfounded. No issue detected. Need to research on actual event

**Comment by Captainkirkdawson** [comment]
As of 12 Dec there were 31 entries. The only recent addition was for STSBIDBA50.CSV from caroline which was uploaded on Dec10 at 23;54

**Comment by Captainkirkdawson** [comment]
There are occasional processing errors that result in these additions.

Propose to close
